{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"device","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Other device name"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"User login at other device"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}],"role":"symbol","title":"onUserLoginOtherDevice(device:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener(im)onUserLoginOtherDeviceWithDevice:","required":true,"modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener/onUserLoginOtherDevice(device:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}],"role":"symbol","title":"onUserLoginOtherDevice(device:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLoginOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"device"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"User login at other device"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener\/onUserLoginOtherDevice(device:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/userstatechangedlistener\/onuserloginotherdevice(device:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener":{"role":"symbol","title":"UserStateChangedListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}],"url":"\/documentation\/easechatuikit\/userstatechangedlistener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"device"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/title","value":"onUserLoginOtherDeviceWithDevice:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener~1onUserLoginOtherDevice(device:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLoginOtherDeviceWithDevice:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}