{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/userstatechangedlistener\/onusertokendidexpired()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/userstatechangedlistener\/onusertokendidexpired()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener\/onUserTokenDidExpired()"},"kind":"symbol","abstract":[{"type":"text","text":"User token expired,when you need to fetch chat token  re-login."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onUserTokenDidExpired"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserTokenDidExpired","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener(im)onUserTokenDidExpired","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"onUserTokenDidExpired","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"roleHeading":"Instance Method","title":"onUserTokenDidExpired()"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserStateChangedListener","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/userstatechangedlistener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","abstract":[],"type":"topic","title":"UserStateChangedListener","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener/onUserTokenDidExpired()":{"title":"onUserTokenDidExpired()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onUserTokenDidExpired","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/easechatuikit\/userstatechangedlistener\/onusertokendidexpired()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener\/onUserTokenDidExpired()","kind":"symbol","abstract":[{"text":"User token expired,when you need to fetch chat token  re-login.","type":"text"}],"required":true,"type":"topic","navigatorTitle":[{"text":"onUserTokenDidExpired","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"onUserTokenDidExpired","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"onUserTokenDidExpired","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onUserTokenDidExpired","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/fragments","value":[{"text":"UserStateChangedListener","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/title","value":"onUserTokenDidExpired"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserTokenDidExpired"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener~1onUserTokenDidExpired()\/fragments"}]}]}