{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"userDidForbidden()","externalID":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener(im)userDidForbidden","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userDidForbidden","kind":"identifier"},{"kind":"text","text":"()"}],"required":true,"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"userDidForbidden"}],"modules":[{"name":"EaseChatUIKit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener"]]},"abstract":[{"text":"The method called on user did forbid by server.","type":"text"}],"variants":[{"paths":["\/documentation\/easechatuikit\/userstatechangedlistener\/userdidforbidden()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/userstatechangedlistener\/userdidforbidden()"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userDidForbidden","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener\/userDidForbidden()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserStateChangedListener"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/userstatechangedlistener","role":"symbol","title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener/userDidForbidden()":{"url":"\/documentation\/easechatuikit\/userstatechangedlistener\/userdidforbidden()","title":"userDidForbidden()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userDidForbidden"},{"text":"()","kind":"text"}],"required":true,"role":"symbol","abstract":[{"type":"text","text":"The method called on user did forbid by server."}],"navigatorTitle":[{"kind":"identifier","text":"userDidForbidden"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener\/userDidForbidden()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"userDidForbidden"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"userDidForbidden","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"userDidForbidden"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/title","op":"replace","value":"UserStateChangedListener"},{"value":[{"text":"UserStateChangedListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"UserStateChangedListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener~1userDidForbidden()\/title","op":"replace","value":"userDidForbidden"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener~1userDidForbidden()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userDidForbidden","kind":"identifier"}]}]}]}