{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recordIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RippleButton","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RippleButton","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)RippleButton"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageaudiorecordview\/recordicon"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAudioRecordView\/recordIcon"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"recordIcon","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)RippleButton","text":"RippleButton"}],"role":"symbol","title":"recordIcon","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit22MessageAudioRecordViewC10recordIconAA12RippleButtonCvp"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAudioRecordView"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/RippleButton":{"role":"symbol","url":"\/documentation\/easechatuikit\/ripplebutton","title":"RippleButton","navigatorTitle":[{"text":"RippleButton","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RippleButton","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RippleButton","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAudioRecordView/recordIcon":{"role":"symbol","url":"\/documentation\/easechatuikit\/messageaudiorecordview\/recordicon","title":"recordIcon","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAudioRecordView\/recordIcon","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recordIcon"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)RippleButton","kind":"typeIdentifier","text":"RippleButton"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAudioRecordView":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAudioRecordView"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAudioRecordView","kind":"symbol","url":"\/documentation\/easechatuikit\/messageaudiorecordview","role":"symbol","navigatorTitle":[{"text":"MessageAudioRecordView","kind":"identifier"}],"title":"MessageAudioRecordView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1RippleButton\/title","op":"replace","value":"RippleButton"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1RippleButton\/fragments","value":[{"kind":"identifier","text":"RippleButton"}],"op":"replace"},{"value":"MessageAudioRecordView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAudioRecordView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MessageAudioRecordView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAudioRecordView\/fragments","op":"replace"}]}]}