{"metadata":{"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewController(im)createContactList","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"createContactList"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createContactList","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"ContactView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactView"}],"title":"createContactList()"},"abstract":[{"type":"text","text":"Creates a contact list view."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/createContactList()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/createcontactlist()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/createcontactlist()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createContactList","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactView","text":"ContactView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"A ","type":"text"},{"code":"ContactView","type":"codeVoice"},{"type":"text","text":" instance."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController/createContactList()":{"navigatorTitle":[{"kind":"identifier","text":"createContactList"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/createContactList()","kind":"symbol","role":"symbol","title":"createContactList()","url":"\/documentation\/easechatuikit\/contactviewcontroller\/createcontactlist()","type":"topic","abstract":[{"text":"Creates a contact list view.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createContactList","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"ContactView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactView","kind":"typeIdentifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactviewcontroller","type":"topic","role":"symbol","title":"ContactViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController","abstract":[],"navigatorTitle":[{"text":"ContactViewController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView":{"title":"ContactView","url":"\/documentation\/easechatuikit\/contactview","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactView"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"createContactList"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createContactList"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"ContactView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"createContactList","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"createContactList","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1createContactList()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1createContactList()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createContactList","kind":"identifier"}]},{"value":"ContactViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/title","op":"replace"},{"value":[{"text":"ContactViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/title","value":"ContactView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/fragments","op":"replace","value":[{"text":"ContactView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}