{"kind":"symbol","abstract":[{"code":"ContactListController","type":"codeVoice"},{"type":"text","text":" init method.Only available in Objective-C language."}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/init(headerStyle:ignoreIds:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithHeaderStyle:ignoreIds:) "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headerStyle"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","kind":"typeIdentifier","text":"ContactListHeaderStyle"},{"kind":"text","text":" = .contact, "},{"text":"ignoreIds","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"] = [])"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","type":"reference","isActive":true}]}],"name":"headerStyle"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of contact ids that already exist in the group."}]}],"name":"ignoreIds"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/init(headerstyle:ignoreids:)"]},{"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/init(headerstyle:ignoreids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"init(headerStyle:ignoreIds:)","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"headerStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContactListHeaderStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ignoreIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithHeaderStyle:ignoreIds:","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewController(im)initWithHeaderStyle:ignoreIds:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle":{"navigatorTitle":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"title":"ContactListHeaderStyle","url":"\/documentation\/easechatuikit\/contactlistheaderstyle","abstract":[{"type":"text","text":"The header display style of the "},{"type":"codeVoice","code":"ContactList"},{"type":"text","text":"."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListHeaderStyle"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController":{"role":"symbol","title":"ContactViewController","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ContactViewController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController/init(headerStyle:ignoreIds:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headerStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","kind":"typeIdentifier","text":"ContactListHeaderStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ignoreIds"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/init(headerStyle:ignoreIds:)","url":"\/documentation\/easechatuikit\/contactviewcontroller\/init(headerstyle:ignoreids:)","type":"topic","abstract":[{"code":"ContactListController","type":"codeVoice"},{"type":"text","text":" init method.Only available in Objective-C language."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithHeaderStyle:ignoreIds:"}],"title":"init(headerStyle:ignoreIds:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithHeaderStyle:ignoreIds:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithHeaderStyle:ignoreIds:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithHeaderStyle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","text":"ContactListHeaderStyle"},{"text":") ","kind":"text"},{"text":"headerStyle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreIds:"},{"kind":"text","text":"("},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"ignoreIds","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"headerStyle","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","isActive":true}],"type":"paragraph"}]},{"name":"ignoreIds","content":[{"inlineContent":[{"text":"Array of contact ids that already exist in the group.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/title","value":"ContactListHeaderStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderStyle"}]},{"value":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/title","op":"replace","value":"ContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/fragments","value":[{"kind":"identifier","text":"ContactViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ContactViewController"}],"op":"replace"},{"value":"initWithHeaderStyle:ignoreIds:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1init(headerStyle:ignoreIds:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithHeaderStyle:ignoreIds:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1init(headerStyle:ignoreIds:)\/fragments"}]}]}