{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/navigation"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"text":"EaseChatNavigationBar","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewController(py)navigation","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigation"},{"kind":"text","text":": "},{"text":"EaseChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"}],"title":"navigation","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"navigation"}],"modules":[{"name":"EaseChatUIKit"}]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/navigation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/navigation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactviewcontroller","type":"topic","role":"symbol","title":"ContactViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController","abstract":[],"navigatorTitle":[{"text":"ContactViewController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EaseChatNavigationBar","kind":"identifier"}],"navigatorTitle":[{"text":"EaseChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the EaseChatUIKit."}],"kind":"symbol","title":"EaseChatNavigationBar","url":"\/documentation\/easechatuikit\/easechatnavigationbar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController/navigation":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/navigation","kind":"symbol","title":"navigation","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"text":"EaseChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/contactviewcontroller\/navigation","navigatorTitle":[{"kind":"identifier","text":"navigation"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"navigation","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"navigation"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","text":"EaseChatNavigationBar","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"navigation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/title","op":"replace","value":"ContactViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/fragments","value":[{"kind":"identifier","text":"ContactViewController"}]},{"op":"replace","value":"EaseChatNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/title"},{"op":"replace","value":[{"text":"EaseChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/fragments"},{"value":"navigation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1navigation\/title"},{"value":[{"text":"navigation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1navigation\/fragments"}]}]}