{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/switchTheme(style:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController"]]},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","modules":[{"name":"EaseChatUIKit"}]},"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/themeswitchprotocol-implementations"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController":{"title":"ContactViewController","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/contactviewcontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController","navigatorTitle":[{"kind":"identifier","text":"ContactViewController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController/switchTheme(style:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/switchTheme(style:)","kind":"symbol","title":"switchTheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"text":" to switch theme.","type":"text"}],"url":"\/documentation\/easechatuikit\/contactviewcontroller\/switchtheme(style:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/switchTheme(style:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/title","value":"ContactViewController","op":"replace"},{"op":"replace","value":[{"text":"ContactViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1switchTheme(style:)\/title","op":"replace","value":"switchThemeWithStyle:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1switchTheme(style:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchThemeWithStyle:"}]}]}]}