{"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/viewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactviewcontroller\/viewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"viewModel","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewController(py)viewModel","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viewModel","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel","text":"ContactViewModel","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"viewModel","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/viewModel","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viewModel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactViewModel","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController/viewModel":{"url":"\/documentation\/easechatuikit\/contactviewcontroller\/viewmodel","title":"viewModel","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewModel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContactViewModel","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"viewModel","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController\/viewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewController":{"role":"symbol","title":"ContactViewController","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewController","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ContactViewController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactViewModel"}],"type":"topic","abstract":[{"text":"Bind service and driver","type":"text"}],"url":"\/documentation\/easechatuikit\/contactviewmodel","role":"symbol","title":"ContactViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"viewModel","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"viewModel"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"ContactViewModel","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel"},{"text":" * ","kind":"text"},{"text":"viewModel","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"viewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1viewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController~1viewModel\/fragments","value":[{"kind":"identifier","text":"viewModel"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/title","op":"replace","value":"ContactViewController"},{"value":[{"text":"ContactViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ContactViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","op":"replace","value":"ContactViewModel"},{"value":[{"kind":"identifier","text":"ContactViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}