{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerControllerDidCancel(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/imagepickercontrollerdidcancel(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/imagepickercontrollerdidcancel(_:)"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIImagePickerControllerDelegate.imagePickerControllerDidCancel(_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"picker","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/UIImagePickerControllerDelegate-Implementations"]]},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","title":"imagePickerControllerDidCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imagePickerControllerDidCancel","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)imagePickerControllerDidCancel:"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/UIImagePickerControllerDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/messagelistcontroller\/uiimagepickercontrollerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/UIImagePickerControllerDelegate-Implementations","role":"collectionGroup","kind":"article","type":"topic","title":"UIImagePickerControllerDelegate Implementations","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","title":"MessageListController","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/imagePickerControllerDidCancel(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"text":"(","kind":"text"},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagelistcontroller\/imagepickercontrollerdidcancel(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerControllerDidCancel(_:)","role":"symbol","kind":"symbol","type":"topic","title":"imagePickerControllerDidCancel(_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"imagePickerControllerDidCancel:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"imagePickerControllerDidCancel:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"kind":"text","text":" *) "},{"text":"picker","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"kind":"identifier","text":"MessageListController"}]},{"value":"imagePickerControllerDidCancel:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1imagePickerControllerDidCancel(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerControllerDidCancel:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1imagePickerControllerDidCancel(_:)\/fragments"}]}]}