{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/init(conversationId:chatType:)"},"abstract":[{"text":"Initializes a new instance of the ","type":"text"},{"code":"MessageListController","type":"codeVoice"},{"text":" class with the specified conversation ID and chat type.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/init(conversationid:chattype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/init(conversationid:chattype:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithConversationId:chatType:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"chatType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType","text":"ChatType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageListController(im)initWithConversationId:chatType:","title":"init(conversationId:chatType:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithConversationId:chatType:) "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chatType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatType","kind":"typeIdentifier","text":"ChatType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType"},{"kind":"text","text":" = .chat)"}]}]},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"conversationId: The ID of the conversation.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"chatType: The type of chat. Default value is "},{"code":".chat","type":"codeVoice"},{"text":".","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"text":"This initializer sets the ","type":"text"},{"code":"profile","type":"codeVoice"},{"type":"text","text":" property based on the conversation ID. If the conversation ID is found in the conversations cache, the profile is set to the corresponding information. Otherwise, the profile ID is set to the conversation ID."}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"chatType"},{"type":"text","text":" parameter determines the type of chat, which can be "},{"code":".group","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":".chat"},{"type":"text","text":". If the chat type is not one of these options, it defaults to "},{"code":".chatroom","type":"codeVoice"},{"text":".","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/init(conversationId:chatType:)":{"abstract":[{"text":"Initializes a new instance of the ","type":"text"},{"code":"MessageListController","type":"codeVoice"},{"type":"text","text":" class with the specified conversation ID and chat type."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/init(conversationId:chatType:)","url":"\/documentation\/easechatuikit\/messagelistcontroller\/init(conversationid:chattype:)","title":"init(conversationId:chatType:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithConversationId:chatType:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"chatType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType","text":"ChatType","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatType":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatType","url":"\/documentation\/easechatuikit\/chattype","abstract":[{"type":"text","text":"An enumeration representing different types of chats."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatType"}],"kind":"symbol","title":"ChatType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","title":"MessageListController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithConversationId:chatType:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConversationId:chatType:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConversationId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"chatType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType","text":"ChatType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"chatType"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1init(conversationId:chatType:)\/title","value":"initWithConversationId:chatType:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithConversationId:chatType:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1init(conversationId:chatType:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatType\/title","value":"ChatType","op":"replace"},{"value":[{"text":"ChatType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatType\/navigatorTitle","value":[{"text":"ChatType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","op":"replace","value":"MessageListController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"text":"MessageListController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/navigatorTitle","op":"replace","value":[{"text":"MessageListController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}