{"abstract":[{"type":"text","text":"Handles the action of mentioning a user in the chat."}],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/mentionaction()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/mentionaction()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mentionAction","kind":"identifier"},{"kind":"text","text":"()"}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method presents a view controller that allows the user to select a participant to mention in the chat."},{"text":" ","type":"text"},{"type":"text","text":"The selected participant’s profile ID is used to update the mention IDs in the view model."}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]]},"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)mentionAction","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionAction"},{"kind":"text","text":"()"}],"title":"mentionAction()","extendedModule":"EaseChatUIKit","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"mentionAction","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/mentionAction()","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","type":"topic","abstract":[],"title":"MessageListController","url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/mentionAction()":{"type":"topic","abstract":[{"type":"text","text":"Handles the action of mentioning a user in the chat."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/mentionAction()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mentionAction"},{"text":"()","kind":"text"}],"url":"\/documentation\/easechatuikit\/messagelistcontroller\/mentionaction()","navigatorTitle":[{"kind":"identifier","text":"mentionAction"}],"kind":"symbol","title":"mentionAction()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"mentionAction","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mentionAction"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mentionAction","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageListController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1mentionAction()\/title","value":"mentionAction"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"mentionAction","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1mentionAction()\/fragments"}]}]}