{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/messageavatarclick(user:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/messageavatarclick(user:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)messageAvatarClickWithUser:","role":"symbol","navigatorTitle":[{"text":"messageAvatarClickWithUser:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageAvatarClick","kind":"identifier"},{"kind":"text","text":"("},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit","roleHeading":"Instance Method","title":"messageAvatarClick(user:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/messageAvatarClick(user:)","interfaceLanguage":"swift"},"abstract":[{"text":"Handles the click event on the message avatar.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageAvatarClick","kind":"identifier"},{"kind":"text","text":"("},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"text":")","kind":"text"}]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"user: The user profile associated with the clicked avatar."}]}]}]}],"kind":"content"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/messageAvatarClick(user:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/messageAvatarClick(user:)","role":"symbol","navigatorTitle":[{"text":"messageAvatarClickWithUser:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageAvatarClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":")","kind":"text"}],"abstract":[{"text":"Handles the click event on the message avatar.","type":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistcontroller\/messageavatarclick(user:)","title":"messageAvatarClick(user:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","title":"MessageListController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProtocol":{"abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatuserprofileprotocol","role":"symbol","title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"messageAvatarClickWithUser:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messageAvatarClickWithUser:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageAvatarClickWithUser:"},{"kind":"text","text":"("},{"text":"id<ChatUserProfileProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":") "},{"text":"user","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"messageAvatarClickWithUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1messageAvatarClick(user:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1messageAvatarClick(user:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messageAvatarClickWithUser:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/navigatorTitle"},{"op":"replace","value":"ChatUserProfileProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/fragments","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/navigatorTitle"}]}]}