{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numberOfPreviewItems"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)QLPreviewController","kind":"typeIdentifier","text":"QLPreviewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"numberOfPreviewItemsInPreviewController:"}],"extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)numberOfPreviewItemsInPreviewController:","symbolKind":"method","roleHeading":"Instance Method","title":"numberOfPreviewItems(in:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/QLPreviewControllerDataSource-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"numberOfPreviewItems"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"QLPreviewControllerDataSource.numberOfPreviewItems(in:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/numberofpreviewitems(in:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/numberofpreviewitems(in:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/numberOfPreviewItems(in:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","title":"MessageListController","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/numberOfPreviewItems(in:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"numberOfPreviewItems","kind":"identifier"},{"kind":"text","text":"("},{"text":"in","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/numberOfPreviewItems(in:)","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"numberOfPreviewItemsInPreviewController:"}],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelistcontroller\/numberofpreviewitems(in:)","title":"numberOfPreviewItems(in:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/QLPreviewControllerDataSource-Implementations":{"url":"\/documentation\/easechatuikit\/messagelistcontroller\/qlpreviewcontrollerdatasource-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/QLPreviewControllerDataSource-Implementations","title":"QLPreviewControllerDataSource Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"numberOfPreviewItemsInPreviewController:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"numberOfPreviewItemsInPreviewController:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"text":"numberOfPreviewItemsInPreviewController:","kind":"identifier"},{"kind":"text","text":"("},{"text":"QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController"},{"value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments"},{"value":"numberOfPreviewItemsInPreviewController:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1numberOfPreviewItems(in:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"numberOfPreviewItemsInPreviewController:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1numberOfPreviewItems(in:)\/fragments"}]}]}