{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType"}]}]},{"name":"attributeText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Text view’s attributeText"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/oninputboxeventsoccur(action:attributetext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/oninputboxeventsoccur(action:attributetext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/onInputBoxEventsOccur(action:attributeText:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputBarActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?)"}],"title":"onInputBoxEventsOccur(action:attributeText:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)onInputBoxEventsOccurWithAction:attributeText:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/MessageListDriverEventsListener-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/MessageListDriverEventsListener-Implementations":{"role":"collectionGroup","title":"MessageListDriverEventsListener Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/MessageListDriverEventsListener-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/messagelistcontroller\/messagelistdrivereventslistener-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/onInputBoxEventsOccur(action:attributeText:)":{"role":"symbol","title":"onInputBoxEventsOccur(action:attributeText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputBarActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/onInputBoxEventsOccur(action:attributeText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"url":"\/documentation\/easechatuikit\/messagelistcontroller\/oninputboxeventsoccur(action:attributetext:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"role":"symbol","title":"MessageListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListController"}],"url":"\/documentation\/easechatuikit\/messagelistcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBarActionType":{"role":"symbol","title":"MessageInputBarActionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageInputBarActionType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}],"url":"\/documentation\/easechatuikit\/messageinputbaractiontype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onInputBoxEventsOccurWithAction:attributeText:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributeText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"attributeText"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1onInputBoxEventsOccur(action:attributeText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"kind":"identifier","text":"MessageListController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/title","value":"MessageInputBarActionType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/fragments","value":[{"kind":"identifier","text":"MessageInputBarActionType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}