{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"When you click a message list multi select bar item,the method will call.","type":"text"}],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/onmessagemultiselectbarclicked(operation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/onmessagemultiselectbarclicked(operation:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/MessageListDriverEventsListener-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"operation","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","isActive":true,"type":"reference"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"onMessageMultiSelectBarClicked(operation:)","symbolKind":"method","role":"symbol","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)onMessageMultiSelectBarClickedWithOperation:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/onMessageMultiSelectBarClicked(operation:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/onMessageMultiSelectBarClicked(operation:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/onMessageMultiSelectBarClicked(operation:)","title":"onMessageMultiSelectBarClicked(operation:)","url":"\/documentation\/easechatuikit\/messagelistcontroller\/onmessagemultiselectbarclicked(operation:)","role":"symbol","abstract":[{"type":"text","text":"When you click a message list multi select bar item,the method will call."}],"navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/MessageListDriverEventsListener-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/MessageListDriverEventsListener-Implementations","kind":"article","url":"\/documentation\/easechatuikit\/messagelistcontroller\/messagelistdrivereventslistener-implementations","role":"collectionGroup","title":"MessageListDriverEventsListener Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","title":"MessageListController","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBarOperation":{"abstract":[],"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombaroperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"navigatorTitle":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MessageMultiSelectedBottomBarOperation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onMessageMultiSelectBarClickedWithOperation:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"text":") ","kind":"text"},{"text":"operation","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1onMessageMultiSelectBarClicked(operation:)\/title","op":"replace","value":"onMessageMultiSelectBarClickedWithOperation:"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1onMessageMultiSelectBarClicked(operation:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace"},{"op":"replace","value":"MessageMultiSelectedBottomBarOperation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/title"},{"value":[{"kind":"identifier","text":"MessageMultiSelectedBottomBarOperation"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/fragments","op":"replace"}]}]}