{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/showAllReactionsController(message:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"title":"showAllReactionsController(message:)","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)showAllReactionsControllerWithMessage:","extendedModule":"EaseChatUIKit","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showAllReactionsController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"showAllReactionsControllerWithMessage:"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAllReactionsController"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"typeIdentifier","text":"MessageEntity"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/showallreactionscontroller(message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/showallreactionscontroller(message:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/showAllReactionsController(message:)":{"url":"\/documentation\/easechatuikit\/messagelistcontroller\/showallreactionscontroller(message:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showAllReactionsController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"title":"showAllReactionsController(message:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/showAllReactionsController(message:)","navigatorTitle":[{"kind":"identifier","text":"showAllReactionsControllerWithMessage:"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","type":"topic","abstract":[],"title":"MessageListController","url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messageentity","title":"MessageEntity","navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"showAllReactionsControllerWithMessage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"showAllReactionsControllerWithMessage:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"showAllReactionsControllerWithMessage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"typeIdentifier","text":"MessageEntity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"showAllReactionsControllerWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1showAllReactionsController(message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1showAllReactionsController(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showAllReactionsControllerWithMessage:"}],"op":"replace"},{"op":"replace","value":"MessageListController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title"},{"value":[{"text":"MessageListController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title","value":"MessageEntity"},{"op":"replace","value":[{"kind":"identifier","text":"MessageEntity"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}