{"sections":[],"metadata":{"title":"showMessageLongPressedDialog(cell:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)showMessageLongPressedDialogWithCell:","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showMessageLongPressedDialog","kind":"identifier"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/showMessageLongPressedDialog(cell:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/showmessagelongpresseddialog(cell:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/showmessagelongpresseddialog(cell:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Shows a long-pressed dialog for a given chat message.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showMessageLongPressedDialog","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cell"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"message: The chat message for which the dialog is shown.","type":"text"}]}]}],"type":"unorderedList"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/showMessageLongPressedDialog(cell:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/showMessageLongPressedDialog(cell:)","title":"showMessageLongPressedDialog(cell:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showMessageLongPressedDialogWithCell:"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistcontroller\/showmessagelongpresseddialog(cell:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showMessageLongPressedDialog","kind":"identifier"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Shows a long-pressed dialog for a given chat message."}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagecell","role":"symbol","title":"MessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","title":"MessageListController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showMessageLongPressedDialogWithCell:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cell"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1showMessageLongPressedDialog(cell:)\/title","value":"showMessageLongPressedDialogWithCell:"},{"value":[{"text":"- ","kind":"text"},{"text":"showMessageLongPressedDialogWithCell:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1showMessageLongPressedDialog(cell:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","value":"MessageCell","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/navigatorTitle","value":[{"text":"MessageCell","kind":"identifier"}]},{"op":"replace","value":"MessageListController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title"},{"value":[{"kind":"identifier","text":"MessageListController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/navigatorTitle","value":[{"text":"MessageListController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}