{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"UIImagePickerControllerDelegate Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/uiimagepickercontrollerdelegate-implementations"]},{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/uiimagepickercontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerControllerDidCancel(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]]},"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/UIImagePickerControllerDelegate-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/imagePickerControllerDidCancel(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"text":"(","kind":"text"},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerControllerDidCancel(_:)","navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"title":"imagePickerControllerDidCancel(_:)","url":"\/documentation\/easechatuikit\/messagelistcontroller\/imagepickercontrollerdidcancel(_:)","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","title":"MessageListController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","navigatorTitle":[{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":", ","kind":"text"},{"text":"didFinishPickingMediaWithInfo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIImagePickerController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","text":"InfoKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/imagePickerControllerDidCancel(_:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":"imagePickerControllerDidCancel:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1imagePickerControllerDidCancel(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1imagePickerControllerDidCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerControllerDidCancel:"}],"op":"replace"},{"value":"MessageListController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title"},{"value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListController"}],"op":"replace"},{"value":"imagePickerController:didFinishPickingMediaWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}