{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDetail"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/viewdetail()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistcontroller\/viewdetail()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/viewDetail()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method is called to view the detail of a chat message."},{"type":"text","text":" "},{"type":"text","text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly."},{"type":"text","text":" "},{"type":"text","text":"If the previous view controller in the navigation stack is either "},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":", it pops the current view controller."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"type":"codeVoice","code":"GroupInfoController"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."},{"type":"text","text":" "},{"type":"text","text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either "},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" and dismisses it."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"type":"codeVoice","code":"GroupInfoController"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDetail"},{"kind":"text","text":"()"}],"title":"viewDetail()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListController(im)viewDetail","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"viewDetail"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"role":"symbol","title":"MessageListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListController"}],"url":"\/documentation\/easechatuikit\/messagelistcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController/viewDetail()":{"role":"symbol","title":"viewDetail()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDetail"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is called to view the detail of a chat message."},{"type":"text","text":" "},{"type":"text","text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly."},{"type":"text","text":" "},{"type":"text","text":"If the previous view controller in the navigation stack is either "},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":", it pops the current view controller."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"type":"codeVoice","code":"GroupInfoController"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."},{"type":"text","text":" "},{"type":"text","text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either "},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" and dismisses it."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"type":"codeVoice","code":"GroupInfoController"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController\/viewDetail()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDetail"}],"url":"\/documentation\/easechatuikit\/messagelistcontroller\/viewdetail()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewDetail"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDetail"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDetail"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"kind":"identifier","text":"MessageListController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1viewDetail()\/title","value":"viewDetail"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController~1viewDetail()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDetail"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}