{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/large"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"large","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/alertstyle\/large"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/alertstyle\/large"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@E@AlertStyle@AlertStyleLarge","title":"AlertStyle.large","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"large","kind":"identifier"}],"navigatorTitle":[{"text":"AlertStyleLarge","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle/large":{"url":"\/documentation\/easechatuikit\/alertstyle\/large","type":"topic","abstract":[],"role":"symbol","kind":"symbol","title":"AlertStyle.large","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"large","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/large","navigatorTitle":[{"text":"AlertStyleLarge","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle":{"navigatorTitle":[{"kind":"identifier","text":"AlertStyle"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle","title":"AlertStyle","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertStyle","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/alertstyle","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AlertStyleLarge"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AlertStyleLarge"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"AlertStyleLarge","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle~1large\/title","value":"AlertStyleLarge"},{"value":[{"text":"AlertStyleLarge","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle~1large\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle\/title","value":"AlertStyle"},{"value":[{"text":"AlertStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle\/fragments","op":"replace"}]}]}