{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"content","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ImageMessageCell(py)content","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageMessageCell"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/imagemessagecell\/content"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/imagemessagecell\/content"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageMessageCell\/content","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","text":"ImageView"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ImageMessageCell/content":{"url":"\/documentation\/easechatuikit\/imagemessagecell\/content","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageMessageCell\/content","title":"content","abstract":[],"role":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ImageMessageCell":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageMessageCell","title":"ImageMessageCell","url":"\/documentation\/easechatuikit\/imagemessagecell","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageMessageCell"}],"kind":"symbol","navigatorTitle":[{"text":"ImageMessageCell","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ImageView":{"kind":"symbol","navigatorTitle":[{"text":"ImageView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"title":"ImageView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A subclass of "},{"code":"UIImageView","type":"codeVoice"},{"text":" that provides a method for loading an image from a URL.","type":"text"}],"url":"\/documentation\/easechatuikit\/imageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"content"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"content","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","text":"ImageView","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"content","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageMessageCell~1content\/title","value":"content"},{"value":[{"kind":"identifier","text":"content"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageMessageCell~1content\/fragments"},{"value":"ImageMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageMessageCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageMessageCell\/fragments","value":[{"text":"ImageMessageCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/title","value":"ImageView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/fragments","value":[{"text":"ImageView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}