{"abstract":[{"text":"When fetch list occur error.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/occurError()","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver"]]},"metadata":{"title":"occurError()","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"occurError"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver(im)occurError","symbolKind":"method","navigatorTitle":[{"text":"occurError","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"occurError","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/icontactlistdriver\/occurerror()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/icontactlistdriver\/occurerror()"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver","type":"topic","navigatorTitle":[{"text":"IContactListDriver","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IContactListDriver","kind":"identifier"}],"title":"IContactListDriver","url":"\/documentation\/easechatuikit\/icontactlistdriver","kind":"symbol","abstract":[{"type":"text","text":"A driver protocol of "},{"type":"codeVoice","code":"ContactList"},{"type":"text","text":"."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/occurError()":{"navigatorTitle":[{"text":"occurError","kind":"identifier"}],"required":true,"abstract":[{"text":"When fetch list occur error.","type":"text"}],"url":"\/documentation\/easechatuikit\/icontactlistdriver\/occurerror()","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/occurError()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"occurError","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","title":"occurError()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"occurError","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"occurError","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"occurError"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"IContactListDriver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/fragments","value":[{"text":"IContactListDriver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1occurError()\/title","value":"occurError"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1occurError()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"occurError"}]}]}]}