{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/destructive"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/actionsheetitemtype\/destructive"]},{"paths":["\/documentation\/easechatuikit\/actionsheetitemtype\/destructive"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"destructive"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"ActionSheetItemTypeDestructive","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"destructive"}],"externalID":"c:@M@EaseChatUIKit@E@ActionSheetItemType@ActionSheetItemTypeDestructive","title":"ActionSheetItemType.destructive","symbolKind":"case","roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType/destructive":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"destructive"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}],"url":"\/documentation\/easechatuikit\/actionsheetitemtype\/destructive","kind":"symbol","title":"ActionSheetItemType.destructive","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/destructive"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","navigatorTitle":[{"text":"ActionSheetItemType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionSheetItemType","kind":"identifier"}],"title":"ActionSheetItemType","role":"symbol","url":"\/documentation\/easechatuikit\/actionsheetitemtype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ActionSheetItemTypeDestructive","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"ActionSheetItemTypeDestructive","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"ActionSheetItemTypeDestructive","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType~1destructive\/title","value":"ActionSheetItemTypeDestructive"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType~1destructive\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/title","op":"replace","value":"ActionSheetItemType"},{"value":[{"text":"ActionSheetItemType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/fragments","op":"replace"}]}]}