{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/extensionMenus"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageinputbar\/extensionmenus"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messageinputbar\/extensionmenus"]}],"metadata":{"symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"title":"extensionMenus","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"extensionMenus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageInputExtensionView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputExtensionView"}],"role":"symbol","navigatorTitle":[{"text":"extensionMenus","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageInputBar(py)extensionMenus"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"extensionMenus","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageInputExtensionView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputExtensionView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputExtensionView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar":{"type":"topic","navigatorTitle":[{"text":"MessageInputBar","kind":"identifier"}],"title":"MessageInputBar","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputBar"}],"url":"\/documentation\/easechatuikit\/messageinputbar","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputExtensionView":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageInputExtensionView","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messageinputextensionview","role":"symbol","title":"MessageInputExtensionView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputExtensionView","navigatorTitle":[{"kind":"identifier","text":"MessageInputExtensionView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar/extensionMenus":{"abstract":[],"url":"\/documentation\/easechatuikit\/messageinputbar\/extensionmenus","title":"extensionMenus","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"extensionMenus","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageInputExtensionView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputExtensionView"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"extensionMenus"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/extensionMenus"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"extensionMenus"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"extensionMenus"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"MessageInputExtensionView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputExtensionView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputExtensionView","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"extensionMenus"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/title","value":"MessageInputBar"},{"op":"replace","value":[{"text":"MessageInputBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/navigatorTitle","value":[{"kind":"identifier","text":"MessageInputBar"}],"op":"replace"},{"value":"MessageInputExtensionView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputExtensionView\/title"},{"value":[{"kind":"identifier","text":"MessageInputExtensionView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputExtensionView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"MessageInputExtensionView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputExtensionView\/navigatorTitle"},{"value":"extensionMenus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1extensionMenus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1extensionMenus\/fragments","value":[{"text":"extensionMenus","kind":"identifier"}],"op":"replace"}]}]}