{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/hitTest(_:with:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageinputbar\/hittest(_:with:)"]},{"paths":["\/documentation\/easechatuikit\/messageinputbar\/hittest(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hitTest","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"hitTest:withEvent:","kind":"identifier"}],"extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageInputBar(im)hitTest:withEvent:","symbolKind":"method","roleHeading":"Instance Method","title":"hitTest(_:with:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hitTest","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"point","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"?"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar":{"role":"symbol","type":"topic","title":"MessageInputBar","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageInputBar","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageInputBar"}],"url":"\/documentation\/easechatuikit\/messageinputbar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar/hitTest(_:with:)":{"url":"\/documentation\/easechatuikit\/messageinputbar\/hittest(_:with:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hitTest"},{"text":"(","kind":"text"},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":"?) -> "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"hitTest(_:with:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/hitTest(_:with:)","role":"symbol","navigatorTitle":[{"text":"hitTest:withEvent:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"hitTest:withEvent:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"hitTest:withEvent:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"hitTest:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"text":") ","kind":"text"},{"text":"point","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"withEvent:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"event"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/title","op":"replace","value":"MessageInputBar"},{"op":"replace","value":[{"text":"MessageInputBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/fragments"},{"value":"hitTest:withEvent:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1hitTest(_:with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1hitTest(_:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"hitTest:withEvent:","kind":"identifier"}]}]}]}