{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/ThemeSwitchProtocol-Implementations"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/messageinputbar\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messageinputbar\/switchtheme(style:)"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/switchTheme(style:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","type":"reference"}]}]}],"kind":"parameters"}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageInputBar(im)switchThemeWithStyle:","title":"switchTheme(style:)","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"extendedModule":"EaseChatUIKit","symbolKind":"method","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageInputBar","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messageinputbar","navigatorTitle":[{"text":"MessageInputBar","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar","type":"topic","kind":"symbol","title":"MessageInputBar"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar/switchTheme(style:)":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/messageinputbar\/switchtheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/switchTheme(style:)","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"title":"switchTheme(style:)","kind":"symbol","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle":{"role":"symbol","kind":"symbol","type":"topic","title":"ThemeStyle","abstract":[{"text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","type":"reference"},{"text":".Then call ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"type":"text","text":" method"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","navigatorTitle":[{"text":"ThemeStyle","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/themestyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar/ThemeSwitchProtocol-Implementations":{"type":"topic","role":"collectionGroup","url":"\/documentation\/easechatuikit\/messageinputbar\/themeswitchprotocol-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","abstract":[],"kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"switchThemeWithStyle:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"switchThemeWithStyle:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"style","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/title","value":"MessageInputBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/fragments","value":[{"kind":"identifier","text":"MessageInputBar"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","op":"replace","value":"Appearance"},{"value":[{"kind":"identifier","text":"Appearance"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments"},{"value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1switchTheme(style:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1switchTheme(style:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}]},{"value":"ThemeStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/title"},{"value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/fragments"}]}]}