{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/textViewDidBeginEditing(_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/UITextViewDelegate-Implementations"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textViewDidBeginEditing","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"textView","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier","text":"UITextView"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textViewDidBeginEditing","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"textViewDidBeginEditing:"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageInputBar(im)textViewDidBeginEditing:","symbolKind":"method","roleHeading":"Instance Method","title":"textViewDidBeginEditing(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageinputbar\/textviewdidbeginediting(_:)"]},{"paths":["\/documentation\/easechatuikit\/messageinputbar\/textviewdidbeginediting(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITextViewDelegate.textViewDidBeginEditing(_:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar/textViewDidBeginEditing(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textViewDidBeginEditing","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/textViewDidBeginEditing(_:)","url":"\/documentation\/easechatuikit\/messageinputbar\/textviewdidbeginediting(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textViewDidBeginEditing:"}],"type":"topic","title":"textViewDidBeginEditing(_:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar/UITextViewDelegate-Implementations":{"type":"topic","title":"UITextViewDelegate Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/messageinputbar\/uitextviewdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar\/UITextViewDelegate-Implementations","kind":"article","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBar":{"role":"symbol","type":"topic","title":"MessageInputBar","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageInputBar","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageInputBar"}],"url":"\/documentation\/easechatuikit\/messageinputbar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBar","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"textViewDidBeginEditing:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"textViewDidBeginEditing:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"textViewDidBeginEditing:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textView"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"textViewDidBeginEditing:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1textViewDidBeginEditing(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidBeginEditing:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar~1textViewDidBeginEditing(_:)\/fragments"},{"value":"MessageInputBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBar\/fragments","value":[{"text":"MessageInputBar","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}