{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextMessageCell\/createTranslateSymbol()","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextMessageCell"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createTranslateSymbol"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/textmessagecell\/createtranslatesymbol()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/textmessagecell\/createtranslatesymbol()"]}],"metadata":{"role":"symbol","title":"createTranslateSymbol()","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)TextMessageCell(im)createTranslateSymbol","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTranslateSymbol","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton"}],"navigatorTitle":[{"text":"createTranslateSymbol","kind":"identifier"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TextMessageCell":{"type":"topic","title":"TextMessageCell","navigatorTitle":[{"text":"TextMessageCell","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextMessageCell","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/textmessagecell","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextMessageCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TextMessageCell/createTranslateSymbol()":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"createTranslateSymbol"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextMessageCell\/createTranslateSymbol()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createTranslateSymbol","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"role":"symbol","url":"\/documentation\/easechatuikit\/textmessagecell\/createtranslatesymbol()","title":"createTranslateSymbol()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"createTranslateSymbol","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createTranslateSymbol"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"createTranslateSymbol","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TextMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextMessageCell\/title"},{"value":[{"text":"TextMessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextMessageCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextMessageCell\/navigatorTitle","value":[{"text":"TextMessageCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextMessageCell~1createTranslateSymbol()\/title","value":"createTranslateSymbol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextMessageCell~1createTranslateSymbol()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createTranslateSymbol","kind":"identifier"}]}]}]}