{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"pop","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"text":"()","kind":"text"}],"title":"pop()","externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationListController(im)pop","role":"symbol","symbolKind":"method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/pop()"]},{"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/pop()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/pop()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Pops the current view controller from the navigation stack if it exists,"},{"type":"text","text":" "},{"type":"text","text":"otherwise dismisses the view controller."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pop","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"This method is typically used to navigate back to the previous screen.","type":"text"}]}],"type":"aside","name":"Note","style":"note"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/pop()":{"title":"pop()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/pop()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pop"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"text":"Pops the current view controller from the navigation stack if it exists,","type":"text"},{"text":" ","type":"text"},{"text":"otherwise dismisses the view controller.","type":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/pop()","navigatorTitle":[{"text":"pop","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"ConversationListController","type":"codeVoice"},{"text":" class implements a view controller that displays a list of conversations.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It inherits from "},{"code":"UIViewController","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/conversationlistcontroller","title":"ConversationListController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pop","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"pop","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pop","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1pop()\/title","value":"pop"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1pop()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pop","kind":"identifier"}]},{"value":"ConversationListController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/fragments","op":"replace","value":[{"text":"ConversationListController","kind":"identifier"}]}]}]}