{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/searchAction()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Performs a search action in the conversation list."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController"]]},"metadata":{"extendedModule":"EaseChatUIKit","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchAction"},{"text":"()","kind":"text"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationListController(im)searchAction","role":"symbol","title":"searchAction()","roleHeading":"Instance Method","navigatorTitle":[{"text":"searchAction","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/searchaction()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/searchaction()"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"searchAction"},{"text":"()","kind":"text"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method creates a "},{"code":"SearchConversationsController","type":"codeVoice"},{"type":"text","text":" instance and presents it to the user."},{"text":" ","type":"text"},{"type":"text","text":"When a conversation is selected from the search results, it navigates to the chat screen."}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/searchAction()":{"title":"searchAction()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/searchAction()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"searchAction","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"text":"Performs a search action in the conversation list.","type":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/searchaction()","navigatorTitle":[{"text":"searchAction","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"ConversationListController","type":"codeVoice"},{"text":" class implements a view controller that displays a list of conversations.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It inherits from "},{"code":"UIViewController","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/conversationlistcontroller","title":"ConversationListController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"searchAction"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"searchAction","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"searchAction"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1searchAction()\/title","value":"searchAction"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"searchAction"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1searchAction()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/title","value":"ConversationListController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/fragments","value":[{"text":"ConversationListController","kind":"identifier"}]}]}]}