{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/switchTheme(style:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","text":"ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","type":"reference","isActive":true}]}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationListController(im)switchThemeWithStyle:","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"switchTheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/ThemeSwitchProtocol-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/switchtheme(style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/switchtheme(style:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/ThemeSwitchProtocol-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/themeswitchprotocol-implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController":{"url":"\/documentation\/easechatuikit\/conversationlistcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","abstract":[{"type":"text","text":"The "},{"code":"ConversationListController","type":"codeVoice"},{"text":" class implements a view controller that displays a list of conversations.","type":"text"},{"type":"text","text":" "},{"text":"It inherits from ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","title":"ConversationListController","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/switchTheme(style:)":{"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/switchtheme(style:)","kind":"symbol","title":"switchTheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"role":"symbol","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"text":" to switch theme.","type":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/switchTheme(style:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle":{"type":"topic","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","type":"reference","isActive":true},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"text":" method","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","title":"ThemeStyle","kind":"symbol","url":"\/documentation\/easechatuikit\/themestyle","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"type":"topic","abstract":[{"text":"An object containing visual configurations for the whole application.","type":"text"}],"title":"Appearance","kind":"symbol","navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","url":"\/documentation\/easechatuikit\/appearance"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"switchThemeWithStyle:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/title","op":"replace","value":"ConversationListController"},{"value":[{"text":"ConversationListController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationListController"}]},{"value":"switchThemeWithStyle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1switchTheme(style:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1switchTheme(style:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/title","value":"ThemeStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/fragments","value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/navigatorTitle"},{"value":"Appearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","value":[{"kind":"identifier","text":"Appearance"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/navigatorTitle"}]}]}