{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toChat"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index path of the selected conversation in the table view."}]}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The information of the selected conversation."}]}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This method creates an instance of "},{"type":"codeVoice","code":"MessageViewController"},{"type":"text","text":" and pushes it onto the navigation stack using "},{"type":"codeVoice","code":"ControllerStack.toDestination(vc:)"},{"type":"text","text":"."}]}],"type":"aside","name":"Note"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/tochat(indexpath:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationlistcontroller\/tochat(indexpath:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/toChat(indexPath:info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Opens the chat view controller for the selected conversation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toChat"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"title":"toChat(indexPath:info:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationListController(im)toChatWithIndexPath:info:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"toChatWithIndexPath:info:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/toChat(indexPath:info:)":{"role":"symbol","title":"toChat(indexPath:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"toChat"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Opens the chat view controller for the selected conversation."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/toChat(indexPath:info:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"toChatWithIndexPath:info:"}],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/tochat(indexpath:info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"role":"symbol","title":"ConversationInfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationInfo"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationInfo"}],"url":"\/documentation\/easechatuikit\/conversationinfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController":{"role":"symbol","title":"ConversationListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListController"}],"abstract":[{"type":"text","text":"When you"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationListController"}],"url":"\/documentation\/easechatuikit\/conversationlistcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"toChatWithIndexPath:info:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toChatWithIndexPath:info:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"toChatWithIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":" "},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1toChat(indexPath:info:)\/title","value":"toChatWithIndexPath:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1toChat(indexPath:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"toChatWithIndexPath:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title","value":"ConversationInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","value":[{"kind":"identifier","text":"ConversationInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/title","value":"ConversationListController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/fragments","value":[{"kind":"identifier","text":"ConversationListController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}