{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"},{"kind":"text","text":"()"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistoccurerrorwhenfetchserver()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistoccurerrorwhenfetchserver()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate(im)onConversationListOccurErrorWhenFetchServer","required":true,"symbolKind":"method","role":"symbol","title":"onConversationListOccurErrorWhenFetchServer()","roleHeading":"Instance Method","navigatorTitle":[{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"},{"kind":"text","text":"()"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"title":"ConversationListActionEventsDelegate","type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate","kind":"symbol","navigatorTitle":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationListOccurErrorWhenFetchServer()":{"required":true,"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","role":"symbol","title":"onConversationListOccurErrorWhenFetchServer()","navigatorTitle":[{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistoccurerrorwhenfetchserver()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onConversationListOccurErrorWhenFetchServer","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title","value":"ConversationListActionEventsDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments","value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]},{"op":"replace","value":"onConversationListOccurErrorWhenFetchServer","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListOccurErrorWhenFetchServer()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListOccurErrorWhenFetchServer()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"}],"op":"replace"}]}]}