{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onConversationListEndScrollNeededDisplayInfos","kind":"identifier"},{"kind":"text","text":"("},{"text":"ids","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"ids","content":[{"inlineContent":[{"type":"text","text":"[conversationId]"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistendscrollneededdisplayinfos(ids:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistendscrollneededdisplayinfos(ids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","interfaceLanguage":"swift"},"metadata":{"required":true,"symbolKind":"method","title":"onConversationListEndScrollNeededDisplayInfos(ids:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfos","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ids","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate(im)onConversationListEndScrollNeededDisplayInfosWithIds:","navigatorTitle":[{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate"]]},"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"title":"ConversationListActionEventsDelegate","type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate","kind":"symbol","navigatorTitle":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationListEndScrollNeededDisplayInfos(ids:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","title":"onConversationListEndScrollNeededDisplayInfos(ids:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfos"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"required":true,"url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistendscrollneededdisplayinfos(ids:)","navigatorTitle":[{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"}],"role":"symbol","abstract":[{"type":"text","text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"onConversationListEndScrollNeededDisplayInfosWithIds:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ids"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"ConversationListActionEventsDelegate","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments","value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListEndScrollNeededDisplayInfos(ids:)\/title","value":"onConversationListEndScrollNeededDisplayInfosWithIds:"},{"value":[{"kind":"text","text":"- "},{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListEndScrollNeededDisplayInfos(ids:)\/fragments"}]}]}