{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Callback on conversation was long pressed."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlongpressed(indexpath:info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlongpressed(indexpath:info:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onConversationLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate(im)onConversationLongPressedWithIndexPath:info:","role":"symbol","roleHeading":"Instance Method","title":"onConversationLongPressed(indexPath:info:)","required":true,"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"typeIdentifier","text":"ConversationInfo"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"indexPath","content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"IndexPath"},{"type":"text","text":" of long pressed cell."}],"type":"paragraph"}]},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","isActive":true},{"type":"text","text":" object."}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationLongPressed(indexPath:info:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationLongPressed"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"text":"Callback on conversation was long pressed.","type":"text"}],"title":"onConversationLongPressed(indexPath:info:)","role":"symbol","navigatorTitle":[{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlongpressed(indexpath:info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"type":"topic","title":"ConversationInfo","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationinfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationInfo"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","title":"ConversationListActionEventsDelegate","abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate","navigatorTitle":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onConversationLongPressedWithIndexPath:info:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onConversationLongPressedWithIndexPath:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":" ","kind":"text"},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":" *) "},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"IndexPath"},{"text":" of long pressed cell.","type":"text"}],"type":"paragraph"}],"name":"indexPath"},{"name":"info","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","isActive":true},{"type":"text","text":" object."}],"type":"paragraph"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationLongPressed(indexPath:info:)\/title","value":"onConversationLongPressedWithIndexPath:info:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationLongPressed(indexPath:info:)\/fragments"},{"op":"replace","value":"ConversationInfo","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"ConversationInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title","value":"ConversationListActionEventsDelegate","op":"replace"},{"op":"replace","value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/navigatorTitle","value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"op":"replace"}]}]}