{"abstract":[{"text":"Callback on conversation was swiped.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationswipe(type:info:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationswipe(type:info:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationSwipe"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIContextualActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType"}],"type":"paragraph"}],"name":"type"},{"name":"info","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","isActive":true,"type":"reference"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate(im)onConversationSwipeWithType:info:","role":"symbol","title":"onConversationSwipe(type:info:)","required":true,"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationSwipe","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onConversationSwipeWithType:info:"}]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","navigatorTitle":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"title":"ConversationListActionEventsDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationSwipe(type:info:)":{"type":"topic","title":"onConversationSwipe(type:info:)","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationswipe(type:info:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationSwipe"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)","navigatorTitle":[{"kind":"identifier","text":"onConversationSwipeWithType:info:"}],"kind":"symbol","abstract":[{"text":"Callback on conversation was swiped.","type":"text"}],"required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"navigatorTitle":[{"kind":"identifier","text":"ConversationInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/conversationinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"symbol","type":"topic","title":"ConversationInfo","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType":{"role":"symbol","title":"UIContextualActionType","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"UIContextualActionType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","url":"\/documentation\/easechatuikit\/uicontextualactiontype"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"onConversationSwipeWithType:info:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationSwipeWithType:info:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onConversationSwipeWithType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UIContextualActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"text":"info:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ConversationListActionEventsDelegate","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationSwipe(type:info:)\/title","value":"onConversationSwipeWithType:info:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationSwipeWithType:info:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationSwipe(type:info:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title","op":"replace","value":"ConversationInfo"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationInfo"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/title","value":"UIContextualActionType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/fragments","value":[{"kind":"identifier","text":"UIContextualActionType"}],"op":"replace"}]}]}