{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/contentStyle"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"contentStyle","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MessageContentDisplayStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageContentDisplayStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","kind":"typeIdentifier"},{"kind":"text","text":"]"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatappearance\/contentstyle"]}],"kind":"symbol","abstract":[{"text":"Message content display style.You can use these four styles to combine a style array you want. Bubbles are all provided by default, except for picture messages and video messages.","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","type":"reference","isActive":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"externalID":"s:13EaseChatUIKit0B10AppearanceC12contentStyleSayAA021MessageContentDisplayF0OGvp","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"contentStyle","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageContentDisplayStyle","text":"MessageContentDisplayStyle"},{"kind":"text","text":"]"}],"role":"symbol","title":"contentStyle"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance":{"navigatorTitle":[{"text":"ChatAppearance","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatappearance","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance","title":"ChatAppearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAppearance"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle":{"title":"MessageContentDisplayStyle","navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyle"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageContentDisplayStyle","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance/contentStyle":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/contentStyle","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/chatappearance\/contentstyle","type":"topic","abstract":[{"text":"Message content display style.You can use these four styles to combine a style array you want. Bubbles are all provided by default, except for picture messages and video messages.","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","type":"reference","isActive":true}],"title":"contentStyle","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"contentStyle","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageContentDisplayStyle","text":"MessageContentDisplayStyle"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"patch":[{"value":"ChatAppearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/title"},{"value":[{"text":"ChatAppearance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"ChatAppearance"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/navigatorTitle"},{"value":"MessageContentDisplayStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/fragments","op":"replace","value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/navigatorTitle","op":"replace","value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}