{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"dateFormatOtherDay"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dateFormatOtherDay","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatAppearance(py)dateFormatOtherDay","role":"symbol","title":"dateFormatOtherDay","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/dateFormatOtherDay","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateFormatOtherDay","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Setting this property changes the date format displayed within a single session."}],"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatappearance\/dateformatotherday"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatappearance\/dateformatotherday"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance/dateFormatOtherDay":{"abstract":[{"type":"text","text":"Setting this property changes the date format displayed within a single session."}],"role":"symbol","title":"dateFormatOtherDay","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dateFormatOtherDay","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"dateFormatOtherDay","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/dateFormatOtherDay","type":"topic","url":"\/documentation\/easechatuikit\/chatappearance\/dateformatotherday"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAppearance","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance","navigatorTitle":[{"text":"ChatAppearance","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/chatappearance","role":"symbol","title":"ChatAppearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dateFormatOtherDay"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"dateFormatOtherDay","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"dateFormatOtherDay","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1dateFormatOtherDay\/title","value":"dateFormatOtherDay","op":"replace"},{"value":[{"kind":"identifier","text":"dateFormatOtherDay"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1dateFormatOtherDay\/fragments","op":"replace"},{"value":"ChatAppearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ChatAppearance"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}