{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageAttachmentMenuStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageAttachmentMenuStyle","text":"MessageAttachmentMenuStyle","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"messageAttachmentMenuStyle","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","title":"messageAttachmentMenuStyle","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatAppearance(py)messageAttachmentMenuStyle"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/messageAttachmentMenuStyle"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance"]]},"kind":"symbol","abstract":[{"type":"text","text":"Choose to show the message attachment menu style."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"messageAttachmentMenuStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"MessageAttachmentMenuStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageAttachmentMenuStyle","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatappearance\/messageattachmentmenustyle"]},{"paths":["\/documentation\/easechatuikit\/chatappearance\/messageattachmentmenustyle"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance/messageAttachmentMenuStyle":{"title":"messageAttachmentMenuStyle","type":"topic","url":"\/documentation\/easechatuikit\/chatappearance\/messageattachmentmenustyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"messageAttachmentMenuStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageAttachmentMenuStyle","kind":"typeIdentifier","text":"MessageAttachmentMenuStyle"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/messageAttachmentMenuStyle","role":"symbol","abstract":[{"type":"text","text":"Choose to show the message attachment menu style."}],"navigatorTitle":[{"text":"messageAttachmentMenuStyle","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance":{"navigatorTitle":[{"text":"ChatAppearance","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatappearance","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance","title":"ChatAppearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAppearance"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle":{"navigatorTitle":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MessageAttachmentMenuStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"messageAttachmentMenuStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"messageAttachmentMenuStyle"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageAttachmentMenuStyle","text":"MessageAttachmentMenuStyle"},{"text":" ","kind":"text"},{"text":"messageAttachmentMenuStyle","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1messageAttachmentMenuStyle\/title","value":"messageAttachmentMenuStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1messageAttachmentMenuStyle\/fragments","value":[{"text":"messageAttachmentMenuStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ChatAppearance","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/fragments","value":[{"text":"ChatAppearance","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/navigatorTitle","value":[{"text":"ChatAppearance","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/title","value":"MessageAttachmentMenuStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/fragments","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/navigatorTitle","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"op":"replace"}]}]}