{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/messageLongPressMenuStyle"},"metadata":{"symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatAppearance(py)messageLongPressMenuStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageLongPressMenuStyle"}],"modules":[{"name":"EaseChatUIKit"}],"title":"messageLongPressMenuStyle","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageLongPressMenuStyle","text":"MessageLongPressMenuStyle"}]},"kind":"symbol","abstract":[{"type":"text","text":"Choose to show the message long press menu style."}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatappearance\/messagelongpressmenustyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatappearance\/messagelongpressmenustyle"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageLongPressMenuStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageLongPressMenuStyle","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenuStyle":{"title":"MessageLongPressMenuStyle","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageLongPressMenuStyle"}],"navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenuStyle"}],"url":"\/documentation\/easechatuikit\/messagelongpressmenustyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance/messageLongPressMenuStyle":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/messageLongPressMenuStyle","kind":"symbol","title":"messageLongPressMenuStyle","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"MessageLongPressMenuStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageLongPressMenuStyle"}],"navigatorTitle":[{"text":"messageLongPressMenuStyle","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Choose to show the message long press menu style.","type":"text"}],"type":"topic","url":"\/documentation\/easechatuikit\/chatappearance\/messagelongpressmenustyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance":{"navigatorTitle":[{"text":"ChatAppearance","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatappearance","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance","title":"ChatAppearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAppearance"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"messageLongPressMenuStyle","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"messageLongPressMenuStyle","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"MessageLongPressMenuStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageLongPressMenuStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle"},{"kind":"text","text":" "},{"text":"messageLongPressMenuStyle","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle\/title","op":"replace","value":"MessageLongPressMenuStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle\/fragments","value":[{"kind":"identifier","text":"MessageLongPressMenuStyle"}]},{"value":[{"kind":"identifier","text":"MessageLongPressMenuStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1messageLongPressMenuStyle\/title","op":"replace","value":"messageLongPressMenuStyle"},{"value":[{"kind":"identifier","text":"messageLongPressMenuStyle"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1messageLongPressMenuStyle\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/title","value":"ChatAppearance","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/fragments","value":[{"kind":"identifier","text":"ChatAppearance"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ChatAppearance"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/navigatorTitle"}]}]}