{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"moreMessageAlertPosition","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MoreMessagePosition","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","preciseIdentifier":"c:@M@EaseChatUIKit@E@MoreMessagePosition"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatappearance\/moremessagealertposition"]},{"paths":["\/documentation\/easechatuikit\/chatappearance\/moremessagealertposition"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The alert position on received lots of messages.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/moreMessageAlertPosition","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"moreMessageAlertPosition","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatAppearance(py)moreMessageAlertPosition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"moreMessageAlertPosition"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"moreMessageAlertPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MoreMessagePosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MoreMessagePosition"}],"roleHeading":"Instance Property","symbolKind":"property"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition":{"title":"MoreMessagePosition","url":"\/documentation\/easechatuikit\/moremessageposition","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MoreMessagePosition","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","abstract":[],"type":"topic","navigatorTitle":[{"text":"MoreMessagePosition","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"ChatAppearance","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatappearance","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAppearance"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance","title":"ChatAppearance","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance/moreMessageAlertPosition":{"title":"moreMessageAlertPosition","abstract":[{"type":"text","text":"The alert position on received lots of messages."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"moreMessageAlertPosition"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/chatappearance\/moremessagealertposition","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/moreMessageAlertPosition","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"moreMessageAlertPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MoreMessagePosition","preciseIdentifier":"c:@M@EaseChatUIKit@E@MoreMessagePosition","kind":"typeIdentifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"moreMessageAlertPosition"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"moreMessageAlertPosition"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MoreMessagePosition","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MoreMessagePosition"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moreMessageAlertPosition"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/title","op":"replace","value":"MoreMessagePosition"},{"op":"replace","value":[{"kind":"identifier","text":"MoreMessagePosition"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/title","value":"ChatAppearance","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/fragments","value":[{"text":"ChatAppearance","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1moreMessageAlertPosition\/title","value":"moreMessageAlertPosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance~1moreMessageAlertPosition\/fragments","value":[{"text":"moreMessageAlertPosition","kind":"identifier"}]}]}]}