{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/targetLanguage","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"targetLanguage"},{"text":": ","kind":"text"},{"text":"LanguageType","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit12LanguageTypeO","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LanguageType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/chatappearance\/targetlanguage"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"targetLanguage","modules":[{"name":"EaseChatUIKit"}],"externalID":"s:13EaseChatUIKit0B10AppearanceC14targetLanguageAA0F4TypeOvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetLanguage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"LanguageType","preciseIdentifier":"s:13EaseChatUIKit12LanguageTypeO"}]},"kind":"symbol","abstract":[{"type":"text","text":"The mirror type of the language code of LanguageType."},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LanguageType","isActive":true,"type":"reference"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LanguageType":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LanguageType","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/languagetype","navigatorTitle":[{"text":"LanguageType","kind":"identifier"}],"abstract":[{"text":"https:\/\/learn.microsoft.com\/en-us\/azure\/ai-services\/translator\/language-support#translation","type":"text"}],"title":"LanguageType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LanguageType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance":{"navigatorTitle":[{"text":"ChatAppearance","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatappearance","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance","title":"ChatAppearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatAppearance"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatAppearance/targetLanguage":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"targetLanguage"},{"text":": ","kind":"text"},{"text":"LanguageType","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit12LanguageTypeO"}],"url":"\/documentation\/easechatuikit\/chatappearance\/targetlanguage","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatAppearance\/targetLanguage","abstract":[{"text":"The mirror type of the language code of LanguageType.","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LanguageType"}],"title":"targetLanguage","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ChatAppearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatAppearance"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatAppearance\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatAppearance"}]}]}]}