{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onInviterAcceptedInvitationOfGroup","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"text":"ID of the group.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user."}]}],"name":"userId"}],"kind":"parameters"}],"kind":"symbol","abstract":[{"text":"Accepted invitation of the group.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInviterAcceptedInvitationOfGroup","kind":"identifier"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","required":true,"externalID":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener(im)onInviterAcceptedInvitationOfGroupWithGroupId:userId:","navigatorTitle":[{"text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","kind":"identifier"}],"title":"onInviterAcceptedInvitationOfGroup(groupId:userId:)","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}]},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onInviterAcceptedInvitationOfGroup(groupId:userId:)":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Accepted invitation of the group."}],"navigatorTitle":[{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","title":"onInviterAcceptedInvitationOfGroup(groupId:userId:)","url":"\/documentation\/easechatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroup"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"GroupServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","url":"\/documentation\/easechatuikit\/groupservicelistener","title":"GroupServiceListener","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GroupServiceListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"userId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the user.","type":"text"}]}],"name":"userId"}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/title","value":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/title","value":"GroupServiceListener","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/fragments","value":[{"text":"GroupServiceListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/navigatorTitle","value":[{"text":"GroupServiceListener","kind":"identifier"}],"op":"replace"}]}]}