{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListRefresh()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationSwipe(type:info:)"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"ConversationListActionEventsDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"variants":[{"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/conversationlistactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/conversationlistactioneventsdelegate-implementations"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"]]},"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"type":"topic","title":"ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationDidSelected(indexPath:info:)":{"role":"symbol","navigatorTitle":[{"text":"onConversationDidSelectedWithIndexPath:info:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationDidSelected(indexPath:info:)","url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationdidselected(indexpath:info:)","title":"onConversationDidSelected(indexPath:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onConversationDidSelected","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Callback on conversation was selected."}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationSwipe(type:info:)":{"role":"symbol","navigatorTitle":[{"text":"onConversationSwipeWithType:info:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationSwipe(type:info:)","url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationswipe(type:info:)","title":"onConversationSwipe(type:info:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationSwipe","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"UIContextualActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Callback on conversation was swiped."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationListRefresh()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationListRefresh"},{"kind":"text","text":"()"}],"title":"onConversationListRefresh()","type":"topic","abstract":[{"type":"text","text":"Pull down to refresh"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlistrefresh()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onConversationListRefresh"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListRefresh()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationListEndScrollNeededDisplayInfos(ids:)":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlistendscrollneededdisplayinfos(ids:)","navigatorTitle":[{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfos","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)","kind":"symbol","title":"onConversationListEndScrollNeededDisplayInfos(ids:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationLongPressed(indexPath:info:)":{"url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlongpressed(indexpath:info:)","role":"symbol","navigatorTitle":[{"text":"onConversationLongPressedWithIndexPath:info:","kind":"identifier"}],"title":"onConversationLongPressed(indexPath:info:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","abstract":[{"text":"Callback on conversation was long pressed.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationLongPressed"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationListOccurErrorWhenFetchServer()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListOccurErrorWhenFetchServer()","url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlistoccurerrorwhenfetchserver()","title":"onConversationListOccurErrorWhenFetchServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListRefresh()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationSwipe(type:info:)"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"ConversationViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title"},{"value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationDidSelected(indexPath:info:)\/title","value":"onConversationDidSelectedWithIndexPath:info:"},{"value":[{"kind":"text","text":"- "},{"text":"onConversationDidSelectedWithIndexPath:info:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationDidSelected(indexPath:info:)\/fragments"},{"op":"replace","value":"onConversationSwipeWithType:info:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationSwipe(type:info:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationSwipeWithType:info:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationSwipe(type:info:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListRefresh()\/title","value":"onConversationListRefresh"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onConversationListRefresh","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListRefresh()\/fragments"},{"op":"replace","value":"onConversationListEndScrollNeededDisplayInfosWithIds:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListEndScrollNeededDisplayInfos(ids:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListEndScrollNeededDisplayInfos(ids:)\/fragments"},{"value":"onConversationLongPressedWithIndexPath:info:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationLongPressed(indexPath:info:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationLongPressed(indexPath:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListOccurErrorWhenFetchServer()\/title","op":"replace","value":"onConversationListOccurErrorWhenFetchServer"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListOccurErrorWhenFetchServer()\/fragments","value":[{"kind":"text","text":"- "},{"text":"onConversationListOccurErrorWhenFetchServer","kind":"identifier"}],"op":"replace"}]}]}