{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/conversationmessagealreadyreadonotherdevice(info:)"]},{"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/conversationmessagealreadyreadonotherdevice(info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationMessageAlreadyReadOnOtherDevice(info:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"conversationMessageAlreadyReadOnOtherDevice(info:)","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationMessageAlreadyReadOnOtherDevice","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationViewModel(im)conversationMessageAlreadyReadOnOtherDeviceWithInfo:","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationMessageAlreadyReadOnOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/conversationMessageAlreadyReadOnOtherDevice(info:)":{"url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationmessagealreadyreadonotherdevice(info:)","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationMessageAlreadyReadOnOtherDevice(info:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationMessageAlreadyReadOnOtherDevice","kind":"identifier"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"conversationMessageAlreadyReadOnOtherDevice(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"type":"topic","title":"ConversationInfo","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/conversationinfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"type":"topic","title":"ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationMessageAlreadyReadOnOtherDevice(info:)\/title","value":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationMessageAlreadyReadOnOtherDevice(info:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title","value":"ConversationInfo"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}