{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationServiceListener-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onChatConversationListDidChanged(list:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationMessageAlreadyReadOnOtherDevice(info:)"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","title":"ConversationServiceListener Implementations","role":"collectionGroup"},"variants":[{"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/conversationservicelistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/conversationservicelistener-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationLastMessageUpdate(message:info:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationLastMessageUpdate(message:info:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onConversationLastMessageUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onConversationLastMessageUpdateWithMessage:info:"}],"kind":"symbol","title":"onConversationLastMessageUpdate(message:info:)","role":"symbol","abstract":[{"text":"The last message of conversation changes.","type":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlastmessageupdate(message:info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationMessageAlreadyReadOnOtherDevice(info:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationMessageAlreadyReadOnOtherDevice(info:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationMessageAlreadyReadOnOtherDevice"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onConversationMessageAlreadyReadOnOtherDeviceWithInfo:","kind":"identifier"}],"kind":"symbol","title":"onConversationMessageAlreadyReadOnOtherDevice(info:)","role":"symbol","abstract":[{"text":"The read status of the conversation message changes.","type":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationmessagealreadyreadonotherdevice(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onChatConversationListDidChanged(list:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onChatConversationListDidChanged(list:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onChatConversationListDidChanged"},{"text":"(","kind":"text"},{"text":"list","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onChatConversationListDidChangedWithList:"}],"kind":"symbol","title":"onChatConversationListDidChanged(list:)","role":"symbol","abstract":[{"text":"When conversation list updated.","type":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/onchatconversationlistdidchanged(list:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"url":"\/documentation\/easechatuikit\/conversationviewmodel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Bind service and driver"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewModel"}],"title":"ConversationViewModel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onChatConversationListDidChanged(list:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationMessageAlreadyReadOnOtherDevice(info:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"onConversationLastMessageUpdateWithMessage:info:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationLastMessageUpdate(message:info:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationLastMessageUpdateWithMessage:info:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationLastMessageUpdate(message:info:)\/fragments"},{"value":"onConversationMessageAlreadyReadOnOtherDeviceWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationMessageAlreadyReadOnOtherDevice(info:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationMessageAlreadyReadOnOtherDevice(info:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onConversationMessageAlreadyReadOnOtherDeviceWithInfo:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onChatConversationListDidChanged(list:)\/title","value":"onChatConversationListDidChangedWithList:"},{"value":[{"text":"- ","kind":"text"},{"text":"onChatConversationListDidChangedWithList:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onChatConversationListDidChanged(list:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","value":[{"kind":"identifier","text":"ConversationViewModel"}]}]}]}