{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/firstLoadConversation"},"metadata":{"title":"firstLoadConversation","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstLoadConversation","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit21ConversationViewModelC09firstLoadD0Sbvp"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"firstLoadConversation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { get }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/firstloadconversation"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/firstLoadConversation":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/firstLoadConversation","kind":"symbol","title":"firstLoadConversation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"firstLoadConversation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/firstloadconversation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"kind":"symbol","title":"ConversationViewModel","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationViewModel","kind":"identifier"}],"abstract":[{"text":"Bind service and driver","type":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel","navigatorTitle":[{"kind":"identifier","text":"ConversationViewModel"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","op":"replace","value":"ConversationViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","op":"replace","value":[{"text":"ConversationViewModel","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ConversationViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/navigatorTitle"}]}]}