{"sections":[],"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"mapperWithObjects:","kind":"identifier"}],"title":"mapper(objects:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mapper"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"objects"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatConversation","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"text":"]) -> [","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":"]","kind":"text"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationViewModel(im)mapperWithObjects:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mapper(objects:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/mapper(objects:)"]},{"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/mapper(objects:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapper"},{"kind":"text","text":"("},{"kind":"externalParam","text":"objects"},{"text":": [","kind":"text"},{"text":"ChatConversation","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"kind":"text","text":"]) -> ["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"typeIdentifier","text":"ConversationInfo"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"navigatorTitle":[{"kind":"identifier","text":"ConversationInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/conversationinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"symbol","type":"topic","title":"ConversationInfo","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"url":"\/documentation\/easechatuikit\/conversationviewmodel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Bind service and driver"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewModel"}],"title":"ConversationViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/mapper(objects:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mapper(objects:)","kind":"symbol","title":"mapper(objects:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mapper"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"objects"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","text":"ChatConversation"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"]"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/mapper(objects:)","navigatorTitle":[{"text":"mapperWithObjects:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatConversation":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatConversation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatConversation"}],"title":"ChatConversation","type":"topic","url":"\/documentation\/easechatuikit\/chatconversation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","role":"symbol","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"mapperWithObjects:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mapperWithObjects:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<ConversationInfo *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mapperWithObjects:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<EMConversation *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"objects","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"ConversationInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title"},{"value":[{"text":"ConversationInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","value":[{"text":"ConversationViewModel","kind":"identifier"}]},{"value":"mapperWithObjects:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1mapper(objects:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1mapper(objects:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mapperWithObjects:"}]}]}]}