{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onChatConversationListDidChanged(list:)"},"abstract":[{"text":"When conversation list updated.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationServiceListener-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onChatConversationListDidChanged"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"list"},{"text":": [","kind":"text"},{"text":"ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"list","content":[{"type":"paragraph","inlineContent":[{"text":"Array of session objects.","type":"text"}]}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onChatConversationListDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"list"},{"text":": [","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":"])","kind":"text"}],"roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","title":"onChatConversationListDidChanged(list:)","externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationViewModel(im)onChatConversationListDidChangedWithList:","role":"symbol","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"onChatConversationListDidChangedWithList:","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/onchatconversationlistdidchanged(list:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/onchatconversationlistdidchanged(list:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/ConversationServiceListener-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationServiceListener-Implementations","kind":"article","url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationservicelistener-implementations","type":"topic","role":"collectionGroup","title":"ConversationServiceListener Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onChatConversationListDidChanged(list:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onChatConversationListDidChanged(list:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onChatConversationListDidChanged"},{"text":"(","kind":"text"},{"text":"list","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":"])"}],"navigatorTitle":[{"kind":"identifier","text":"onChatConversationListDidChangedWithList:"}],"kind":"symbol","title":"onChatConversationListDidChanged(list:)","role":"symbol","abstract":[{"text":"When conversation list updated.","type":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/onchatconversationlistdidchanged(list:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"url":"\/documentation\/easechatuikit\/conversationviewmodel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Bind service and driver"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewModel"}],"title":"ConversationViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"navigatorTitle":[{"kind":"identifier","text":"ConversationInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/conversationinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"symbol","type":"topic","title":"ConversationInfo","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onChatConversationListDidChangedWithList:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onChatConversationListDidChangedWithList:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onChatConversationListDidChangedWithList:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<ConversationInfo *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"list","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"onChatConversationListDidChangedWithList:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onChatConversationListDidChanged(list:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatConversationListDidChangedWithList:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onChatConversationListDidChanged(list:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel","op":"replace"},{"op":"replace","value":[{"text":"ConversationViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title","value":"ConversationInfo"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}