{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfos","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ids","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"[conversationId]"}],"type":"paragraph"}],"name":"ids"}]}],"metadata":{"title":"onConversationListEndScrollNeededDisplayInfos(ids:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfos","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"symbolKind":"method","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationViewModel(im)onConversationListEndScrollNeededDisplayInfosWithIds:","roleHeading":"Instance Method","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlistendscrollneededdisplayinfos(ids:)"]},{"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlistendscrollneededdisplayinfos(ids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations"]]},"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationListEndScrollNeededDisplayInfos(ids:)":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationlistendscrollneededdisplayinfos(ids:)","navigatorTitle":[{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfos","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationListEndScrollNeededDisplayInfos(ids:)","kind":"symbol","title":"onConversationListEndScrollNeededDisplayInfos(ids:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"type":"topic","title":"ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/ConversationListActionEventsDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationlistactioneventsdelegate-implementations","role":"collectionGroup","title":"ConversationListActionEventsDelegate Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"onConversationListEndScrollNeededDisplayInfosWithIds:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onConversationListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ids"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListEndScrollNeededDisplayInfos(ids:)\/title","value":"onConversationListEndScrollNeededDisplayInfosWithIds:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationListEndScrollNeededDisplayInfos(ids:)\/fragments","op":"replace"},{"value":"ConversationViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationViewModel"}]}]}]}