{"abstract":[{"text":"When a event of conversation changes on other devices","type":"text"}],"metadata":{"extendedModule":"EaseChatUIKit","title":"onConversationEventDidChanged(event:conversationId:conversationType:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationEventDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"conversationType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationViewModel(im)onConversationEventDidChangedWithEvent:conversationId:conversationType:","symbolKind":"method"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationEventDidChanged(event:conversationId:conversationType:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/MultiDeviceListener-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationEventDidChanged"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","kind":"typeIdentifier","text":"MultiDeviceEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"conversationType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType","text":"ChatConversationType"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","isActive":true}]}],"name":"event"},{"name":"conversationId","content":[{"type":"paragraph","inlineContent":[{"text":"The id of the group.","type":"text"}]}]},{"name":"conversationType","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType"},{"text":".","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/onconversationeventdidchanged(event:conversationid:conversationtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/onconversationeventdidchanged(event:conversationid:conversationtype:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/onConversationEventDidChanged(event:conversationId:conversationType:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/onConversationEventDidChanged(event:conversationId:conversationType:)","type":"topic","title":"onConversationEventDidChanged(event:conversationId:conversationType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onConversationEventDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"conversationType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea"},{"text":")","kind":"text"}],"abstract":[{"text":"When a event of conversation changes on other devices","type":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/onconversationeventdidchanged(event:conversationid:conversationtype:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"type":"topic","title":"ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/MultiDeviceListener-Implementations":{"url":"\/documentation\/easechatuikit\/conversationviewmodel\/multidevicelistener-implementations","kind":"article","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/MultiDeviceListener-Implementations","role":"collectionGroup","type":"topic","title":"MultiDeviceListener Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceEvent":{"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"title":"MultiDeviceEvent","url":"\/documentation\/easechatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"MultiDeviceEvent","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatConversationType":{"title":"ChatConversationType","navigatorTitle":[{"text":"ChatConversationType","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatConversationType"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatconversationtype","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onConversationEventDidChangedWithEvent:conversationId:conversationType:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onConversationEventDidChangedWithEvent:","kind":"identifier"},{"kind":"text","text":"("},{"text":"EMMultiDevicesEvent","preciseIdentifier":"c:@E@EMMultiDevicesEvent","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"event","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"conversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"kind":"text","text":" "},{"text":"conversationType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@EMConversationType","text":"EMConversationType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"conversationType"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationEventDidChanged(event:conversationId:conversationType:)\/title","op":"replace","value":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1onConversationEventDidChanged(event:conversationId:conversationType:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onConversationEventDidChangedWithEvent:conversationId:conversationType:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace"}]}]}