{"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"welcomeMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"}],"navigatorTitle":[{"kind":"identifier","text":"welcomeMessageWithConversationId:text:"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationViewModel(im)welcomeMessageWithConversationId:text:","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","title":"welcomeMessage(conversationId:text:)","roleHeading":"Instance Method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/welcomeMessage(conversationId:text:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/welcomemessage(conversationid:text:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationviewmodel\/welcomemessage(conversationid:text:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"welcomeMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/welcomeMessage(conversationId:text:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"welcomeMessageWithConversationId:text:","kind":"identifier"}],"type":"topic","abstract":[],"title":"welcomeMessage(conversationId:text:)","url":"\/documentation\/easechatuikit\/conversationviewmodel\/welcomemessage(conversationid:text:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/welcomeMessage(conversationId:text:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"welcomeMessage"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"url":"\/documentation\/easechatuikit\/conversationviewmodel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Bind service and driver"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewModel"}],"title":"ConversationViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","abstract":[],"title":"ChatMessage","url":"\/documentation\/easechatuikit\/chatmessage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessage","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"welcomeMessageWithConversationId:text:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"welcomeMessageWithConversationId:text:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"EMChatMessage","preciseIdentifier":"c:objc(cs)EMChatMessage"},{"kind":"text","text":" *) "},{"text":"welcomeMessageWithConversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"conversationId"},{"text":" ","kind":"text"},{"text":"text:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"text","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"welcomeMessageWithConversationId:text:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1welcomeMessage(conversationId:text:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"welcomeMessageWithConversationId:text:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1welcomeMessage(conversationId:text:)\/fragments"},{"op":"replace","value":"ConversationViewModel","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","op":"replace","value":[{"text":"ConversationViewModel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}