{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"contact","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"EaseProfileProviderTypeContact","kind":"identifier"}],"title":"EaseProfileProviderType.contact","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contact"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@EaseProfileProviderType@EaseProfileProviderTypeContact","roleHeading":"Case"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProviderType"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProviderType\/contact","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/easeprofileprovidertype\/contact"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/easeprofileprovidertype\/contact"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProviderType/contact":{"navigatorTitle":[{"kind":"identifier","text":"EaseProfileProviderTypeContact"}],"title":"EaseProfileProviderType.contact","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProviderType\/contact","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contact"}],"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/easeprofileprovidertype\/contact","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProviderType":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProviderType","kind":"symbol","url":"\/documentation\/easechatuikit\/easeprofileprovidertype","abstract":[],"title":"EaseProfileProviderType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"EaseProfileProviderType","kind":"identifier"}],"navigatorTitle":[{"text":"EaseProfileProviderType","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"EaseProfileProviderTypeContact","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"EaseProfileProviderTypeContact"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"EaseProfileProviderTypeContact","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"EaseProfileProviderTypeContact","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProviderType~1contact\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProviderType~1contact\/fragments","value":[{"text":"EaseProfileProviderTypeContact","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProviderType\/title","value":"EaseProfileProviderType"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProviderType\/fragments","op":"replace","value":[{"text":"EaseProfileProviderType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}