{"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","kind":"typeIdentifier","text":"UICollectionViewFlowLayout"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatNavigationBar(py)layout","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"layout"}],"title":"layout","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/layout","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/layout"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/layout"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","kind":"typeIdentifier","text":"UICollectionViewFlowLayout"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar/layout":{"url":"\/documentation\/easechatuikit\/chatnavigationbar\/layout","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/layout","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","text":"UICollectionViewFlowLayout"}],"navigatorTitle":[{"kind":"identifier","text":"layout"}],"kind":"symbol","type":"topic","title":"layout"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar","navigatorTitle":[{"text":"ChatNavigationBar","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/chatnavigationbar","title":"ChatNavigationBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"layout"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"layout","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UICollectionViewFlowLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"},{"kind":"text","text":" * "},{"text":"layout","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1layout\/title","op":"replace","value":"layout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1layout\/fragments","value":[{"text":"layout","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/title","value":"ChatNavigationBar"},{"value":[{"text":"ChatNavigationBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/navigatorTitle","value":[{"text":"ChatNavigationBar","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}