{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/titleOriginFrame"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleOriginFrame"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"titleOriginFrame"}],"title":"titleOriginFrame","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatNavigationBar(py)titleOriginFrame","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"titleOriginFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/titleoriginframe"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/titleoriginframe"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar/titleOriginFrame":{"role":"symbol","title":"titleOriginFrame","url":"\/documentation\/easechatuikit\/chatnavigationbar\/titleoriginframe","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/titleOriginFrame","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"titleOriginFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"titleOriginFrame","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar","navigatorTitle":[{"text":"ChatNavigationBar","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/chatnavigationbar","title":"ChatNavigationBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"titleOriginFrame","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"titleOriginFrame","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"titleOriginFrame"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1titleOriginFrame\/title","value":"titleOriginFrame"},{"op":"replace","value":[{"kind":"identifier","text":"titleOriginFrame"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1titleOriginFrame\/fragments"},{"value":"ChatNavigationBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/title"},{"value":[{"text":"ChatNavigationBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/navigatorTitle","value":[{"kind":"identifier","text":"ChatNavigationBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}