{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/UICollectionViewDelegate-Implementations"},"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:didSelectItemAt:)"]}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/uicollectionviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/uicollectionviewdelegate-implementations"]}],"kind":"article","metadata":{"role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"UICollectionViewDelegate Implementations","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar/collectionView(_:didSelectItemAt:)":{"role":"symbol","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:didSelectItemAt:)","title":"collectionView(_:didSelectItemAt:)","url":"\/documentation\/easechatuikit\/chatnavigationbar\/collectionview(_:didselectitemat:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didSelectItemAt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar","navigatorTitle":[{"text":"ChatNavigationBar","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/chatnavigationbar","title":"ChatNavigationBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:didSelectItemAt:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":"collectionView:didSelectItemAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1collectionView(_:didSelectItemAt:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1collectionView(_:didSelectItemAt:)\/fragments"},{"value":"ChatNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/fragments","value":[{"text":"ChatNavigationBar","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/navigatorTitle","value":[{"text":"ChatNavigationBar","kind":"identifier"}]}]}]}