{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"UICollectionViewDataSource Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/uicollectionviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatnavigationbar\/uicollectionviewdatasource-implementations"]}],"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:numberOfItemsInSection:)"],"anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar"]]},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/UICollectionViewDataSource-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar","navigatorTitle":[{"text":"ChatNavigationBar","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/chatnavigationbar","title":"ChatNavigationBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar/collectionView(_:cellForItemAt:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/chatnavigationbar\/collectionview(_:cellforitemat:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:cellForItemAt:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"title":"collectionView(_:cellForItemAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"cellForItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar/collectionView(_:numberOfItemsInSection:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/chatnavigationbar\/collectionview(_:numberofitemsinsection:)","title":"collectionView(_:numberOfItemsInSection:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"numberOfItemsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:numberOfItemsInSection:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar\/collectionView(_:numberOfItemsInSection:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/title","op":"replace","value":"ChatNavigationBar"},{"op":"replace","value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/fragments"},{"value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/navigatorTitle","op":"replace"},{"value":"collectionView:cellForItemAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1collectionView(_:cellForItemAt:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1collectionView(_:cellForItemAt:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"op":"replace"},{"value":"collectionView:numberOfItemsInSection:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1collectionView(_:numberOfItemsInSection:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar~1collectionView(_:numberOfItemsInSection:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}