{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetState\/forwarded","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetState"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"forwarded"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/forwardtargetstate\/forwarded"]},{"paths":["\/documentation\/easechatuikit\/forwardtargetstate\/forwarded"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","roleHeading":"Case","role":"symbol","title":"ForwardTargetState.forwarded","externalID":"c:@M@EaseChatUIKit@E@ForwardTargetState@ForwardTargetStateForwarded","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"forwarded","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ForwardTargetStateForwarded"}]},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetState/forwarded":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"forwarded","kind":"identifier"}],"title":"ForwardTargetState.forwarded","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetState\/forwarded","navigatorTitle":[{"text":"ForwardTargetStateForwarded","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/forwardtargetstate\/forwarded","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetState":{"abstract":[],"url":"\/documentation\/easechatuikit\/forwardtargetstate","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForwardTargetState"}],"title":"ForwardTargetState","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ForwardTargetState"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetState","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"ForwardTargetStateForwarded","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ForwardTargetStateForwarded"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"ForwardTargetStateForwarded","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"ForwardTargetStateForwarded","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetState~1forwarded\/title"},{"value":[{"kind":"identifier","text":"ForwardTargetStateForwarded"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetState~1forwarded\/fragments","op":"replace"},{"value":"ForwardTargetState","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetState\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetState\/fragments","value":[{"kind":"identifier","text":"ForwardTargetState"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}