{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unbindContactEventListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactEventsResponse","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEventsResponse"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"unbindContactEventListenerWithListener:"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)ContactServiceProtocol(im)unbindContactEventListenerWithListener:","symbolKind":"method","roleHeading":"Instance Method","title":"unbindContactEventListener(listener:)"},"abstract":[{"type":"text","text":"Unbind contacts state changed listener"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unbindContactEventListener(listener:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindContactEventListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEventsResponse","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse","text":"ContactEventsResponse"},{"text":")","kind":"text"}]}]},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactserviceprotocol\/unbindcontacteventlistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactserviceprotocol\/unbindcontacteventlistener(listener:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/unbindContactEventListener(listener:)":{"url":"\/documentation\/easechatuikit\/contactserviceprotocol\/unbindcontacteventlistener(listener:)","abstract":[{"type":"text","text":"Unbind contacts state changed listener"}],"role":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindContactEventListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ContactEventsResponse","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEventsResponse"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"unbindContactEventListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"unbindContactEventListenerWithListener:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unbindContactEventListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEventsResponse":{"abstract":[],"url":"\/documentation\/easechatuikit\/contacteventsresponse","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEventsResponse","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse","kind":"symbol","type":"topic","title":"ContactEventsResponse","navigatorTitle":[{"kind":"identifier","text":"ContactEventsResponse"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactServiceProtocol","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol","title":"ContactServiceProtocol","url":"\/documentation\/easechatuikit\/contactserviceprotocol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ContactServiceProtocol","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"unbindContactEventListenerWithListener:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unbindContactEventListenerWithListener:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"unbindContactEventListenerWithListener:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ContactEventsResponse","text":"id<ContactEventsResponse>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"unbindContactEventListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1unbindContactEventListener(listener:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1unbindContactEventListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unbindContactEventListenerWithListener:","kind":"identifier"}],"op":"replace"},{"value":"ContactEventsResponse","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse\/title"},{"op":"replace","value":[{"text":"ContactEventsResponse","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse\/fragments"},{"value":"ContactServiceProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ContactServiceProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}