{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/datas"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"datas","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/datas"]},{"paths":["\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/datas"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"title":"datas","navigatorTitle":[{"kind":"identifier","text":"datas"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)JoinedGroupsViewController(py)datas","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"datas","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}]},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController/datas":{"title":"datas","url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/datas","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"datas","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/datas","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"datas","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":"]","kind":"text"}],"type":"topic","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController":{"navigatorTitle":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoinedGroupsViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController","kind":"symbol","title":"JoinedGroupsViewController","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProtocol":{"abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatuserprofileprotocol","role":"symbol","title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"datas"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"datas","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<ChatUserProfileProtocol>>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"datas"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1datas\/title","op":"replace","value":"datas"},{"value":[{"text":"datas","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1datas\/fragments","op":"replace"},{"value":"JoinedGroupsViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/fragments","value":[{"text":"JoinedGroupsViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/navigatorTitle","value":[{"text":"JoinedGroupsViewController","kind":"identifier"}]},{"op":"replace","value":"ChatUserProfileProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/title"},{"value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}