{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/requestGroups()"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/requestgroups()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/requestgroups()"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"requestGroups","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestGroups"},{"kind":"text","text":"()"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)JoinedGroupsViewController(im)requestGroups","title":"requestGroups()","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestGroups"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController/requestGroups()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"requestGroups","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"title":"requestGroups()","role":"symbol","navigatorTitle":[{"text":"requestGroups","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/requestgroups()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/requestGroups()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController":{"navigatorTitle":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoinedGroupsViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController","kind":"symbol","title":"JoinedGroupsViewController","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"requestGroups"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestGroups"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"requestGroups","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"requestGroups","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1requestGroups()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1requestGroups()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestGroups"}],"op":"replace"},{"value":"JoinedGroupsViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/fragments","value":[{"kind":"identifier","text":"JoinedGroupsViewController"}]},{"op":"replace","value":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/navigatorTitle"}]}]}