{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"UITableViewDataSource Implementations","role":"collectionGroup","roleHeading":"API Collection"},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/tableView(_:numberOfRowsInSection:)"],"title":"Instance Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController"]]},"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController/tableView(_:numberOfRowsInSection:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/tableView(_:numberOfRowsInSection:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"title":"tableView(_:numberOfRowsInSection:)","kind":"symbol","url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/tableview(_:numberofrowsinsection:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController/tableView(_:cellForRowAt:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller\/tableview(_:cellforrowat:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/tableView(_:cellForRowAt:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"title":"tableView(_:cellForRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cellForRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController":{"navigatorTitle":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"JoinedGroupsViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController","kind":"symbol","title":"JoinedGroupsViewController","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController\/tableView(_:numberOfRowsInSection:)"],"title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"tableView:numberOfRowsInSection:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1tableView(_:numberOfRowsInSection:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController~1tableView(_:cellForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/title","value":"JoinedGroupsViewController","op":"replace"},{"value":[{"kind":"identifier","text":"JoinedGroupsViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/fragments"},{"value":[{"kind":"identifier","text":"JoinedGroupsViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}