{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ActionSheetItemType","kind":"identifier"}],"navigatorTitle":[{"text":"ActionSheetItemType","kind":"identifier"}],"title":"ActionSheetItemType","externalID":"c:@M@EaseChatUIKit@E@ActionSheetItemType"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionSheetItemType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/actionsheetitemtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/actionsheetitemtype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/destructive","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/normal"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType/init(rawValue:)":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/actionsheetitemtype\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/init(rawValue:)"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","navigatorTitle":[{"text":"ActionSheetItemType","kind":"identifier"}],"abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionSheetItemType","kind":"identifier"}],"title":"ActionSheetItemType","role":"symbol","url":"\/documentation\/easechatuikit\/actionsheetitemtype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType/destructive":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"destructive"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}],"url":"\/documentation\/easechatuikit\/actionsheetitemtype\/destructive","kind":"symbol","title":"ActionSheetItemType.destructive","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/destructive"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType/normal":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}],"navigatorTitle":[{"text":"ActionSheetItemTypeNormal","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/actionsheetitemtype\/normal","kind":"symbol","title":"ActionSheetItemType.normal","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/normal"},"doc://org.cocoapods.EaseChatUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType/RawRepresentable-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/easechatuikit\/actionsheetitemtype\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/RawRepresentable-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType/Equatable-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/easechatuikit\/actionsheetitemtype\/equatable-implementations","kind":"article","title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/Equatable-Implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"value":"ActionSheetItemType","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemType"}]},{"value":[{"text":"ActionSheetItemType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/destructive","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType\/normal"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionSheetItemType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/title","value":"ActionSheetItemType"},{"value":[{"text":"ActionSheetItemType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType~1destructive\/title","value":"ActionSheetItemTypeDestructive","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType~1destructive\/fragments","op":"replace","value":[{"kind":"identifier","text":"ActionSheetItemTypeDestructive"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType~1normal\/title","value":"ActionSheetItemTypeNormal"},{"value":[{"kind":"identifier","text":"ActionSheetItemTypeNormal"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType~1normal\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}