{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/large","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/small"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/RawRepresentable-Implementations"],"generated":true}],"metadata":{"externalID":"c:@M@EaseChatUIKit@E@AlertStyle","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"title":"AlertStyle","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertStyle","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AlertStyle"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AlertStyle","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/alertstyle"]},{"paths":["\/documentation\/easechatuikit\/alertstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/init(rawValue:)","url":"\/documentation\/easechatuikit\/alertstyle\/init(rawvalue:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"init(rawValue:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle/small":{"url":"\/documentation\/easechatuikit\/alertstyle\/small","type":"topic","abstract":[],"role":"symbol","title":"AlertStyle.small","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"small","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/small","navigatorTitle":[{"text":"AlertStyleSmall","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle/large":{"url":"\/documentation\/easechatuikit\/alertstyle\/large","type":"topic","abstract":[],"role":"symbol","kind":"symbol","title":"AlertStyle.large","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"large","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/large","navigatorTitle":[{"text":"AlertStyleLarge","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle/RawRepresentable-Implementations":{"url":"\/documentation\/easechatuikit\/alertstyle\/rawrepresentable-implementations","type":"topic","abstract":[],"role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/RawRepresentable-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle/Equatable-Implementations":{"url":"\/documentation\/easechatuikit\/alertstyle\/equatable-implementations","type":"topic","abstract":[],"role":"collectionGroup","title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/Equatable-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle":{"navigatorTitle":[{"kind":"identifier","text":"AlertStyle"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle","title":"AlertStyle","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertStyle","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/alertstyle","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"AlertStyle"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"AlertStyle"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AlertStyle"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/large","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle\/small"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertStyle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"AlertStyleSmall","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle~1small\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle~1small\/fragments","op":"replace","value":[{"kind":"identifier","text":"AlertStyleSmall"}]},{"value":"AlertStyleLarge","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle~1large\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle~1large\/fragments","op":"replace","value":[{"kind":"identifier","text":"AlertStyleLarge"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle\/title","value":"AlertStyle","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AlertStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle\/fragments"}]}]}