{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/alertmessagecell"]},{"paths":["\/documentation\/easechatuikit\/alertmessagecell"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell"},"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertMessageCell","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"text":"AlertMessageCell","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"class","externalID":"c:@M@EaseChatUIKit@objc(cs)AlertMessageCell","title":"AlertMessageCell","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/init(towards:reuseIdentifier:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/content","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/time"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/layoutSubviews()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/refresh(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/switchTheme(style:)"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertMessageCell","kind":"identifier"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIDynamicItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/switchTheme(style:)":{"url":"\/documentation\/easechatuikit\/alertmessagecell\/switchtheme(style:)","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"abstract":[{"type":"text","text":"Switches the theme of the cell."}],"type":"topic","title":"switchTheme(style:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/switchTheme(style:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier","text":"ThemeStyle"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/time":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"time","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier","text":"UILabel"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"time"}],"title":"time","abstract":[],"url":"\/documentation\/easechatuikit\/alertmessagecell\/time","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/time","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearance":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","title":"UIKit.UIAppearance"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell":{"title":"AlertMessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertMessageCell","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/alertmessagecell","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AlertMessageCell"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIGestureRecognizerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/init(towards:reuseIdentifier:)":{"title":"init(towards:reuseIdentifier:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/init(towards:reuseIdentifier:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/alertmessagecell\/init(towards:reuseidentifier:)","abstract":[{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell"},{"type":"text","text":" required init method."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/content":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"content"},{"text":": ","kind":"text"},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"}],"type":"topic","abstract":[],"title":"content","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/alertmessagecell\/content","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/content"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/init(coder:)":{"role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"init(coder:)","url":"\/documentation\/easechatuikit\/alertmessagecell\/init(coder:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/init(coder:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/layoutSubviews()":{"url":"\/documentation\/easechatuikit\/alertmessagecell\/layoutsubviews()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/layoutSubviews()","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"kind":"symbol","title":"layoutSubviews()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/refresh(entity:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/easechatuikit\/alertmessagecell\/refresh(entity:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/refresh(entity:)","navigatorTitle":[{"text":"refreshWithEntity:","kind":"identifier"}],"abstract":[{"type":"text","text":"Refresh cell with "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","isActive":true,"type":"reference"}],"title":"refresh(entity:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"abstract":[{"text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit.","type":"text"}],"url":"\/documentation\/easechatuikit\/themeswitchprotocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","role":"symbol","title":"ThemeSwitchProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCell","kind":"identifier"}],"kind":"symbol","title":"MessageCell","url":"\/documentation\/easechatuikit\/messagecell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messageentity","title":"MessageEntity","navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AlertMessageCell"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AlertMessageCell"}]},{"value":[{"text":"AlertMessageCell","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/content","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/time"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/init(towards:reuseIdentifier:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/layoutSubviews()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/refresh(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/switchTheme(style:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertMessageCell","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1switchTheme(style:)\/title","op":"replace","value":"switchThemeWithStyle:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1switchTheme(style:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}]},{"value":"time","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1time\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1time\/fragments","value":[{"text":"time","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell\/title","op":"replace","value":"AlertMessageCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"AlertMessageCell"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1init(towards:reuseIdentifier:)\/title","value":"initWithTowards:reuseIdentifier:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTowards:reuseIdentifier:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1init(towards:reuseIdentifier:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1content\/title","value":"content"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1content\/fragments","value":[{"kind":"identifier","text":"content"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1init(coder:)\/fragments"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1layoutSubviews()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1refresh(entity:)\/title","value":"refreshWithEntity:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithEntity:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1refresh(entity:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace"},{"value":"MessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","value":[{"kind":"identifier","text":"MessageCell"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title","value":"MessageEntity"},{"value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}