{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/actionSheetRowHeight","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertContainerConstraintsSize","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertStyle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/avatarPlaceHolder","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/avatarRadius","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/chat","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/contact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/conversation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/ease_chat_language","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/errorHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/hiddenPresence","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/neutralHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/neutralSpecialHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/pageContainerConstraintsSize","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/pageContainerTitleBarItemWidth","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/primaryHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/secondaryHue"],"title":"Type Properties"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"title":"Appearance","externalID":"c:@M@EaseChatUIKit@objc(cs)Appearance","role":"symbol","roleHeading":"Class","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance"},"abstract":[{"text":"An object containing visual configurations for the whole application.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Appearance","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/appearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/appearance"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/avatarPlaceHolder":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/avatarPlaceHolder","url":"\/documentation\/easechatuikit\/appearance\/avatarplaceholder","abstract":[{"type":"text","text":"The placeholder image of the avatar image view of "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","type":"reference","isActive":true},{"text":".","type":"text"}],"navigatorTitle":[{"text":"avatarPlaceHolder","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avatarPlaceHolder"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","title":"avatarPlaceHolder"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainersDialogController":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController","abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"url":"\/documentation\/easechatuikit\/pagecontainersdialogcontroller","navigatorTitle":[{"text":"PageContainersDialogController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainersDialogController"}],"type":"topic","kind":"symbol","title":"PageContainersDialogController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertViewController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AlertViewController"}],"type":"topic","title":"AlertViewController","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AlertViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertViewController","url":"\/documentation\/easechatuikit\/alertviewcontroller","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/neutralHue":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/neutralHue","url":"\/documentation\/easechatuikit\/appearance\/neutralhue","abstract":[{"type":"text","text":"You can change the neutral hue. The default value is 203\/360.0."},{"text":" ","type":"text"},{"type":"text","text":"After the neutral hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the related color series in the ease chat UIKit will also change accordingly."}],"navigatorTitle":[{"text":"neutralHue","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"neutralHue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","kind":"symbol","title":"neutralHue"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/alertStyle":{"navigatorTitle":[{"text":"alertStyle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The corner radius of the alert view."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertStyle","title":"alertStyle","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"alertStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"AlertStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@AlertStyle"}],"role":"symbol","url":"\/documentation\/easechatuikit\/appearance\/alertstyle","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCell","kind":"identifier"}],"kind":"symbol","title":"MessageCell","url":"\/documentation\/easechatuikit\/messagecell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/hiddenPresence":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/hiddenPresence","url":"\/documentation\/easechatuikit\/appearance\/hiddenpresence","abstract":[],"navigatorTitle":[{"text":"hiddenPresence","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hiddenPresence","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","title":"hiddenPresence"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/primaryHue":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/primaryHue","abstract":[{"text":"You can change the hue of the base color, and then change the thirteen UIColor objects of the related color series. The UI components that use the relevant color series in the ease chat UIKit will also change accordingly. The default value is 203\/360.0.","type":"text"}],"url":"\/documentation\/easechatuikit\/appearance\/primaryhue","navigatorTitle":[{"text":"primaryHue","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"primaryHue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"type":"topic","kind":"symbol","title":"primaryHue"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"title":"AlertView","abstract":[],"url":"\/documentation\/easechatuikit\/alertview","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/ease_chat_language":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/ease_chat_language","url":"\/documentation\/easechatuikit\/appearance\/ease_chat_language","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ease_chat_language","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LanguageType","preciseIdentifier":"s:13EaseChatUIKit12LanguageTypeO","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","title":"ease_chat_language"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/errorHue":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/errorHue","type":"topic","title":"errorHue","role":"symbol","navigatorTitle":[{"text":"errorHue","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorHue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/appearance\/errorhue","abstract":[{"text":"You can change the secondary hue. The default value is 155\/360.0.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"After the secondary hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the related color series in the ease chat UIKit will also change accordingly."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/avatarRadius":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/avatarRadius","title":"avatarRadius","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"avatarRadius","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit12CornerRadiusO","text":"CornerRadius","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/appearance\/avatarradius","abstract":[{"type":"text","text":"The corner radius of the avatar image view of "},{"type":"codeVoice","code":"ChatInputBar"},{"text":".","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/alertContainerConstraintsSize":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alertContainerConstraintsSize"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"abstract":[{"type":"text","text":"The size of alert container constraints."},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertViewController","type":"reference","isActive":true}],"url":"\/documentation\/easechatuikit\/appearance\/alertcontainerconstraintssize","title":"alertContainerConstraintsSize","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertContainerConstraintsSize","navigatorTitle":[{"text":"alertContainerConstraintsSize","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/neutralSpecialHue":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/neutralSpecialHue","type":"topic","title":"neutralSpecialHue","role":"symbol","navigatorTitle":[{"text":"neutralSpecialHue","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"neutralSpecialHue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/appearance\/neutralspecialhue","abstract":[{"text":"You can change the neutral special hue. The default value is 220\/360.0.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"After the neutral special hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the relevant color series in the ease chat UIKit will also change accordingly."}]},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/init":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/init","title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/easechatuikit\/appearance\/init","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/pageContainerConstraintsSize":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/pageContainerConstraintsSize","title":"pageContainerConstraintsSize","role":"symbol","navigatorTitle":[{"text":"pageContainerConstraintsSize","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"pageContainerConstraintsSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/appearance\/pagecontainerconstraintssize","abstract":[{"type":"text","text":"The size of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController"},{"text":" constraints.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/actionSheetRowHeight":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/actionSheetRowHeight","type":"topic","title":"actionSheetRowHeight","role":"symbol","navigatorTitle":[{"text":"actionSheetRowHeight","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"actionSheetRowHeight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"url":"\/documentation\/easechatuikit\/appearance\/actionsheetrowheight","abstract":[{"text":"ActionSheet row height.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/secondaryHue":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/secondaryHue","title":"secondaryHue","role":"symbol","navigatorTitle":[{"text":"secondaryHue","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"secondaryHue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/appearance\/secondaryhue","abstract":[{"text":"You can change the primary hue. The default value is 203\/360.0.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"After the primary hue is changed, thirteen UIColor objects of the related color series will be changed. The color of UI components that use the related color series in the ease chat UIKit will also change accordingly."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/chat":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"},{"text":": ","kind":"text"},{"text":"ChatAppearance","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatAppearance","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/chat","kind":"symbol","title":"chat","url":"\/documentation\/easechatuikit\/appearance\/chat","type":"topic","abstract":[{"text":"Chat Component","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"chat"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/pageContainerTitleBarItemWidth":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/pageContainerTitleBarItemWidth","title":"pageContainerTitleBarItemWidth","role":"symbol","navigatorTitle":[{"text":"pageContainerTitleBarItemWidth","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageContainerTitleBarItemWidth","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"url":"\/documentation\/easechatuikit\/appearance\/pagecontainertitlebaritemwidth","abstract":[{"type":"text","text":"You can change the width of a single option with "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar","isActive":true},{"text":" in the popup container by setting the current property.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/contact":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/contact","title":"contact","role":"symbol","navigatorTitle":[{"text":"contact","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"contact","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactAppearance","text":"ContactAppearance","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/appearance\/contact","abstract":[{"text":"Contact Component","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/conversation":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/conversation","type":"topic","title":"conversation","role":"symbol","navigatorTitle":[{"text":"conversation","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationAppearance","text":"ConversationAppearance"}],"url":"\/documentation\/easechatuikit\/appearance\/conversation","abstract":[{"text":"Conversation Component","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainerTitleBar":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageContainerTitleBar"}],"type":"topic","title":"PageContainerTitleBar","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar","abstract":[],"navigatorTitle":[{"text":"PageContainerTitleBar","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pagecontainertitlebar"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"Appearance"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Appearance","kind":"identifier"}]},{"op":"replace","value":[{"text":"Appearance","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/init"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/actionSheetRowHeight","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertContainerConstraintsSize","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertStyle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/avatarPlaceHolder","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/chat","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/contact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/conversation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/errorHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/hiddenPresence","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/neutralHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/neutralSpecialHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/pageContainerConstraintsSize","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/pageContainerTitleBarItemWidth","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/primaryHue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/secondaryHue"],"title":"Type Properties"}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1avatarPlaceHolder\/title","value":"avatarPlaceHolder"},{"value":[{"text":"avatarPlaceHolder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1avatarPlaceHolder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/title","value":"PageContainersDialogController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/fragments","value":[{"text":"PageContainersDialogController","kind":"identifier"}]},{"value":"AlertViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertViewController\/title"},{"op":"replace","value":[{"text":"AlertViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1neutralHue\/title","value":"neutralHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1neutralHue\/fragments","value":[{"text":"neutralHue","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1alertStyle\/title","value":"alertStyle","op":"replace"},{"value":[{"text":"alertStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1alertStyle\/fragments","op":"replace"},{"value":"MessageCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","value":[{"text":"MessageCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1hiddenPresence\/title","value":"hiddenPresence"},{"value":[{"text":"hiddenPresence","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1hiddenPresence\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1primaryHue\/title","value":"primaryHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1primaryHue\/fragments","value":[{"kind":"identifier","text":"primaryHue"}]},{"value":"AlertView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title"},{"value":[{"kind":"identifier","text":"AlertView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1errorHue\/title","value":"errorHue","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"errorHue"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1errorHue\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1alertContainerConstraintsSize\/title","value":"alertContainerConstraintsSize","op":"replace"},{"value":[{"kind":"identifier","text":"alertContainerConstraintsSize"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1alertContainerConstraintsSize\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1neutralSpecialHue\/title","value":"neutralSpecialHue"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1neutralSpecialHue\/fragments","value":[{"kind":"identifier","text":"neutralSpecialHue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1pageContainerConstraintsSize\/title","value":"pageContainerConstraintsSize"},{"op":"replace","value":[{"text":"pageContainerConstraintsSize","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1pageContainerConstraintsSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1actionSheetRowHeight\/title","value":"actionSheetRowHeight"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1actionSheetRowHeight\/fragments","value":[{"text":"actionSheetRowHeight","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1secondaryHue\/title","value":"secondaryHue"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1secondaryHue\/fragments","value":[{"kind":"identifier","text":"secondaryHue"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance"},{"value":[{"text":"Appearance","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1chat\/title","value":"chat"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1chat\/fragments","value":[{"kind":"identifier","text":"chat"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1pageContainerTitleBarItemWidth\/title","value":"pageContainerTitleBarItemWidth","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1pageContainerTitleBarItemWidth\/fragments","value":[{"text":"pageContainerTitleBarItemWidth","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1contact\/title","value":"contact","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1contact\/fragments","op":"replace","value":[{"kind":"identifier","text":"contact"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1conversation\/title","value":"conversation","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1conversation\/fragments","value":[{"text":"conversation","kind":"identifier"}],"op":"replace"},{"value":"PageContainerTitleBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"PageContainerTitleBar"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar\/fragments"}]}]}