{"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatTopicOptions"}],"symbolKind":"enum","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Enumeration","title":"ChatTopicOptions","externalID":"c:@M@EaseChatUIKit@E@ChatTopicOptions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatTopicOptions"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/chattopicoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chattopicoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/destroy","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/leave"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatTopicOptions"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatTopicOptions/leave":{"title":"ChatTopicOptions.leave","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/leave","url":"\/documentation\/easechatuikit\/chattopicoptions\/leave","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leave","kind":"identifier"}],"navigatorTitle":[{"text":"ChatTopicOptionsLeave","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatTopicOptions/destroy":{"navigatorTitle":[{"text":"ChatTopicOptionsDestroy","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/destroy","kind":"symbol","role":"symbol","title":"ChatTopicOptions.destroy","url":"\/documentation\/easechatuikit\/chattopicoptions\/destroy","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"destroy","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatTopicOptions/init(rawValue:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/init(rawValue:)","kind":"symbol","role":"symbol","title":"init(rawValue:)","url":"\/documentation\/easechatuikit\/chattopicoptions\/init(rawvalue:)","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatTopicOptions/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/Equatable-Implementations","type":"topic","kind":"article","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/chattopicoptions\/equatable-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatTopicOptions":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatTopicOptions"}],"navigatorTitle":[{"text":"ChatTopicOptions","kind":"identifier"}],"title":"ChatTopicOptions","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/chattopicoptions","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatTopicOptions/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/easechatuikit\/chattopicoptions\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ChatTopicOptions"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"kind":"identifier","text":"ChatTopicOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ChatTopicOptions"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/destroy","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatTopicOptions\/leave"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatTopicOptions"},{"kind":"text","text":": "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"ChatTopicOptionsLeave","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatTopicOptions~1leave\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatTopicOptions~1leave\/fragments","value":[{"text":"ChatTopicOptionsLeave","kind":"identifier"}]},{"op":"replace","value":"ChatTopicOptionsDestroy","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatTopicOptions~1destroy\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatTopicOptions~1destroy\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatTopicOptionsDestroy"}]},{"value":"ChatTopicOptions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatTopicOptions\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatTopicOptions\/fragments","op":"replace","value":[{"text":"ChatTopicOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}