{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatResponseListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatresponselistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatresponselistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageStatusDidChanged(message:status:error:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatResponseListener"}],"title":"ChatResponseListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatResponseListener"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageDidRecalled(recallInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}],"role":"symbol","title":"onMessageDidRecalled(recallInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidRecalled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recallInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When message recalled."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidRecalled(recallInfo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidrecalled(recallinfo:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageDidEdited(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageDidEditedWithMessage:"}],"role":"symbol","title":"onMessageDidEdited(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidEdited"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When message edited."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidEdited(message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidedited(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageAttachmentStatusChanged(message:error:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageAttachmentStatusChangedWithMessage:error:"}],"role":"symbol","title":"onMessageAttachmentStatusChanged(message:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAttachmentStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"When status of message attachment changed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageAttachmentStatusChanged(message:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessageattachmentstatuschanged(message:error:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener":{"role":"symbol","title":"ChatResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatResponseListener"}],"url":"\/documentation\/easechatuikit\/chatresponselistener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageReactionChanged(changes:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageReactionChangedWithChanges:"}],"role":"symbol","title":"onMessageReactionChanged(changes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReactionChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageReactionChange","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"When reaction of message changed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageReactionChanged(changes:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagereactionchanged(changes:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageStatusDidChanged(message:status:error:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageStatusDidChangedWithMessage:status:error:"}],"role":"symbol","title":"onMessageStatusDidChanged(message:status:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageStatusDidChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageStatus","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"When status of message changed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageStatusDidChanged(message:status:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagestatusdidchanged(message:status:error:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageDidReceived(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}],"role":"symbol","title":"onMessageDidReceived(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidReceived"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When message received."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidReceived(message:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidreceived(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"role":"symbol","title":"MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListViewModel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ChatResponseListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatResponseListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatResponseListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageStatusDidChanged(message:status:error:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatResponseListener"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidRecalled(recallInfo:)\/title","value":"onMessageDidRecalledWithRecallInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidRecalled(recallInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidEdited(message:)\/title","value":"onMessageDidEditedWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidEdited(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidEditedWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageAttachmentStatusChanged(message:error:)\/title","value":"onMessageAttachmentStatusChangedWithMessage:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageAttachmentStatusChanged(message:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAttachmentStatusChangedWithMessage:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/title","value":"ChatResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/fragments","value":[{"kind":"identifier","text":"ChatResponseListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageReactionChanged(changes:)\/title","value":"onMessageReactionChangedWithChanges:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageReactionChanged(changes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageReactionChangedWithChanges:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageStatusDidChanged(message:status:error:)\/title","value":"onMessageStatusDidChangedWithMessage:status:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageStatusDidChanged(message:status:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageStatusDidChangedWithMessage:status:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidReceived(message:)\/title","value":"onMessageDidReceivedWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidReceived(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"kind":"identifier","text":"MessageListViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}