{"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/init(chatThread:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/chatService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/chatThread","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/driver","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/groupService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/multiService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/to"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/addEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/audioMessagePlay(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/bindDriver(driver:create:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/cacheFrame(attachMessage:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/cacheImage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/constructMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/copyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/deleteMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/deleteMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/destroyChatTopic(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/downloadMessageAttachment(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/editMessage(message:content:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/leaveChatTopic(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/loadMessages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageStatusChanged(message:status:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageTopicClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageVisibleMark(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/operationReaction(emoji:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/operationTopic(option:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processInputEvents(action:attributeText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processMessage(operation:message:edit:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/recallAction(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/recallMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/removeEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/replyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/requestGroupDetail()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/retrySendMessage(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/sendFirstMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/sendMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/showOriginalText(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/threadCreateAlert()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/translateMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/willSendMessage(attributeText:)"],"title":"Instance Methods"},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/GroupChatThreadEventListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MultiDeviceListener-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"],"type":"conformsTo"}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatThreadViewModel","title":"ChatThreadViewModel","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatThreadViewModel"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadViewModel","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageDidRecalled(recallInfo:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagedidrecalled(recallinfo:)","type":"topic","title":"messageDidRecalled(recallInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recallInfo"},{"text":": ","kind":"text"},{"text":"RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidRecalled(recallInfo:)","role":"symbol","kind":"symbol","abstract":[{"text":"Handles the event when a message is recalled.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageAvatarLongPressed(profile:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messageavatarlongpressed(profile:)","type":"topic","title":"messageAvatarLongPressed(profile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageAvatarLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAvatarLongPressed(profile:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/chatService":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/chatservice","type":"topic","title":"chatService","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"chatService","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatService","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatService"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/chatService","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"chatService","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/operationReaction(emoji:message:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/operationreaction(emoji:message:)","type":"topic","title":"operationReaction(emoji:message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operationReaction"},{"kind":"text","text":"("},{"text":"emoji","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/operationReaction(emoji:message:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"operationReactionWithEmoji:message:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/MultiDeviceListener-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/multidevicelistener-implementations","type":"topic","title":"MultiDeviceListener Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MultiDeviceListener-Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/MessageListViewActionEventsDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagelistviewactioneventsdelegate-implementations","type":"topic","title":"MessageListViewActionEventsDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageReactionChanged(changes:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagereactionchanged(changes:)","type":"topic","title":"messageReactionChanged(changes:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageReactionChanged"},{"kind":"text","text":"("},{"text":"changes","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea","kind":"typeIdentifier","text":"MessageReactionChange"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionChanged(changes:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"messageReactionChangedWithChanges:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/addEventsListener(_:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/addeventslistener(_:)","type":"topic","title":"addEventsListener(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventsListener"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener","text":"MessageListDriverEventsListener"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/addEventsListener(_:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Add events listener of the message list."}],"navigatorTitle":[{"kind":"identifier","text":"addEventsListener:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageReactionClicked(reaction:entity:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagereactionclicked(reaction:entity:)","type":"topic","title":"messageReactionClicked(reaction:entity:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messageReactionClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","text":"MessageReaction"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionClicked(reaction:entity:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"messageReactionClickedWithReaction:entity:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceListener":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","title":"MultiDeviceListener","url":"\/documentation\/easechatuikit\/multidevicelistener","role":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/to":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/to","title":"to","kind":"symbol","type":"topic","navigatorTitle":[{"text":"to","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/to","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"to","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/ChatResponseListener-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/chatresponselistener-implementations","type":"topic","title":"ChatResponseListener Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageVisibleMark(entity:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagevisiblemark(entity:)","title":"messageVisibleMark(entity:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"messageVisibleMarkWithEntity:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageVisibleMark(entity:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageVisibleMark","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/driver":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/driver","type":"topic","title":"driver","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"driver"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/driver","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"driver","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IMessageListViewDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/processInputEvents(action:attributeText:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/processinputevents(action:attributetext:)","title":"processInputEvents(action:attributeText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processInputEventsWithAction:attributeText:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processInputEvents(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"processInputEvents","kind":"identifier"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType"},{"kind":"text","text":", "},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/sendMessage(text:type:extensionInfo:)":{"role":"symbol","abstract":[{"type":"text","text":"Send message with text&type&extension info."}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/sendmessage(text:type:extensioninfo:)","type":"topic","title":"sendMessage(text:type:extensionInfo:)","kind":"symbol","navigatorTitle":[{"text":"sendMessageWithText:type:extensionInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/sendMessage(text:type:extensionInfo:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageCellStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageCellStyle"},{"text":", ","kind":"text"},{"text":"extensionInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Dictionary","preciseIdentifier":"s:SD","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":">)"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/showOriginalText(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/showoriginaltext(message:)","title":"showOriginalText(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"showOriginalTextWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/showOriginalText(message:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showOriginalText"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/downloadMessageAttachment(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/downloadmessageattachment(message:)","type":"topic","title":"downloadMessageAttachment(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"downloadMessageAttachmentWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/downloadMessageAttachment(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"downloadMessageAttachment"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/recallMessage(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/recallmessage(message:)","title":"recallMessage(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"recallMessageWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/recallMessage(message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recallMessage"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageDidEdited(message:)":{"role":"symbol","abstract":[{"text":"Notifies the view model that a message has been edited.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagedidedited(message:)","type":"topic","title":"messageDidEdited(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageDidEditedWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidEdited(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageDidEdited"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/replyMessage(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/replymessage(message:)","title":"replyMessage(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"replyMessageWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/replyMessage(message:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"replyMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/deleteMessages(messages:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/deletemessages(messages:)","title":"deleteMessages(messages:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"deleteMessagesWithMessages:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/deleteMessages(messages:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/operationTopic(option:completion:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/operationtopic(option:completion:)","title":"operationTopic(option:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"operationTopicWithOption:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/operationTopic(option:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"operationTopic","kind":"identifier"},{"kind":"text","text":"("},{"text":"option","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatTopicOptions","text":"ChatTopicOptions"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/requestGroupDetail()":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/requestgroupdetail()","type":"topic","title":"requestGroupDetail()","kind":"symbol","navigatorTitle":[{"text":"requestGroupDetail","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/requestGroupDetail()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestGroupDetail"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageTopicClicked(entity:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagetopicclicked(entity:)","title":"messageTopicClicked(entity:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messageTopicClickedWithEntity:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageTopicClicked(entity:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTopicClicked"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/groupService":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/groupservice","title":"groupService","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupService"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/groupService","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupService"},{"text":": ","kind":"text"},{"text":"GroupService","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupService","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatresponselistener","type":"topic","title":"ChatResponseListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatResponseListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatResponseListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/GroupChatThreadEventListener-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/groupchatthreadeventlistener-implementations","title":"GroupChatThreadEventListener Implementations","kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/GroupChatThreadEventListener-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/sendFirstMessage(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/sendfirstmessage(message:)","type":"topic","title":"sendFirstMessage(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sendFirstMessageWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/sendFirstMessage(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sendFirstMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onattributeschangedofgroupmember(groupid:userid:operatorid:attributes:)","title":"onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAttributesChangedOfGroupMember"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"attributes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">)","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/init(chatThread:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/init(chatthread:)","type":"topic","title":"init(chatThread:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithChatThread:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/init(chatThread:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"chatThread","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB6Threada","text":"GroupChatThread"},{"kind":"text","text":"?)"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageStatusChanged(message:status:error:)":{"role":"symbol","abstract":[{"type":"text","text":"Notifies the message list view model when the status of a chat message has changed."}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagestatuschanged(message:status:error:)","title":"messageStatusChanged(message:status:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"messageStatusChangedWithMessage:status:error:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageStatusChanged(message:status:error:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messageStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus","text":"ChatMessageStatus"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/cacheImage(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/cacheimage(message:)","type":"topic","title":"cacheImage(message:)","kind":"symbol","navigatorTitle":[{"text":"cacheImageWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/cacheImage(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventListener":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/groupchatthreadeventlistener","title":"GroupChatThreadEventListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEventListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/recallAction(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/recallaction(message:)","type":"topic","title":"recallAction(message:)","kind":"symbol","navigatorTitle":[{"text":"recallActionWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/recallAction(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"recallAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/constructMessage(text:type:extensionInfo:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/constructmessage(text:type:extensioninfo:)","title":"constructMessage(text:type:extensionInfo:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"constructMessageWithText:type:extensionInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/constructMessage(text:type:extensionInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"constructMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageCellStyle","text":"MessageCellStyle"},{"text":", ","kind":"text"},{"text":"extensionInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/removeEventsListener(_:)":{"role":"symbol","abstract":[{"type":"text","text":"Remove events listener of the message list."}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/removeeventslistener(_:)","type":"topic","title":"removeEventsListener(_:)","kind":"symbol","navigatorTitle":[{"text":"removeEventsListener:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/removeEventsListener(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener","text":"MessageListDriverEventsListener"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/imessagelistviewdriver","title":"IMessageListViewDriver","kind":"symbol","type":"topic","navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IMessageListViewDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/translateMessage(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/translatemessage(message:)","type":"topic","title":"translateMessage(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"translateMessageWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/translateMessage(message:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"translateMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/threadCreateAlert()":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/threadcreatealert()","title":"threadCreateAlert()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"threadCreateAlert","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/threadCreateAlert()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threadCreateAlert","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/chatThread":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/chatthread","type":"topic","title":"chatThread","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"chatThread"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/chatThread","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatThread","kind":"identifier"},{"text":": ","kind":"text"},{"text":"GroupChatThread","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB6Threada"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageAttachmentStatusChanged(message:error:)":{"role":"symbol","abstract":[{"type":"text","text":"Handles the change in attachment status of a chat message."}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messageattachmentstatuschanged(message:error:)","title":"messageAttachmentStatusChanged(message:error:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"messageAttachmentStatusChangedWithMessage:error:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAttachmentStatusChanged(message:error:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageAttachmentStatusChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/audioMessagePlay(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/audiomessageplay(message:)","type":"topic","title":"audioMessagePlay(message:)","kind":"symbol","navigatorTitle":[{"text":"audioMessagePlayWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/audioMessagePlay(message:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioMessagePlay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"abstract":[],"title":"ChatThreadViewModel","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageBubbleClicked(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagebubbleclicked(message:)","title":"onMessageBubbleClicked(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"onMessageBubbleClickedWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageBubbleClicked(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageBubbleClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/leaveChatTopic(completion:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/leavechattopic(completion:)","title":"leaveChatTopic(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"leaveChatTopicWithCompletion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/leaveChatTopic(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"leaveChatTopic","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/processMessage(operation:message:edit:)":{"role":"symbol","abstract":[{"text":"Call the corresponding method in ViewModel to handle the specified message.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/processmessage(operation:message:edit:)","type":"topic","title":"processMessage(operation:message:edit:)","kind":"symbol","navigatorTitle":[{"text":"processMessageWithOperation:message:edieText:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processMessage(operation:message:edit:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"processMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"text":"MessageOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageOperation"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"text":"edit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/destroyChatTopic(completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"destroyChatTopic","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"destroyChatTopicWithCompletion:","kind":"identifier"}],"title":"destroyChatTopic(completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/destroyChatTopic(completion:)","type":"topic","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/destroychattopic(completion:)","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/editMessage(message:content:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/editmessage(message:content:)","title":"editMessage(message:content:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"editMessageWithMessage:content:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/editMessage(message:content:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"editMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/loadMessages()":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/loadmessages()","title":"loadMessages()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"loadMessages","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/loadMessages()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadMessages","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/multiService":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/multiservice","type":"topic","title":"multiService","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"multiService"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/multiService","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiService"},{"kind":"text","text":": "},{"text":"MultiDeviceService","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceService"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewActionEventsDelegate":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate","title":"MessageListViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/retrySendMessage(entity:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/retrysendmessage(entity:)","type":"topic","title":"retrySendMessage(entity:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"retrySendMessageWithEntity:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/retrySendMessage(entity:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"retrySendMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/willSendMessage(attributeText:)":{"title":"willSendMessage(attributeText:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/willSendMessage(attributeText:)","navigatorTitle":[{"text":"willSendMessageWithAttributeText:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/willsendmessage(attributetext:)","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willSendMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/bindDriver(driver:create:)":{"role":"symbol","abstract":[{"type":"text","text":"Bind "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver"}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/binddriver(driver:create:)","title":"bindDriver(driver:create:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindWithDriver:create:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/bindDriver(driver:create:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindDriver"},{"text":"(","kind":"text"},{"text":"driver","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver","kind":"typeIdentifier","text":"IMessageListViewDriver"},{"kind":"text","text":", "},{"text":"create","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/deleteMessage(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/deletemessage(message:)","type":"topic","title":"deleteMessage(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"deleteMessageWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/deleteMessage(message:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deleteMessage"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/cacheFrame(attachMessage:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/cacheframe(attachmessage:)","title":"cacheFrame(attachMessage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cacheFrameWithAttachMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/cacheFrame(attachMessage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheFrame"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"attachMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageDidReceived(message:)":{"role":"symbol","abstract":[{"type":"text","text":"Handles the received message and performs necessary actions based on the message type."}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagedidreceived(message:)","type":"topic","title":"messageDidReceived(message:)","kind":"symbol","navigatorTitle":[{"text":"messageDidReceivedWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidReceived(message:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDidReceived"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/copyMessage(message:)":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/copymessage(message:)","title":"copyMessage(message:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"copyMessageWithMessage:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/copyMessage(message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"copyMessage"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"ChatThreadViewModel"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewModel"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadViewModel"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/chatService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/chatThread","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/driver","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/groupService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/multiService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/to"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/addEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/audioMessagePlay(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/bindDriver(driver:create:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/cacheFrame(attachMessage:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/cacheImage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/constructMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/copyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/deleteMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/deleteMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/destroyChatTopic(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/downloadMessageAttachment(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/editMessage(message:content:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/init(chatThread:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/leaveChatTopic(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/loadMessages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageStatusChanged(message:status:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageTopicClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageVisibleMark(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/operationReaction(emoji:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/operationTopic(option:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processInputEvents(action:attributeText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processMessage(operation:message:edit:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/recallAction(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/recallMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/removeEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/replyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/requestGroupDetail()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/retrySendMessage(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/sendFirstMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/sendMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/showOriginalText(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/threadCreateAlert()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/translateMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/willSendMessage(attributeText:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/GroupChatThreadEventListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MultiDeviceListener-Implementations"],"generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatThreadViewModel"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidRecalled(recallInfo:)\/title","value":"messageDidRecalledWithRecallInfo:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidRecalled(recallInfo:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageAvatarLongPressed(profile:)\/title","value":"messageAvatarLongPressedWithProfile:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageAvatarLongPressed(profile:)\/fragments"},{"op":"replace","value":"chatService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1chatService\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1chatService\/fragments","value":[{"text":"chatService","kind":"identifier"}]},{"value":"operationReactionWithEmoji:message:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1operationReaction(emoji:message:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"operationReactionWithEmoji:message:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1operationReaction(emoji:message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageReactionChanged(changes:)\/title","value":"messageReactionChangedWithChanges:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageReactionChanged(changes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messageReactionChangedWithChanges:","kind":"identifier"}]},{"value":"addEventsListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1addEventsListener(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addEventsListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1addEventsListener(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageReactionClicked(reaction:entity:)\/title","op":"replace","value":"messageReactionClickedWithReaction:entity:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageReactionClicked(reaction:entity:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageReactionClickedWithReaction:entity:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/title","op":"replace","value":"MultiDeviceListener"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/fragments","op":"replace","value":[{"kind":"identifier","text":"MultiDeviceListener"}]},{"value":"to","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1to\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1to\/fragments","op":"replace","value":[{"text":"to","kind":"identifier"}]},{"value":"messageVisibleMarkWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageVisibleMark(entity:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageVisibleMarkWithEntity:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageVisibleMark(entity:)\/fragments","op":"replace"},{"value":"driver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1driver\/title"},{"value":[{"kind":"identifier","text":"driver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1driver\/fragments"},{"op":"replace","value":"processInputEventsWithAction:attributeText:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1processInputEvents(action:attributeText:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"processInputEventsWithAction:attributeText:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1processInputEvents(action:attributeText:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1sendMessage(text:type:extensionInfo:)\/title","op":"replace","value":"sendMessageWithText:type:extensionInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1sendMessage(text:type:extensionInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendMessageWithText:type:extensionInfo:"}],"op":"replace"},{"value":"showOriginalTextWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1showOriginalText(message:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"showOriginalTextWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1showOriginalText(message:)\/fragments","op":"replace"},{"value":"downloadMessageAttachmentWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1downloadMessageAttachment(message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"downloadMessageAttachmentWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1downloadMessageAttachment(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1recallMessage(message:)\/title","value":"recallMessageWithMessage:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1recallMessage(message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recallMessageWithMessage:"}]},{"op":"replace","value":"messageDidEditedWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidEdited(message:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageDidEditedWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidEdited(message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1replyMessage(message:)\/title","value":"replyMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1replyMessage(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"replyMessageWithMessage:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1deleteMessages(messages:)\/title","op":"replace","value":"deleteMessagesWithMessages:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1deleteMessages(messages:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deleteMessagesWithMessages:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1operationTopic(option:completion:)\/title","value":"operationTopicWithOption:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"operationTopicWithOption:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1operationTopic(option:completion:)\/fragments"},{"value":"requestGroupDetail","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1requestGroupDetail()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1requestGroupDetail()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestGroupDetail"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageTopicClicked(entity:)\/title","value":"messageTopicClickedWithEntity:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"messageTopicClickedWithEntity:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageTopicClicked(entity:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1groupService\/title","value":"groupService"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1groupService\/fragments","op":"replace","value":[{"text":"groupService","kind":"identifier"}]},{"value":"ChatResponseListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/fragments","value":[{"text":"ChatResponseListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1sendFirstMessage(message:)\/title","op":"replace","value":"sendFirstMessageWithMessage:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendFirstMessageWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1sendFirstMessage(message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/title","value":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:"}]},{"value":"initWithChatThread:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1init(chatThread:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithChatThread:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1init(chatThread:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageStatusChanged(message:status:error:)\/title","value":"messageStatusChangedWithMessage:status:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageStatusChanged(message:status:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messageStatusChangedWithMessage:status:error:","kind":"identifier"}]},{"value":"cacheImageWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1cacheImage(message:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cacheImageWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1cacheImage(message:)\/fragments"},{"op":"replace","value":"GroupChatThreadEventListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/fragments","value":[{"text":"GroupChatThreadEventListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1recallAction(message:)\/title","value":"recallActionWithMessage:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recallActionWithMessage:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1recallAction(message:)\/fragments","op":"replace"},{"value":"constructMessageWithText:type:extensionInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1constructMessage(text:type:extensionInfo:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1constructMessage(text:type:extensionInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"constructMessageWithText:type:extensionInfo:","kind":"identifier"}]},{"value":"removeEventsListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1removeEventsListener(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"removeEventsListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1removeEventsListener(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/title","op":"replace","value":"IMessageListViewDriver"},{"op":"replace","value":[{"kind":"identifier","text":"IMessageListViewDriver"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/fragments"},{"op":"replace","value":"translateMessageWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1translateMessage(message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1translateMessage(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"translateMessageWithMessage:","kind":"identifier"}],"op":"replace"},{"value":"threadCreateAlert","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1threadCreateAlert()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1threadCreateAlert()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"threadCreateAlert","kind":"identifier"}],"op":"replace"},{"value":"chatThread","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1chatThread\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1chatThread\/fragments","value":[{"text":"chatThread","kind":"identifier"}],"op":"replace"},{"value":"messageAttachmentStatusChangedWithMessage:error:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageAttachmentStatusChanged(message:error:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"messageAttachmentStatusChangedWithMessage:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageAttachmentStatusChanged(message:error:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1audioMessagePlay(message:)\/title","value":"audioMessagePlayWithMessage:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioMessagePlayWithMessage:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1audioMessagePlay(message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel"},{"op":"replace","value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageBubbleClicked(message:)\/title","value":"onMessageBubbleClickedWithMessage:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageBubbleClicked(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageBubbleClickedWithMessage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1leaveChatTopic(completion:)\/title","value":"leaveChatTopicWithCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1leaveChatTopic(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"leaveChatTopicWithCompletion:"}],"op":"replace"},{"value":"processMessageWithOperation:message:edieText:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1processMessage(operation:message:edit:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"processMessageWithOperation:message:edieText:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1processMessage(operation:message:edit:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1destroyChatTopic(completion:)\/title","value":"destroyChatTopicWithCompletion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"destroyChatTopicWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1destroyChatTopic(completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1editMessage(message:content:)\/title","value":"editMessageWithMessage:content:"},{"value":[{"kind":"text","text":"- "},{"text":"editMessageWithMessage:content:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1editMessage(message:content:)\/fragments","op":"replace"},{"value":"loadMessages","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1loadMessages()\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadMessages","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1loadMessages()\/fragments"},{"op":"replace","value":"multiService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1multiService\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1multiService\/fragments","value":[{"kind":"identifier","text":"multiService"}]},{"op":"replace","value":"MessageListViewActionEventsDelegate","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/fragments","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}]},{"value":"retrySendMessageWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1retrySendMessage(entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1retrySendMessage(entity:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"retrySendMessageWithEntity:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1willSendMessage(attributeText:)\/title","value":"willSendMessageWithAttributeText:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1willSendMessage(attributeText:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willSendMessageWithAttributeText:","kind":"identifier"}],"op":"replace"},{"value":"bindWithDriver:create:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1bindDriver(driver:create:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1bindDriver(driver:create:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindWithDriver:create:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1deleteMessage(message:)\/title","value":"deleteMessageWithMessage:"},{"value":[{"kind":"text","text":"- "},{"text":"deleteMessageWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1deleteMessage(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1cacheFrame(attachMessage:)\/title","value":"cacheFrameWithAttachMessage:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cacheFrameWithAttachMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1cacheFrame(attachMessage:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidReceived(message:)\/title","op":"replace","value":"messageDidReceivedWithMessage:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"messageDidReceivedWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidReceived(message:)\/fragments"},{"value":"copyMessageWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1copyMessage(message:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"copyMessageWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1copyMessage(message:)\/fragments"}]}]}