{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"class","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitContext","navigatorTitle":[{"text":"ChatUIKitContext","kind":"identifier"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitContext"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","title":"ChatUIKitContext"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatuikitcontext"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatuikitcontext"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/chatCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/currentUser","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/currentUserId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProvider","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProviderOC","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/onGroupNameUpdated","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/pinnedCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userProfileProvider","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userProfileProviderOC"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/cleanCache(type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/updateCache(type:profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/updateCaches(type:profiles:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/shared"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatUIKitContext","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/currentUser":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatuikitcontext\/currentuser","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"currentUser"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/currentUser","role":"symbol","title":"currentUser","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"currentUser","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/groupProfileProviderOC":{"type":"topic","title":"groupProfileProviderOC","navigatorTitle":[{"text":"groupProfileProviderOC","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupProfileProviderOC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatGroupProfileProviderOC","kind":"typeIdentifier","text":"ChatGroupProfileProviderOC"},{"text":"?","kind":"text"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext\/groupprofileprovideroc","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProviderOC"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/onGroupNameUpdated":{"title":"onGroupNameUpdated","abstract":[{"text":"The first parameter is the group id and the second parameter is the group name.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupNameUpdated","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onGroupNameUpdated"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext\/ongroupnameupdated","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/onGroupNameUpdated"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitCacheType":{"url":"\/documentation\/easechatuikit\/easechatuikitcachetype","title":"EaseChatUIKitCacheType","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"navigatorTitle":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/shared":{"abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatUIKitContext","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitContext"},{"text":"?","kind":"text"}],"role":"symbol","title":"shared","navigatorTitle":[{"kind":"identifier","text":"shared"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/shared","kind":"symbol","url":"\/documentation\/easechatuikit\/chatuikitcontext\/shared"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/chatCache":{"navigatorTitle":[{"kind":"identifier","text":"chatCache"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatCache"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":">?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/chatCache","kind":"symbol","title":"chatCache","abstract":[{"text":"The cache of user information on the side of the message in the chat page. The key is the user ID and the value is an object that complies with the ","type":"text"},{"type":"codeVoice","code":"EaseProfileProtocol"},{"text":" protocol.Display the info on chat page.","type":"text"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatuikitcontext\/chatcache","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/currentUserId":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentUserId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/currentUserId","abstract":[],"title":"currentUserId","url":"\/documentation\/easechatuikit\/chatuikitcontext\/currentuserid","navigatorTitle":[{"text":"currentUserId","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/updateCache(type:profile:)":{"kind":"symbol","title":"updateCache(type:profile:)","navigatorTitle":[{"text":"updateCacheWithType:profile:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext\/updatecache(type:profile:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateCache","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType","text":"EaseChatUIKitCacheType"},{"kind":"text","text":", "},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/updateCache(type:profile:)","abstract":[{"text":"Update the cache of ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","type":"reference","isActive":true},{"type":"text","text":" type"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/userProfileProviderOC":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userProfileProviderOC","url":"\/documentation\/easechatuikit\/chatuikitcontext\/userprofileprovideroc","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userProfileProviderOC"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProviderOC","text":"ChatUserProfileProviderOC","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"userProfileProviderOC"}],"type":"topic","title":"userProfileProviderOC","kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/init":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/init","url":"\/documentation\/easechatuikit\/chatuikitcontext\/init","title":"init","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/cleanCache(type:)":{"url":"\/documentation\/easechatuikit\/chatuikitcontext\/cleancache(type:)","role":"symbol","title":"cleanCache(type:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/cleanCache(type:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanCache"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType","text":"EaseChatUIKitCacheType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"cleanCacheWithType:","kind":"identifier"}],"abstract":[{"type":"text","text":"Clean the cache of "},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","type":"reference"},{"text":" type","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext":{"kind":"symbol","title":"ChatUIKitContext","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitContext"}],"navigatorTitle":[{"kind":"identifier","text":"ChatUIKitContext"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/userCache":{"title":"userCache","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userCache","navigatorTitle":[{"text":"userCache","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The cache of user information on user. Display the info on contact-list&single-chat-conversation-item&user-profile page ."}],"url":"\/documentation\/easechatuikit\/chatuikitcontext\/usercache","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userCache"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":">?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/pinnedCache":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinnedCache","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":">?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"pinnedCache","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/pinnedCache","url":"\/documentation\/easechatuikit\/chatuikitcontext\/pinnedcache","abstract":[],"title":"pinnedCache","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/userProfileProvider":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatuikitcontext\/userprofileprovider","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userProfileProvider","role":"symbol","title":"userProfileProvider","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userProfileProvider"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProvider","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B19UserProfileProviderP"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/updateCaches(type:profiles:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateCaches","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"EaseChatUIKitCacheType","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"profiles","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/updateCaches(type:profiles:)","title":"updateCaches(type:profiles:)","url":"\/documentation\/easechatuikit\/chatuikitcontext\/updatecaches(type:profiles:)","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"updateCachesWithType:profiles:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/groupProfileProvider":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupProfileProvider"},{"kind":"text","text":": "},{"text":"ChatGroupProfileProvider","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B20GroupProfileProviderP"},{"text":"?","kind":"text"}],"abstract":[],"title":"groupProfileProvider","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/chatuikitcontext\/groupprofileprovider","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProvider"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/groupCache":{"abstract":[{"type":"text","text":"The cache of user information on group-conversation-item. The key is the user ID and the value is an object that complies with the "},{"type":"codeVoice","code":"EaseProfileProtocol"},{"type":"text","text":" protocol."}],"url":"\/documentation\/easechatuikit\/chatuikitcontext\/groupcache","title":"groupCache","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupCache"},{"text":": ","kind":"text"},{"text":"Dictionary","kind":"typeIdentifier","preciseIdentifier":"s:SD"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":">?"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"groupCache"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupCache"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"ChatUIKitContext","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ChatUIKitContext"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ChatUIKitContext","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/chatCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/currentUser","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/currentUserId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProviderOC","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/onGroupNameUpdated","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/pinnedCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userCache","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/userProfileProviderOC"],"generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/cleanCache(type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/init","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/updateCache(type:profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/updateCaches(type:profiles:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/shared"],"title":"Type Properties","anchor":"Type-Properties","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatUIKitContext","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1currentUser\/title","op":"replace","value":"currentUser"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1currentUser\/fragments","value":[{"kind":"identifier","text":"currentUser"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1groupProfileProviderOC\/title","op":"replace","value":"groupProfileProviderOC"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1groupProfileProviderOC\/fragments","value":[{"text":"groupProfileProviderOC","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1onGroupNameUpdated\/title","value":"onGroupNameUpdated","op":"replace"},{"value":[{"kind":"identifier","text":"onGroupNameUpdated"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1onGroupNameUpdated\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/title","value":"EaseChatUIKitCacheType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/fragments","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/navigatorTitle","value":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"op":"replace"},{"value":"shared","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1shared\/title","op":"replace"},{"value":[{"text":"shared","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1shared\/fragments","op":"replace"},{"op":"replace","value":"chatCache","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1chatCache\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1chatCache\/fragments","value":[{"text":"chatCache","kind":"identifier"}],"op":"replace"},{"value":"currentUserId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1currentUserId\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1currentUserId\/fragments","op":"replace","value":[{"kind":"identifier","text":"currentUserId"}]},{"value":"updateCacheWithType:profile:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1updateCache(type:profile:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateCacheWithType:profile:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1updateCache(type:profile:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1userProfileProviderOC\/title","value":"userProfileProviderOC","op":"replace"},{"value":[{"text":"userProfileProviderOC","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1userProfileProviderOC\/fragments"},{"value":"cleanCacheWithType:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1cleanCache(type:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1cleanCache(type:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"cleanCacheWithType:","kind":"identifier"}]},{"value":"ChatUIKitContext","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatUIKitContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUIKitContext"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1userCache\/title","value":"userCache","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1userCache\/fragments","value":[{"kind":"identifier","text":"userCache"}]},{"value":"pinnedCache","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1pinnedCache\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1pinnedCache\/fragments","value":[{"kind":"identifier","text":"pinnedCache"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1updateCaches(type:profiles:)\/title","op":"replace","value":"updateCachesWithType:profiles:"},{"value":[{"text":"- ","kind":"text"},{"text":"updateCachesWithType:profiles:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1updateCaches(type:profiles:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1groupCache\/title","value":"groupCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1groupCache\/fragments","value":[{"text":"groupCache","kind":"identifier"}]}]}]}