{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement"],"title":"Conforming Types","kind":"relationships"}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/bindChatEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/edit(messageId:text:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/loadMessages(start:pageSize:searchMessage:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/markAllMessagesAsRead()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/markMessageAsRead(messageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinMessage(messageId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinnedMessages(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/reaction(reaction:message:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/recall(messageId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/removeHistoryMessages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/removeLocalMessage(messageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/searchMessage(keyword:pageSize:userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/send(message:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/translateMessage(message:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/unbindChatEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/unpinMessage(messageId:completion:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"metadata":{"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)ChatService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatService"}],"title":"ChatService","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Protocol","symbolKind":"protocol","navigatorTitle":[{"text":"ChatService","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatService"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatservice"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatservice"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/unpinMessage(messageId:completion:)":{"role":"symbol","abstract":[{"type":"text","text":"Remove the stickied message."}],"type":"topic","kind":"symbol","title":"unpinMessage(messageId:completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unpinMessage"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"unpinMessageWithMessageId:completion:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatservice\/unpinmessage(messageid:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/unpinMessage(messageId:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/reaction(reaction:message:completion:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reaction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Operation reaction api."}],"title":"reaction(reaction:message:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reactionWithReaction:message:completion:"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/reaction(reaction:message:completion:)","url":"\/documentation\/easechatuikit\/chatservice\/reaction(reaction:message:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/removeLocalMessage(messageId:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/removeLocalMessage(messageId:)","abstract":[{"type":"text","text":"Remove a message from database."}],"kind":"symbol","role":"symbol","title":"removeLocalMessage(messageId:)","type":"topic","required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeLocalMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"removeLocalMessageWithMessageId:"}],"url":"\/documentation\/easechatuikit\/chatservice\/removelocalmessage(messageid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/recall(messageId:completion:)":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Recall a message succeed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/recall(messageId:completion:)","title":"recall(messageId:completion:)","url":"\/documentation\/easechatuikit\/chatservice\/recall(messageid:completion:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recall"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"recallWithMessageId:completion:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/loadMessages(start:pageSize:searchMessage:completion:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"start","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":", ","kind":"text"},{"text":"searchMessage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"text":"?, [","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"text":"]) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/loadMessages(start:pageSize:searchMessage:completion:)","navigatorTitle":[{"text":"loadMessagesWithStart:pageSize:searchMessage:completion:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatservice\/loadmessages(start:pagesize:searchmessage:completion:)","title":"loadMessages(start:pageSize:searchMessage:completion:)","abstract":[{"type":"text","text":"Load messages from database."}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/unbindChatEventsListener(listener:)":{"abstract":[{"type":"text","text":"Unbind message changed listener"}],"title":"unbindChatEventsListener(listener:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/unbindChatEventsListener(listener:)","required":true,"kind":"symbol","url":"\/documentation\/easechatuikit\/chatservice\/unbindchateventslistener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unbindChatEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"text":"ChatResponseListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"unbindChatEventsListenerWithListener:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/pinMessage(messageId:completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Stickied a message on top."}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatservice\/pinmessage(messageid:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinMessage(messageId:completion:)","required":true,"title":"pinMessage(messageId:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"pinMessageWithMessageId:completion:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/markAllMessagesAsRead()":{"kind":"symbol","abstract":[{"text":"Mark all of the history messages as already read.","type":"text"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatservice\/markallmessagesasread()","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"markAllMessagesAsRead","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"markAllMessagesAsRead"}],"title":"markAllMessagesAsRead()","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/markAllMessagesAsRead()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/send(message:completion:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"send"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/send(message:completion:)","required":true,"abstract":[{"text":"Send message to someone.","type":"text"}],"title":"send(message:completion:)","url":"\/documentation\/easechatuikit\/chatservice\/send(message:completion:)","navigatorTitle":[{"kind":"identifier","text":"sendWithMessage:completion:"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/translateMessage(message:completion:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Translate the message text.","type":"text"}],"navigatorTitle":[{"text":"translateMessageWithMessage:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/translateMessage(message:completion:)","title":"translateMessage(message:completion:)","url":"\/documentation\/easechatuikit\/chatservice\/translatemessage(message:completion:)","required":true,"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"translateMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?, "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement":{"title":"ChatServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatServiceImplement","kind":"identifier"}],"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatserviceimplement","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)":{"navigatorTitle":[{"text":"fetchChatThreadHistoryMessagesWithConversationId:start:pageSize:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","title":"fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","abstract":[{"text":"Load messages from server.","type":"text"}],"required":true,"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchChatThreadHistoryMessages","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"start"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"pageSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?, ["},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/easechatuikit\/chatservice\/fetchchatthreadhistorymessages(conversationid:start:pagesize:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/bindChatEventsListener(listener:)":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindChatEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatResponseListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"bindChatEventsListenerWithListener:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatservice\/bindchateventslistener(listener:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Bind message changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/bindChatEventsListener(listener:)","title":"bindChatEventsListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/markMessageAsRead(messageId:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markMessageAsRead"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Mark a message as already read state."}],"title":"markMessageAsRead(messageId:)","role":"symbol","navigatorTitle":[{"text":"markMessageAsReadWithMessageId:","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/markMessageAsRead(messageId:)","url":"\/documentation\/easechatuikit\/chatservice\/markmessageasread(messageid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/removeHistoryMessages()":{"type":"topic","required":true,"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/chatservice\/removehistorymessages()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeHistoryMessages"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"removeHistoryMessages"}],"title":"removeHistoryMessages()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/removeHistoryMessages()","abstract":[{"text":"Remove all of the history messages from database.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/pinnedMessages(conversationId:completion:)":{"abstract":[{"type":"text","text":"Get all of the stickied messages."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinnedMessages(conversationId:completion:)","type":"topic","navigatorTitle":[{"text":"pinnedMessagesWithConversationId:completion:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/chatservice\/pinnedmessages(conversationid:completion:)","required":true,"title":"pinnedMessages(conversationId:completion:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinnedMessages"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"]?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/searchMessage(keyword:pageSize:userId:completion:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Search message from database."}],"navigatorTitle":[{"text":"searchMessageWithKeyword:pageSize:userId:completion:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/searchMessage(keyword:pageSize:userId:completion:)","title":"searchMessage(keyword:pageSize:userId:completion:)","url":"\/documentation\/easechatuikit\/chatservice\/searchmessage(keyword:pagesize:userid:completion:)","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"searchMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"keyword"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?, [","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"]) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/edit(messageId:text:completion:)":{"abstract":[{"type":"text","text":"Edit text message content."}],"url":"\/documentation\/easechatuikit\/chatservice\/edit(messageid:text:completion:)","title":"edit(messageId:text:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"edit","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"editWithMessageId:text:completion:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/edit(messageId:text:completion:)","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService","url":"\/documentation\/easechatuikit\/chatservice","title":"ChatService","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ChatService","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatService"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"ChatService","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"ChatService","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"ChatService","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/bindChatEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/edit(messageId:text:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/loadMessages(start:pageSize:searchMessage:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/markAllMessagesAsRead()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/markMessageAsRead(messageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinMessage(messageId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinnedMessages(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/reaction(reaction:message:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/recall(messageId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/removeHistoryMessages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/removeLocalMessage(messageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/searchMessage(keyword:pageSize:userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/send(message:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/translateMessage(message:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/unbindChatEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/unpinMessage(messageId:completion:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatService","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1unpinMessage(messageId:completion:)\/title","value":"unpinMessageWithMessageId:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1unpinMessage(messageId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unpinMessageWithMessageId:completion:","kind":"identifier"}],"op":"replace"},{"value":"reactionWithReaction:message:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1reaction(reaction:message:completion:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"reactionWithReaction:message:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1reaction(reaction:message:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1removeLocalMessage(messageId:)\/title","value":"removeLocalMessageWithMessageId:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"removeLocalMessageWithMessageId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1removeLocalMessage(messageId:)\/fragments","op":"replace"},{"value":"recallWithMessageId:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1recall(messageId:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1recall(messageId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"recallWithMessageId:completion:"}]},{"value":"loadMessagesWithStart:pageSize:searchMessage:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1loadMessages(start:pageSize:searchMessage:completion:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1loadMessages(start:pageSize:searchMessage:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadMessagesWithStart:pageSize:searchMessage:completion:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1unbindChatEventsListener(listener:)\/title","value":"unbindChatEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1unbindChatEventsListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unbindChatEventsListenerWithListener:"}]},{"value":"pinMessageWithMessageId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1pinMessage(messageId:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1pinMessage(messageId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pinMessageWithMessageId:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1markAllMessagesAsRead()\/title","op":"replace","value":"markAllMessagesAsRead"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1markAllMessagesAsRead()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markAllMessagesAsRead"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1send(message:completion:)\/title","value":"sendWithMessage:completion:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"sendWithMessage:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1send(message:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1translateMessage(message:completion:)\/title","value":"translateMessageWithMessage:completion:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"translateMessageWithMessage:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1translateMessage(message:completion:)\/fragments"},{"value":"ChatServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/fragments","value":[{"text":"ChatServiceImplement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/navigatorTitle","value":[{"kind":"identifier","text":"ChatServiceImplement"}]},{"value":"fetchChatThreadHistoryMessagesWithConversationId:start:pageSize:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"fetchChatThreadHistoryMessagesWithConversationId:start:pageSize:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1fetchChatThreadHistoryMessages(conversationId:start:pageSize:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1bindChatEventsListener(listener:)\/title","op":"replace","value":"bindChatEventsListenerWithListener:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindChatEventsListenerWithListener:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1bindChatEventsListener(listener:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1markMessageAsRead(messageId:)\/title","value":"markMessageAsReadWithMessageId:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1markMessageAsRead(messageId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"markMessageAsReadWithMessageId:","kind":"identifier"}]},{"op":"replace","value":"removeHistoryMessages","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1removeHistoryMessages()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeHistoryMessages"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1removeHistoryMessages()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1pinnedMessages(conversationId:completion:)\/title","op":"replace","value":"pinnedMessagesWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1pinnedMessages(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pinnedMessagesWithConversationId:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1searchMessage(keyword:pageSize:userId:completion:)\/title","op":"replace","value":"searchMessageWithKeyword:pageSize:userId:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"searchMessageWithKeyword:pageSize:userId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1searchMessage(keyword:pageSize:userId:completion:)\/fragments","op":"replace"},{"value":"editWithMessageId:text:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1edit(messageId:text:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1edit(messageId:text:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"editWithMessageId:text:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/title","op":"replace","value":"ChatService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/fragments","value":[{"kind":"identifier","text":"ChatService"}]},{"value":[{"kind":"identifier","text":"ChatService"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}