{"kind":"symbol","metadata":{"title":"ChatGroupProfileProviderOC","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"symbolKind":"protocol","navigatorTitle":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)ChatGroupProfileProviderOC"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProviderOC"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatGroupProfileProviderOC"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatgroupprofileprovideroc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatgroupprofileprovideroc"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"title":"Inherits From"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroupProfileProviderOC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProviderOC","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"navigatorTitle":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/chatgroupprofileprovideroc","type":"topic","title":"ChatGroupProfileProviderOC"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroupProfileProviderOC/fetchGroupProfiles(profileIds:completion:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchGroupProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"profileIds","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ([","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)","required":true,"abstract":[{"type":"text","text":"Need to obtain the list display information on the current screen."}],"url":"\/documentation\/easechatuikit\/chatgroupprofileprovideroc\/fetchgroupprofiles(profileids:completion:)","title":"fetchGroupProfiles(profileIds:completion:)","navigatorTitle":[{"kind":"identifier","text":"fetchGroupProfilesWithProfileIds:completion:"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"ChatGroupProfileProviderOC","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatGroupProfileProviderOC"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)"],"generated":true,"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatGroupProfileProviderOC"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC\/title","value":"ChatGroupProfileProviderOC","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC\/fragments","value":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ChatGroupProfileProviderOC"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC~1fetchGroupProfiles(profileIds:completion:)\/title","value":"fetchGroupProfilesWithProfileIds:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC~1fetchGroupProfiles(profileIds:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchGroupProfilesWithProfileIds:completion:","kind":"identifier"}]}]}]}