{"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatThreadParticipantsController","roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ChatThreadParticipantsController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadParticipantsController"}],"title":"ChatThreadParticipantsController","role":"symbol","modules":[{"name":"EaseChatUIKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller"]},{"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/init(chatThread:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/init(coder:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/navigation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participants","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participantsList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/profile"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/createNavigation()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/pop()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/removeMember(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/viewDidLoad()"],"title":"Instance Methods"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UITableViewDelegate-Implementations"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadParticipantsController"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/participantsList":{"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/participantslist","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participantsList","title":"participantsList","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"participantsList"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"participantsList","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/navigation":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","kind":"typeIdentifier","text":"EaseChatNavigationBar"}],"title":"navigation","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/navigation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"navigation"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/navigation"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/fetchParticipants()":{"title":"fetchParticipants()","navigatorTitle":[{"text":"fetchParticipants","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchParticipants","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/fetchparticipants()","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/navigationClick(type:indexPath:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseChatNavigationBarClickEvent","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"navigationClick(type:indexPath:)","type":"topic","abstract":[{"type":"text","text":"Handles the navigation bar click events."}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/navigationclick(type:indexpath:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/navigationClick(type:indexPath:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"title":"UIKit.UIViewControllerTransitioningDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/viewDidLoad()":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"title":"viewDidLoad()","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/viewdidload()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/viewDidLoad()"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIViewController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/pop()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/pop()","role":"symbol","title":"pop()","navigatorTitle":[{"kind":"identifier","text":"pop"}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/pop()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pop","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/profile":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"profile","kind":"identifier"},{"kind":"text","text":": "},{"text":"GroupChatThread","preciseIdentifier":"s:13EaseChatUIKit05GroupB6Threada","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/profile","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"profile","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/profile","title":"profile"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/createNavigation()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createNavigation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","text":"EaseChatNavigationBar"}],"navigatorTitle":[{"text":"createNavigation","kind":"identifier"}],"title":"createNavigation()","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/createnavigation()","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Creates and returns a navigation bar for the ChatThreadParticipantsController."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/createNavigation()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/UIScrollViewDelegate-Implementations":{"kind":"article","title":"UIScrollViewDelegate Implementations","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/uiscrollviewdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UIScrollViewDelegate-Implementations","abstract":[],"role":"collectionGroup","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController","title":"ChatThreadParticipantsController","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDataSource":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","title":"UITableViewDataSource","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/cellForRowAt(indexPath:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/cellForRowAt(indexPath:)","role":"symbol","title":"cellForRowAt(indexPath:)","navigatorTitle":[{"kind":"identifier","text":"cellForRowAtIndexPath:"}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/cellforrowat(indexpath:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellForRowAt","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/participants":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"participants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol"},{"text":"]","kind":"text"}],"title":"participants","type":"topic","abstract":[{"text":"The array of participants in the group.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/participants","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"participants"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participants"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/removeMember(user:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeMember","kind":"identifier"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/removeMember(user:)","type":"topic","navigatorTitle":[{"text":"removeMemberWithUser:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/removemember(user:)","title":"removeMember(user:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/init(chatThread:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"chatThread"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit05GroupB6Threada","kind":"typeIdentifier","text":"GroupChatThread"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/init(chatThread:)","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithChatThread:"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/init(chatthread:)","title":"init(chatThread:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/UITableViewDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/uitableviewdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UITableViewDelegate-Implementations","title":"UITableViewDelegate Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/init(coder:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/init(coder:)","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/init(coder:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIScrollViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","type":"unresolvable","title":"UIKit.UIScrollViewDelegate"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable","title":"Foundation.NSExtensionRequestHandling"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","abstract":[{"text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the chat room UIKit.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/themeswitchprotocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"title":"ThemeSwitchProtocol","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIContentContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","type":"unresolvable","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/ThemeSwitchProtocol-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/themeswitchprotocol-implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/ThemeSwitchProtocol-Implementations","abstract":[],"title":"ThemeSwitchProtocol Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/UITableViewDataSource-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UITableViewDataSource-Implementations","title":"UITableViewDataSource Implementations","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/uitableviewdatasource-implementations","role":"collectionGroup","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ChatThreadParticipantsController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"ChatThreadParticipantsController"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/navigation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participants","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participantsList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/profile"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/cellForRowAt(indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/createNavigation()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/fetchParticipants()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/init(chatThread:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/pop()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/removeMember(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/viewDidLoad()"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UIScrollViewDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UITableViewDelegate-Implementations"]}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ChatThreadParticipantsController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1participantsList\/title","value":"participantsList","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1participantsList\/fragments","op":"replace","value":[{"text":"participantsList","kind":"identifier"}]},{"op":"replace","value":"navigation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1navigation\/title"},{"value":[{"kind":"identifier","text":"navigation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1navigation\/fragments"},{"value":"fetchParticipants","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1fetchParticipants()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1fetchParticipants()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchParticipants"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1navigationClick(type:indexPath:)\/title","value":"navigationClickWithType:indexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1navigationClick(type:indexPath:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"op":"replace"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1viewDidLoad()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1viewDidLoad()\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}]},{"op":"replace","value":"pop","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1pop()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pop"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1pop()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1profile\/title","op":"replace","value":"profile"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1profile\/fragments","op":"replace","value":[{"text":"profile","kind":"identifier"}]},{"value":"createNavigation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1createNavigation()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1createNavigation()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createNavigation"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/title","op":"replace","value":"ChatThreadParticipantsController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/fragments","op":"replace","value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1cellForRowAt(indexPath:)\/title","value":"cellForRowAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1cellForRowAt(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cellForRowAtIndexPath:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1participants\/title","op":"replace","value":"participants"},{"value":[{"kind":"identifier","text":"participants"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1participants\/fragments","op":"replace"},{"op":"replace","value":"removeMemberWithUser:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1removeMember(user:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1removeMember(user:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeMemberWithUser:"}],"op":"replace"},{"op":"replace","value":"initWithChatThread:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1init(chatThread:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithChatThread:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1init(chatThread:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","value":"ThemeSwitchProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title"},{"value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments","op":"replace"}]}]}