{"variants":[{"paths":["\/documentation\/easechatuikit\/commonreactionview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/commonreactionview"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Class","externalID":"c:@M@EaseChatUIKit@objc(cs)CommonReactionView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonReactionView","kind":"identifier"}],"title":"CommonReactionView","navigatorTitle":[{"text":"CommonReactionView","kind":"identifier"}],"symbolKind":"class","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/init(frame:message:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/layout","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/message","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionClosure","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionMore","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionsList"],"anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/fillReactions()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/moreReactions()"],"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/UICollectionViewDelegate-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CommonReactionView","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/message":{"type":"topic","kind":"symbol","title":"message","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/message","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"}],"navigatorTitle":[{"kind":"identifier","text":"message"}],"url":"\/documentation\/easechatuikit\/commonreactionview\/message"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICollectionViewDelegate":{"title":"UICollectionViewDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/fillReactions()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fillReactions","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"text":"fillReactions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/fillReactions()","url":"\/documentation\/easechatuikit\/commonreactionview\/fillreactions()","abstract":[],"title":"fillReactions()","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/layout":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UICollectionViewFlowLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}],"kind":"symbol","navigatorTitle":[{"text":"layout","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/layout","url":"\/documentation\/easechatuikit\/commonreactionview\/layout","abstract":[],"title":"layout","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/ThemeSwitchProtocol-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","url":"\/documentation\/easechatuikit\/commonreactionview\/themeswitchprotocol-implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/UICollectionViewDelegate-Implementations":{"title":"UICollectionViewDelegate Implementations","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/UICollectionViewDelegate-Implementations","type":"topic","url":"\/documentation\/easechatuikit\/commonreactionview\/uicollectionviewdelegate-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/init(coder:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/init(coder:)","url":"\/documentation\/easechatuikit\/commonreactionview\/init(coder:)","abstract":[],"title":"init(coder:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"role":"symbol","url":"\/documentation\/easechatuikit\/themeswitchprotocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","title":"ThemeSwitchProtocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/reactions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reactions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Reaction","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)Reaction"},{"kind":"text","text":"]"}],"url":"\/documentation\/easechatuikit\/commonreactionview\/reactions","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"reactions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactions","title":"reactions","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/init(frame:message:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":")"}],"title":"init(frame:message:)","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:message:"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/init(frame:message:)","url":"\/documentation\/easechatuikit\/commonreactionview\/init(frame:message:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/moreReactions()":{"url":"\/documentation\/easechatuikit\/commonreactionview\/morereactions()","navigatorTitle":[{"kind":"identifier","text":"moreReactions"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/moreReactions()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moreReactions","kind":"identifier"},{"kind":"text","text":"()"}],"title":"moreReactions()","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/reactionMore":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reactionMore"},{"text":": ","kind":"text"},{"text":"UIButton","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIButton"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionMore","navigatorTitle":[{"text":"reactionMore","kind":"identifier"}],"title":"reactionMore","url":"\/documentation\/easechatuikit\/commonreactionview\/reactionmore","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICollectionViewDataSource":{"title":"UICollectionViewDataSource","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDataSource","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/UICollectionViewDataSource-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/UICollectionViewDataSource-Implementations","title":"UICollectionViewDataSource Implementations","url":"\/documentation\/easechatuikit\/commonreactionview\/uicollectionviewdatasource-implementations","role":"collectionGroup","kind":"article","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIView":{"title":"UIView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/reactionsList":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reactionsList","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"text":"reactionsList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionsList","url":"\/documentation\/easechatuikit\/commonreactionview\/reactionslist","abstract":[],"title":"reactionsList","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/commonreactionview","navigatorTitle":[{"kind":"identifier","text":"CommonReactionView"}],"abstract":[],"title":"CommonReactionView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CommonReactionView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/reactionClosure":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"reactionClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionClosure","navigatorTitle":[{"text":"reactionClosure","kind":"identifier"}],"title":"reactionClosure","url":"\/documentation\/easechatuikit\/commonreactionview\/reactionclosure","role":"symbol","kind":"symbol","abstract":[{"type":"codeVoice","code":"String"},{"type":"text","text":" represents the emoji of reaction,if empty,means more"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIScrollViewDelegate":{"title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"CommonReactionView","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"CommonReactionView"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"CommonReactionView","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/layout","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/message","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionClosure","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionMore","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactionsList"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/fillReactions()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/init(frame:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/moreReactions()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/UICollectionViewDelegate-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}]},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegate"]}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"CommonReactionView","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1message\/title","op":"replace","value":"message"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1message\/fragments","value":[{"text":"message","kind":"identifier"}]},{"value":"fillReactions","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1fillReactions()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1fillReactions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fillReactions"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1layout\/title","value":"layout","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1layout\/fragments","value":[{"kind":"identifier","text":"layout"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1init(coder:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title","op":"replace","value":"ThemeSwitchProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactions\/title","value":"reactions","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactions\/fragments","value":[{"text":"reactions","kind":"identifier"}],"op":"replace"},{"value":"initWithFrame:message:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1init(frame:message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1init(frame:message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:message:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1moreReactions()\/title","op":"replace","value":"moreReactions"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1moreReactions()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"moreReactions","kind":"identifier"}],"op":"replace"},{"value":"reactionMore","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactionMore\/title","op":"replace"},{"value":[{"kind":"identifier","text":"reactionMore"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactionMore\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactionsList\/title","op":"replace","value":"reactionsList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactionsList\/fragments","value":[{"kind":"identifier","text":"reactionsList"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/title","value":"CommonReactionView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/fragments","op":"replace","value":[{"text":"CommonReactionView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"CommonReactionView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactionClosure\/title","value":"reactionClosure"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactionClosure\/fragments","value":[{"text":"reactionClosure","kind":"identifier"}],"op":"replace"}]}]}