{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"},"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComponentsRegister","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister","roleHeading":"Class","title":"ComponentsRegister"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAlertCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCombineCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatContactMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatFileMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatImageMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatLocationCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatTextMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatVideoMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactInfoController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactViewService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactsCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/Conversation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationViewService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupInfoController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupParticipantController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/JoinedGroupsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageRenderEntity","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessagesViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/NewFriendRequestController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/RemoveGroupParticipantController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ReportViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/customCellClasses"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/shared"],"title":"Type Properties"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/componentsregister"]},{"paths":["\/documentation\/easechatuikit\/componentsregister"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ComponentsRegister","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatFileMessageCell":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatFileMessageCell","navigatorTitle":[{"text":"ChatFileMessageCell","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatFileMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FileMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)FileMessageCell"},{"kind":"text","text":".Type"}],"title":"ChatFileMessageCell","role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/chatfilemessagecell"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ConversationsController":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationsController"},{"text":": ","kind":"text"},{"text":"ConversationListController","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationListController"},{"text":".Type","kind":"text"}],"kind":"symbol","abstract":[{"type":"text","text":"Conversation list page controller"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationsController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsController"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/conversationscontroller","title":"ConversationsController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ContactInfoController":{"url":"\/documentation\/easechatuikit\/componentsregister\/contactinfocontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactInfoController","title":"ContactInfoController","abstract":[{"text":"Contact detail info of the group.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactInfoController"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactInfoController","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController","kind":"typeIdentifier","text":"ContactInfoViewController"},{"text":".Type","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ContactViewService":{"abstract":[{"text":"Contact list view model.","type":"text"}],"url":"\/documentation\/easechatuikit\/componentsregister\/contactviewservice","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactViewService"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactViewModel","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel"},{"text":".Type","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactViewService","type":"topic","kind":"symbol","title":"ContactViewService","navigatorTitle":[{"text":"ContactViewService","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ConversationCell":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"ConversationCell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationListCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationListCell"},{"kind":"text","text":".Type"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationCell","type":"topic","navigatorTitle":[{"text":"ConversationCell","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/conversationcell","title":"ConversationCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/GroupParticipantController":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantController"},{"text":": ","kind":"text"},{"text":"GroupParticipantsController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupParticipantController","title":"GroupParticipantController","url":"\/documentation\/easechatuikit\/componentsregister\/groupparticipantcontroller","role":"symbol","abstract":[{"text":"Participants controller of the group.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GroupParticipantController"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ContactsCell":{"title":"ContactsCell","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactsCell","url":"\/documentation\/easechatuikit\/componentsregister\/contactscell","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactsCell"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactCell","text":"ContactCell","kind":"typeIdentifier"},{"kind":"text","text":".Type"}],"navigatorTitle":[{"text":"ContactsCell","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatLocationCell":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatLocationCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LocationMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)LocationMessageCell"},{"text":".Type","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatLocationCell","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ChatLocationCell","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/chatlocationcell","title":"ChatLocationCell"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/JoinedGroupsController":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/JoinedGroupsController","role":"symbol","title":"JoinedGroupsController","navigatorTitle":[{"kind":"identifier","text":"JoinedGroupsController"}],"url":"\/documentation\/easechatuikit\/componentsregister\/joinedgroupscontroller","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoinedGroupsController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JoinedGroupsViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)JoinedGroupsViewController"},{"kind":"text","text":".Type"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/shared":{"title":"shared","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/shared","kind":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/shared","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister","kind":"typeIdentifier","text":"ComponentsRegister"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatAlertCell":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAlertCell","abstract":[],"url":"\/documentation\/easechatuikit\/componentsregister\/chatalertcell","title":"ChatAlertCell","navigatorTitle":[{"kind":"identifier","text":"ChatAlertCell"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAlertCell","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertMessageCell","text":"AlertMessageCell"},{"kind":"text","text":".Type"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatAudioMessageCell":{"url":"\/documentation\/easechatuikit\/componentsregister\/chataudiomessagecell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","title":"ChatAudioMessageCell","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatAudioMessageCell"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatAudioMessageCell","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AudioMessageCell","text":"AudioMessageCell"},{"kind":"text","text":".Type"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/MessageViewController":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MessageViewController","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageListController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageListController"},{"kind":"text","text":".Type"}],"kind":"symbol","abstract":[{"text":"Message list page controller.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageViewController","type":"topic","navigatorTitle":[{"text":"MessageViewController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/messageviewcontroller","title":"MessageViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatImageMessageCell":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatImageMessageCell"},{"kind":"text","text":": "},{"text":"ImageMessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageMessageCell"},{"text":".Type","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatImageMessageCell","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"ChatImageMessageCell","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/chatimagemessagecell","title":"ChatImageMessageCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/RemoveGroupParticipantController":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RemoveGroupParticipantController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsRemoveController","text":"GroupParticipantsRemoveController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"kind":"symbol","abstract":[{"text":"Remove participants controller of the group.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/RemoveGroupParticipantController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RemoveGroupParticipantController"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/removegroupparticipantcontroller","title":"RemoveGroupParticipantController"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatContactMessageCell":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatContactMessageCell","url":"\/documentation\/easechatuikit\/componentsregister\/chatcontactmessagecell","role":"symbol","title":"ChatContactMessageCell","navigatorTitle":[{"text":"ChatContactMessageCell","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatContactMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactCardCell","text":"ContactCardCell","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatCustomMessageCell":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ChatCustomMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CustomMessageCell","text":"CustomMessageCell"},{"kind":"text","text":".Type"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","type":"topic","navigatorTitle":[{"text":"ChatCustomMessageCell","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/chatcustommessagecell","title":"ChatCustomMessageCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/Conversation":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/Conversation","role":"symbol","title":"Conversation","navigatorTitle":[{"text":"Conversation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/componentsregister\/conversation","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":".Type"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatCombineCell":{"url":"\/documentation\/easechatuikit\/componentsregister\/chatcombinecell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCombineCell","navigatorTitle":[{"kind":"identifier","text":"ChatCombineCell"}],"title":"ChatCombineCell","abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ChatCombineCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CombineMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CombineMessageCell"},{"text":".Type","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/GroupInfoController":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupInfoController","role":"symbol","title":"GroupInfoController","navigatorTitle":[{"text":"GroupInfoController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/componentsregister\/groupinfocontroller","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoController","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController","kind":"typeIdentifier","text":"GroupInfoViewController"},{"kind":"text","text":".Type"}],"abstract":[{"text":"Group detail info view controller.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/MessagesViewModel":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessagesViewModel","role":"symbol","title":"MessagesViewModel","navigatorTitle":[{"kind":"identifier","text":"MessagesViewModel"}],"url":"\/documentation\/easechatuikit\/componentsregister\/messagesviewmodel","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MessagesViewModel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageListViewModel","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageListViewModel"},{"kind":"text","text":".Type"}]},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/customCellClasses":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"customCellClasses","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"text":".Type]","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/customCellClasses","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"customCellClasses","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/customcellclasses","title":"customCellClasses"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/registerCustomizeCellClass(cellType:)":{"url":"\/documentation\/easechatuikit\/componentsregister\/registercustomizecellclass(celltype:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)","title":"registerCustomizeCellClass(cellType:)","kind":"symbol","abstract":[{"text":"Register customize table view cell method.","type":"text"}],"navigatorTitle":[{"text":"registerCustomizeCellClassWithCellType:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerCustomizeCellClass"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cellType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier","text":"MessageCell"},{"kind":"text","text":".Type)"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ConversationViewService":{"url":"\/documentation\/easechatuikit\/componentsregister\/conversationviewservice","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationViewService","kind":"symbol","title":"ConversationViewService","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationViewService"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationViewModel","text":"ConversationViewModel","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"navigatorTitle":[{"text":"ConversationViewService","kind":"identifier"}],"type":"topic","abstract":[{"text":"Conversation list view model.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ContactsController":{"url":"\/documentation\/easechatuikit\/componentsregister\/contactscontroller","abstract":[{"type":"text","text":"Contact list page controller."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ContactsController","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactViewController","text":"ContactViewController"},{"text":".Type","kind":"text"}],"type":"topic","title":"ContactsController","kind":"symbol","navigatorTitle":[{"text":"ContactsController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactsController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatTextMessageCell":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatTextMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TextMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)TextMessageCell"},{"text":".Type","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatTextMessageCell","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatTextMessageCell"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/chattextmessagecell","title":"ChatTextMessageCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ReportViewController":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ReportViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ReportOptionsController","text":"ReportOptionsController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ReportViewController","kind":"symbol","abstract":[{"text":"Report message controller.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ReportViewController"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/reportviewcontroller","title":"ReportViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/init":{"url":"\/documentation\/easechatuikit\/componentsregister\/init","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/init","title":"init","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"url":"\/documentation\/easechatuikit\/componentsregister","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"title":"ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/MessageRenderEntity":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageRenderEntity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":".Type"}],"abstract":[{"type":"text","text":"Message cell render entity."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageRenderEntity","type":"topic","navigatorTitle":[{"text":"MessageRenderEntity","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/messagerenderentity","title":"MessageRenderEntity"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/NewFriendRequestController":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"NewFriendRequestController","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NewContactRequestController","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)NewContactRequestController"},{"kind":"text","text":".Type"}],"kind":"symbol","abstract":[{"type":"text","text":"New friend request controller."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/NewFriendRequestController","type":"topic","navigatorTitle":[{"text":"NewFriendRequestController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/newfriendrequestcontroller","title":"NewFriendRequestController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatVideoMessageCell":{"kind":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/chatvideomessagecell","navigatorTitle":[{"text":"ChatVideoMessageCell","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatVideoMessageCell","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"VideoMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)VideoMessageCell"},{"kind":"text","text":".Type"}],"type":"topic","title":"ChatVideoMessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatVideoMessageCell"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ComponentsRegister","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"text":"ComponentsRegister","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ComponentsRegister"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAlertCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCombineCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatContactMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatFileMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatImageMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatLocationCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatTextMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatVideoMessageCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactInfoController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactViewService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactsCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/Conversation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationViewService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupInfoController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupParticipantController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/JoinedGroupsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageRenderEntity","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessagesViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/NewFriendRequestController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/RemoveGroupParticipantController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ReportViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/customCellClasses"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/init","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/registerCustomizeCellClass(cellType:)"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/shared"],"title":"Type Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ComponentsRegister","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatFileMessageCell\/title","op":"replace","value":"ChatFileMessageCell"},{"value":[{"text":"ChatFileMessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatFileMessageCell\/fragments"},{"value":"ConversationsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationsController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationsController\/fragments","value":[{"text":"ConversationsController","kind":"identifier"}]},{"value":"ContactInfoController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactInfoController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ContactInfoController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactInfoController\/fragments"},{"value":"ContactViewService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactViewService\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactViewService\/fragments","op":"replace","value":[{"text":"ContactViewService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationCell\/title","op":"replace","value":"ConversationCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationCell\/fragments","value":[{"text":"ConversationCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupParticipantController\/title","value":"GroupParticipantController"},{"value":[{"kind":"identifier","text":"GroupParticipantController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupParticipantController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactsCell\/title","op":"replace","value":"ContactsCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactsCell\/fragments","value":[{"text":"ContactsCell","kind":"identifier"}],"op":"replace"},{"value":"ChatLocationCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatLocationCell\/title"},{"value":[{"text":"ChatLocationCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatLocationCell\/fragments","op":"replace"},{"op":"replace","value":"JoinedGroupsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1JoinedGroupsController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1JoinedGroupsController\/fragments","op":"replace","value":[{"text":"JoinedGroupsController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1shared\/title","value":"shared"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1shared\/fragments","op":"replace","value":[{"kind":"identifier","text":"shared"}]},{"value":"ChatAlertCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatAlertCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatAlertCell\/fragments","value":[{"text":"ChatAlertCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/title","value":"ChatAudioMessageCell","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/fragments","value":[{"text":"ChatAudioMessageCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessageViewController\/title","value":"MessageViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessageViewController\/fragments","value":[{"text":"MessageViewController","kind":"identifier"}]},{"op":"replace","value":"ChatImageMessageCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatImageMessageCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatImageMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatImageMessageCell"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1RemoveGroupParticipantController\/title","value":"RemoveGroupParticipantController"},{"value":[{"kind":"identifier","text":"RemoveGroupParticipantController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1RemoveGroupParticipantController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatContactMessageCell\/title","value":"ChatContactMessageCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatContactMessageCell\/fragments","value":[{"text":"ChatContactMessageCell","kind":"identifier"}],"op":"replace"},{"value":"ChatCustomMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatCustomMessageCell\/title"},{"value":[{"kind":"identifier","text":"ChatCustomMessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatCustomMessageCell\/fragments"},{"op":"replace","value":"Conversation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1Conversation\/title"},{"value":[{"text":"Conversation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1Conversation\/fragments","op":"replace"},{"op":"replace","value":"ChatCombineCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatCombineCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatCombineCell\/fragments","value":[{"kind":"identifier","text":"ChatCombineCell"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupInfoController\/title","value":"GroupInfoController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GroupInfoController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupInfoController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessagesViewModel\/title","value":"MessagesViewModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessagesViewModel\/fragments","value":[{"text":"MessagesViewModel","kind":"identifier"}]},{"value":"customCellClasses","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1customCellClasses\/title"},{"op":"replace","value":[{"text":"customCellClasses","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1customCellClasses\/fragments"},{"value":"registerCustomizeCellClassWithCellType:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1registerCustomizeCellClass(cellType:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerCustomizeCellClassWithCellType:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1registerCustomizeCellClass(cellType:)\/fragments"},{"value":"ConversationViewService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationViewService\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationViewService\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationViewService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactsController\/title","value":"ContactsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactsController\/fragments","value":[{"kind":"identifier","text":"ContactsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/title","value":"ChatTextMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatTextMessageCell"}]},{"value":"ReportViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ReportViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ReportViewController\/fragments","value":[{"text":"ReportViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","op":"replace","value":"ComponentsRegister"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessageRenderEntity\/title","value":"MessageRenderEntity","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessageRenderEntity\/fragments","op":"replace","value":[{"text":"MessageRenderEntity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1NewFriendRequestController\/title","value":"NewFriendRequestController"},{"value":[{"text":"NewFriendRequestController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1NewFriendRequestController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatVideoMessageCell\/title","op":"replace","value":"ChatVideoMessageCell"},{"value":[{"kind":"identifier","text":"ChatVideoMessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatVideoMessageCell\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}