{"metadata":{"navigatorTitle":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"symbolKind":"enum","title":"ContactListHeaderStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ContactListHeaderStyle","kind":"identifier"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","roleHeading":"Enumeration"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/addGroupParticipant","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/contact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newChat","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newGroup","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/shareContact"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ContactListHeaderStyle","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactlistheaderstyle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactlistheaderstyle"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle"},"abstract":[{"type":"text","text":"The header display style of the "},{"type":"codeVoice","code":"ContactList"},{"type":"text","text":"."}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"]}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/init(rawValue:)":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/init(rawValue:)","title":"init(rawValue:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/init(rawvalue:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/addGroupParticipant":{"navigatorTitle":[{"text":"ContactListHeaderStyleAddGroupParticipant","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/addGroupParticipant","kind":"symbol","role":"symbol","title":"ContactListHeaderStyle.addGroupParticipant","url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/addgroupparticipant","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addGroupParticipant"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/newGroup":{"role":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/newgroup","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newGroup","abstract":[],"title":"ContactListHeaderStyle.newGroup","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyleNewGroup"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"newGroup","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/newChat":{"navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyleNewChat"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newChat","kind":"symbol","role":"symbol","title":"ContactListHeaderStyle.newChat","url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/newchat","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"newChat","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/RawRepresentable-Implementations","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/contact":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"contact","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ContactListHeaderStyle.contact","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/contact","abstract":[],"url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/contact","navigatorTitle":[{"text":"ContactListHeaderStyleContact","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/Equatable-Implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/shareContact":{"title":"ContactListHeaderStyle.shareContact","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/sharecontact","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/shareContact","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyleShareContact"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"shareContact","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListHeaderStyle"}],"type":"topic","kind":"symbol","title":"ContactListHeaderStyle","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","abstract":[{"text":"The header display style of the ","type":"text"},{"code":"ContactList","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/easechatuikit\/contactlistheaderstyle","navigatorTitle":[{"text":"ContactListHeaderStyle","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"ContactListHeaderStyle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","value":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/addGroupParticipant","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/contact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newChat","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newGroup","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/shareContact"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ContactListHeaderStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1addGroupParticipant\/title","op":"replace","value":"ContactListHeaderStyleAddGroupParticipant"},{"value":[{"kind":"identifier","text":"ContactListHeaderStyleAddGroupParticipant"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1addGroupParticipant\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1newGroup\/title","value":"ContactListHeaderStyleNewGroup","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1newGroup\/fragments","value":[{"text":"ContactListHeaderStyleNewGroup","kind":"identifier"}]},{"op":"replace","value":"ContactListHeaderStyleNewChat","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1newChat\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1newChat\/fragments","value":[{"text":"ContactListHeaderStyleNewChat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1contact\/title","value":"ContactListHeaderStyleContact"},{"op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderStyleContact"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1contact\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1shareContact\/title","op":"replace","value":"ContactListHeaderStyleShareContact"},{"op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderStyleShareContact"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1shareContact\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/title","value":"ContactListHeaderStyle","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}