{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/didSelected(indexPath:profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListScroll(indexPath:)"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactlistactioneventsdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactlistactioneventsdelegate"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ContactListActionEventsDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"abstract":[{"text":"ContactList action events delegate.","type":"text"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ContactListActionEventsDelegate"}],"role":"symbol","symbolKind":"protocol","roleHeading":"Protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)ContactListActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListActionEventsDelegate"}],"title":"ContactListActionEventsDelegate","modules":[{"name":"EaseChatUIKit"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListActionEventsDelegate/onContactListScroll(indexPath:)":{"navigatorTitle":[{"kind":"identifier","text":"onContactListScrollWithIndexPath:"}],"abstract":[{"text":"When contact list scrolled.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListScroll(indexPath:)","type":"topic","url":"\/documentation\/easechatuikit\/contactlistactioneventsdelegate\/oncontactlistscroll(indexpath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onContactListScroll","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"title":"onContactListScroll(indexPath:)","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListActionEventsDelegate":{"abstract":[{"text":"ContactList action events delegate.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate","type":"topic","url":"\/documentation\/easechatuikit\/contactlistactioneventsdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListActionEventsDelegate"}],"title":"ContactListActionEventsDelegate","navigatorTitle":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListActionEventsDelegate/onContactListOccurErrorWhenFetchServer()":{"navigatorTitle":[{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"}],"abstract":[{"type":"text","text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListOccurErrorWhenFetchServer()","type":"topic","url":"\/documentation\/easechatuikit\/contactlistactioneventsdelegate\/oncontactlistoccurerrorwhenfetchserver()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"},{"text":"()","kind":"text"}],"title":"onContactListOccurErrorWhenFetchServer()","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListActionEventsDelegate/onContactListEndScrollNeededDisplayInfos(ids:)":{"navigatorTitle":[{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}],"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListEndScrollNeededDisplayInfos(ids:)","type":"topic","url":"\/documentation\/easechatuikit\/contactlistactioneventsdelegate\/oncontactlistendscrollneededdisplayinfos(ids:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfos"},{"text":"(","kind":"text"},{"text":"ids","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"title":"onContactListEndScrollNeededDisplayInfos(ids:)","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListActionEventsDelegate/didSelected(indexPath:profile:)":{"navigatorTitle":[{"text":"didSelectedWithIndexPath:profile:","kind":"identifier"}],"abstract":[{"text":"The method’ll called on contact list cell clicked.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/didSelected(indexPath:profile:)","type":"topic","url":"\/documentation\/easechatuikit\/contactlistactioneventsdelegate\/didselected(indexpath:profile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didSelected","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}],"title":"didSelected(indexPath:profile:)","required":true},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","url":"\/documentation\/easechatuikit\/contactviewmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewModel","kind":"identifier"}],"title":"ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"ContactListActionEventsDelegate","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"ContactListActionEventsDelegate"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/didSelected(indexPath:profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListScroll(indexPath:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"]},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"],"type":"conformingTypes","kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListActionEventsDelegate"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"onContactListScrollWithIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListScroll(indexPath:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onContactListScrollWithIndexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListScroll(indexPath:)\/fragments"},{"value":"ContactListActionEventsDelegate","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate\/fragments","value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListOccurErrorWhenFetchServer()\/title","value":"onContactListOccurErrorWhenFetchServer","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListOccurErrorWhenFetchServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListEndScrollNeededDisplayInfos(ids:)\/title","value":"onContactListEndScrollNeededDisplayInfosWithIds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListEndScrollNeededDisplayInfos(ids:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}]},{"op":"replace","value":"didSelectedWithIndexPath:profile:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1didSelected(indexPath:profile:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1didSelected(indexPath:profile:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"didSelectedWithIndexPath:profile:","kind":"identifier"}],"op":"replace"},{"value":"ContactViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"kind":"identifier","text":"ContactViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}