{"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)"],"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactEmergencyListener"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactemergencylistener"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactemergencylistener"]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"]}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","symbolKind":"protocol","title":"ContactEmergencyListener","navigatorTitle":[{"text":"ContactEmergencyListener","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEmergencyListener","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Protocol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyListener/onResult(error:type:operatorId:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)","url":"\/documentation\/easechatuikit\/contactemergencylistener\/onresult(error:type:operatorid:)","title":"onResult(error:type:operatorId:)","kind":"symbol","required":true,"role":"symbol","abstract":[{"text":"You’ll receive the result on conversation service request successful or failure.","type":"text"}],"navigatorTitle":[{"text":"onResultWithError:type:operatorId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onResult","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?, "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContactEmergencyType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactEmergencyType"},{"kind":"text","text":", "},{"text":"operatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyListener":{"title":"ContactEmergencyListener","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener","url":"\/documentation\/easechatuikit\/contactemergencylistener","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ContactEmergencyListener","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEmergencyListener","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ContactEmergencyListener"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"ContactEmergencyListener"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"ContactEmergencyListener","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactEmergencyListener","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener~1onResult(error:type:operatorId:)\/title","op":"replace","value":"onResultWithError:type:operatorId:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener~1onResult(error:type:operatorId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onResultWithError:type:operatorId:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/title","value":"ContactEmergencyListener"},{"value":[{"kind":"identifier","text":"ContactEmergencyListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/fragments"}]}]}