{"metadata":{"role":"symbol","roleHeading":"Protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)ContactEventsResponse","title":"ContactEventsResponse","navigatorTitle":[{"kind":"identifier","text":"ContactEventsResponse"}],"symbolKind":"protocol","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactEventsResponse"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidAgree(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidDecline(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidReceive(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendshipDidAddSuccessful(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendshipDidRemove(by:)"]}],"variants":[{"paths":["\/documentation\/easechatuikit\/contacteventsresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contacteventsresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEventsResponse","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEventsResponse":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse","kind":"symbol","title":"ContactEventsResponse","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactEventsResponse"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/contacteventsresponse","navigatorTitle":[{"kind":"identifier","text":"ContactEventsResponse"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEventsResponse/friendRequestDidReceive(by:)":{"required":true,"title":"friendRequestDidReceive(by:)","url":"\/documentation\/easechatuikit\/contacteventsresponse\/friendrequestdidreceive(by:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidReceive"},{"text":"(","kind":"text"},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidReceive(by:)","kind":"symbol","abstract":[{"type":"text","text":"Received friend request"}],"navigatorTitle":[{"text":"friendRequestDidReceiveBy:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEventsResponse/friendRequestDidAgree(by:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"friendRequestDidAgree","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol","title":"friendRequestDidAgree(by:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidAgree(by:)","url":"\/documentation\/easechatuikit\/contacteventsresponse\/friendrequestdidagree(by:)","abstract":[{"text":"The friend request was accepted by the other party","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidAgreeBy:"}],"kind":"symbol","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEventsResponse/friendshipDidAddSuccessful(by:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendshipDidAddSuccessful"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","title":"friendshipDidAddSuccessful(by:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendshipDidAddSuccessful(by:)","url":"\/documentation\/easechatuikit\/contacteventsresponse\/friendshipdidaddsuccessful(by:)","abstract":[{"type":"text","text":"Friend relationship added successfully"}],"navigatorTitle":[{"kind":"identifier","text":"friendshipDidAddSuccessfulBy:"}],"kind":"symbol","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEventsResponse/friendshipDidRemove(by:)":{"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/contacteventsresponse\/friendshipdidremove(by:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendshipDidRemove"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"friendshipDidRemoveBy:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendshipDidRemove(by:)","abstract":[{"type":"text","text":"The friend relationship was removed by the other party"}],"title":"friendshipDidRemove(by:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","url":"\/documentation\/easechatuikit\/contactviewmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewModel","kind":"identifier"}],"title":"ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEventsResponse/friendRequestDidDecline(by:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"friendRequestDidDecline","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","title":"friendRequestDidDecline(by:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidDecline(by:)","url":"\/documentation\/easechatuikit\/contacteventsresponse\/friendrequestdiddecline(by:)","abstract":[{"type":"text","text":"Friend request was rejected by the other party"}],"navigatorTitle":[{"text":"friendRequestDidDeclineBy:","kind":"identifier"}],"kind":"symbol","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ContactEventsResponse","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactEventsResponse"}]},{"op":"replace","value":[{"kind":"identifier","text":"ContactEventsResponse"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidAgree(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidDecline(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendRequestDidReceive(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendshipDidAddSuccessful(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEventsResponse\/friendshipDidRemove(by:)"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactEventsResponse"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse\/title","op":"replace","value":"ContactEventsResponse"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse\/fragments","value":[{"kind":"identifier","text":"ContactEventsResponse"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendRequestDidReceive(by:)\/title","value":"friendRequestDidReceiveBy:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendRequestDidReceive(by:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidReceiveBy:"}]},{"op":"replace","value":"friendRequestDidAgreeBy:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendRequestDidAgree(by:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendRequestDidAgree(by:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"friendRequestDidAgreeBy:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendshipDidAddSuccessful(by:)\/title","value":"friendshipDidAddSuccessfulBy:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendshipDidAddSuccessful(by:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"friendshipDidAddSuccessfulBy:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendshipDidRemove(by:)\/title","value":"friendshipDidRemoveBy:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"friendshipDidRemoveBy:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendshipDidRemove(by:)\/fragments"},{"value":"ContactViewModel","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"text":"ContactViewModel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendRequestDidDecline(by:)\/title","value":"friendRequestDidDeclineBy:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEventsResponse~1friendRequestDidDecline(by:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"friendRequestDidDeclineBy:","kind":"identifier"}],"op":"replace"}]}]}