{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactserviceprotocol"]},{"paths":["\/documentation\/easechatuikit\/contactserviceprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactServiceProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/addContact(userId:invitation:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/addUserToBlackList(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/agreeFriendRequest(from:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/bindContactEventListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/contacts(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/declineFriendRequest(from:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/removeContact(userId:removeChannel:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/removeUserFromBlackList(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/setRemark(userId:remark:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unbindContactEventListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unregisterEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/userBlackList(completion:)"]}],"metadata":{"navigatorTitle":[{"text":"ContactServiceProtocol","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)ContactServiceProtocol","modules":[{"name":"EaseChatUIKit"}],"title":"ContactServiceProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ContactServiceProtocol","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/addContact(userId:invitation:completion:)":{"navigatorTitle":[{"text":"addContactWithUserId:invitation:completion:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/contactserviceprotocol\/addcontact(userid:invitation:completion:)","type":"topic","title":"addContact(userId:invitation:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addContact","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitation"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Add contact."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/addContact(userId:invitation:completion:)","kind":"symbol","required":true,"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/unbindContactEventListener(listener:)":{"navigatorTitle":[{"text":"unbindContactEventListenerWithListener:","kind":"identifier"}],"required":true,"abstract":[{"text":"Unbind contacts state changed listener","type":"text"}],"url":"\/documentation\/easechatuikit\/contactserviceprotocol\/unbindcontacteventlistener(listener:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unbindContactEventListener(listener:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unbindContactEventListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEventsResponse","text":"ContactEventsResponse"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","title":"unbindContactEventListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/bindContactEventListener(listener:)":{"navigatorTitle":[{"kind":"identifier","text":"bindContactEventListenerWithListener:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindContactEventListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEventsResponse","text":"ContactEventsResponse"},{"text":")","kind":"text"}],"title":"bindContactEventListener(listener:)","kind":"symbol","type":"topic","abstract":[{"text":"Bind contacts changed listener","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/bindContactEventListener(listener:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/bindcontacteventlistener(listener:)","required":true,"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol":{"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactServiceProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ContactServiceProtocol"}],"title":"ContactServiceProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol","url":"\/documentation\/easechatuikit\/contactserviceprotocol","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/contacts(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"contactsWithCompletion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contacts"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?, [","kind":"text"},{"kind":"typeIdentifier","text":"Contact","preciseIdentifier":"s:13EaseChatUIKit7Contacta"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"contacts(completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Fetch contacts form server.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/contacts(completion:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/contacts(completion:)","required":true,"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/removeContact(userId:removeChannel:completion:)":{"navigatorTitle":[{"text":"removeContactWithUserId:removeChannel:completion:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeContact","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"removeChannel","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"removeContact(userId:removeChannel:completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Remove contact.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/removeContact(userId:removeChannel:completion:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/removecontact(userid:removechannel:completion:)","required":true,"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/userBlackList(completion:)":{"navigatorTitle":[{"kind":"identifier","text":"userBlackListWithCompletion:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userBlackList","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?, ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"userBlackList(completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Get friend blacklist list","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/userBlackList(completion:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/userblacklist(completion:)","required":true,"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/addUserToBlackList(userId:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"addUserToBlackListWithUserId:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addUserToBlackList"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"title":"addUserToBlackList(userId:completion:)","kind":"symbol","type":"topic","abstract":[{"text":"Add user to black list.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/addUserToBlackList(userId:completion:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/addusertoblacklist(userid:completion:)","required":true,"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/deviceIdsOnOtherPlatformOfCurrentUser(completion:)":{"navigatorTitle":[{"text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","required":true,"abstract":[{"text":"Get the device ID array of all current user logins except the current device.","type":"text"}],"title":"deviceIdsOnOtherPlatformOfCurrentUser(completion:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/deviceidsonotherplatformofcurrentuser(completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deviceIdsOnOtherPlatformOfCurrentUser","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?, ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","abstract":[],"url":"\/documentation\/easechatuikit\/contactserviceimplement","navigatorTitle":[{"text":"ContactServiceImplement","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactServiceImplement"}],"kind":"symbol","type":"topic","title":"ContactServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/unregisterEmergencyListener(listener:)":{"required":true,"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/unregisteremergencylistener(listener:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"}],"title":"unregisterEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterEmergencyListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","text":"ContactEmergencyListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"Unregister emergency listener","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unregisterEmergencyListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/registerEmergencyListener(listener:)":{"navigatorTitle":[{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","required":true,"abstract":[{"type":"text","text":"Register emergency listener"}],"title":"registerEmergencyListener(listener:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/registeremergencylistener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerEmergencyListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","text":"ContactEmergencyListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/registerEmergencyListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/declineFriendRequest(from:completion:)":{"kind":"symbol","required":true,"title":"declineFriendRequest(from:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/declineFriendRequest(from:completion:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/declinefriendrequest(from:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"declineFriendRequest"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?, "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","navigatorTitle":[{"text":"declineFriendRequestFrom:completion:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Decline friend request."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/removeUserFromBlackList(userId:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"removeUserFromBlackListWithUserId:completion:"}],"type":"topic","kind":"symbol","role":"symbol","required":true,"title":"removeUserFromBlackList(userId:completion:)","abstract":[{"type":"text","text":"Remove user from black list."}],"url":"\/documentation\/easechatuikit\/contactserviceprotocol\/removeuserfromblacklist(userid:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeUserFromBlackList","kind":"identifier"},{"kind":"text","text":"("},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/removeUserFromBlackList(userId:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/setRemark(userId:remark:completion:)":{"navigatorTitle":[{"text":"setRemarkWithUserId:remark:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","required":true,"abstract":[{"text":"Set remark to the friend.","type":"text"}],"title":"setRemark(userId:remark:completion:)","url":"\/documentation\/easechatuikit\/contactserviceprotocol\/setremark(userid:remark:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setRemark","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"remark","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Contact","preciseIdentifier":"s:13EaseChatUIKit7Contacta"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/setRemark(userId:remark:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceProtocol/agreeFriendRequest(from:completion:)":{"navigatorTitle":[{"text":"agreeFriendRequestFrom:completion:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","required":true,"title":"agreeFriendRequest(from:completion:)","abstract":[{"type":"text","text":"Agree friend request."}],"url":"\/documentation\/easechatuikit\/contactserviceprotocol\/agreefriendrequest(from:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"agreeFriendRequest"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/agreeFriendRequest(from:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"ContactServiceProtocol"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ContactServiceProtocol","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"ContactServiceProtocol","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/addContact(userId:invitation:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/addUserToBlackList(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/agreeFriendRequest(from:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/bindContactEventListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/contacts(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/declineFriendRequest(from:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/deviceIdsOnOtherPlatformOfCurrentUser(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/removeContact(userId:removeChannel:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/removeUserFromBlackList(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/setRemark(userId:remark:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unbindContactEventListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/unregisterEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceProtocol\/userBlackList(completion:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"ContactServiceProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"addContactWithUserId:invitation:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1addContact(userId:invitation:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1addContact(userId:invitation:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addContactWithUserId:invitation:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1unbindContactEventListener(listener:)\/title","value":"unbindContactEventListenerWithListener:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"unbindContactEventListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1unbindContactEventListener(listener:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1bindContactEventListener(listener:)\/title","op":"replace","value":"bindContactEventListenerWithListener:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindContactEventListenerWithListener:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1bindContactEventListener(listener:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol\/title","op":"replace","value":"ContactServiceProtocol"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactServiceProtocol"}]},{"value":"contactsWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1contacts(completion:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"contactsWithCompletion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1contacts(completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1removeContact(userId:removeChannel:completion:)\/title","op":"replace","value":"removeContactWithUserId:removeChannel:completion:"},{"value":[{"text":"- ","kind":"text"},{"text":"removeContactWithUserId:removeChannel:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1removeContact(userId:removeChannel:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1userBlackList(completion:)\/title","value":"userBlackListWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1userBlackList(completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userBlackListWithCompletion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1addUserToBlackList(userId:completion:)\/title","value":"addUserToBlackListWithUserId:completion:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addUserToBlackListWithUserId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1addUserToBlackList(userId:completion:)\/fragments"},{"value":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1deviceIdsOnOtherPlatformOfCurrentUser(completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deviceIdsOnOtherPlatformOfCurrentUserWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1deviceIdsOnOtherPlatformOfCurrentUser(completion:)\/fragments"},{"value":"ContactServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/fragments","value":[{"text":"ContactServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1unregisterEmergencyListener(listener:)\/title","op":"replace","value":"unregisterEmergencyListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1unregisterEmergencyListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1registerEmergencyListener(listener:)\/title","value":"registerEmergencyListenerWithListener:"},{"value":[{"text":"- ","kind":"text"},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1registerEmergencyListener(listener:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1declineFriendRequest(from:completion:)\/title","value":"declineFriendRequestFrom:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1declineFriendRequest(from:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"declineFriendRequestFrom:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1removeUserFromBlackList(userId:completion:)\/title","op":"replace","value":"removeUserFromBlackListWithUserId:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeUserFromBlackListWithUserId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1removeUserFromBlackList(userId:completion:)\/fragments"},{"value":"setRemarkWithUserId:remark:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1setRemark(userId:remark:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1setRemark(userId:remark:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setRemarkWithUserId:remark:completion:","kind":"identifier"}]},{"value":"agreeFriendRequestFrom:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1agreeFriendRequest(from:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceProtocol~1agreeFriendRequest(from:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"agreeFriendRequestFrom:completion:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}