{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationServiceImplement","kind":"identifier"}]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/init()"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/eventsNotifiers"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/handleResult(error:type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/mapper(objects:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/notifyUnreadCount(count:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/onConversationReadCallback(conversation:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/EMChatManagerDelegate-Implementations"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceImplement"}],"navigatorTitle":[{"text":"ConversationServiceImplement","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"class","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationServiceImplement","roleHeading":"Class","title":"ConversationServiceImplement"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMChatManagerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/notifyUnreadCount(count:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"notifyUnreadCount","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/notifyUnreadCount(count:)","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/notifyunreadcount(count:)","title":"notifyUnreadCount(count:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/init()":{"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/init()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/init()","title":"init()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","title":"ConversationServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/EMChatManagerDelegate-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/EMChatManagerDelegate-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/emchatmanagerdelegate-implementations","title":"EMChatManagerDelegate Implementations"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/eventsNotifiers":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/eventsNotifiers","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventsNotifiers"},{"kind":"text","text":": "},{"text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener","text":"ConversationEmergencyListener","kind":"typeIdentifier"},{"kind":"text","text":">"}],"kind":"symbol","title":"eventsNotifiers","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/eventsnotifiers"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/handleResult(error:type:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handleResult"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationEmergencyType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ConversationEmergencyType"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/handleResult(error:type:)","kind":"symbol","abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/handleresult(error:type:)","title":"handleResult(error:type:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/mapper(objects:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mapper"},{"kind":"text","text":"("},{"kind":"externalParam","text":"objects"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","text":"ChatConversation"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/mapper(objects:)","role":"symbol","title":"mapper(objects:)","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/mapper(objects:)","abstract":[],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationService"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","url":"\/documentation\/easechatuikit\/conversationservice","navigatorTitle":[{"text":"ConversationService","kind":"identifier"}],"abstract":[],"type":"topic","title":"ConversationService"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/onConversationReadCallback(conversation:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onConversationReadCallback"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","text":"ChatConversation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/onConversationReadCallback(conversation:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onConversationReadCallbackWithConversation:"}],"role":"symbol","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/onconversationreadcallback(conversation:)","title":"onConversationReadCallback(conversation:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)EMChatManagerDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMChatManagerDelegate","title":"EMChatManagerDelegate"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","title":"ConversationService Implementations","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ConversationServiceImplement","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ConversationServiceImplement","kind":"identifier"}]},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/init()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/onConversationReadCallback(conversation:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/EMChatManagerDelegate-Implementations"],"generated":true}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMChatManagerDelegate"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationServiceImplement","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"init","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"op":"replace","value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/title","value":"ConversationService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/fragments","value":[{"kind":"identifier","text":"ConversationService"}]},{"value":"onConversationReadCallbackWithConversation:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1onConversationReadCallback(conversation:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1onConversationReadCallback(conversation:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onConversationReadCallbackWithConversation:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}