{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"ConversationListController"},{"text":" class implements a view controller that displays a list of conversations.","type":"text"},{"type":"text","text":" "},{"text":"It inherits from ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationListController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"ConversationListController","role":"symbol","roleHeading":"Class","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationListController","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListController"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationListController"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlistcontroller"]},{"paths":["\/documentation\/easechatuikit\/conversationlistcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/init()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/init(coder:)"],"generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/conversationList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/navigation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/search","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewModel"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/addContact()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/chatToContact(profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/create(profiles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createChat(profile:type:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createGroup()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createList()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createNavigationBar()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createSearchBar()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/pop()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/rightActions(indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/searchAction()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/selectContact()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/toChat(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/updateAvatarURL(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewDidLoad()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewWillAppear(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewWillDisappear(_:)"],"title":"Instance Methods","generated":true},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/ThemeSwitchProtocol-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController":{"url":"\/documentation\/easechatuikit\/conversationlistcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","abstract":[{"type":"text","text":"The "},{"code":"ConversationListController","type":"codeVoice"},{"text":" class implements a view controller that displays a list of conversations.","type":"text"},{"type":"text","text":" "},{"text":"It inherits from ","type":"text"},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","title":"ConversationListController","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/viewDidLoad()":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/viewdidload()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewDidLoad()","title":"viewDidLoad()"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/navigation":{"abstract":[],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/navigation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/navigation","title":"navigation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"navigation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatNavigationBar","kind":"typeIdentifier","text":"ChatNavigationBar"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/navigationClick(type:indexPath:)":{"title":"navigationClick(type:indexPath:)","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Handles the navigation bar click event.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/navigationClick(type:indexPath:)","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/navigationclick(type:indexpath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?)"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/search":{"abstract":[],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/search","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/search","title":"search","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"search","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate","title":"UIKit.UIViewControllerTransitioningDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/viewModel":{"title":"viewModel","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewModel","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/viewmodel","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewModel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationViewModel","kind":"typeIdentifier","text":"ConversationViewModel"},{"text":"?","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/createGroup()":{"abstract":[],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/creategroup()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createGroup()","navigatorTitle":[{"text":"createGroup","kind":"identifier"}],"title":"createGroup()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createGroup","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/createSearchBar()":{"abstract":[],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/createsearchbar()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createSearchBar()","navigatorTitle":[{"text":"createSearchBar","kind":"identifier"}],"title":"createSearchBar()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createSearchBar","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/searchAction()":{"title":"searchAction()","navigatorTitle":[{"text":"searchAction","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Performs a search action in the conversation list."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/searchAction()","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/searchaction()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"searchAction","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/viewWillAppear(_:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/viewwillappear(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewWillAppear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"title":"viewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/addContact()":{"title":"addContact()","navigatorTitle":[{"text":"addContact","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Adds a contact to the conversation list.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/addContact()","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/addcontact()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addContact","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/updateAvatarURL(_:)":{"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/updateavatarurl(_:)","abstract":[{"type":"text","text":"Update navigation avatar url."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/updateAvatarURL(_:)","navigatorTitle":[{"kind":"identifier","text":"updateWithAvatarURL:"}],"title":"updateAvatarURL(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"updateAvatarURL","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/createList()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createList()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createList"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/createlist()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createList","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationList","text":"ConversationList"}],"title":"createList()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/selectContact()":{"title":"selectContact()","navigatorTitle":[{"text":"selectContact","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Selects a contact from the contacts list.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/selectContact()","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/selectcontact()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectContact","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/chatToContact(profile:)":{"abstract":[{"type":"text","text":"Opens a chat with the specified contact profile."}],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/chattocontact(profile:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/chatToContact(profile:)","navigatorTitle":[{"kind":"identifier","text":"chatToContactWithProfile:"}],"title":"chatToContact(profile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatToContact","kind":"identifier"},{"kind":"text","text":"("},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIViewController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/toChat(indexPath:info:)":{"title":"toChat(indexPath:info:)","navigatorTitle":[{"text":"toChatWithIndexPath:info:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Opens the chat view controller for the selected conversation."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/toChat(indexPath:info:)","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/tochat(indexpath:info:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"toChat","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/createNavigationBar()":{"abstract":[],"url":"\/documentation\/easechatuikit\/conversationlistcontroller\/createnavigationbar()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createNavigationBar()","navigatorTitle":[{"text":"createNavigationBar","kind":"identifier"}],"title":"createNavigationBar()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createNavigationBar","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatNavigationBar","text":"ChatNavigationBar"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/init(coder:)":{"title":"init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/init(coder:)","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"role":"symbol","url":"\/documentation\/easechatuikit\/themeswitchprotocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","title":"ThemeSwitchProtocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","title":"Swift.Copyable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/ThemeSwitchProtocol-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/themeswitchprotocol-implementations","type":"topic","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/create(profiles:)":{"title":"create(profiles:)","navigatorTitle":[{"text":"createWithProfiles:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Creates a group conversation with the given profiles."}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/create(profiles:)","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/create(profiles:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profiles"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/rightActions(indexPath:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/rightActions(indexPath:)","title":"rightActions(indexPath:)","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/rightactions(indexpath:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"rightActionsWithIndexPath:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightActions"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":")","kind":"text"}],"abstract":[{"text":"Handles the right actions for a given indexPath in the conversation list.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/createChat(profile:type:info:)":{"title":"createChat(profile:type:info:)","navigatorTitle":[{"kind":"identifier","text":"createChatWithProfile:type:info:"}],"kind":"symbol","abstract":[{"text":"Creates a chat with the given profile and information.","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createChat(profile:type:info:)","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/createchat(profile:type:info:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createChat","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/init()":{"title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/init()","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/conversationList":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/conversationList","title":"conversationList","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/conversationlist","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationList","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationList","text":"ConversationList"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/viewWillDisappear(_:)":{"title":"viewWillDisappear(_:)","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewWillDisappear(_:)","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/viewwilldisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController/pop()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/pop()","title":"pop()","url":"\/documentation\/easechatuikit\/conversationlistcontroller\/pop()","type":"topic","role":"symbol","navigatorTitle":[{"text":"pop","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pop"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Pops the current view controller from the navigation stack if it exists,"},{"type":"text","text":" "},{"text":"otherwise dismisses the view controller.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"ConversationListController","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"ConversationListController","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ConversationListController","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/addContact()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/chatToContact(profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/create(profiles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createChat(profile:type:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createGroup()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createList()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createNavigationBar()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/createSearchBar()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/init()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/pop()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/rightActions(indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/searchAction()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/selectContact()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/toChat(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/updateAvatarURL(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewDidLoad()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewWillAppear(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/viewWillDisappear(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"},{"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController\/ThemeSwitchProtocol-Implementations"],"title":"Default Implementations","generated":true}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationListController","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"ConversationListController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/fragments","value":[{"text":"ConversationListController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationListController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1viewDidLoad()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1navigationClick(type:indexPath:)\/title","value":"navigationClickWithType:indexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1navigationClick(type:indexPath:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}]},{"op":"replace","value":"createGroup","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createGroup()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createGroup()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createGroup","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"createSearchBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createSearchBar()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createSearchBar()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createSearchBar","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"searchAction","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1searchAction()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"searchAction","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1searchAction()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1viewWillAppear(_:)\/fragments","op":"replace"},{"value":"addContact","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1addContact()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addContact"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1addContact()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1updateAvatarURL(_:)\/title","value":"updateWithAvatarURL:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"updateWithAvatarURL:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1updateAvatarURL(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createList()\/title","value":"createList","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createList()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createList","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1selectContact()\/title","value":"selectContact"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1selectContact()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"selectContact"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1chatToContact(profile:)\/title","value":"chatToContactWithProfile:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1chatToContact(profile:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"chatToContactWithProfile:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1toChat(indexPath:info:)\/title","value":"toChatWithIndexPath:info:"},{"value":[{"kind":"text","text":"- "},{"text":"toChatWithIndexPath:info:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1toChat(indexPath:info:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createNavigationBar()\/title","op":"replace","value":"createNavigationBar"},{"value":[{"text":"- ","kind":"text"},{"text":"createNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createNavigationBar()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title","op":"replace","value":"ThemeSwitchProtocol"},{"op":"replace","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments"},{"op":"replace","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1create(profiles:)\/title","value":"createWithProfiles:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1create(profiles:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createWithProfiles:"}]},{"op":"replace","value":"rightActionsWithIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1rightActions(indexPath:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1rightActions(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rightActionsWithIndexPath:"}]},{"value":"createChatWithProfile:type:info:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createChat(profile:type:info:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"createChatWithProfile:type:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1createChat(profile:type:info:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"value":"viewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1viewWillDisappear(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1viewWillDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillDisappear:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1pop()\/title","value":"pop"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController~1pop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pop"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}