{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationemergencylistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationemergencylistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationsUnreadCountUpdate(unreadCount:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onResult(error:type:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyListener"}],"title":"ConversationEmergencyListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyListener"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener/onConversationLastMessageUpdate(message:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationLastMessageUpdateWithMessage:info:"}],"role":"symbol","title":"onConversationLastMessageUpdate(message:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationLastMessageUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The last message of conversation changes."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationLastMessageUpdate(message:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencylistener\/onconversationlastmessageupdate(message:info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener":{"role":"symbol","title":"ConversationEmergencyListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"url":"\/documentation\/easechatuikit\/conversationemergencylistener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener/onConversationsUnreadCountUpdate(unreadCount:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationsUnreadCountUpdateWithUnreadCount:"}],"role":"symbol","title":"onConversationsUnreadCountUpdate(unreadCount:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationsUnreadCountUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"unreadCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You’ll receive the result on some conversation last message update."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationsUnreadCountUpdate(unreadCount:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencylistener\/onconversationsunreadcountupdate(unreadcount:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener/onResult(error:type:)":{"navigatorTitle":[{"kind":"identifier","text":"onResultWithError:type:"}],"role":"symbol","title":"onResult(error:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResult"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEmergencyType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ConversationEmergencyType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"You’ll receive the result on conversation service request successful or failure."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onResult(error:type:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencylistener\/onresult(error:type:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ConversationEmergencyListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationEmergencyListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationsUnreadCountUpdate(unreadCount:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onResult(error:type:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyListener"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onConversationLastMessageUpdate(message:info:)\/title","value":"onConversationLastMessageUpdateWithMessage:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onConversationLastMessageUpdate(message:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationLastMessageUpdateWithMessage:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/title","value":"ConversationEmergencyListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onConversationsUnreadCountUpdate(unreadCount:)\/title","value":"onConversationsUnreadCountUpdateWithUnreadCount:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onConversationsUnreadCountUpdate(unreadCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationsUnreadCountUpdateWithUnreadCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onResult(error:type:)\/title","value":"onResultWithError:type:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onResult(error:type:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onResultWithError:type:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}