{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"sections":[],"metadata":{"symbolKind":"class","title":"ConversationAppearance","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationAppearance","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationAppearance","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"ConversationAppearance"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/dateFormatOtherDay","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/dateFormatToday","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/groupPlaceHolder","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/listMoreActions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/moreActions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/rowHeight","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/singlePlaceHolder","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/swipeLeftActions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/swipeRightActions"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationAppearance","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/conversationappearance"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationappearance"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIContextualActionType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype","title":"UIContextualActionType","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIContextualActionType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/swipeLeftActions":{"title":"swipeLeftActions","url":"\/documentation\/easechatuikit\/conversationappearance\/swipeleftactions","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"swipeLeftActions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/swipeLeftActions","role":"symbol","abstract":[{"text":"Menu items that appear after swiping left in a conversation.You can choose to have just some of the features or all of them.","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","isActive":true,"type":"reference"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/groupPlaceHolder":{"url":"\/documentation\/easechatuikit\/conversationappearance\/groupplaceholder","kind":"symbol","title":"groupPlaceHolder","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupPlaceHolder"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/groupPlaceHolder","role":"symbol","abstract":[{"text":"Group chat default place holder of avatar.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"groupPlaceHolder"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","navigatorTitle":[{"text":"ConversationListController","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"code":"ConversationListController","type":"codeVoice"},{"text":" class implements a view controller that displays a list of conversations.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It inherits from "},{"code":"UIViewController","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/conversationlistcontroller","title":"ConversationListController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/swipeRightActions":{"title":"swipeRightActions","url":"\/documentation\/easechatuikit\/conversationappearance\/swiperightactions","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipeRightActions","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/swipeRightActions","role":"symbol","abstract":[{"type":"text","text":"Menu items that appear after swiping right in a conversation.You can choose to have just some of the features or all of them."},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","isActive":true,"type":"reference"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/moreActions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moreActions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"text":"]","kind":"text"}],"url":"\/documentation\/easechatuikit\/conversationappearance\/moreactions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/moreActions","kind":"symbol","title":"moreActions","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"moreActions"}],"abstract":[{"text":"ActionSheet menu configuration items after clicking more buttons in a single session side sliding menu.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"text":" ","type":"text"},{"type":"codeVoice","code":"let translate = ActionSheetItem(title: \"translate\", type: .normal,tag: \"Translate\")"},{"type":"text","text":" "},{"code":"translate.action = { }","type":"codeVoice"},{"type":"text","text":" "},{"type":"codeVoice","code":"Appearance.conversation.moreActions.append(translate)"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/dateFormatToday":{"title":"dateFormatToday","type":"topic","abstract":[{"text":"Setting this property changes the date format displayed on conversation last message updated.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateFormatToday"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/easechatuikit\/conversationappearance\/dateformattoday","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/dateFormatToday","navigatorTitle":[{"kind":"identifier","text":"dateFormatToday"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/init":{"url":"\/documentation\/easechatuikit\/conversationappearance\/init","kind":"symbol","title":"init","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/init","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/rowHeight":{"url":"\/documentation\/easechatuikit\/conversationappearance\/rowheight","kind":"symbol","title":"rowHeight","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rowHeight"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/rowHeight","role":"symbol","abstract":[{"text":"Conversation row height.","type":"text"}],"navigatorTitle":[{"text":"rowHeight","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/dateFormatOtherDay":{"url":"\/documentation\/easechatuikit\/conversationappearance\/dateformatotherday","kind":"symbol","title":"dateFormatOtherDay","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateFormatOtherDay"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/dateFormatOtherDay","role":"symbol","abstract":[{"text":"Setting this property changes the date format displayed on conversation last message updated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dateFormatOtherDay"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance":{"title":"ConversationAppearance","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationAppearance","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationappearance","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance","navigatorTitle":[{"kind":"identifier","text":"ConversationAppearance"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/listMoreActions":{"title":"listMoreActions","url":"\/documentation\/easechatuikit\/conversationappearance\/listmoreactions","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"listMoreActions","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/listMoreActions","role":"symbol","abstract":[{"type":"text","text":"Shown menus on "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController"},{"text":" right item clicked.","type":"text"}],"navigatorTitle":[{"text":"listMoreActions","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/singlePlaceHolder":{"title":"singlePlaceHolder","url":"\/documentation\/easechatuikit\/conversationappearance\/singleplaceholder","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"singlePlaceHolder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/singlePlaceHolder","role":"symbol","abstract":[{"type":"text","text":"Single chat default place holder of avatar."}],"navigatorTitle":[{"text":"singlePlaceHolder","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"ConversationAppearance","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationAppearance"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationAppearance"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/dateFormatOtherDay","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/dateFormatToday","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/groupPlaceHolder","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/listMoreActions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/moreActions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/rowHeight","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/singlePlaceHolder"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/init"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"ConversationAppearance","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"UIContextualActionType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/fragments","op":"replace","value":[{"text":"UIContextualActionType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1groupPlaceHolder\/title","value":"groupPlaceHolder","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1groupPlaceHolder\/fragments","op":"replace","value":[{"text":"groupPlaceHolder","kind":"identifier"}]},{"value":"ConversationListController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationListController"}]},{"value":"moreActions","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1moreActions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"moreActions"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1moreActions\/fragments","op":"replace"},{"value":"dateFormatToday","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1dateFormatToday\/title","op":"replace"},{"op":"replace","value":[{"text":"dateFormatToday","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1dateFormatToday\/fragments"},{"value":"rowHeight","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1rowHeight\/title"},{"op":"replace","value":[{"kind":"identifier","text":"rowHeight"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1rowHeight\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1dateFormatOtherDay\/title","op":"replace","value":"dateFormatOtherDay"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1dateFormatOtherDay\/fragments","op":"replace","value":[{"text":"dateFormatOtherDay","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance\/title","value":"ConversationAppearance","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance\/fragments","value":[{"text":"ConversationAppearance","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1listMoreActions\/title","op":"replace","value":"listMoreActions"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1listMoreActions\/fragments","op":"replace","value":[{"text":"listMoreActions","kind":"identifier"}]},{"value":"singlePlaceHolder","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1singlePlaceHolder\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1singlePlaceHolder\/fragments","value":[{"text":"singlePlaceHolder","kind":"identifier"}],"op":"replace"}]}]}