{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/init()"],"anchor":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/chatId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/driver","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/firstLoadConversation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/multiService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/muteMap","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/service","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/toChat"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/bind(driver:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/cacheGroup(profiles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/cacheUser(profiles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/calculateUnreadCount(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationEventDidChanged(event:conversationId:conversationType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationMessageAlreadyReadOnOtherDevice(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/delete(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/destroyed()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/loadExistLocalDataIfEmptyFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/loadIfNotExistCreate(profile:type:text:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mapper(objects:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/moreAction(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mute(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/pin(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/playNewMessageSound()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/read(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/registerEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/renderDriver(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/requestDisplayProfiles(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unmute(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unpin(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unregisterEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/updateUnreadCount()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/welcomeMessage(conversationId:text:)"],"anchor":"Instance-Methods","generated":true},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationServiceListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/MultiDeviceListener-Implementations"]}],"sections":[],"abstract":[{"type":"text","text":"Bind service and driver"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"],"title":"Conforms To","kind":"relationships"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewModel"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"roleHeading":"Class","modules":[{"name":"EaseChatUIKit"}],"title":"ConversationViewModel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationViewModel","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationViewModel","symbolKind":"class"},"variants":[{"paths":["\/documentation\/easechatuikit\/conversationviewmodel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationviewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/updateUnreadCount()":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/updateUnreadCount()","kind":"symbol","title":"updateUnreadCount()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUnreadCount"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"updateUnreadCount","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/updateunreadcount()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/delete(info:)":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"deleteWithInfo:","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/delete(info:)","role":"symbol","title":"delete(info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/delete(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/driver":{"type":"topic","title":"driver","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"driver"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver","text":"IConversationListDriver","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/driver","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/driver"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/unmute(info:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unmute(info:)","kind":"symbol","title":"unmute(info:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unmute"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"unmuteWithInfo:","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/unmute(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/ConversationServiceListener-Implementations":{"type":"topic","title":"ConversationServiceListener Implementations","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationservicelistener-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationServiceListener-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/firstLoadConversation":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/firstLoadConversation","kind":"symbol","title":"firstLoadConversation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"firstLoadConversation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/firstloadconversation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"kind":"symbol","title":"ConversationViewModel","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationViewModel","kind":"identifier"}],"abstract":[{"text":"Bind service and driver","type":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel","navigatorTitle":[{"kind":"identifier","text":"ConversationViewModel"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener":{"role":"symbol","type":"topic","title":"ConversationServiceListener","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservicelistener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationServiceListener","kind":"identifier"}],"navigatorTitle":[{"text":"ConversationServiceListener","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/pin(info:)":{"type":"topic","title":"pin(info:)","navigatorTitle":[{"kind":"identifier","text":"pinWithInfo:"}],"abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pin","kind":"identifier"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/pin(info:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/pin(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/service":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/service","kind":"symbol","title":"service","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"service"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationServiceImplement","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationServiceImplement"},{"text":"?","kind":"text"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/service"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/mapper(objects:)":{"type":"topic","title":"mapper(objects:)","navigatorTitle":[{"kind":"identifier","text":"mapperWithObjects:"}],"abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mapper","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"objects"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","text":"ChatConversation","kind":"typeIdentifier"},{"text":"]) -> [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier","text":"ConversationInfo"},{"kind":"text","text":"]"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/mapper(objects:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mapper(objects:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/renderDriver(infos:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/renderDriver(infos:)","kind":"symbol","title":"renderDriver(infos:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"renderDriver","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infos","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"renderDriverWithInfos:"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/renderdriver(infos:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/conversationDidSelected(indexPath:info:)":{"type":"topic","title":"conversationDidSelected(indexPath:info:)","navigatorTitle":[{"text":"conversationDidSelectedWithIndexPath:info:","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"conversationDidSelected"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationdidselected(indexpath:info:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationDidSelected(indexPath:info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/destroyed()":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/destroyed()","kind":"symbol","title":"destroyed()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"destroyed","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"destroyed"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/destroyed()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/multidevicelistener","kind":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"abstract":[],"title":"MultiDeviceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","title":"Swift.Copyable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/loadIfNotExistCreate(profile:type:text:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/loadIfNotExistCreate(profile:type:text:)","kind":"symbol","title":"loadIfNotExistCreate(profile:type:text:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadIfNotExistCreate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ChatConversationType","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier","text":"ConversationInfo"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"loadIfNotExistCreateWithProfile:type:text:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Load the session in the local database and create one if it does not exist"}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/loadifnotexistcreate(profile:type:text:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/multiService":{"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/multiservice","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/multiService","kind":"symbol","abstract":[],"title":"multiService","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiService"},{"kind":"text","text":": "},{"text":"MultiDeviceService","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceService"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/unregisterEventsListener(listener:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterEventsListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"unregisterEventsListener(listener:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unregisterEventsListener(listener:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"When you don’t want to listen to the registered events above, you can use this method to clear the registration."}],"navigatorTitle":[{"kind":"identifier","text":"unregisterEventsListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/unregistereventslistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/calculateUnreadCount(info:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"calculateUnreadCount","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/calculateUnreadCount(info:)","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel\/calculateunreadcount(info:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"calculateUnreadCountWithInfo:"}],"title":"calculateUnreadCount(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/bind(driver:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bind","kind":"identifier"},{"text":"(","kind":"text"},{"text":"driver","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver","kind":"typeIdentifier","text":"IConversationListDriver"},{"kind":"text","text":")"}],"title":"bind(driver:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/bind(driver:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Bind UI driver and service"}],"navigatorTitle":[{"text":"bindWithDriver:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/bind(driver:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/moreAction(info:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreAction"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/moreAction(info:)","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel\/moreaction(info:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"moreActionWithInfo:","kind":"identifier"}],"title":"moreAction(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/read(info:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier","text":"ConversationInfo"},{"kind":"text","text":")"}],"title":"read(info:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/read(info:)","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"readWithInfo:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/read(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/unpin(info:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpin"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unpin(info:)","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel\/unpin(info:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"unpinWithInfo:","kind":"identifier"}],"title":"unpin(info:)"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/MultiDeviceListener-Implementations":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/MultiDeviceListener-Implementations","kind":"article","url":"\/documentation\/easechatuikit\/conversationviewmodel\/multidevicelistener-implementations","type":"topic","role":"collectionGroup","title":"MultiDeviceListener Implementations"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/playNewMessageSound()":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/playnewmessagesound()","navigatorTitle":[{"kind":"identifier","text":"playNewMessageSound"}],"title":"playNewMessageSound()","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/playNewMessageSound()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"playNewMessageSound"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/welcomeMessage(conversationId:text:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"welcomeMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/welcomemessage(conversationid:text:)","role":"symbol","title":"welcomeMessage(conversationId:text:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/welcomeMessage(conversationId:text:)","navigatorTitle":[{"text":"welcomeMessageWithConversationId:text:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/chatId":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/chatId","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationviewmodel\/chatid","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"chatId"}],"title":"chatId"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/registerEventsListener(listener:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener","kind":"typeIdentifier","text":"ConversationEmergencyListener"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Register to monitor when certain emergencies occur","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/registerEventsListener(listener:)","role":"symbol","title":"registerEventsListener(listener:)","kind":"symbol","navigatorTitle":[{"text":"registerEventsListenerWithListener:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/registereventslistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/conversationEventDidChanged(event:conversationId:conversationType:)":{"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationeventdidchanged(event:conversationid:conversationtype:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationEventDidChanged(event:conversationId:conversationType:)","navigatorTitle":[{"text":"conversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}],"kind":"symbol","title":"conversationEventDidChanged(event:conversationId:conversationType:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","kind":"typeIdentifier","text":"MultiDeviceEvent"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"text":"ChatConversationType","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/loadExistLocalDataIfEmptyFetchServer()":{"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/loadexistlocaldataifemptyfetchserver()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/loadExistLocalDataIfEmptyFetchServer()","navigatorTitle":[{"kind":"identifier","text":"loadExistLocalDataIfEmptyFetchServer"}],"kind":"symbol","abstract":[{"type":"text","text":"Load all sessions that exist locally. If they do not exist, load them from the server."}],"title":"loadExistLocalDataIfEmptyFetchServer()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadExistLocalDataIfEmptyFetchServer"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/ConversationListActionEventsDelegate-Implementations":{"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationlistactioneventsdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations","kind":"article","abstract":[],"title":"ConversationListActionEventsDelegate Implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","title":"ConversationListActionEventsDelegate","abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate","navigatorTitle":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/toChat":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/toChat","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"toChat","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":", "},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"title":"toChat","abstract":[{"text":"When conversation clicked.","type":"text"}],"navigatorTitle":[{"text":"toChat","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/tochat","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/cacheUser(profiles:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/cacheUser(profiles:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cacheUser"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profiles"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"kind":"text","text":"])"}],"title":"cacheUser(profiles:)","abstract":[],"navigatorTitle":[{"text":"cacheUserWithProfiles:","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/cacheuser(profiles:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/muteMap":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/muteMap","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"muteMap","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"text":"Dictionary","preciseIdentifier":"s:SD","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":">]","kind":"text"}],"title":"muteMap","abstract":[{"type":"text","text":"Map to store session settings do not disturb."}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/mutemap","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/requestDisplayProfiles(ids:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/requestDisplayProfiles(ids:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestDisplayProfiles"},{"kind":"text","text":"("},{"text":"ids","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"requestDisplayProfiles(ids:)","abstract":[],"navigatorTitle":[{"text":"requestDisplayProfilesWithIds:","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationviewmodel\/requestdisplayprofiles(ids:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/conversationLastMessageUpdate(message:info:)":{"type":"topic","title":"conversationLastMessageUpdate(message:info:)","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"conversationLastMessageUpdateWithMessage:info:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationlastmessageupdate(message:info:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"conversationLastMessageUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationLastMessageUpdate(message:info:)"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/conversationMessageAlreadyReadOnOtherDevice(info:)":{"type":"topic","title":"conversationMessageAlreadyReadOnOtherDevice(info:)","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationmessagealreadyreadonotherdevice(info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"conversationMessageAlreadyReadOnOtherDevice","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationMessageAlreadyReadOnOtherDevice(info:)"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/mute(info:)":{"type":"topic","title":"mute(info:)","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"muteWithInfo:"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/mute(info:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mute(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/conversationLongPressed(indexPath:info:)":{"kind":"symbol","navigatorTitle":[{"text":"conversationLongPressedWithIndexPath:info:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"conversationLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":")","kind":"text"}],"title":"conversationLongPressed(indexPath:info:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationLongPressed(indexPath:info:)","url":"\/documentation\/easechatuikit\/conversationviewmodel\/conversationlongpressed(indexpath:info:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/init()":{"type":"topic","title":"init()","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/init()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel/cacheGroup(profiles:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheGroupWithProfiles:"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheGroup","kind":"identifier"},{"kind":"text","text":"("},{"text":"profiles","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"kind":"text","text":"])"}],"title":"cacheGroup(profiles:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/cacheGroup(profiles:)","url":"\/documentation\/easechatuikit\/conversationviewmodel\/cachegroup(profiles:)","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"ConversationViewModel","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"ConversationViewModel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ConversationViewModel","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/chatId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/toChat"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/bind(driver:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/cacheGroup(profiles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/cacheUser(profiles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/calculateUnreadCount(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationEventDidChanged(event:conversationId:conversationType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/conversationMessageAlreadyReadOnOtherDevice(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/delete(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/destroyed()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/init()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/loadExistLocalDataIfEmptyFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/loadIfNotExistCreate(profile:type:text:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mapper(objects:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/moreAction(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/mute(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/pin(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/playNewMessageSound()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/read(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/registerEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/renderDriver(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/requestDisplayProfiles(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unmute(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unpin(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/unregisterEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/updateUnreadCount()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/welcomeMessage(conversationId:text:)"],"generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationListActionEventsDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/ConversationServiceListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel\/MultiDeviceListener-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener"],"type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationViewModel","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1updateUnreadCount()\/title","value":"updateUnreadCount"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1updateUnreadCount()\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateUnreadCount","kind":"identifier"}]},{"value":"deleteWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1delete(info:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deleteWithInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1delete(info:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1unmute(info:)\/title","value":"unmuteWithInfo:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"unmuteWithInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1unmute(info:)\/fragments"},{"value":"ConversationViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/navigatorTitle","value":[{"text":"ConversationViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/title","value":"ConversationServiceListener"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/fragments","value":[{"text":"ConversationServiceListener","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationServiceListener"}]},{"value":"pinWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1pin(info:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1pin(info:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pinWithInfo:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1mapper(objects:)\/title","value":"mapperWithObjects:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1mapper(objects:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"mapperWithObjects:","kind":"identifier"}],"op":"replace"},{"value":"renderDriverWithInfos:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1renderDriver(infos:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1renderDriver(infos:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"renderDriverWithInfos:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationDidSelected(indexPath:info:)\/title","value":"conversationDidSelectedWithIndexPath:info:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationDidSelected(indexPath:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationDidSelectedWithIndexPath:info:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1destroyed()\/title","value":"destroyed","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"destroyed"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1destroyed()\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/title","value":"MultiDeviceListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/fragments","value":[{"text":"MultiDeviceListener","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MultiDeviceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/navigatorTitle"},{"value":"loadIfNotExistCreateWithProfile:type:text:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1loadIfNotExistCreate(profile:type:text:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1loadIfNotExistCreate(profile:type:text:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadIfNotExistCreateWithProfile:type:text:"}]},{"value":"unregisterEventsListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1unregisterEventsListener(listener:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1unregisterEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"unregisterEventsListenerWithListener:","kind":"identifier"}]},{"value":"calculateUnreadCountWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1calculateUnreadCount(info:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1calculateUnreadCount(info:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"calculateUnreadCountWithInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1bind(driver:)\/title","value":"bindWithDriver:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"bindWithDriver:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1bind(driver:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1moreAction(info:)\/title","value":"moreActionWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1moreAction(info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moreActionWithInfo:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1read(info:)\/title","value":"readWithInfo:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1read(info:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"readWithInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1unpin(info:)\/title","value":"unpinWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1unpin(info:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unpinWithInfo:"}]},{"value":"playNewMessageSound","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1playNewMessageSound()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"playNewMessageSound","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1playNewMessageSound()\/fragments"},{"op":"replace","value":"welcomeMessageWithConversationId:text:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1welcomeMessage(conversationId:text:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"welcomeMessageWithConversationId:text:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1welcomeMessage(conversationId:text:)\/fragments"},{"value":"chatId","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1chatId\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1chatId\/fragments","value":[{"text":"chatId","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1registerEventsListener(listener:)\/title","value":"registerEventsListenerWithListener:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerEventsListenerWithListener:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1registerEventsListener(listener:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationEventDidChanged(event:conversationId:conversationType:)\/title","value":"conversationEventDidChangedWithEvent:conversationId:conversationType:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationEventDidChanged(event:conversationId:conversationType:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"conversationEventDidChangedWithEvent:conversationId:conversationType:","kind":"identifier"}]},{"value":"loadExistLocalDataIfEmptyFetchServer","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1loadExistLocalDataIfEmptyFetchServer()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1loadExistLocalDataIfEmptyFetchServer()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadExistLocalDataIfEmptyFetchServer"}],"op":"replace"},{"value":"ConversationListActionEventsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments","op":"replace","value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]},{"value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/navigatorTitle","op":"replace"},{"value":"toChat","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1toChat\/title"},{"op":"replace","value":[{"text":"toChat","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1toChat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1cacheUser(profiles:)\/title","value":"cacheUserWithProfiles:"},{"value":[{"kind":"text","text":"- "},{"text":"cacheUserWithProfiles:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1cacheUser(profiles:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1requestDisplayProfiles(ids:)\/title","value":"requestDisplayProfilesWithIds:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1requestDisplayProfiles(ids:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestDisplayProfilesWithIds:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationLastMessageUpdate(message:info:)\/title","value":"conversationLastMessageUpdateWithMessage:info:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationLastMessageUpdate(message:info:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"conversationLastMessageUpdateWithMessage:info:","kind":"identifier"}],"op":"replace"},{"value":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationMessageAlreadyReadOnOtherDevice(info:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationMessageAlreadyReadOnOtherDevice(info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationMessageAlreadyReadOnOtherDeviceWithInfo:"}]},{"value":"muteWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1mute(info:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"muteWithInfo:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1mute(info:)\/fragments"},{"value":"conversationLongPressedWithIndexPath:info:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationLongPressed(indexPath:info:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1conversationLongPressed(indexPath:info:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"conversationLongPressedWithIndexPath:info:","kind":"identifier"}]},{"value":"init","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1init()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1init()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1cacheGroup(profiles:)\/title","value":"cacheGroupWithProfiles:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel~1cacheGroup(profiles:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheGroupWithProfiles:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}