{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"symbolKind":"protocol","modules":[{"name":"EaseChatUIKit"}],"title":"ConversationService","navigatorTitle":[{"kind":"identifier","text":"ConversationService"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationService","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationService","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement"],"kind":"relationships","type":"conformingTypes"}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/bindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/clearSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/deleteConversation(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchAllConversations(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchPinnedConversations(cursor:pageSize:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchSilentMode(conversationIds:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/loadExistConversations()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/loadIfNotExistCreate(conversationId:type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/markAllMessagesAsRead(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/pin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/setSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unbindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unpin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unregisterEmergencyListener(listener:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationservice"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationservice"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationService"},{"kind":"text","text":" : "},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationService"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/conversationservice","role":"symbol","title":"ConversationService","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","navigatorTitle":[{"kind":"identifier","text":"ConversationService"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/pin(conversationId:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/pin(conversationId:completion:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/pin(conversationid:completion:)","navigatorTitle":[{"kind":"identifier","text":"pinWithConversationId:completion:"}],"required":true,"abstract":[{"type":"text","text":"Pin a conversation to the top"}],"title":"pin(conversationId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pin"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/unbindConversationEventsListener(listener:)":{"role":"symbol","abstract":[{"type":"text","text":"Unbind channel changed listener"}],"navigatorTitle":[{"text":"unbindConversationEventsListenerWithListener:","kind":"identifier"}],"title":"unbindConversationEventsListener(listener:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unbindConversationEventsListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unbindConversationEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/unbindconversationeventslistener(listener:)","required":true,"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/unregisterEmergencyListener(listener:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unregisterEmergencyListener(listener:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/unregisteremergencylistener(listener:)","navigatorTitle":[{"text":"unregisterEmergencyListenerWithListener:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Unregister emergency listener"}],"title":"unregisterEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterEmergencyListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationEmergencyListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/deleteConversation(conversationId:completion:)":{"role":"symbol","abstract":[{"text":"Delete a conversation exist in db&server.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"deleteConversationWithConversationId:completion:"}],"title":"deleteConversation(conversationId:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/deleteConversation(conversationId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deleteConversation","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/deleteconversation(conversationid:completion:)","required":true,"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/clearSilentMode(conversationId:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/clearSilentMode(conversationId:completion:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/clearsilentmode(conversationid:completion:)","navigatorTitle":[{"kind":"identifier","text":"clearSilentModeWithConversationId:completion:"}],"required":true,"abstract":[{"type":"text","text":"Clear the quiesce status of a session"}],"title":"clearSilentMode(conversationId:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearSilentMode"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"text":"SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/fetchPinnedConversations(cursor:pageSize:completion:)":{"role":"symbol","abstract":[{"type":"text","text":"Fetch pinned conversations from server."}],"navigatorTitle":[{"kind":"identifier","text":"fetchPinnedConversationsWithCursor:pageSize:completion:"}],"title":"fetchPinnedConversations(cursor:pageSize:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchPinnedConversations(cursor:pageSize:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchPinnedConversations","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cursor","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"CursorResult","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit12CursorResulta"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/fetchpinnedconversations(cursor:pagesize:completion:)","required":true,"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/fetchSilentMode(conversationIds:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchSilentMode(conversationIds:completion:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/fetchsilentmode(conversationids:completion:)","navigatorTitle":[{"text":"fetchSilentModeWithConversationIds:completion:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Get the session where the server is set to silent state"}],"title":"fetchSilentMode(conversationIds:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSilentMode"},{"kind":"text","text":"("},{"text":"conversationIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Dictionary","preciseIdentifier":"s:SD","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"SilentModeResult","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"text":">?, ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/unpin(conversationId:completion:)":{"role":"symbol","abstract":[{"text":"Unpin a conversation.","type":"text"}],"navigatorTitle":[{"text":"unpinWithConversationId:completion:","kind":"identifier"}],"title":"unpin(conversationId:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unpin(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpin"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/unpin(conversationid:completion:)","required":true,"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/setSilentMode(conversationId:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/setSilentMode(conversationId:completion:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/setsilentmode(conversationid:completion:)","navigatorTitle":[{"text":"setSilentModeWithConversationId:completion:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Set a session to silent state"}],"title":"setSilentMode(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setSilentMode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"SilentModeResult","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/fetchAllConversations(completion:)":{"role":"symbol","abstract":[{"text":"Fetch conversations from server.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fetchAllConversationsWithCompletion:"}],"title":"fetchAllConversations(completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchAllConversations(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fetchAllConversations","kind":"identifier"},{"kind":"text","text":"("},{"text":"completion","kind":"externalParam"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"CursorResult","preciseIdentifier":"s:13EaseChatUIKit12CursorResulta"},{"kind":"text","text":"<"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":">?, ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")?)","kind":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/fetchallconversations(completion:)","required":true,"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/loadExistConversations()":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/loadExistConversations()","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/loadexistconversations()","navigatorTitle":[{"text":"loadExistConversations","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Get all conversations from database."}],"title":"loadExistConversations()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadExistConversations"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceImplement"}],"title":"ConversationServiceImplement","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/bindConversationEventsListener(listener:)":{"role":"symbol","type":"topic","title":"bindConversationEventsListener(listener:)","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/bindconversationeventslistener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bindConversationEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener","text":"ConversationServiceListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Bind channel changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/bindConversationEventsListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/registerEmergencyListener(listener:)":{"role":"symbol","abstract":[{"type":"text","text":"Register emergency listener"}],"navigatorTitle":[{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"title":"registerEmergencyListener(listener:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/registerEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/registeremergencylistener(listener:)","required":true,"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/markAllMessagesAsRead(conversationId:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/markAllMessagesAsRead(conversationId:)","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/markallmessagesasread(conversationid:)","navigatorTitle":[{"text":"markAllMessagesAsReadWithConversationId:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Mark all of the history messages as already read."}],"title":"markAllMessagesAsRead(conversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"markAllMessagesAsRead","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/loadIfNotExistCreate(conversationId:type:)":{"role":"symbol","abstract":[{"type":"text","text":"Load a session and create one if it does not exist"}],"navigatorTitle":[{"text":"loadIfNotExistCreateWithConversationId:type:","kind":"identifier"}],"title":"loadIfNotExistCreate(conversationId:type:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/loadIfNotExistCreate(conversationId:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadIfNotExistCreate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","text":"ChatConversationType","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","text":"ChatConversation"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/loadifnotexistcreate(conversationid:type:)","required":true,"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ConversationService"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"ConversationService","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationService"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/bindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/clearSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/deleteConversation(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchAllConversations(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchPinnedConversations(cursor:pageSize:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchSilentMode(conversationIds:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/loadExistConversations()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/loadIfNotExistCreate(conversationId:type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/markAllMessagesAsRead(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/pin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/setSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unbindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unpin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/unregisterEmergencyListener(listener:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"type":"conformingTypes","title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"ConversationService","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/title","op":"replace","value":"ConversationService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/fragments","value":[{"text":"ConversationService","kind":"identifier"}]},{"op":"replace","value":[{"text":"ConversationService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/navigatorTitle"},{"value":"pinWithConversationId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1pin(conversationId:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1pin(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pinWithConversationId:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1unbindConversationEventsListener(listener:)\/title","value":"unbindConversationEventsListenerWithListener:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindConversationEventsListenerWithListener:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1unbindConversationEventsListener(listener:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1unregisterEmergencyListener(listener:)\/title","value":"unregisterEmergencyListenerWithListener:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1unregisterEmergencyListener(listener:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1deleteConversation(conversationId:completion:)\/title","value":"deleteConversationWithConversationId:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"deleteConversationWithConversationId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1deleteConversation(conversationId:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1clearSilentMode(conversationId:completion:)\/title","op":"replace","value":"clearSilentModeWithConversationId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1clearSilentMode(conversationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearSilentModeWithConversationId:completion:","kind":"identifier"}],"op":"replace"},{"value":"fetchPinnedConversationsWithCursor:pageSize:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchPinnedConversations(cursor:pageSize:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchPinnedConversationsWithCursor:pageSize:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchPinnedConversations(cursor:pageSize:completion:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchSilentMode(conversationIds:completion:)\/title","value":"fetchSilentModeWithConversationIds:completion:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchSilentMode(conversationIds:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fetchSilentModeWithConversationIds:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1unpin(conversationId:completion:)\/title","op":"replace","value":"unpinWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1unpin(conversationId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unpinWithConversationId:completion:"}]},{"value":"setSilentModeWithConversationId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1setSilentMode(conversationId:completion:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"setSilentModeWithConversationId:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1setSilentMode(conversationId:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchAllConversations(completion:)\/title","value":"fetchAllConversationsWithCompletion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fetchAllConversationsWithCompletion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchAllConversations(completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1loadExistConversations()\/title","value":"loadExistConversations","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1loadExistConversations()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadExistConversations"}],"op":"replace"},{"value":"ConversationServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"text":"ConversationServiceImplement","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ConversationServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1bindConversationEventsListener(listener:)\/title","value":"bindConversationEventsListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1bindConversationEventsListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1registerEmergencyListener(listener:)\/title","value":"registerEmergencyListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1registerEmergencyListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}]},{"value":"markAllMessagesAsReadWithConversationId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1markAllMessagesAsRead(conversationId:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"markAllMessagesAsReadWithConversationId:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1markAllMessagesAsRead(conversationId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1loadIfNotExistCreate(conversationId:type:)\/title","value":"loadIfNotExistCreateWithConversationId:type:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1loadIfNotExistCreate(conversationId:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:type:"}],"op":"replace"}]}]}