{"metadata":{"role":"symbol","title":"ConversationEmergencyType","roleHeading":"Enumeration","symbolKind":"enum","externalID":"c:@M@EaseChatUIKit@E@ConversationEmergencyType","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyType"}],"navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationemergencytype"]},{"paths":["\/documentation\/easechatuikit\/conversationemergencytype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/clearSilent","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/delete","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/fetchPinned","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/fetchSilent","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/loadAllConversationFirstLoadUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/pin","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/read","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/setSilent","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/unpin"],"title":"Enumeration Cases"},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/init(rawValue:)"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ConversationEmergencyType","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/fetchSilent":{"url":"\/documentation\/easechatuikit\/conversationemergencytype\/fetchsilent","role":"symbol","title":"ConversationEmergencyType.fetchSilent","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/fetchSilent","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchSilent"}],"navigatorTitle":[{"text":"ConversationEmergencyTypeFetchSilent","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/init(rawValue:)":{"url":"\/documentation\/easechatuikit\/conversationemergencytype\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/init(rawValue:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/pin":{"navigatorTitle":[{"text":"ConversationEmergencyTypePin","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/pin","title":"ConversationEmergencyType.pin","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pin","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationemergencytype\/pin"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/setSilent":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setSilent"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/setSilent","navigatorTitle":[{"text":"ConversationEmergencyTypeSetSilent","kind":"identifier"}],"title":"ConversationEmergencyType.setSilent","url":"\/documentation\/easechatuikit\/conversationemergencytype\/setsilent","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/clearSilent":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/clearSilent","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeClearSilent"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearSilent","kind":"identifier"}],"title":"ConversationEmergencyType.clearSilent","url":"\/documentation\/easechatuikit\/conversationemergencytype\/clearsilent"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/delete":{"abstract":[],"url":"\/documentation\/easechatuikit\/conversationemergencytype\/delete","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/delete","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConversationEmergencyTypeDelete","kind":"identifier"}],"title":"ConversationEmergencyType.delete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"delete"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/loadAllConversationFirstLoadUIKit":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAllConversationFirstLoadUIKit","kind":"identifier"}],"title":"ConversationEmergencyType.loadAllConversationFirstLoadUIKit","navigatorTitle":[{"text":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/loadAllConversationFirstLoadUIKit","type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencytype\/loadallconversationfirstloaduikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/RawRepresentable-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article","url":"\/documentation\/easechatuikit\/conversationemergencytype\/rawrepresentable-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationemergencytype","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType","navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyType"}],"abstract":[],"title":"ConversationEmergencyType"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/unpin":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/unpin","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unpin","kind":"identifier"}],"kind":"symbol","title":"ConversationEmergencyType.unpin","url":"\/documentation\/easechatuikit\/conversationemergencytype\/unpin","navigatorTitle":[{"text":"ConversationEmergencyTypeUnpin","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/read":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/read","url":"\/documentation\/easechatuikit\/conversationemergencytype\/read","abstract":[],"kind":"symbol","role":"symbol","title":"ConversationEmergencyType.read","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeRead"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/fetchPinned":{"url":"\/documentation\/easechatuikit\/conversationemergencytype\/fetchpinned","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/fetchPinned","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchPinned","kind":"identifier"}],"type":"topic","abstract":[],"title":"ConversationEmergencyType.fetchPinned","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeFetchPinned"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/Equatable-Implementations":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/easechatuikit\/conversationemergencytype\/equatable-implementations","title":"Equatable Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"ConversationEmergencyType"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationEmergencyType"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"op":"replace"},{"value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/clearSilent","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/delete","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/fetchPinned","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/fetchSilent","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/loadAllConversationFirstLoadUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/pin","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/read","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/setSilent","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/unpin"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationEmergencyType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t","text":"uint8_t"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1fetchSilent\/title","value":"ConversationEmergencyTypeFetchSilent","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1fetchSilent\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyTypeFetchSilent"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1pin\/title","value":"ConversationEmergencyTypePin"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1pin\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationEmergencyTypePin"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1setSilent\/title","value":"ConversationEmergencyTypeSetSilent"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1setSilent\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyTypeSetSilent"}],"op":"replace"},{"value":"ConversationEmergencyTypeClearSilent","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1clearSilent\/title"},{"value":[{"text":"ConversationEmergencyTypeClearSilent","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1clearSilent\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1delete\/title","op":"replace","value":"ConversationEmergencyTypeDelete"},{"op":"replace","value":[{"text":"ConversationEmergencyTypeDelete","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1delete\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1loadAllConversationFirstLoadUIKit\/title","value":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1loadAllConversationFirstLoadUIKit\/fragments","value":[{"text":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/title","value":"ConversationEmergencyType"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/fragments","value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/navigatorTitle"},{"value":"ConversationEmergencyTypeUnpin","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1unpin\/title","op":"replace"},{"op":"replace","value":[{"text":"ConversationEmergencyTypeUnpin","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1unpin\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1read\/title","value":"ConversationEmergencyTypeRead","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ConversationEmergencyTypeRead"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1read\/fragments"},{"value":"ConversationEmergencyTypeFetchPinned","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1fetchPinned\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1fetchPinned\/fragments","value":[{"text":"ConversationEmergencyTypeFetchPinned","kind":"identifier"}],"op":"replace"}]}]}