{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationlistactioneventsdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"title":"ConversationListActionEventsDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListRefresh()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationListEndScrollNeededDisplayInfos(ids:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"}],"role":"symbol","title":"onConversationListEndScrollNeededDisplayInfos(ids:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistendscrollneededdisplayinfos(ids:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationDidSelected(indexPath:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationDidSelectedWithIndexPath:info:"}],"role":"symbol","title":"onConversationDidSelected(indexPath:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationDidSelected"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Callback on conversation was selected."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationDidSelected(indexPath:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationdidselected(indexpath:info:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationListOccurErrorWhenFetchServer()":{"navigatorTitle":[{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"}],"role":"symbol","title":"onConversationListOccurErrorWhenFetchServer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistoccurerrorwhenfetchserver()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationListRefresh()":{"navigatorTitle":[{"kind":"identifier","text":"onConversationListRefresh"}],"role":"symbol","title":"onConversationListRefresh()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationListRefresh"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Pull down to refresh"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListRefresh()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlistrefresh()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"role":"symbol","title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewModel"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationViewModel"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationLongPressed(indexPath:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}],"role":"symbol","title":"onConversationLongPressed(indexPath:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationLongPressed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Callback on conversation was long pressed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationlongpressed(indexpath:info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"role":"symbol","title":"ConversationListActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate/onConversationSwipe(type:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationSwipeWithType:info:"}],"role":"symbol","title":"onConversationSwipe(type:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationSwipe"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Callback on conversation was swiped."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate\/onconversationswipe(type:info:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ConversationListActionEventsDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationDidSelected(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationListRefresh()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationLongPressed(indexPath:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate\/onConversationSwipe(type:info:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListEndScrollNeededDisplayInfos(ids:)\/title","value":"onConversationListEndScrollNeededDisplayInfosWithIds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListEndScrollNeededDisplayInfos(ids:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationListEndScrollNeededDisplayInfosWithIds:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationDidSelected(indexPath:info:)\/title","value":"onConversationDidSelectedWithIndexPath:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationDidSelected(indexPath:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationDidSelectedWithIndexPath:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListOccurErrorWhenFetchServer()\/title","value":"onConversationListOccurErrorWhenFetchServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListOccurErrorWhenFetchServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationListOccurErrorWhenFetchServer"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListRefresh()\/title","value":"onConversationListRefresh"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationListRefresh()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationListRefresh"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","value":[{"kind":"identifier","text":"ConversationViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationLongPressed(indexPath:info:)\/title","value":"onConversationLongPressedWithIndexPath:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationLongPressed(indexPath:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationLongPressedWithIndexPath:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title","value":"ConversationListActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationSwipe(type:info:)\/title","value":"onConversationSwipeWithType:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate~1onConversationSwipe(type:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationSwipeWithType:info:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}