{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationservicelistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationservicelistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onChatConversationListDidChanged(list:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onConversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onConversationMessageAlreadyReadOnOtherDevice(info:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceListener"}],"title":"ConversationServiceListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceListener"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationViewModel":{"role":"symbol","title":"ConversationViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationViewModel"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationViewModel"}],"url":"\/documentation\/easechatuikit\/conversationviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener/onConversationLastMessageUpdate(message:info:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationLastMessageUpdateWithMessage:info:"}],"role":"symbol","title":"onConversationLastMessageUpdate(message:info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationLastMessageUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The last message of conversation changes."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onConversationLastMessageUpdate(message:info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationservicelistener\/onconversationlastmessageupdate(message:info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener":{"role":"symbol","title":"ConversationServiceListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationServiceListener"}],"url":"\/documentation\/easechatuikit\/conversationservicelistener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener/onChatConversationListDidChanged(list:)":{"navigatorTitle":[{"kind":"identifier","text":"onChatConversationListDidChangedWithList:"}],"role":"symbol","title":"onChatConversationListDidChanged(list:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatConversationListDidChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"list"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"When conversation list updated."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onChatConversationListDidChanged(list:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationservicelistener\/onchatconversationlistdidchanged(list:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener/onConversationMessageAlreadyReadOnOtherDevice(info:)":{"navigatorTitle":[{"kind":"identifier","text":"onConversationMessageAlreadyReadOnOtherDeviceWithInfo:"}],"role":"symbol","title":"onConversationMessageAlreadyReadOnOtherDevice(info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationMessageAlreadyReadOnOtherDevice"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The read status of the conversation message changes."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onConversationMessageAlreadyReadOnOtherDevice(info:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/conversationservicelistener\/onconversationmessagealreadyreadonotherdevice(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"ConversationServiceListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationServiceListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationServiceListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onChatConversationListDidChanged(list:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onConversationLastMessageUpdate(message:info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener\/onConversationMessageAlreadyReadOnOtherDevice(info:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationViewModel"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceListener"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/title","value":"ConversationViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationViewModel\/fragments","value":[{"kind":"identifier","text":"ConversationViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener~1onConversationLastMessageUpdate(message:info:)\/title","value":"onConversationLastMessageUpdateWithMessage:info:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener~1onConversationLastMessageUpdate(message:info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationLastMessageUpdateWithMessage:info:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/title","value":"ConversationServiceListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/fragments","value":[{"kind":"identifier","text":"ConversationServiceListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener~1onChatConversationListDidChanged(list:)\/title","value":"onChatConversationListDidChangedWithList:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener~1onChatConversationListDidChanged(list:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatConversationListDidChangedWithList:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener~1onConversationMessageAlreadyReadOnOtherDevice(info:)\/title","value":"onConversationMessageAlreadyReadOnOtherDeviceWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener~1onConversationMessageAlreadyReadOnOtherDevice(info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationMessageAlreadyReadOnOtherDeviceWithInfo:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}