{"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation\/afterAnimation(animationContext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation\/beforeAnimation(animationContext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation\/performAnimation(animationContext:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/crossdissolveanimation"]},{"paths":["\/documentation\/easechatuikit\/crossdissolveanimation"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)CrossDissolveAnimation","navigatorTitle":[{"kind":"identifier","text":"CrossDissolveAnimation"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CrossDissolveAnimation","kind":"identifier"}],"role":"symbol","title":"CrossDissolveAnimation"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CrossDissolveAnimation","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation":{"title":"PresentationAnimation","navigatorTitle":[{"text":"PresentationAnimation","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationAnimation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/presentationanimation","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIViewControllerAnimatedTransitioning":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning","type":"unresolvable","title":"UIKit.UIViewControllerAnimatedTransitioning"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossDissolveAnimation":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation","type":"topic","navigatorTitle":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/crossdissolveanimation","role":"symbol","title":"CrossDissolveAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CrossDissolveAnimation"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossDissolveAnimation/afterAnimation(animationContext:)":{"url":"\/documentation\/easechatuikit\/crossdissolveanimation\/afteranimation(animationcontext:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation\/afterAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"afterAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","text":"AnimationContext"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"type":"text","text":"动画完成后（做动画完成的清理工作，子类可覆写）"}],"kind":"symbol","title":"afterAnimation(animationContext:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossDissolveAnimation/beforeAnimation(animationContext:)":{"url":"\/documentation\/easechatuikit\/crossdissolveanimation\/beforeanimation(animationcontext:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation\/beforeAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beforeAnimation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"animationContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","text":"AnimationContext","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"kind":"symbol","title":"beforeAnimation(animationContext:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossDissolveAnimation/performAnimation(animationContext:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation\/performAnimation(animationContext:)","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/crossdissolveanimation\/performanimation(animationcontext:)","role":"symbol","title":"performAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"performAnimation","kind":"identifier"},{"kind":"text","text":"("},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","text":"AnimationContext"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"CrossDissolveAnimation","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"CrossDissolveAnimation","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":null,"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"CrossDissolveAnimation","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PresentationAnimation","kind":"typeIdentifier","text":"PresentationAnimation"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"PresentationAnimation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"PresentationAnimation"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/fragments"},{"value":[{"kind":"identifier","text":"PresentationAnimation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossDissolveAnimation\/title","value":"CrossDissolveAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossDissolveAnimation\/fragments","value":[{"text":"CrossDissolveAnimation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossDissolveAnimation\/navigatorTitle","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}]}]}]}