{"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomActivityIndicator","kind":"identifier"}],"title":"CustomActivityIndicator","navigatorTitle":[{"kind":"identifier","text":"CustomActivityIndicator"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)CustomActivityIndicator","symbolKind":"class","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CustomActivityIndicator","kind":"identifier"}]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","type":"conformsTo"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/customactivityindicator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/customactivityindicator"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomActivityIndicator","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomActivityIndicator\/init(coder:)"],"anchor":"Initializers"}],"references":{"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItem":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CustomActivityIndicator":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CustomActivityIndicator","kind":"identifier"}],"title":"CustomActivityIndicator","navigatorTitle":[{"text":"CustomActivityIndicator","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomActivityIndicator","url":"\/documentation\/easechatuikit\/customactivityindicator"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CustomActivityIndicator/init(coder:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":")","kind":"text"}],"title":"init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomActivityIndicator\/init(coder:)","url":"\/documentation\/easechatuikit\/customactivityindicator\/init(coder:)"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"CustomActivityIndicator","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"CustomActivityIndicator","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"CustomActivityIndicator","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomActivityIndicator\/init(coder:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CustomActivityIndicator"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"CustomActivityIndicator","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomActivityIndicator\/title"},{"value":[{"text":"CustomActivityIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomActivityIndicator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomActivityIndicator\/navigatorTitle","value":[{"text":"CustomActivityIndicator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomActivityIndicator~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomActivityIndicator~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace"}]}]}