{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Decoder_Interface_Decode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"in","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">!, ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"out","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"kind":"text","text":">!, "},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"bfi"},{"kind":"text","text":": "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@F@Decoder_Interface_Decode","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Function","role":"symbol","title":"Decoder_Interface_Decode(_:_:_:_:)","symbolKind":"func","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Decoder_Interface_Decode"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafePointer","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!, "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"Int16","preciseIdentifier":"s:s5Int16V","kind":"typeIdentifier"},{"kind":"text","text":">!, "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"Decoder_Interface_Decode","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/decoder_interface_decode(_:_:_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/decoder_interface_decode(_:_:_:_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Decoder_Interface_Decode(_:_:_:_:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Decoder_Interface_Decode(_:_:_:_:)":{"title":"Decoder_Interface_Decode(_:_:_:_:)","kind":"symbol","url":"\/documentation\/easechatuikit\/decoder_interface_decode(_:_:_:_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Decoder_Interface_Decode(_:_:_:_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Decoder_Interface_Decode"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"text":"!, ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"kind":"text","text":"<"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"kind":"text","text":">!, "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5Int16V","kind":"typeIdentifier","text":"Int16"},{"kind":"text","text":">!, "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"Decoder_Interface_Decode","kind":"identifier"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Function"},{"path":"\/metadata\/title","value":"Decoder_Interface_Decode","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Decoder_Interface_Decode","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"Decoder_Interface_Decode"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"state"},{"kind":"text","text":", "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unsigned char","preciseIdentifier":"c:c","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"in","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:S","text":"short","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"out","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"text":"bfi","kind":"internalParam"},{"kind":"text","text":");"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Decoder_Interface_Decode(_:_:_:_:)\/title","value":"Decoder_Interface_Decode","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Decoder_Interface_Decode(_:_:_:_:)\/fragments","value":[{"text":"Decoder_Interface_Decode","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}