{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/decoder_interface_init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/decoder_interface_init()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"Decoder_Interface_init","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"text":"!","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Decoder_Interface_init()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@F@Decoder_Interface_init","roleHeading":"Function","role":"symbol","title":"Decoder_Interface_init()","symbolKind":"func","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"Decoder_Interface_init"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"text":"!","kind":"text"}],"navigatorTitle":[{"text":"Decoder_Interface_init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Decoder_Interface_init()":{"kind":"symbol","title":"Decoder_Interface_init()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Decoder_Interface_init()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Decoder_Interface_init"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"Decoder_Interface_init"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/decoder_interface_init()","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"path":"\/metadata\/title","value":"Decoder_Interface_init","op":"replace"},{"path":"\/metadata\/symbolKind","value":"func","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Decoder_Interface_init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" * "},{"text":"Decoder_Interface_init","kind":"identifier"},{"text":"();","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Decoder_Interface_init()\/title","value":"Decoder_Interface_init","op":"replace"},{"value":[{"text":"Decoder_Interface_init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Decoder_Interface_init()\/fragments"}]}]}