{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Decoder_Interface_exit(_:)"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@F@Decoder_Interface_exit","title":"Decoder_Interface_exit(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"Decoder_Interface_exit","kind":"identifier"},{"kind":"text","text":"("},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!)"}],"navigatorTitle":[{"kind":"identifier","text":"Decoder_Interface_exit"}],"symbolKind":"func","roleHeading":"Function"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"Decoder_Interface_exit","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!)"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/decoder_interface_exit(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/decoder_interface_exit(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Decoder_Interface_exit(_:)":{"abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/decoder_interface_exit(_:)","title":"Decoder_Interface_exit(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"Decoder_Interface_exit","kind":"identifier"},{"kind":"text","text":"("},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!)"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Decoder_Interface_exit(_:)","navigatorTitle":[{"text":"Decoder_Interface_exit","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Function"},{"value":"Decoder_Interface_exit","op":"replace","path":"\/metadata\/title"},{"value":"func","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"Decoder_Interface_exit","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" ","kind":"text"},{"text":"Decoder_Interface_exit","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"state"},{"text":");","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"Decoder_Interface_exit","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Decoder_Interface_exit(_:)\/title"},{"value":[{"text":"Decoder_Interface_exit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Decoder_Interface_exit(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}