{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetailInfo"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/detailinfo"]},{"paths":["\/documentation\/easechatuikit\/detailinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/detail","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/switchValue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/title","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/withSwitch"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/setValue(_:forUndefinedKey:)"],"title":"Instance Methods"}],"metadata":{"roleHeading":"Class","symbolKind":"class","title":"DetailInfo","navigatorTitle":[{"text":"DetailInfo","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetailInfo","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)DetailInfo"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo/withSwitch":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/withSwitch","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withSwitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"withSwitch"}],"role":"symbol","title":"withSwitch","url":"\/documentation\/easechatuikit\/detailinfo\/withswitch","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetailInfo"}],"kind":"symbol","navigatorTitle":[{"text":"DetailInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/detailinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo","type":"topic","title":"DetailInfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo/setValue(_:forUndefinedKey:)":{"title":"setValue(_:forUndefinedKey:)","navigatorTitle":[{"text":"setValue:forUndefinedKey:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/setValue(_:forUndefinedKey:)","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/detailinfo\/setvalue(_:forundefinedkey:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setValue","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"forUndefinedKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo/detail":{"title":"detail","navigatorTitle":[{"text":"detail","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/detail","abstract":[],"url":"\/documentation\/easechatuikit\/detailinfo\/detail","kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"detail","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo/init":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/init","abstract":[],"role":"symbol","title":"init","url":"\/documentation\/easechatuikit\/detailinfo\/init","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo/switchValue":{"title":"switchValue","navigatorTitle":[{"text":"switchValue","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/switchValue","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/detailinfo\/switchvalue","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo/title":{"title":"title","navigatorTitle":[{"text":"title","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/title","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/detailinfo\/title","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DetailInfo","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DetailInfo","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DetailInfo","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/detail","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/switchValue","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/title","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/withSwitch"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/init","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo\/setValue(_:forUndefinedKey:)"]}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetailInfo","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"withSwitch","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1withSwitch\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1withSwitch\/fragments","value":[{"text":"withSwitch","kind":"identifier"}]},{"value":"DetailInfo","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo\/fragments","value":[{"text":"DetailInfo","kind":"identifier"}],"op":"replace"},{"value":"setValue:forUndefinedKey:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1setValue(_:forUndefinedKey:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setValue:forUndefinedKey:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1setValue(_:forUndefinedKey:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1detail\/title","value":"detail"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1detail\/fragments","value":[{"text":"detail","kind":"identifier"}],"op":"replace"},{"value":"switchValue","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1switchValue\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1switchValue\/fragments","value":[{"kind":"identifier","text":"switchValue"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1title\/title","value":"title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo~1title\/fragments","op":"replace","value":[{"text":"title","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}