{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"roleHeading":"Function","externalID":"c:@F@E_IF_exit","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","title":"E_IF_exit(_:)","symbolKind":"func","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"E_IF_exit","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer","kind":"typeIdentifier"},{"text":"!)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"E_IF_exit"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"E_IF_exit","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sv","kind":"typeIdentifier","text":"UnsafeMutableRawPointer"},{"text":"!)","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/E_IF_exit(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/e_if_exit(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/e_if_exit(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/E_IF_exit(_:)":{"navigatorTitle":[{"text":"E_IF_exit","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/E_IF_exit(_:)","kind":"symbol","role":"symbol","title":"E_IF_exit(_:)","url":"\/documentation\/easechatuikit\/e_if_exit(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"E_IF_exit"},{"kind":"text","text":"("},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"!)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Function","op":"replace"},{"path":"\/metadata\/title","value":"E_IF_exit","op":"replace"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"E_IF_exit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"E_IF_exit"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"state"},{"text":");","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1E_IF_exit(_:)\/title","value":"E_IF_exit"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1E_IF_exit(_:)\/fragments","value":[{"text":"E_IF_exit","kind":"identifier"}]}]}]}