{"metadata":{"title":"E_IF_init()","roleHeading":"Function","role":"symbol","externalID":"c:@F@E_IF_init","symbolKind":"func","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"E_IF_init","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"navigatorTitle":[{"kind":"identifier","text":"E_IF_init"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/E_IF_init()","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"E_IF_init","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"kind":"text","text":"!"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/e_if_init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/e_if_init()"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/E_IF_init()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"E_IF_init","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"kind":"text","text":"!"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/E_IF_init()","title":"E_IF_init()","url":"\/documentation\/easechatuikit\/e_if_init()","role":"symbol","abstract":[],"navigatorTitle":[{"text":"E_IF_init","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"E_IF_init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"E_IF_init","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"E_IF_init"},{"kind":"text","text":"();"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"E_IF_init","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1E_IF_init()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1E_IF_init()\/fragments","op":"replace","value":[{"text":"E_IF_init","kind":"identifier"}]}]}]}