{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"E_IF_encode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"state","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"mode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"speech"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"kind":"text","text":">!, "},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"out","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"dtx","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/e_if_encode(_:_:_:_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/e_if_encode(_:_:_:_:_:)"]}],"metadata":{"externalID":"c:@F@E_IF_encode","roleHeading":"Function","navigatorTitle":[{"kind":"identifier","text":"E_IF_encode"}],"title":"E_IF_encode(_:_:_:_:_:)","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"E_IF_encode","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sv","text":"UnsafeMutableRawPointer"},{"text":"!, ","kind":"text"},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"text":">!, ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!, "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"symbolKind":"func","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/E_IF_encode(_:_:_:_:_:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/E_IF_encode(_:_:_:_:_:)":{"title":"E_IF_encode(_:_:_:_:_:)","navigatorTitle":[{"text":"E_IF_encode","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/e_if_encode(_:_:_:_:_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/E_IF_encode(_:_:_:_:_:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"E_IF_encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!, "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SP","text":"UnsafePointer"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5Int16V","text":"Int16","kind":"typeIdentifier"},{"kind":"text","text":">!, "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">!, ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"text":"Int32","preciseIdentifier":"s:s5Int32V","kind":"typeIdentifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Function","op":"replace"},{"op":"replace","value":"E_IF_encode","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"E_IF_encode"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"text":" ","kind":"text"},{"text":"E_IF_encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"state"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:I","text":"int","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"mode"},{"kind":"text","text":", "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"short","kind":"typeIdentifier","preciseIdentifier":"c:S"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"speech"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"unsigned char","preciseIdentifier":"c:c"},{"text":" * ","kind":"text"},{"text":"out","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dtx"},{"text":");","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1E_IF_encode(_:_:_:_:_:)\/title","op":"replace","value":"E_IF_encode"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1E_IF_encode(_:_:_:_:_:)\/fragments","op":"replace","value":[{"text":"E_IF_encode","kind":"identifier"}]}]}]}