{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/easechatnavigationbarclickevent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/easechatnavigationbarclickevent"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/avatar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/back","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightItems","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightTitle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/subtitle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/title"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}],"title":"EaseChatNavigationBarClickEvent","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent":{"role":"symbol","title":"EaseChatNavigationBarClickEvent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/back":{"role":"symbol","title":"EaseChatNavigationBarClickEvent.back","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/back","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventBack"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/back"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/equatable-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/avatar":{"role":"symbol","title":"EaseChatNavigationBarClickEvent.avatar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/avatar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventAvatar"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/avatar"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/rightTitle":{"role":"symbol","title":"EaseChatNavigationBarClickEvent.rightTitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightTitle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightTitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventRightTitle"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/righttitle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/init(rawvalue:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/title":{"role":"symbol","title":"EaseChatNavigationBarClickEvent.title","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/title","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventTitle"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/title"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/subtitle":{"role":"symbol","title":"EaseChatNavigationBarClickEvent.subtitle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"subtitle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/subtitle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventSubtitle"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/subtitle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/rawrepresentable-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/rightItems":{"role":"symbol","title":"EaseChatNavigationBarClickEvent.rightItems","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightItems"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightItems","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventRightItems"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/rightitems"},"doc://org.cocoapods.EaseChatUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"EaseChatNavigationBarClickEvent"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/avatar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/back","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightItems","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightTitle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/subtitle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/title"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/title","value":"EaseChatNavigationBarClickEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1back\/title","value":"EaseChatNavigationBarClickEventBack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1back\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventBack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1avatar\/title","value":"EaseChatNavigationBarClickEventAvatar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1avatar\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventAvatar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1rightTitle\/title","value":"EaseChatNavigationBarClickEventRightTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1rightTitle\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventRightTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1title\/title","value":"EaseChatNavigationBarClickEventTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1title\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventTitle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1subtitle\/title","value":"EaseChatNavigationBarClickEventSubtitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1subtitle\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventSubtitle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1rightItems\/title","value":"EaseChatNavigationBarClickEventRightItems"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1rightItems\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventRightItems"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}