{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/easegroupprofileprovideroc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/easegroupprofileprovideroc"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseGroupProfileProviderOC","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseGroupProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseGroupProfileProviderOC","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)EaseGroupProfileProviderOC","modules":[{"name":"EaseChatUIKit"}],"title":"EaseGroupProfileProviderOC","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"EaseGroupProfileProviderOC"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"EaseGroupProfileProviderOC","kind":"identifier"}],"symbolKind":"protocol","role":"symbol"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseGroupProfileProviderOC":{"kind":"symbol","title":"EaseGroupProfileProviderOC","navigatorTitle":[{"text":"EaseGroupProfileProviderOC","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/easegroupprofileprovideroc","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseGroupProfileProviderOC","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"EaseGroupProfileProviderOC","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseGroupProfileProviderOC/fetchGroupProfiles(profileIds:completion:)":{"navigatorTitle":[{"text":"fetchGroupProfilesWithProfileIds:completion:","kind":"identifier"}],"role":"symbol","type":"topic","title":"fetchGroupProfiles(profileIds:completion:)","abstract":[{"type":"text","text":"Need to obtain the list display information on the current screen."}],"kind":"symbol","url":"\/documentation\/easechatuikit\/easegroupprofileprovideroc\/fetchgroupprofiles(profileids:completion:)","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseGroupProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchGroupProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profileIds"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol","kind":"typeIdentifier"},{"text":"]) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","value":"EaseGroupProfileProviderOC","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"EaseGroupProfileProviderOC"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"EaseGroupProfileProviderOC"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseGroupProfileProviderOC\/fetchGroupProfiles(profileIds:completion:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EaseGroupProfileProviderOC"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseGroupProfileProviderOC\/title","value":"EaseGroupProfileProviderOC","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseGroupProfileProviderOC\/fragments","value":[{"kind":"identifier","text":"EaseGroupProfileProviderOC"}],"op":"replace"},{"value":"fetchGroupProfilesWithProfileIds:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseGroupProfileProviderOC~1fetchGroupProfiles(profileIds:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"fetchGroupProfilesWithProfileIds:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseGroupProfileProviderOC~1fetchGroupProfiles(profileIds:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}