{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/emptyviewstate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/emptyviewstate"]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"EmptyViewState","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmptyViewState"}],"navigatorTitle":[{"text":"EmptyViewState","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@E@EmptyViewState","modules":[{"name":"EaseChatUIKit"}]},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"title":"Conforms To","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/empty","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/error"],"title":"Enumeration Cases"},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/init(rawValue:)"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations","title":"Default Implementations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EmptyViewState"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyViewState/empty":{"title":"EmptyViewState.empty","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/empty","kind":"symbol","type":"topic","navigatorTitle":[{"text":"EmptyViewStateEmpty","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"empty","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/emptyviewstate\/empty"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyViewState/Equatable-Implementations":{"url":"\/documentation\/easechatuikit\/emptyviewstate\/equatable-implementations","kind":"article","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/Equatable-Implementations","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyViewState/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/init(rawValue:)","title":"init(rawValue:)","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/emptyviewstate\/init(rawvalue:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyViewState/RawRepresentable-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/easechatuikit\/emptyviewstate\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyViewState/error":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/error","url":"\/documentation\/easechatuikit\/emptyviewstate\/error","abstract":[],"kind":"symbol","role":"symbol","title":"EmptyViewState.error","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"navigatorTitle":[{"text":"EmptyViewStateError","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyViewState":{"navigatorTitle":[{"text":"EmptyViewState","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/emptyviewstate","title":"EmptyViewState","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EmptyViewState"}]},"doc://org.cocoapods.EaseChatUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"EmptyViewState"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"EmptyViewState","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"EmptyViewState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/empty","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyViewState\/error"],"anchor":"Enumeration-Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"EmptyViewState","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"EmptyViewStateEmpty","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyViewState~1empty\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyViewState~1empty\/fragments","value":[{"text":"EmptyViewStateEmpty","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyViewState~1error\/title","value":"EmptyViewStateError","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyViewState~1error\/fragments","value":[{"text":"EmptyViewStateError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyViewState\/title","value":"EmptyViewState"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyViewState\/fragments","value":[{"kind":"identifier","text":"EmptyViewState"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyViewState\/navigatorTitle","value":[{"text":"EmptyViewState","kind":"identifier"}]}]}]}