{"metadata":{"role":"symbol","externalID":"c:@F@Encoder_Interface_Encode","roleHeading":"Function","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"func","navigatorTitle":[{"text":"Encoder_Interface_Encode","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"Encoder_Interface_Encode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"kind":"text","text":"!, "},{"preciseIdentifier":"c:@E@Mode","text":"Mode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UnsafePointer","preciseIdentifier":"s:SP","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V","text":"Int16"},{"kind":"text","text":">!, "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">!, "},{"text":"Int32","kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"title":"Encoder_Interface_Encode(_:_:_:_:_:)"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Encoder_Interface_Encode(_:_:_:_:_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/encoder_interface_encode(_:_:_:_:_:)"]},{"paths":["\/documentation\/easechatuikit\/encoder_interface_encode(_:_:_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Encoder_Interface_Encode"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutableRawPointer","preciseIdentifier":"s:Sv"},{"text":"!, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Mode","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode","preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"speech","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UnsafePointer","kind":"typeIdentifier","preciseIdentifier":"s:SP"},{"text":"<","kind":"text"},{"text":"Int16","kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V"},{"kind":"text","text":">!, "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"out","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">!, "},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"forceSpeech"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Encoder_Interface_Encode(_:_:_:_:_:)":{"title":"Encoder_Interface_Encode(_:_:_:_:_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Encoder_Interface_Encode(_:_:_:_:_:)","url":"\/documentation\/easechatuikit\/encoder_interface_encode(_:_:_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"Encoder_Interface_Encode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UnsafeMutableRawPointer","kind":"typeIdentifier","preciseIdentifier":"s:Sv"},{"text":"!, ","kind":"text"},{"preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier","text":"Mode"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SP","kind":"typeIdentifier","text":"UnsafePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"Int16","preciseIdentifier":"s:s5Int16V"},{"text":">!, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":">!, "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"text":"Encoder_Interface_Encode","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Mode":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/mode","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"kind":"symbol","title":"Mode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Function","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"Encoder_Interface_Encode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"path":"\/metadata\/fragments","value":[{"text":"Encoder_Interface_Encode","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"int","preciseIdentifier":"c:I"},{"kind":"text","text":" "},{"text":"Encoder_Interface_Encode","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" * "},{"text":"state","kind":"internalParam"},{"kind":"text","text":", "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Mode","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode","preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"mode","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"short","kind":"typeIdentifier","preciseIdentifier":"c:S"},{"text":" * ","kind":"text"},{"text":"speech","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:c","text":"unsigned char","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"out"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:I","text":"int"},{"kind":"text","text":" "},{"text":"forceSpeech","kind":"internalParam"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Encoder_Interface_Encode(_:_:_:_:_:)\/title","op":"replace","value":"Encoder_Interface_Encode"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Encoder_Interface_Encode(_:_:_:_:_:)\/fragments","value":[{"text":"Encoder_Interface_Encode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Mode\/title","value":"Mode"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Mode\/fragments","value":[{"text":"Mode","kind":"identifier"}]}]}]}