{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/init(style:reuseIdentifier:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/action","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/actionClosure","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/avatar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/nickName","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/separateLine"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/actionClick()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/layoutSubviews()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/refresh(info:keyword:forward:)"],"title":"Instance Methods"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ForwardTargetCell"}],"navigatorTitle":[{"text":"ForwardTargetCell","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ForwardTargetCell","symbolKind":"class","roleHeading":"Class","title":"ForwardTargetCell"},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UITableViewCell"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ForwardTargetCell","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/forwardtargetcell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/forwardtargetcell"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell","abstract":[],"role":"symbol","type":"topic","title":"ForwardTargetCell","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ForwardTargetCell"}],"navigatorTitle":[{"kind":"identifier","text":"ForwardTargetCell"}],"url":"\/documentation\/easechatuikit\/forwardtargetcell"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UILargeContentViewerItem":{"title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/nickName":{"url":"\/documentation\/easechatuikit\/forwardtargetcell\/nickname","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/nickName","title":"nickName","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"nickName"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"nickName"},{"kind":"text","text":": "},{"text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItemContainer":{"title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/init(coder:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/init(coder:)","title":"init(coder:)","url":"\/documentation\/easechatuikit\/forwardtargetcell\/init(coder:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/refresh(info:keyword:forward:)":{"title":"refresh(info:keyword:forward:)","url":"\/documentation\/easechatuikit\/forwardtargetcell\/refresh(info:keyword:forward:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"keyword"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forward"},{"kind":"text","text":": "},{"text":"ForwardTargetState","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ForwardTargetState"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/refresh(info:keyword:forward:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"refreshWithInfo:keyword:forward:"}]},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UITableViewCell":{"title":"UITableViewCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UITableViewCell","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIGestureRecognizerDelegate":{"title":"UIKit.UIGestureRecognizerDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIGestureRecognizerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/actionClosure":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/actionClosure","abstract":[],"role":"symbol","type":"topic","title":"actionClosure","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"actionClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ForwardTargetCell","text":"ForwardTargetCell"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"actionClosure"}],"url":"\/documentation\/easechatuikit\/forwardtargetcell\/actionclosure"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/init(style:reuseIdentifier:)":{"url":"\/documentation\/easechatuikit\/forwardtargetcell\/init(style:reuseidentifier:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/init(style:reuseIdentifier:)","title":"init(style:reuseIdentifier:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithStyle:reuseIdentifier:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UITableViewCellStyle","kind":"typeIdentifier","text":"CellStyle"},{"text":", ","kind":"text"},{"text":"reuseIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/actionClick()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"actionClick","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/actionClick()","type":"topic","navigatorTitle":[{"text":"actionClick","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/forwardtargetcell\/actionclick()","title":"actionClick()"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/action":{"url":"\/documentation\/easechatuikit\/forwardtargetcell\/action","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/action","title":"action","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"action"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIButton","preciseIdentifier":"c:objc(cs)UIButton"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/avatar":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/avatar","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"avatar","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/forwardtargetcell\/avatar","title":"avatar"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/separateLine":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"separateLine"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/separateLine","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"separateLine","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/forwardtargetcell\/separateline","title":"separateLine"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/layoutSubviews()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/layoutSubviews()","type":"topic","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/forwardtargetcell\/layoutsubviews()","title":"layoutSubviews()"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"ForwardTargetCell","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ForwardTargetCell","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ForwardTargetCell"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/action","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/actionClosure","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/avatar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/nickName","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/separateLine"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/actionClick()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/init(style:reuseIdentifier:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/layoutSubviews()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/refresh(info:keyword:forward:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UITableViewCell"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"ForwardTargetCell","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell\/title","value":"ForwardTargetCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell\/fragments","value":[{"text":"ForwardTargetCell","kind":"identifier"}],"op":"replace"},{"value":"nickName","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1nickName\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1nickName\/fragments","value":[{"kind":"identifier","text":"nickName"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1init(coder:)\/title","value":"initWithCoder:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1init(coder:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1refresh(info:keyword:forward:)\/title","value":"refreshWithInfo:keyword:forward:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithInfo:keyword:forward:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1refresh(info:keyword:forward:)\/fragments"},{"value":"actionClosure","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1actionClosure\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1actionClosure\/fragments","value":[{"text":"actionClosure","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1init(style:reuseIdentifier:)\/title","value":"initWithStyle:reuseIdentifier:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1init(style:reuseIdentifier:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStyle:reuseIdentifier:"}]},{"value":"actionClick","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1actionClick()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1actionClick()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"actionClick"}],"op":"replace"},{"value":"action","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1action\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1action\/fragments","value":[{"kind":"identifier","text":"action"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1avatar\/title","value":"avatar","op":"replace"},{"value":[{"kind":"identifier","text":"avatar"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1avatar\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1separateLine\/title","value":"separateLine","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1separateLine\/fragments","op":"replace","value":[{"text":"separateLine","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1layoutSubviews()\/title","value":"layoutSubviews"},{"value":[{"kind":"text","text":"- "},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1layoutSubviews()\/fragments"}]}]}