{"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/gradientColors0","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors1","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors2","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors3","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors4","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors5","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors6"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"variants":[{"paths":["\/documentation\/easechatuikit\/gradientcolors"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/gradientcolors"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GradientColors","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"kind":"symbol","metadata":{"roleHeading":"Class","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)GradientColors","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GradientColors","kind":"identifier"}],"role":"symbol","title":"GradientColors","navigatorTitle":[{"text":"GradientColors","kind":"identifier"}],"symbolKind":"class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/gradientColors0":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"gradientColors0","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"]","kind":"text"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/gradientcolors0","abstract":[],"title":"gradientColors0","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/gradientColors0","role":"symbol","navigatorTitle":[{"text":"gradientColors0","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/graduentColors3":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"graduentColors3"},{"kind":"text","text":": ["},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/graduentcolors3","abstract":[],"title":"graduentColors3","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors3","role":"symbol","navigatorTitle":[{"text":"graduentColors3","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/init":{"type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/init","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/init","title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/graduentColors5":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors5"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/graduentcolors5","abstract":[],"title":"graduentColors5","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors5","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"graduentColors5"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GradientColors","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/gradientcolors","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors","title":"GradientColors","role":"symbol","navigatorTitle":[{"text":"GradientColors","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/graduentColors2":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors2"},{"kind":"text","text":": ["},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/graduentcolors2","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors2","title":"graduentColors2","role":"symbol","navigatorTitle":[{"text":"graduentColors2","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/graduentColors4":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors4"},{"kind":"text","text":": ["},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/graduentcolors4","abstract":[],"title":"graduentColors4","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors4","role":"symbol","navigatorTitle":[{"text":"graduentColors4","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/graduentColors1":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors1"},{"kind":"text","text":": ["},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":"]"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/graduentcolors1","abstract":[],"title":"graduentColors1","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors1","role":"symbol","navigatorTitle":[{"text":"graduentColors1","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientColors/graduentColors6":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"graduentColors6"},{"kind":"text","text":": ["},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/easechatuikit\/gradientcolors\/graduentcolors6","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors6","title":"graduentColors6","role":"symbol","navigatorTitle":[{"text":"graduentColors6","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"GradientColors"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GradientColors"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GradientColors"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/init"],"title":"Instance Methods"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/gradientColors0","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors1","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors2","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors3","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors4","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors5","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientColors\/graduentColors6"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"GradientColors","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"gradientColors0","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1gradientColors0\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1gradientColors0\/fragments","value":[{"text":"gradientColors0","kind":"identifier"}],"op":"replace"},{"value":"graduentColors3","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors3\/title"},{"value":[{"kind":"identifier","text":"graduentColors3"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors3\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors5\/title","value":"graduentColors5","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors5\/fragments","value":[{"kind":"identifier","text":"graduentColors5"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors\/title","op":"replace","value":"GradientColors"},{"value":[{"kind":"identifier","text":"GradientColors"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors2\/title","op":"replace","value":"graduentColors2"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors2\/fragments","value":[{"text":"graduentColors2","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors4\/title","value":"graduentColors4"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors4\/fragments","value":[{"kind":"identifier","text":"graduentColors4"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors1\/title","value":"graduentColors1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors1\/fragments","op":"replace","value":[{"text":"graduentColors1","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors6\/title","op":"replace","value":"graduentColors6"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientColors~1graduentColors6\/fragments","value":[{"text":"graduentColors6","kind":"identifier"}],"op":"replace"}]}]}