{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/groupservicelistener"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupservicelistener"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onCurrentUserJoinedGroup(groupId:invitation:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onCurrentUserLeft(groupId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupJoinApplicationApproved(groupId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupJoinApplicationDeclined(groupId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onReceivedNewGroupApplication(groupId:userId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onUserJoinedGroup(groupId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceListener"}],"title":"GroupServiceListener","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener":{"role":"symbol","title":"GroupServiceListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"url":"\/documentation\/easechatuikit\/groupservicelistener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onUserJoinedGroup(groupId:userId:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserJoinedGroupWithGroupId:userId:"}],"role":"symbol","title":"onUserJoinedGroup(groupId:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserJoinedGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some user joined group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onUserJoinedGroup(groupId:userId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/onuserjoinedgroup(groupid:userid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onUserLeaveGroup(groupId:userId:)":{"navigatorTitle":[{"kind":"identifier","text":"onUserLeaveGroupWithGroupId:userId:"}],"role":"symbol","title":"onUserLeaveGroup(groupId:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLeaveGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When some user left group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/onuserleavegroup(groupid:userid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)":{"navigatorTitle":[{"kind":"identifier","text":"onReceivedNewGroupInvitationWithGroupId:groupName:userId:invitation:"}],"role":"symbol","title":"onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReceivedNewGroupInvitation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Received new group invitation"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/onreceivednewgroupinvitation(groupid:groupname:userid:invitation:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onGroupJoinApplicationApproved(groupId:)":{"navigatorTitle":[{"kind":"identifier","text":"onGroupJoinApplicationApprovedWithGroupId:"}],"role":"symbol","title":"onGroupJoinApplicationApproved(groupId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupJoinApplicationApproved"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The application to join the group was approved."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupJoinApplicationApproved(groupId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/ongroupjoinapplicationapproved(groupid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onInviterAcceptedInvitationOfGroup(groupId:userId:)":{"navigatorTitle":[{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}],"role":"symbol","title":"onInviterAcceptedInvitationOfGroup(groupId:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Accepted invitation of the group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/oninviteracceptedinvitationofgroup(groupid:userid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onGroupJoinApplicationDeclined(groupId:reason:)":{"navigatorTitle":[{"kind":"identifier","text":"onGroupJoinApplicationDeclinedWithGroupId:reason:"}],"role":"symbol","title":"onGroupJoinApplicationDeclined(groupId:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupJoinApplicationDeclined"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Application to join the group was rejected"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupJoinApplicationDeclined(groupId:reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/ongroupjoinapplicationdeclined(groupid:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)":{"navigatorTitle":[{"kind":"identifier","text":"onInviterDeclinedInvitationOfGroupWithGroupId:userId:reason:"}],"role":"symbol","title":"onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onInviterDeclinedInvitationOfGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When a group invitation is rejected"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/oninviterdeclinedinvitationofgroup(groupid:userid:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onReceivedNewGroupApplication(groupId:userId:reason:)":{"navigatorTitle":[{"kind":"identifier","text":"onReceivedNewGroupApplicationWithGroupId:userId:reason:"}],"role":"symbol","title":"onReceivedNewGroupApplication(groupId:userId:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onReceivedNewGroupApplication"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Received new group invitation"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onReceivedNewGroupApplication(groupId:userId:reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/onreceivednewgroupapplication(groupid:userid:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onGroupOwnerUpdated(groupId:ownerId:userId:)":{"navigatorTitle":[{"kind":"identifier","text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:"}],"role":"symbol","title":"onGroupOwnerUpdated(groupId:ownerId:userId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupOwnerUpdated"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ownerId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The group owner of the current group has changed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/ongroupownerupdated(groupid:ownerid:userid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onCurrentUserLeft(groupId:reason:)":{"navigatorTitle":[{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"role":"symbol","title":"onCurrentUserLeft(groupId:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCurrentUserLeft"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupLeaveReason","preciseIdentifier":"s:13EaseChatUIKit16GroupLeaveReasona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Current user is removed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onCurrentUserLeft(groupId:reason:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/oncurrentuserleft(groupid:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onCurrentUserJoinedGroup(groupId:invitation:)":{"navigatorTitle":[{"kind":"identifier","text":"onCurrentUserJoinedGroupWithGroupId:invitation:"}],"role":"symbol","title":"onCurrentUserJoinedGroup(groupId:invitation:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onCurrentUserJoinedGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The current user is added to the group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onCurrentUserJoinedGroup(groupId:invitation:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/oncurrentuserjoinedgroup(groupid:invitation:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)":{"navigatorTitle":[{"kind":"identifier","text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:"}],"role":"symbol","title":"onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAttributesChangedOfGroupMember"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">)"}],"abstract":[{"type":"text","text":"When attributes changed of some group member."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/groupservicelistener\/onattributeschangedofgroupmember(groupid:userid:operatorid:attributes:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"GroupServiceListener"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"GroupServiceListener"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"GroupServiceListener"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onCurrentUserJoinedGroup(groupId:invitation:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onCurrentUserLeft(groupId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupJoinApplicationApproved(groupId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupJoinApplicationDeclined(groupId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onGroupOwnerUpdated(groupId:ownerId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterAcceptedInvitationOfGroup(groupId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onReceivedNewGroupApplication(groupId:userId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onUserJoinedGroup(groupId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener\/onUserLeaveGroup(groupId:userId:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceListener"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/title","value":"GroupServiceListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/fragments","value":[{"kind":"identifier","text":"GroupServiceListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onUserJoinedGroup(groupId:userId:)\/title","value":"onUserJoinedGroupWithGroupId:userId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onUserJoinedGroup(groupId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserJoinedGroupWithGroupId:userId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onUserLeaveGroup(groupId:userId:)\/title","value":"onUserLeaveGroupWithGroupId:userId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onUserLeaveGroup(groupId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserLeaveGroupWithGroupId:userId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)\/title","value":"onReceivedNewGroupInvitationWithGroupId:groupName:userId:invitation:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onReceivedNewGroupInvitation(groupId:groupName:userId:invitation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReceivedNewGroupInvitationWithGroupId:groupName:userId:invitation:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onGroupJoinApplicationApproved(groupId:)\/title","value":"onGroupJoinApplicationApprovedWithGroupId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onGroupJoinApplicationApproved(groupId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupJoinApplicationApprovedWithGroupId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/title","value":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onInviterAcceptedInvitationOfGroup(groupId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInviterAcceptedInvitationOfGroupWithGroupId:userId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onGroupJoinApplicationDeclined(groupId:reason:)\/title","value":"onGroupJoinApplicationDeclinedWithGroupId:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onGroupJoinApplicationDeclined(groupId:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupJoinApplicationDeclinedWithGroupId:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)\/title","value":"onInviterDeclinedInvitationOfGroupWithGroupId:userId:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onInviterDeclinedInvitationOfGroup(groupId:userId:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onInviterDeclinedInvitationOfGroupWithGroupId:userId:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onReceivedNewGroupApplication(groupId:userId:reason:)\/title","value":"onReceivedNewGroupApplicationWithGroupId:userId:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onReceivedNewGroupApplication(groupId:userId:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onReceivedNewGroupApplicationWithGroupId:userId:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/title","value":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onCurrentUserLeft(groupId:reason:)\/title","value":"onCurrentUserLeftWithGroupId:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onCurrentUserLeft(groupId:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onCurrentUserJoinedGroup(groupId:invitation:)\/title","value":"onCurrentUserJoinedGroupWithGroupId:invitation:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onCurrentUserJoinedGroup(groupId:invitation:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onCurrentUserJoinedGroupWithGroupId:invitation:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/title","value":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}