{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupServiceImplement"}]}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/init()"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMGroupManagerDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMThreadManagerDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceImplement"}],"navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupServiceImplement","symbolKind":"class","roleHeading":"Class","title":"GroupServiceImplement"},"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMGroupManagerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMThreadManagerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupserviceimplement"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)EMThreadManagerDelegate":{"title":"EMThreadManagerDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMThreadManagerDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","navigatorTitle":[{"kind":"identifier","text":"GroupServiceImplement"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement","role":"symbol","title":"GroupServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/GroupService-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupservice-implementations","role":"collectionGroup","title":"GroupService Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/init()":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/init()","title":"init()","type":"topic","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/init()"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/EMGroupManagerDelegate-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement\/emgroupmanagerdelegate-implementations","abstract":[],"title":"EMGroupManagerDelegate Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMGroupManagerDelegate-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService":{"title":"GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupService","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/groupservice","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService","navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)EMGroupManagerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMGroupManagerDelegate","title":"EMGroupManagerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/EMThreadManagerDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMThreadManagerDelegate-Implementations","title":"EMThreadManagerDelegate Implementations","role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/emthreadmanagerdelegate-implementations","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","value":"GroupServiceImplement","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"GroupServiceImplement","kind":"identifier"}]},{"value":[{"text":"GroupServiceImplement","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/init()"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMGroupManagerDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMThreadManagerDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations"],"title":"Default Implementations","generated":true}]},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMGroupManagerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)EMThreadManagerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupServiceImplement","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"GroupServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title"},{"value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/title","value":"GroupService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/fragments","value":[{"text":"GroupService","kind":"identifier"}]}]}]}