{"abstract":[{"text":"ConversationList view driver.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IConversationListDriver","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver","modules":[{"name":"EaseChatUIKit"}],"title":"IConversationListDriver","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"IConversationListDriver"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IConversationListDriver","kind":"identifier"}],"symbolKind":"protocol","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList"],"type":"conformingTypes","title":"Conforming Types","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/appendThenRefresh(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/occurError()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshList(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/removeActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/showNew(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/swipeMenuOperation(info:type:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/showNew(info:)":{"title":"showNew(info:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showNew"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"When you received a new contact message,you can call the method.","type":"text"}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver\/shownew(info:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/showNew(info:)","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showNewWithInfo:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/refreshList(infos:)":{"title":"refreshList(infos:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/iconversationlistdriver\/refreshlist(infos:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshList(infos:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"refreshList","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"refreshListWithInfos:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This method can be used when pulling down to refresh."}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/appendThenRefresh(infos:)":{"abstract":[{"type":"text","text":"When you receive a lot of messages from new contacts, you can call this method for data transfer."}],"title":"appendThenRefresh(infos:)","type":"topic","navigatorTitle":[{"text":"appendThenRefreshWithInfos:","kind":"identifier"}],"required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/appendThenRefresh(infos:)","kind":"symbol","url":"\/documentation\/easechatuikit\/iconversationlistdriver\/appendthenrefresh(infos:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"appendThenRefresh","kind":"identifier"},{"kind":"text","text":"("},{"text":"infos","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/addActionHandler(actionHandler:)":{"navigatorTitle":[{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"abstract":[{"type":"text","text":"Add UI actions handler."}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver\/addactionhandler(actionhandler:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/addActionHandler(actionHandler:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate"},{"kind":"text","text":")"}],"title":"addActionHandler(actionHandler:)","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/swipeMenuOperation(info:type:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/swipeMenuOperation(info:type:)","kind":"symbol","title":"swipeMenuOperation(info:type:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipeMenuOperation","kind":"identifier"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Conversation Operation event after clicking the button in the side-sliding menu.","type":"text"}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver\/swipemenuoperation(info:type:)","navigatorTitle":[{"text":"swipeMenuOperationWithInfo:type:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/occurError()":{"abstract":[{"type":"text","text":"When fetch list occur error."}],"title":"occurError()","type":"topic","navigatorTitle":[{"text":"occurError","kind":"identifier"}],"required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/occurError()","kind":"symbol","url":"\/documentation\/easechatuikit\/iconversationlistdriver\/occurerror()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"occurError","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IConversationListDriver"}],"abstract":[{"type":"text","text":"ConversationList view driver."}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver","title":"IConversationListDriver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IConversationListDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationList":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationlist","title":"ConversationList","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationList"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/refreshProfiles(infos:)":{"url":"\/documentation\/easechatuikit\/iconversationlistdriver\/refreshprofiles(infos:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshProfiles(infos:)","navigatorTitle":[{"text":"refreshProfilesWithInfos:","kind":"identifier"}],"abstract":[{"text":"This method can be used when you want refresh some  display info  of datas.","type":"text"}],"role":"symbol","title":"refreshProfiles(infos:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refreshProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infos","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol"},{"kind":"text","text":"])"}],"required":true,"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/removeActionHandler(actionHandler:)":{"role":"symbol","title":"removeActionHandler(actionHandler:)","type":"topic","navigatorTitle":[{"text":"removeActionHandlerWithActionHandler:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/removeActionHandler(actionHandler:)","url":"\/documentation\/easechatuikit\/iconversationlistdriver\/removeactionhandler(actionhandler:)","abstract":[{"text":"Remove UI action handler.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeActionHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"text":"ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"IConversationListDriver"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IConversationListDriver"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"IConversationListDriver","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/appendThenRefresh(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/occurError()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshList(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/removeActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/showNew(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/swipeMenuOperation(info:type:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IConversationListDriver"},{"kind":"text","text":" <"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1showNew(info:)\/title","value":"showNewWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1showNew(info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showNewWithInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshList(infos:)\/title","value":"refreshListWithInfos:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshList(infos:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"refreshListWithInfos:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1appendThenRefresh(infos:)\/title","op":"replace","value":"appendThenRefreshWithInfos:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1appendThenRefresh(infos:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"appendThenRefreshWithInfos:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1addActionHandler(actionHandler:)\/title","value":"addActionHandlerWithActionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1addActionHandler(actionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"value":"swipeMenuOperationWithInfo:type:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1swipeMenuOperation(info:type:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"swipeMenuOperationWithInfo:type:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1swipeMenuOperation(info:type:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1occurError()\/title","value":"occurError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1occurError()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"occurError"}]},{"value":"IConversationListDriver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/title"},{"op":"replace","value":[{"kind":"identifier","text":"IConversationListDriver"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/fragments"},{"value":"ConversationList","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationList"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshProfiles(infos:)\/title","value":"refreshProfilesWithInfos:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"refreshProfilesWithInfos:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshProfiles(infos:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1removeActionHandler(actionHandler:)\/title","value":"removeActionHandlerWithActionHandler:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1removeActionHandler(actionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}]}]}]}