{"variants":[{"paths":["\/documentation\/easechatuikit\/icontactlistdriver"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/icontactlistdriver"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView"],"kind":"relationships","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IContactListDriver"}],"title":"IContactListDriver","navigatorTitle":[{"kind":"identifier","text":"IContactListDriver"}],"role":"symbol","symbolKind":"protocol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"A driver protocol of ","type":"text"},{"type":"codeVoice","code":"ContactList"},{"text":".","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/appendThenRefresh(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/occurError()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshHeader(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshList(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/remove(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/removeActionHandler(actionHandler:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IContactListDriver","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/remove(info:)":{"title":"remove(info:)","required":true,"kind":"symbol","navigatorTitle":[{"text":"removeWithInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/remove(info:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"The method can be used when you want to remove a contact."}],"url":"\/documentation\/easechatuikit\/icontactlistdriver\/remove(info:)","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/refreshProfiles(infos:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"refreshProfilesWithInfos:"}],"type":"topic","required":true,"title":"refreshProfiles(infos:)","abstract":[{"type":"text","text":"This method can be used when you want refresh some  display info  of datas."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refreshProfiles","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infos","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshProfiles(infos:)","url":"\/documentation\/easechatuikit\/icontactlistdriver\/refreshprofiles(infos:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver":{"kind":"symbol","abstract":[{"text":"A driver protocol of ","type":"text"},{"code":"ContactList","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","navigatorTitle":[{"text":"IContactListDriver","kind":"identifier"}],"title":"IContactListDriver","url":"\/documentation\/easechatuikit\/icontactlistdriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IContactListDriver"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/removeActionHandler(actionHandler:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeActionHandler"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ContactListActionEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListActionEventsDelegate"},{"text":")","kind":"text"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/removeActionHandler(actionHandler:)","navigatorTitle":[{"text":"removeActionHandlerWithActionHandler:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/icontactlistdriver\/removeactionhandler(actionhandler:)","abstract":[{"text":"Remove UI action handler.","type":"text"}],"title":"removeActionHandler(actionHandler:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/refreshList(infos:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshList(infos:)","role":"symbol","title":"refreshList(infos:)","url":"\/documentation\/easechatuikit\/icontactlistdriver\/refreshlist(infos:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refreshList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infos","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"text":"])","kind":"text"}],"abstract":[{"type":"text","text":"This method can be used when pulling down to refresh."}],"kind":"symbol","required":true,"navigatorTitle":[{"text":"refreshListWithInfos:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/appendThenRefresh(info:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/appendThenRefresh(info:)","title":"appendThenRefresh(info:)","abstract":[{"text":"The method can be user when you want to add someone to contact list.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"appendThenRefresh","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":")"}],"required":true,"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/icontactlistdriver\/appendthenrefresh(info:)","type":"topic","navigatorTitle":[{"text":"appendThenRefreshWithInfo:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactView","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/contactview","type":"topic","title":"ContactView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView","navigatorTitle":[{"text":"ContactView","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/addActionHandler(actionHandler:)":{"required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/addActionHandler(actionHandler:)","url":"\/documentation\/easechatuikit\/icontactlistdriver\/addactionhandler(actionhandler:)","title":"addActionHandler(actionHandler:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"abstract":[{"type":"text","text":"Add UI actions handler."}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListActionEventsDelegate","kind":"typeIdentifier","text":"ContactListActionEventsDelegate"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/occurError()":{"abstract":[{"type":"text","text":"When fetch list occur error."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/occurError()","type":"topic","navigatorTitle":[{"text":"occurError","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/icontactlistdriver\/occurerror()","kind":"symbol","required":true,"title":"occurError()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"occurError"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver/refreshHeader(info:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refreshHeader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ContactListHeaderItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"kind":"text","text":")"}],"required":true,"abstract":[{"text":"The method can be used when you want to refresh header of the contact list.","type":"text"}],"role":"symbol","url":"\/documentation\/easechatuikit\/icontactlistdriver\/refreshheader(info:)","kind":"symbol","title":"refreshHeader(info:)","navigatorTitle":[{"text":"refreshHeaderWithInfo:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshHeader(info:)","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"IContactListDriver","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"IContactListDriver","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"IContactListDriver"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/appendThenRefresh(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/occurError()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshHeader(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshList(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/remove(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver\/removeActionHandler(actionHandler:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView"],"kind":"relationships","type":"conformingTypes"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IContactListDriver"},{"kind":"text","text":" <"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"kind":"text","text":">"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1remove(info:)\/title","value":"removeWithInfo:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1remove(info:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeWithInfo:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1refreshProfiles(infos:)\/title","value":"refreshProfilesWithInfos:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1refreshProfiles(infos:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshProfilesWithInfos:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/title","op":"replace","value":"IContactListDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/fragments","value":[{"kind":"identifier","text":"IContactListDriver"}]},{"op":"replace","value":[{"text":"IContactListDriver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1removeActionHandler(actionHandler:)\/title","value":"removeActionHandlerWithActionHandler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1removeActionHandler(actionHandler:)\/fragments"},{"value":"refreshListWithInfos:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1refreshList(infos:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"refreshListWithInfos:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1refreshList(infos:)\/fragments"},{"value":"appendThenRefreshWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1appendThenRefresh(info:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"appendThenRefreshWithInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1appendThenRefresh(info:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/title","value":"ContactView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/fragments","value":[{"kind":"identifier","text":"ContactView"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ContactView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/navigatorTitle"},{"value":"addActionHandlerWithActionHandler:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1addActionHandler(actionHandler:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1addActionHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"op":"replace"},{"value":"occurError","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1occurError()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"occurError"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1occurError()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1refreshHeader(info:)\/title","value":"refreshHeaderWithInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver~1refreshHeader(info:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"refreshHeaderWithInfo:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}