{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/refresh(entities:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/remove(messageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/removeEventHandler(actionHandler:)"],"anchor":"Instance-Methods"}],"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer"],"kind":"relationships","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IPinnedMessagesContainerDriver","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"IPinnedMessagesContainerDriver","externalID":"c:@M@EaseChatUIKit@objc(pl)IPinnedMessagesContainerDriver","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"protocol","roleHeading":"Protocol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer","type":"topic","title":"PinnedMessagesContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver/remove(messageId:)":{"navigatorTitle":[{"kind":"identifier","text":"removeWithMessageId:"}],"role":"symbol","type":"topic","abstract":[],"required":true,"kind":"symbol","url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/remove(messageid:)","title":"remove(messageId:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/remove(messageId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver/addActionHandler(actionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/addActionHandler(actionHandler:)","title":"addActionHandler(actionHandler:)","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"abstract":[{"type":"text","text":"Add action events listener of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","isActive":true},{"type":"text","text":"."}],"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/addactionhandler(actionhandler:)","kind":"symbol","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver/refresh(entities:)":{"kind":"symbol","title":"refresh(entities:)","required":true,"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entities"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"PinnedMessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity"},{"kind":"text","text":"])"}],"abstract":[],"url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/refresh(entities:)","navigatorTitle":[{"kind":"identifier","text":"refreshWithEntities:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/refresh(entities:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver":{"url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"IPinnedMessagesContainerDriver","navigatorTitle":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver/removeEventHandler(actionHandler:)":{"url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/removeeventhandler(actionhandler:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/removeEventHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeEventHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PinnedMessagesContainerDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Remove action events listener of ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","isActive":true},{"text":".","type":"text"}],"required":true,"title":"removeEventHandler(actionHandler:)","navigatorTitle":[{"text":"removeEventHandlerWithActionHandler:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"IPinnedMessagesContainerDriver","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}]},{"value":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/refresh(entities:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/remove(messageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/removeEventHandler(actionHandler:)"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"]},{"title":"Conforming Types","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer"],"type":"conformingTypes"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"IPinnedMessagesContainerDriver","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"PinnedMessagesContainer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/fragments","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/navigatorTitle"},{"value":"removeWithMessageId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1remove(messageId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1remove(messageId:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeWithMessageId:","kind":"identifier"}]},{"value":"addActionHandlerWithActionHandler:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1addActionHandler(actionHandler:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1addActionHandler(actionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1refresh(entities:)\/title","value":"refreshWithEntities:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithEntities:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1refresh(entities:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/title","op":"replace","value":"IPinnedMessagesContainerDriver"},{"op":"replace","value":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/navigatorTitle","op":"replace","value":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1removeEventHandler(actionHandler:)\/title","value":"removeEventHandlerWithActionHandler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1removeEventHandler(actionHandler:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}