{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"title":"Inherits From"},{"type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList"],"kind":"relationships","title":"Conforming Types"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"ISectionIndexListDriver"}],"title":"ISectionIndexListDriver","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ISectionIndexListDriver"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)ISectionIndexListDriver","symbolKind":"protocol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/isectionindexlistdriver"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/isectionindexlistdriver"]}],"abstract":[{"type":"text","text":"A protocol that defines the driver for a section index list."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver\/refresh(titles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISectionIndexListDriver"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SectionIndexList":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SectionIndexList"}],"url":"\/documentation\/easechatuikit\/sectionindexlist","navigatorTitle":[{"kind":"identifier","text":"SectionIndexList"}],"role":"symbol","type":"topic","title":"SectionIndexList"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ISectionIndexListDriver":{"role":"symbol","navigatorTitle":[{"text":"ISectionIndexListDriver","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A protocol that defines the driver for a section index list."}],"title":"ISectionIndexListDriver","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ISectionIndexListDriver"}],"type":"topic","url":"\/documentation\/easechatuikit\/isectionindexlistdriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ISectionIndexListDriver/selectItem(indexPath:)":{"navigatorTitle":[{"text":"selectItemWithIndexPath:","kind":"identifier"}],"title":"selectItem(indexPath:)","url":"\/documentation\/easechatuikit\/isectionindexlistdriver\/selectitem(indexpath:)","abstract":[{"text":"Selects an item at the specified index path.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ISectionIndexListDriver/refresh(titles:)":{"role":"symbol","navigatorTitle":[{"text":"refreshWithTitles:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Refreshes the titles of the section index list."}],"required":true,"title":"refresh(titles:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"titles"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver\/refresh(titles:)","url":"\/documentation\/easechatuikit\/isectionindexlistdriver\/refresh(titles:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"ISectionIndexListDriver","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"text":"ISectionIndexListDriver","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"ISectionIndexListDriver","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver\/refresh(titles:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ISectionIndexListDriver\/selectItem(indexPath:)"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList"],"title":"Conforming Types"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISectionIndexListDriver","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList\/title","value":"SectionIndexList","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList\/fragments","value":[{"kind":"identifier","text":"SectionIndexList"}]},{"op":"replace","value":"ISectionIndexListDriver","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ISectionIndexListDriver\/title"},{"value":[{"kind":"identifier","text":"ISectionIndexListDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ISectionIndexListDriver\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ISectionIndexListDriver~1selectItem(indexPath:)\/title","value":"selectItemWithIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ISectionIndexListDriver~1selectItem(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"selectItemWithIndexPath:"}],"op":"replace"},{"value":"refreshWithTitles:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ISectionIndexListDriver~1refresh(titles:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ISectionIndexListDriver~1refresh(titles:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithTitles:"}]}]}]}