{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecellstyle"]},{"paths":["\/documentation\/easechatuikit\/messagecellstyle"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"title":"MessageCellStyle","roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"text":"MessageCellStyle","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@E@MessageCellStyle","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCellStyle"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Enum representing the style of a message cell."}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/alert","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/cmd","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/combine","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/contact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/file","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/image","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/location","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/text","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/video","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/voice"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageCellStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle","type":"topic","role":"symbol","abstract":[{"text":"Enum representing the style of a message cell.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageCellStyle"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCellStyle"}],"title":"MessageCellStyle","kind":"symbol","url":"\/documentation\/easechatuikit\/messagecellstyle"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/image":{"abstract":[],"url":"\/documentation\/easechatuikit\/messagecellstyle\/image","title":"MessageCellStyle.image","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCellStyleImage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/image"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/text":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/messagecellstyle\/text","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/text","navigatorTitle":[{"text":"MessageCellStyleText","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"text","kind":"identifier"}],"title":"MessageCellStyle.text","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/alert":{"title":"MessageCellStyle.alert","navigatorTitle":[{"text":"MessageCellStyleAlert","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/alert","url":"\/documentation\/easechatuikit\/messagecellstyle\/alert","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alert"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/contact":{"type":"topic","title":"MessageCellStyle.contact","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/contact","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contact","kind":"identifier"}],"navigatorTitle":[{"text":"MessageCellStyleContact","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagecellstyle\/contact"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/cmd":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCellStyleCmd"}],"title":"MessageCellStyle.cmd","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cmd"}],"url":"\/documentation\/easechatuikit\/messagecellstyle\/cmd","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/cmd"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/RawRepresentable-Implementations","url":"\/documentation\/easechatuikit\/messagecellstyle\/rawrepresentable-implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/init(rawValue:)","url":"\/documentation\/easechatuikit\/messagecellstyle\/init(rawvalue:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/voice":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"voice","kind":"identifier"}],"abstract":[],"title":"MessageCellStyle.voice","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCellStyleVoice"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messagecellstyle\/voice","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/voice"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/file":{"abstract":[],"url":"\/documentation\/easechatuikit\/messagecellstyle\/file","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"file"}],"title":"MessageCellStyle.file","navigatorTitle":[{"kind":"identifier","text":"MessageCellStyleFile"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/file","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/location":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/location","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"location","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCellStyleLocation"}],"title":"MessageCellStyle.location","url":"\/documentation\/easechatuikit\/messagecellstyle\/location","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/combine":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MessageCellStyleCombine"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/combine","url":"\/documentation\/easechatuikit\/messagecellstyle\/combine","title":"MessageCellStyle.combine","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"combine","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/video":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"video","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"MessageCellStyleVideo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/video","url":"\/documentation\/easechatuikit\/messagecellstyle\/video","title":"MessageCellStyle.video","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/Equatable-Implementations":{"role":"collectionGroup","type":"topic","title":"Equatable Implementations","kind":"article","url":"\/documentation\/easechatuikit\/messagecellstyle\/equatable-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/Equatable-Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"MessageCellStyle","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageCellStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MessageCellStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/alert","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/cmd","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/combine","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/contact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/file","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/image","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/location","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/text","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/video","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/voice"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true}]},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCellStyle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle\/title","value":"MessageCellStyle","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCellStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle\/navigatorTitle","value":[{"kind":"identifier","text":"MessageCellStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1image\/title","value":"MessageCellStyleImage"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1image\/fragments","value":[{"text":"MessageCellStyleImage","kind":"identifier"}],"op":"replace"},{"value":"MessageCellStyleText","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1text\/title"},{"value":[{"kind":"identifier","text":"MessageCellStyleText"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1text\/fragments"},{"value":"MessageCellStyleAlert","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1alert\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1alert\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageCellStyleAlert"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1contact\/title","value":"MessageCellStyleContact"},{"value":[{"kind":"identifier","text":"MessageCellStyleContact"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1contact\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1cmd\/title","value":"MessageCellStyleCmd"},{"value":[{"text":"MessageCellStyleCmd","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1cmd\/fragments"},{"value":"MessageCellStyleVoice","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1voice\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCellStyleVoice"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1voice\/fragments"},{"op":"replace","value":"MessageCellStyleFile","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1file\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1file\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageCellStyleFile"}]},{"value":"MessageCellStyleLocation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1location\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1location\/fragments","op":"replace","value":[{"text":"MessageCellStyleLocation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1combine\/title","value":"MessageCellStyleCombine"},{"value":[{"text":"MessageCellStyleCombine","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1combine\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1video\/title","value":"MessageCellStyleVideo"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCellStyleVideo"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle~1video\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}