{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionsDetailController"}],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentedViewType","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegateFlowLayout","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController"},"variants":[{"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"navigatorTitle":[{"text":"MessageReactionsDetailController","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionsDetailController"}],"title":"MessageReactionsDetailController","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageReactionsDetailController","symbolKind":"class","roleHeading":"Class","role":"symbol"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/init(message:actionClosure:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/cursor","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/indicator","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/layout","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/message","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/presentedViewComponent","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactionUserList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactionsList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/selectedReaction","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/users"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/messageReactionUsers()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/viewDidLoad()"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegateFlowLayout-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDelegate-Implementations"],"generated":true,"title":"Default Implementations"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"kind":"symbol","type":"topic","title":"MessageReactionsDetailController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionsDetailController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/reactionUserList":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/reactionuserlist","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactionUserList","role":"symbol","navigatorTitle":[{"text":"reactionUserList","kind":"identifier"}],"title":"reactionUserList","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reactionUserList"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/cursor":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/cursor","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/cursor","role":"symbol","navigatorTitle":[{"text":"cursor","kind":"identifier"}],"kind":"symbol","type":"topic","title":"cursor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cursor"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/indicator":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/indicator","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/indicator","role":"symbol","navigatorTitle":[{"text":"indicator","kind":"identifier"}],"title":"indicator","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicator"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","title":"UIKit.UIScrollViewDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/messageReactionUsers()":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/messagereactionusers()","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/messageReactionUsers()","role":"symbol","navigatorTitle":[{"text":"messageReactionUsers","kind":"identifier"}],"title":"messageReactionUsers()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionUsers"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICollectionViewDelegateFlowLayout":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegateFlowLayout","title":"UICollectionViewDelegateFlowLayout","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/message":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/message","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/message","role":"symbol","navigatorTitle":[{"text":"message","kind":"identifier"}],"kind":"symbol","type":"topic","title":"message","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICollectionViewDataSource":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDataSource","title":"UICollectionViewDataSource","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/reactionsList":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/reactionslist","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactionsList","role":"symbol","navigatorTitle":[{"text":"reactionsList","kind":"identifier"}],"title":"reactionsList","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactionsList"},{"kind":"text","text":": "},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"}]},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/presentedViewComponent":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/presentedviewcomponent","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/presentedViewComponent","role":"symbol","title":"presentedViewComponent","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"text":"PresentedViewComponent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit22PresentedViewComponentV"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDataSource":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","title":"UITableViewDataSource"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/init(message:actionClosure:)":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/init(message:actionclosure:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/init(message:actionClosure:)","role":"symbol","navigatorTitle":[{"text":"initWithMessage:actionClosure:","kind":"identifier"}],"kind":"symbol","type":"topic","title":"init(message:actionClosure:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"text":"actionClosure","kind":"externalParam"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/ThemeSwitchProtocol-Implementations":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/themeswitchprotocol-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/ThemeSwitchProtocol-Implementations","role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDelegate":{"title":"UITableViewDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/scrollViewDidEndDecelerating(_:)":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/scrollviewdidenddecelerating(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/scrollViewDidEndDecelerating(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"kind":"symbol","type":"topic","title":"scrollViewDidEndDecelerating(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/UICollectionViewDataSource-Implementations":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/uicollectionviewdatasource-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDataSource-Implementations","role":"collectionGroup","title":"UICollectionViewDataSource Implementations","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/UICollectionViewDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/uicollectionviewdelegate-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegate-Implementations","role":"collectionGroup","title":"UICollectionViewDelegate Implementations","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/viewDidLoad()":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/viewdidload()","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/viewDidLoad()","role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","type":"topic","title":"viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/UITableViewDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/uitableviewdelegate-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDelegate-Implementations","role":"collectionGroup","kind":"article","type":"topic","title":"UITableViewDelegate Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/layout":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/layout","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/layout","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"layout"}],"title":"layout","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layout","kind":"identifier"},{"kind":"text","text":": "},{"text":"UICollectionViewFlowLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentedViewType":{"url":"\/documentation\/easechatuikit\/presentedviewtype","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentedViewType","role":"symbol","navigatorTitle":[{"text":"PresentedViewType","kind":"identifier"}],"kind":"symbol","type":"topic","title":"PresentedViewType","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentedViewType","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate","title":"UIKit.UIViewControllerTransitioningDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/reactions":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/reactions","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactions","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reactions"}],"kind":"symbol","type":"topic","title":"reactions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"reactions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","text":"MessageReaction","kind":"typeIdentifier"},{"kind":"text","text":"]"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/UITableViewDataSource-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDataSource-Implementations","kind":"article","title":"UITableViewDataSource Implementations","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/uitableviewdatasource-implementations"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIViewController":{"title":"UIViewController","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","abstract":[{"text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the chat room UIKit.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ThemeSwitchProtocol","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/themeswitchprotocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"title":"ThemeSwitchProtocol","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/users":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/users","kind":"symbol","title":"users","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"users","kind":"identifier"},{"text":": [any ","kind":"text"},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"users"}],"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/users","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/init(coder:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/init(coder:)","kind":"symbol","title":"init(coder:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/init(coder:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/UICollectionViewDelegateFlowLayout-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegateFlowLayout-Implementations","kind":"article","title":"UICollectionViewDelegateFlowLayout Implementations","type":"topic","url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/uicollectionviewdelegateflowlayout-implementations","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICollectionViewDelegate":{"title":"UIKit.UICollectionViewDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegate"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/selectedReaction":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/selectedReaction","kind":"symbol","title":"selectedReaction","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"selectedReaction","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"selectedReaction","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/selectedreaction"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MessageReactionsDetailController","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MessageReactionsDetailController"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/cursor","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/indicator","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/layout","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/message","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactionUserList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/reactionsList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/selectedReaction","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/users"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/init(message:actionClosure:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/messageReactionUsers()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/viewDidLoad()"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegateFlowLayout-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDelegate-Implementations"],"generated":true}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICollectionViewDelegateFlowLayout","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate"],"title":"Conforms To","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"MessageReactionsDetailController","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/title","value":"MessageReactionsDetailController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/fragments","value":[{"text":"MessageReactionsDetailController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1reactionUserList\/title","value":"reactionUserList","op":"replace"},{"value":[{"text":"reactionUserList","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1reactionUserList\/fragments"},{"value":"cursor","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1cursor\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1cursor\/fragments","value":[{"kind":"identifier","text":"cursor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1indicator\/title","value":"indicator"},{"value":[{"kind":"identifier","text":"indicator"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1indicator\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1messageReactionUsers()\/title","op":"replace","value":"messageReactionUsers"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1messageReactionUsers()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageReactionUsers"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1message\/title","value":"message","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1message\/fragments","value":[{"kind":"identifier","text":"message"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1reactionsList\/title","value":"reactionsList","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1reactionsList\/fragments","value":[{"kind":"identifier","text":"reactionsList"}],"op":"replace"},{"value":"initWithMessage:actionClosure:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1init(message:actionClosure:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMessage:actionClosure:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1init(message:actionClosure:)\/fragments","op":"replace"},{"op":"replace","value":"scrollViewDidEndDecelerating:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1scrollViewDidEndDecelerating(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1scrollViewDidEndDecelerating(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}]},{"value":"layout","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1layout\/title"},{"value":[{"kind":"identifier","text":"layout"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1layout\/fragments"},{"value":"reactions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1reactions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"reactions"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1reactions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"value":"users","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1users\/title"},{"op":"replace","value":[{"kind":"identifier","text":"users"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1users\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1init(coder:)\/title","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1init(coder:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1selectedReaction\/title","op":"replace","value":"selectedReaction"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1selectedReaction\/fragments","value":[{"kind":"identifier","text":"selectedReaction"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}