{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistview"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Class","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageListView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListView","kind":"identifier"}],"title":"MessageListView","navigatorTitle":[{"kind":"identifier","text":"MessageListView"}],"role":"symbol","symbolKind":"class"},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(frame:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(frame:mention:showType:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/canMention","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/editBottomBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/editMode","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/inputBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/messageList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/messages","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/moreMessages","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/replyBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/showType","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/threadMessagesLoadFinished"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshPreviewResult(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/removeEventHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollTableViewToBottom()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollToBottom()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollViewDidEndDecelerating(_:)"],"anchor":"Instance-Methods","generated":true},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/UITableViewDelegate-Implementations"],"title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListView"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/scrollTableViewToBottom()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scrollTableViewToBottom"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollTableViewToBottom()","navigatorTitle":[{"kind":"identifier","text":"scrollTableViewToBottom"}],"title":"scrollTableViewToBottom()","url":"\/documentation\/easechatuikit\/messagelistview\/scrolltableviewtobottom()","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}],"url":"\/documentation\/easechatuikit\/messagelistview","title":"MessageListView"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/imessagelistviewdriver","abstract":[],"role":"symbol","title":"IMessageListViewDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IMessageListViewDriver","kind":"identifier"}],"navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/canMention":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"canMention"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"title":"canMention","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/canMention","url":"\/documentation\/easechatuikit\/messagelistview\/canmention"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIScrollViewDelegate":{"title":"UIKit.UIScrollViewDelegate","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","type":"unresolvable","title":"Foundation.NSCoding"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/init(frame:mention:showType:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mention"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showType"},{"text":": ","kind":"text"},{"text":"MessageListType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageListType"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Init method","type":"text"}],"url":"\/documentation\/easechatuikit\/messagelistview\/init(frame:mention:showtype:)","role":"symbol","navigatorTitle":[{"text":"initWithFrame:mention:showType:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(frame:mention:showType:)","title":"init(frame:mention:showType:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/IMessageListViewDriver-Implementations":{"title":"IMessageListViewDriver Implementations","url":"\/documentation\/easechatuikit\/messagelistview\/imessagelistviewdriver-implementations","abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/showType":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/showType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"showType","kind":"identifier"},{"kind":"text","text":": "},{"text":"MessageListType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageListType"}],"url":"\/documentation\/easechatuikit\/messagelistview\/showtype","role":"symbol","abstract":[],"title":"showType","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/refreshPreviewResult(entity:)":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"refreshPreviewResultWithEntity:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshPreviewResult(entity:)","title":"refreshPreviewResult(entity:)","url":"\/documentation\/easechatuikit\/messagelistview\/refreshpreviewresult(entity:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refreshPreviewResult","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"role":"symbol","url":"\/documentation\/easechatuikit\/themeswitchprotocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","title":"ThemeSwitchProtocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/replyBar":{"url":"\/documentation\/easechatuikit\/messagelistview\/replybar","title":"replyBar","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replyBar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputReplyView","kind":"typeIdentifier","text":"MessageInputReplyView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/replyBar","kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/editBottomBar":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"editBottomBar"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageMultiSelectedBottomBar","text":"MessageMultiSelectedBottomBar"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/editBottomBar","url":"\/documentation\/easechatuikit\/messagelistview\/editbottombar","title":"editBottomBar","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICoordinateSpace":{"title":"UIKit.UICoordinateSpace","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/editMode":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"editMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/editMode","title":"editMode","url":"\/documentation\/easechatuikit\/messagelistview\/editmode","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/init(frame:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(frame:)","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":")"}],"url":"\/documentation\/easechatuikit\/messagelistview\/init(frame:)","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/removeEventHandler(actionHandler:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"removeEventHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageListViewActionEventsDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeEventHandlerWithActionHandler:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelistview\/removeeventhandler(actionhandler:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/removeEventHandler(actionHandler:)","abstract":[{"text":"Remove UI action handler.","type":"text"}],"type":"topic","title":"removeEventHandler(actionHandler:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/threadMessagesLoadFinished":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threadMessagesLoadFinished"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"threadMessagesLoadFinished","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistview\/threadmessagesloadfinished","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/threadMessagesLoadFinished"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/inputBar":{"role":"symbol","abstract":[],"type":"topic","kind":"symbol","title":"inputBar","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"inputBar","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageInputBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputBar"}],"url":"\/documentation\/easechatuikit\/messagelistview\/inputbar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/inputBar"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItemContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","type":"unresolvable","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/messageList":{"role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistview\/messagelist","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/messageList","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageList"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"}],"title":"messageList"},"doc://org.cocoapods.EaseChatUIKit/s8CopyableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/UITableViewDataSource-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","url":"\/documentation\/easechatuikit\/messagelistview\/uitableviewdatasource-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/UITableViewDataSource-Implementations","title":"UITableViewDataSource Implementations","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/ThemeSwitchProtocol-Implementations":{"abstract":[],"kind":"article","title":"ThemeSwitchProtocol Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/easechatuikit\/messagelistview\/themeswitchprotocol-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/ThemeSwitchProtocol-Implementations"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearance":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","type":"unresolvable","title":"UIKit.UIAppearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/scrollViewDidEndDecelerating(_:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollViewDidEndDecelerating(_:)","url":"\/documentation\/easechatuikit\/messagelistview\/scrollviewdidenddecelerating(_:)","title":"scrollViewDidEndDecelerating(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView","type":"unresolvable","title":"UIView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/addActionHandler(actionHandler:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"text":"MessageListViewActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addActionHandler(actionHandler:)","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"title":"addActionHandler(actionHandler:)","url":"\/documentation\/easechatuikit\/messagelistview\/addactionhandler(actionhandler:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Add UI actions handler."}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDataSource":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","type":"unresolvable","title":"UITableViewDataSource"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate","type":"unresolvable","title":"UITableViewDelegate"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/UITableViewDelegate-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistview\/uitableviewdelegate-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/UITableViewDelegate-Implementations","title":"UITableViewDelegate Implementations","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/scrollToBottom()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"scrollToBottom"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollToBottom()","navigatorTitle":[{"text":"scrollToBottom","kind":"identifier"}],"title":"scrollToBottom()","url":"\/documentation\/easechatuikit\/messagelistview\/scrolltobottom()","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/messages":{"type":"topic","role":"symbol","kind":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistview\/messages","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messages"},{"kind":"text","text":": ["},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/messages","title":"messages"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/init(coder:)":{"url":"\/documentation\/easechatuikit\/messagelistview\/init(coder:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(coder:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"title":"init(coder:)","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/moreMessages":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreMessages"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIButton","text":"UIButton","kind":"typeIdentifier"}],"title":"moreMessages","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/moreMessages","type":"topic","url":"\/documentation\/easechatuikit\/messagelistview\/moremessages"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MessageListView"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageListView"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"MessageListView","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(frame:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/init(frame:mention:showType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshPreviewResult(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/removeEventHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollTableViewToBottom()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollToBottom()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrollViewDidEndDecelerating(_:)"],"generated":true},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/UITableViewDelegate-Implementations"],"title":"Default Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIView"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListView","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrollTableViewToBottom()\/title","value":"scrollTableViewToBottom","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrollTableViewToBottom()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollTableViewToBottom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title","value":"MessageListView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments","value":[{"text":"MessageListView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListView"}]},{"value":"IMessageListViewDriver","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/fragments","op":"replace","value":[{"text":"IMessageListViewDriver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/navigatorTitle","value":[{"kind":"identifier","text":"IMessageListViewDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1init(frame:mention:showType:)\/title","value":"initWithFrame:mention:showType:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:mention:showType:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1init(frame:mention:showType:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1refreshPreviewResult(entity:)\/title","op":"replace","value":"refreshPreviewResultWithEntity:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1refreshPreviewResult(entity:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshPreviewResultWithEntity:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title","value":"ThemeSwitchProtocol"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments","op":"replace","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1init(frame:)\/title","op":"replace","value":"initWithFrame:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithFrame:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1init(frame:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1removeEventHandler(actionHandler:)\/title","value":"removeEventHandlerWithActionHandler:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1removeEventHandler(actionHandler:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrollViewDidEndDecelerating(_:)\/title","op":"replace","value":"scrollViewDidEndDecelerating:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrollViewDidEndDecelerating(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}]},{"value":"addActionHandlerWithActionHandler:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1addActionHandler(actionHandler:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1addActionHandler(actionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrollToBottom()\/title","value":"scrollToBottom","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scrollToBottom","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrollToBottom()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1init(coder:)\/title","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1init(coder:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}