{"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/actionSheet","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/withArrow"],"generated":true},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/init(rawValue:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"sections":[],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageLongPressMenuStyle"}],"roleHeading":"Enumeration","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenuStyle"}],"externalID":"c:@M@EaseChatUIKit@E@MessageLongPressMenuStyle","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"title":"MessageLongPressMenuStyle"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelongpressmenustyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelongpressmenustyle"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenuStyle":{"title":"MessageLongPressMenuStyle","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageLongPressMenuStyle"}],"navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenuStyle"}],"url":"\/documentation\/easechatuikit\/messagelongpressmenustyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenuStyle/init(rawValue:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/init(rawValue:)","url":"\/documentation\/easechatuikit\/messagelongpressmenustyle\/init(rawvalue:)","title":"init(rawValue:)","abstract":[],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenuStyle/withArrow":{"type":"topic","url":"\/documentation\/easechatuikit\/messagelongpressmenustyle\/witharrow","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/withArrow","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenuStyleWithArrow"}],"title":"MessageLongPressMenuStyle.withArrow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"withArrow","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenuStyle/Equatable-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/easechatuikit\/messagelongpressmenustyle\/equatable-implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenuStyle/actionSheet":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/actionSheet","title":"MessageLongPressMenuStyle.actionSheet","kind":"symbol","url":"\/documentation\/easechatuikit\/messagelongpressmenustyle\/actionsheet","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"actionSheet","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenuStyleActionSheet"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenuStyle/RawRepresentable-Implementations":{"type":"topic","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/easechatuikit\/messagelongpressmenustyle\/rawrepresentable-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/RawRepresentable-Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"MessageLongPressMenuStyle","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/actionSheet","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenuStyle\/withArrow"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageLongPressMenuStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t","text":"uint8_t"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"MessageLongPressMenuStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle\/fragments","value":[{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"MessageLongPressMenuStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle~1withArrow\/title","value":"MessageLongPressMenuStyleWithArrow","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle~1withArrow\/fragments","value":[{"text":"MessageLongPressMenuStyleWithArrow","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle~1actionSheet\/title","value":"MessageLongPressMenuStyleActionSheet"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenuStyle~1actionSheet\/fragments","value":[{"text":"MessageLongPressMenuStyleActionSheet","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}