{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageListType","kind":"identifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType"},"sections":[],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/history","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/normal","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/thread"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/RawRepresentable-Implementations"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelisttype"]},{"paths":["\/documentation\/easechatuikit\/messagelisttype"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"MessageListType","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Enumeration","role":"symbol","navigatorTitle":[{"text":"MessageListType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListType"}],"externalID":"c:@M@EaseChatUIKit@E@MessageListType","symbolKind":"enum"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"type":"conformsTo"}],"references":{"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType/normal":{"url":"\/documentation\/easechatuikit\/messagelisttype\/normal","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/normal","title":"MessageListType.normal","abstract":[],"role":"symbol","navigatorTitle":[{"text":"MessageListTypeNormal","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normal"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType/Equatable-Implementations":{"url":"\/documentation\/easechatuikit\/messagelisttype\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType/thread":{"role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/messagelisttype\/thread","navigatorTitle":[{"kind":"identifier","text":"MessageListTypeThread"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/thread","title":"MessageListType.thread","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"thread"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/easechatuikit\/messagelisttype\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType/history":{"url":"\/documentation\/easechatuikit\/messagelisttype\/history","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/history","title":"MessageListType.history","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListTypeHistory"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"history"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType":{"title":"MessageListType","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListType"}],"url":"\/documentation\/easechatuikit\/messagelisttype","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType","navigatorTitle":[{"kind":"identifier","text":"MessageListType"}]},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType/init(rawValue:)":{"url":"\/documentation\/easechatuikit\/messagelisttype\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"MessageListType","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"MessageListType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MessageListType","kind":"identifier"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/history","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/normal","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/thread"]}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier","text":"uint8_t"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MessageListTypeNormal","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1normal\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1normal\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageListTypeNormal"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1thread\/title","op":"replace","value":"MessageListTypeThread"},{"value":[{"kind":"identifier","text":"MessageListTypeThread"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1thread\/fragments","op":"replace"},{"value":"MessageListTypeHistory","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1history\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1history\/fragments","value":[{"text":"MessageListTypeHistory","kind":"identifier"}]},{"op":"replace","value":"MessageListType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType\/title"},{"value":[{"text":"MessageListType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType\/fragments"}]}]}