{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecellclickarea"]},{"paths":["\/documentation\/easechatuikit\/messagecellclickarea"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Enum representing the different areas that can be clicked in a message cell.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Enumeration","externalID":"c:@M@EaseChatUIKit@E@MessageCellClickArea","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"MessageCellClickArea","kind":"identifier"}],"symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCellClickArea","kind":"identifier"}],"role":"symbol","title":"MessageCellClickArea"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea"},"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/avatar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/bubble","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/cell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/checkbox","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/reaction","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/reply","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/status","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/topic"],"generated":true,"title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/RawRepresentable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCellClickArea","kind":"identifier"}],"platforms":["iOS"]}]}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/cell":{"url":"\/documentation\/easechatuikit\/messagecellclickarea\/cell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/cell","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cell","kind":"identifier"}],"title":"MessageCellClickArea.cell","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageCellClickAreaCell","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea":{"navigatorTitle":[{"kind":"identifier","text":"MessageCellClickArea"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageCellClickArea","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Enum representing the different areas that can be clicked in a message cell."}],"title":"MessageCellClickArea","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea","url":"\/documentation\/easechatuikit\/messagecellclickarea","kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagecellclickarea\/init(rawvalue:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/status":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagecellclickarea\/status","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaStatus"}],"title":"MessageCellClickArea.status","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/status"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/RawRepresentable-Implementations":{"kind":"article","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/messagecellclickarea\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/RawRepresentable-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/reaction":{"url":"\/documentation\/easechatuikit\/messagecellclickarea\/reaction","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/reaction","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reaction","kind":"identifier"}],"title":"MessageCellClickArea.reaction","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageCellClickAreaReaction","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/reply":{"url":"\/documentation\/easechatuikit\/messagecellclickarea\/reply","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/reply","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"}],"title":"MessageCellClickArea.reply","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaReply"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/avatar":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagecellclickarea\/avatar","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"}],"navigatorTitle":[{"text":"MessageCellClickAreaAvatar","kind":"identifier"}],"title":"MessageCellClickArea.avatar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/avatar"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/bubble":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bubble"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/bubble","role":"symbol","url":"\/documentation\/easechatuikit\/messagecellclickarea\/bubble","title":"MessageCellClickArea.bubble","abstract":[],"navigatorTitle":[{"text":"MessageCellClickAreaBubble","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/checkbox":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagecellclickarea\/checkbox","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkbox","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaCheckbox"}],"title":"MessageCellClickArea.checkbox","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/checkbox"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/topic":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/topic","url":"\/documentation\/easechatuikit\/messagecellclickarea\/topic","navigatorTitle":[{"text":"MessageCellClickAreaTopic","kind":"identifier"}],"title":"MessageCellClickArea.topic","type":"topic","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topic"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/easechatuikit\/messagecellclickarea\/equatable-implementations","abstract":[],"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/Equatable-Implementations"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"MessageCellClickArea","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"MessageCellClickArea","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MessageCellClickArea","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/avatar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/bubble","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/cell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/checkbox","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/reaction","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/reply","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/status","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/topic"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageCellClickArea","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MessageCellClickAreaCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1cell\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1cell\/fragments","op":"replace","value":[{"text":"MessageCellClickAreaCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/title","value":"MessageCellClickArea"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/fragments","value":[{"text":"MessageCellClickArea","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MessageCellClickArea"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1status\/title","value":"MessageCellClickAreaStatus"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1status\/fragments","value":[{"text":"MessageCellClickAreaStatus","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1reaction\/title","value":"MessageCellClickAreaReaction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1reaction\/fragments","value":[{"text":"MessageCellClickAreaReaction","kind":"identifier"}]},{"value":"MessageCellClickAreaReply","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1reply\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1reply\/fragments","value":[{"kind":"identifier","text":"MessageCellClickAreaReply"}]},{"value":"MessageCellClickAreaAvatar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1avatar\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1avatar\/fragments","op":"replace","value":[{"text":"MessageCellClickAreaAvatar","kind":"identifier"}]},{"op":"replace","value":"MessageCellClickAreaBubble","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1bubble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCellClickAreaBubble"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1bubble\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1checkbox\/title","op":"replace","value":"MessageCellClickAreaCheckbox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1checkbox\/fragments","value":[{"text":"MessageCellClickAreaCheckbox","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1topic\/title","value":"MessageCellClickAreaTopic"},{"value":[{"text":"MessageCellClickAreaTopic","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1topic\/fragments"}]}]}