{"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/copy","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/createTopic","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/delete","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/edit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/forward","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/multiSelect","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/originalText","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/recall","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/reply","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/translate"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/init(rawValue:)"],"title":"Initializers"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/RawRepresentable-Implementations"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation"},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageOperation","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easechatuikit\/messageoperation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messageoperation"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageOperation","kind":"identifier"}],"symbolKind":"enum","role":"symbol","title":"MessageOperation","navigatorTitle":[{"text":"MessageOperation","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@E@MessageOperation","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Enumeration"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/createTopic":{"role":"symbol","title":"MessageOperation.createTopic","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageOperationCreateTopic"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/createTopic","url":"\/documentation\/easechatuikit\/messageoperation\/createtopic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createTopic","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/init(rawValue:)":{"kind":"symbol","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/init(rawValue:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/messageoperation\/init(rawvalue:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/reply":{"abstract":[],"url":"\/documentation\/easechatuikit\/messageoperation\/reply","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageOperationReply"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reply","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/reply","title":"MessageOperation.reply","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/forward":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/forward","url":"\/documentation\/easechatuikit\/messageoperation\/forward","abstract":[],"navigatorTitle":[{"text":"MessageOperationForward","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"forward"}],"type":"topic","kind":"symbol","title":"MessageOperation.forward"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation":{"role":"symbol","title":"MessageOperation","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageOperation"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation","url":"\/documentation\/easechatuikit\/messageoperation","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageOperation","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/originalText":{"navigatorTitle":[{"text":"MessageOperationOriginalText","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/originalText","kind":"symbol","role":"symbol","title":"MessageOperation.originalText","url":"\/documentation\/easechatuikit\/messageoperation\/originaltext","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"originalText","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/copy":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"copy","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/copy","navigatorTitle":[{"kind":"identifier","text":"MessageOperationCopy"}],"url":"\/documentation\/easechatuikit\/messageoperation\/copy","type":"topic","title":"MessageOperation.copy","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","url":"\/documentation\/easechatuikit\/messageoperation\/equatable-implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/Equatable-Implementations","role":"collectionGroup","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/multiSelect":{"url":"\/documentation\/easechatuikit\/messageoperation\/multiselect","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/multiSelect","title":"MessageOperation.multiSelect","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiSelect"}],"navigatorTitle":[{"kind":"identifier","text":"MessageOperationMultiSelect"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/delete":{"role":"symbol","navigatorTitle":[{"text":"MessageOperationDelete","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/delete","abstract":[],"url":"\/documentation\/easechatuikit\/messageoperation\/delete","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"}],"title":"MessageOperation.delete"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/recall":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/recall","abstract":[],"url":"\/documentation\/easechatuikit\/messageoperation\/recall","navigatorTitle":[{"kind":"identifier","text":"MessageOperationRecall"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"recall","kind":"identifier"}],"kind":"symbol","type":"topic","title":"MessageOperation.recall"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/edit":{"abstract":[],"url":"\/documentation\/easechatuikit\/messageoperation\/edit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"edit","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/edit","title":"MessageOperation.edit","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageOperationEdit"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/RawRepresentable-Implementations":{"kind":"article","abstract":[],"title":"RawRepresentable Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/RawRepresentable-Implementations","url":"\/documentation\/easechatuikit\/messageoperation\/rawrepresentable-implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/translate":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"translate","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messageoperation\/translate","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/translate","role":"symbol","kind":"symbol","title":"MessageOperation.translate","type":"topic","navigatorTitle":[{"text":"MessageOperationTranslate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"MessageOperation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","value":[{"text":"MessageOperation","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"MessageOperation","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/copy","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/createTopic","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/delete","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/edit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/forward","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/multiSelect","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/originalText","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/recall","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/reply","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/translate"]}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageOperation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1createTopic\/title","value":"MessageOperationCreateTopic","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1createTopic\/fragments","value":[{"kind":"identifier","text":"MessageOperationCreateTopic"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1reply\/title","value":"MessageOperationReply","op":"replace"},{"value":[{"text":"MessageOperationReply","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1reply\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1forward\/title","value":"MessageOperationForward","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1forward\/fragments","value":[{"text":"MessageOperationForward","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/title","op":"replace","value":"MessageOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/fragments","value":[{"text":"MessageOperation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1originalText\/title","op":"replace","value":"MessageOperationOriginalText"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1originalText\/fragments","op":"replace","value":[{"text":"MessageOperationOriginalText","kind":"identifier"}]},{"value":"MessageOperationCopy","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1copy\/title"},{"value":[{"kind":"identifier","text":"MessageOperationCopy"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1copy\/fragments","op":"replace"},{"value":"MessageOperationMultiSelect","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1multiSelect\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1multiSelect\/fragments","value":[{"text":"MessageOperationMultiSelect","kind":"identifier"}],"op":"replace"},{"value":"MessageOperationDelete","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1delete\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1delete\/fragments","value":[{"text":"MessageOperationDelete","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1recall\/title","op":"replace","value":"MessageOperationRecall"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1recall\/fragments","op":"replace","value":[{"text":"MessageOperationRecall","kind":"identifier"}]},{"value":"MessageOperationEdit","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1edit\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1edit\/fragments","op":"replace","value":[{"text":"MessageOperationEdit","kind":"identifier"}]},{"value":"MessageOperationTranslate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1translate\/title"},{"value":[{"text":"MessageOperationTranslate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1translate\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}