{"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onChatThreadUpdated(chatThread:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageAttachmentLoading(loading:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageBubbleLongPressed(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMoreReactionAreaClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageTopicAreaClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageWillSendFillExtensionInfo()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onUserQuitTopic()"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistdrivereventslistener"]},{"paths":["\/documentation\/easechatuikit\/messagelistdrivereventslistener"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListDriverEventsListener"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener","roleHeading":"Protocol","role":"symbol","title":"MessageListDriverEventsListener","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListDriverEventsListener","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListDriverEventsListener"}]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListDriverEventsListener"}],"url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener","navigatorTitle":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"kind":"symbol","title":"MessageListDriverEventsListener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onChatThreadUpdated(chatThread:)":{"navigatorTitle":[{"kind":"identifier","text":"onChatThreadUpdatedWithChatThread:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onChatThreadUpdated(chatThread:)","kind":"symbol","role":"symbol","title":"onChatThreadUpdated(chatThread:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onchatthreadupdated(chatthread:)","required":true,"type":"topic","abstract":[{"type":"text","text":"You can update chat thread on the method called."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onChatThreadUpdated","kind":"identifier"},{"kind":"text","text":"("},{"text":"chatThread","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChatThread","preciseIdentifier":"s:13EaseChatUIKit05GroupB6Threada"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageTopicAreaClicked(entity:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageTopicAreaClickedWithEntity:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageTopicAreaClicked(entity:)","kind":"symbol","role":"symbol","title":"onMessageTopicAreaClicked(entity:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagetopicareaclicked(entity:)","type":"topic","abstract":[{"type":"text","text":"When you click a message’s topic area ,the method will call."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageTopicAreaClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageWillSendFillExtensionInfo()":{"role":"symbol","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagewillsendfillextensioninfo()","navigatorTitle":[{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Insert extension info before sending message.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageWillSendFillExtensionInfo","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Dictionary","preciseIdentifier":"s:SD","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":">","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageWillSendFillExtensionInfo()","title":"onMessageWillSendFillExtensionInfo()","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageBubbleClicked(message:)":{"title":"onMessageBubbleClicked(message:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"onMessageBubbleClickedWithMessage:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageBubbleClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"abstract":[],"required":true,"url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagebubbleclicked(message:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageBubbleClicked(message:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","type":"topic","abstract":[],"title":"MessageListController","url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageMoreReactionAreaClicked(entity:)":{"title":"onMessageMoreReactionAreaClicked(entity:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMoreReactionAreaClicked(entity:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagemorereactionareaclicked(entity:)","kind":"symbol","navigatorTitle":[{"text":"onMessageMoreReactionAreaClickedWithEntity:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageMoreReactionAreaClicked"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","text":"MessageEntity"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"type":"text","text":"When you click a message’s reaction ,the method will call."}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"type":"topic","title":"ChatThreadViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onInputBoxEventsOccur(action:attributeText:)":{"navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onInputBoxEventsOccur(action:attributeText:)","kind":"symbol","role":"symbol","title":"onInputBoxEventsOccur(action:attributeText:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/oninputboxeventsoccur(action:attributetext:)","required":true,"type":"topic","abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageMultiSelectBarClicked(operation:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMultiSelectBarClicked(operation:)","kind":"symbol","role":"symbol","title":"onMessageMultiSelectBarClicked(operation:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagemultiselectbarclicked(operation:)","required":true,"type":"topic","abstract":[{"type":"text","text":"When you click a message list multi select bar item,the method will call."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController":{"role":"symbol","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller","navigatorTitle":[{"text":"SearchResultMessagesController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController","title":"SearchResultMessagesController","kind":"symbol","abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SearchResultMessagesController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageAttachmentLoading(loading:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageAttachmentLoadingWithLoading:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageAttachmentLoading(loading:)","kind":"symbol","role":"symbol","title":"onMessageAttachmentLoading(loading:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessageattachmentloading(loading:)","required":true,"type":"topic","abstract":[{"type":"text","text":"When you click a attachment message,we’ll download the attachment,the method also called."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageAttachmentLoading","kind":"identifier"},{"kind":"text","text":"("},{"text":"loading","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onUserQuitTopic()":{"abstract":[{"text":"When received quit signal form other device on the chat thread.","type":"text"}],"url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onuserquittopic()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onUserQuitTopic()","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"onUserQuitTopic","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserQuitTopic","kind":"identifier"},{"kind":"text","text":"()"}],"title":"onUserQuitTopic()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageAvatarClicked(user:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageAvatarClickedWithUser:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageAvatarClicked(user:)","kind":"symbol","role":"symbol","title":"onMessageAvatarClicked(user:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessageavatarclicked(user:)","required":true,"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"user"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageBubbleLongPressed(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageBubbleLongPressedWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageBubbleLongPressed(message:)","kind":"symbol","role":"symbol","title":"onMessageBubbleLongPressed(message:)","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagebubblelongpressed(message:)","required":true,"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageBubbleLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"MessageListDriverEventsListener","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onChatThreadUpdated(chatThread:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onInputBoxEventsOccur(action:attributeText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageAttachmentLoading(loading:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageBubbleLongPressed(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMoreReactionAreaClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMultiSelectBarClicked(operation:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageTopicAreaClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageWillSendFillExtensionInfo()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onUserQuitTopic()"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"],"title":"Conforming Types","kind":"relationships","type":"conformingTypes"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListDriverEventsListener","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/title","value":"MessageListDriverEventsListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/fragments","value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onChatThreadUpdated(chatThread:)\/title","value":"onChatThreadUpdatedWithChatThread:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onChatThreadUpdated(chatThread:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onChatThreadUpdatedWithChatThread:","kind":"identifier"}]},{"value":"onMessageTopicAreaClickedWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageTopicAreaClicked(entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageTopicAreaClicked(entity:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageTopicAreaClickedWithEntity:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageWillSendFillExtensionInfo()\/title","value":"onMessageWillSendFillExtensionInfo"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageWillSendFillExtensionInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageWillSendFillExtensionInfo()\/fragments"},{"value":"onMessageBubbleClickedWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageBubbleClicked(message:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageBubbleClickedWithMessage:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageBubbleClicked(message:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"kind":"identifier","text":"MessageListController"}]},{"value":"onMessageMoreReactionAreaClickedWithEntity:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageMoreReactionAreaClicked(entity:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageMoreReactionAreaClicked(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageMoreReactionAreaClickedWithEntity:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments","value":[{"kind":"identifier","text":"ChatThreadViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onInputBoxEventsOccur(action:attributeText:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageMultiSelectBarClicked(operation:)\/title","op":"replace","value":"onMessageMultiSelectBarClickedWithOperation:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageMultiSelectBarClicked(operation:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/title","value":"SearchResultMessagesController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/fragments","value":[{"text":"SearchResultMessagesController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageAttachmentLoading(loading:)\/title","value":"onMessageAttachmentLoadingWithLoading:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageAttachmentLoading(loading:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageAttachmentLoadingWithLoading:"}],"op":"replace"},{"value":"onUserQuitTopic","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onUserQuitTopic()\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onUserQuitTopic"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onUserQuitTopic()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageAvatarClicked(user:)\/title","value":"onMessageAvatarClickedWithUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageAvatarClicked(user:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClickedWithUser:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageBubbleLongPressed(message:)\/title","value":"onMessageBubbleLongPressedWithMessage:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageBubbleLongPressed(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageBubbleLongPressedWithMessage:"}],"op":"replace"}]}]}