{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/init(conversationId:type:)"],"title":"Initializers"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/chatService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/chatType","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/driver","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/groupService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/mentionIds","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/multiService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/searchMessageId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/to"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/addEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/audioMessagePlay(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/bindDriver(driver:searchMessageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/cacheFrame(attachMessage:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/cacheImage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/constructMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/copyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/deleteMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/deleteMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/downloadMessageAttachment(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/editMessage(message:content:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/loadMessages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/loadSearchMessage()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageStatusChanged(message:status:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageTopicClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageVisibleMark(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/notifyUnreadCountChanged()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/operationReaction(emoji:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/processInputEvents(action:attributeText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/processMessage(operation:message:edit:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/recallAction(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/recallMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/removeEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/replyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/retrySendMessage(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/sendMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/showOriginalText(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/translateMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/updateMentionIds(profile:type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/willSendMessage(attributeText:)"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupChatThreadEventListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupServiceListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MultiDeviceListener-Implementations"],"generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"symbolKind":"class","role":"symbol","roleHeading":"Class","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageListViewModel","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}],"title":"MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageListViewModel","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListViewModel","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel"]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/to":{"role":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/to","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/to","abstract":[],"title":"to","navigatorTitle":[{"kind":"identifier","text":"to"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"to","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onMessageBubbleClicked(message:)":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagebubbleclicked(message:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageBubbleClicked(message:)","title":"onMessageBubbleClicked(message:)","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageBubbleClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onMessageBubbleClickedWithMessage:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/ChatResponseListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations","kind":"article","title":"ChatResponseListener Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/chatresponselistener-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageDidReceived(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidReceived(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagedidreceived(message:)","abstract":[{"text":"Handles the received message and performs necessary actions based on the message type.","type":"text"}],"navigatorTitle":[{"text":"messageDidReceivedWithMessage:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"messageDidReceived(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageStatusChanged(message:status:error:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageStatusChanged(message:status:error:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageStatusChangedWithMessage:status:error:"}],"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagestatuschanged(message:status:error:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageStatusChanged"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"text":"ChatMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"text":"?)","kind":"text"}],"abstract":[{"text":"Notifies the message list view model when the status of a chat message has changed.","type":"text"}],"title":"messageStatusChanged(message:status:error:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/GroupServiceListener-Implementations":{"role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupServiceListener-Implementations","type":"topic","abstract":[],"title":"GroupServiceListener Implementations","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/groupservicelistener-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageDidRecalled(recallInfo:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidRecalled(recallInfo:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagedidrecalled(recallinfo:)","abstract":[{"type":"text","text":"Handles the event when a message is recalled."}],"navigatorTitle":[{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"messageDidRecalled(recallInfo:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/searchMessageId":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/searchMessageId","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/searchmessageid","abstract":[],"navigatorTitle":[{"text":"searchMessageId","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"searchMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","title":"searchMessageId"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/recallMessage(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/recallMessage(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/recallmessage(message:)","abstract":[],"navigatorTitle":[{"text":"recallMessageWithMessage:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recallMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"recallMessage(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/sendMessage(text:type:extensionInfo:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/sendMessage(text:type:extensionInfo:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/sendmessage(text:type:extensioninfo:)","abstract":[{"text":"Send message with text&type&extension info.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sendMessageWithText:type:extensionInfo:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sendMessage","kind":"identifier"},{"kind":"text","text":"("},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageCellStyle","text":"MessageCellStyle","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extensionInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"keyword","text":"Any"},{"text":">)","kind":"text"}],"kind":"symbol","type":"topic","title":"sendMessage(text:type:extensionInfo:)"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/loadSearchMessage()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/loadSearchMessage()","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/loadsearchmessage()","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"loadSearchMessage"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadSearchMessage"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","title":"loadSearchMessage()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/deleteMessages(messages:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/deleteMessages(messages:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/deletemessages(messages:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"deleteMessagesWithMessages:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMessages"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"])"}],"type":"topic","kind":"symbol","title":"deleteMessages(messages:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/deleteMessage(message:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/deleteMessage(message:)","navigatorTitle":[{"kind":"identifier","text":"deleteMessageWithMessage:"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/deletemessage(message:)","type":"topic","title":"deleteMessage(message:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/audioMessagePlay(message:)":{"abstract":[],"role":"symbol","title":"audioMessagePlay(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/audiomessageplay(message:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioMessagePlay","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/audioMessagePlay(message:)","navigatorTitle":[{"text":"audioMessagePlayWithMessage:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/chatService":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/chatService","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/chatservice","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"chatService"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"chatService"},{"kind":"text","text":": "},{"text":"ChatService","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatService"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","title":"chatService"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/showOriginalText(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/showOriginalText(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/showoriginaltext(message:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"showOriginalTextWithMessage:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showOriginalText"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"showOriginalText(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageVisibleMark(entity:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageVisibleMark(entity:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagevisiblemark(entity:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"messageVisibleMarkWithEntity:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageVisibleMark"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"messageVisibleMark(entity:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/imessagelistviewdriver","title":"IMessageListViewDriver","kind":"symbol","type":"topic","navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IMessageListViewDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/editMessage(message:content:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/editMessage(message:content:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/editmessage(message:content:)","abstract":[],"navigatorTitle":[{"text":"editMessageWithMessage:content:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"editMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"editMessage(message:content:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/updateMentionIds(profile:type:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/updateMentionIds(profile:type:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/updatementionids(profile:type:)","abstract":[{"type":"text","text":"When you mention somebody update mention user id array."}],"navigatorTitle":[{"text":"updateMentionIdsWithProfile:type:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateMentionIds"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MentionUpdate","preciseIdentifier":"c:@M@EaseChatUIKit@E@MentionUpdate"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"updateMentionIds(profile:type:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageDidEdited(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidEdited(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagedidedited(message:)","abstract":[{"text":"Notifies the view model that a message has been edited.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"messageDidEditedWithMessage:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageDidEdited"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"messageDidEdited(message:)"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageTopicClicked(entity:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageTopicClicked(entity:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagetopicclicked(entity:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"messageTopicClickedWithEntity:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageTopicClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"messageTopicClicked(entity:)"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/MultiDeviceListener-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MultiDeviceListener-Implementations","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/multidevicelistener-implementations","abstract":[],"kind":"article","type":"topic","title":"MultiDeviceListener Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/cacheImage(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/cacheImage(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/cacheimage(message:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"cacheImageWithMessage:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cacheImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"cacheImage(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/recallAction(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/recallAction(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/recallaction(message:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"recallActionWithMessage:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recallAction"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"recallAction(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatresponselistener","type":"topic","title":"ChatResponseListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatResponseListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatResponseListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/driver":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/driver","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/driver","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"driver"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IMessageListViewDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","title":"driver"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventListener":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/groupchatthreadeventlistener","title":"GroupChatThreadEventListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEventListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/loadMessages()":{"kind":"symbol","title":"loadMessages()","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/loadMessages()","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/loadmessages()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadMessages"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"loadMessages","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"type":"topic","abstract":[],"title":"GroupServiceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupServiceListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","url":"\/documentation\/easechatuikit\/groupservicelistener","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/notifyUnreadCountChanged()":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/notifyUnreadCountChanged()","kind":"symbol","title":"notifyUnreadCountChanged()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"notifyUnreadCountChanged","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/notifyunreadcountchanged()","navigatorTitle":[{"text":"notifyUnreadCountChanged","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/retrySendMessage(entity:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/retrySendMessage(entity:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/retrysendmessage(entity:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"retrySendMessageWithEntity:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"retrySendMessage"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"retrySendMessage(entity:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageReactionClicked(reaction:entity:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionClicked(reaction:entity:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagereactionclicked(reaction:entity:)","abstract":[],"navigatorTitle":[{"text":"messageReactionClickedWithReaction:entity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"reaction"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageReaction","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"messageReactionClicked(reaction:entity:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageReactionChanged(changes:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionChanged(changes:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagereactionchanged(changes:)","abstract":[],"navigatorTitle":[{"text":"messageReactionChangedWithChanges:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageReactionChanged","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageReactionChange","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"kind":"text","text":"])"}],"kind":"symbol","type":"topic","title":"messageReactionChanged(changes:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/addEventsListener(_:)":{"navigatorTitle":[{"kind":"identifier","text":"addEventsListener:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/addEventsListener(_:)","kind":"symbol","role":"symbol","title":"addEventsListener(_:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/addeventslistener(_:)","type":"topic","abstract":[{"text":"Add events listener of the message list.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener","text":"MessageListDriverEventsListener","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/downloadMessageAttachment(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/downloadMessageAttachment(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/downloadmessageattachment(message:)","abstract":[],"navigatorTitle":[{"text":"downloadMessageAttachmentWithMessage:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadMessageAttachment"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"downloadMessageAttachment(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/multiService":{"title":"multiService","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"multiService"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/multiService","type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/multiservice","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"multiService","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceService","kind":"typeIdentifier","text":"MultiDeviceService"},{"text":"?","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/groupService":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupService"},{"text":": ","kind":"text"},{"text":"GroupService","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupService"},{"text":"?","kind":"text"}],"role":"symbol","title":"groupService","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/groupservice","navigatorTitle":[{"kind":"identifier","text":"groupService"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/groupService"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageAvatarLongPressed(profile:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageAvatarLongPressed(profile:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messageavatarlongpressed(profile:)","abstract":[],"navigatorTitle":[{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageAvatarLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"messageAvatarLongPressed(profile:)"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/translateMessage(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/translateMessage(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/translatemessage(message:)","abstract":[],"navigatorTitle":[{"text":"translateMessageWithMessage:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"translateMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"translateMessage(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"kind":"symbol","title":"MessageListViewModel","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","url":"\/documentation\/easechatuikit\/messagelistviewmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"text":"MessageListViewModel","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceListener":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","title":"MultiDeviceListener","url":"\/documentation\/easechatuikit\/multidevicelistener","role":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/chatType":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/chatType","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/chattype","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"chatType"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"chatType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType"}],"type":"topic","kind":"symbol","title":"chatType"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/cacheFrame(attachMessage:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/cacheFrame(attachMessage:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/cacheframe(attachmessage:)","abstract":[],"navigatorTitle":[{"text":"cacheFrameWithAttachMessage:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cacheFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"attachMessage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","title":"cacheFrame(attachMessage:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/bindDriver(driver:searchMessageId:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/bindDriver(driver:searchMessageId:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/binddriver(driver:searchmessageid:)","abstract":[{"text":"Bind ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","isActive":true,"type":"reference"}],"navigatorTitle":[{"text":"bindWithDriver:searchMessageId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindDriver","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"text":"IMessageListViewDriver","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver"},{"kind":"text","text":", "},{"kind":"externalParam","text":"searchMessageId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"bindDriver(driver:searchMessageId:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/mentionIds":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/mentionIds","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/mentionids","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"mentionIds"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"mentionIds","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"kind":"symbol","type":"topic","title":"mentionIds"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/MessageListViewActionEventsDelegate-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","kind":"article","title":"MessageListViewActionEventsDelegate Implementations","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewActionEventsDelegate":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate","title":"MessageListViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/operationReaction(emoji:message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/operationReaction(emoji:message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/operationreaction(emoji:message:)","abstract":[],"navigatorTitle":[{"text":"operationReactionWithEmoji:message:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"operationReaction"},{"text":"(","kind":"text"},{"text":"emoji","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"operationReaction(emoji:message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageAttachmentStatusChanged(message:error:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageAttachmentStatusChanged(message:error:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messageattachmentstatuschanged(message:error:)","abstract":[{"text":"Handles the change in attachment status of a chat message.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"messageAttachmentStatusChangedWithMessage:error:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageAttachmentStatusChanged","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","title":"messageAttachmentStatusChanged(message:error:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/init(conversationId:type:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/init(conversationId:type:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/init(conversationid:type:)","abstract":[],"navigatorTitle":[{"text":"initWithConversationId:type:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"init(conversationId:type:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/processInputEvents(action:attributeText:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/processInputEvents(action:attributeText:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/processinputevents(action:attributetext:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"processInputEventsWithAction:attributeText:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"processInputEvents"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","text":"MessageInputBarActionType"},{"kind":"text","text":", "},{"text":"attributeText","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","type":"topic","title":"processInputEvents(action:attributeText:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/removeEventsListener(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/removeEventsListener(_:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/removeeventslistener(_:)","abstract":[{"type":"text","text":"Remove events listener of the message list."}],"navigatorTitle":[{"text":"removeEventsListener:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener","text":"MessageListDriverEventsListener"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"removeEventsListener(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/copyMessage(message:)":{"role":"symbol","abstract":[],"title":"copyMessage(message:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"copyMessageWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/copyMessage(message:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"copyMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/copymessage(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/replyMessage(message:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/replyMessage(message:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/replymessage(message:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"replyMessageWithMessage:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"replyMessage"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","title":"replyMessage(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/processMessage(operation:message:edit:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/processMessage(operation:message:edit:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/processmessage(operation:message:edit:)","abstract":[{"type":"text","text":"Call the corresponding method in ViewModel to handle the specified message."}],"navigatorTitle":[{"text":"processMessageWithOperation:message:edieText:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageOperation","text":"MessageOperation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":", "},{"kind":"externalParam","text":"edit"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"processMessage(operation:message:edit:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/GroupChatThreadEventListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupChatThreadEventListener-Implementations","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/groupchatthreadeventlistener-implementations","role":"collectionGroup","abstract":[],"title":"GroupChatThreadEventListener Implementations","kind":"article","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/willSendMessage(attributeText:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/willSendMessage(attributeText:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/willsendmessage(attributetext:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"willSendMessageWithAttributeText:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willSendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"willSendMessage(attributeText:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/constructMessage(text:type:extensionInfo:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/constructMessage(text:type:extensionInfo:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/constructmessage(text:type:extensioninfo:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"constructMessageWithText:type:extensionInfo:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"constructMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageCellStyle","text":"MessageCellStyle"},{"kind":"text","text":", "},{"text":"extensionInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":">) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","title":"constructMessage(text:type:extensionInfo:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"MessageListViewModel","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/chatService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/chatType","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/driver","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/groupService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/mentionIds","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/multiService","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/searchMessageId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/to"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/addEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/audioMessagePlay(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/bindDriver(driver:searchMessageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/cacheFrame(attachMessage:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/cacheImage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/constructMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/copyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/deleteMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/deleteMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/downloadMessageAttachment(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/editMessage(message:content:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/init(conversationId:type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/loadMessages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/loadSearchMessage()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageAvatarLongPressed(profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionClicked(reaction:entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageStatusChanged(message:status:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageTopicClicked(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageVisibleMark(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/notifyUnreadCountChanged()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageBubbleClicked(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/operationReaction(emoji:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/processInputEvents(action:attributeText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/processMessage(operation:message:edit:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/recallAction(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/recallMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/removeEventsListener(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/replyMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/retrySendMessage(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/sendMessage(text:type:extensionInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/showOriginalText(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/translateMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/updateMentionIds(profile:type:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/willSendMessage(attributeText:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupChatThreadEventListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupServiceListener-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MultiDeviceListener-Implementations"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener"],"title":"Conforms To","type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListViewModel"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"op":"replace"},{"value":"to","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1to\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1to\/fragments","op":"replace","value":[{"kind":"identifier","text":"to"}]},{"value":"onMessageBubbleClickedWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageBubbleClicked(message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageBubbleClickedWithMessage:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageBubbleClicked(message:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidReceived(message:)\/title","value":"messageDidReceivedWithMessage:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageDidReceivedWithMessage:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidReceived(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageStatusChanged(message:status:error:)\/title","op":"replace","value":"messageStatusChangedWithMessage:status:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageStatusChanged(message:status:error:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageStatusChangedWithMessage:status:error:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidRecalled(recallInfo:)\/title","value":"messageDidRecalledWithRecallInfo:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidRecalled(recallInfo:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1searchMessageId\/title","value":"searchMessageId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1searchMessageId\/fragments","value":[{"kind":"identifier","text":"searchMessageId"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1recallMessage(message:)\/title","op":"replace","value":"recallMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1recallMessage(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recallMessageWithMessage:"}]},{"value":"sendMessageWithText:type:extensionInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1sendMessage(text:type:extensionInfo:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1sendMessage(text:type:extensionInfo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sendMessageWithText:type:extensionInfo:"}]},{"value":"loadSearchMessage","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1loadSearchMessage()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadSearchMessage"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1loadSearchMessage()\/fragments"},{"op":"replace","value":"deleteMessagesWithMessages:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1deleteMessages(messages:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1deleteMessages(messages:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"deleteMessagesWithMessages:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1deleteMessage(message:)\/title","value":"deleteMessageWithMessage:"},{"value":[{"text":"- ","kind":"text"},{"text":"deleteMessageWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1deleteMessage(message:)\/fragments","op":"replace"},{"value":"audioMessagePlayWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1audioMessagePlay(message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1audioMessagePlay(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioMessagePlayWithMessage:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1chatService\/title","value":"chatService"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1chatService\/fragments","op":"replace","value":[{"text":"chatService","kind":"identifier"}]},{"op":"replace","value":"showOriginalTextWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1showOriginalText(message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"showOriginalTextWithMessage:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1showOriginalText(message:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageVisibleMark(entity:)\/title","value":"messageVisibleMarkWithEntity:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageVisibleMark(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageVisibleMarkWithEntity:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/title","value":"IMessageListViewDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/fragments","value":[{"kind":"identifier","text":"IMessageListViewDriver"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1editMessage(message:content:)\/title","value":"editMessageWithMessage:content:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1editMessage(message:content:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editMessageWithMessage:content:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1updateMentionIds(profile:type:)\/title","value":"updateMentionIdsWithProfile:type:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1updateMentionIds(profile:type:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateMentionIdsWithProfile:type:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"messageDidEditedWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidEdited(message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidEdited(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageDidEditedWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageTopicClicked(entity:)\/title","value":"messageTopicClickedWithEntity:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageTopicClicked(entity:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageTopicClickedWithEntity:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1cacheImage(message:)\/title","value":"cacheImageWithMessage:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheImageWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1cacheImage(message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1recallAction(message:)\/title","value":"recallActionWithMessage:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"recallActionWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1recallAction(message:)\/fragments"},{"value":"ChatResponseListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/title","op":"replace"},{"value":[{"text":"ChatResponseListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/fragments","op":"replace"},{"value":"driver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1driver\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1driver\/fragments","value":[{"text":"driver","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/title","value":"GroupChatThreadEventListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventListener"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1loadMessages()\/title","op":"replace","value":"loadMessages"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadMessages"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1loadMessages()\/fragments"},{"value":"GroupServiceListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/title"},{"op":"replace","value":[{"kind":"identifier","text":"GroupServiceListener"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1notifyUnreadCountChanged()\/title","value":"notifyUnreadCountChanged","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1notifyUnreadCountChanged()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"notifyUnreadCountChanged","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1retrySendMessage(entity:)\/title","value":"retrySendMessageWithEntity:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"retrySendMessageWithEntity:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1retrySendMessage(entity:)\/fragments","op":"replace"},{"value":"messageReactionClickedWithReaction:entity:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageReactionClicked(reaction:entity:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageReactionClicked(reaction:entity:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"messageReactionClickedWithReaction:entity:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageReactionChanged(changes:)\/title","value":"messageReactionChangedWithChanges:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"messageReactionChangedWithChanges:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageReactionChanged(changes:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1addEventsListener(_:)\/title","op":"replace","value":"addEventsListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1addEventsListener(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addEventsListener:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1downloadMessageAttachment(message:)\/title","op":"replace","value":"downloadMessageAttachmentWithMessage:"},{"value":[{"kind":"text","text":"- "},{"text":"downloadMessageAttachmentWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1downloadMessageAttachment(message:)\/fragments"},{"value":"multiService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1multiService\/title"},{"value":[{"kind":"identifier","text":"multiService"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1multiService\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1groupService\/title","value":"groupService"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1groupService\/fragments","value":[{"text":"groupService","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageAvatarLongPressed(profile:)\/title","value":"messageAvatarLongPressedWithProfile:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageAvatarLongPressed(profile:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageAvatarLongPressedWithProfile:"}],"op":"replace"},{"value":"translateMessageWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1translateMessage(message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"translateMessageWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1translateMessage(message:)\/fragments"},{"value":"MessageListViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title"},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","op":"replace"},{"op":"replace","value":"MultiDeviceListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/title"},{"value":[{"text":"MultiDeviceListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1chatType\/title","value":"chatType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1chatType\/fragments","value":[{"text":"chatType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1cacheFrame(attachMessage:)\/title","value":"cacheFrameWithAttachMessage:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1cacheFrame(attachMessage:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheFrameWithAttachMessage:"}],"op":"replace"},{"value":"bindWithDriver:searchMessageId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1bindDriver(driver:searchMessageId:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1bindDriver(driver:searchMessageId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindWithDriver:searchMessageId:","kind":"identifier"}]},{"op":"replace","value":"mentionIds","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1mentionIds\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1mentionIds\/fragments","value":[{"text":"mentionIds","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"op":"replace"},{"op":"replace","value":"operationReactionWithEmoji:message:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1operationReaction(emoji:message:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"operationReactionWithEmoji:message:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1operationReaction(emoji:message:)\/fragments"},{"op":"replace","value":"messageAttachmentStatusChangedWithMessage:error:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageAttachmentStatusChanged(message:error:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageAttachmentStatusChangedWithMessage:error:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageAttachmentStatusChanged(message:error:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1init(conversationId:type:)\/title","op":"replace","value":"initWithConversationId:type:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConversationId:type:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1init(conversationId:type:)\/fragments","op":"replace"},{"op":"replace","value":"processInputEventsWithAction:attributeText:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1processInputEvents(action:attributeText:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1processInputEvents(action:attributeText:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"processInputEventsWithAction:attributeText:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1removeEventsListener(_:)\/title","value":"removeEventsListener:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1removeEventsListener(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeEventsListener:"}]},{"op":"replace","value":"copyMessageWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1copyMessage(message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1copyMessage(message:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"copyMessageWithMessage:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1replyMessage(message:)\/title","value":"replyMessageWithMessage:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"replyMessageWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1replyMessage(message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1processMessage(operation:message:edit:)\/title","value":"processMessageWithOperation:message:edieText:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1processMessage(operation:message:edit:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"processMessageWithOperation:message:edieText:","kind":"identifier"}]},{"value":"willSendMessageWithAttributeText:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1willSendMessage(attributeText:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willSendMessageWithAttributeText:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1willSendMessage(attributeText:)\/fragments"},{"value":"constructMessageWithText:type:extensionInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1constructMessage(text:type:extensionInfo:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"constructMessageWithText:type:extensionInfo:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1constructMessage(text:type:extensionInfo:)\/fragments"}]}]}