{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageattachmentmenustyle"]},{"paths":["\/documentation\/easechatuikit\/messageattachmentmenustyle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@E@MessageAttachmentMenuStyle","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"symbolKind":"enum","role":"symbol","title":"MessageAttachmentMenuStyle","roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageAttachmentMenuStyle","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle"},"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/followInput"],"title":"Enumeration Cases"},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/init(rawValue:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/RawRepresentable-Implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle/init(rawValue:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle\/init(rawvalue:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","kind":"symbol","title":"init(rawValue:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle/actionSheet":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","url":"\/documentation\/easechatuikit\/messageattachmentmenustyle\/actionsheet","title":"MessageAttachmentMenuStyle.actionSheet","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"MessageAttachmentMenuStyleActionSheet","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"actionSheet","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle":{"navigatorTitle":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MessageAttachmentMenuStyle"},"doc://org.cocoapods.EaseChatUIKit/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle/followInput":{"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle\/followinput","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"followInput"}],"abstract":[],"navigatorTitle":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}],"title":"MessageAttachmentMenuStyle.followInput","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/followInput","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/easechatuikit\/messageattachmentmenustyle\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/RawRepresentable-Implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle/Equatable-Implementations":{"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle\/equatable-implementations","role":"collectionGroup","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/Equatable-Implementations","kind":"article","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"MessageAttachmentMenuStyle"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"op":"replace","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/actionSheet","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/followInput"],"title":"Enumeration Cases","generated":true}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageAttachmentMenuStyle"},{"text":": ","kind":"text"},{"text":"uint8_t","preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"MessageAttachmentMenuStyleActionSheet","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle~1actionSheet\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle~1actionSheet\/fragments","op":"replace","value":[{"text":"MessageAttachmentMenuStyleActionSheet","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/title","value":"MessageAttachmentMenuStyle","op":"replace"},{"value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/navigatorTitle","value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"op":"replace"},{"value":"MessageAttachmentMenuStyleFollowInput","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle~1followInput\/title"},{"op":"replace","value":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle~1followInput\/fragments"}]}]}