{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"MessageReactionCell","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MessageReactionCell"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageReactionCell","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionCell","kind":"identifier"}],"symbolKind":"class"},"kind":"symbol","sections":[],"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/init(frame:)"]},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/content"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/createContent()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/refresh(reaction:)"],"title":"Instance Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UICollectionViewCell"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionCell","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagereactioncell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagereactioncell"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","type":"unresolvable","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UICoordinateSpace","type":"unresolvable","title":"UIKit.UICoordinateSpace"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","type":"unresolvable","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)CALayerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)CALayerDelegate","type":"unresolvable","title":"QuartzCore.CALayerDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell/refresh(reaction:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/refresh(reaction:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageReaction","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona"},{"kind":"text","text":")"}],"title":"refresh(reaction:)","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"refreshWithReaction:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagereactioncell\/refresh(reaction:)"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell/init(coder:)":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/init(coder:)","kind":"symbol","title":"init(coder:)","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagereactioncell\/init(coder:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"MessageReactionCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell","title":"MessageReactionCell","url":"\/documentation\/easechatuikit\/messagereactioncell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","title":"Swift.Sendable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UILargeContentViewerItem","title":"UIKit.UILargeContentViewerItem"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearance":{"title":"UIKit.UIAppearance","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearance","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAccessibilityIdentification":{"title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAccessibilityIdentification","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIDynamicItem":{"title":"UIKit.UIDynamicItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDynamicItem","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell/init(frame:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/init(frame:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"title":"init(frame:)","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/easechatuikit\/messagereactioncell\/init(frame:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell/createContent()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createContent"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createContent"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/createContent()","url":"\/documentation\/easechatuikit\/messagereactioncell\/createcontent()","title":"createContent()","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusItem":{"title":"UIKit.UIFocusItem","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusItem"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell/content":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/content","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"title":"content","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagereactioncell\/content"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UICollectionViewCell":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UICollectionViewCell","title":"UICollectionViewCell"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"MessageReactionCell","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"MessageReactionCell"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageReactionCell"}]},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/content"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/createContent()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/init(frame:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/refresh(reaction:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UICollectionViewCell"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"MessageReactionCell","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"refreshWithReaction:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1refresh(reaction:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1refresh(reaction:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"refreshWithReaction:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithCoder:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1init(coder:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1init(coder:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell\/title","value":"MessageReactionCell"},{"value":[{"text":"MessageReactionCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell\/fragments"},{"value":[{"text":"MessageReactionCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell\/navigatorTitle"},{"value":"initWithFrame:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1init(frame:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1init(frame:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1createContent()\/title","value":"createContent"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1createContent()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createContent","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1content\/title","value":"content"},{"op":"replace","value":[{"kind":"identifier","text":"content"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1content\/fragments"}]}]}