{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/mode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/mode"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"Mode","role":"symbol","roleHeading":"Structure","navigatorTitle":[{"text":"Mode","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"externalID":"c:@E@Mode","symbolKind":"struct"},"kind":"symbol","topicSections":[{"title":"Variables","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR515","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR67","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR74","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR795","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/N_MODES"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/init(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/rawValue"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/Equatable-Implementations"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SY","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Mode":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"navigatorTitle":[{"text":"Mode","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode","abstract":[],"url":"\/documentation\/easechatuikit\/mode","title":"Mode"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MR67":{"url":"\/documentation\/easechatuikit\/mr67","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR67","title":"MR67","abstract":[],"role":"symbol","navigatorTitle":[{"text":"MR67","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MR67","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@Mode","text":"Mode"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Mode/init(_:)":{"title":"init(_:)","url":"\/documentation\/easechatuikit\/mode\/init(_:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/init(_:)","role":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MR515":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR515","role":"symbol","title":"MR515","navigatorTitle":[{"text":"MR515","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/mr515","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MR515"},{"text":": ","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"c:@E@Mode"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MR795":{"kind":"symbol","url":"\/documentation\/easechatuikit\/mr795","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"MR795","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"c:@E@Mode"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR795","title":"MR795","navigatorTitle":[{"kind":"identifier","text":"MR795"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Mode/Equatable-Implementations":{"url":"\/documentation\/easechatuikit\/mode\/equatable-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MR74":{"url":"\/documentation\/easechatuikit\/mr74","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR74","title":"MR74","abstract":[],"role":"symbol","navigatorTitle":[{"text":"MR74","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MR74","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Mode","preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Mode/init(rawValue:)":{"url":"\/documentation\/easechatuikit\/mode\/init(rawvalue:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Mode/rawValue":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode\/rawValue","title":"rawValue","url":"\/documentation\/easechatuikit\/mode\/rawvalue","role":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/N_MODES":{"navigatorTitle":[{"kind":"identifier","text":"N_MODES"}],"type":"topic","url":"\/documentation\/easechatuikit\/n_modes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"N_MODES","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"c:@E@Mode"}],"title":"N_MODES","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/N_MODES","abstract":[],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","value":"Mode","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"value":[{"kind":"identifier","text":"Mode"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"Mode","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR515","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR67","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR74","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR795","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/N_MODES"]}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Mode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:i","text":"unsigned int","kind":"typeIdentifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Mode\/title","value":"Mode","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Mode\/fragments","value":[{"kind":"identifier","text":"Mode"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR67\/title","value":"MR67","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR67\/fragments","op":"replace","value":[{"text":"MR67","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR515\/title","value":"MR515"},{"op":"replace","value":[{"text":"MR515","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR515\/fragments"},{"op":"replace","value":"MR795","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR795\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR795\/fragments","value":[{"kind":"identifier","text":"MR795"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR74\/title","value":"MR74"},{"value":[{"text":"MR74","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR74\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1N_MODES\/title","op":"replace","value":"N_MODES"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1N_MODES\/fragments","value":[{"kind":"identifier","text":"N_MODES"}]}]}]}