{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","interfaceLanguage":"swift"},"metadata":{"title":"MoreMessagePosition","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MoreMessagePosition","kind":"identifier"}],"navigatorTitle":[{"text":"MoreMessagePosition","kind":"identifier"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","externalID":"c:@M@EaseChatUIKit@E@MoreMessagePosition"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/center","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/left","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/right"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/init(rawValue:)"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/moremessageposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/moremessageposition"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MoreMessagePosition","kind":"identifier"}]}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/left":{"title":"MoreMessagePosition.left","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/left","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/moremessageposition\/left","navigatorTitle":[{"text":"MoreMessagePositionLeft","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition":{"title":"MoreMessagePosition","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MoreMessagePosition","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/moremessageposition","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePosition"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/RawRepresentable-Implementations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/moremessageposition\/rawrepresentable-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/init(rawValue:)":{"title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/moremessageposition\/init(rawvalue:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/SY":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","title":"Swift.RawRepresentable"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/center":{"title":"MoreMessagePosition.center","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/center","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/moremessageposition\/center","navigatorTitle":[{"text":"MoreMessagePositionCenter","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/Equatable-Implementations":{"title":"Equatable Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/Equatable-Implementations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/moremessageposition\/equatable-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/right":{"title":"MoreMessagePosition.right","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/right","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/moremessageposition\/right","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePositionRight"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"MoreMessagePosition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MoreMessagePosition","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"MoreMessagePosition"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/center","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/left","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/right"],"title":"Enumeration Cases"}]},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoreMessagePosition"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1left\/title","value":"MoreMessagePositionLeft"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1left\/fragments","value":[{"text":"MoreMessagePositionLeft","kind":"identifier"}],"op":"replace"},{"value":"MoreMessagePosition","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/fragments","value":[{"text":"MoreMessagePosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1center\/title","op":"replace","value":"MoreMessagePositionCenter"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1center\/fragments","op":"replace","value":[{"text":"MoreMessagePositionCenter","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1right\/title","op":"replace","value":"MoreMessagePositionRight"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1right\/fragments","op":"replace","value":[{"kind":"identifier","text":"MoreMessagePositionRight"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}