{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MR74","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode","preciseIdentifier":"c:@E@Mode","text":"Mode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/mr74"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/mr74"]}],"kind":"symbol","metadata":{"externalID":"c:@E@Mode@MR74","modules":[{"name":"EaseChatUIKit"}],"title":"MR74","roleHeading":"Global Variable","navigatorTitle":[{"text":"MR74","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MR74"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@Mode","text":"Mode","kind":"typeIdentifier"}],"symbolKind":"var","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR74","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Mode":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Mode","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"Mode","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/mode","navigatorTitle":[{"kind":"identifier","text":"Mode"}],"kind":"symbol","title":"Mode"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MR74":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MR74","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"MR74","kind":"identifier"},{"kind":"text","text":": "},{"text":"Mode","preciseIdentifier":"c:@E@Mode","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/mr74","navigatorTitle":[{"text":"MR74","kind":"identifier"}],"kind":"symbol","title":"MR74"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MR74","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"MR74"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MR74"}]}],"kind":"declarations"}},{"op":"replace","value":"Mode","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Mode\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Mode\/fragments","op":"replace","value":[{"text":"Mode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR74\/title","value":"MR74","op":"replace"},{"value":[{"kind":"identifier","text":"MR74"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MR74\/fragments","op":"replace"}]}]}