{"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessagesContainerDelegate"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/didSelect(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/remove(entity:)"],"anchor":"Instance-Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"],"type":"conformingTypes"}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"title":"PinnedMessagesContainerDelegate","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"symbolKind":"protocol","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate/remove(entity:)":{"url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate\/remove(entity:)","role":"symbol","navigatorTitle":[{"text":"removeWithEntity:","kind":"identifier"}],"kind":"symbol","title":"remove(entity:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/remove(entity:)","type":"topic","required":true,"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity","text":"PinnedMessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate":{"navigatorTitle":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","kind":"symbol","title":"PinnedMessagesContainerDelegate","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate/didSelect(entity:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didSelect","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity","text":"PinnedMessageEntity"},{"text":")","kind":"text"}],"abstract":[],"title":"didSelect(entity:)","role":"symbol","navigatorTitle":[{"text":"didSelectWithEntity:","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/didSelect(entity:)","url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate\/didselect(entity:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"PinnedMessagesContainerDelegate"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"op":"replace"},{"value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/didSelect(entity:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/remove(entity:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"removeWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate~1remove(entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate~1remove(entity:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeWithEntity:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/title","op":"replace","value":"PinnedMessagesContainerDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/fragments","value":[{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/navigatorTitle","value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageListViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate~1didSelect(entity:)\/title","value":"didSelectWithEntity:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"didSelectWithEntity:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate~1didSelect(entity:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}