{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentedViewType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/presentedviewtype"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogContainerViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentedViewType","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentedViewType\/presentedViewComponent"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentedViewType"}],"title":"PresentedViewType","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"s:13EaseChatUIKit17PresentedViewTypeP","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"PresentedViewType"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainersDialogController":{"role":"symbol","title":"PageContainersDialogController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainersDialogController"}],"abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainersDialogController"}],"url":"\/documentation\/easechatuikit\/pagecontainersdialogcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogContainerViewController":{"role":"symbol","title":"DialogContainerViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DialogContainerViewController"}],"abstract":[{"type":"text","text":"A view controller that manages the presentation of a dialog container view and its content."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogContainerViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DialogContainerViewController"}],"url":"\/documentation\/easechatuikit\/dialogcontainerviewcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentedViewType/presentedViewComponent":{"role":"symbol","title":"presentedViewComponent","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentedViewComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentedViewComponent","preciseIdentifier":"s:13EaseChatUIKit22PresentedViewComponentV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentedViewType\/presentedViewComponent","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/presentedviewtype\/presentedviewcomponent"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertViewController":{"role":"symbol","title":"AlertViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AlertViewController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AlertViewController"}],"url":"\/documentation\/easechatuikit\/alertviewcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentedViewType":{"role":"symbol","title":"PresentedViewType","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentedViewType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentedViewType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentedViewType"}],"url":"\/documentation\/easechatuikit\/presentedviewtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/title","value":"PageContainersDialogController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/fragments","value":[{"kind":"identifier","text":"PageContainersDialogController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogContainerViewController\/title","value":"DialogContainerViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogContainerViewController\/fragments","value":[{"kind":"identifier","text":"DialogContainerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertViewController\/title","value":"AlertViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertViewController\/fragments","value":[{"kind":"identifier","text":"AlertViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}