{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/presentationanimation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/presentationanimation"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FlipHorizontalAnimation"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/init(options:origin:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/options","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/origin"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/afterAnimation(animationContext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/performAnimation(animationContext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/transformInitialFrame(containerFrame:finalFrame:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"title":"PresentationAnimation","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@EaseChatUIKit@objc(cs)PresentationAnimation","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"PresentationAnimation"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/beforeAnimation(animationContext:)":{"role":"symbol","title":"beforeAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"beforeAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/beforeAnimation(animationContext:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/beforeanimation(animationcontext:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIViewControllerAnimatedTransitioning":{"type":"unresolvable","title":"UIViewControllerAnimatedTransitioning","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/afterAnimation(animationContext:)":{"role":"symbol","title":"afterAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"afterAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"动画完成后（做动画完成的清理工作，子类可覆写）"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/afterAnimation(animationContext:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/afteranimation(animationcontext:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/init(options:origin:)":{"role":"symbol","title":"init(options:origin:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationOptions","preciseIdentifier":"s:13EaseChatUIKit16AnimationOptionsO"},{"kind":"text","text":", "},{"kind":"externalParam","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentationOrigin","preciseIdentifier":"s:13EaseChatUIKit18PresentationOriginO"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/init(options:origin:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/init(options:origin:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/options":{"role":"symbol","title":"options","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationOptions","preciseIdentifier":"s:13EaseChatUIKit16AnimationOptionsO"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/options","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/options"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossDissolveAnimation":{"role":"symbol","title":"CrossDissolveAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CrossDissolveAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CrossDissolveAnimation"}],"url":"\/documentation\/easechatuikit\/crossdissolveanimation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation":{"role":"symbol","title":"PresentationAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationAnimation"}],"url":"\/documentation\/easechatuikit\/presentationanimation"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/origin":{"role":"symbol","title":"origin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PresentationOrigin","preciseIdentifier":"s:13EaseChatUIKit18PresentationOriginO"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/origin","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/origin"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossZoomAnimation":{"role":"symbol","title":"CrossZoomAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CrossZoomAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CrossZoomAnimation"}],"url":"\/documentation\/easechatuikit\/crosszoomanimation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/performAnimation(animationContext:)":{"role":"symbol","title":"performAnimation(animationContext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAnimation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animationContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationContext","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/performAnimation(animationContext:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/performanimation(animationcontext:)"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/FlipHorizontalAnimation":{"role":"symbol","title":"FlipHorizontalAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlipHorizontalAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FlipHorizontalAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FlipHorizontalAnimation"}],"url":"\/documentation\/easechatuikit\/fliphorizontalanimation"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/transformInitialFrame(containerFrame:finalFrame:)":{"role":"symbol","title":"transformInitialFrame(containerFrame:finalFrame:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformInitialFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"containerFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finalFrame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/transformInitialFrame(containerFrame:finalFrame:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/transforminitialframe(containerframe:finalframe:)"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/UIViewControllerAnimatedTransitioning-Implementations":{"role":"collectionGroup","title":"UIViewControllerAnimatedTransitioning Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"PresentationAnimation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossDissolveAnimation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FlipHorizontalAnimation"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerAnimatedTransitioning"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossDissolveAnimation\/title","value":"CrossDissolveAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossDissolveAnimation\/fragments","value":[{"kind":"identifier","text":"CrossDissolveAnimation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/title","value":"PresentationAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/fragments","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/title","value":"CrossZoomAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/fragments","value":[{"kind":"identifier","text":"CrossZoomAnimation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FlipHorizontalAnimation\/title","value":"FlipHorizontalAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FlipHorizontalAnimation\/fragments","value":[{"kind":"identifier","text":"FlipHorizontalAnimation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}