{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)PresentationSegue","role":"symbol","navigatorTitle":[{"text":"PresentationSegue","kind":"identifier"}],"title":"PresentationSegue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationSegue"}],"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"class","roleHeading":"Class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationSegue"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIStoryboardSegue"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationSegue\/perform()"],"title":"Instance Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationSegue"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/presentationsegue"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/presentationsegue"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationSegue":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationSegue"}],"navigatorTitle":[{"kind":"identifier","text":"PresentationSegue"}],"role":"symbol","abstract":[],"title":"PresentationSegue","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationSegue","url":"\/documentation\/easechatuikit\/presentationsegue"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIStoryboardSegue":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIStoryboardSegue","title":"UIStoryboardSegue","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationSegue/initWithIdentifier:source:destination:":{"kind":"symbol","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIdentifier:source:destination:"}],"navigatorTitle":[{"text":"initWithIdentifier:source:destination:","kind":"identifier"}],"role":"symbol","title":"initWithIdentifier:source:destination:","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationSegue\/initWithIdentifier:source:destination:","url":"\/documentation\/easechatuikit\/presentationsegue\/initwithidentifier:source:destination:"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationSegue/perform()":{"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"perform"}],"title":"perform()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"perform"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationSegue\/perform()","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/presentationsegue\/perform()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"PresentationSegue","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"PresentationSegue"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationSegue"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationSegue\/initWithIdentifier:source:destination:","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationSegue\/perform()"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIStoryboardSegue"],"type":"inheritsFrom","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentationSegue"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIStoryboardSegue","preciseIdentifier":"c:objc(cs)UIStoryboardSegue"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"PresentationSegue","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationSegue\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationSegue\/fragments","value":[{"text":"PresentationSegue","kind":"identifier"}],"op":"replace"},{"value":"perform","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationSegue~1perform()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationSegue~1perform()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"perform","kind":"identifier"}],"op":"replace"}]}]}