{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"PresentationController","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"PresentationController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PresentationController"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)PresentationController","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIPresentationController"],"title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PresentationController","kind":"identifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"content":[{"inlineContent":[{"text":"This class is a subclass of ","type":"text"},{"type":"codeVoice","code":"UIPresentationController"},{"type":"text","text":"."}],"type":"paragraph"}],"type":"aside","name":"Note","style":"note"},{"content":[{"inlineContent":[{"type":"text","text":"FILEPATH"}],"type":"paragraph"}],"style":"note","name":"Author","type":"aside"},{"content":[{"inlineContent":[{"type":"text","text":"1.0"}],"type":"paragraph"}],"name":"Version","style":"note","type":"aside"}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/presentationcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/presentationcontroller"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/init(presentedViewController:presenting:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/presentationTransitionWillBegin()"],"title":"Instance Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController/frameOfPresentedViewInContainerView":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"frameOfPresentedViewInContainerView","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/presentationcontroller\/frameofpresentedviewincontainerview","title":"frameOfPresentedViewInContainerView"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController/dismissalTransitionWillBegin()":{"abstract":[],"title":"dismissalTransitionWillBegin()","kind":"symbol","type":"topic","navigatorTitle":[{"text":"dismissalTransitionWillBegin","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/presentationcontroller\/dismissaltransitionwillbegin()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/dismissalTransitionWillBegin()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dismissalTransitionWillBegin"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController/presentationTransitionDidEnd(_:)":{"url":"\/documentation\/easechatuikit\/presentationcontroller\/presentationtransitiondidend(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","title":"presentationTransitionDidEnd(_:)","abstract":[{"text":"已经弹出视图","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"presentationTransitionDidEnd:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentationTransitionDidEnd"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIPresentationController":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIPresentationController","title":"UIPresentationController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController/init(presentedViewController:presenting:)":{"url":"\/documentation\/easechatuikit\/presentationcontroller\/init(presentedviewcontroller:presenting:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/init(presentedViewController:presenting:)","title":"init(presentedViewController:presenting:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"initWithPresentedViewController:presentingViewController:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"presentedViewController","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"presenting","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"?)"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController/presentationTransitionWillBegin()":{"url":"\/documentation\/easechatuikit\/presentationcontroller\/presentationtransitionwillbegin()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/presentationTransitionWillBegin()","title":"presentationTransitionWillBegin()","abstract":[{"type":"text","text":"将要弹出时添加背景按钮"}],"role":"symbol","navigatorTitle":[{"text":"presentationTransitionWillBegin","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentationTransitionWillBegin","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController":{"title":"PresentationController","abstract":[{"type":"text","text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"PresentationController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/presentationcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PresentationController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController/dismissalTransitionDidEnd(_:)":{"url":"\/documentation\/easechatuikit\/presentationcontroller\/dismissaltransitiondidend(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","title":"dismissalTransitionDidEnd(_:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"dismissalTransitionDidEnd:","kind":"identifier"}],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dismissalTransitionDidEnd","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"PresentationController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"PresentationController","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/dismissalTransitionDidEnd(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/dismissalTransitionWillBegin()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/init(presentedViewController:presenting:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/presentationTransitionDidEnd(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/presentationTransitionWillBegin()"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIPresentationController"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"PresentationController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIPresentationController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPresentationController"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/title","op":"replace","value":"frameOfPresentedViewInContainerView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/fragments","value":[{"text":"frameOfPresentedViewInContainerView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"dismissalTransitionWillBegin","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1dismissalTransitionWillBegin()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1dismissalTransitionWillBegin()\/fragments","value":[{"kind":"text","text":"- "},{"text":"dismissalTransitionWillBegin","kind":"identifier"}]},{"value":"presentationTransitionDidEnd:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1presentationTransitionDidEnd(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1presentationTransitionDidEnd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentationTransitionDidEnd:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1init(presentedViewController:presenting:)\/title","op":"replace","value":"initWithPresentedViewController:presentingViewController:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPresentedViewController:presentingViewController:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1init(presentedViewController:presenting:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1presentationTransitionWillBegin()\/title","op":"replace","value":"presentationTransitionWillBegin"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentationTransitionWillBegin"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1presentationTransitionWillBegin()\/fragments"},{"value":"PresentationController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController\/fragments","op":"replace","value":[{"kind":"identifier","text":"PresentationController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1dismissalTransitionDidEnd(_:)\/title","value":"dismissalTransitionDidEnd:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1dismissalTransitionDidEnd(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"dismissalTransitionDidEnd:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}