{"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchResultMessagesController","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@EaseChatUIKit@objc(cs)SearchResultMessagesController","navigatorTitle":[{"text":"SearchResultMessagesController","kind":"identifier"}],"title":"SearchResultMessagesController","symbolKind":"class","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:searchMessageId:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/searchMessageId"],"generated":true,"title":"Instance Properties"},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/createMessageContainer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/rightImages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewContact(body:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDetail()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDidLoad()"]}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)QLPreviewControllerDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDocumentPickerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIGestureRecognizerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIImagePickerControllerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UINavigationControllerDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchresultmessagescontroller"]},{"paths":["\/documentation\/easechatuikit\/searchresultmessagescontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchResultMessagesController"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchResultMessagesController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController","abstract":[],"title":"SearchResultMessagesController","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller","navigatorTitle":[{"text":"SearchResultMessagesController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/onMessageAvatarClicked(user:)":{"kind":"symbol","title":"onMessageAvatarClicked(user:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClicked"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageAvatarClickedWithUser:"}],"abstract":[],"url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/onmessageavatarclicked(user:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/onMessageAvatarClicked(user:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/init(coder:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(coder:)","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/init(coder:)","abstract":[],"title":"init(coder:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/createMessageContainer()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createMessageContainer","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"MessageListView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageListView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/createMessageContainer()","navigatorTitle":[{"text":"createMessageContainer","kind":"identifier"}],"title":"createMessageContainer()","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/createmessagecontainer()","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)QLPreviewControllerDataSource":{"title":"QuickLook.QLPreviewControllerDataSource","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)QLPreviewControllerDataSource"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/viewDetail()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDetail","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"viewDetail","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDetail()","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/viewdetail()","abstract":[{"type":"text","text":"This method is called to view the detail of a chat message."},{"type":"text","text":" "},{"type":"text","text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly."},{"type":"text","text":" "},{"text":"If the previous view controller in the navigation stack is either ","type":"text"},{"code":"GroupInfoViewController","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"text":", it pops the current view controller.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is individual, it presents the ","type":"text"},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"code":"GroupInfoController","type":"codeVoice"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"},{"type":"text","text":" "},{"text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either ","type":"text"},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" and dismisses it."},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"text":" with the given profile.","type":"text"},{"type":"text","text":" "},{"text":"If the chat type is group, it presents the ","type":"text"},{"code":"GroupInfoController","type":"codeVoice"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"}],"title":"viewDetail()","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIGestureRecognizerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIGestureRecognizerDelegate","title":"UIKit.UIGestureRecognizerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/viewContact(body:)":{"type":"topic","kind":"symbol","abstract":[{"text":"Opens the contact view for the given custom message body.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewContactWithBody:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewContact(body:)","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/viewcontact(body:)","title":"viewContact(body:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewContact","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"text":": ","kind":"text"},{"text":"ChatCustomMessageBody","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B17CustomMessageBodya"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagelistcontroller","role":"symbol","navigatorTitle":[{"text":"MessageListController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController","title":"MessageListController"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/searchMessageId":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"searchMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"searchMessageId","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/searchMessageId","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"searchMessageId"}],"url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/searchmessageid"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/navigationClick(type:indexPath:)":{"title":"navigationClick(type:indexPath:)","abstract":[{"text":"Handles the navigation bar click events.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatNavigationBarClickEvent","text":"ChatNavigationBarClickEvent"},{"kind":"text","text":", "},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/navigationclick(type:indexpath:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/navigationClick(type:indexPath:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate","title":"UIKit.UIViewControllerTransitioningDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/init(conversationId:chatType:searchMessageId:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chatType"},{"text":": ","kind":"text"},{"text":"ChatType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType"},{"text":", ","kind":"text"},{"text":"searchMessageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:searchMessageId:)","navigatorTitle":[{"text":"initWithConversationId:chatType:searchMessageId:","kind":"identifier"}],"title":"init(conversationId:chatType:searchMessageId:)","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/init(conversationid:chattype:searchmessageid:)","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/rightImages()":{"abstract":[{"text":"Right images of the ","type":"text"},{"type":"codeVoice","code":"EaseChatNavigationBar"},{"type":"text","text":"."}],"url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/rightimages()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightImages"},{"text":"() -> [","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"]","kind":"text"}],"title":"rightImages()","navigatorTitle":[{"text":"rightImages","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/rightImages()","type":"topic","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener":{"url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","abstract":[],"type":"topic","kind":"symbol","title":"MessageListDriverEventsListener","navigatorTitle":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MessageListDriverEventsListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"role":"symbol","url":"\/documentation\/easechatuikit\/themeswitchprotocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","title":"ThemeSwitchProtocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UINavigationControllerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UINavigationControllerDelegate","title":"UIKit.UINavigationControllerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/viewDidLoad()":{"type":"topic","kind":"symbol","title":"viewDidLoad()","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDidLoad()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/viewdidload()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/init(conversationId:chatType:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chatType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType","text":"ChatType"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"initWithConversationId:chatType:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:)","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/init(conversationid:chattype:)","abstract":[{"text":"Initializes a new instance of the ","type":"text"},{"type":"codeVoice","code":"MessageListController"},{"text":" class with the specified conversation ID and chat type.","type":"text"}],"title":"init(conversationId:chatType:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIImagePickerControllerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIImagePickerControllerDelegate","title":"UIKit.UIImagePickerControllerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIDocumentPickerDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIDocumentPickerDelegate","title":"UIKit.UIDocumentPickerDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SearchResultMessagesController","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SearchResultMessagesController"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SearchResultMessagesController"}]},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/searchMessageId"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/createMessageContainer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:searchMessageId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/navigationClick(type:indexPath:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/onMessageAvatarClicked(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/rightImages()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewContact(body:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDetail()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDidLoad()"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchResultMessagesController"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageListController","text":"MessageListController","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListController"}]}]}},{"value":"SearchResultMessagesController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/fragments","value":[{"text":"SearchResultMessagesController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SearchResultMessagesController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/navigatorTitle","op":"replace"},{"value":"onMessageAvatarClickedWithUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1onMessageAvatarClicked(user:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1onMessageAvatarClicked(user:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageAvatarClickedWithUser:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(coder:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1createMessageContainer()\/title","op":"replace","value":"createMessageContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1createMessageContainer()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createMessageContainer","kind":"identifier"}]},{"value":"viewDetail","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewDetail()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"viewDetail","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewDetail()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewContact(body:)\/title","value":"viewContactWithBody:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewContactWithBody:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewContact(body:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/title","value":"MessageListController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/fragments","value":[{"text":"MessageListController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListController\/navigatorTitle","op":"replace","value":[{"text":"MessageListController","kind":"identifier"}]},{"value":"searchMessageId","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1searchMessageId\/title","op":"replace"},{"op":"replace","value":[{"text":"searchMessageId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1searchMessageId\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1navigationClick(type:indexPath:)\/title","op":"replace","value":"navigationClickWithType:indexPath:"},{"value":[{"text":"- ","kind":"text"},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1navigationClick(type:indexPath:)\/fragments","op":"replace"},{"value":"initWithConversationId:chatType:searchMessageId:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(conversationId:chatType:searchMessageId:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(conversationId:chatType:searchMessageId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConversationId:chatType:searchMessageId:"}]},{"value":"rightImages","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1rightImages()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightImages"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1rightImages()\/fragments","op":"replace"},{"value":"MessageListDriverEventsListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/title","op":"replace"},{"value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/fragments"},{"value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/navigatorTitle","op":"replace"},{"op":"replace","value":"ThemeSwitchProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewDidLoad()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewDidLoad()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(conversationId:chatType:)\/title","value":"initWithConversationId:chatType:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConversationId:chatType:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(conversationId:chatType:)\/fragments","op":"replace"}]}]}