{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/searchheaderbardisplaystyle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/searchheaderbardisplaystyle"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/other","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/withBack"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}],"title":"SearchHeaderBarDisplayStyle","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@EaseChatUIKit@E@SearchHeaderBarDisplayStyle","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle/other":{"role":"symbol","title":"SearchHeaderBarDisplayStyle.other","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/other","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyleOther"}],"url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/other"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/rawrepresentable-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/equatable-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle/withBack":{"role":"symbol","title":"SearchHeaderBarDisplayStyle.withBack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"withBack"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/withBack","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyleWithBack"}],"url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/withback"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/init(rawvalue:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle":{"role":"symbol","title":"SearchHeaderBarDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}],"url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SearchHeaderBarDisplayStyle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/other","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/withBack"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1other\/title","value":"SearchHeaderBarDisplayStyleOther"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1other\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyleOther"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1withBack\/title","value":"SearchHeaderBarDisplayStyleWithBack"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1withBack\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyleWithBack"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/title","value":"SearchHeaderBarDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}