{"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/init(searchInfos:toChat:)"],"anchor":"Initializers"},{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/empty","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/searchHeader","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/searchList"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewDidLoad()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewWillAppear(_:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDelegate-Implementations"],"title":"Default Implementations"}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate","doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchConversationsController","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchconversationscontroller"]},{"paths":["\/documentation\/easechatuikit\/searchconversationscontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"SearchConversationsController","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SearchConversationsController","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"text":"SearchConversationsController","kind":"identifier"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@EaseChatUIKit@objc(cs)SearchConversationsController"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)UIViewController":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController","title":"UIViewController"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIScrollViewDelegate":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIScrollViewDelegate","title":"UIKit.UIScrollViewDelegate"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/UITableViewDataSource-Implementations":{"abstract":[],"title":"UITableViewDataSource Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDataSource-Implementations","type":"topic","kind":"article","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/uitableviewdatasource-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeSwitchProtocol":{"role":"symbol","url":"\/documentation\/easechatuikit\/themeswitchprotocol","abstract":[{"type":"text","text":"When the system theme changes, you can use this static method to switch between the light and dark themes of the ease chat UIKit."}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ThemeSwitchProtocol"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","title":"ThemeSwitchProtocol","navigatorTitle":[{"text":"ThemeSwitchProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/UITableViewDelegate-Implementations":{"title":"UITableViewDelegate Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/searchconversationscontroller\/uitableviewdelegate-implementations","type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDelegate-Implementations"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://org.cocoapods.EaseChatUIKit/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8CopyableP","title":"Swift.Copyable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/empty":{"title":"empty","abstract":[],"url":"\/documentation\/easechatuikit\/searchconversationscontroller\/empty","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"empty"},{"text":": ","kind":"text"},{"text":"EmptyStateView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EmptyStateView"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/empty"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/ThemeSwitchProtocol-Implementations":{"abstract":[],"title":"ThemeSwitchProtocol Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/ThemeSwitchProtocol-Implementations","type":"topic","kind":"article","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/themeswitchprotocol-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","abstract":[],"url":"\/documentation\/easechatuikit\/searchconversationscontroller\/viewwillappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewWillAppear(_:)"},"doc://org.cocoapods.EaseChatUIKit/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","title":"UIKit.UITraitChangeObservable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/5UIKit23UITraitChangeObservableP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController":{"title":"SearchConversationsController","url":"\/documentation\/easechatuikit\/searchconversationscontroller","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchConversationsController"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SearchConversationsController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/init(coder:)":{"title":"init(coder:)","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/init(coder:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/init(coder:)"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDataSource":{"title":"UITableViewDataSource","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/init(searchInfos:toChat:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithSearchInfos:toChat:"}],"abstract":[],"title":"init(searchInfos:toChat:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/init(searchInfos:toChat:)","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/init(searchinfos:tochat:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"searchInfos"},{"text":": [","kind":"text"},{"text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"toChat"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/viewDidAppear(_:)":{"title":"viewDidAppear(_:)","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/viewdidappear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewDidAppear(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/searchHeader":{"abstract":[],"title":"searchHeader","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/searchHeader","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/searchheader","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchHeader","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)SearchHeaderBar","text":"SearchHeaderBar"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/viewDidLoad()":{"title":"viewDidLoad()","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/viewdidload()","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewDidLoad()"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSCoding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSCoding","title":"Foundation.NSCoding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIViewControllerTransitioningDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIViewControllerTransitioningDelegate","title":"UIKit.UIViewControllerTransitioningDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UITableViewDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate","title":"UITableViewDelegate","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/s8SendableP":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIUserActivityRestoring":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/searchList":{"abstract":[],"title":"searchList","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/searchList","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/searchlist","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"searchList","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"}]},"doc://org.cocoapods.EaseChatUIKit/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UIFocusEnvironment"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SearchConversationsController","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SearchConversationsController","kind":"identifier"}]},{"value":[{"text":"SearchConversationsController","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/init(coder:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/init(searchInfos:toChat:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewDidAppear(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewDidLoad()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/viewWillAppear(_:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/ThemeSwitchProtocol-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDataSource-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDelegate-Implementations"],"anchor":"Default-Implementations"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)UIViewController"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeSwitchProtocol","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)UITableViewDelegate"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SearchConversationsController","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"ThemeSwitchProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/title"},{"value":[{"text":"ThemeSwitchProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeSwitchProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ThemeSwitchProtocol"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1viewWillAppear(_:)\/fragments"},{"op":"replace","value":"SearchConversationsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController\/title"},{"value":[{"text":"SearchConversationsController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController\/navigatorTitle","op":"replace","value":[{"text":"SearchConversationsController","kind":"identifier"}]},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1init(coder:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1init(coder:)\/fragments"},{"op":"replace","value":"initWithSearchInfos:toChat:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1init(searchInfos:toChat:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1init(searchInfos:toChat:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSearchInfos:toChat:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1viewDidAppear(_:)\/title","value":"viewDidAppear:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidAppear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1viewDidAppear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1viewDidLoad()\/title","value":"viewDidLoad"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1viewDidLoad()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]}]}]}