{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/theme"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/theme"]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"abstract":[{"type":"text","text":"The theme switching class is used for users to switch themes or register some user’s own views that comply with the ThemeSwitchProtocol protocol."},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"type":"text","text":" "},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch theme that light and dark themes provided by default chatroom UIKit  ","type":"text"},{"type":"codeVoice","code":"theme"},{"type":"text","text":" ."},{"text":" ","type":"text"},{"type":"text","text":"Call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" method"},{"type":"text","text":" "},{"type":"text","text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch themes provided by customer ."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objcMembers","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Theme"}]}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/style"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/registerSwitchThemeViews(view:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/switchTheme(style:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/unregisterSwitchThemeViews()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme","interfaceLanguage":"swift"},"metadata":{"title":"Theme","roleHeading":"Class","externalID":"c:@M@EaseChatUIKit@objc(cs)Theme","symbolKind":"class","navigatorTitle":[{"text":"Theme","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Theme","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Theme/init":{"abstract":[],"url":"\/documentation\/easechatuikit\/theme\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/init","title":"init","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Theme/style":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/style","navigatorTitle":[{"kind":"identifier","text":"style"}],"url":"\/documentation\/easechatuikit\/theme\/style","type":"topic","title":"style","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Theme/unregisterSwitchThemeViews()":{"url":"\/documentation\/easechatuikit\/theme\/unregisterswitchthemeviews()","title":"unregisterSwitchThemeViews()","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/unregisterSwitchThemeViews()","navigatorTitle":[{"text":"unregisterSwitchThemeViews","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unregisterSwitchThemeViews","kind":"identifier"},{"kind":"text","text":"()"}],"kind":"symbol","abstract":[{"type":"text","text":"Clean register views."}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Theme/registerSwitchThemeViews(view:)":{"type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerSwitchThemeViews","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"view"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ThemeSwitchProtocol","kind":"typeIdentifier","text":"ThemeSwitchProtocol"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/registerSwitchThemeViews(view:)","abstract":[{"type":"text","text":"Register some user’s own views that Implement with the ThemeSwitchProtocol protocol."}],"url":"\/documentation\/easechatuikit\/theme\/registerswitchthemeviews(view:)","navigatorTitle":[{"kind":"identifier","text":"registerSwitchThemeViewsWithView:"}],"kind":"symbol","title":"registerSwitchThemeViews(view:)"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","title":"Swift.CVarArg"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject","title":"NSObject"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Theme/switchTheme(style:)":{"type":"topic","abstract":[{"type":"text","text":"The method"}],"navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"title":"switchTheme(style:)","url":"\/documentation\/easechatuikit\/theme\/switchtheme(style:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/switchTheme(style:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Theme":{"type":"topic","abstract":[{"text":"The theme switching class is used for users to switch themes or register some user’s own views that comply with the ThemeSwitchProtocol protocol.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"How to use?"},{"type":"text","text":" "},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch theme that light and dark themes provided by default chatroom UIKit  ","type":"text"},{"code":"theme","type":"codeVoice"},{"text":" .","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Call "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"text":" method","type":"text"},{"text":" ","type":"text"},{"text":"A view conform ThemeSwitchProtocol.Then Implement protocol methods.When you want switch themes provided by customer .","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Theme"}],"title":"Theme","url":"\/documentation\/easechatuikit\/theme","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Theme"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"Theme","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Theme"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"Theme","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/init"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/style"]},{"title":"Type Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/registerSwitchThemeViews(view:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/switchTheme(style:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Theme\/unregisterSwitchThemeViews()"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"Theme","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1style\/title","value":"style","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1style\/fragments","value":[{"text":"style","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1unregisterSwitchThemeViews()\/title","value":"unregisterSwitchThemeViews","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"unregisterSwitchThemeViews","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1unregisterSwitchThemeViews()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1registerSwitchThemeViews(view:)\/title","value":"registerSwitchThemeViewsWithView:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1registerSwitchThemeViews(view:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"registerSwitchThemeViewsWithView:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"value":[{"text":"+ ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme~1switchTheme(style:)\/fragments","op":"replace"},{"op":"replace","value":"Theme","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Theme\/fragments","op":"replace","value":[{"text":"Theme","kind":"identifier"}]}]}]}