{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"type":"conformsTo","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/triangledirection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/triangledirection"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TriangleDirection"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/left","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/right"],"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Enumeration","externalID":"c:@M@EaseChatUIKit@E@TriangleDirection","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","navigatorTitle":[{"text":"TriangleDirection","kind":"identifier"}],"role":"symbol","symbolKind":"enum"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection/right":{"title":"TriangleDirection.right","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/triangledirection\/right","navigatorTitle":[{"kind":"identifier","text":"TriangleDirectionRight"}],"kind":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/right"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/triangledirection\/init(rawvalue:)","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/SH":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"TriangleDirection","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/triangledirection"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/triangledirection\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/Equatable-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","kind":"article","url":"\/documentation\/easechatuikit\/triangledirection\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/RawRepresentable-Implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection/left":{"url":"\/documentation\/easechatuikit\/triangledirection\/left","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/left","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"}],"type":"topic","abstract":[],"title":"TriangleDirection.left","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TriangleDirectionLeft"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"path":"\/metadata\/title","value":"TriangleDirection","op":"replace"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"TriangleDirection","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"TriangleDirection","kind":"identifier"}]},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/left","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/right"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TriangleDirection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"uint8_t","preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection~1right\/title","value":"TriangleDirectionRight","op":"replace"},{"value":[{"text":"TriangleDirectionRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection~1right\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/title","value":"TriangleDirection"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/fragments","value":[{"text":"TriangleDirection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/navigatorTitle","value":[{"kind":"identifier","text":"TriangleDirection"}]},{"value":"TriangleDirectionLeft","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection~1left\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection~1left\/fragments","value":[{"text":"TriangleDirectionLeft","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}