{"metadata":{"roleHeading":"Enumeration","title":"UIContextualActionType","navigatorTitle":[{"kind":"identifier","text":"UIContextualActionType"}],"symbolKind":"enum","externalID":"c:@M@EaseChatUIKit@E@UIContextualActionType","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIContextualActionType"}]},"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH","doc:\/\/org.cocoapods.EaseChatUIKit\/SY"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/uicontextualactiontype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/uicontextualactiontype"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/delete","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/more","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/mute","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/pin","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/read","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/unmute","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/unpin"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/init(rawValue:)"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/Equatable-Implementations","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"UIContextualActionType","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/RawRepresentable-Implementations","url":"\/documentation\/easechatuikit\/uicontextualactiontype\/rawrepresentable-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/unpin":{"abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unpin","kind":"identifier"}],"title":"UIContextualActionType.unpin","url":"\/documentation\/easechatuikit\/uicontextualactiontype\/unpin","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/unpin","navigatorTitle":[{"text":"UIContextualActionTypeUnpin","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/more":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/more","title":"UIContextualActionType.more","navigatorTitle":[{"text":"UIContextualActionTypeMore","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/more","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"more","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/mute":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/mute","title":"UIContextualActionType.mute","navigatorTitle":[{"text":"UIContextualActionTypeMute","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/mute","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mute","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType":{"role":"symbol","title":"UIContextualActionType","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"UIContextualActionType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","url":"\/documentation\/easechatuikit\/uicontextualactiontype"},"doc://org.cocoapods.EaseChatUIKit/SY":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/delete":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/delete","title":"UIContextualActionType.delete","navigatorTitle":[{"text":"UIContextualActionTypeDelete","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/delete","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/read":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/read","title":"UIContextualActionType.read","navigatorTitle":[{"text":"UIContextualActionTypeRead","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/read","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/pin":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/pin","title":"UIContextualActionType.pin","navigatorTitle":[{"text":"UIContextualActionTypePin","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/pin","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pin","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH","type":"unresolvable"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/equatable-implementations","kind":"article","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/unmute":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/unmute","title":"UIContextualActionType.unmute","navigatorTitle":[{"text":"UIContextualActionTypeUnmute","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/unmute","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unmute","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/init(rawValue:)","title":"init(rawValue:)","abstract":[],"url":"\/documentation\/easechatuikit\/uicontextualactiontype\/init(rawvalue:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","value":"UIContextualActionType","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"UIContextualActionType","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"UIContextualActionType","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/delete","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/more","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/mute","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/pin","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/read","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/unmute","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType\/unpin"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIContextualActionType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1unpin\/title","op":"replace","value":"UIContextualActionTypeUnpin"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1unpin\/fragments","value":[{"kind":"identifier","text":"UIContextualActionTypeUnpin"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1more\/title","value":"UIContextualActionTypeMore"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1more\/fragments","value":[{"text":"UIContextualActionTypeMore","kind":"identifier"}],"op":"replace"},{"value":"UIContextualActionTypeMute","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1mute\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1mute\/fragments","value":[{"kind":"identifier","text":"UIContextualActionTypeMute"}]},{"value":"UIContextualActionType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/title","op":"replace"},{"op":"replace","value":[{"text":"UIContextualActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1delete\/title","value":"UIContextualActionTypeDelete","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1delete\/fragments","op":"replace","value":[{"text":"UIContextualActionTypeDelete","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1read\/title","value":"UIContextualActionTypeRead"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1read\/fragments","value":[{"text":"UIContextualActionTypeRead","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1pin\/title","op":"replace","value":"UIContextualActionTypePin"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1pin\/fragments","value":[{"kind":"identifier","text":"UIContextualActionTypePin"}]},{"value":"UIContextualActionTypeUnmute","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1unmute\/title"},{"op":"replace","value":[{"text":"UIContextualActionTypeUnmute","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType~1unmute\/fragments"}]}]}