{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"UIOptions","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"EaseChatUIKit"}],"title":"UIOptions","externalID":"c:@M@EaseChatUIKit@objc(cs)UIOptions","role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"UIOptions","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/enableContact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/loadLocalHistoryMessages","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/saveConversationInfo","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/soundOnReceivedNewMessage"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"UIOptions","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/uioptions"]},{"paths":["\/documentation\/easechatuikit\/uioptions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions/enableContact":{"navigatorTitle":[{"kind":"identifier","text":"enableContact"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"enableContact","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/easechatuikit\/uioptions\/enablecontact","kind":"symbol","abstract":[{"type":"text","text":"Whether using contact list module."}],"title":"enableContact","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/enableContact"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions/soundOnReceivedNewMessage":{"abstract":[{"type":"text","text":"Whether to play a sound when new messages are received"}],"navigatorTitle":[{"text":"soundOnReceivedNewMessage","kind":"identifier"}],"role":"symbol","title":"soundOnReceivedNewMessage","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/soundOnReceivedNewMessage","url":"\/documentation\/easechatuikit\/uioptions\/soundonreceivednewmessage","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"soundOnReceivedNewMessage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions/saveConversationInfo":{"navigatorTitle":[{"text":"saveConversationInfo","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/saveConversationInfo","kind":"symbol","role":"symbol","title":"saveConversationInfo","url":"\/documentation\/easechatuikit\/uioptions\/saveconversationinfo","type":"topic","abstract":[{"type":"text","text":"Whether to store session avatars and nicknames in EaseChatUIKit."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"saveConversationInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions/loadLocalHistoryMessages":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/loadLocalHistoryMessages","abstract":[{"type":"text","text":"Whether load messages from local database."}],"url":"\/documentation\/easechatuikit\/uioptions\/loadlocalhistorymessages","navigatorTitle":[{"kind":"identifier","text":"loadLocalHistoryMessages"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"loadLocalHistoryMessages","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","title":"loadLocalHistoryMessages"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions":{"navigatorTitle":[{"kind":"identifier","text":"UIOptions"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIOptions"}],"url":"\/documentation\/easechatuikit\/uioptions","kind":"symbol","abstract":[],"title":"UIOptions","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions/init":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/init","kind":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/uioptions\/init","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"UIOptions","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"UIOptions"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"UIOptions","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/enableContact","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/loadLocalHistoryMessages","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/saveConversationInfo","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/soundOnReceivedNewMessage"]},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions\/init"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"UIOptions","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1enableContact\/title","op":"replace","value":"enableContact"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1enableContact\/fragments","op":"replace","value":[{"kind":"identifier","text":"enableContact"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1soundOnReceivedNewMessage\/title","value":"soundOnReceivedNewMessage"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1soundOnReceivedNewMessage\/fragments","value":[{"text":"soundOnReceivedNewMessage","kind":"identifier"}],"op":"replace"},{"value":"saveConversationInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1saveConversationInfo\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1saveConversationInfo\/fragments","value":[{"kind":"identifier","text":"saveConversationInfo"}]},{"value":"loadLocalHistoryMessages","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1loadLocalHistoryMessages\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions~1loadLocalHistoryMessages\/fragments","value":[{"kind":"identifier","text":"loadLocalHistoryMessages"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions\/title","value":"UIOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions\/fragments","value":[{"text":"UIOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}