{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement"],"title":"Conforming Types","type":"conformingTypes","kind":"relationships"}],"variants":[{"paths":["\/documentation\/easechatuikit\/userserviceprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/userserviceprotocol"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserServiceProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/bindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/login(userId:token:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/logout(unbindNotificationDeviceToken:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/unBindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/updateUserInfo(userInfo:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/userInfo(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/userInfos(userIds:completion:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"UserServiceProtocol","kind":"identifier"}],"roleHeading":"Protocol","externalID":"c:@M@EaseChatUIKit@objc(pl)UserServiceProtocol","navigatorTitle":[{"text":"UserServiceProtocol","kind":"identifier"}],"title":"UserServiceProtocol","symbolKind":"protocol","modules":[{"name":"EaseChatUIKit"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol/bindUserStateChangedListener(listener:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUserStateChangedListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/bindUserStateChangedListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/userserviceprotocol\/binduserstatechangedlistener(listener:)","title":"bindUserStateChangedListener(listener:)","abstract":[{"type":"text","text":"Bind user state changed listener"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol":{"abstract":[],"kind":"symbol","title":"UserServiceProtocol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserServiceProtocol"}],"url":"\/documentation\/easechatuikit\/userserviceprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserServiceProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol/logout(unbindNotificationDeviceToken:completion:)":{"type":"topic","abstract":[{"text":"Logout SDK","type":"text"}],"title":"logout(unbindNotificationDeviceToken:completion:)","url":"\/documentation\/easechatuikit\/userserviceprotocol\/logout(unbindnotificationdevicetoken:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/logout(unbindNotificationDeviceToken:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"unbindNotificationDeviceToken","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"logoutWithUnbindNotificationDeviceToken:completion:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol/updateUserInfo(userInfo:completion:)":{"abstract":[{"type":"text","text":"Update user info.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage."}],"url":"\/documentation\/easechatuikit\/userserviceprotocol\/updateuserinfo(userinfo:completion:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/updateUserInfo(userInfo:completion:)","required":true,"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"updateUserInfoWithUserInfo:completion:"}],"title":"updateUserInfo(userInfo:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateUserInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","url":"\/documentation\/easechatuikit\/userserviceimplement","title":"UserServiceImplement","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UserServiceImplement","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserServiceImplement"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol/userInfo(userId:completion:)":{"title":"userInfo(userId:completion:)","navigatorTitle":[{"kind":"identifier","text":"userInfoWithUserId:completion:"}],"url":"\/documentation\/easechatuikit\/userserviceprotocol\/userinfo(userid:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/userInfo(userId:completion:)","required":true,"abstract":[{"text":"Get user info by userId.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userInfo"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":"?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol/unBindUserStateChangedListener(listener:)":{"title":"unBindUserStateChangedListener(listener:)","navigatorTitle":[{"text":"unBindUserStateChangedListenerWithListener:","kind":"identifier"}],"kind":"symbol","required":true,"url":"\/documentation\/easechatuikit\/userserviceprotocol\/unbinduserstatechangedlistener(listener:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unBindUserStateChangedListener"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":")"}],"type":"topic","abstract":[{"text":"Unbind user state changed listener","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/unBindUserStateChangedListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol/login(userId:token:completion:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/login(userId:token:completion:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceprotocol\/login(userid:token:completion:)","navigatorTitle":[{"text":"loginWithUserId:token:completion:","kind":"identifier"}],"required":true,"abstract":[{"text":"Login SDK","type":"text"}],"title":"login(userId:token:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"login","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"token","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceProtocol/userInfos(userIds:completion:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"userInfosWithUserIds:completion:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/userInfos(userIds:completion:)","title":"userInfos(userIds:completion:)","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceprotocol\/userinfos(userids:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInfos"},{"text":"(","kind":"text"},{"text":"userIds","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"text":": ([","kind":"text"},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":"], "},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"type":"topic","abstract":[{"type":"text","text":"Get user info by userIds.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"UserServiceProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"UserServiceProtocol","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"UserServiceProtocol"}]},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/bindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/login(userId:token:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/logout(unbindNotificationDeviceToken:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/unBindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/updateUserInfo(userInfo:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/userInfo(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceProtocol\/userInfos(userIds:completion:)"],"generated":true,"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","type":"conformingTypes","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserServiceProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"},{"kind":"text","text":">"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1bindUserStateChangedListener(listener:)\/title","value":"bindUserStateChangedListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1bindUserStateChangedListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"}]},{"value":"UserServiceProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol\/title","op":"replace"},{"op":"replace","value":[{"text":"UserServiceProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol\/navigatorTitle","value":[{"text":"UserServiceProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1logout(unbindNotificationDeviceToken:completion:)\/title","value":"logoutWithUnbindNotificationDeviceToken:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1logout(unbindNotificationDeviceToken:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"logoutWithUnbindNotificationDeviceToken:completion:","kind":"identifier"}]},{"value":"updateUserInfoWithUserInfo:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1updateUserInfo(userInfo:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1updateUserInfo(userInfo:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"updateUserInfoWithUserInfo:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","op":"replace","value":"UserServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","op":"replace","value":[{"text":"UserServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"UserServiceImplement"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1userInfo(userId:completion:)\/title","value":"userInfoWithUserId:completion:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"userInfoWithUserId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1userInfo(userId:completion:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1unBindUserStateChangedListener(listener:)\/title","op":"replace","value":"unBindUserStateChangedListenerWithListener:"},{"value":[{"kind":"text","text":"- "},{"text":"unBindUserStateChangedListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1unBindUserStateChangedListener(listener:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1login(userId:token:completion:)\/title","value":"loginWithUserId:token:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1login(userId:token:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"loginWithUserId:token:completion:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1userInfos(userIds:completion:)\/title","value":"userInfosWithUserIds:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceProtocol~1userInfos(userIds:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userInfosWithUserIds:completion:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}