{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Word16","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"symbolKind":"typealias","modules":[{"name":"EaseChatUIKit"}],"title":"Word16","navigatorTitle":[{"text":"Word16","kind":"identifier"}],"roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Word16","kind":"identifier"}],"externalID":"c:if_rom.h@T@Word16","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/word16"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/word16"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"Word16","kind":"identifier"},{"kind":"text","text":" = "},{"text":"Int16","kind":"typeIdentifier","preciseIdentifier":"s:s5Int16V"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Word16":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Word16"}],"title":"Word16","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Word16","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Word16","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/word16","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Alias","op":"replace"},{"op":"replace","value":"Word16","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"Word16"}]},{"op":"replace","value":[{"kind":"identifier","text":"Word16"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@int16_t","text":"int16_t"},{"kind":"text","text":" "},{"text":"Word16","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"Word16","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Word16\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Word16\/fragments","value":[{"text":"Word16","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"Word16"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Word16\/navigatorTitle"}]}]}