{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":" { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)CommonReactionView(py)message","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"message"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","title":"message"},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/message","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/commonreactionview\/message"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/commonreactionview\/message"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","title":"ChatMessage","abstract":[],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CommonReactionView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView","title":"CommonReactionView","url":"\/documentation\/easechatuikit\/commonreactionview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CommonReactionView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/message":{"url":"\/documentation\/easechatuikit\/commonreactionview\/message","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"}],"navigatorTitle":[{"kind":"identifier","text":"message"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/message","title":"message"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"message"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"message"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMChatMessage","text":"EMChatMessage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"message"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"CommonReactionView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/fragments","value":[{"text":"CommonReactionView","kind":"identifier"}]},{"value":"message","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1message\/title"},{"value":[{"text":"message","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1message\/fragments"}]}]}