{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/easechatuikit\/commonreactionview\/morereactions()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/commonreactionview\/morereactions()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)CommonReactionView(im)moreReactions","symbolKind":"method","navigatorTitle":[{"text":"moreReactions","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"moreReactions","kind":"identifier"},{"text":"()","kind":"text"}],"title":"moreReactions()","role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"moreReactions"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/moreReactions()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/moreReactions()":{"url":"\/documentation\/easechatuikit\/commonreactionview\/morereactions()","navigatorTitle":[{"kind":"identifier","text":"moreReactions"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/moreReactions()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moreReactions","kind":"identifier"},{"kind":"text","text":"()"}],"title":"moreReactions()","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/commonreactionview","navigatorTitle":[{"kind":"identifier","text":"CommonReactionView"}],"abstract":[],"title":"CommonReactionView","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CommonReactionView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"moreReactions"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"moreReactions"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"moreReactions"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1moreReactions()\/title","value":"moreReactions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1moreReactions()\/fragments","value":[{"kind":"text","text":"- "},{"text":"moreReactions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/title","value":"CommonReactionView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/fragments","op":"replace","value":[{"kind":"identifier","text":"CommonReactionView"}]},{"value":[{"text":"CommonReactionView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/navigatorTitle"}]}]}