{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactions","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reactions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Reaction","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Reaction","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)Reaction"},{"text":"] { get }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/commonreactionview\/reactions"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/commonreactionview\/reactions"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"reactions"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)CommonReactionView(py)reactions","roleHeading":"Instance Property","title":"reactions","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reactions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)Reaction","text":"Reaction","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Reaction":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Reaction","kind":"identifier"}],"navigatorTitle":[{"text":"Reaction","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Reaction","kind":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/reaction","role":"symbol","title":"Reaction","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView/reactions":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"reactions"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView\/reactions","title":"reactions","url":"\/documentation\/easechatuikit\/commonreactionview\/reactions","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reactions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"Reaction","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)Reaction"},{"kind":"text","text":"]"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CommonReactionView":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CommonReactionView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CommonReactionView","title":"CommonReactionView","url":"\/documentation\/easechatuikit\/commonreactionview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CommonReactionView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"reactions"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"reactions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<Reaction *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"reactions","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"Reaction","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Reaction\/title"},{"value":[{"kind":"identifier","text":"Reaction"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Reaction\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactions\/title","op":"replace","value":"reactions"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView~1reactions\/fragments","op":"replace","value":[{"text":"reactions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/title","value":"CommonReactionView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CommonReactionView\/fragments","value":[{"kind":"identifier","text":"CommonReactionView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}