{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIContextualAction","text":"UIContextualAction","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIContextualActionStyle","text":"Style","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"actionType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIContextualAction","kind":"typeIdentifier","text":"UIContextualAction"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIContextualActionHandler","text":"Handler"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionChatUIKit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/uicontextualactionchatuikit\/init(title:style:actiontype:handler:)"]},{"paths":["\/documentation\/easechatuikit\/uicontextualactionchatuikit\/init(title:style:actiontype:handler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionChatUIKit\/init(title:style:actionType:handler:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)UIContextualActionChatUIKit(im)initWithTitle:style:actionType:handler:","symbolKind":"init","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIContextualAction","text":"UIContextualAction"},{"text":".","kind":"text"},{"text":"Style","preciseIdentifier":"c:@E@UIContextualActionStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"actionType"},{"kind":"text","text":": "},{"text":"UIContextualActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"text":", ","kind":"text"},{"text":"handler","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIContextualAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIContextualAction"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIContextualActionHandler","text":"Handler"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithTitle:style:actionType:handler:","kind":"identifier"}],"title":"init(title:style:actionType:handler:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionChatUIKit":{"url":"\/documentation\/easechatuikit\/uicontextualactionchatuikit","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionChatUIKit","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"UIContextualActionChatUIKit"}],"type":"topic","role":"symbol","title":"UIContextualActionChatUIKit","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UIContextualActionChatUIKit"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType":{"role":"symbol","title":"UIContextualActionType","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"UIContextualActionType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","url":"\/documentation\/easechatuikit\/uicontextualactiontype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionChatUIKit/init(title:style:actionType:handler:)":{"url":"\/documentation\/easechatuikit\/uicontextualactionchatuikit\/init(title:style:actiontype:handler:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionChatUIKit\/init(title:style:actionType:handler:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTitle:style:actionType:handler:"}],"type":"topic","role":"symbol","title":"init(title:style:actionType:handler:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIContextualAction","text":"UIContextualAction","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIContextualActionStyle","kind":"typeIdentifier","text":"Style"},{"text":", ","kind":"text"},{"text":"actionType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":", "},{"text":"handler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIContextualAction","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIContextualAction"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIContextualActionHandler","kind":"typeIdentifier","text":"Handler"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithTitle:style:actionType:handler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTitle:style:actionType:handler:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UIContextualActionStyle","text":"UIContextualActionStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"actionType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"actionType"},{"text":" ","kind":"text"},{"text":"handler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#*$objc(cs)UIContextualAction#*Q$objc(cs)UIView#BFv(#b))","text":"void (^)(UIContextualAction *, __kindof UIView *, void (^)(_Bool))","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"handler","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionChatUIKit\/title","op":"replace","value":"UIContextualActionChatUIKit"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionChatUIKit\/fragments","op":"replace","value":[{"kind":"identifier","text":"UIContextualActionChatUIKit"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/title","value":"UIContextualActionType"},{"op":"replace","value":[{"text":"UIContextualActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionChatUIKit~1init(title:style:actionType:handler:)\/title","op":"replace","value":"initWithTitle:style:actionType:handler:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionChatUIKit~1init(title:style:actionType:handler:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTitle:style:actionType:handler:","kind":"identifier"}],"op":"replace"}]}]}