{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createCheckbox","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier","text":"UIImageView"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionUserCell\/createCheckbox()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionUserCell"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/reactionusercell\/createcheckbox()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/reactionusercell\/createcheckbox()"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"createCheckbox","kind":"identifier"}],"title":"createCheckbox()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createCheckbox","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ReactionUserCell(im)createCheckbox"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReactionUserCell":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReactionUserCell"}],"kind":"symbol","title":"ReactionUserCell","role":"symbol","url":"\/documentation\/easechatuikit\/reactionusercell","abstract":[],"navigatorTitle":[{"text":"ReactionUserCell","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionUserCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReactionUserCell/createCheckbox()":{"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionUserCell\/createCheckbox()","url":"\/documentation\/easechatuikit\/reactionusercell\/createcheckbox()","abstract":[],"title":"createCheckbox()","navigatorTitle":[{"text":"createCheckbox","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createCheckbox","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createCheckbox"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createCheckbox"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier","text":"UIImageView"},{"kind":"text","text":" *) "},{"text":"createCheckbox","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"ReactionUserCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionUserCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionUserCell\/fragments","value":[{"text":"ReactionUserCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionUserCell~1createCheckbox()\/title","value":"createCheckbox","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionUserCell~1createCheckbox()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"createCheckbox","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}