{"variants":[{"paths":["\/documentation\/easechatuikit\/texteditorview\/minheight"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minHeight"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"title":"minHeight","role":"symbol","externalID":"s:13EaseChatUIKit14TextEditorViewC9minHeight14CoreFoundation7CGFloatVvp","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextEditorView\/minHeight","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"text":"输入范围最小高度， 注意: 表示实际 textView 文本高度。","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextEditorView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minHeight"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TextEditorView/minHeight":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextEditorView\/minHeight","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minHeight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/texteditorview\/minheight","abstract":[{"type":"text","text":"输入范围最小高度， 注意: 表示实际 textView 文本高度。"}],"type":"topic","title":"minHeight"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TextEditorView":{"role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/texteditorview","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextEditorView","title":"TextEditorView","abstract":[{"type":"text","text":"自适应输入框"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TextEditorView","kind":"identifier"}],"navigatorTitle":[{"text":"TextEditorView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextEditorView\/title","op":"replace","value":"TextEditorView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextEditorView\/fragments","value":[{"text":"TextEditorView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextEditorView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"TextEditorView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}