{"variants":[{"paths":["\/documentation\/easechatuikit\/crosszoomanimation\/beforeanimation(animationcontext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation\/beforeAnimation(animationContext:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"beforeAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AnimationContext","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AnimationContext","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"s:13EaseChatUIKit18CrossZoomAnimationC06beforeF016animationContextyAA0fI0V_tF","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"beforeAnimation"},{"kind":"text","text":"("},{"text":"animationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","text":"AnimationContext","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"beforeAnimation(animationContext:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AnimationContext":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimationContext","kind":"identifier"}],"abstract":[],"title":"AnimationContext","role":"symbol","navigatorTitle":[{"text":"AnimationContext","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/animationcontext","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AnimationContext"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossZoomAnimation":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CrossZoomAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"CrossZoomAnimation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/crosszoomanimation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation","type":"topic","title":"CrossZoomAnimation","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossZoomAnimation/beforeAnimation(animationContext:)":{"role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"beforeAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","text":"AnimationContext"},{"kind":"text","text":")"}],"title":"beforeAnimation(animationContext:)","kind":"symbol","url":"\/documentation\/easechatuikit\/crosszoomanimation\/beforeanimation(animationcontext:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation\/beforeAnimation(animationContext:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/title","value":"CrossZoomAnimation"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/fragments","op":"replace","value":[{"text":"CrossZoomAnimation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/navigatorTitle","op":"replace","value":[{"text":"CrossZoomAnimation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}