{"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"scale","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"AnimationOptions","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16AnimationOptionsO"},{"kind":"text","text":", "},{"text":"origin","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PresentationOrigin","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit18PresentationOriginO"},{"text":"?)","kind":"text"}],"title":"init(scale:options:origin:)","role":"symbol","externalID":"s:13EaseChatUIKit18CrossZoomAnimationC5scale7options6originAC14CoreFoundation7CGFloatV_AA0F7OptionsOAA18PresentationOriginOSgtcfc","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation\/init(scale:options:origin:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/crosszoomanimation\/init(scale:options:origin:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"AnimationOptions","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AnimationOptions","preciseIdentifier":"s:13EaseChatUIKit16AnimationOptionsO"},{"text":" = .normal(duration: 0.3), ","kind":"text"},{"kind":"externalParam","text":"origin"},{"text":": ","kind":"text"},{"text":"PresentationOrigin","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationOrigin","preciseIdentifier":"s:13EaseChatUIKit18PresentationOriginO","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationOrigin":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PresentationOrigin","kind":"identifier"}],"abstract":[],"title":"PresentationOrigin","role":"symbol","navigatorTitle":[{"text":"PresentationOrigin","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationOrigin","url":"\/documentation\/easechatuikit\/presentationorigin"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossZoomAnimation":{"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CrossZoomAnimation","kind":"identifier"}],"navigatorTitle":[{"text":"CrossZoomAnimation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/crosszoomanimation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation","type":"topic","title":"CrossZoomAnimation","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CrossZoomAnimation/init(scale:options:origin:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CrossZoomAnimation\/init(scale:options:origin:)","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/crosszoomanimation\/init(scale:options:origin:)","role":"symbol","title":"init(scale:options:origin:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"scale","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AnimationOptions","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16AnimationOptionsO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"origin"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit18PresentationOriginO","text":"PresentationOrigin"},{"text":"?)","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AnimationOptions":{"abstract":[],"kind":"symbol","title":"AnimationOptions","type":"topic","role":"symbol","navigatorTitle":[{"text":"AnimationOptions","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/animationoptions","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnimationOptions"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AnimationOptions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/title","value":"CrossZoomAnimation","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/fragments","value":[{"text":"CrossZoomAnimation","kind":"identifier"}]},{"value":[{"text":"CrossZoomAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CrossZoomAnimation\/navigatorTitle","op":"replace"}]}]}