{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient\/friendRequestDidApprove(byUser:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMContactManagerDelegate.friendRequestDidApprove(byUser:)"},{"text":".","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatuikitclient\/friendrequestdidapprove(byuser:)"]},{"paths":["\/documentation\/easechatuikit\/chatuikitclient\/friendrequestdidapprove(byuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"friendRequestDidApproveByUser:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"friendRequestDidApprove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatUIKitClient(im)friendRequestDidApproveByUser:","title":"friendRequestDidApprove(byUser:)","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient\/EMContactManagerDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"friendRequestDidApprove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byUser","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aUsername","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitClient":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatUIKitClient","kind":"identifier"}],"abstract":[],"role":"symbol","title":"ChatUIKitClient","navigatorTitle":[{"text":"ChatUIKitClient","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatuikitclient","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitClient/EMContactManagerDelegate-Implementations":{"type":"topic","abstract":[],"title":"EMContactManagerDelegate Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/easechatuikit\/chatuikitclient\/emcontactmanagerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient\/EMContactManagerDelegate-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitClient/friendRequestDidApprove(byUser:)":{"role":"symbol","url":"\/documentation\/easechatuikit\/chatuikitclient\/friendrequestdidapprove(byuser:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient\/friendRequestDidApprove(byUser:)","type":"topic","title":"friendRequestDidApprove(byUser:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friendRequestDidApprove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byUser","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"friendRequestDidApproveByUser:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"friendRequestDidApproveByUser:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"friendRequestDidApproveByUser:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"friendRequestDidApproveByUser:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"aUsername","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ChatUIKitClient","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient\/title"},{"op":"replace","value":[{"text":"ChatUIKitClient","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUIKitClient"}]},{"value":"friendRequestDidApproveByUser:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient~1friendRequestDidApprove(byUser:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient~1friendRequestDidApprove(byUser:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"friendRequestDidApproveByUser:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}