{"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitClient(im)unregisterUserStateListener:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"unregisterUserStateListener:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unregisterUserStateListener","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"unregisterUserStateListener(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unregisterUserStateListener"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"listener"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","kind":"typeIdentifier","text":"UserStateChangedListener"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","isActive":true,"type":"reference"}],"type":"paragraph"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient\/unregisterUserStateListener(_:)"},"abstract":[{"text":"Remove monitoring of user status changes.","type":"text"}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatuikitclient\/unregisteruserstatelistener(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatuikitclient\/unregisteruserstatelistener(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitClient":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatUIKitClient","kind":"identifier"}],"abstract":[],"role":"symbol","title":"ChatUIKitClient","navigatorTitle":[{"text":"ChatUIKitClient","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatuikitclient","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitClient/unregisterUserStateListener(_:)":{"type":"topic","url":"\/documentation\/easechatuikit\/chatuikitclient\/unregisteruserstatelistener(_:)","abstract":[{"type":"text","text":"Remove monitoring of user status changes."}],"navigatorTitle":[{"kind":"identifier","text":"unregisterUserStateListener:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitClient\/unregisterUserStateListener(_:)","role":"symbol","title":"unregisterUserStateListener(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterUserStateListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UserStateChangedListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserStateChangedListener"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/userstatechangedlistener","role":"symbol","title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"unregisterUserStateListener:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterUserStateListener:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"unregisterUserStateListener:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)UserStateChangedListener","text":"id<UserStateChangedListener>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"listener","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","type":"reference","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":"ChatUIKitClient","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient\/fragments","value":[{"text":"ChatUIKitClient","kind":"identifier"}]},{"value":[{"text":"ChatUIKitClient","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient~1unregisterUserStateListener(_:)\/title","op":"replace","value":"unregisterUserStateListener:"},{"value":[{"text":"- ","kind":"text"},{"text":"unregisterUserStateListener:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitClient~1unregisterUserStateListener(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener"},{"value":[{"kind":"identifier","text":"UserStateChangedListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/navigatorTitle","value":[{"text":"UserStateChangedListener","kind":"identifier"}]}]}]}