{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker","text":"ComponentViewsActionHooker"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/Chat-swift.class","preciseIdentifier":"s:13EaseChatUIKit26ComponentViewsActionHookerC0B0C","text":"Chat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/chat-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/chat-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/chat-swift.property","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Chat","preciseIdentifier":"s:13EaseChatUIKit26ComponentViewsActionHookerC0B0C"}],"title":"chat","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker(py)chat","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"chat"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker/chat-swift.property":{"role":"symbol","title":"chat","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"chat"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Chat","preciseIdentifier":"s:13EaseChatUIKit26ComponentViewsActionHookerC0B0C"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/chat-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"chat"}],"url":"\/documentation\/easechatuikit\/componentviewsactionhooker\/chat-swift.property"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker":{"role":"symbol","title":"ComponentViewsActionHooker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentViewsActionHooker"}],"abstract":[{"type":"text","text":"A class that handles action events for various component views in the application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentViewsActionHooker"}],"url":"\/documentation\/easechatuikit\/componentviewsactionhooker"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker/Chat-swift.class":{"role":"symbol","title":"ComponentViewsActionHooker.Chat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"abstract":[{"type":"text","text":"A class representing a chat component."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/Chat-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"url":"\/documentation\/easechatuikit\/componentviewsactionhooker\/chat-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"chat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"chat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Chat","preciseIdentifier":"c:objc(cs)Chat"},{"kind":"text","text":" * "},{"kind":"identifier","text":"chat"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1chat-swift.property\/title","value":"chat"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1chat-swift.property\/fragments","value":[{"kind":"identifier","text":"chat"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/title","value":"ComponentViewsActionHooker"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/fragments","value":[{"kind":"identifier","text":"ComponentViewsActionHooker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}