{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/contact","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contact"},{"kind":"text","text":": "},{"text":"ContactHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactHooker","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"contact","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker(py)contact","symbolKind":"property","roleHeading":"Instance Property","title":"contact"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contact"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactHooker","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactHooker"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/contact"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/contact"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker/contact":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contact"},{"text":": ","kind":"text"},{"text":"ContactHooker","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactHooker"}],"type":"topic","abstract":[],"navigatorTitle":[{"text":"contact","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/contact","url":"\/documentation\/easechatuikit\/componentviewsactionhooker\/contact","kind":"symbol","title":"contact"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentViewsActionHooker"}],"type":"topic","abstract":[{"type":"text","text":"A class that handles action events for various component views in the application."}],"navigatorTitle":[{"text":"ComponentViewsActionHooker","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","url":"\/documentation\/easechatuikit\/componentviewsactionhooker","kind":"symbol","title":"ComponentViewsActionHooker"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactHooker":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactHooker"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactHooker","title":"ContactHooker","url":"\/documentation\/easechatuikit\/contacthooker","role":"symbol","abstract":[{"type":"text","text":"A class representing a contact."}],"navigatorTitle":[{"kind":"identifier","text":"ContactHooker"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"contact","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"contact"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"ContactHooker","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactHooker"},{"kind":"text","text":" * "},{"text":"contact","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1contact\/title","value":"contact","op":"replace"},{"value":[{"kind":"identifier","text":"contact"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1contact\/fragments"},{"op":"replace","value":"ComponentViewsActionHooker","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/fragments","value":[{"text":"ComponentViewsActionHooker","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ContactHooker","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactHooker\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactHooker\/fragments","value":[{"kind":"identifier","text":"ContactHooker"}]}]}]}