{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker","text":"ComponentViewsActionHooker"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/Conversation-swift.class","preciseIdentifier":"s:13EaseChatUIKit26ComponentViewsActionHookerC12ConversationC","text":"Conversation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/conversation-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/conversation-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/conversation-swift.property","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"s:13EaseChatUIKit26ComponentViewsActionHookerC12ConversationC"}],"title":"conversation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker(py)conversation","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"conversation"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker/Conversation-swift.class":{"role":"symbol","title":"ComponentViewsActionHooker.Conversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"}],"abstract":[{"type":"text","text":"A class representing a conversation in the chat UI."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/Conversation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/easechatuikit\/componentviewsactionhooker\/conversation-swift.class"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker/conversation-swift.property":{"role":"symbol","title":"conversation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"s:13EaseChatUIKit26ComponentViewsActionHookerC12ConversationC"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/conversation-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"conversation"}],"url":"\/documentation\/easechatuikit\/componentviewsactionhooker\/conversation-swift.property"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker":{"role":"symbol","title":"ComponentViewsActionHooker","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentViewsActionHooker"}],"abstract":[{"type":"text","text":"A class that handles action events for various component views in the application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentViewsActionHooker"}],"url":"\/documentation\/easechatuikit\/componentviewsactionhooker"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"conversation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"conversation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:objc(cs)Conversation"},{"kind":"text","text":" * "},{"kind":"identifier","text":"conversation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1conversation-swift.property\/title","value":"conversation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1conversation-swift.property\/fragments","value":[{"kind":"identifier","text":"conversation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/title","value":"ComponentViewsActionHooker"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/fragments","value":[{"kind":"identifier","text":"ComponentViewsActionHooker"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}