{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/shared"]},{"paths":["\/documentation\/easechatuikit\/componentviewsactionhooker\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/shared","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"shared","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker"}],"role":"symbol","title":"shared","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker(cpy)shared","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Type Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentViewsActionHooker"}],"title":"ComponentViewsActionHooker","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"A class that handles action events for various component views in the application."}],"navigatorTitle":[{"kind":"identifier","text":"ComponentViewsActionHooker"}],"url":"\/documentation\/easechatuikit\/componentviewsactionhooker"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentViewsActionHooker/shared":{"navigatorTitle":[{"text":"shared","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"text":"ComponentViewsActionHooker","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker\/shared","kind":"symbol","title":"shared","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/componentviewsactionhooker\/shared","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"shared"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"shared","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentViewsActionHooker","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ComponentViewsActionHooker","text":"ComponentViewsActionHooker","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"shared","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/title","value":"ComponentViewsActionHooker","op":"replace"},{"value":[{"kind":"identifier","text":"ComponentViewsActionHooker"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker\/navigatorTitle","value":[{"kind":"identifier","text":"ComponentViewsActionHooker"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1shared\/title","value":"shared"},{"value":[{"text":"shared","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentViewsActionHooker~1shared\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}