{"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/contenteditor"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentEditor"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomTextView","text":"CustomTextView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CustomTextView"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/contentEditor"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"externalID":"s:13EaseChatUIKit27GroupInfoEditViewControllerC13contentEditorAA010CustomTextG0Cvp","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"contentEditor","kind":"identifier"},{"kind":"text","text":": "},{"text":"CustomTextView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CustomTextView"}],"role":"symbol","title":"contentEditor"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController/contentEditor":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentEditor"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CustomTextView","text":"CustomTextView","kind":"typeIdentifier"}],"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/contenteditor","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/contentEditor","title":"contentEditor"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController":{"kind":"symbol","title":"GroupInfoEditViewController","abstract":[],"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController","navigatorTitle":[{"kind":"identifier","text":"GroupInfoEditViewController"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoEditViewController"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CustomTextView":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomTextView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomTextView","url":"\/documentation\/easechatuikit\/customtextview","title":"CustomTextView","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"CustomTextView"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController\/title","value":"GroupInfoEditViewController"},{"value":[{"text":"GroupInfoEditViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"GroupInfoEditViewController"}]},{"value":"CustomTextView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomTextView\/title"},{"value":[{"text":"CustomTextView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomTextView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomTextView\/navigatorTitle","op":"replace","value":[{"text":"CustomTextView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}