{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/UITextViewDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textView(_:shouldChangeTextIn:replacementText:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/textview(_:shouldchangetextin:replacementtext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/textview(_:shouldchangetextin:replacementtext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"text":", ","kind":"text"},{"text":"shouldChangeTextIn","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange"},{"text":", ","kind":"text"},{"text":"replacementText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"textView:shouldChangeTextInRange:replacementText:"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupInfoEditViewController(im)textView:shouldChangeTextInRange:replacementText:","title":"textView(_:shouldChangeTextIn:replacementText:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"textView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"shouldChangeTextIn","kind":"externalParam"},{"kind":"text","text":" "},{"text":"range","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"replacementText","kind":"externalParam"},{"kind":"text","text":" "},{"text":"text","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITextViewDelegate.textView(_:shouldChangeTextIn:replacementText:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController/textView(_:shouldChangeTextIn:replacementText:)":{"role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldChangeTextIn","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"replacementText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/textview(_:shouldchangetextin:replacementtext:)","kind":"symbol","navigatorTitle":[{"text":"textView:shouldChangeTextInRange:replacementText:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textView(_:shouldChangeTextIn:replacementText:)","title":"textView(_:shouldChangeTextIn:replacementText:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController/UITextViewDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/uitextviewdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/UITextViewDelegate-Implementations","title":"UITextViewDelegate Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController":{"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller","navigatorTitle":[{"text":"GroupInfoEditViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoEditViewController","kind":"identifier"}],"title":"GroupInfoEditViewController","abstract":[],"role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textView:shouldChangeTextInRange:replacementText:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textView:shouldChangeTextInRange:replacementText:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"textView:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"textView"},{"kind":"text","text":" "},{"text":"shouldChangeTextInRange:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@_NSRange","text":"NSRange","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"range"},{"kind":"text","text":" "},{"kind":"identifier","text":"replacementText:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController~1textView(_:shouldChangeTextIn:replacementText:)\/title","value":"textView:shouldChangeTextInRange:replacementText:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController~1textView(_:shouldChangeTextIn:replacementText:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"textView:shouldChangeTextInRange:replacementText:","kind":"identifier"}]},{"value":"GroupInfoEditViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController\/title"},{"op":"replace","value":[{"text":"GroupInfoEditViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController\/fragments"}]}]}