{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textViewDidChange(_:)"],"generated":true,"title":"Instance Methods"}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"UITextViewDelegate Implementations","role":"collectionGroup","roleHeading":"API Collection"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/UITextViewDelegate-Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/uitextviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/uitextviewdelegate-implementations"]}],"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController":{"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller","navigatorTitle":[{"text":"GroupInfoEditViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoEditViewController","kind":"identifier"}],"title":"GroupInfoEditViewController","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController/textViewDidChange(_:)":{"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/textviewdidchange(_:)","navigatorTitle":[{"kind":"identifier","text":"textViewDidChange:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textViewDidChange(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textViewDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"text":")","kind":"text"}],"title":"textViewDidChange(_:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditViewController/textView(_:shouldChangeTextIn:replacementText:)":{"role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldChangeTextIn","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"replacementText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/easechatuikit\/groupinfoeditviewcontroller\/textview(_:shouldchangetextin:replacementtext:)","kind":"symbol","navigatorTitle":[{"text":"textView:shouldChangeTextInRange:replacementText:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textView(_:shouldChangeTextIn:replacementText:)","title":"textView(_:shouldChangeTextIn:replacementText:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textView(_:shouldChangeTextIn:replacementText:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditViewController\/textViewDidChange(_:)"],"generated":true,"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController\/title","value":"GroupInfoEditViewController"},{"value":[{"kind":"identifier","text":"GroupInfoEditViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController\/fragments","op":"replace"},{"value":"textViewDidChange:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController~1textViewDidChange(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController~1textViewDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"textViewDidChange:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"textView:shouldChangeTextInRange:replacementText:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController~1textView(_:shouldChangeTextIn:replacementText:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditViewController~1textView(_:shouldChangeTextIn:replacementText:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"textView:shouldChangeTextInRange:replacementText:","kind":"identifier"}]}]}]}