{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"titleForHeaderInSection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"symbolKind":"method","role":"symbol","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)ReportOptionsController(im)tableView:titleForHeaderInSection:","title":"tableView(_:titleForHeaderInSection:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"tableView:titleForHeaderInSection:"}],"modules":[{"name":"EaseChatUIKit"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITableViewDataSource.tableView(_:titleForHeaderInSection:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/UITableViewDataSource-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/tableView(_:titleForHeaderInSection:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":": "},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"titleForHeaderInSection"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"section"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/reportoptionscontroller\/tableview(_:titleforheaderinsection:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/reportoptionscontroller\/tableview(_:titleforheaderinsection:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReportOptionsController/UITableViewDataSource-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/UITableViewDataSource-Implementations","abstract":[],"role":"collectionGroup","title":"UITableViewDataSource Implementations","kind":"article","url":"\/documentation\/easechatuikit\/reportoptionscontroller\/uitableviewdatasource-implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReportOptionsController":{"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController","role":"symbol","url":"\/documentation\/easechatuikit\/reportoptionscontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReportOptionsController","kind":"identifier"}],"title":"ReportOptionsController","navigatorTitle":[{"kind":"identifier","text":"ReportOptionsController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReportOptionsController/tableView(_:titleForHeaderInSection:)":{"role":"symbol","url":"\/documentation\/easechatuikit\/reportoptionscontroller\/tableview(_:titleforheaderinsection:)","abstract":[],"navigatorTitle":[{"text":"tableView:titleForHeaderInSection:","kind":"identifier"}],"title":"tableView(_:titleForHeaderInSection:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"titleForHeaderInSection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/tableView(_:titleForHeaderInSection:)","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:titleForHeaderInSection:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"tableView:titleForHeaderInSection:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"titleForHeaderInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"text":"section","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"ReportOptionsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController\/fragments","value":[{"text":"ReportOptionsController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController~1tableView(_:titleForHeaderInSection:)\/title","value":"tableView:titleForHeaderInSection:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:titleForHeaderInSection:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController~1tableView(_:titleForHeaderInSection:)\/fragments"}]}]}