{"metadata":{"role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}]},"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/reportoptionscontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/reportoptionscontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/switchTheme(style:)"],"title":"Instance Methods"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReportOptionsController":{"navigatorTitle":[{"kind":"identifier","text":"ReportOptionsController"}],"abstract":[],"title":"ReportOptionsController","url":"\/documentation\/easechatuikit\/reportoptionscontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ReportOptionsController","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReportOptionsController/switchTheme(style:)":{"navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}],"title":"switchTheme(style:)","url":"\/documentation\/easechatuikit\/reportoptionscontroller\/switchtheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/switchTheme(style:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionsController\/switchTheme(style:)"],"generated":true}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController\/title","op":"replace","value":"ReportOptionsController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ReportOptionsController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController~1switchTheme(style:)\/title","op":"replace","value":"switchThemeWithStyle:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionsController~1switchTheme(style:)\/fragments","op":"replace"}]}]}