{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","kind":"typeIdentifier","text":"MessageReaction"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionDetailCell\/refresh(reaction:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionDetailCell"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/reactiondetailcell\/refresh(reaction:)"]},{"paths":["\/documentation\/easechatuikit\/reactiondetailcell\/refresh(reaction:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","title":"refresh(reaction:)","externalID":"c:@M@EaseChatUIKit@objc(cs)ReactionDetailCell(im)refreshWithReaction:","navigatorTitle":[{"text":"refreshWithReaction:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageReaction","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona"},{"kind":"text","text":")"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReaction":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReaction"}],"kind":"symbol","abstract":[],"title":"MessageReaction","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","navigatorTitle":[{"kind":"identifier","text":"MessageReaction"}],"url":"\/documentation\/easechatuikit\/messagereaction","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReactionDetailCell/refresh(reaction:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionDetailCell\/refresh(reaction:)","url":"\/documentation\/easechatuikit\/reactiondetailcell\/refresh(reaction:)","title":"refresh(reaction:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"refreshWithReaction:","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageReaction","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReactionDetailCell":{"role":"symbol","url":"\/documentation\/easechatuikit\/reactiondetailcell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionDetailCell","title":"ReactionDetailCell","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ReactionDetailCell"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReactionDetailCell","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"refreshWithReaction:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithReaction:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"refreshWithReaction:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMMessageReaction","text":"EMMessageReaction"},{"text":" *) ","kind":"text"},{"text":"reaction","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"refreshWithReaction:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionDetailCell~1refresh(reaction:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"refreshWithReaction:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionDetailCell~1refresh(reaction:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionDetailCell\/title","value":"ReactionDetailCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionDetailCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"ReactionDetailCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}