{"variants":[{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/agorachatmultidevicesdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/agorachatmultidevicesdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/AgoraChatMultiDevicesDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesContactEventDidReceive(_:username:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"AgoraChatMultiDevicesDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesMessageBeRemoved(_:deviceId:)":{"role":"symbol","title":"multiDevicesMessageBeRemoved(_:deviceId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesMessageBeRemoved"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesMessageBeRemoved:deviceId:"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesmessageberemoved(_:deviceid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"role":"symbol","title":"MultiDeviceServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesGroupEventDidReceive(_:groupId:ext:)":{"role":"symbol","title":"multiDevicesGroupEventDidReceive(_:groupId:ext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)":{"role":"symbol","title":"multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesundisturbeventnotifyformotherdevicedata(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesConversationEvent(_:conversationId:conversationType:)":{"role":"symbol","title":"multiDevicesConversationEvent(_:conversationId:conversationType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesConversationEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationType","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesContactEventDidReceive(_:username:ext:)":{"role":"symbol","title":"multiDevicesContactEventDidReceive(_:username:ext:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesContactEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesContactEventDidReceive(_:username:ext:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesContactEventDidReceive:username:ext:"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicescontacteventdidreceive(_:username:ext:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesContactEventDidReceive(_:username:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesMessageBeRemoved(_:deviceId:)\/title","value":"multiDevicesMessageBeRemoved:deviceId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesMessageBeRemoved(_:deviceId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesMessageBeRemoved:deviceId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title","value":"MultiDeviceServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments","value":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/title","value":"multiDevicesGroupEventDidReceive:groupId:ext:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/title","value":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/title","value":"multiDevicesConversationEvent:conversationId:conversationType:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesContactEventDidReceive(_:username:ext:)\/title","value":"multiDevicesContactEventDidReceive:username:ext:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesContactEventDidReceive(_:username:ext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesContactEventDidReceive:username:ext:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}