{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}],"title":"EMMultiDevicesDelegate Implementations","role":"collectionGroup"},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/emmultidevicesdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/emmultidevicesdelegate-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/EMMultiDevicesDelegate-Implementations"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesContactEventDidReceive(_:username:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesMessageBeRemoved(_:deviceId:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"multiDevicesMessageBeRemoved","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"multiDevicesMessageBeRemoved:deviceId:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)","abstract":[],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesmessageberemoved(_:deviceid:)","type":"topic","title":"multiDevicesMessageBeRemoved(_:deviceId:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesContactEventDidReceive(_:username:ext:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesContactEventDidReceive"},{"kind":"text","text":"("},{"preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","kind":"typeIdentifier","text":"MultiDeviceEvent"},{"kind":"text","text":", "},{"text":"username","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"multiDevicesContactEventDidReceive:username:ext:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesContactEventDidReceive(_:username:ext:)","abstract":[],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicescontacteventdidreceive(_:username:ext:)","type":"topic","title":"multiDevicesContactEventDidReceive(_:username:ext:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","abstract":[],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesundisturbeventnotifyformotherdevicedata(_:)","type":"topic","title":"multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesGroupEventDidReceive(_:groupId:ext:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"multiDevicesGroupEventDidReceive:groupId:ext:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","abstract":[],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)","type":"topic","title":"multiDevicesGroupEventDidReceive(_:groupId:ext:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesConversationEvent(_:conversationId:conversationType:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesConversationEvent"},{"kind":"text","text":"("},{"preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","kind":"typeIdentifier","text":"MultiDeviceEvent"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","text":"ChatConversationType"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"multiDevicesConversationEvent:conversationId:conversationType:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","abstract":[],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)","type":"topic","title":"multiDevicesConversationEvent(_:conversationId:conversationType:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","title":"MultiDeviceServiceImplement","url":"\/documentation\/easechatuikit\/multideviceserviceimplement","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceServiceImplement","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesContactEventDidReceive(_:username:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesMessageBeRemoved(_:deviceId:)\/title","value":"multiDevicesMessageBeRemoved:deviceId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesMessageBeRemoved(_:deviceId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiDevicesMessageBeRemoved:deviceId:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesContactEventDidReceive(_:username:ext:)\/title","value":"multiDevicesContactEventDidReceive:username:ext:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesContactEventDidReceive(_:username:ext:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesContactEventDidReceive:username:ext:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/title","value":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/title","value":"multiDevicesGroupEventDidReceive:groupId:ext:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}],"op":"replace"},{"value":"multiDevicesConversationEvent:conversationId:conversationType:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/fragments"},{"value":"MultiDeviceServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title"},{"value":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}