{"sections":[],"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/bindMultiDeviceListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)"],"title":"Instance Methods"}],"variants":[{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multideviceservice-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multideviceservice-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/MultiDeviceService-Implementations","interfaceLanguage":"swift"},"kind":"article","metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}],"title":"MultiDeviceService Implementations"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/unbindMultiDeviceListener(listener:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"}],"abstract":[{"type":"text","text":"Unbind multi device changed listener"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindMultiDeviceListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","kind":"typeIdentifier","text":"MultiDeviceListener"},{"text":")","kind":"text"}],"title":"unbindMultiDeviceListener(listener:)","role":"symbol","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/unbindmultidevicelistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"kind":"symbol","title":"MultiDeviceServiceImplement","role":"symbol","url":"\/documentation\/easechatuikit\/multideviceserviceimplement","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/bindMultiDeviceListener(listener:)":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/bindMultiDeviceListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"bindMultiDeviceListenerWithListener:"}],"abstract":[{"type":"text","text":"Bind multi device changed listener"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindMultiDeviceListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","text":"MultiDeviceListener"},{"text":")","kind":"text"}],"title":"bindMultiDeviceListener(listener:)","role":"symbol","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/bindmultidevicelistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/bindMultiDeviceListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"unbindMultiDeviceListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1unbindMultiDeviceListener(listener:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1unbindMultiDeviceListener(listener:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title","value":"MultiDeviceServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments","op":"replace","value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1bindMultiDeviceListener(listener:)\/title","value":"bindMultiDeviceListenerWithListener:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bindMultiDeviceListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1bindMultiDeviceListener(listener:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}