{"metadata":{"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)MultiDeviceServiceImplement(im)multiDevicesGroupEventDidReceive:groupId:ext:","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiDevicesGroupEventDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiDeviceEvent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?)","kind":"text"}],"title":"multiDevicesGroupEventDidReceive(_:groupId:ext:)"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"EMMultiDevicesDelegate.multiDevicesGroupEventDidReceive(_:groupId:ext:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aEvent","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"groupId","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aGroupId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"ext","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aExt"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/EMMultiDevicesDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceEvent":{"role":"symbol","abstract":[],"title":"MultiDeviceEvent","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiDeviceEvent"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"MultiDeviceEvent","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/multideviceevent"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","title":"MultiDeviceServiceImplement","url":"\/documentation\/easechatuikit\/multideviceserviceimplement","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/EMMultiDevicesDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/EMMultiDevicesDelegate-Implementations","kind":"article","role":"collectionGroup","title":"EMMultiDevicesDelegate Implementations","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/emmultidevicesdelegate-implementations","type":"topic","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesGroupEventDidReceive(_:groupId:ext:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ext"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"multiDevicesGroupEventDidReceive:groupId:ext:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesGroupEventDidReceive(_:groupId:ext:)","abstract":[],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesgroupeventdidreceive(_:groupid:ext:)","type":"topic","title":"multiDevicesGroupEventDidReceive(_:groupId:ext:)"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"multiDevicesGroupEventDidReceive:groupId:ext:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"multiDevicesGroupEventDidReceive:groupId:ext:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"multiDevicesGroupEventDidReceive:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EMMultiDevicesEvent","preciseIdentifier":"c:@E@EMMultiDevicesEvent","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"aEvent","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"groupId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"aGroupId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"ext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"aExt","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title","op":"replace","value":"MultiDeviceServiceImplement"},{"op":"replace","value":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/title","value":"multiDevicesGroupEventDidReceive:groupId:ext:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesGroupEventDidReceive(_:groupId:ext:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiDevicesGroupEventDidReceive:groupId:ext:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}