{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesConversationEvent"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"event"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","text":"ChatConversationType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AgoraChatMultiDevicesDelegate.multiDevicesConversationEvent(_:conversationId:conversationType:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}],"role":"symbol","title":"multiDevicesConversationEvent(_:conversationId:conversationType:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesConversationEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationType","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MultiDeviceServiceImplement(im)multiDevicesConversationEvent:conversationId:conversationType:","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/AgoraChatMultiDevicesDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/AgoraChatMultiDevicesDelegate-Implementations":{"role":"collectionGroup","title":"AgoraChatMultiDevicesDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/AgoraChatMultiDevicesDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/agorachatmultidevicesdelegate-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"role":"symbol","title":"MultiDeviceServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceEvent":{"role":"symbol","title":"MultiDeviceEvent","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceEvent"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MultiDeviceEvent"}],"url":"\/documentation\/easechatuikit\/multideviceevent"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesConversationEvent(_:conversationId:conversationType:)":{"role":"symbol","title":"multiDevicesConversationEvent(_:conversationId:conversationType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesConversationEvent"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatConversationType","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesConversationEvent(_:conversationId:conversationType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesconversationevent(_:conversationid:conversationtype:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatConversationType":{"role":"symbol","title":"ChatConversationType","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatConversationType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatConversationType"}],"url":"\/documentation\/easechatuikit\/chatconversationtype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"multiDevicesConversationEvent:conversationId:conversationType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"multiDevicesConversationEvent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatMultiDevicesEvent","preciseIdentifier":"c:@E@AgoraChatMultiDevicesEvent"},{"kind":"text","text":") "},{"kind":"internalParam","text":"event"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatConversationType","preciseIdentifier":"c:@E@AgoraChatConversationType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"conversationType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title","value":"MultiDeviceServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments","value":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/title","value":"multiDevicesConversationEvent:conversationId:conversationType:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesConversationEvent(_:conversationId:conversationType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesConversationEvent:conversationId:conversationType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}