{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/EMMultiDevicesDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMMultiDevicesDelegate.multiDevicesMessageBeRemoved(_:deviceId:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesMessageBeRemoved"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"deviceId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)"},"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiDevicesMessageBeRemoved"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"deviceId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)MultiDeviceServiceImplement(im)multiDevicesMessageBeRemoved:deviceId:","title":"multiDevicesMessageBeRemoved(_:deviceId:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"multiDevicesMessageBeRemoved:deviceId:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesmessageberemoved(_:deviceid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesmessageberemoved(_:deviceid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","title":"MultiDeviceServiceImplement","url":"\/documentation\/easechatuikit\/multideviceserviceimplement","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesMessageBeRemoved(_:deviceId:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"multiDevicesMessageBeRemoved","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"deviceId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"multiDevicesMessageBeRemoved:deviceId:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesMessageBeRemoved(_:deviceId:)","abstract":[],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesmessageberemoved(_:deviceid:)","type":"topic","title":"multiDevicesMessageBeRemoved(_:deviceId:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/EMMultiDevicesDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/EMMultiDevicesDelegate-Implementations","kind":"article","role":"collectionGroup","title":"EMMultiDevicesDelegate Implementations","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/emmultidevicesdelegate-implementations","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"multiDevicesMessageBeRemoved:deviceId:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiDevicesMessageBeRemoved:deviceId:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"multiDevicesMessageBeRemoved:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"deviceId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"deviceId"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"MultiDeviceServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title"},{"value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesMessageBeRemoved(_:deviceId:)\/title","value":"multiDevicesMessageBeRemoved:deviceId:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesMessageBeRemoved(_:deviceId:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"multiDevicesMessageBeRemoved:deviceId:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}