{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"undisturbData"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesundisturbeventnotifyformotherdevicedata(_:)"]},{"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesundisturbeventnotifyformotherdevicedata(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/EMMultiDevicesDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMMultiDevicesDelegate.multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"},"metadata":{"roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)MultiDeviceServiceImplement(im)multiDevicesUndisturbEventNotifyFormOtherDeviceData:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}],"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"title":"multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"kind":"symbol","title":"multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)","role":"symbol","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multidevicesundisturbeventnotifyformotherdevicedata(_:)","abstract":[],"navigatorTitle":[{"text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"kind":"symbol","title":"MultiDeviceServiceImplement","role":"symbol","url":"\/documentation\/easechatuikit\/multideviceserviceimplement","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MultiDeviceServiceImplement"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/EMMultiDevicesDelegate-Implementations":{"kind":"article","title":"EMMultiDevicesDelegate Implementations","role":"collectionGroup","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/emmultidevicesdelegate-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/EMMultiDevicesDelegate-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"undisturbData","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1multiDevicesUndisturbEventNotifyFormOtherDeviceData(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"multiDevicesUndisturbEventNotifyFormOtherDeviceData:","kind":"identifier"}]},{"op":"replace","value":"MultiDeviceServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title"},{"op":"replace","value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments"}]}]}