{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/unbindmultidevicelistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/multideviceserviceimplement\/unbindmultidevicelistener(listener:)"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Unbind multi device changed listener","type":"text"}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MultiDeviceServiceImplement(im)unbindMultiDeviceListenerWithListener:","roleHeading":"Instance Method","role":"symbol","title":"unbindMultiDeviceListener(listener:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unbindMultiDeviceListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","text":"MultiDeviceListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/MultiDeviceService-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindMultiDeviceListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","text":"MultiDeviceListener","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/unbindMultiDeviceListener(listener:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unbindMultiDeviceListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","kind":"typeIdentifier","text":"MultiDeviceListener"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Unbind multi device changed listener"}],"url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/unbindmultidevicelistener(listener:)","title":"unbindMultiDeviceListener(listener:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/unbindMultiDeviceListener(listener:)","navigatorTitle":[{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement","title":"MultiDeviceServiceImplement","url":"\/documentation\/easechatuikit\/multideviceserviceimplement","role":"symbol","navigatorTitle":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceServiceImplement","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceServiceImplement/MultiDeviceService-Implementations":{"kind":"article","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceServiceImplement\/MultiDeviceService-Implementations","url":"\/documentation\/easechatuikit\/multideviceserviceimplement\/multideviceservice-implementations","title":"MultiDeviceService Implementations","role":"collectionGroup","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceListener":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","title":"MultiDeviceListener","url":"\/documentation\/easechatuikit\/multidevicelistener","role":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceListener","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"unbindMultiDeviceListenerWithListener:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)MultiDeviceListener","text":"id<MultiDeviceListener>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1unbindMultiDeviceListener(listener:)\/title","value":"unbindMultiDeviceListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement~1unbindMultiDeviceListener(listener:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/title","value":"MultiDeviceServiceImplement"},{"value":[{"text":"MultiDeviceServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/title","value":"MultiDeviceListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/fragments","value":[{"kind":"identifier","text":"MultiDeviceListener"}],"op":"replace"}]}]}