{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/center","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition"]]},"metadata":{"title":"MoreMessagePosition.center","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"MoreMessagePositionCenter","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"center","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@E@MoreMessagePosition@MoreMessagePositionCenter","symbolKind":"case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"center"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/moremessageposition\/center"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/moremessageposition\/center"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition":{"title":"MoreMessagePosition","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MoreMessagePosition","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/moremessageposition","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePosition"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/center":{"title":"MoreMessagePosition.center","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/center","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"center","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/moremessageposition\/center","navigatorTitle":[{"text":"MoreMessagePositionCenter","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MoreMessagePositionCenter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MoreMessagePositionCenter","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"MoreMessagePositionCenter","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/title","value":"MoreMessagePosition"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/fragments","value":[{"kind":"identifier","text":"MoreMessagePosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1center\/title","op":"replace","value":"MoreMessagePositionCenter"},{"value":[{"text":"MoreMessagePositionCenter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1center\/fragments"}]}]}