{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/left"},"variants":[{"paths":["\/documentation\/easechatuikit\/moremessageposition\/left"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/moremessageposition\/left"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"title":"MoreMessagePosition.left","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@MoreMessagePosition@MoreMessagePositionLeft","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePositionLeft"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/left":{"navigatorTitle":[{"text":"MoreMessagePositionLeft","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/left","title":"MoreMessagePosition.left","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"url":"\/documentation\/easechatuikit\/moremessageposition\/left"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MoreMessagePosition"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/moremessageposition","role":"symbol","title":"MoreMessagePosition","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePosition"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MoreMessagePositionLeft"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MoreMessagePositionLeft","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"MoreMessagePositionLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1left\/title","op":"replace","value":"MoreMessagePositionLeft"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1left\/fragments","value":[{"kind":"identifier","text":"MoreMessagePositionLeft"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/title","value":"MoreMessagePosition"},{"value":[{"text":"MoreMessagePosition","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/navigatorTitle","value":[{"text":"MoreMessagePosition","kind":"identifier"}]}]}]}