{"variants":[{"paths":["\/documentation\/easechatuikit\/moremessageposition\/right"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/moremessageposition\/right"]}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"case","navigatorTitle":[{"text":"MoreMessagePositionRight","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@E@MoreMessagePosition@MoreMessagePositionRight","title":"MoreMessagePosition.right","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/right","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition":{"title":"MoreMessagePosition","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MoreMessagePosition","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/moremessageposition","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePosition"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MoreMessagePosition/right":{"title":"MoreMessagePosition.right","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MoreMessagePosition\/right","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/moremessageposition\/right","navigatorTitle":[{"kind":"identifier","text":"MoreMessagePositionRight"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"MoreMessagePositionRight","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"MoreMessagePositionRight","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MoreMessagePositionRight","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"MoreMessagePosition","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MoreMessagePosition"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1right\/title","value":"MoreMessagePositionRight","op":"replace"},{"value":[{"text":"MoreMessagePositionRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MoreMessagePosition~1right\/fragments"}]}]}