{"metadata":{"title":"flowLayout","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageInputEmojiView(py)flowLayout","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"flowLayout"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"flowLayout","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UICollectionViewFlowLayout","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}],"roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"flowLayout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","kind":"typeIdentifier","text":"UICollectionViewFlowLayout"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageinputemojiview\/flowlayout"]},{"paths":["\/documentation\/easechatuikit\/messageinputemojiview\/flowlayout"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView\/flowLayout"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputEmojiView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView","title":"MessageInputEmojiView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputEmojiView"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/messageinputemojiview","type":"topic","navigatorTitle":[{"text":"MessageInputEmojiView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputEmojiView/flowLayout":{"abstract":[],"url":"\/documentation\/easechatuikit\/messageinputemojiview\/flowlayout","title":"flowLayout","role":"symbol","navigatorTitle":[{"text":"flowLayout","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"flowLayout","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","kind":"typeIdentifier","text":"UICollectionViewFlowLayout"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView\/flowLayout"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"flowLayout","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"flowLayout"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","kind":"typeIdentifier","text":"UICollectionViewFlowLayout"},{"kind":"text","text":" * "},{"kind":"identifier","text":"flowLayout"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"MessageInputEmojiView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView\/fragments","value":[{"kind":"identifier","text":"MessageInputEmojiView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageInputEmojiView"}]},{"value":"flowLayout","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView~1flowLayout\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView~1flowLayout\/fragments","value":[{"text":"flowLayout","kind":"identifier"}],"op":"replace"}]}]}