{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hitTest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"point"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":", "},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageinputemojiview\/hittest(_:with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messageinputemojiview\/hittest(_:with:)"]}],"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"title":"hitTest(_:with:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hitTest"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hitTest:withEvent:"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageInputEmojiView(im)hitTest:withEvent:"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView\/hitTest(_:with:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputEmojiView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView","title":"MessageInputEmojiView","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputEmojiView"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/messageinputemojiview","type":"topic","navigatorTitle":[{"text":"MessageInputEmojiView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputEmojiView/hitTest(_:with:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputEmojiView\/hitTest(_:with:)","title":"hitTest(_:with:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hitTest"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/messageinputemojiview\/hittest(_:with:)","type":"topic","navigatorTitle":[{"text":"hitTest:withEvent:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"hitTest:withEvent:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hitTest:withEvent:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"hitTest:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"point"},{"kind":"text","text":" "},{"text":"withEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"event"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView\/title","value":"MessageInputEmojiView","op":"replace"},{"value":[{"text":"MessageInputEmojiView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView\/navigatorTitle","value":[{"text":"MessageInputEmojiView","kind":"identifier"}]},{"op":"replace","value":"hitTest:withEvent:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView~1hitTest(_:with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputEmojiView~1hitTest(_:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"hitTest:withEvent:"}]}]}]}