{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/clickaction"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"clickAction","kind":"identifier"},{"text":": (() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","externalID":"s:13EaseChatUIKit21LinkRecognizeTextViewC11clickActionyycSgvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clickAction","kind":"identifier"},{"kind":"text","text":": (() -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")?"}],"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property","title":"clickAction"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/clickAction","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"role":"symbol","url":"\/documentation\/easechatuikit\/linkrecognizetextview","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView/clickAction":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickAction"},{"kind":"text","text":": (() -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"type":"topic","url":"\/documentation\/easechatuikit\/linkrecognizetextview\/clickaction","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/clickAction","title":"clickAction"}},"variantOverrides":[{"patch":[{"value":"LinkRecognizeTextView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/fragments"},{"value":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}