{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/selectedRange","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedRange","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier","text":"NSRange"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/selectedrange"]},{"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/selectedrange"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"selectedRange"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectedRange","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"}],"title":"selectedRange","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)LinkRecognizeTextView(py)selectedRange","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"role":"symbol","url":"\/documentation\/easechatuikit\/linkrecognizetextview","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView/selectedRange":{"navigatorTitle":[{"text":"selectedRange","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"selectedRange","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier","text":"NSRange"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/selectedRange","title":"selectedRange","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/linkrecognizetextview\/selectedrange","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"selectedRange"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"selectedRange","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@S@_NSRange"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectedRange"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/title","value":"LinkRecognizeTextView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/fragments","op":"replace","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}]},{"value":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/navigatorTitle"},{"value":"selectedRange","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView~1selectedRange\/title"},{"op":"replace","value":[{"kind":"identifier","text":"selectedRange"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView~1selectedRange\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}