{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/selectedTextColor","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"selectedTextColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"title":"selectedTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedTextColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"role":"symbol","externalID":"s:13EaseChatUIKit21LinkRecognizeTextViewC08selectedF5ColorSo7UIColorCvp","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/selectedtextcolor"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"role":"symbol","url":"\/documentation\/easechatuikit\/linkrecognizetextview","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView/selectedTextColor":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/selectedTextColor","kind":"symbol","title":"selectedTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectedTextColor","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/linkrecognizetextview\/selectedtextcolor"}},"variantOverrides":[{"patch":[{"value":"LinkRecognizeTextView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/fragments","op":"replace","value":[{"text":"LinkRecognizeTextView","kind":"identifier"}]},{"value":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}