{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/tapaction(gesture:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/tapaction(gesture:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tapAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"gesture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UITapGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)LinkRecognizeTextView(im)tapActionWithGesture:","symbolKind":"method","title":"tapAction(gesture:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tapAction"},{"text":"(","kind":"text"},{"text":"gesture","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITapGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"tapActionWithGesture:","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/tapAction(gesture:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView/tapAction(gesture:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/linkrecognizetextview\/tapaction(gesture:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tapAction","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"gesture"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","text":"UITapGestureRecognizer","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/tapAction(gesture:)","kind":"symbol","type":"topic","title":"tapAction(gesture:)","role":"symbol","navigatorTitle":[{"text":"tapActionWithGesture:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"role":"symbol","url":"\/documentation\/easechatuikit\/linkrecognizetextview","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"tapActionWithGesture:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tapActionWithGesture:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"tapActionWithGesture:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","text":"UITapGestureRecognizer"},{"text":" *) ","kind":"text"},{"text":"gesture","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"tapActionWithGesture:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView~1tapAction(gesture:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView~1tapAction(gesture:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tapActionWithGesture:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/title","value":"LinkRecognizeTextView","op":"replace"},{"op":"replace","value":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/fragments"},{"value":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}