{"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"textViewDidChangeSelection:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)LinkRecognizeTextView(im)textViewDidChangeSelection:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection"},{"text":"(","kind":"text"},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":")"}],"title":"textViewDidChangeSelection(_:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textViewDidChangeSelection"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"textView"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView"},{"kind":"text","text":")"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/textviewdidchangeselection(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/linkrecognizetextview\/textviewdidchangeselection(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITextViewDelegate.textViewDidChangeSelection(_:)"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/textViewDidChangeSelection(_:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView/textViewDidChangeSelection(_:)":{"url":"\/documentation\/easechatuikit\/linkrecognizetextview\/textviewdidchangeselection(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView\/textViewDidChangeSelection(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textViewDidChangeSelection:"}],"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier","text":"UITextView"},{"text":")","kind":"text"}],"title":"textViewDidChangeSelection(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LinkRecognizeTextView":{"title":"LinkRecognizeTextView","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LinkRecognizeTextView"}],"role":"symbol","url":"\/documentation\/easechatuikit\/linkrecognizetextview","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LinkRecognizeTextView","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"LinkRecognizeTextView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"textViewDidChangeSelection:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textViewDidChangeSelection:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"textViewDidChangeSelection:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textView"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView~1textViewDidChangeSelection(_:)\/title","value":"textViewDidChangeSelection:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView~1textViewDidChangeSelection(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textViewDidChangeSelection:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/title","value":"LinkRecognizeTextView"},{"op":"replace","value":[{"text":"LinkRecognizeTextView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LinkRecognizeTextView\/navigatorTitle","value":[{"kind":"identifier","text":"LinkRecognizeTextView"}]}]}]}