{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"indicator","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"}],"roleHeading":"Instance Property","symbolKind":"property","title":"indicator","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ForwardTargetViewController(py)indicator","navigatorTitle":[{"kind":"identifier","text":"indicator"}],"modules":[{"name":"EaseChatUIKit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/indicator"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/forwardtargetviewcontroller\/indicator"]},{"paths":["\/documentation\/easechatuikit\/forwardtargetviewcontroller\/indicator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"indicator","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController":{"title":"ForwardTargetViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ForwardTargetViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ForwardTargetViewController"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController/indicator":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicator"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/indicator","title":"indicator","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller\/indicator","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"indicator"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"indicator"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"indicator","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" * "},{"text":"indicator","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController\/title","value":"ForwardTargetViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ForwardTargetViewController"}]},{"op":"replace","value":"indicator","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1indicator\/title"},{"value":[{"text":"indicator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1indicator\/fragments"}]}]}