{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/switchTheme(style:)"],"generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/easechatuikit\/forwardtargetviewcontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/forwardtargetviewcontroller\/themeswitchprotocol-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController/switchTheme(style:)":{"navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/switchTheme(style:)","kind":"symbol","role":"symbol","title":"switchTheme(style:)","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller\/switchtheme(style:)","type":"topic","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController":{"role":"symbol","navigatorTitle":[{"text":"ForwardTargetViewController","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ForwardTargetViewController"}],"title":"ForwardTargetViewController"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/switchTheme(style:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1switchTheme(style:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController\/title","value":"ForwardTargetViewController"},{"value":[{"kind":"identifier","text":"ForwardTargetViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}