{"variants":[{"paths":["\/documentation\/easechatuikit\/forwardtargetviewcontroller\/uisearchcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/forwardtargetviewcontroller\/uisearchcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/UISearchControllerDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController"]]},"metadata":{"role":"collectionGroup","title":"UISearchControllerDelegate Implementations","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection"},"schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/presentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/willPresentSearchController(_:)"],"anchor":"Instance-Methods"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController/didPresentSearchController(_:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/didPresentSearchController(_:)","title":"didPresentSearchController(_:)","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller\/didpresentsearchcontroller(_:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"didPresentSearchController:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didPresentSearchController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController/willDismissSearchController(_:)":{"title":"willDismissSearchController(_:)","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller\/willdismisssearchcontroller(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"willDismissSearchController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"willDismissSearchController:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/willDismissSearchController(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController/willPresentSearchController(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willPresentSearchController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller\/willpresentsearchcontroller(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/willPresentSearchController(_:)","role":"symbol","kind":"symbol","title":"willPresentSearchController(_:)","navigatorTitle":[{"text":"willPresentSearchController:","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController/didDismissSearchController(_:)":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"didDismissSearchController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/didDismissSearchController(_:)","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller\/diddismisssearchcontroller(_:)","title":"didDismissSearchController(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didDismissSearchController"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ForwardTargetViewController","kind":"identifier"}],"type":"topic","title":"ForwardTargetViewController","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController","navigatorTitle":[{"kind":"identifier","text":"ForwardTargetViewController"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetViewController/presentSearchController(_:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"presentSearchController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"presentSearchController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/presentSearchController(_:)","url":"\/documentation\/easechatuikit\/forwardtargetviewcontroller\/presentsearchcontroller(_:)","abstract":[],"title":"presentSearchController(_:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/presentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetViewController\/willPresentSearchController(_:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1didPresentSearchController(_:)\/title","value":"didPresentSearchController:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1didPresentSearchController(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"didPresentSearchController:","kind":"identifier"}]},{"op":"replace","value":"willDismissSearchController:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1willDismissSearchController(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"willDismissSearchController:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1willDismissSearchController(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1willPresentSearchController(_:)\/title","value":"willPresentSearchController:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1willPresentSearchController(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willPresentSearchController:"}]},{"value":"didDismissSearchController:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1didDismissSearchController(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1didDismissSearchController(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didDismissSearchController:"}],"op":"replace"},{"value":"ForwardTargetViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ForwardTargetViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController\/navigatorTitle","value":[{"text":"ForwardTargetViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1presentSearchController(_:)\/title","value":"presentSearchController:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"presentSearchController:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetViewController~1presentSearchController(_:)\/fragments"}]}]}