{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addActionHandler(actionHandler:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Add UI actions handler."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageListViewActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","type":"reference","isActive":true}]}],"name":"actionHandler"}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistview\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistview\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate","text":"MessageListViewActionEventsDelegate"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageListView(im)addActionHandlerWithActionHandler:","title":"addActionHandler(actionHandler:)","navigatorTitle":[{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/addActionHandler(actionHandler:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageListViewActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addActionHandler(actionHandler:)","abstract":[{"text":"Add UI actions handler.","type":"text"}],"url":"\/documentation\/easechatuikit\/messagelistview\/addactionhandler(actionhandler:)","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"type":"topic","title":"addActionHandler(actionHandler:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListView","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistview","navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","kind":"symbol","title":"MessageListView","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewActionEventsDelegate":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate","navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"type":"topic","title":"MessageListViewActionEventsDelegate","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"addActionHandlerWithActionHandler:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<MessageListViewActionEventsDelegate>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate"},{"text":") ","kind":"text"},{"text":"actionHandler","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"addActionHandlerWithActionHandler:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1addActionHandler(actionHandler:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1addActionHandler(actionHandler:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title","value":"MessageListView","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments","value":[{"text":"MessageListView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate","op":"replace"},{"value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/fragments","op":"replace"}]}]}