{"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistview\/imessagelistviewdriver-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistview\/imessagelistviewdriver-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","title":"IMessageListViewDriver Implementations","role":"collectionGroup"},"kind":"article","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/dataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/firstMessageId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/replyMessageId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrolledBottom"],"title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addMentionUserToField(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/endRefreshing()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/insertMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/processMessage(operation:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/reloadReaction(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/reloadTopic(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/showMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/stopAudioMessagesPlay()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateGroupMessageChatThreadChanged(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateMessageAttachmentStatus(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateMessageStatus(message:status:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateThreadLoadMessagesFinished(finished:)"],"generated":true,"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/stopAudioMessagesPlay()":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopAudioMessagesPlay","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/stopAudioMessagesPlay()","title":"stopAudioMessagesPlay()","navigatorTitle":[{"kind":"identifier","text":"stopAudioMessagesPlay"}],"url":"\/documentation\/easechatuikit\/messagelistview\/stopaudiomessagesplay()","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/showMessage(message:)":{"title":"showMessage(message:)","navigatorTitle":[{"text":"showMessageWithMessage:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/showMessage(message:)","url":"\/documentation\/easechatuikit\/messagelistview\/showmessage(message:)","type":"topic","role":"symbol","abstract":[{"text":"Display new message.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/reloadReaction(message:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reloadReaction","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Reload reaction content."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/reloadReaction(message:)","kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistview\/reloadreaction(message:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"reloadReactionWithMessage:"}],"title":"reloadReaction(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/updateGroupMessageChatThreadChanged(message:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateGroupMessageChatThreadChanged(message:)","role":"symbol","title":"updateGroupMessageChatThreadChanged(message:)","navigatorTitle":[{"text":"updateGroupMessageChatThreadChangedWithMessage:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagelistview\/updategroupmessagechatthreadchanged(message:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateGroupMessageChatThreadChanged"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Chat thread of the group message on changed."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/reloadTopic(message:)":{"title":"reloadTopic(message:)","navigatorTitle":[{"text":"reloadTopicWithMessage:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/reloadTopic(message:)","url":"\/documentation\/easechatuikit\/messagelistview\/reloadtopic(message:)","type":"topic","role":"symbol","abstract":[{"text":"Reload topic content","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"reloadTopic"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/updateThreadLoadMessagesFinished(finished:)":{"title":"updateThreadLoadMessagesFinished(finished:)","navigatorTitle":[{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateThreadLoadMessagesFinished(finished:)","url":"\/documentation\/easechatuikit\/messagelistview\/updatethreadloadmessagesfinished(finished:)","type":"topic","role":"symbol","abstract":[{"text":"Update state on chat thread load messages finished.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateThreadLoadMessagesFinished","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/updateMessageAttachmentStatus(message:)":{"title":"updateMessageAttachmentStatus(message:)","navigatorTitle":[{"text":"updateMessageAttachmentStatusWithMessage:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateMessageAttachmentStatus(message:)","url":"\/documentation\/easechatuikit\/messagelistview\/updatemessageattachmentstatus(message:)","type":"topic","role":"symbol","abstract":[{"text":"Update status on message attachment state changed.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateMessageAttachmentStatus"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/endRefreshing()":{"title":"endRefreshing()","navigatorTitle":[{"kind":"identifier","text":"endRefreshing"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/endRefreshing()","url":"\/documentation\/easechatuikit\/messagelistview\/endrefreshing()","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"endRefreshing","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListView","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistview","navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","kind":"symbol","title":"MessageListView","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/insertMessages(messages:)":{"title":"insertMessages(messages:)","navigatorTitle":[{"text":"insertMessagesWithMessages:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/insertMessages(messages:)","url":"\/documentation\/easechatuikit\/messagelistview\/insertmessages(messages:)","type":"topic","role":"symbol","abstract":[{"text":"Message list pull to load more db messages.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"insertMessages","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/dataSource":{"title":"dataSource","navigatorTitle":[{"kind":"identifier","text":"dataSource"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/dataSource","url":"\/documentation\/easechatuikit\/messagelistview\/datasource","type":"topic","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataSource"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":"]","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/processMessage(operation:message:)":{"title":"processMessage(operation:message:)","navigatorTitle":[{"text":"processMessageWithOperation:message:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/processMessage(operation:message:)","url":"\/documentation\/easechatuikit\/messagelistview\/processmessage(operation:message:)","type":"topic","role":"symbol","abstract":[{"text":"Process messages according to operation type.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"text":"MessageOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageOperation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/addMentionUserToField(user:)":{"title":"addMentionUserToField(user:)","navigatorTitle":[{"kind":"identifier","text":"addMentionUserToFieldWithUser:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addMentionUserToField(user:)","url":"\/documentation\/easechatuikit\/messagelistview\/addmentionusertofield(user:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Add mention user to textfield on needed."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addMentionUserToField","kind":"identifier"},{"text":"(","kind":"text"},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/updateMessageStatus(message:status:)":{"title":"updateMessageStatus(message:status:)","navigatorTitle":[{"text":"updateMessageStatusWithMessage:status:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateMessageStatus(message:status:)","url":"\/documentation\/easechatuikit\/messagelistview\/updatemessagestatus(message:status:)","type":"topic","role":"symbol","abstract":[{"text":"Update message.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateMessageStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus","text":"ChatMessageStatus"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/refreshMessages(messages:)":{"title":"refreshMessages(messages:)","navigatorTitle":[{"text":"refreshMessagesWithMessages:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshMessages(messages:)","url":"\/documentation\/easechatuikit\/messagelistview\/refreshmessages(messages:)","type":"topic","role":"symbol","abstract":[{"text":"Message list on first load show db messages .","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessages"},{"text":"(","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/firstMessageId":{"title":"firstMessageId","navigatorTitle":[{"kind":"identifier","text":"firstMessageId"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/firstMessageId","url":"\/documentation\/easechatuikit\/messagelistview\/firstmessageid","type":"topic","role":"symbol","abstract":[{"text":"Latest message id.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"firstMessageId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/updateAudioMessageStatus(message:play:)":{"title":"updateAudioMessageStatus(message:play:)","navigatorTitle":[{"text":"updateAudioMessageStatusWithMessage:play:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)","url":"\/documentation\/easechatuikit\/messagelistview\/updateaudiomessagestatus(message:play:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Update audio message  on play status changed."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAudioMessageStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":", ","kind":"text"},{"text":"play","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/scrolledBottom":{"title":"scrolledBottom","navigatorTitle":[{"kind":"identifier","text":"scrolledBottom"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrolledBottom","url":"\/documentation\/easechatuikit\/messagelistview\/scrolledbottom","type":"topic","role":"symbol","abstract":[{"text":"Whether scroll view is scrolled to bottom.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"scrolledBottom","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/replyMessageId":{"title":"replyMessageId","navigatorTitle":[{"kind":"identifier","text":"replyMessageId"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/replyMessageId","url":"\/documentation\/easechatuikit\/messagelistview\/replymessageid","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Reply message id."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"replyMessageId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/dataSource","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/firstMessageId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/replyMessageId","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/scrolledBottom"],"title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/addMentionUserToField(user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/endRefreshing()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/insertMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/processMessage(operation:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshMessages(messages:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/reloadReaction(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/reloadTopic(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/showMessage(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/stopAudioMessagesPlay()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateGroupMessageChatThreadChanged(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateMessageAttachmentStatus(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateMessageStatus(message:status:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateThreadLoadMessagesFinished(finished:)"],"generated":true,"title":"Instance Methods"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"stopAudioMessagesPlay","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1stopAudioMessagesPlay()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1stopAudioMessagesPlay()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopAudioMessagesPlay","kind":"identifier"}]},{"op":"replace","value":"showMessageWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1showMessage(message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1showMessage(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showMessageWithMessage:"}]},{"value":"reloadReactionWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1reloadReaction(message:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"reloadReactionWithMessage:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1reloadReaction(message:)\/fragments","op":"replace"},{"op":"replace","value":"updateGroupMessageChatThreadChangedWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateGroupMessageChatThreadChanged(message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateGroupMessageChatThreadChanged(message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"updateGroupMessageChatThreadChangedWithMessage:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1reloadTopic(message:)\/title","value":"reloadTopicWithMessage:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"reloadTopicWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1reloadTopic(message:)\/fragments"},{"op":"replace","value":"updateThreadLoadMessagesFinishedWithFinished:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateThreadLoadMessagesFinished(finished:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateThreadLoadMessagesFinished(finished:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateMessageAttachmentStatus(message:)\/title","op":"replace","value":"updateMessageAttachmentStatusWithMessage:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateMessageAttachmentStatus(message:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"updateMessageAttachmentStatusWithMessage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1endRefreshing()\/title","value":"endRefreshing"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1endRefreshing()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"endRefreshing"}]},{"value":"MessageListView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title"},{"op":"replace","value":[{"text":"MessageListView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments"},{"value":"insertMessagesWithMessages:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1insertMessages(messages:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"insertMessagesWithMessages:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1insertMessages(messages:)\/fragments"},{"op":"replace","value":"dataSource","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1dataSource\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1dataSource\/fragments","value":[{"text":"dataSource","kind":"identifier"}]},{"op":"replace","value":"processMessageWithOperation:message:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1processMessage(operation:message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1processMessage(operation:message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"processMessageWithOperation:message:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1addMentionUserToField(user:)\/title","value":"addMentionUserToFieldWithUser:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1addMentionUserToField(user:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addMentionUserToFieldWithUser:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateMessageStatus(message:status:)\/title","value":"updateMessageStatusWithMessage:status:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateMessageStatusWithMessage:status:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateMessageStatus(message:status:)\/fragments","op":"replace"},{"value":"refreshMessagesWithMessages:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1refreshMessages(messages:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1refreshMessages(messages:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshMessagesWithMessages:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1firstMessageId\/title","op":"replace","value":"firstMessageId"},{"value":[{"text":"firstMessageId","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1firstMessageId\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateAudioMessageStatus(message:play:)\/title","value":"updateAudioMessageStatusWithMessage:play:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateAudioMessageStatus(message:play:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateAudioMessageStatusWithMessage:play:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrolledBottom\/title","value":"scrolledBottom","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1scrolledBottom\/fragments","value":[{"text":"scrolledBottom","kind":"identifier"}]},{"op":"replace","value":"replyMessageId","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1replyMessageId\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1replyMessageId\/fragments","value":[{"text":"replyMessageId","kind":"identifier"}]}]}]}