{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":"])","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"code":"[ChatMessage]","type":"codeVoice"}],"type":"paragraph"}],"name":"messages"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistview\/refreshmessages(messages:)"]},{"paths":["\/documentation\/easechatuikit\/messagelistview\/refreshmessages(messages:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshMessages(messages:)"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"refreshMessagesWithMessages:","kind":"identifier"}],"roleHeading":"Instance Method","title":"refreshMessages(messages:)","modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListView(im)refreshMessagesWithMessages:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations"]]},"abstract":[{"type":"text","text":"Message list on first load show db messages ."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/refreshMessages(messages:)":{"title":"refreshMessages(messages:)","navigatorTitle":[{"text":"refreshMessagesWithMessages:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/refreshMessages(messages:)","url":"\/documentation\/easechatuikit\/messagelistview\/refreshmessages(messages:)","type":"topic","role":"symbol","abstract":[{"text":"Message list on first load show db messages .","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessages"},{"text":"(","kind":"text"},{"text":"messages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","title":"ChatMessage","abstract":[],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListView","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistview","navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","kind":"symbol","title":"MessageListView","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/IMessageListViewDriver-Implementations":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations","title":"IMessageListViewDriver Implementations","url":"\/documentation\/easechatuikit\/messagelistview\/imessagelistviewdriver-implementations","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"refreshMessagesWithMessages:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshMessagesWithMessages:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"refreshMessagesWithMessages:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<EMChatMessage *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"messages"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1refreshMessages(messages:)\/title","value":"refreshMessagesWithMessages:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshMessagesWithMessages:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1refreshMessages(messages:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title","value":"MessageListView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments","value":[{"text":"MessageListView","kind":"identifier"}]}]}]}