{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/replyBar"},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"s:13EaseChatUIKit15MessageListViewC8replyBarAA0d10InputReplyF0Cvp","title":"replyBar","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"replyBar","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageInputReplyView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputReplyView"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistview\/replybar"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"replyBar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputReplyView","text":"MessageInputReplyView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}],"url":"\/documentation\/easechatuikit\/messagelistview","title":"MessageListView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/replyBar":{"url":"\/documentation\/easechatuikit\/messagelistview\/replybar","title":"replyBar","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"replyBar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageInputReplyView","kind":"typeIdentifier","text":"MessageInputReplyView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/replyBar","kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputReplyView":{"kind":"symbol","title":"MessageInputReplyView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputReplyView"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView","navigatorTitle":[{"text":"MessageInputReplyView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messageinputreplyview","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MessageListView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title","op":"replace"},{"value":[{"text":"MessageListView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/navigatorTitle","op":"replace","value":[{"text":"MessageListView","kind":"identifier"}]},{"op":"replace","value":"MessageInputReplyView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView\/title"},{"value":[{"kind":"identifier","text":"MessageInputReplyView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView\/fragments"},{"value":[{"kind":"identifier","text":"MessageInputReplyView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView\/navigatorTitle"}]}]}