{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistview\/showtype"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/showType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MessageListType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageListType"},{"kind":"text","text":" { get }"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView"]]},"sections":[],"metadata":{"symbolKind":"property","externalID":"s:13EaseChatUIKit15MessageListViewC8showTypeAA0deH0Ovp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"showType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageListType","kind":"typeIdentifier","text":"MessageListType"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","title":"showType"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/showType":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/showType","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"showType","kind":"identifier"},{"kind":"text","text":": "},{"text":"MessageListType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageListType"}],"url":"\/documentation\/easechatuikit\/messagelistview\/showtype","role":"symbol","abstract":[],"title":"showType","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}],"url":"\/documentation\/easechatuikit\/messagelistview","title":"MessageListView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType":{"navigatorTitle":[{"kind":"identifier","text":"MessageListType"}],"url":"\/documentation\/easechatuikit\/messagelisttype","title":"MessageListType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListType"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType","kind":"symbol","type":"topic","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"MessageListView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title"},{"value":[{"text":"MessageListView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListView"}]},{"value":"MessageListType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MessageListType"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType\/navigatorTitle","value":[{"text":"MessageListType","kind":"identifier"}],"op":"replace"}]}]}