{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","title":"ThemeSwitchProtocol Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/switchTheme(style:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistview\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistview\/themeswitchprotocol-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/switchTheme(style:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/switchTheme(style:)","type":"topic","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"title":"switchTheme(style:)","url":"\/documentation\/easechatuikit\/messagelistview\/switchtheme(style:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"title":"MessageListView","type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","url":"\/documentation\/easechatuikit\/messagelistview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/switchTheme(style:)"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1switchTheme(style:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1switchTheme(style:)\/fragments","op":"replace"},{"value":"MessageListView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title"},{"value":[{"text":"MessageListView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments","op":"replace"}]}]}