{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"UITableViewDataSource Implementations"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/tableView(_:numberOfRowsInSection:)"],"title":"Instance Methods","generated":true}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistview\/uitableviewdatasource-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistview\/uitableviewdatasource-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"title":"MessageListView","type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","url":"\/documentation\/easechatuikit\/messagelistview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/tableView(_:cellForRowAt:)":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/tableView(_:cellForRowAt:)","title":"tableView(_:cellForRowAt:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelistview\/tableview(_:cellforrowat:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/tableView(_:numberOfRowsInSection:)":{"navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"abstract":[],"title":"tableView(_:numberOfRowsInSection:)","url":"\/documentation\/easechatuikit\/messagelistview\/tableview(_:numberofrowsinsection:)","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/tableView(_:numberOfRowsInSection:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"numberOfRowsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/tableView(_:numberOfRowsInSection:)"],"title":"Instance Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title","value":"MessageListView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments","value":[{"text":"MessageListView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1tableView(_:cellForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}