{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Update audio message  on play status changed."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateAudioMessageStatus"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"play","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"}]}],"name":"message"},{"name":"play","content":[{"type":"paragraph","inlineContent":[{"text":"play or stop","type":"text"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations"]]},"sections":[],"metadata":{"extendedModule":"EaseChatUIKit","title":"updateAudioMessageStatus(message:play:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"updateAudioMessageStatusWithMessage:play:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateAudioMessageStatus","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":", "},{"text":"play","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListView(im)updateAudioMessageStatusWithMessage:play:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistview\/updateaudiomessagestatus(message:play:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistview\/updateaudiomessagestatus(message:play:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/IMessageListViewDriver-Implementations":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/IMessageListViewDriver-Implementations","title":"IMessageListViewDriver Implementations","url":"\/documentation\/easechatuikit\/messagelistview\/imessagelistviewdriver-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageListView","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistview","navigatorTitle":[{"text":"MessageListView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView","kind":"symbol","title":"MessageListView","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","title":"ChatMessage","abstract":[],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListView/updateAudioMessageStatus(message:play:)":{"title":"updateAudioMessageStatus(message:play:)","navigatorTitle":[{"text":"updateAudioMessageStatusWithMessage:play:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListView\/updateAudioMessageStatus(message:play:)","url":"\/documentation\/easechatuikit\/messagelistview\/updateaudiomessagestatus(message:play:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Update audio message  on play status changed."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"updateAudioMessageStatus","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":", ","kind":"text"},{"text":"play","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"updateAudioMessageStatusWithMessage:play:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateAudioMessageStatusWithMessage:play:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"updateAudioMessageStatusWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMChatMessage","text":"EMChatMessage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"play:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"play","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/title","value":"MessageListView"},{"value":[{"kind":"identifier","text":"MessageListView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView\/fragments","op":"replace"},{"op":"replace","value":"updateAudioMessageStatusWithMessage:play:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateAudioMessageStatus(message:play:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"updateAudioMessageStatusWithMessage:play:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListView~1updateAudioMessageStatus(message:play:)\/fragments"}]}]}