{"metadata":{"symbolKind":"method","title":"topicContentHeight()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topicContentHeight"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"topicContentHeight"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageEntity(im)topicContentHeight","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity\/topicContentHeight()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageentity\/topiccontentheight()"]},{"paths":["\/documentation\/easechatuikit\/messageentity\/topiccontentheight()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicContentHeight"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messageentity","title":"MessageEntity","navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity/topicContentHeight()":{"title":"topicContentHeight()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topicContentHeight"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity\/topicContentHeight()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topicContentHeight"}],"type":"topic","url":"\/documentation\/easechatuikit\/messageentity\/topiccontentheight()","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"topicContentHeight"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"topicContentHeight","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":") ","kind":"text"},{"text":"topicContentHeight","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title","op":"replace","value":"MessageEntity"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments","value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity~1topicContentHeight()\/title","value":"topicContentHeight"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"topicContentHeight","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity~1topicContentHeight()\/fragments"}]}]}