{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEditor\/contentHeightConstraint"},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"text":"contentHeightConstraint","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"contentHeightConstraint","kind":"identifier"},{"kind":"text","text":": "},{"text":"NSLayoutConstraint","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint"},{"kind":"text","text":"!"}],"role":"symbol","title":"contentHeightConstraint","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageEditor(py)contentHeightConstraint","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property"},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/messageeditor\/contentheightconstraint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messageeditor\/contentheightconstraint"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentHeightConstraint"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"text":"! { get }","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEditor"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEditor/contentHeightConstraint":{"url":"\/documentation\/easechatuikit\/messageeditor\/contentheightconstraint","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"contentHeightConstraint","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contentHeightConstraint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"title":"contentHeightConstraint","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEditor\/contentHeightConstraint","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEditor":{"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"MessageEditor"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEditor","title":"MessageEditor","url":"\/documentation\/easechatuikit\/messageeditor","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageEditor","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"contentHeightConstraint","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"contentHeightConstraint"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","kind":"typeIdentifier","text":"NSLayoutConstraint"},{"kind":"text","text":" * "},{"text":"contentHeightConstraint","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"contentHeightConstraint","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEditor~1contentHeightConstraint\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEditor~1contentHeightConstraint\/fragments","op":"replace","value":[{"kind":"identifier","text":"contentHeightConstraint"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEditor\/title","value":"MessageEditor"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEditor\/fragments","op":"replace","value":[{"text":"MessageEditor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEditor\/navigatorTitle","op":"replace","value":[{"text":"MessageEditor","kind":"identifier"}]}]}]}