{"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"transferOwner","kind":"identifier"}],"symbolKind":"case","title":"GroupParticipantsOperation.transferOwner","roleHeading":"Case","role":"symbol","externalID":"c:@M@EaseChatUIKit@E@GroupParticipantsOperation@GroupParticipantsOperationTransferOwner","navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsOperationTransferOwner"}],"modules":[{"name":"EaseChatUIKit"}]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsOperation\/transferOwner","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/groupparticipantsoperation\/transferowner"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupparticipantsoperation\/transferowner"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transferOwner"}],"languages":["swift"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsOperation"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsOperation":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsOperation","kind":"symbol","title":"GroupParticipantsOperation","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantsOperation"}],"navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsOperation"}],"abstract":[{"type":"text","text":"An enumeration representing the possible operations for group participants."}],"url":"\/documentation\/easechatuikit\/groupparticipantsoperation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsOperation/transferOwner":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsOperation\/transferOwner","kind":"symbol","title":"GroupParticipantsOperation.transferOwner","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"transferOwner","kind":"identifier"}],"navigatorTitle":[{"text":"GroupParticipantsOperationTransferOwner","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupparticipantsoperation\/transferowner","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GroupParticipantsOperationTransferOwner","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"GroupParticipantsOperationTransferOwner","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"GroupParticipantsOperationTransferOwner","kind":"identifier"}]}]}},{"op":"replace","value":"GroupParticipantsOperation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsOperation\/title"},{"value":[{"text":"GroupParticipantsOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsOperation\/fragments"},{"value":"GroupParticipantsOperationTransferOwner","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsOperation~1transferOwner\/title","op":"replace"},{"value":[{"text":"GroupParticipantsOperationTransferOwner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsOperation~1transferOwner\/fragments"}]}]}