{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"towards","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BubbleTowards","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards"},{"kind":"text","text":", "},{"text":"reuseIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"towards","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards"},{"text":" is towards of the bubble.","type":"text"}]}]},{"name":"reuseIdentifier","content":[{"type":"paragraph","inlineContent":[{"text":"Cell reuse identifier.","type":"text"}]}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/audiomessagecell\/init(towards:reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/audiomessagecell\/init(towards:reuseidentifier:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)AudioMessageCell(im)initWithTowards:reuseIdentifier:","symbolKind":"init","navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(towards:reuseIdentifier:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageCell"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageCell\/init(towards:reuseIdentifier:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","isActive":true,"type":"reference"},{"text":" required init method.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioMessageCell":{"url":"\/documentation\/easechatuikit\/audiomessagecell","title":"AudioMessageCell","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioMessageCell"}],"navigatorTitle":[{"text":"AudioMessageCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageCell","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioMessageCell/init(towards:reuseIdentifier:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","kind":"typeIdentifier","text":"BubbleTowards"},{"kind":"text","text":", "},{"text":"reuseIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageCell\/init(towards:reuseIdentifier:)","title":"init(towards:reuseIdentifier:)","url":"\/documentation\/easechatuikit\/audiomessagecell\/init(towards:reuseidentifier:)","role":"symbol","abstract":[{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","type":"reference","isActive":true},{"text":" required init method.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/BubbleTowards":{"role":"symbol","type":"topic","title":"BubbleTowards","kind":"symbol","url":"\/documentation\/easechatuikit\/bubbletowards","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}],"navigatorTitle":[{"text":"BubbleTowards","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagecell","role":"symbol","title":"MessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithTowards:reuseIdentifier:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"initWithTowards:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"towards","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"reuseIdentifier:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"reuseIdentifier","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"AudioMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageCell\/title"},{"value":[{"text":"AudioMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageCell\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AudioMessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageCell\/navigatorTitle"},{"value":"initWithTowards:reuseIdentifier:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageCell~1init(towards:reuseIdentifier:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageCell~1init(towards:reuseIdentifier:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/title","value":"BubbleTowards","op":"replace"},{"value":[{"text":"BubbleTowards","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"BubbleTowards"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","value":"MessageCell"},{"value":[{"kind":"identifier","text":"MessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/navigatorTitle"}]}]}