{"metadata":{"extendedModule":"EaseChatUIKit","role":"symbol","navigatorTitle":[{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"text":")","kind":"text"}],"title":"addActionHandler(actionHandler:)","roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)PinnedMessagesContainer(im)addActionHandlerWithActionHandler:","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate","kind":"typeIdentifier","text":"PinnedMessagesContainerDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object of conform "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","isActive":true},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"sections":[],"abstract":[{"text":"Add action events listener of ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","type":"reference"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/IPinnedMessagesContainerDriver-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/addActionHandler(actionHandler:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer/addActionHandler(actionHandler:)":{"url":"\/documentation\/easechatuikit\/pinnedmessagescontainer\/addactionhandler(actionhandler:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/addActionHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"kind":"keyword","text":"any"},{"text":" ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"kind":"text","text":")"}],"title":"addActionHandler(actionHandler:)","abstract":[{"type":"text","text":"Add action events listener of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer"},{"type":"text","text":"."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer/IPinnedMessagesContainerDriver-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/IPinnedMessagesContainerDriver-Implementations","kind":"article","abstract":[],"title":"IPinnedMessagesContainerDriver Implementations","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer\/ipinnedmessagescontainerdriver-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate":{"navigatorTitle":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","kind":"symbol","title":"PinnedMessagesContainerDelegate","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer","type":"topic","title":"PinnedMessagesContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"addActionHandlerWithActionHandler:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<PinnedMessagesContainerDelegate>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"actionHandler","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object of conform "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","type":"reference","isActive":true},{"type":"text","text":"."}]}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1addActionHandler(actionHandler:)\/title","value":"addActionHandlerWithActionHandler:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1addActionHandler(actionHandler:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"value":"PinnedMessagesContainerDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/title"},{"value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/title","value":"PinnedMessagesContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/fragments","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}