{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/removeEventHandler(actionHandler:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeEventHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object of conform "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","type":"reference","isActive":true},{"type":"text","text":"."}]}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"Remove action events listener of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/removeeventhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/removeeventhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"removeEventHandler(actionHandler:)","navigatorTitle":[{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeEventHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"text":"any","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)PinnedMessagesContainer(im)removeEventHandlerWithActionHandler:","extendedModule":"EaseChatUIKit","symbolKind":"method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/IPinnedMessagesContainerDriver-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer","type":"topic","title":"PinnedMessagesContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer/removeEventHandler(actionHandler:)":{"url":"\/documentation\/easechatuikit\/pinnedmessagescontainer\/removeeventhandler(actionhandler:)","role":"symbol","title":"removeEventHandler(actionHandler:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/removeEventHandler(actionHandler:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeEventHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"keyword","text":"any"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate","kind":"typeIdentifier","text":"PinnedMessagesContainerDelegate"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeEventHandlerWithActionHandler:","kind":"identifier"}],"abstract":[{"type":"text","text":"Remove action events listener of "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","type":"reference","isActive":true},{"type":"text","text":"."}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer/IPinnedMessagesContainerDriver-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/IPinnedMessagesContainerDriver-Implementations","kind":"article","abstract":[],"title":"IPinnedMessagesContainerDriver Implementations","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer\/ipinnedmessagescontainerdriver-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate":{"navigatorTitle":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","kind":"symbol","title":"PinnedMessagesContainerDelegate","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"removeEventHandlerWithActionHandler:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeEventHandlerWithActionHandler:"},{"text":"(","kind":"text"},{"text":"id<PinnedMessagesContainerDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"kind":"text","text":") "},{"kind":"internalParam","text":"actionHandler"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object of conform "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","isActive":true},{"text":".","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/title","value":"PinnedMessagesContainer"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/fragments","op":"replace","value":[{"kind":"identifier","text":"PinnedMessagesContainer"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/navigatorTitle","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1removeEventHandler(actionHandler:)\/title","op":"replace","value":"removeEventHandlerWithActionHandler:"},{"value":[{"kind":"text","text":"- "},{"text":"removeEventHandlerWithActionHandler:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1removeEventHandler(actionHandler:)\/fragments"},{"value":"PinnedMessagesContainerDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/fragments","value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}