{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"IPinnedMessagesContainerDriver.remove(messageId:)"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/remove(messageId:)"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"removeWithMessageId:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)PinnedMessagesContainer(im)removeWithMessageId:","role":"symbol","title":"remove(messageId:)","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/remove(messageid:)"]},{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/remove(messageid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/IPinnedMessagesContainerDriver-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer/remove(messageId:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/remove(messageId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"text":"removeWithMessageId:","kind":"identifier"}],"title":"remove(messageId:)","type":"topic","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer\/remove(messageid:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer","type":"topic","title":"PinnedMessagesContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer/IPinnedMessagesContainerDriver-Implementations":{"role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/IPinnedMessagesContainerDriver-Implementations","kind":"article","abstract":[],"title":"IPinnedMessagesContainerDriver Implementations","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer\/ipinnedmessagescontainerdriver-implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"removeWithMessageId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeWithMessageId:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeWithMessageId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"messageId","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1remove(messageId:)\/title","value":"removeWithMessageId:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1remove(messageId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeWithMessageId:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"PinnedMessagesContainer","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/fragments","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}]},{"value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}