{"metadata":{"symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"touchesEnded:withEvent:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)PinnedMessagesContainer(im)touchesEnded:withEvent:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"touchesEnded"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch","text":"UITouch"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIEvent","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent"},{"kind":"text","text":"?)"}],"title":"touchesEnded(_:with:)","modules":[{"name":"EaseChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/touchesEnded(_:with:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"touchesEnded"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"touches"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"event"},{"text":": ","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/touchesended(_:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainer\/touchesended(_:with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer","type":"topic","title":"PinnedMessagesContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer/touchesEnded(_:with:)":{"title":"touchesEnded(_:with:)","abstract":[],"navigatorTitle":[{"text":"touchesEnded:withEvent:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"touchesEnded"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"UITouch","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITouch"},{"text":">, ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIEvent","text":"UIEvent"},{"kind":"text","text":"?)"}],"url":"\/documentation\/easechatuikit\/pinnedmessagescontainer\/touchesended(_:with:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer\/touchesEnded(_:with:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"touchesEnded:withEvent:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"touchesEnded:withEvent:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"touchesEnded:"},{"text":"(","kind":"text"},{"text":"NSSet<UITouch *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *) "},{"text":"touches","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withEvent:"},{"text":"(","kind":"text"},{"text":"UIEvent","preciseIdentifier":"c:objc(cs)UIEvent","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"event","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PinnedMessagesContainer","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/fragments","value":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/navigatorTitle","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"touchesEnded:withEvent:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1touchesEnded(_:with:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"touchesEnded:withEvent:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer~1touchesEnded(_:with:)\/fragments"}]}]}