{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/triangleview\/direction"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/triangleview\/direction"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView\/direction","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","externalID":"c:@M@EaseChatUIKit@objc(cs)TriangleView(py)direction","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"direction","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TriangleDirection","preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection"}],"title":"direction","navigatorTitle":[{"text":"direction","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"direction"},{"text":": ","kind":"text"},{"text":"TriangleDirection","preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleView/direction":{"role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/triangleview\/direction","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView\/direction","abstract":[],"title":"direction","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"direction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection","text":"TriangleDirection"}],"navigatorTitle":[{"kind":"identifier","text":"direction"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleView":{"url":"\/documentation\/easechatuikit\/triangleview","title":"TriangleView","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TriangleView"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TriangleView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"TriangleDirection","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/triangledirection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"direction"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"direction"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection","text":"TriangleDirection","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"direction","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView~1direction\/title","value":"direction"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView~1direction\/fragments","value":[{"kind":"identifier","text":"direction"}]},{"value":"TriangleView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView\/title"},{"op":"replace","value":[{"text":"TriangleView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView\/navigatorTitle","value":[{"text":"TriangleView","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/title","op":"replace","value":"TriangleDirection"},{"op":"replace","value":[{"text":"TriangleDirection","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/fragments"},{"value":[{"kind":"identifier","text":"TriangleDirection"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}