{"metadata":{"title":"setDirection(direction:color:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)TriangleView(im)setDirectionWithDirection:color:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDirection"},{"kind":"text","text":"("},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection","text":"TriangleDirection"},{"kind":"text","text":", "},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"setDirectionWithDirection:color:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setDirection","kind":"identifier"},{"kind":"text","text":"("},{"text":"direction","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection","text":"TriangleDirection","preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView\/setDirection(direction:color:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/triangleview\/setdirection(direction:color:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/triangleview\/setdirection(direction:color:)"]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"TriangleDirection","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/triangledirection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleView":{"url":"\/documentation\/easechatuikit\/triangleview","title":"TriangleView","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TriangleView"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"TriangleView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleView/setDirection(direction:color:)":{"type":"topic","navigatorTitle":[{"text":"setDirectionWithDirection:color:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setDirection","kind":"identifier"},{"kind":"text","text":"("},{"text":"direction","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TriangleDirection","preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/triangleview\/setdirection(direction:color:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleView\/setDirection(direction:color:)","abstract":[],"title":"setDirection(direction:color:)","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"setDirectionWithDirection:color:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDirectionWithDirection:color:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setDirectionWithDirection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@TriangleDirection","kind":"typeIdentifier","text":"TriangleDirection","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection"},{"kind":"text","text":") "},{"text":"direction","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"color:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" *) ","kind":"text"},{"text":"color","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"TriangleDirection","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/fragments","value":[{"text":"TriangleDirection","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"TriangleDirection"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView\/title","op":"replace","value":"TriangleView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView\/fragments","value":[{"kind":"identifier","text":"TriangleView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView\/navigatorTitle","value":[{"kind":"identifier","text":"TriangleView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView~1setDirection(direction:color:)\/title","op":"replace","value":"setDirectionWithDirection:color:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleView~1setDirection(direction:color:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setDirectionWithDirection:color:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}