{"abstract":[{"text":"Bind user state changed listener","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindUserStateChangedListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UserStateChangedListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"text":"UserStateChangedListener","type":"text"}]}]}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","roleHeading":"Instance Method","symbolKind":"method","title":"bindUserStateChangedListener(listener:)","navigatorTitle":[{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)UserServiceImplement(im)bindUserStateChangedListenerWithListener:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindUserStateChangedListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"UserStateChangedListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"text":")","kind":"text"}],"role":"symbol"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UserStateChangedListener","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/userstatechangedlistener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","abstract":[],"type":"topic","title":"UserStateChangedListener","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserStateChangedListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserServiceImplement","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceimplement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"title":"UserServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/UserServiceProtocol-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/userserviceimplement\/userserviceprotocol-implementations","title":"UserServiceProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/bindUserStateChangedListener(listener:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindUserStateChangedListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Bind user state changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"title":"bindUserStateChangedListener(listener:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"bindUserStateChangedListenerWithListener:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bindUserStateChangedListenerWithListener:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)UserStateChangedListener","text":"id<UserStateChangedListener>"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener","op":"replace"},{"value":[{"kind":"identifier","text":"UserStateChangedListener"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}]},{"op":"replace","value":"bindUserStateChangedListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"op":"replace"}]}]}