{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/userserviceimplement\/emclientdelegate-implementations"]},{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/emclientdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/EMClientDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"EMClientDelegate Implementations","roleHeading":"API Collection"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement"]]},"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/autoLoginDidCompleteWithError(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/tokenWillExpire(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userDidForbidByServer()"],"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/userAccountDidForced(toLogout:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","kind":"symbol","title":"userAccountDidForced(toLogout:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userAccountDidForced","kind":"identifier"},{"text":"(","kind":"text"},{"text":"toLogout","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"userAccountDidForcedToLogout:"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/userserviceimplement\/useraccountdidforced(tologout:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/tokenDidExpire(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tokenDidExpire","kind":"identifier"},{"kind":"text","text":"("},{"text":"ChatErrorCode","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B9ErrorCodea"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)","title":"tokenDidExpire(_:)","url":"\/documentation\/easechatuikit\/userserviceimplement\/tokendidexpire(_:)","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"tokenDidExpire:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","url":"\/documentation\/easechatuikit\/userserviceimplement","title":"UserServiceImplement","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"UserServiceImplement","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"UserServiceImplement"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/userAccountDidLogin(fromOtherDevice:)":{"title":"userAccountDidLogin(fromOtherDevice:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userAccountDidLogin","kind":"identifier"},{"kind":"text","text":"("},{"text":"fromOtherDevice","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"url":"\/documentation\/easechatuikit\/userserviceimplement\/useraccountdidlogin(fromotherdevice:)","navigatorTitle":[{"text":"userAccountDidLoginFromOtherDevice:","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/connectionStateDidChange(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"connectionStateDidChange","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit15ConnectionStatea","text":"ConnectionState"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","navigatorTitle":[{"kind":"identifier","text":"connectionStateDidChange:"}],"title":"connectionStateDidChange(_:)","url":"\/documentation\/easechatuikit\/userserviceimplement\/connectionstatedidchange(_:)","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/tokenWillExpire(_:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/userserviceimplement\/tokenwillexpire(_:)","title":"tokenWillExpire(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tokenWillExpire","kind":"identifier"},{"kind":"text","text":"("},{"text":"ChatErrorCode","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B9ErrorCodea"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"tokenWillExpire:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/tokenWillExpire(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/userAccountDidRemoveFromServer()":{"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"userAccountDidRemoveFromServer","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","title":"userAccountDidRemoveFromServer()","url":"\/documentation\/easechatuikit\/userserviceimplement\/useraccountdidremovefromserver()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAccountDidRemoveFromServer"},{"kind":"text","text":"()"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/autoLoginDidCompleteWithError(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoLoginDidCompleteWithError"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?)"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/userserviceimplement\/autologindidcompletewitherror(_:)","role":"symbol","navigatorTitle":[{"text":"autoLoginDidCompleteWithError:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/autoLoginDidCompleteWithError(_:)","title":"autoLoginDidCompleteWithError(_:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/userDidForbidByServer()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"userDidForbidByServer","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userDidForbidByServer()","navigatorTitle":[{"text":"userDidForbidByServer","kind":"identifier"}],"title":"userDidForbidByServer()","url":"\/documentation\/easechatuikit\/userserviceimplement\/userdidforbidbyserver()","role":"symbol","kind":"symbol","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/autoLoginDidCompleteWithError(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/connectionStateDidChange(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/tokenDidExpire(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/tokenWillExpire(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidForced(toLogout:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidRemoveFromServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userDidForbidByServer()"],"title":"Instance Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"userAccountDidForcedToLogout:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidForced(toLogout:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidForced(toLogout:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userAccountDidForcedToLogout:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/title","op":"replace","value":"tokenDidExpire:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1tokenDidExpire(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"tokenDidExpire:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","op":"replace","value":"UserServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","op":"replace","value":[{"text":"UserServiceImplement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/navigatorTitle","value":[{"kind":"identifier","text":"UserServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/title","value":"userAccountDidLoginFromOtherDevice:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/title","op":"replace","value":"connectionStateDidChange:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1connectionStateDidChange(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"connectionStateDidChange:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"tokenWillExpire:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1tokenWillExpire(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tokenWillExpire:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1tokenWillExpire(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidRemoveFromServer()\/title","value":"userAccountDidRemoveFromServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidRemoveFromServer()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userAccountDidRemoveFromServer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1autoLoginDidCompleteWithError(_:)\/title","value":"autoLoginDidCompleteWithError:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1autoLoginDidCompleteWithError(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"autoLoginDidCompleteWithError:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userDidForbidByServer()\/title","value":"userDidForbidByServer","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userDidForbidByServer"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userDidForbidByServer()\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}