{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Initializer","title":"init()","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)UserServiceImplement(im)init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/init()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/init()":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/init()","title":"init()","role":"symbol","url":"\/documentation\/easechatuikit\/userserviceimplement\/init()","fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserServiceImplement","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceimplement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"title":"UserServiceImplement"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"init"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement","op":"replace"},{"value":[{"text":"UserServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}