{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback,success or failure"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/logout(completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/logout(completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/logout(completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Logout SDK"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"logout(completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)UserServiceImplement(im)logoutWithCompletion:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"logoutWithCompletion:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/logout(completion:)":{"role":"symbol","title":"logout(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Logout SDK"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/logout(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logoutWithCompletion:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/logout(completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/UserServiceProtocol-Implementations":{"role":"collectionGroup","title":"UserServiceProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/userserviceimplement\/userserviceprotocol-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/easechatuikit\/chaterror"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"role":"symbol","title":"UserServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/easechatuikit\/userserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"logoutWithCompletion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logoutWithCompletion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"logoutWithCompletion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(_Bool, AgoraChatError *)","preciseIdentifier":"c:BFv(#b#*$objc(cs)AgoraChatError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1logout(completion:)\/title","value":"logoutWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1logout(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logoutWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}