{"metadata":{"title":"updateUserInfo(userInfo:completion:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateUserInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"updateUserInfoWithUserInfo:completion:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)UserServiceImplement(im)updateUserInfoWithUserInfo:completion:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateUserInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","text":"EaseProfileProtocol"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"userInfo","content":[{"inlineContent":[{"type":"text","text":"EaseProfileProtocol"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":""}],"type":"paragraph"}],"name":"completion"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/updateuserinfo(userinfo:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/updateuserinfo(userinfo:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations"]]},"abstract":[{"type":"text","text":"Update user info.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserServiceImplement","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceimplement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"title":"UserServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/UserServiceProtocol-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/userserviceimplement\/userserviceprotocol-implementations","title":"UserServiceProtocol Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/updateUserInfo(userInfo:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateUserInfo","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userInfo"},{"text":": ","kind":"text"},{"text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[{"text":"Update user info.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceimplement\/updateuserinfo(userinfo:completion:)","role":"symbol","navigatorTitle":[{"text":"updateUserInfoWithUserInfo:completion:","kind":"identifier"}],"title":"updateUserInfo(userInfo:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"title":"ChatError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chaterror","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"title":"EaseProfileProtocol","abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"EaseProfileProtocol","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/easeprofileprotocol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","navigatorTitle":[{"kind":"identifier","text":"EaseProfileProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateUserInfoWithUserInfo:completion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateUserInfoWithUserInfo:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateUserInfoWithUserInfo:"},{"text":"(","kind":"text"},{"text":"id<EaseProfileProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":") "},{"text":"userInfo","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"EMError","preciseIdentifier":"c:objc(cs)EMError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"UserServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1updateUserInfo(userInfo:completion:)\/title","value":"updateUserInfoWithUserInfo:completion:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateUserInfoWithUserInfo:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1updateUserInfo(userInfo:completion:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title","value":"EaseProfileProtocol"},{"value":[{"kind":"identifier","text":"EaseProfileProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments"}]}]}