{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/EMClientDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMClientDelegate.userAccountDidLogin(fromOtherDevice:)"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userAccountDidLogin","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromOtherDevice","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aDeviceName","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"userAccountDidLogin(fromOtherDevice:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"userAccountDidLoginFromOtherDevice:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userAccountDidLogin","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromOtherDevice"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)UserServiceImplement(im)userAccountDidLoginFromOtherDevice:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/useraccountdidlogin(fromotherdevice:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/userserviceimplement\/useraccountdidlogin(fromotherdevice:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/userAccountDidLogin(fromOtherDevice:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userAccountDidLogin"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromOtherDevice"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[],"title":"userAccountDidLogin(fromOtherDevice:)","navigatorTitle":[{"text":"userAccountDidLoginFromOtherDevice:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userAccountDidLogin(fromOtherDevice:)","url":"\/documentation\/easechatuikit\/userserviceimplement\/useraccountdidlogin(fromotherdevice:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/EMClientDelegate-Implementations":{"title":"EMClientDelegate Implementations","role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/EMClientDelegate-Implementations","url":"\/documentation\/easechatuikit\/userserviceimplement\/emclientdelegate-implementations","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"UserServiceImplement","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","kind":"symbol","url":"\/documentation\/easechatuikit\/userserviceimplement","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"title":"UserServiceImplement"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"userAccountDidLoginFromOtherDevice:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"userAccountDidLoginFromOtherDevice:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"userAccountDidLoginFromOtherDevice:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aDeviceName","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"userAccountDidLoginFromOtherDevice:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"userAccountDidLoginFromOtherDevice:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userAccountDidLogin(fromOtherDevice:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","value":[{"text":"UserServiceImplement","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}