{"variants":[{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/userserviceprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/userserviceimplement\/userserviceprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/UserServiceProtocol-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/login(userId:token:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/logout(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/unBindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userInfo(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userInfos(userIds:completion:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"UserServiceProtocol Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/logout(completion:)":{"role":"symbol","title":"logout(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"logout"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Logout SDK"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/logout(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logoutWithCompletion:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/logout(completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/updateUserInfo(userInfo:completion:)":{"role":"symbol","title":"updateUserInfo(userInfo:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateUserInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update user info.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateUserInfoWithUserInfo:completion:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/updateuserinfo(userinfo:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/userInfo(userId:completion:)":{"role":"symbol","title":"userInfo(userId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get user info by userId.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userInfo(userId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userInfoWithUserId:completion:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/userinfo(userid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/login(userId:token:completion:)":{"role":"symbol","title":"login(userId:token:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"login"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"token"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Login SDK"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/login(userId:token:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loginWithUserId:token:completion:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/login(userid:token:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/unBindUserStateChangedListener(listener:)":{"role":"symbol","title":"unBindUserStateChangedListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unBindUserStateChangedListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unbind user state changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/unBindUserStateChangedListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unBindUserStateChangedListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/unbinduserstatechangedlistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/userInfos(userIds:completion:)":{"role":"symbol","title":"userInfos(userIds:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get user info by userIds.The frequency of api usage for free users is 100 times in 1 second.Upgrading the package can increase the usage."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userInfos(userIds:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userInfosWithUserIds:completion:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/userinfos(userids:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement/bindUserStateChangedListener(listener:)":{"role":"symbol","title":"bindUserStateChangedListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindUserStateChangedListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Bind user state changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/userserviceimplement\/binduserstatechangedlistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserServiceImplement":{"role":"symbol","title":"UserServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UserServiceImplement"}],"url":"\/documentation\/easechatuikit\/userserviceimplement"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/bindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/login(userId:token:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/logout(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/unBindUserStateChangedListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/updateUserInfo(userInfo:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userInfo(userId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserServiceImplement\/userInfos(userIds:completion:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1logout(completion:)\/title","value":"logoutWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1logout(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"logoutWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1updateUserInfo(userInfo:completion:)\/title","value":"updateUserInfoWithUserInfo:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1updateUserInfo(userInfo:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateUserInfoWithUserInfo:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userInfo(userId:completion:)\/title","value":"userInfoWithUserId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userInfo(userId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userInfoWithUserId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1login(userId:token:completion:)\/title","value":"loginWithUserId:token:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1login(userId:token:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loginWithUserId:token:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1unBindUserStateChangedListener(listener:)\/title","value":"unBindUserStateChangedListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1unBindUserStateChangedListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unBindUserStateChangedListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userInfos(userIds:completion:)\/title","value":"userInfosWithUserIds:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1userInfos(userIds:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userInfosWithUserIds:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/title","value":"bindUserStateChangedListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement~1bindUserStateChangedListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindUserStateChangedListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/title","value":"UserServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserServiceImplement\/fragments","value":[{"kind":"identifier","text":"UserServiceImplement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}