{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BlockContactsViewController\/initWithCoder:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BlockContactsViewController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/blockcontactsviewcontroller\/initwithcoder:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"initWithCoder:","externalID":"c:@M@EaseChatUIKit@objc(cs)BlockContactsViewController(im)initWithCoder:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCoder:"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/BlockContactsViewController/initWithCoder:":{"url":"\/documentation\/easechatuikit\/blockcontactsviewcontroller\/initwithcoder:","title":"initWithCoder:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BlockContactsViewController\/initWithCoder:"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/BlockContactsViewController":{"role":"symbol","title":"BlockContactsViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BlockContactsViewController","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/blockcontactsviewcontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BlockContactsViewController","kind":"identifier"}],"navigatorTitle":[{"text":"BlockContactsViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"BlockContactsViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BlockContactsViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"BlockContactsViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BlockContactsViewController\/fragments"},{"value":[{"kind":"identifier","text":"BlockContactsViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BlockContactsViewController\/navigatorTitle"}]}]}