{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onGroupEventDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"users","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}]}]},{"parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent"}]}]},{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the group."}]}]},{"name":"users","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"[UserId]."}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/multidevicelistener\/ongroupeventdidchanged(event:groupid:users:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/multidevicelistener\/ongroupeventdidchanged(event:groupid:users:)"]}],"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"title":"onGroupEventDidChanged(event:groupId:users:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onGroupEventDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"users","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"onGroupEventDidChangedWithEvent:groupId:users:","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener(im)onGroupEventDidChangedWithEvent:groupId:users:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener\/onGroupEventDidChanged(event:groupId:users:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When a event of group changes on other devices"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceListener/onGroupEventDidChanged(event:groupId:users:)":{"abstract":[{"type":"text","text":"When a event of group changes on other devices"}],"navigatorTitle":[{"text":"onGroupEventDidChangedWithEvent:groupId:users:","kind":"identifier"}],"title":"onGroupEventDidChanged(event:groupId:users:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener\/onGroupEventDidChanged(event:groupId:users:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onGroupEventDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","kind":"typeIdentifier","text":"MultiDeviceEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"users","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/multidevicelistener\/ongroupeventdidchanged(event:groupid:users:)","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceEvent":{"title":"MultiDeviceEvent","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceEvent","kind":"identifier"}],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/multidevicelistener","kind":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"abstract":[],"title":"MultiDeviceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceListener","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onGroupEventDidChangedWithEvent:groupId:users:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onGroupEventDidChangedWithEvent:groupId:users:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"onGroupEventDidChangedWithEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EMMultiDevicesEvent","kind":"typeIdentifier","preciseIdentifier":"c:@E@EMMultiDevicesEvent"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":" "},{"text":"groupId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"users:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"users"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","type":"reference","isActive":true}]}],"name":"event"},{"name":"groupId","content":[{"inlineContent":[{"type":"text","text":"The id of the group."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"[UserId].","type":"text"}]}],"name":"users"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener~1onGroupEventDidChanged(event:groupId:users:)\/title","value":"onGroupEventDidChangedWithEvent:groupId:users:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener~1onGroupEventDidChanged(event:groupId:users:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onGroupEventDidChangedWithEvent:groupId:users:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/title","value":"MultiDeviceListener","op":"replace"},{"value":[{"kind":"identifier","text":"MultiDeviceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/navigatorTitle","value":[{"kind":"identifier","text":"MultiDeviceListener"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}