{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertStyle"},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"alertStyle"}],"modules":[{"name":"EaseChatUIKit"}],"title":"alertStyle","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)Appearance(cpy)alertStyle","role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"alertStyle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AlertStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@AlertStyle"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alertStyle"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle","text":"AlertStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@AlertStyle","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/appearance\/alertstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/appearance\/alertstyle"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance"]]},"abstract":[{"text":"The corner radius of the alert view.","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","type":"reference"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"title":"AlertView","abstract":[],"url":"\/documentation\/easechatuikit\/alertview","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/alertStyle":{"navigatorTitle":[{"text":"alertStyle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The corner radius of the alert view."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/alertStyle","title":"alertStyle","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"alertStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"AlertStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@AlertStyle"}],"role":"symbol","url":"\/documentation\/easechatuikit\/appearance\/alertstyle","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertStyle":{"navigatorTitle":[{"kind":"identifier","text":"AlertStyle"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle","title":"AlertStyle","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertStyle","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/alertstyle","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"alertStyle","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"alertStyle"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertStyle","text":"AlertStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@AlertStyle","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"alertStyle"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"AlertView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}]},{"value":"Appearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title"},{"value":[{"text":"Appearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","op":"replace"},{"value":"alertStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1alertStyle\/title"},{"value":[{"kind":"identifier","text":"alertStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1alertStyle\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle\/title","value":"AlertStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertStyle\/fragments","value":[{"kind":"identifier","text":"AlertStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}