{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objcMembers"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/appearance\/chat-swift.class"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject","doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP","doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.EaseChatUIKit\/SQ","doc:\/\/org.cocoapods.EaseChatUIKit\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/audioDuration","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/bubbleStyle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/contentStyle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/dateFormatOtherDay","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/dateFormatToday","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/imageMessageCorner","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/imagePlaceHolder","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/inputBarCorner","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/inputExtendActions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/inputPlaceHolder","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/maxInputHeight","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/messageLongPressedActions","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/receiveAudioAnimationImages","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/receiveBubbleColor","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/receiveTextColor","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/reportSelectionReasons","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/reportSelectionTags","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/sendAudioAnimationImages","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/sendBubbleColor","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/sendTextColor","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/videoPlaceHolder"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"title":"Appearance.Chat","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:13EaseChatUIKit10AppearanceC0B0C","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"Chat"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/dateFormatOtherDay":{"role":"symbol","title":"dateFormatOtherDay","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateFormatOtherDay"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Setting this property changes the date format displayed within a single session."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/dateFormatOtherDay","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/dateformatotherday"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/reportSelectionTags":{"role":"symbol","title":"reportSelectionTags","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportSelectionTags"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The label for message reporting types."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/reportSelectionTags","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/reportselectiontags"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/sendBubbleColor":{"role":"symbol","title":"sendBubbleColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendBubbleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The bubble color of the sender of the message."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/sendBubbleColor","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/sendbubblecolor"},"doc://org.cocoapods.EaseChatUIKit/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(cs)NSObject"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/contentStyle":{"role":"symbol","title":"contentStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentStyle"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentDisplayStyle","preciseIdentifier":"s:13EaseChatUIKit11MessageCellC19ContentDisplayStyleO"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Message content display style.You can use these four styles to combine a style array you want. Bubbles are all provided by default, except for picture messages and video messages."},{"type":"codeVoice","code":"MessageCell.ContentDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/contentStyle","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/contentstyle"},"doc://org.cocoapods.EaseChatUIKit/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s7CVarArgP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/sendAudioAnimationImages":{"role":"symbol","title":"sendAudioAnimationImages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendAudioAnimationImages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The resource image of the audio animation played after the sender of the audio message clicks"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/sendAudioAnimationImages","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/sendaudioanimationimages"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/imageMessageCorner":{"role":"symbol","title":"imageMessageCorner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageMessageCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The corner of the image message."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/imageMessageCorner","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/imagemessagecorner"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/messageLongPressedActions":{"role":"symbol","title":"messageLongPressedActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageLongPressedActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"ActionSheet data source of the message being long pressed."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/messageLongPressedActions","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/messagelongpressedactions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/bubbleStyle":{"role":"symbol","title":"bubbleStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bubbleStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"BubbleDisplayStyle","preciseIdentifier":"s:13EaseChatUIKit11MessageCellC18BubbleDisplayStyleO"}],"abstract":[{"type":"text","text":"Message bubble display style."},{"type":"codeVoice","code":"MessageCell.BubbleDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/bubbleStyle","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/bubblestyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol":{"role":"symbol","title":"ActionSheetItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/easechatuikit\/actionsheetitemprotocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class":{"role":"symbol","title":"Appearance.Chat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/receiveAudioAnimationImages":{"role":"symbol","title":"receiveAudioAnimationImages","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiveAudioAnimationImages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The resource image of the audio animation played after the recipient of the audio message clicks"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/receiveAudioAnimationImages","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/receiveaudioanimationimages"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/videoPlaceHolder":{"role":"symbol","title":"videoPlaceHolder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"videoPlaceHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Default placeholder image for video messages."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/videoPlaceHolder","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/videoplaceholder"},"doc://org.cocoapods.EaseChatUIKit/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SH"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/inputExtendActions":{"role":"symbol","title":"inputExtendActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputExtendActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"A menu item pops up when you click the "},{"type":"codeVoice","code":"+"},{"type":"text","text":" button on the input box"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/inputExtendActions","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/inputextendactions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/sendTextColor":{"role":"symbol","title":"sendTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sendTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The color of the sender of the text message."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/sendTextColor","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/sendtextcolor"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/receiveBubbleColor":{"role":"symbol","title":"receiveBubbleColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiveBubbleColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The bubble color of the recipient of the message."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/receiveBubbleColor","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/receivebubblecolor"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/inputBarCorner":{"role":"symbol","title":"inputBarCorner","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputBarCorner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CornerRadius","preciseIdentifier":"s:13EaseChatUIKit12CornerRadiusO"}],"abstract":[{"type":"text","text":"The corner radius of "},{"type":"codeVoice","code":"ChatInputBar"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/inputBarCorner","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/inputbarcorner"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/inputPlaceHolder":{"role":"symbol","title":"inputPlaceHolder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"inputPlaceHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The placeholder text in "},{"type":"codeVoice","code":"ChatInputBar"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/inputPlaceHolder","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/inputplaceholder"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/reportSelectionReasons":{"role":"symbol","title":"reportSelectionReasons","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reportSelectionReasons"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The label for message reporting reason."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/reportSelectionReasons","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/reportselectionreasons"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/audioDuration":{"role":"symbol","title":"audioDuration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Record audio limitation."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/audioDuration","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/audioduration"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/receiveTextColor":{"role":"symbol","title":"receiveTextColor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiveTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"The color of the recipient of the text message."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/receiveTextColor","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/receivetextcolor"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/maxInputHeight":{"role":"symbol","title":"maxInputHeight","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxInputHeight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"The height limit of the input box in "},{"type":"codeVoice","code":"ChatInputBar"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/maxInputHeight","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/maxinputheight"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/imagePlaceHolder":{"role":"symbol","title":"imagePlaceHolder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePlaceHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Default placeholder image for picture messages."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/imagePlaceHolder","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/imageplaceholder"},"doc://org.cocoapods.EaseChatUIKit/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s23CustomStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/dateFormatToday":{"role":"symbol","title":"dateFormatToday","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateFormatToday"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Setting this property changes the date format displayed within a single session."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/dateFormatToday","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/dateformattoday"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/SQ"},"doc://org.cocoapods.EaseChatUIKit/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.EaseChatUIKit/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/title","value":"ActionSheetItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}