{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)Appearance","text":"Appearance"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Conversation-swift.class","preciseIdentifier":"s:13EaseChatUIKit10AppearanceC12ConversationC","text":"Conversation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/appearance\/conversation-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/appearance\/conversation-swift.type.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/conversation-swift.type.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Conversation Component"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Appearance","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)Appearance"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"s:13EaseChatUIKit10AppearanceC12ConversationC"}],"title":"conversation","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)Appearance(cpy)conversation","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"conversation"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/conversation-swift.type.property":{"role":"symbol","title":"conversation","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Appearance","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)Appearance"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"s:13EaseChatUIKit10AppearanceC12ConversationC"}],"abstract":[{"type":"text","text":"Conversation Component"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/conversation-swift.type.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"conversation"}],"url":"\/documentation\/easechatuikit\/appearance\/conversation-swift.type.property"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Conversation-swift.class":{"role":"symbol","title":"Appearance.Conversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Conversation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/easechatuikit\/appearance\/conversation-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"conversation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"conversation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Conversation","preciseIdentifier":"c:objc(cs)Conversation"},{"kind":"text","text":" * "},{"kind":"identifier","text":"conversation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1conversation-swift.type.property\/title","value":"conversation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance~1conversation-swift.type.property\/fragments","value":[{"kind":"identifier","text":"conversation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}