{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity\/message","interfaceLanguage":"swift"},"metadata":{"title":"message","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"}],"symbolKind":"property","navigatorTitle":[{"text":"message","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity(py)message"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pinnedmessageentity\/message"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pinnedmessageentity\/message"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","abstract":[],"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessageEntity":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessageentity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity","navigatorTitle":[{"kind":"identifier","text":"PinnedMessageEntity"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PinnedMessageEntity","kind":"identifier"}],"title":"PinnedMessageEntity","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessageEntity/message":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity\/message","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/pinnedmessageentity\/message","abstract":[],"title":"message","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"message"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"message"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"message"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"EMChatMessage","preciseIdentifier":"c:objc(cs)EMChatMessage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"message"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"PinnedMessageEntity","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/fragments","op":"replace","value":[{"text":"PinnedMessageEntity","kind":"identifier"}]},{"op":"replace","value":[{"text":"PinnedMessageEntity","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity~1message\/title","value":"message","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity~1message\/fragments","op":"replace","value":[{"kind":"identifier","text":"message"}]}]}]}