{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionEmojiCell"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ReactionEmojiCell(im)initWithCoder:","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"EaseChatUIKit"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionEmojiCell\/init(coder:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/reactionemojicell\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/reactionemojicell\/init(coder:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReactionEmojiCell":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ReactionEmojiCell"}],"url":"\/documentation\/easechatuikit\/reactionemojicell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionEmojiCell","kind":"symbol","title":"ReactionEmojiCell","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ReactionEmojiCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReactionEmojiCell/init(coder:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"title":"init(coder:)","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReactionEmojiCell\/init(coder:)","type":"topic","url":"\/documentation\/easechatuikit\/reactionemojicell\/init(coder:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithCoder:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"ReactionEmojiCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionEmojiCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionEmojiCell\/fragments","value":[{"kind":"identifier","text":"ReactionEmojiCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionEmojiCell\/navigatorTitle","value":[{"kind":"identifier","text":"ReactionEmojiCell"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionEmojiCell~1init(coder:)\/title","op":"replace","value":"initWithCoder:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReactionEmojiCell~1init(coder:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}]}]}]}