{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageTopicView\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"ThemeSwitchProtocol Implementations","roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagetopicview\/themeswitchprotocol-implementations"]},{"paths":["\/documentation\/easechatuikit\/messagetopicview\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageTopicView\/switchTheme(style:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageTopicView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageTopicView":{"title":"MessageTopicView","url":"\/documentation\/easechatuikit\/messagetopicview","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageTopicView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageTopicView","navigatorTitle":[{"text":"MessageTopicView","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageTopicView/switchTheme(style:)":{"url":"\/documentation\/easechatuikit\/messagetopicview\/switchtheme(style:)","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageTopicView\/switchTheme(style:)","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"title":"switchTheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageTopicView\/switchTheme(style:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageTopicView\/title","value":"MessageTopicView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageTopicView\/fragments","value":[{"text":"MessageTopicView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageTopicView\/navigatorTitle","value":[{"kind":"identifier","text":"MessageTopicView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageTopicView~1switchTheme(style:)\/title","value":"switchThemeWithStyle:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageTopicView~1switchTheme(style:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}