{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadListController\/scrollViewDidEndDecelerating(_:)"},"metadata":{"navigatorTitle":[{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"title":"scrollViewDidEndDecelerating(_:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadListController(im)scrollViewDidEndDecelerating:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIScrollViewDelegate.scrollViewDidEndDecelerating(_:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadListController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadListController\/UIScrollViewDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"scrollView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadlistcontroller\/scrollviewdidenddecelerating(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadlistcontroller\/scrollviewdidenddecelerating(_:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadListController/UIScrollViewDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadlistcontroller\/uiscrollviewdelegate-implementations","title":"UIScrollViewDelegate Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadListController\/UIScrollViewDelegate-Implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadListController/scrollViewDidEndDecelerating(_:)":{"kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadlistcontroller\/scrollviewdidenddecelerating(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"title":"scrollViewDidEndDecelerating(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadListController\/scrollViewDidEndDecelerating(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadListController":{"type":"topic","kind":"symbol","title":"ChatThreadListController","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ChatThreadListController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadlistcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadListController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadListController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"scrollViewDidEndDecelerating:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadListController~1scrollViewDidEndDecelerating(_:)\/title","op":"replace","value":"scrollViewDidEndDecelerating:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadListController~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}]},{"value":"ChatThreadListController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadListController\/title"},{"value":[{"text":"ChatThreadListController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadListController\/fragments"},{"value":[{"kind":"identifier","text":"ChatThreadListController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadListController\/navigatorTitle"}]}]}