{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener\/onGroupChatThreadEventOccur(type:event:)"},"kind":"symbol","metadata":{"modules":[{"name":"EaseChatUIKit"}],"required":true,"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupChatThreadEventOccur"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","text":"GroupChatThreadEventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GroupChatThreadEvent","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener(im)onGroupChatThreadEventOccurWithType:event:","navigatorTitle":[{"text":"onGroupChatThreadEventOccurWithType:event:","kind":"identifier"}],"symbolKind":"method","title":"onGroupChatThreadEventOccur(type:event:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener"]]},"abstract":[{"text":"Some event occur on group chat thread.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupchatthreadeventlistener\/ongroupchatthreadeventoccur(type:event:)"]},{"paths":["\/documentation\/easechatuikit\/groupchatthreadeventlistener\/ongroupchatthreadeventoccur(type:event:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onGroupChatThreadEventOccur"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","kind":"typeIdentifier","text":"GroupChatThreadEventType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","kind":"typeIdentifier","text":"GroupChatThreadEvent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"}]}]},{"name":"event","content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","isActive":true,"type":"reference"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventListener":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/groupchatthreadeventlistener","title":"GroupChatThreadEventListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEventListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEvent":{"navigatorTitle":[{"text":"GroupChatThreadEvent","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","url":"\/documentation\/easechatuikit\/groupchatthreadevent","role":"symbol","abstract":[],"title":"GroupChatThreadEvent","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupChatThreadEvent"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType":{"navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","url":"\/documentation\/easechatuikit\/groupchatthreadeventtype","role":"symbol","abstract":[],"title":"GroupChatThreadEventType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GroupChatThreadEventType","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventListener/onGroupChatThreadEventOccur(type:event:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener\/onGroupChatThreadEventOccur(type:event:)","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}],"title":"onGroupChatThreadEventOccur(type:event:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupChatThreadEventOccur","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","kind":"typeIdentifier","text":"GroupChatThreadEventType"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/groupchatthreadeventlistener\/ongroupchatthreadeventoccur(type:event:)","type":"topic","abstract":[{"type":"text","text":"Some event occur on group chat thread."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onGroupChatThreadEventOccurWithType:event:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onGroupChatThreadEventOccurWithType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","text":"GroupChatThreadEventType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"event:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMChatThreadEvent","text":"EMChatThreadEvent"},{"text":" *) ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"GroupChatThreadEventListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/fragments","value":[{"text":"GroupChatThreadEventListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/title","value":"GroupChatThreadEventType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener~1onGroupChatThreadEventOccur(type:event:)\/title","value":"onGroupChatThreadEventOccurWithType:event:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onGroupChatThreadEventOccurWithType:event:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener~1onGroupChatThreadEventOccur(type:event:)\/fragments"}]}]}