{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listExtensionActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol","text":"ContactListHeaderItemProtocol"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/appearance\/contact-swift.class\/listextensionactions"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Contact-swift.class\/listExtensionActions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The header items of the contact list."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listExtensionActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ContactListHeaderItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"kind":"text","text":"]"}],"title":"listExtensionActions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13EaseChatUIKit10AppearanceC7ContactC20listExtensionActionsSayAA0E22ListHeaderItemProtocol_pGvp","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Contact-swift.class"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItemProtocol":{"role":"symbol","title":"ContactListHeaderItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"abstract":[{"type":"text","text":"A protocol of the contact list item."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"url":"\/documentation\/easechatuikit\/contactlistheaderitemprotocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Contact-swift.class":{"role":"symbol","title":"Appearance.Contact","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Contact"}],"abstract":[{"type":"text","text":"Contact Module"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Contact-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Contact"}],"url":"\/documentation\/easechatuikit\/appearance\/contact-swift.class"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Contact-swift.class/listExtensionActions":{"role":"symbol","title":"listExtensionActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"listExtensionActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ContactListHeaderItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"The header items of the contact list."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Contact-swift.class\/listExtensionActions","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/contact-swift.class\/listextensionactions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol\/title","value":"ContactListHeaderItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}