{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProviderType"]]},"kind":"symbol","metadata":{"role":"symbol","title":"ChatUserProfileProviderType.contact","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@ChatUserProfileProviderType@ChatUserProfileProviderTypeContact","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"contact"}],"navigatorTitle":[{"kind":"identifier","text":"ChatUserProfileProviderTypeContact"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contact"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProviderType\/contact","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatuserprofileprovidertype\/contact"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatuserprofileprovidertype\/contact"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProviderType/contact":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProviderType\/contact","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/chatuserprofileprovidertype\/contact","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"contact","kind":"identifier"}],"navigatorTitle":[{"text":"ChatUserProfileProviderTypeContact","kind":"identifier"}],"title":"ChatUserProfileProviderType.contact","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProviderType":{"title":"ChatUserProfileProviderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ChatUserProfileProviderType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProviderType","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProviderType","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatuserprofileprovidertype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ChatUserProfileProviderTypeContact"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ChatUserProfileProviderTypeContact","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ChatUserProfileProviderTypeContact"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ChatUserProfileProviderTypeContact","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProviderType~1contact\/title"},{"value":[{"kind":"identifier","text":"ChatUserProfileProviderTypeContact"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProviderType~1contact\/fragments"},{"op":"replace","value":"ChatUserProfileProviderType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProviderType\/title"},{"value":[{"kind":"identifier","text":"ChatUserProfileProviderType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProviderType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProviderType\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUserProfileProviderType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}