{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageinputreplyview\/themeswitchprotocol-implementations"]},{"paths":["\/documentation\/easechatuikit\/messageinputreplyview\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView\/switchTheme(style:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","modules":[{"name":"EaseChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputReplyView/switchTheme(style:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"switchTheme(style:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView\/switchTheme(style:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"url":"\/documentation\/easechatuikit\/messageinputreplyview\/switchtheme(style:)","kind":"symbol","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"text":" to switch theme.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputReplyView":{"kind":"symbol","title":"MessageInputReplyView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageInputReplyView"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView","navigatorTitle":[{"text":"MessageInputReplyView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messageinputreplyview","abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputReplyView\/switchTheme(style:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView~1switchTheme(style:)\/title","op":"replace","value":"switchThemeWithStyle:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView~1switchTheme(style:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView\/title","value":"MessageInputReplyView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView\/fragments","value":[{"kind":"identifier","text":"MessageInputReplyView"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputReplyView\/navigatorTitle","op":"replace","value":[{"text":"MessageInputReplyView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}