{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/detailinfoheader\/collectionview(_:cellforitemat:)"]},{"paths":["\/documentation\/easechatuikit\/detailinfoheader\/collectionview(_:cellforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:cellForItemAt:)"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cellForItemAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/collectionView(_:cellForItemAt:)"},"metadata":{"title":"collectionView(_:cellForItemAt:)","externalID":"c:@CM@EaseChatUIKit@objc(cs)DetailInfoHeader(im)collectionView:cellForItemAtIndexPath:","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier"}],"extendedModule":"EaseChatUIKit"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/UICollectionViewDataSource-Implementations"]]},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader/UICollectionViewDataSource-Implementations":{"url":"\/documentation\/easechatuikit\/detailinfoheader\/uicollectionviewdatasource-implementations","title":"UICollectionViewDataSource Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/UICollectionViewDataSource-Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader/collectionView(_:cellForItemAt:)":{"url":"\/documentation\/easechatuikit\/detailinfoheader\/collectionview(_:cellforitemat:)","title":"collectionView(_:cellForItemAt:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/collectionView(_:cellForItemAt:)","navigatorTitle":[{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cellForItemAt"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell","text":"UICollectionViewCell"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetailInfoHeader","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","title":"DetailInfoHeader","url":"\/documentation\/easechatuikit\/detailinfoheader","role":"symbol","abstract":[],"navigatorTitle":[{"text":"DetailInfoHeader","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"collectionView:cellForItemAtIndexPath:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"UICollectionViewCell","preciseIdentifier":"c:objc(cs)UICollectionViewCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"collectionView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"text":" ","kind":"text"},{"text":"cellForItemAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader~1collectionView(_:cellForItemAt:)\/title","value":"collectionView:cellForItemAtIndexPath:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader~1collectionView(_:cellForItemAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/title","value":"DetailInfoHeader"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/fragments","value":[{"kind":"identifier","text":"DetailInfoHeader"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}