{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/itemList","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"property","externalID":"s:13EaseChatUIKit16DetailInfoHeaderC8itemListSo16UICollectionViewCvp","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","title":"itemList","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"itemList"},{"text":": ","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/detailinfoheader\/itemlist"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"itemList","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader/itemList":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/itemList","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/detailinfoheader\/itemlist","abstract":[],"title":"itemList","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"itemList"},{"kind":"text","text":": "},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader":{"abstract":[],"title":"DetailInfoHeader","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetailInfoHeader"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","navigatorTitle":[{"text":"DetailInfoHeader","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/detailinfoheader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/title","value":"DetailInfoHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/fragments","value":[{"text":"DetailInfoHeader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/navigatorTitle","op":"replace","value":[{"text":"DetailInfoHeader","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}