{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"layout","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UICollectionViewFlowLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/detailinfoheader\/layout"]}],"metadata":{"externalID":"s:13EaseChatUIKit16DetailInfoHeaderC6layoutSo26UICollectionViewFlowLayoutCvp","roleHeading":"Instance Property","role":"symbol","title":"layout","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"layout"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout","text":"UICollectionViewFlowLayout"}],"symbolKind":"property"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/layout","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader":{"abstract":[],"title":"DetailInfoHeader","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetailInfoHeader"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","navigatorTitle":[{"text":"DetailInfoHeader","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/detailinfoheader"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader/layout":{"url":"\/documentation\/easechatuikit\/detailinfoheader\/layout","title":"layout","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout"},{"kind":"text","text":": "},{"text":"UICollectionViewFlowLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewFlowLayout"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/layout","kind":"symbol","type":"topic","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DetailInfoHeader","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DetailInfoHeader"}]},{"value":[{"text":"DetailInfoHeader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/navigatorTitle"}]}]}