{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nickName"},{"text":": ","kind":"text"},{"text":"UILabel","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"nickName","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UILabel","preciseIdentifier":"c:objc(cs)UILabel"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13EaseChatUIKit16DetailInfoHeaderC8nickNameSo7UILabelCvp","title":"nickName"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/nickName","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/detailinfoheader\/nickname"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader/nickName":{"abstract":[],"url":"\/documentation\/easechatuikit\/detailinfoheader\/nickname","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/nickName","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nickName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UILabel","text":"UILabel"}],"title":"nickName"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader":{"abstract":[],"title":"DetailInfoHeader","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetailInfoHeader"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","navigatorTitle":[{"text":"DetailInfoHeader","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/detailinfoheader"}},"variantOverrides":[{"patch":[{"value":"DetailInfoHeader","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/fragments","value":[{"kind":"identifier","text":"DetailInfoHeader"}]},{"value":[{"text":"DetailInfoHeader","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}