{"variants":[{"paths":["\/documentation\/easechatuikit\/detailinfoheader\/refreshheader(showmenu:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/detailinfoheader\/refreshheader(showmenu:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshHeader"},{"kind":"text","text":"("},{"text":"showMenu","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"refreshHeader(showMenu:)","navigatorTitle":[{"kind":"identifier","text":"refreshHeaderWithShowMenu:"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)DetailInfoHeader(im)refreshHeaderWithShowMenu:","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/refreshHeader(showMenu:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshHeader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"showMenu"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader/refreshHeader(showMenu:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader\/refreshHeader(showMenu:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/detailinfoheader\/refreshheader(showmenu:)","navigatorTitle":[{"text":"refreshHeaderWithShowMenu:","kind":"identifier"}],"abstract":[],"title":"refreshHeader(showMenu:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refreshHeader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"showMenu","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader":{"abstract":[],"title":"DetailInfoHeader","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetailInfoHeader"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","navigatorTitle":[{"text":"DetailInfoHeader","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/detailinfoheader"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"refreshHeaderWithShowMenu:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshHeaderWithShowMenu:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"refreshHeaderWithShowMenu:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showMenu","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"refreshHeaderWithShowMenu:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader~1refreshHeader(showMenu:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader~1refreshHeader(showMenu:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"refreshHeaderWithShowMenu:","kind":"identifier"}],"op":"replace"},{"value":"DetailInfoHeader","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/title"},{"op":"replace","value":[{"text":"DetailInfoHeader","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/fragments"},{"value":[{"text":"DetailInfoHeader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/navigatorTitle"}]}]}