{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PlaceHolderTextView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PlaceHolderTextView\/font"},"variants":[{"paths":["\/documentation\/easechatuikit\/placeholdertextview\/font"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/placeholdertextview\/font"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"font"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier","text":"UIFont"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","title":"font","navigatorTitle":[{"kind":"identifier","text":"font"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"font"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":"?"}],"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)PlaceHolderTextView(py)font","role":"symbol"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PlaceHolderTextView/font":{"abstract":[],"url":"\/documentation\/easechatuikit\/placeholdertextview\/font","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PlaceHolderTextView\/font","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"font","kind":"identifier"}],"title":"font","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"font","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PlaceHolderTextView":{"title":"PlaceHolderTextView","abstract":[{"text":"A subclass of UITextView that provides a placeholder text when the text view is empty.","type":"text"}],"type":"topic","url":"\/documentation\/easechatuikit\/placeholdertextview","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceHolderTextView","kind":"identifier"}],"navigatorTitle":[{"text":"PlaceHolderTextView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PlaceHolderTextView","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"font","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"font","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"font","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"font","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PlaceHolderTextView~1font\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PlaceHolderTextView~1font\/fragments","value":[{"text":"font","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PlaceHolderTextView\/title","value":"PlaceHolderTextView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PlaceHolderTextView\/fragments","value":[{"text":"PlaceHolderTextView","kind":"identifier"}]},{"value":[{"text":"PlaceHolderTextView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PlaceHolderTextView\/navigatorTitle","op":"replace"}]}]}