{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentStyle"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell\/ContentDisplayStyle","preciseIdentifier":"s:13EaseChatUIKit11MessageCellC19ContentDisplayStyleO","text":"ContentDisplayStyle"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/appearance\/chat-swift.class\/contentstyle"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/contentStyle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message content display style.You can use these four styles to combine a style array you want. Bubbles are all provided by default, except for picture messages and video messages."},{"type":"codeVoice","code":"MessageCell.ContentDisplayStyle"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentStyle"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentDisplayStyle","preciseIdentifier":"s:13EaseChatUIKit11MessageCellC19ContentDisplayStyleO"},{"kind":"text","text":"]"}],"title":"contentStyle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13EaseChatUIKit10AppearanceC0B0C12contentStyleSayAA11MessageCellC014ContentDisplayF0OGvp","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"role":"symbol","title":"MessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageCell"}],"url":"\/documentation\/easechatuikit\/messagecell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell/ContentDisplayStyle":{"role":"symbol","title":"MessageCell.ContentDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContentDisplayStyle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell\/ContentDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContentDisplayStyle"}],"url":"\/documentation\/easechatuikit\/messagecell\/contentdisplaystyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class/contentStyle":{"role":"symbol","title":"contentStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"contentStyle"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ContentDisplayStyle","preciseIdentifier":"s:13EaseChatUIKit11MessageCellC19ContentDisplayStyleO"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Message content display style.You can use these four styles to combine a style array you want. Bubbles are all provided by default, except for picture messages and video messages."},{"type":"codeVoice","code":"MessageCell.ContentDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class\/contentStyle","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class\/contentstyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Chat-swift.class":{"role":"symbol","title":"Appearance.Chat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Chat"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Chat-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Chat"}],"url":"\/documentation\/easechatuikit\/appearance\/chat-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","value":"MessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","value":[{"kind":"identifier","text":"MessageCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}