{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactdisplaystyle\/normal"]},{"paths":["\/documentation\/easechatuikit\/contactdisplaystyle\/normal"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle"]]},"metadata":{"title":"ContactDisplayStyle.normal","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@ContactDisplayStyle@ContactDisplayStyleNormal","navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyleNormal"}],"roleHeading":"Case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle\/normal","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"normal"}]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactDisplayStyle/normal":{"title":"ContactDisplayStyle.normal","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/contactdisplaystyle\/normal","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"normal"}],"navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyleNormal"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle\/normal","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactDisplayStyle":{"kind":"symbol","title":"ContactDisplayStyle","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyle"}],"url":"\/documentation\/easechatuikit\/contactdisplaystyle","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"ContactDisplayStyleNormal","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"ContactDisplayStyleNormal","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ContactDisplayStyleNormal"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle~1normal\/title","op":"replace","value":"ContactDisplayStyleNormal"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle~1normal\/fragments","op":"replace","value":[{"text":"ContactDisplayStyleNormal","kind":"identifier"}]},{"op":"replace","value":"ContactDisplayStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/fragments","op":"replace","value":[{"text":"ContactDisplayStyle","kind":"identifier"}]},{"value":[{"text":"ContactDisplayStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/navigatorTitle"}]}]}