{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCheckBox"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactdisplaystyle\/withcheckbox"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactdisplaystyle\/withcheckbox"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle\/withCheckBox","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCheckBox"}],"title":"ContactDisplayStyle.withCheckBox","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@ContactDisplayStyle@ContactDisplayStyleWithCheckBox","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyleWithCheckBox"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactDisplayStyle/withCheckBox":{"role":"symbol","title":"ContactDisplayStyle.withCheckBox","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"withCheckBox"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle\/withCheckBox","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyleWithCheckBox"}],"url":"\/documentation\/easechatuikit\/contactdisplaystyle\/withcheckbox"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactDisplayStyle":{"role":"symbol","title":"ContactDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactDisplayStyle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyle"}],"url":"\/documentation\/easechatuikit\/contactdisplaystyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"ContactDisplayStyleWithCheckBox"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ContactDisplayStyleWithCheckBox"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ContactDisplayStyleWithCheckBox"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle~1withCheckBox\/title","value":"ContactDisplayStyleWithCheckBox"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle~1withCheckBox\/fragments","value":[{"kind":"identifier","text":"ContactDisplayStyleWithCheckBox"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/title","value":"ContactDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/fragments","value":[{"kind":"identifier","text":"ContactDisplayStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}