{"sections":[],"metadata":{"extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatServiceImplement(im)editWithMessageId:text:completion:","navigatorTitle":[{"text":"editWithMessageId:text:completion:","kind":"identifier"}],"symbolKind":"method","role":"symbol","title":"edit(messageId:text:completion:)","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"edit","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/edit(messageId:text:completion:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/ChatService-Implementations"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/edit(messageid:text:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/edit(messageid:text:completion:)"]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Edit text message content."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"edit","kind":"identifier"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"text":"?, ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the message.","type":"text"}]}],"name":"messageId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Replacement king of "},{"type":"codeVoice","code":"String"},{"text":".","type":"text"}]}],"name":"text"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Callback, returns message if successful, returns error if failed","type":"text"}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement":{"title":"ChatServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatServiceImplement","kind":"identifier"}],"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatserviceimplement","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"title":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chaterror"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/ChatService-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/chatserviceimplement\/chatservice-implementations","title":"ChatService Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/ChatService-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/edit(messageId:text:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"edit","kind":"identifier"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/edit(messageId:text:completion:)","navigatorTitle":[{"kind":"identifier","text":"editWithMessageId:text:completion:"}],"title":"edit(messageId:text:completion:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/edit(messageid:text:completion:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Edit text message content."}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","abstract":[],"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"editWithMessageId:text:completion:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"editWithMessageId:text:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"editWithMessageId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"messageId"},{"text":" ","kind":"text"},{"text":"text:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMError","text":"EMError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)EMChatMessage","text":"EMChatMessage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}]}]}},{"value":"ChatServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/fragments","value":[{"kind":"identifier","text":"ChatServiceImplement"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/navigatorTitle","value":[{"kind":"identifier","text":"ChatServiceImplement"}],"op":"replace"},{"op":"replace","value":"editWithMessageId:text:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1edit(messageId:text:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editWithMessageId:text:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1edit(messageId:text:completion:)\/fragments"}]}]}