{"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"EMChatManagerDelegate Implementations","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/EMChatManagerDelegate-Implementations","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/emchatmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/emchatmanagerdelegate-implementations"]}],"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageAttachmentStatusDidChange(_:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageReactionDidChange(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageStatusDidChange(_:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidDeliver(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidRead(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidReceive(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesInfoDidRecall(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/onMessageContentChanged(_:operatorId:operationTime:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/messageAttachmentStatusDidChange(_:error:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageAttachmentStatusDidChange"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?)"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageAttachmentStatusDidChange(_:error:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/messageattachmentstatusdidchange(_:error:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageAttachmentStatusDidChange:error:"}],"type":"topic","title":"messageAttachmentStatusDidChange(_:error:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/messageStatusDidChange(_:error:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageStatusDidChange","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?)"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageStatusDidChange(_:error:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/messagestatusdidchange(_:error:)","role":"symbol","navigatorTitle":[{"text":"messageStatusDidChange:error:","kind":"identifier"}],"type":"topic","title":"messageStatusDidChange(_:error:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/messageReactionDidChange(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionDidChange"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea","text":"MessageReactionChange"},{"text":"])","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageReactionDidChange(_:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/messagereactiondidchange(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageReactionDidChange:"}],"type":"topic","title":"messageReactionDidChange(_:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/messagesDidDeliver(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messagesDidDeliver"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":"])"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidDeliver(_:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/messagesdiddeliver(_:)","role":"symbol","navigatorTitle":[{"text":"messagesDidDeliver:","kind":"identifier"}],"type":"topic","title":"messagesDidDeliver(_:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/messagesDidRead(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidRead"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":"])","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidRead(_:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/messagesdidread(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messagesDidRead:"}],"type":"topic","title":"messagesDidRead(_:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/messagesInfoDidRecall(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messagesInfoDidRecall"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","text":"RecallInfo"},{"kind":"text","text":"])"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesInfoDidRecall(_:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/messagesinfodidrecall(_:)","role":"symbol","navigatorTitle":[{"text":"messagesInfoDidRecall:","kind":"identifier"}],"type":"topic","title":"messagesInfoDidRecall(_:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/onMessageContentChanged(_:operatorId:operationTime:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageContentChanged"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operatorId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operationTime"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/onMessageContentChanged(_:operatorId:operationTime:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/onmessagecontentchanged(_:operatorid:operationtime:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageContentChanged:operatorId:operationTime:"}],"type":"topic","title":"onMessageContentChanged(_:operatorId:operationTime:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/messagesDidReceive(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messagesDidReceive","kind":"identifier"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":"])"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidReceive(_:)","url":"\/documentation\/easechatuikit\/chatserviceimplement\/messagesdidreceive(_:)","role":"symbol","navigatorTitle":[{"text":"messagesDidReceive:","kind":"identifier"}],"type":"topic","title":"messagesDidReceive(_:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement":{"url":"\/documentation\/easechatuikit\/chatserviceimplement","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatServiceImplement","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatServiceImplement"}],"type":"topic","title":"ChatServiceImplement","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageAttachmentStatusDidChange(_:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageReactionDidChange(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messageStatusDidChange(_:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidDeliver(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidRead(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesDidReceive(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/messagesInfoDidRecall(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/onMessageContentChanged(_:operatorId:operationTime:)"],"title":"Instance Methods","generated":true}],"path":"\/topicSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messageAttachmentStatusDidChange(_:error:)\/title","value":"messageAttachmentStatusDidChange:error:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messageAttachmentStatusDidChange(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"messageAttachmentStatusDidChange:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messageStatusDidChange(_:error:)\/title","value":"messageStatusDidChange:error:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messageStatusDidChange(_:error:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"messageStatusDidChange:error:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messageReactionDidChange(_:)\/title","value":"messageReactionDidChange:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageReactionDidChange:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messageReactionDidChange(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesDidDeliver(_:)\/title","value":"messagesDidDeliver:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"messagesDidDeliver:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesDidDeliver(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesDidRead(_:)\/title","value":"messagesDidRead:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesDidRead(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"messagesDidRead:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesInfoDidRecall(_:)\/title","value":"messagesInfoDidRecall:"},{"value":[{"text":"- ","kind":"text"},{"text":"messagesInfoDidRecall:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesInfoDidRecall(_:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1onMessageContentChanged(_:operatorId:operationTime:)\/title","value":"onMessageContentChanged:operatorId:operationTime:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageContentChanged:operatorId:operationTime:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1onMessageContentChanged(_:operatorId:operationTime:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesDidReceive(_:)\/title","value":"messagesDidReceive:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1messagesDidReceive(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"messagesDidReceive:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/title","value":"ChatServiceImplement"},{"op":"replace","value":[{"kind":"identifier","text":"ChatServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}