{"variants":[{"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/onmessagepinchanged(_:conversationid:operation:pininfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/onmessagepinchanged(_:conversationid:operation:pininfo:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/onMessagePinChanged(_:conversationId:operation:pinInfo:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/EMChatManagerDelegate-Implementations"]]},"kind":"symbol","metadata":{"extendedModule":"EaseChatUIKit","navigatorTitle":[{"text":"onMessagePinChanged:conversationId:operation:pinInfo:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessagePinChanged"},{"kind":"text","text":"("},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa","text":"MessagePinOperation","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pinInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePinInfo","preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa"},{"kind":"text","text":")"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"title":"onMessagePinChanged(_:conversationId:operation:pinInfo:)","roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatServiceImplement(im)onMessagePinChanged:conversationId:operation:pinInfo:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessagePinChanged"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"messageId","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operation"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pinOperation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinOperation","preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa","text":"MessagePinOperation"},{"text":", ","kind":"text"},{"text":"pinInfo","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinInfo","preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa","text":"MessagePinInfo"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"EMChatManagerDelegate.onMessagePinChanged(_:conversationId:operation:pinInfo:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement":{"title":"ChatServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatServiceImplement","kind":"identifier"}],"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatserviceimplement","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessagePinOperation":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinOperation","role":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePinOperation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessagePinOperation"}],"title":"MessagePinOperation","url":"\/documentation\/easechatuikit\/messagepinoperation","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessagePinInfo":{"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePinInfo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagePinInfo"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinInfo","url":"\/documentation\/easechatuikit\/messagepininfo","title":"MessagePinInfo","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/onMessagePinChanged(_:conversationId:operation:pinInfo:)":{"kind":"symbol","title":"onMessagePinChanged(_:conversationId:operation:pinInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessagePinChanged"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePinOperation","preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa"},{"text":", ","kind":"text"},{"text":"pinInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa","kind":"typeIdentifier","text":"MessagePinInfo"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/chatserviceimplement\/onmessagepinchanged(_:conversationid:operation:pininfo:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessagePinChanged:conversationId:operation:pinInfo:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/onMessagePinChanged(_:conversationId:operation:pinInfo:)","type":"topic","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/EMChatManagerDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/EMChatManagerDelegate-Implementations","type":"topic","role":"collectionGroup","kind":"article","url":"\/documentation\/easechatuikit\/chatserviceimplement\/emchatmanagerdelegate-implementations","title":"EMChatManagerDelegate Implementations","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onMessagePinChanged:conversationId:operation:pinInfo:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessagePinChanged:conversationId:operation:pinInfo:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"onMessagePinChanged:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"messageId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"conversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"kind":"text","text":" "},{"text":"operation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EMMessagePinOperation","text":"EMMessagePinOperation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pinOperation"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMMessagePinInfo","text":"EMMessagePinInfo","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"pinInfo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ChatServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/fragments","value":[{"kind":"identifier","text":"ChatServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/navigatorTitle","value":[{"kind":"identifier","text":"ChatServiceImplement"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1onMessagePinChanged(_:conversationId:operation:pinInfo:)\/title","value":"onMessagePinChanged:conversationId:operation:pinInfo:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessagePinChanged:conversationId:operation:pinInfo:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1onMessagePinChanged(_:conversationId:operation:pinInfo:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}