{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/unbindChatEventsListener(listener:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatServiceImplement(im)unbindChatEventsListenerWithListener:","title":"unbindChatEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unbindChatEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener","text":"ChatResponseListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"unbindChatEventsListenerWithListener:"}],"symbolKind":"method","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unbindChatEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatResponseListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"listener"}],"kind":"parameters"}],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/unbindchateventslistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatserviceimplement\/unbindchateventslistener(listener:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/ChatService-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Unbind message changed listener"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement":{"title":"ChatServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatServiceImplement","kind":"identifier"}],"navigatorTitle":[{"text":"ChatServiceImplement","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatserviceimplement","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/ChatService-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/chatserviceimplement\/chatservice-implementations","title":"ChatService Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/ChatService-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener":{"url":"\/documentation\/easechatuikit\/chatresponselistener","type":"topic","title":"ChatResponseListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatResponseListener"}],"navigatorTitle":[{"text":"ChatResponseListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatServiceImplement/unbindChatEventsListener(listener:)":{"url":"\/documentation\/easechatuikit\/chatserviceimplement\/unbindchateventslistener(listener:)","title":"unbindChatEventsListener(listener:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unbindChatEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener","text":"ChatResponseListener"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"unbindChatEventsListenerWithListener:","kind":"identifier"}],"abstract":[{"type":"text","text":"Unbind message changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatServiceImplement\/unbindChatEventsListener(listener:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unbindChatEventsListenerWithListener:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unbindChatEventsListenerWithListener:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unbindChatEventsListenerWithListener:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ChatResponseListener","text":"id<ChatResponseListener>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"ChatServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/fragments","value":[{"text":"ChatServiceImplement","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ChatServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement\/navigatorTitle"},{"op":"replace","value":"ChatResponseListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/fragments","value":[{"text":"ChatResponseListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/navigatorTitle","value":[{"kind":"identifier","text":"ChatResponseListener"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1unbindChatEventsListener(listener:)\/title","value":"unbindChatEventsListenerWithListener:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatServiceImplement~1unbindChatEventsListener(listener:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unbindChatEventsListenerWithListener:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}