{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"avatar","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"avatar","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avatar"},{"text":": ","kind":"text"},{"text":"ImageView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","kind":"typeIdentifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ForwardTargetCell(py)avatar","symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/avatar","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/forwardtargetcell\/avatar"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/forwardtargetcell\/avatar"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","text":"ImageView"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ImageView":{"kind":"symbol","navigatorTitle":[{"text":"ImageView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"title":"ImageView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A subclass of "},{"code":"UIImageView","type":"codeVoice"},{"text":" that provides a method for loading an image from a URL.","type":"text"}],"url":"\/documentation\/easechatuikit\/imageview"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/avatar":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/avatar","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"avatar","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/forwardtargetcell\/avatar","title":"avatar"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell","abstract":[],"role":"symbol","type":"topic","title":"ForwardTargetCell","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ForwardTargetCell"}],"navigatorTitle":[{"kind":"identifier","text":"ForwardTargetCell"}],"url":"\/documentation\/easechatuikit\/forwardtargetcell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"avatar","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"avatar"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","text":"ImageView"},{"kind":"text","text":" * "},{"text":"avatar","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/title","value":"ImageView","op":"replace"},{"op":"replace","value":[{"text":"ImageView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/fragments"},{"value":"avatar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1avatar\/title"},{"value":[{"kind":"identifier","text":"avatar"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1avatar\/fragments"},{"value":"ForwardTargetCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell\/fragments","value":[{"kind":"identifier","text":"ForwardTargetCell"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}