{"variants":[{"paths":["\/documentation\/easechatuikit\/forwardtargetcell\/layoutsubviews()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/forwardtargetcell\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/layoutSubviews()","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell"]]},"metadata":{"title":"layoutSubviews()","externalID":"c:@M@EaseChatUIKit@objc(cs)ForwardTargetCell(im)layoutSubviews","role":"symbol","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell/layoutSubviews()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}],"title":"layoutSubviews()","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell\/layoutSubviews()","url":"\/documentation\/easechatuikit\/forwardtargetcell\/layoutsubviews()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ForwardTargetCell":{"title":"ForwardTargetCell","url":"\/documentation\/easechatuikit\/forwardtargetcell","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ForwardTargetCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ForwardTargetCell","abstract":[],"type":"topic","navigatorTitle":[{"text":"ForwardTargetCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"layoutSubviews"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"layoutSubviews","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1layoutSubviews()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell\/title","value":"ForwardTargetCell"},{"value":[{"kind":"identifier","text":"ForwardTargetCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ForwardTargetCell\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}