{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"metadata":{"title":"init(coder:)","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)LocationMessageCell(im)initWithCoder:","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LocationMessageCell"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/locationmessagecell\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/locationmessagecell\/init(coder:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LocationMessageCell\/init(coder:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LocationMessageCell":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LocationMessageCell","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/locationmessagecell","navigatorTitle":[{"text":"LocationMessageCell","kind":"identifier"}],"abstract":[],"title":"LocationMessageCell","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LocationMessageCell"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LocationMessageCell/init(coder:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder"},{"text":")","kind":"text"}],"title":"init(coder:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LocationMessageCell\/init(coder:)","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/locationmessagecell\/init(coder:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithCoder:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"coder"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"LocationMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LocationMessageCell\/title"},{"value":[{"text":"LocationMessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LocationMessageCell\/fragments"},{"value":[{"kind":"identifier","text":"LocationMessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LocationMessageCell\/navigatorTitle","op":"replace"},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LocationMessageCell~1init(coder:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LocationMessageCell~1init(coder:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}