{"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate","text":"ConversationListActionEventsDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"addActionHandler(actionHandler:)","navigatorTitle":[{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver(im)addActionHandlerWithActionHandler:","modules":[{"name":"EaseChatUIKit"}],"required":true},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/addActionHandler(actionHandler:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addActionHandler"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"text":"ConversationListActionEventsDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","isActive":true,"type":"reference"}]}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/addactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/addactionhandler(actionhandler:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver"]]},"sections":[],"kind":"symbol","abstract":[{"text":"Add UI actions handler.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/addActionHandler(actionHandler:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/addActionHandler(actionHandler:)","title":"addActionHandler(actionHandler:)","type":"topic","required":true,"navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addActionHandler"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver\/addactionhandler(actionhandler:)","role":"symbol","abstract":[{"text":"Add UI actions handler.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver","title":"IConversationListDriver","type":"topic","navigatorTitle":[{"text":"IConversationListDriver","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IConversationListDriver","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver","role":"symbol","abstract":[{"text":"ConversationList view driver.","type":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"title":"ConversationListActionEventsDelegate","type":"topic","url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate","kind":"symbol","navigatorTitle":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"addActionHandlerWithActionHandler:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate","text":"id<ConversationListActionEventsDelegate>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"actionHandler"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"addActionHandlerWithActionHandler:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1addActionHandler(actionHandler:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1addActionHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/title","value":"IConversationListDriver"},{"value":[{"text":"IConversationListDriver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/fragments","op":"replace"},{"value":"ConversationListActionEventsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title"},{"value":[{"text":"ConversationListActionEventsDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments"}]}]}