{"abstract":[{"text":"This method can be used when pulling down to refresh.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/refreshlist(infos:)"]},{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/refreshlist(infos:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver(im)refreshListWithInfos:","modules":[{"name":"EaseChatUIKit"}],"title":"refreshList(infos:)","roleHeading":"Instance Method","required":true,"navigatorTitle":[{"kind":"identifier","text":"refreshListWithInfos:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refreshList","kind":"identifier"},{"text":"(","kind":"text"},{"text":"infos","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":"])","kind":"text"}],"symbolKind":"method","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshList(infos:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshList"},{"text":"(","kind":"text"},{"text":"infos","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo"},{"text":"])","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"infos","content":[{"type":"paragraph","inlineContent":[{"text":"Array of ConversationInfo objects.","type":"text"}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"navigatorTitle":[{"kind":"identifier","text":"ConversationInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/conversationinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"symbol","type":"topic","title":"ConversationInfo","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/refreshList(infos:)":{"title":"refreshList(infos:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/iconversationlistdriver\/refreshlist(infos:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshList(infos:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"refreshList","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"refreshListWithInfos:","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"This method can be used when pulling down to refresh."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IConversationListDriver"}],"abstract":[{"type":"text","text":"ConversationList view driver."}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver","title":"IConversationListDriver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IConversationListDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"refreshListWithInfos:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshListWithInfos:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"refreshListWithInfos:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<ConversationInfo *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"infos","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title","op":"replace","value":"ConversationInfo"},{"value":[{"kind":"identifier","text":"ConversationInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments"},{"value":"refreshListWithInfos:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshList(infos:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"refreshListWithInfos:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshList(infos:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/title","value":"IConversationListDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/fragments","value":[{"text":"IConversationListDriver","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}