{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshProfiles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"infos","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of conform "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/refreshprofiles(infos:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/refreshprofiles(infos:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshProfiles(infos:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method can be used when you want refresh some  display info  of datas."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"refreshProfilesWithInfos:"}],"role":"symbol","title":"refreshProfiles(infos:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshProfiles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver(im)refreshProfilesWithInfos:","required":true,"modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/refreshProfiles(infos:)":{"navigatorTitle":[{"kind":"identifier","text":"refreshProfilesWithInfos:"}],"role":"symbol","title":"refreshProfiles(infos:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshProfiles"},{"kind":"text","text":"("},{"kind":"externalParam","text":"infos"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"This method can be used when you want refresh some  display info  of datas."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/refreshProfiles(infos:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/iconversationlistdriver\/refreshprofiles(infos:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver":{"role":"symbol","title":"IConversationListDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IConversationListDriver"}],"abstract":[{"type":"text","text":"ConversationList view driver."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IConversationListDriver"}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"role":"symbol","title":"EaseProfileProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseProfileProtocol"}],"abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseProfileProtocol"}],"url":"\/documentation\/easechatuikit\/easeprofileprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshProfilesWithInfos:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshProfilesWithInfos:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshProfilesWithInfos:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<EaseProfileProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"infos"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshProfiles(infos:)\/title","value":"refreshProfilesWithInfos:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1refreshProfiles(infos:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshProfilesWithInfos:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/title","value":"IConversationListDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/fragments","value":[{"kind":"identifier","text":"IConversationListDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title","value":"EaseProfileProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments","value":[{"kind":"identifier","text":"EaseProfileProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}