{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate","text":"ConversationListActionEventsDelegate"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/removeactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/removeactionhandler(actionhandler:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/removeActionHandler(actionHandler:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Remove UI action handler."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}],"role":"symbol","title":"removeActionHandler(actionHandler:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver(im)removeActionHandlerWithActionHandler:","required":true,"modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver":{"role":"symbol","title":"IConversationListDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IConversationListDriver"}],"abstract":[{"type":"text","text":"ConversationList view driver."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IConversationListDriver"}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListActionEventsDelegate":{"role":"symbol","title":"ConversationListActionEventsDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"abstract":[{"type":"text","text":"Session list touch event callback proxy"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}],"url":"\/documentation\/easechatuikit\/conversationlistactioneventsdelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/removeActionHandler(actionHandler:)":{"navigatorTitle":[{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}],"role":"symbol","title":"removeActionHandler(actionHandler:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeActionHandler"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove UI action handler."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/removeActionHandler(actionHandler:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/iconversationlistdriver\/removeactionhandler(actionhandler:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeActionHandlerWithActionHandler:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ConversationListActionEventsDelegate>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ConversationListActionEventsDelegate"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"actionHandler"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/title","value":"IConversationListDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/fragments","value":[{"kind":"identifier","text":"IConversationListDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/title","value":"ConversationListActionEventsDelegate"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"ConversationListActionEventsDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1removeActionHandler(actionHandler:)\/title","value":"removeActionHandlerWithActionHandler:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1removeActionHandler(actionHandler:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeActionHandlerWithActionHandler:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}