{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/swipemenuoperation(info:type:)"]},{"paths":["\/documentation\/easechatuikit\/iconversationlistdriver\/swipemenuoperation(info:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"swipeMenuOperation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"text":"ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"UIContextualActionType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","type":"reference"},{"text":" object.","type":"text"}]}],"name":"info"},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","isActive":true}]}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/swipeMenuOperation(info:type:)"},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)IConversationListDriver(im)swipeMenuOperationWithInfo:type:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeMenuOperation"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIContextualActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"text":")","kind":"text"}],"required":true,"title":"swipeMenuOperation(info:type:)","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"swipeMenuOperationWithInfo:type:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"kind":"symbol","abstract":[{"text":"Conversation Operation event after clicking the button in the side-sliding menu.","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType":{"role":"symbol","title":"UIContextualActionType","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"UIContextualActionType","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"UIContextualActionType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","url":"\/documentation\/easechatuikit\/uicontextualactiontype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IConversationListDriver"}],"abstract":[{"type":"text","text":"ConversationList view driver."}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver","title":"IConversationListDriver","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"IConversationListDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IConversationListDriver/swipeMenuOperation(info:type:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IConversationListDriver\/swipeMenuOperation(info:type:)","kind":"symbol","title":"swipeMenuOperation(info:type:)","required":true,"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"swipeMenuOperation","kind":"identifier"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"kind":"text","text":")"}],"role":"symbol","abstract":[{"text":"Conversation Operation event after clicking the button in the side-sliding menu.","type":"text"}],"url":"\/documentation\/easechatuikit\/iconversationlistdriver\/swipemenuoperation(info:type:)","navigatorTitle":[{"text":"swipeMenuOperationWithInfo:type:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"navigatorTitle":[{"kind":"identifier","text":"ConversationInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/conversationinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"symbol","type":"topic","title":"ConversationInfo","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"swipeMenuOperationWithInfo:type:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"swipeMenuOperationWithInfo:type:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"swipeMenuOperationWithInfo:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","text":"ConversationInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","text":"UIContextualActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"UIContextualActionType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/title"},{"op":"replace","value":[{"text":"UIContextualActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/title","value":"IConversationListDriver"},{"value":[{"text":"IConversationListDriver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1swipeMenuOperation(info:type:)\/title","op":"replace","value":"swipeMenuOperationWithInfo:type:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"swipeMenuOperationWithInfo:type:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IConversationListDriver~1swipeMenuOperation(info:type:)\/fragments","op":"replace"},{"value":"ConversationInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}],"op":"replace"}]}]}