{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDialog"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"This method stops any currently playing audio, presents a custom audio recording view, and sends the recorded audio message using the view model’s ","type":"text"},{"code":"sendMessage","type":"codeVoice"},{"type":"text","text":" method."}]},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The audio recording view is an instance of "},{"type":"codeVoice","code":"MessageAudioRecordView"},{"text":" and is presented as a custom dialog using ","type":"text"},{"type":"codeVoice","code":"DialogManager.shared.showCustomDialog"},{"type":"text","text":"."}]}],"name":"Note","style":"note"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The recorded audio message is sent as a text message with the file path of the recorded audio and the duration of the recording as extension information."}]}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/audiodialog()"]},{"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/audiodialog()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatThreadCreateController(im)audioDialog","role":"symbol","title":"audioDialog()","navigatorTitle":[{"kind":"identifier","text":"audioDialog"}],"symbolKind":"method","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"audioDialog","kind":"identifier"},{"text":"()","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/audioDialog()"},"abstract":[{"type":"text","text":"Opens the audio dialog for recording and sending voice messages."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/audioDialog()":{"title":"audioDialog()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/audioDialog()","navigatorTitle":[{"kind":"identifier","text":"audioDialog"}],"url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/audiodialog()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioDialog"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Opens the audio dialog for recording and sending voice messages."}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadCreateController","kind":"identifier"}],"title":"ChatThreadCreateController","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController","navigatorTitle":[{"kind":"identifier","text":"ChatThreadCreateController"}],"abstract":[],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"audioDialog","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"audioDialog"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"audioDialog"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1audioDialog()\/title","value":"audioDialog","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"audioDialog","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1audioDialog()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/title","value":"ChatThreadCreateController"},{"op":"replace","value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/navigatorTitle","op":"replace","value":[{"text":"ChatThreadCreateController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}