{"metadata":{"extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"title":"documentPickerOpenFile(controller:urls:)","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"documentPickerOpenFileWithController:urls:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPickerOpenFile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"controller","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"urls"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":"])"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadCreateController(im)documentPickerOpenFileWithController:urls:","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPickerOpenFile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"text":"UIDocumentPickerViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController"},{"text":", ","kind":"text"},{"text":"urls","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"])","kind":"text"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/documentpickeropenfile(controller:urls:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/documentpickeropenfile(controller:urls:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/documentPickerOpenFile(controller:urls:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller","title":"ChatThreadCreateController","abstract":[],"navigatorTitle":[{"text":"ChatThreadCreateController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadCreateController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/documentPickerOpenFile(controller:urls:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/documentPickerOpenFile(controller:urls:)","role":"symbol","title":"documentPickerOpenFile(controller:urls:)","navigatorTitle":[{"kind":"identifier","text":"documentPickerOpenFileWithController:urls:"}],"url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/documentpickeropenfile(controller:urls:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentPickerOpenFile","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"controller"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","kind":"typeIdentifier","text":"UIDocumentPickerViewController"},{"text":", ","kind":"text"},{"text":"urls","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"])","kind":"text"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"documentPickerOpenFileWithController:urls:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"documentPickerOpenFileWithController:urls:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"documentPickerOpenFileWithController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"urls:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSURL *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"urls","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ChatThreadCreateController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/fragments","value":[{"kind":"identifier","text":"ChatThreadCreateController"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1documentPickerOpenFile(controller:urls:)\/title","op":"replace","value":"documentPickerOpenFileWithController:urls:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1documentPickerOpenFile(controller:urls:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"documentPickerOpenFileWithController:urls:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}