{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/init(message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/init(message:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithMessage:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"title":"init(message:)","role":"symbol","symbolKind":"init","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatThreadCreateController(im)initWithMessage:","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Initializer"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/init(message:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/init(message:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithMessage:"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/init(message:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/init(message:)","title":"init(message:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadCreateController","kind":"identifier"}],"title":"ChatThreadCreateController","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController","navigatorTitle":[{"kind":"identifier","text":"ChatThreadCreateController"}],"abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","abstract":[],"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithMessage:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMessage:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithMessage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EMChatMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMChatMessage"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1init(message:)\/title","value":"initWithMessage:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1init(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/title","value":"ChatThreadCreateController","op":"replace"},{"op":"replace","value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadCreateController"}]}]}]}