{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/onMessageAvatarLongPressed(profile:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageAvatarLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"codeVoice","code":"EaseProfileProtocol"}]}],"name":"profile"}]}],"abstract":[{"type":"text","text":"The method will call on message avatar long pressed."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/onmessageavatarlongpressed(profile:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/onmessageavatarlongpressed(profile:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations"]]},"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadCreateController(im)onMessageAvatarLongPressedWithProfile:","extendedModule":"EaseChatUIKit","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAvatarLongPressed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"roleHeading":"Instance Method","title":"onMessageAvatarLongPressed(profile:)","symbolKind":"method","role":"symbol","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/onMessageAvatarLongPressed(profile:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/onMessageAvatarLongPressed(profile:)","role":"symbol","navigatorTitle":[{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageAvatarLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"text":"The method will call on message avatar long pressed.","type":"text"}],"title":"onMessageAvatarLongPressed(profile:)","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/onmessageavatarlongpressed(profile:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProtocol":{"abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatuserprofileprotocol","role":"symbol","title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadCreateController","kind":"identifier"}],"title":"ChatThreadCreateController","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController","navigatorTitle":[{"kind":"identifier","text":"ChatThreadCreateController"}],"abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/MessageListViewActionEventsDelegate-Implementations":{"title":"MessageListViewActionEventsDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations","kind":"article","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/messagelistviewactioneventsdelegate-implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onMessageAvatarLongPressedWithProfile:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<ChatUserProfileProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"profile"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"onMessageAvatarLongPressedWithProfile:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1onMessageAvatarLongPressed(profile:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1onMessageAvatarLongPressed(profile:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/fragments","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}]},{"op":"replace","value":"ChatThreadCreateController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/fragments","value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ChatThreadCreateController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/navigatorTitle","op":"replace"}]}]}