{"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/onmessagemultiselectbarclicked(operation:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/onmessagemultiselectbarclicked(operation:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/onMessageMultiSelectBarClicked(operation:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations"]]},"metadata":{"title":"onMessageMultiSelectBarClicked(operation:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadCreateController(im)onMessageMultiSelectBarClickedWithOperation:","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"text":"(","kind":"text"},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"When message multi select bar clicked."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"text":"(","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"operation","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/onMessageMultiSelectBarClicked(operation:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/onMessageMultiSelectBarClicked(operation:)","role":"symbol","navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation"},{"text":")","kind":"text"}],"abstract":[{"text":"When message multi select bar clicked.","type":"text"}],"title":"onMessageMultiSelectBarClicked(operation:)","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/onmessagemultiselectbarclicked(operation:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBarOperation":{"navigatorTitle":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombaroperation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageMultiSelectedBottomBarOperation"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","abstract":[],"title":"MessageMultiSelectedBottomBarOperation","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/MessageListViewActionEventsDelegate-Implementations":{"title":"MessageListViewActionEventsDelegate Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/MessageListViewActionEventsDelegate-Implementations","kind":"article","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/messagelistviewactioneventsdelegate-implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadCreateController","kind":"identifier"}],"title":"ChatThreadCreateController","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController","navigatorTitle":[{"kind":"identifier","text":"ChatThreadCreateController"}],"abstract":[],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onMessageMultiSelectBarClickedWithOperation:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation"},{"kind":"text","text":") "},{"text":"operation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"onMessageMultiSelectBarClickedWithOperation:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1onMessageMultiSelectBarClicked(operation:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1onMessageMultiSelectBarClicked(operation:)\/fragments","op":"replace"},{"op":"replace","value":"MessageMultiSelectedBottomBarOperation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/title"},{"value":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/navigatorTitle","value":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"op":"replace"},{"value":"ChatThreadCreateController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/fragments","value":[{"text":"ChatThreadCreateController","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ChatThreadCreateController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}