{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/imagePickerControllerDidCancel(_:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/uiimagepickercontrollerdelegate-implementations"]},{"paths":["\/documentation\/easechatuikit\/chatthreadcreatecontroller\/uiimagepickercontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"UIImagePickerControllerDelegate Implementations","modules":[{"name":"EaseChatUIKit"}]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/UIImagePickerControllerDelegate-Implementations"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/imagePickerControllerDidCancel(_:)":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/imagepickercontrollerdidcancel(_:)","title":"imagePickerControllerDidCancel(_:)","navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerControllerDidCancel"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier","text":"UIImagePickerController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/imagePickerControllerDidCancel(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller","title":"ChatThreadCreateController","abstract":[],"navigatorTitle":[{"text":"ChatThreadCreateController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatThreadCreateController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadCreateController/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":": ["},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","text":"InfoKey"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}],"role":"symbol","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadcreatecontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadCreateController\/imagePickerControllerDidCancel(_:)"],"title":"Instance Methods","generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"imagePickerControllerDidCancel:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1imagePickerControllerDidCancel(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagePickerControllerDidCancel:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1imagePickerControllerDidCancel(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/title","value":"ChatThreadCreateController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController\/fragments","value":[{"kind":"identifier","text":"ChatThreadCreateController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title","value":"imagePickerController:didFinishPickingMediaWithInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadCreateController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}