{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/agreeJoinApplication(groupId:userId:completion:)"},"abstract":[{"text":"Agree the application of the user.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupservice\/agreejoinapplication(groupid:userid:completion:)"]},{"paths":["\/documentation\/easechatuikit\/groupservice\/agreejoinapplication(groupid:userid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","navigatorTitle":[{"text":"agreeJoinApplicationWithGroupId:userId:completion:","kind":"identifier"}],"title":"agreeJoinApplication(groupId:userId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"agreeJoinApplication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"text":"?, ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"required":true,"externalID":"c:@M@EaseChatUIKit@objc(pl)GroupService(im)agreeJoinApplicationWithGroupId:userId:completion:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"agreeJoinApplication","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup"},{"text":"?, ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group."}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user."}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned."}],"type":"paragraph"}],"name":"completion"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService/agreeJoinApplication(groupId:userId:completion:)":{"required":true,"kind":"symbol","url":"\/documentation\/easechatuikit\/groupservice\/agreejoinapplication(groupid:userid:completion:)","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"agreeJoinApplicationWithGroupId:userId:completion:"}],"title":"agreeJoinApplication(groupId:userId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"agreeJoinApplication","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"abstract":[{"text":"Agree the application of the user.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/agreeJoinApplication(groupId:userId:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"url":"\/documentation\/easechatuikit\/chaterror","role":"symbol","abstract":[],"title":"ChatError","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"}],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroup":{"url":"\/documentation\/easechatuikit\/chatgroup","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatGroup"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ChatGroup","kind":"identifier"}],"title":"ChatGroup","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}],"role":"symbol","title":"GroupService","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/groupservice","navigatorTitle":[{"kind":"identifier","text":"GroupService"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"agreeJoinApplicationWithGroupId:userId:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"agreeJoinApplicationWithGroupId:userId:completion:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"agreeJoinApplicationWithGroupId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"EMGroup","preciseIdentifier":"c:objc(cs)EMGroup"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"EMError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1agreeJoinApplication(groupId:userId:completion:)\/title","value":"agreeJoinApplicationWithGroupId:userId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1agreeJoinApplication(groupId:userId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"agreeJoinApplicationWithGroupId:userId:completion:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/title","op":"replace","value":"GroupService"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/fragments","value":[{"kind":"identifier","text":"GroupService"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}