{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"]]},"abstract":[{"type":"text","text":"Bind group event  changed listener"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/bindGroupEventsListener(listener:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bindGroupEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"GroupServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","title":"bindGroupEventsListener(listener:)","symbolKind":"method","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)GroupService(im)bindGroupEventsListenerWithListener:","navigatorTitle":[{"text":"bindGroupEventsListenerWithListener:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"required":true},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupservice\/bindgroupeventslistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupservice\/bindgroupeventslistener(listener:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindGroupEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupServiceListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","type":"reference"}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService/bindGroupEventsListener(listener:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/groupservice\/bindgroupeventslistener(listener:)","abstract":[{"text":"Bind group event  changed listener","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/bindGroupEventsListener(listener:)","title":"bindGroupEventsListener(listener:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindGroupEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"text":"GroupServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bindGroupEventsListenerWithListener:"}],"role":"symbol","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService":{"title":"GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupService","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/groupservice","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService","navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","kind":"symbol","url":"\/documentation\/easechatuikit\/groupservicelistener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"GroupServiceListener","kind":"identifier"}],"abstract":[],"title":"GroupServiceListener","navigatorTitle":[{"text":"GroupServiceListener","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bindGroupEventsListenerWithListener:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"bindGroupEventsListenerWithListener:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"bindGroupEventsListenerWithListener:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)GroupServiceListener","text":"id<GroupServiceListener>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"bindGroupEventsListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1bindGroupEventsListener(listener:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1bindGroupEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindGroupEventsListenerWithListener:","kind":"identifier"}],"op":"replace"},{"value":"GroupService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/fragments","value":[{"kind":"identifier","text":"GroupService"}],"op":"replace"},{"op":"replace","value":"GroupServiceListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/fragments","value":[{"kind":"identifier","text":"GroupServiceListener"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}