{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"bindGroupChatThreadEventListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","text":"GroupChatThreadEventListener"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener"}]}]}],"kind":"parameters"}],"sections":[],"abstract":[{"type":"text","text":"Bind group chat thread events listener."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/groupservice\/bindgroupchatthreadeventlistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupservice\/bindgroupchatthreadeventlistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/bindGroupChatThreadEventListener(listener:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"bindGroupChatThreadEventListenerWithListener:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","title":"bindGroupChatThreadEventListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindGroupChatThreadEventListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener","text":"GroupChatThreadEventListener"},{"text":")","kind":"text"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"externalID":"c:@M@EaseChatUIKit@objc(pl)GroupService(im)bindGroupChatThreadEventListenerWithListener:"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService/bindGroupChatThreadEventListener(listener:)":{"navigatorTitle":[{"text":"bindGroupChatThreadEventListenerWithListener:","kind":"identifier"}],"required":true,"abstract":[{"text":"Bind group chat thread events listener.","type":"text"}],"url":"\/documentation\/easechatuikit\/groupservice\/bindgroupchatthreadeventlistener(listener:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/bindGroupChatThreadEventListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindGroupChatThreadEventListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener","text":"GroupChatThreadEventListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"bindGroupChatThreadEventListener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}],"role":"symbol","title":"GroupService","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/groupservice","navigatorTitle":[{"kind":"identifier","text":"GroupService"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventListener":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/groupchatthreadeventlistener","title":"GroupChatThreadEventListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEventListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"bindGroupChatThreadEventListenerWithListener:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindGroupChatThreadEventListenerWithListener:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bindGroupChatThreadEventListenerWithListener:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener","text":"id<GroupChatThreadEventListener>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"bindGroupChatThreadEventListenerWithListener:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1bindGroupChatThreadEventListener(listener:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1bindGroupChatThreadEventListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindGroupChatThreadEventListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/title","value":"GroupService"},{"value":[{"text":"GroupService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/fragments","op":"replace"},{"value":"GroupChatThreadEventListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventListener"}]}]}]}