{"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)GroupService(im)getJoinedGroupsWithPage:pageSize:needMemberCount:needRole:completion:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"getJoinedGroupsWithPage:pageSize:needMemberCount:needRole:completion:"}],"modules":[{"name":"EaseChatUIKit"}],"title":"getJoinedGroups(page:pageSize:needMemberCount:needRole:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"getJoinedGroups"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"page"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":", "},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"needMemberCount"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"needRole"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ([","kind":"text"},{"text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","required":true,"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupservice\/getjoinedgroups(page:pagesize:needmembercount:needrole:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupservice\/getjoinedgroups(page:pagesize:needmembercount:needrole:completion:)"]}],"abstract":[{"type":"text","text":"Get joined groups."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getJoinedGroups"},{"text":"(","kind":"text"},{"text":"page","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"text":"pageSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"needMemberCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"needRole","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" ([","kind":"text"},{"text":"ChatGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"text":"]?, ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"page","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Page number."}]}]},{"name":"pageSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Size number of the page."}]}]},{"name":"needMemberCount","content":[{"inlineContent":[{"text":"Whether the number of returned group members is included in the group object in the callback.","type":"text"}],"type":"paragraph"}]},{"name":"needRole","content":[{"inlineContent":[{"text":"Whether the current user role of returned group in the group object in the callback.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty  ","type":"text"},{"code":"Array<ChatGroup>","type":"codeVoice"},{"text":" object will be returned.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/getJoinedGroups(page:pageSize:needMemberCount:needRole:completion:)"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService":{"abstract":[],"kind":"symbol","title":"GroupService","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupService"}],"url":"\/documentation\/easechatuikit\/groupservice","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService/getJoinedGroups(page:pageSize:needMemberCount:needRole:completion:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"getJoinedGroupsWithPage:pageSize:needMemberCount:needRole:completion:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/getJoinedGroups(page:pageSize:needMemberCount:needRole:completion:)","title":"getJoinedGroups(page:pageSize:needMemberCount:needRole:completion:)","kind":"symbol","url":"\/documentation\/easechatuikit\/groupservice\/getjoinedgroups(page:pagesize:needmembercount:needrole:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getJoinedGroups","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"page"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needMemberCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"needRole"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ([","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier","text":"ChatGroup"},{"text":"]?, ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"type":"topic","abstract":[{"type":"text","text":"Get joined groups."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"title":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chaterror"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroup":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatGroup"}],"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatGroup"}],"url":"\/documentation\/easechatuikit\/chatgroup","title":"ChatGroup"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"getJoinedGroupsWithPage:pageSize:needMemberCount:needRole:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"getJoinedGroupsWithPage:pageSize:needMemberCount:needRole:completion:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"getJoinedGroupsWithPage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"page"},{"kind":"text","text":" "},{"text":"pageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"text":"pageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"needMemberCount:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"needMemberCount","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"needRole:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"needRole"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<EMGroup *>"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMError","kind":"typeIdentifier","text":"EMError"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"page","content":[{"inlineContent":[{"text":"Page number.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Size number of the page.","type":"text"}],"type":"paragraph"}],"name":"pageSize"},{"name":"needMemberCount","content":[{"type":"paragraph","inlineContent":[{"text":"Whether the number of returned group members is included in the group object in the callback.","type":"text"}]}]},{"name":"needRole","content":[{"inlineContent":[{"type":"text","text":"Whether the current user role of returned group in the group object in the callback."}],"type":"paragraph"}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty  "},{"code":"Array<ChatGroup>","type":"codeVoice"},{"text":" object will be returned.","type":"text"}]}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/title","value":"GroupService"},{"value":[{"text":"GroupService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/navigatorTitle","value":[{"kind":"identifier","text":"GroupService"}]},{"value":"getJoinedGroupsWithPage:pageSize:needMemberCount:needRole:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1getJoinedGroups(page:pageSize:needMemberCount:needRole:completion:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"getJoinedGroupsWithPage:pageSize:needMemberCount:needRole:completion:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1getJoinedGroups(page:pageSize:needMemberCount:needRole:completion:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}