{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mute"},{"kind":"text","text":"("},{"text":"userIds","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"muteWithUserIds:duration:groupId:completion:"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)GroupService(im)muteWithUserIds:duration:groupId:completion:","symbolKind":"method","roleHeading":"Instance Method","title":"mute(userIds:duration:groupId:completion:)"},"abstract":[{"type":"text","text":"Mute a user."}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/mute(userIds:duration:groupId:completion:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mute","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"userIds"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user."}]}],"name":"userIds"},{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"text":"Mute time range.","type":"text"}]}]},{"name":"groupId","content":[{"inlineContent":[{"text":"ID of the group.","type":"text"}],"type":"paragraph"}]},{"name":"completion","content":[{"inlineContent":[{"text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupservice\/mute(userids:duration:groupid:completion:)"]},{"paths":["\/documentation\/easechatuikit\/groupservice\/mute(userids:duration:groupid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService/mute(userIds:duration:groupId:completion:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mute","kind":"identifier"},{"text":"(","kind":"text"},{"text":"userIds","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"text":", ","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier","text":"ChatGroup"},{"kind":"text","text":"?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/mute(userIds:duration:groupId:completion:)","kind":"symbol","abstract":[{"type":"text","text":"Mute a user."}],"type":"topic","required":true,"navigatorTitle":[{"text":"muteWithUserIds:duration:groupId:completion:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/groupservice\/mute(userids:duration:groupid:completion:)","title":"mute(userIds:duration:groupId:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService":{"title":"GroupService","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupService","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/groupservice","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService","navigatorTitle":[{"text":"GroupService","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroup":{"title":"ChatGroup","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"title":"ChatError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chaterror","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"muteWithUserIds:duration:groupId:completion:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"muteWithUserIds:duration:groupId:completion:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"muteWithUserIds:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"userIds","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration:"},{"text":"(","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"duration"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"groupId","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"EMGroup","preciseIdentifier":"c:objc(cs)EMGroup"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError","text":"EMError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"muteWithUserIds:duration:groupId:completion:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1mute(userIds:duration:groupId:completion:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1mute(userIds:duration:groupId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"muteWithUserIds:duration:groupId:completion:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/title","value":"GroupService","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupService"}]}]}]}