{"abstract":[{"text":"Transfer group own to another one.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupservice\/transfer(groupid:userid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupservice\/transfer(groupid:userid:completion:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/transfer(groupId:userId:completion:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transfer"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"ChatGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"ID of the group"}],"type":"paragraph"}],"name":"groupId"},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the new owner.","type":"text"}]}],"name":"userId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback"}]}],"name":"completion"}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)GroupService(im)transferWithGroupId:userId:completion:","role":"symbol","title":"transfer(groupId:userId:completion:)","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transfer","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"transferWithGroupId:userId:completion:"}]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService/transfer(groupId:userId:completion:)":{"navigatorTitle":[{"text":"transferWithGroupId:userId:completion:","kind":"identifier"}],"required":true,"abstract":[{"text":"Transfer group own to another one.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService\/transfer(groupId:userId:completion:)","kind":"symbol","url":"\/documentation\/easechatuikit\/groupservice\/transfer(groupid:userid:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"transfer","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"transfer(groupId:userId:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupService":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"GroupService","kind":"identifier"}],"role":"symbol","title":"GroupService","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/groupservice","navigatorTitle":[{"kind":"identifier","text":"GroupService"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupService"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroup":{"url":"\/documentation\/easechatuikit\/chatgroup","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatGroup"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ChatGroup","kind":"identifier"}],"title":"ChatGroup","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"url":"\/documentation\/easechatuikit\/chaterror","role":"symbol","abstract":[],"title":"ChatError","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"}],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"transferWithGroupId:userId:completion:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"transferWithGroupId:userId:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"transferWithGroupId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"EMGroup","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMGroup"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"EMError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1transfer(groupId:userId:completion:)\/title","op":"replace","value":"transferWithGroupId:userId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService~1transfer(groupId:userId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transferWithGroupId:userId:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/title","value":"GroupService","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupService\/fragments","value":[{"text":"GroupService","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}