{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"When message received."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","text":"ChatMessage"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"}]}]}],"kind":"parameters"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidReceived"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onMessageDidReceivedWithMessage:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener(im)onMessageDidReceivedWithMessage:","symbolKind":"method","roleHeading":"Instance Method","title":"onMessageDidReceived(message:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidreceived(message:)"]},{"paths":["\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidreceived(message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidReceived(message:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageDidReceived(message:)":{"kind":"symbol","abstract":[{"type":"text","text":"When message received."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageDidReceived","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"title":"onMessageDidReceived(message:)","type":"topic","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidReceived(message:)","role":"symbol","navigatorTitle":[{"text":"onMessageDidReceivedWithMessage:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidreceived(message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatResponseListener","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","title":"ChatResponseListener","url":"\/documentation\/easechatuikit\/chatresponselistener","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatResponseListener","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","title":"ChatMessage","abstract":[],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"onMessageDidReceivedWithMessage:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onMessageDidReceivedWithMessage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"EMChatMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMChatMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onMessageDidReceivedWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidReceived(message:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidReceived(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/title","value":"ChatResponseListener"},{"value":[{"text":"ChatResponseListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/fragments"}]}]}