{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidRecalled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recallInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","text":"RecallInfo"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"recallInfo","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidrecalled(recallinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidrecalled(recallinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidRecalled(recallInfo:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When message recalled."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}],"role":"symbol","title":"onMessageDidRecalled(recallInfo:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidRecalled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recallInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener(im)onMessageDidRecalledWithRecallInfo:","required":true,"modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"url":"\/documentation\/easechatuikit\/chatmessage"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/RecallInfo":{"role":"symbol","title":"RecallInfo","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"RecallInfo"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RecallInfo"}],"url":"\/documentation\/easechatuikit\/recallinfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageDidRecalled(recallInfo:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}],"role":"symbol","title":"onMessageDidRecalled(recallInfo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidRecalled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"recallInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"When message recalled."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageDidRecalled(recallInfo:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagedidrecalled(recallinfo:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener":{"role":"symbol","title":"ChatResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatResponseListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatResponseListener"}],"url":"\/documentation\/easechatuikit\/chatresponselistener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onMessageDidRecalledWithRecallInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"AgoraChatRecallMessageInfo","preciseIdentifier":"c:objc(cs)AgoraChatRecallMessageInfo"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"recallInfo"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidRecalled(recallInfo:)\/title","value":"onMessageDidRecalledWithRecallInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageDidRecalled(recallInfo:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/title","value":"ChatResponseListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/fragments","value":[{"kind":"identifier","text":"ChatResponseListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}