{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageReactionChanged(changes:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/chatresponselistener\/onmessagereactionchanged(changes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatresponselistener\/onmessagereactionchanged(changes:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageReactionChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"changes"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea","text":"MessageReactionChange","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"changes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","type":"reference","isActive":true}]}]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","required":true,"title":"onMessageReactionChanged(changes:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageReactionChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"changes","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea","text":"MessageReactionChange"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(pl)ChatResponseListener(im)onMessageReactionChangedWithChanges:","role":"symbol","navigatorTitle":[{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}]},"abstract":[{"type":"text","text":"When reaction of message changed."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener/onMessageReactionChanged(changes:)":{"url":"\/documentation\/easechatuikit\/chatresponselistener\/onmessagereactionchanged(changes:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}],"kind":"symbol","required":true,"abstract":[{"type":"text","text":"When reaction of message changed."}],"title":"onMessageReactionChanged(changes:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReactionChanged"},{"text":"(","kind":"text"},{"text":"changes","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"MessageReactionChange","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener\/onMessageReactionChanged(changes:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionChange":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageReactionChange","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MessageReactionChange","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReactionChange","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagereactionchange"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatResponseListener":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/chatresponselistener","type":"topic","title":"ChatResponseListener","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatResponseListener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatResponseListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"ChatResponseListener","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onMessageReactionChangedWithChanges:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageReactionChangedWithChanges:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<EMMessageReactionChange *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"changes","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageReactionChanged(changes:)\/title","value":"onMessageReactionChangedWithChanges:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener~1onMessageReactionChanged(changes:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}]},{"op":"replace","value":"ChatResponseListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ChatResponseListener"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatResponseListener\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}