{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactlistactioneventsdelegate\/oncontactlistendscrollneededdisplayinfos(ids:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactlistactioneventsdelegate\/oncontactlistendscrollneededdisplayinfos(ids:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onContactListEndScrollNeededDisplayInfos","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}]}]},{"kind":"parameters","parameters":[{"name":"ids","content":[{"type":"paragraph","inlineContent":[{"text":"[conversationId]","type":"text"}]}]}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"required":true,"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfos"},{"text":"(","kind":"text"},{"text":"ids","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)ContactListActionEventsDelegate(im)onContactListEndScrollNeededDisplayInfosWithIds:","navigatorTitle":[{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}],"symbolKind":"method","title":"onContactListEndScrollNeededDisplayInfos(ids:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListEndScrollNeededDisplayInfos(ids:)"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate"]]},"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListActionEventsDelegate/onContactListEndScrollNeededDisplayInfos(ids:)":{"navigatorTitle":[{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}],"abstract":[{"text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate\/onContactListEndScrollNeededDisplayInfos(ids:)","type":"topic","url":"\/documentation\/easechatuikit\/contactlistactioneventsdelegate\/oncontactlistendscrollneededdisplayinfos(ids:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfos"},{"text":"(","kind":"text"},{"text":"ids","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"title":"onContactListEndScrollNeededDisplayInfos(ids:)","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListActionEventsDelegate":{"abstract":[{"text":"ContactList action events delegate.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListActionEventsDelegate","type":"topic","url":"\/documentation\/easechatuikit\/contactlistactioneventsdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListActionEventsDelegate"}],"title":"ContactListActionEventsDelegate","navigatorTitle":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"onContactListEndScrollNeededDisplayInfosWithIds:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"onContactListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onContactListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ids"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onContactListEndScrollNeededDisplayInfosWithIds:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListEndScrollNeededDisplayInfos(ids:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onContactListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate~1onContactListEndScrollNeededDisplayInfos(ids:)\/fragments"},{"value":"ContactListActionEventsDelegate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListActionEventsDelegate\/fragments","value":[{"text":"ContactListActionEventsDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}