{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"descriptionTopConstraint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSLayoutConstraint","kind":"typeIdentifier","text":"NSLayoutConstraint"},{"text":"! { get }","kind":"text"}]}]}],"metadata":{"title":"descriptionTopConstraint","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit20URLPreviewResultViewC24descriptionTopConstraintSo08NSLayoutI0CSgvp","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"descriptionTopConstraint"},{"text":": ","kind":"text"},{"text":"NSLayoutConstraint","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","kind":"typeIdentifier"},{"kind":"text","text":"!"}],"symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/easechatuikit\/urlpreviewresultview\/descriptiontopconstraint"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/descriptionTopConstraint"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView/descriptionTopConstraint":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"descriptionTopConstraint","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSLayoutConstraint","text":"NSLayoutConstraint"},{"text":"!","kind":"text"}],"url":"\/documentation\/easechatuikit\/urlpreviewresultview\/descriptiontopconstraint","role":"symbol","kind":"symbol","abstract":[],"title":"descriptionTopConstraint","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/descriptionTopConstraint"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewResultView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/urlpreviewresultview","role":"symbol","kind":"symbol","abstract":[],"title":"URLPreviewResultView","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView","navigatorTitle":[{"text":"URLPreviewResultView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"URLPreviewResultView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/fragments","value":[{"text":"URLPreviewResultView","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"URLPreviewResultView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/navigatorTitle"}]}]}