{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/init(coder:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"init","title":"init(coder:)","roleHeading":"Initializer","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)URLPreviewResultView(im)initWithCoder:","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/urlpreviewresultview\/init(coder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/urlpreviewresultview\/init(coder:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView/init(coder:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/urlpreviewresultview\/init(coder:)","role":"symbol","kind":"symbol","abstract":[],"title":"init(coder:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/init(coder:)","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewResultView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/urlpreviewresultview","role":"symbol","kind":"symbol","abstract":[],"title":"URLPreviewResultView","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView","navigatorTitle":[{"text":"URLPreviewResultView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithCoder:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":" *) "},{"text":"coder","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView~1init(coder:)\/fragments"},{"op":"replace","value":"URLPreviewResultView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/fragments","value":[{"text":"URLPreviewResultView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/navigatorTitle","value":[{"kind":"identifier","text":"URLPreviewResultView"}],"op":"replace"}]}]}