{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"content"},{"kind":"text","text":": "},{"text":"URLPreviewManager","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)URLPreviewManager","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit17URLPreviewManagerC11HTMLContentC","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent","text":"HTMLContent"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/show(with:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"show(with:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)URLPreviewResultView(im)showWith:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)URLPreviewManager","text":"URLPreviewManager"},{"text":".","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit17URLPreviewManagerC11HTMLContentC","text":"HTMLContent","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showWith:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/urlpreviewresultview\/show(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/urlpreviewresultview\/show(with:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewResultView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/urlpreviewresultview","role":"symbol","kind":"symbol","abstract":[],"title":"URLPreviewResultView","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView","navigatorTitle":[{"text":"URLPreviewResultView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager":{"role":"symbol","type":"topic","title":"URLPreviewManager","kind":"symbol","url":"\/documentation\/easechatuikit\/urlpreviewmanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewManager","kind":"identifier"}],"navigatorTitle":[{"text":"URLPreviewManager","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView/show(with:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"show","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"URLPreviewManager","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)URLPreviewManager","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"HTMLContent","preciseIdentifier":"s:13EaseChatUIKit17URLPreviewManagerC11HTMLContentC","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"abstract":[],"title":"show(with:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showWith:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/show(with:)","url":"\/documentation\/easechatuikit\/urlpreviewresultview\/show(with:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager/HTMLContent":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTMLContent","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/urlpreviewmanager\/htmlcontent","role":"symbol","title":"URLPreviewManager.HTMLContent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent","navigatorTitle":[{"kind":"identifier","text":"HTMLContent"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"showWith:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showWith:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"showWith:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)HTMLContent","text":"HTMLContent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"content"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"URLPreviewResultView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/title","op":"replace"},{"op":"replace","value":[{"text":"URLPreviewResultView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/navigatorTitle","value":[{"text":"URLPreviewResultView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/title","value":"URLPreviewManager"},{"value":[{"kind":"identifier","text":"URLPreviewManager"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/navigatorTitle","value":[{"kind":"identifier","text":"URLPreviewManager"}],"op":"replace"},{"value":"showWith:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView~1show(with:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView~1show(with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showWith:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}