{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView"]]},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/switchTheme(style:)"],"title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/urlpreviewresultview\/themeswitchprotocol-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/urlpreviewresultview\/themeswitchprotocol-implementations"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"ThemeSwitchProtocol Implementations"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView/switchTheme(style:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/switchTheme(style:)","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/urlpreviewresultview\/switchtheme(style:)","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" to switch theme.","type":"text"}],"title":"switchTheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewResultView":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewResultView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/urlpreviewresultview","role":"symbol","kind":"symbol","abstract":[],"title":"URLPreviewResultView","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView","navigatorTitle":[{"text":"URLPreviewResultView","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewResultView\/switchTheme(style:)"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView~1switchTheme(style:)\/title","value":"switchThemeWithStyle:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView~1switchTheme(style:)\/fragments"},{"op":"replace","value":"URLPreviewResultView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/fragments","value":[{"text":"URLPreviewResultView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewResultView\/navigatorTitle","value":[{"kind":"identifier","text":"URLPreviewResultView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}