{"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The closure to be executed when the action sheet item is selected."}],"metadata":{"symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem(py)action","roleHeading":"Instance Property","title":"action","role":"symbol","navigatorTitle":[{"text":"action","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea","text":"ActionClosure"},{"kind":"text","text":"?"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionClosure","kind":"typeIdentifier","text":"ActionClosure"},{"kind":"text","text":"?"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem\/action","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/actionsheetitem\/action"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/actionsheetitem\/action"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem/action":{"url":"\/documentation\/easechatuikit\/actionsheetitem\/action","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem\/action","title":"action","abstract":[{"type":"text","text":"The closure to be executed when the action sheet item is selected."}],"role":"symbol","navigatorTitle":[{"text":"action","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ActionClosure","preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem":{"url":"\/documentation\/easechatuikit\/actionsheetitem","title":"ActionSheetItem","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItem"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItem"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionClosure":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionClosure","role":"symbol","title":"ActionClosure","navigatorTitle":[{"text":"ActionClosure","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/actionclosure","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ActionClosure","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"action","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"action","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":"action","kind":"identifier"},{"kind":"text","text":")("},{"text":"id<ActionSheetItemProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"keyword","text":"id"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":");"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem~1action\/title","op":"replace","value":"action"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem~1action\/fragments","value":[{"kind":"identifier","text":"action"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/title","value":"ActionSheetItem"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/fragments","value":[{"text":"ActionSheetItem","kind":"identifier"}],"op":"replace"}]}]}