{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem\/init(title:type:tag:action:)"},"abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"type":"codeVoice","code":"ActionSheetItem"},{"type":"text","text":" object with a title, type, tag, and action closure."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/actionsheetitem\/init(title:type:tag:action:)"]},{"paths":["\/documentation\/easechatuikit\/actionsheetitem\/init(title:type:tag:action:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithTitle:type:tag:action:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ActionSheetItemType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea","text":"ActionClosure"},{"text":")","kind":"text"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem(im)initWithTitle:type:tag:action:","role":"symbol","title":"init(title:type:tag:action:)","roleHeading":"Initializer","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ActionSheetItemType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionClosure","text":"ActionClosure","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"title: The title of the action sheet item."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"type: The type of the action sheet item."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"action: The closure to be executed when the action sheet item is selected.","type":"text"}]}]}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/actionsheetitem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ActionSheetItem","kind":"identifier"}],"kind":"symbol","type":"topic","title":"ActionSheetItem","navigatorTitle":[{"text":"ActionSheetItem","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem/init(title:type:tag:action:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"type":"codeVoice","code":"ActionSheetItem"},{"type":"text","text":" object with a title, type, tag, and action closure."}],"navigatorTitle":[{"text":"initWithTitle:type:tag:action:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem\/init(title:type:tag:action:)","url":"\/documentation\/easechatuikit\/actionsheetitem\/init(title:type:tag:action:)","title":"init(title:type:tag:action:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ActionSheetItemType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType"},{"text":", ","kind":"text"},{"text":"tag","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"ActionClosure","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType":{"title":"ActionSheetItemType","navigatorTitle":[{"text":"ActionSheetItemType","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionSheetItemType","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/actionsheetitemtype","kind":"symbol","abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionClosure":{"role":"symbol","url":"\/documentation\/easechatuikit\/actionclosure","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionClosure","type":"topic","title":"ActionClosure","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionClosure"}],"navigatorTitle":[{"text":"ActionClosure","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithTitle:type:tag:action:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTitle:type:tag:action:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTitle:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ActionSheetItemType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"text":"tag:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"tag","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"action:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"id<ActionSheetItemProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"add","value":{"content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"An "},{"type":"codeVoice","code":"ActionSheetItem"},{"type":"text","text":" object."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/1"},{"value":"ActionSheetItem","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/fragments","value":[{"kind":"identifier","text":"ActionSheetItem"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/navigatorTitle","value":[{"kind":"identifier","text":"ActionSheetItem"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem~1init(title:type:tag:action:)\/title","value":"initWithTitle:type:tag:action:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTitle:type:tag:action:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem~1init(title:type:tag:action:)\/fragments"},{"value":"ActionSheetItemType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/title"},{"op":"replace","value":[{"text":"ActionSheetItemType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/navigatorTitle","op":"replace","value":[{"text":"ActionSheetItemType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}