{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem\/init(title:type:tag:image:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","text":"ActionSheetItemType"},{"kind":"text","text":", "},{"text":"tag","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?)","kind":"text"}],"symbolKind":"init","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem(im)initWithTitle:type:tag:image:","title":"init(title:type:tag:image:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithTitle:type:tag:image:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"type":"codeVoice","code":"ActionSheetItem"},{"type":"text","text":" object with a title, type, and tag."}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/actionsheetitem\/init(title:type:tag:image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/actionsheetitem\/init(title:type:tag:image:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","kind":"typeIdentifier","text":"ActionSheetItemType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tag"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"? = nil)","kind":"text"}]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"An ","type":"text"},{"type":"codeVoice","code":"ActionSheetItem"},{"text":" object.","type":"text"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"title: The title of the action sheet item.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"type: The type of the action sheet item."}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem/init(title:type:tag:image:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","text":"ActionSheetItemType"},{"kind":"text","text":", "},{"text":"tag","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?)"}],"url":"\/documentation\/easechatuikit\/actionsheetitem\/init(title:type:tag:image:)","abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"code":"ActionSheetItem","type":"codeVoice"},{"type":"text","text":" object with a title, type, and tag."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem\/init(title:type:tag:image:)","role":"symbol","kind":"symbol","title":"init(title:type:tag:image:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithTitle:type:tag:image:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem":{"role":"symbol","navigatorTitle":[{"text":"ActionSheetItem","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionSheetItem","kind":"identifier"}],"type":"topic","title":"ActionSheetItem","url":"\/documentation\/easechatuikit\/actionsheetitem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","title":"ActionSheetItemType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItemType"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}],"url":"\/documentation\/easechatuikit\/actionsheetitemtype","navigatorTitle":[{"text":"ActionSheetItemType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithTitle:type:tag:image:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTitle:type:tag:image:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithTitle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"title"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","text":"ActionSheetItemType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tag:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tag"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image:"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem~1init(title:type:tag:image:)\/title","value":"initWithTitle:type:tag:image:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem~1init(title:type:tag:image:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithTitle:type:tag:image:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ActionSheetItem","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/fragments","value":[{"kind":"identifier","text":"ActionSheetItem"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/title","op":"replace","value":"ActionSheetItemType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/fragments","value":[{"kind":"identifier","text":"ActionSheetItemType"}]}]}]}