{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/messagemultiselectedbottombaroperation\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"generated":true,"title":"Operators","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation\/!=(_:_:)"],"anchor":"Operators"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBarOperation":{"navigatorTitle":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombaroperation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageMultiSelectedBottomBarOperation"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","abstract":[],"title":"MessageMultiSelectedBottomBarOperation","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBarOperation/!=(_:_:)":{"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombaroperation\/!=(_:_:)","title":"!=(_:_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation\/!=(_:_:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/title","value":"MessageMultiSelectedBottomBarOperation"},{"value":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/navigatorTitle","value":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}