{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlistcell\/avatar"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListCell\/avatar","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListCell"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatar"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","text":"ImageView","kind":"typeIdentifier"}],"title":"avatar","role":"symbol","externalID":"s:13EaseChatUIKit20ConversationListCellC6avatarAA9ImageViewCvp"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","text":"ImageView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListCell/avatar":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListCell\/avatar","type":"topic","title":"avatar","url":"\/documentation\/easechatuikit\/conversationlistcell\/avatar","kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"avatar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListCell":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationListCell","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListCell","title":"ConversationListCell","url":"\/documentation\/easechatuikit\/conversationlistcell","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ConversationListCell","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ImageView":{"kind":"symbol","navigatorTitle":[{"text":"ImageView","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageView"}],"title":"ImageView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","role":"symbol","type":"topic","abstract":[{"type":"text","text":"A subclass of "},{"code":"UIImageView","type":"codeVoice"},{"text":" that provides a method for loading an image from a URL.","type":"text"}],"url":"\/documentation\/easechatuikit\/imageview"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"ConversationListCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListCell\/title"},{"value":[{"kind":"identifier","text":"ConversationListCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListCell\/fragments","op":"replace"},{"value":"ImageView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/fragments","value":[{"kind":"identifier","text":"ImageView"}],"op":"replace"}]}]}