{"topicSections":[{"generated":true,"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/!=(_:_:)"]}],"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/Equatable-Implementations","interfaceLanguage":"swift"},"sections":[],"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageattachmentmenustyle\/equatable-implementations"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle/!=(_:_:)":{"role":"symbol","abstract":[],"title":"!=(_:_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/messageattachmentmenustyle\/!=(_:_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle":{"navigatorTitle":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MessageAttachmentMenuStyle"}},"variantOverrides":[{"patch":[{"value":"MessageAttachmentMenuStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}]},{"value":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}