{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/followInput","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"followInput","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easechatuikit\/messageattachmentmenustyle\/followinput"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messageattachmentmenustyle\/followinput"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"followInput","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"EaseChatUIKit"}],"title":"MessageAttachmentMenuStyle.followInput","externalID":"c:@M@EaseChatUIKit@E@MessageAttachmentMenuStyle@MessageAttachmentMenuStyleFollowInput","navigatorTitle":[{"kind":"identifier","text":"MessageAttachmentMenuStyleFollowInput"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle":{"navigatorTitle":[{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageAttachmentMenuStyle","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MessageAttachmentMenuStyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageAttachmentMenuStyle/followInput":{"url":"\/documentation\/easechatuikit\/messageattachmentmenustyle\/followinput","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"followInput"}],"abstract":[],"navigatorTitle":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}],"title":"MessageAttachmentMenuStyle.followInput","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageAttachmentMenuStyle\/followInput","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"MessageAttachmentMenuStyleFollowInput","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"MessageAttachmentMenuStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle\/navigatorTitle","value":[{"kind":"identifier","text":"MessageAttachmentMenuStyle"}],"op":"replace"},{"value":"MessageAttachmentMenuStyleFollowInput","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle~1followInput\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageAttachmentMenuStyle~1followInput\/fragments","value":[{"text":"MessageAttachmentMenuStyleFollowInput","kind":"identifier"}]}]}]}