{"sections":[],"kind":"symbol","metadata":{"role":"symbol","title":"MessageCellClickArea.cell","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@MessageCellClickArea@MessageCellClickAreaCell","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"cell","kind":"identifier"}],"navigatorTitle":[{"text":"MessageCellClickAreaCell","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cell"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/cell","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecellclickarea\/cell"]},{"paths":["\/documentation\/easechatuikit\/messagecellclickarea\/cell"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea":{"navigatorTitle":[{"kind":"identifier","text":"MessageCellClickArea"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageCellClickArea","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Enum representing the different areas that can be clicked in a message cell."}],"title":"MessageCellClickArea","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea","url":"\/documentation\/easechatuikit\/messagecellclickarea","kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/cell":{"url":"\/documentation\/easechatuikit\/messagecellclickarea\/cell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/cell","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"cell","kind":"identifier"}],"title":"MessageCellClickArea.cell","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageCellClickAreaCell","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MessageCellClickAreaCell","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCellClickAreaCell"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MessageCellClickAreaCell","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"value":"MessageCellClickArea","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/fragments","value":[{"text":"MessageCellClickArea","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/navigatorTitle","value":[{"text":"MessageCellClickArea","kind":"identifier"}],"op":"replace"},{"value":"MessageCellClickAreaCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1cell\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1cell\/fragments","value":[{"text":"MessageCellClickAreaCell","kind":"identifier"}],"op":"replace"}]}]}