{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/status","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/messagecellclickarea\/status"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagecellclickarea\/status"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@MessageCellClickArea@MessageCellClickAreaStatus","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickAreaStatus"}],"title":"MessageCellClickArea.status","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"}]},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea":{"abstract":[{"text":"Enum representing the different areas that can be clicked in a message cell.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageCellClickArea","kind":"identifier"}],"title":"MessageCellClickArea","type":"topic","url":"\/documentation\/easechatuikit\/messagecellclickarea","navigatorTitle":[{"kind":"identifier","text":"MessageCellClickArea"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellClickArea/status":{"kind":"symbol","url":"\/documentation\/easechatuikit\/messagecellclickarea\/status","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellClickArea\/status","navigatorTitle":[{"text":"MessageCellClickAreaStatus","kind":"identifier"}],"title":"MessageCellClickArea.status","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"MessageCellClickAreaStatus","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"MessageCellClickAreaStatus"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"MessageCellClickAreaStatus","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/title","value":"MessageCellClickArea"},{"value":[{"kind":"identifier","text":"MessageCellClickArea"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1status\/title","value":"MessageCellClickAreaStatus","op":"replace"},{"value":[{"text":"MessageCellClickAreaStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellClickArea~1status\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}