{"sections":[],"metadata":{"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headlineMedium"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"headlineMedium","kind":"identifier"}],"title":"headlineMedium","externalID":"c:@M@EaseChatUIKit@objc(cs)FontTheme(py)headlineMedium","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FontTheme\/headlineMedium","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"headlineMedium"},{"kind":"text","text":": "},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/fonttheme\/headlinemedium"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/fonttheme\/headlinemedium"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FontTheme"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/FontTheme/headlineMedium":{"title":"headlineMedium","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headlineMedium"},{"text":": ","kind":"text"},{"text":"UIFont","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont"}],"navigatorTitle":[{"kind":"identifier","text":"headlineMedium"}],"url":"\/documentation\/easechatuikit\/fonttheme\/headlinemedium","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FontTheme\/headlineMedium"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/FontTheme":{"navigatorTitle":[{"text":"FontTheme","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FontTheme"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FontTheme","kind":"symbol","title":"FontTheme","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/fonttheme","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"headlineMedium","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"headlineMedium","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" * "},{"text":"headlineMedium","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"headlineMedium","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FontTheme~1headlineMedium\/title"},{"value":[{"kind":"identifier","text":"headlineMedium"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FontTheme~1headlineMedium\/fragments","op":"replace"},{"op":"replace","value":"FontTheme","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FontTheme\/title"},{"value":[{"text":"FontTheme","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FontTheme\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"FontTheme"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FontTheme\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}