{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchheaderbar\/actionclosure"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/actionClosure","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"actionClosure","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@SearchHeaderBarActionType","kind":"typeIdentifier","text":"SearchHeaderBarActionType"},{"text":") -> ())?","kind":"text"}],"externalID":"s:13EaseChatUIKit15SearchHeaderBarC13actionClosureyAA0deF10ActionTypeOcSgvp","title":"actionClosure","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@SearchHeaderBarActionType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarActionType","text":"SearchHeaderBarActionType"},{"text":") -> ())?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/actionClosure":{"role":"symbol","url":"\/documentation\/easechatuikit\/searchheaderbar\/actionclosure","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/actionClosure","abstract":[],"title":"actionClosure","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"actionClosure","kind":"identifier"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"SearchHeaderBarActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@SearchHeaderBarActionType"},{"text":") -> ())?","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarActionType":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarActionType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarActionType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SearchHeaderBarActionType","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"SearchHeaderBarActionType","url":"\/documentation\/easechatuikit\/searchheaderbaractiontype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","url":"\/documentation\/easechatuikit\/searchheaderbar","type":"topic","navigatorTitle":[{"text":"SearchHeaderBar","kind":"identifier"}],"abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchHeaderBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SearchHeaderBarActionType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarActionType\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarActionType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarActionType\/navigatorTitle","value":[{"kind":"identifier","text":"SearchHeaderBarActionType"}]},{"value":"SearchHeaderBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/fragments","op":"replace","value":[{"kind":"identifier","text":"SearchHeaderBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/navigatorTitle","value":[{"text":"SearchHeaderBar","kind":"identifier"}]}]}]}