{"variants":[{"paths":["\/documentation\/easechatuikit\/searchheaderbar\/init(frame:displaystyle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchheaderbar\/init(frame:displaystyle:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar"]]},"metadata":{"navigatorTitle":[{"text":"initWithFrame:displayStyle:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"init","externalID":"c:@M@EaseChatUIKit@objc(cs)SearchHeaderBar(im)initWithFrame:displayStyle:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"displayStyle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@SearchHeaderBarDisplayStyle","text":"SearchHeaderBarDisplayStyle"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol","title":"init(frame:displayStyle:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/init(frame:displayStyle:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"displayStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@SearchHeaderBarDisplayStyle","text":"SearchHeaderBarDisplayStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/init(frame:displayStyle:)":{"title":"init(frame:displayStyle:)","url":"\/documentation\/easechatuikit\/searchheaderbar\/init(frame:displaystyle:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"displayStyle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@SearchHeaderBarDisplayStyle","text":"SearchHeaderBarDisplayStyle"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/init(frame:displayStyle:)","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:displayStyle:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","url":"\/documentation\/easechatuikit\/searchheaderbar","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHeaderBar"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBar"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle":{"title":"SearchHeaderBarDisplayStyle","url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithFrame:displayStyle:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:displayStyle:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayStyle:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@SearchHeaderBarDisplayStyle","text":"SearchHeaderBarDisplayStyle"},{"text":") ","kind":"text"},{"text":"displayStyle","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"initWithFrame:displayStyle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1init(frame:displayStyle:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1init(frame:displayStyle:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:displayStyle:"}]},{"op":"replace","value":"SearchHeaderBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/fragments","op":"replace","value":[{"text":"SearchHeaderBar","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/title","value":"SearchHeaderBarDisplayStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/fragments","value":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}