{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":" "},{"kind":"internalParam","text":"range"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":" "},{"kind":"internalParam","text":"string"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/searchheaderbar\/textfield(_:shouldchangecharactersin:replacementstring:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/searchheaderbar\/textfield(_:shouldchangecharactersin:replacementstring:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textField(_:shouldChangeCharactersIn:replacementString:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UITextFieldDelegate.textField(_:shouldChangeCharactersIn:replacementString:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"textField(_:shouldChangeCharactersIn:replacementString:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)SearchHeaderBar(im)textField:shouldChangeCharactersInRange:replacementString:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/UITextFieldDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/UITextFieldDelegate-Implementations":{"role":"collectionGroup","title":"UITextFieldDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/UITextFieldDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/searchheaderbar\/uitextfielddelegate-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/textField(_:shouldChangeCharactersIn:replacementString:)":{"role":"symbol","title":"textField(_:shouldChangeCharactersIn:replacementString:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textField"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldChangeCharactersIn"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textField(_:shouldChangeCharactersIn:replacementString:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"url":"\/documentation\/easechatuikit\/searchheaderbar\/textfield(_:shouldchangecharactersin:replacementstring:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar":{"role":"symbol","title":"SearchHeaderBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchHeaderBar"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBar"}],"url":"\/documentation\/easechatuikit\/searchheaderbar"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"textField:shouldChangeCharactersInRange:replacementString:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"textField:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextField","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldChangeCharactersInRange:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@S@_NSRange"},{"kind":"text","text":") "},{"kind":"internalParam","text":"range"},{"kind":"text","text":" "},{"kind":"identifier","text":"replacementString:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"string"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textField(_:shouldChangeCharactersIn:replacementString:)\/title","value":"textField:shouldChangeCharactersInRange:replacementString:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textField(_:shouldChangeCharactersIn:replacementString:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/title","value":"SearchHeaderBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}