{"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITextFieldDelegate.textFieldDidEndEditing(_:)","type":"codeVoice"},{"text":".","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textFieldDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier","text":"UITextField"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/UITextFieldDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchheaderbar\/textfielddidendediting(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchheaderbar\/textfielddidendediting(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldDidEndEditing(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"textFieldDidEndEditing:","kind":"identifier"}],"role":"symbol","extendedModule":"EaseChatUIKit","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textFieldDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITextField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField"},{"kind":"text","text":")"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)SearchHeaderBar(im)textFieldDidEndEditing:","modules":[{"name":"EaseChatUIKit"}],"title":"textFieldDidEndEditing(_:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/UITextFieldDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/searchheaderbar\/uitextfielddelegate-implementations","title":"UITextFieldDelegate Implementations","kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/UITextFieldDelegate-Implementations","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","kind":"symbol","url":"\/documentation\/easechatuikit\/searchheaderbar","navigatorTitle":[{"text":"SearchHeaderBar","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHeaderBar"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/textFieldDidEndEditing(_:)":{"url":"\/documentation\/easechatuikit\/searchheaderbar\/textfielddidendediting(_:)","title":"textFieldDidEndEditing(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"textFieldDidEndEditing:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textFieldDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextField","kind":"typeIdentifier","text":"UITextField"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldDidEndEditing(_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"textFieldDidEndEditing:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldDidEndEditing:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"textFieldDidEndEditing:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textField"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/title","op":"replace","value":"SearchHeaderBar"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/fragments","value":[{"kind":"identifier","text":"SearchHeaderBar"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textFieldDidEndEditing(_:)\/title","value":"textFieldDidEndEditing:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textFieldDidEndEditing(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"textFieldDidEndEditing:","kind":"identifier"}]}]}]}