{"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textField(_:shouldChangeCharactersIn:replacementString:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldDidEndEditing(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldShouldBeginEditing(_:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchheaderbar\/uitextfielddelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchheaderbar\/uitextfielddelegate-implementations"]}],"metadata":{"title":"UITextFieldDelegate Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/UITextFieldDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar":{"title":"SearchHeaderBar","url":"\/documentation\/easechatuikit\/searchheaderbar","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHeaderBar"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBar"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/textFieldShouldBeginEditing(_:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldShouldBeginEditing"},{"text":"(","kind":"text"},{"text":"UITextField","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldShouldBeginEditing(_:)","type":"topic","kind":"symbol","title":"textFieldShouldBeginEditing(_:)","role":"symbol","navigatorTitle":[{"text":"textFieldShouldBeginEditing:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/searchheaderbar\/textfieldshouldbeginediting(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/textField(_:shouldChangeCharactersIn:replacementString:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/searchheaderbar\/textfield(_:shouldchangecharactersin:replacementstring:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textField(_:shouldChangeCharactersIn:replacementString:)","title":"textField(_:shouldChangeCharactersIn:replacementString:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textField","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"shouldChangeCharactersIn","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"replacementString"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textField:shouldChangeCharactersInRange:replacementString:"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBar/textFieldDidEndEditing(_:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/searchheaderbar\/textfielddidendediting(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldDidEndEditing(_:)","title":"textFieldDidEndEditing(_:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textFieldDidEndEditing","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextField","text":"UITextField"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textFieldDidEndEditing:"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textField(_:shouldChangeCharactersIn:replacementString:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldDidEndEditing(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBar\/textFieldShouldBeginEditing(_:)"],"title":"Instance Methods"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/title","value":"SearchHeaderBar"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar\/fragments","op":"replace","value":[{"kind":"identifier","text":"SearchHeaderBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textFieldShouldBeginEditing(_:)\/title","value":"textFieldShouldBeginEditing:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textFieldShouldBeginEditing(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"textFieldShouldBeginEditing:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textField(_:shouldChangeCharactersIn:replacementString:)\/title","value":"textField:shouldChangeCharactersInRange:replacementString:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textField(_:shouldChangeCharactersIn:replacementString:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textField:shouldChangeCharactersInRange:replacementString:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textFieldDidEndEditing(_:)\/title","value":"textFieldDidEndEditing:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBar~1textFieldDidEndEditing(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textFieldDidEndEditing:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}