{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"navigation","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"text":"EaseChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"}],"roleHeading":"Instance Property","role":"symbol","externalID":"s:13EaseChatUIKit33GroupParticipantsRemoveControllerC10navigationAA0aB13NavigationBarCvp"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/navigation"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/navigation","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigation"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","text":"EaseChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController/navigation":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/navigation","abstract":[],"type":"topic","kind":"symbol","title":"navigation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"EaseChatNavigationBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/navigation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"GroupParticipantsRemoveController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsRemoveController"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController","abstract":[],"title":"GroupParticipantsRemoveController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar":{"kind":"symbol","type":"topic","title":"EaseChatNavigationBar","abstract":[{"text":"Navigation  bar of the EaseChatUIKit.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","url":"\/documentation\/easechatuikit\/easechatnavigationbar","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatNavigationBar","kind":"identifier"}],"navigatorTitle":[{"text":"EaseChatNavigationBar","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController\/title","value":"GroupParticipantsRemoveController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"GroupParticipantsRemoveController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController\/fragments"},{"op":"replace","value":"EaseChatNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/title"},{"value":[{"text":"EaseChatNavigationBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/fragments"}]}]}