{"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITableViewDataSource.tableView(_:cellForRowAt:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/tableView(_:cellForRowAt:)"},"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupParticipantsRemoveController(im)tableView:cellForRowAtIndexPath:","title":"tableView(_:cellForRowAt:)","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"role":"symbol","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":" "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/UITableViewDataSource-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/tableview(_:cellforrowat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/tableview(_:cellforrowat:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController":{"title":"GroupParticipantsRemoveController","abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"GroupParticipantsRemoveController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupParticipantsRemoveController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController","url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController/tableView(_:cellForRowAt:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"type":"topic","abstract":[],"title":"tableView(_:cellForRowAt:)","url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/tableview(_:cellforrowat:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/tableView(_:cellForRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController/UITableViewDataSource-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","abstract":[],"title":"UITableViewDataSource Implementations","url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/uitableviewdatasource-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/UITableViewDataSource-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"tableView:cellForRowAtIndexPath:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"UITableViewCell","preciseIdentifier":"c:objc(cs)UITableViewCell"},{"kind":"text","text":" *) "},{"text":"tableView:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"text":" ","kind":"text"},{"text":"cellForRowAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController\/title","value":"GroupParticipantsRemoveController"},{"value":[{"text":"GroupParticipantsRemoveController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController~1tableView(_:cellForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"op":"replace"}]}]}