{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectRowAt","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/tableview(_:didselectrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/tableview(_:didselectrowat:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UITableViewDelegate.tableView(_:didSelectRowAt:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"title":"tableView(_:didSelectRowAt:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"text":"didSelectRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupParticipantsRemoveController(im)tableView:didSelectRowAtIndexPath:"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/tableView(_:didSelectRowAt:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/UITableViewDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController/UITableViewDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/UITableViewDelegate-Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/uitableviewdelegate-implementations","role":"collectionGroup","title":"UITableViewDelegate Implementations","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsRemoveController"}],"url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantsRemoveController"}],"title":"GroupParticipantsRemoveController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsRemoveController/tableView(_:didSelectRowAt:)":{"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"text":"didSelectRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/easechatuikit\/groupparticipantsremovecontroller\/tableview(_:didselectrowat:)","navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsRemoveController\/tableView(_:didSelectRowAt:)","title":"tableView(_:didSelectRowAt:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"tableView:didSelectRowAtIndexPath:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"tableView:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tableView"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didSelectRowAtIndexPath:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"GroupParticipantsRemoveController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController\/title"},{"value":[{"kind":"identifier","text":"GroupParticipantsRemoveController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController\/fragments"},{"value":[{"text":"GroupParticipantsRemoveController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsRemoveController~1tableView(_:didSelectRowAt:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}