{"abstract":[{"text":"Initializes a new ","type":"text"},{"code":"DialogContainerViewController","type":"codeVoice"},{"text":" instance with a custom view and optional constraints size.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/dialogcontainerviewcontroller\/init(custom:constraintssize:canpandismiss:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/dialogcontainerviewcontroller\/init(custom:constraintssize:canpandismiss:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogContainerViewController\/init(custom:constraintsSize:canPanDismiss:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"custom"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"constraintsSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":" = .zero, ","kind":"text"},{"text":"canPanDismiss","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = true)"}]}]},{"kind":"parameters","parameters":[{"name":"custom","content":[{"inlineContent":[{"type":"text","text":"The custom view to be displayed in the dialog container."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The size of the constraints to be applied to the dialog container’s content view. Defaults to ","type":"text"},{"type":"codeVoice","code":".zero"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"constraintsSize"}]},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A new "},{"type":"codeVoice","code":"DialogContainerViewController"},{"type":"text","text":" instance."}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogContainerViewController"]]},"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"custom","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":", "},{"text":"constraintsSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"canPanDismiss"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithCustom:constraintsSize:canPanDismiss:"}],"symbolKind":"init","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)DialogContainerViewController(im)initWithCustom:constraintsSize:canPanDismiss:","title":"init(custom:constraintsSize:canPanDismiss:)","roleHeading":"Initializer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogContainerViewController":{"navigatorTitle":[{"text":"DialogContainerViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"A view controller that manages the presentation of a dialog container view and its content."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DialogContainerViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/dialogcontainerviewcontroller","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogContainerViewController","title":"DialogContainerViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogContainerViewController/init(custom:constraintsSize:canPanDismiss:)":{"kind":"symbol","title":"init(custom:constraintsSize:canPanDismiss:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"custom"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"constraintsSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"canPanDismiss"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithCustom:constraintsSize:canPanDismiss:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogContainerViewController\/init(custom:constraintsSize:canPanDismiss:)","abstract":[{"type":"text","text":"Initializes a new "},{"type":"codeVoice","code":"DialogContainerViewController"},{"type":"text","text":" instance with a custom view and optional constraints size."}],"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/dialogcontainerviewcontroller\/init(custom:constraintssize:canpandismiss:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithCustom:constraintsSize:canPanDismiss:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCustom:constraintsSize:canPanDismiss:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithCustom:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"custom","kind":"internalParam"},{"kind":"text","text":" "},{"text":"constraintsSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"constraintsSize","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"canPanDismiss:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"canPanDismiss","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"DialogContainerViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogContainerViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogContainerViewController\/fragments","value":[{"kind":"identifier","text":"DialogContainerViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogContainerViewController~1init(custom:constraintsSize:canPanDismiss:)\/title","value":"initWithCustom:constraintsSize:canPanDismiss:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCustom:constraintsSize:canPanDismiss:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogContainerViewController~1init(custom:constraintsSize:canPanDismiss:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}