{"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"selectItem"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)SectionIndexList(im)selectItemWithIndexPath:","roleHeading":"Instance Method","title":"selectItem(indexPath:)","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"selectItemWithIndexPath:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList\/selectItem(indexPath:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(selectItemWithIndexPath:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectItem","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"code":"IndexPath","type":"codeVoice"}],"type":"paragraph"}],"name":"indexPath"}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/sectionindexlist\/selectitem(indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/sectionindexlist\/selectitem(indexpath:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList"]]},"abstract":[{"type":"text","text":"Select some item only display."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SectionIndexList":{"title":"SectionIndexList","url":"\/documentation\/easechatuikit\/sectionindexlist","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SectionIndexList"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList","abstract":[],"type":"topic","navigatorTitle":[{"text":"SectionIndexList","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SectionIndexList/selectItem(indexPath:)":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"selectItemWithIndexPath:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Select some item only display.","type":"text"}],"title":"selectItem(indexPath:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList\/selectItem(indexPath:)","url":"\/documentation\/easechatuikit\/sectionindexlist\/selectitem(indexpath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"selectItem","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"selectItemWithIndexPath:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"selectItemWithIndexPath:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"selectItemWithIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList\/title","value":"SectionIndexList"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList\/fragments","value":[{"kind":"identifier","text":"SectionIndexList"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList~1selectItem(indexPath:)\/title","op":"replace","value":"selectItemWithIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList~1selectItem(indexPath:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"selectItemWithIndexPath:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}