{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList\/UITableViewDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}],"title":"UITableViewDelegate Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList"]]},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList\/tableView(_:didSelectRowAt:)"]}],"variants":[{"paths":["\/documentation\/easechatuikit\/sectionindexlist\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/sectionindexlist\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SectionIndexList/tableView(_:didSelectRowAt:)":{"type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectRowAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList\/tableView(_:didSelectRowAt:)","abstract":[],"url":"\/documentation\/easechatuikit\/sectionindexlist\/tableview(_:didselectrowat:)","navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"kind":"symbol","title":"tableView(_:didSelectRowAt:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SectionIndexList":{"title":"SectionIndexList","url":"\/documentation\/easechatuikit\/sectionindexlist","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SectionIndexList"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList","abstract":[],"type":"topic","navigatorTitle":[{"text":"SectionIndexList","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SectionIndexList\/tableView(_:didSelectRowAt:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList~1tableView(_:didSelectRowAt:)\/title","value":"tableView:didSelectRowAtIndexPath:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:didSelectRowAtIndexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList~1tableView(_:didSelectRowAt:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList\/title","value":"SectionIndexList"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SectionIndexList\/fragments","value":[{"kind":"identifier","text":"SectionIndexList"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}