{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"withArrow"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle"]]},"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@MessageBubbleDisplayStyle@MessageBubbleDisplayStyleWithArrow","roleHeading":"Case","navigatorTitle":[{"text":"MessageBubbleDisplayStyleWithArrow","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"withArrow","kind":"identifier"}],"title":"MessageBubbleDisplayStyle.withArrow"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle\/withArrow"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/messagebubbledisplaystyle\/witharrow"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagebubbledisplaystyle\/witharrow"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleDisplayStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle","url":"\/documentation\/easechatuikit\/messagebubbledisplaystyle","kind":"symbol","role":"symbol","type":"topic","title":"MessageBubbleDisplayStyle","abstract":[],"navigatorTitle":[{"text":"MessageBubbleDisplayStyle","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleDisplayStyle/withArrow":{"navigatorTitle":[{"kind":"identifier","text":"MessageBubbleDisplayStyleWithArrow"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle\/withArrow","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withArrow","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagebubbledisplaystyle\/witharrow","title":"MessageBubbleDisplayStyle.withArrow","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MessageBubbleDisplayStyleWithArrow"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"MessageBubbleDisplayStyleWithArrow"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MessageBubbleDisplayStyleWithArrow"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"MessageBubbleDisplayStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle\/title"},{"value":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle\/fragments"},{"value":"MessageBubbleDisplayStyleWithArrow","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle~1withArrow\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle~1withArrow\/fragments","value":[{"kind":"identifier","text":"MessageBubbleDisplayStyleWithArrow"}],"op":"replace"}]}]}