{"variants":[{"paths":["\/documentation\/easechatuikit\/messagebubbledisplaystyle\/withmulticorner"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagebubbledisplaystyle\/withmulticorner"]}],"metadata":{"symbolKind":"case","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"withMultiCorner","kind":"identifier"}],"role":"symbol","title":"MessageBubbleDisplayStyle.withMultiCorner","externalID":"c:@M@EaseChatUIKit@E@MessageBubbleDisplayStyle@MessageBubbleDisplayStyleWithMultiCorner","navigatorTitle":[{"text":"MessageBubbleDisplayStyleWithMultiCorner","kind":"identifier"}],"roleHeading":"Case"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle\/withMultiCorner","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"withMultiCorner","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleDisplayStyle":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageBubbleDisplayStyle","kind":"identifier"}],"role":"symbol","title":"MessageBubbleDisplayStyle","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/messagebubbledisplaystyle","navigatorTitle":[{"kind":"identifier","text":"MessageBubbleDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleDisplayStyle/withMultiCorner":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"withMultiCorner","kind":"identifier"}],"role":"symbol","title":"MessageBubbleDisplayStyle.withMultiCorner","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/messagebubbledisplaystyle\/withmulticorner","navigatorTitle":[{"kind":"identifier","text":"MessageBubbleDisplayStyleWithMultiCorner"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleDisplayStyle\/withMultiCorner"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"MessageBubbleDisplayStyleWithMultiCorner","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageBubbleDisplayStyleWithMultiCorner"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"MessageBubbleDisplayStyleWithMultiCorner"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"MessageBubbleDisplayStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle\/fragments","value":[{"text":"MessageBubbleDisplayStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle~1withMultiCorner\/title","value":"MessageBubbleDisplayStyleWithMultiCorner"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleDisplayStyle~1withMultiCorner\/fragments","value":[{"text":"MessageBubbleDisplayStyleWithMultiCorner","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}