{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newChat"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"newChat"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactlistheaderstyle\/newchat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactlistheaderstyle\/newchat"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle"]]},"metadata":{"roleHeading":"Case","externalID":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle@ContactListHeaderStyleNewChat","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyleNewChat"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newChat","kind":"identifier"}],"role":"symbol","title":"ContactListHeaderStyle.newChat"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle/newChat":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle\/newChat","type":"topic","navigatorTitle":[{"text":"ContactListHeaderStyleNewChat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactlistheaderstyle\/newchat","role":"symbol","title":"ContactListHeaderStyle.newChat","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"newChat","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle":{"navigatorTitle":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"title":"ContactListHeaderStyle","url":"\/documentation\/easechatuikit\/contactlistheaderstyle","abstract":[{"type":"text","text":"The header display style of the "},{"type":"codeVoice","code":"ContactList"},{"type":"text","text":"."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListHeaderStyle"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"ContactListHeaderStyleNewChat","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderStyleNewChat"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ContactListHeaderStyleNewChat"}]}],"kind":"declarations"}},{"value":"ContactListHeaderStyleNewChat","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1newChat\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle~1newChat\/fragments","value":[{"text":"ContactListHeaderStyleNewChat","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ContactListHeaderStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/fragments","value":[{"text":"ContactListHeaderStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/navigatorTitle","value":[{"text":"ContactListHeaderStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}