{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:)","externalID":"c:@M@EaseChatUIKit@objc(cs)DialogManager(im)showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAlert"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showCancel"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"showConfirm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showTextFiled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"placeHolder","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"confirmClosure","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:"}]},"variants":[{"paths":["\/documentation\/easechatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager\/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showAlert","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showCancel"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"showConfirm","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"text":"showTextFiled","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = false, "},{"text":"placeHolder","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" = \"\", ","kind":"text"},{"kind":"externalParam","text":"confirmClosure"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"name":"title","content":[{"inlineContent":[{"text":"The alert title to display.","type":"text"}],"type":"paragraph"}]},{"name":"content","content":[{"inlineContent":[{"text":"The alert content to display.","type":"text"}],"type":"paragraph"}]},{"name":"showCancel","content":[{"inlineContent":[{"type":"text","text":"Whether to display the "},{"type":"codeVoice","code":"Cancel"},{"type":"text","text":" button."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to display the "},{"code":"Confirm","type":"codeVoice"},{"text":" button.","type":"text"}]}],"name":"showConfirm"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to display the "},{"type":"codeVoice","code":"TextField"},{"type":"text","text":" ."}]}],"name":"showTextField"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"TextField"},{"text":" placeholder.","type":"text"}]}],"name":"placeHolder"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback upon a click of the "},{"code":"Confirm","type":"codeVoice"},{"type":"text","text":" button.When text field was shown callback contain input text."}]}],"name":"confirmClosure"}],"kind":"parameters"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogManager/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:)":{"title":"showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:)","role":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showAlert"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showCancel"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showConfirm"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"showTextFiled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeHolder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"confirmClosure","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager\/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:)","navigatorTitle":[{"text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogManager":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/dialogmanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DialogManager","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DialogManager"}],"abstract":[],"title":"DialogManager","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"showAlertWithTitle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"title"},{"kind":"text","text":" "},{"text":"content:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"content","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"showCancel:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"showCancel"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showConfirm:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"showConfirm"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showTextFiled:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"showTextFiled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"placeHolder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"placeHolder","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confirmClosure:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"confirmClosure","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager~1showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:)\/title","op":"replace","value":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager~1showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager\/title","value":"DialogManager"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"DialogManager"}]}]}]}