{"metadata":{"title":"showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)","externalID":"c:@M@EaseChatUIKit@objc(cs)DialogManager(im)showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showAlert","kind":"identifier"},{"text":"(","kind":"text"},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"showCancel","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"showConfirm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"showTextFiled","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeHolder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"confirmClosure"},{"text":": (","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":", ","kind":"text"},{"text":"cancelClosure","kind":"externalParam"},{"kind":"text","text":": (() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?)"}],"roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager\/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showAlert"},{"kind":"text","text":"("},{"text":"title","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"showCancel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"showConfirm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"showTextFiled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = false, ","kind":"text"},{"kind":"externalParam","text":"placeHolder"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" = \"\", ","kind":"text"},{"kind":"externalParam","text":"confirmClosure"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cancelClosure"},{"text":": (() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"title","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The alert title to display."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The alert content to display.","type":"text"}]}],"name":"content"},{"name":"showCancel","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to display the "},{"code":"Cancel","type":"codeVoice"},{"type":"text","text":" button."}]}]},{"name":"showConfirm","content":[{"type":"paragraph","inlineContent":[{"text":"Whether to display the ","type":"text"},{"code":"Confirm","type":"codeVoice"},{"text":" button.","type":"text"}]}]},{"name":"placeHolder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"TextField"},{"type":"text","text":" placeholder."}]}]},{"name":"confirmClosure","content":[{"inlineContent":[{"text":"Callback upon a click of the ","type":"text"},{"type":"codeVoice","code":"Confirm"},{"text":" button.When text field was shown callback contain input text.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:cancelclosure:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:cancelclosure:)"]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogManager/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/dialogmanager\/showalert(title:content:showcancel:showconfirm:showtextfiled:placeholder:confirmclosure:cancelclosure:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager\/showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)","navigatorTitle":[{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showAlert"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"showCancel","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"text":"showConfirm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"showTextFiled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"placeHolder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"confirmClosure"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cancelClosure"},{"text":": (() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"title":"showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogManager":{"url":"\/documentation\/easechatuikit\/dialogmanager","navigatorTitle":[{"kind":"identifier","text":"DialogManager"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager","kind":"symbol","title":"DialogManager","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DialogManager","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"showAlertWithTitle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"title","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"content"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showCancel:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"showCancel","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"showConfirm:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showConfirm","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showTextFiled:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showTextFiled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeHolder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placeHolder"},{"kind":"text","text":" "},{"text":"confirmClosure:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"confirmClosure","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cancelClosure:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"text":"cancelClosure","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The alert title to display."}]}],"name":"title"},{"content":[{"inlineContent":[{"text":"The alert content to display.","type":"text"}],"type":"paragraph"}],"name":"content"},{"content":[{"inlineContent":[{"text":"Whether to display the ","type":"text"},{"type":"codeVoice","code":"Cancel"},{"text":" button.","type":"text"}],"type":"paragraph"}],"name":"showCancel"},{"content":[{"inlineContent":[{"type":"text","text":"Whether to display the "},{"type":"codeVoice","code":"Confirm"},{"type":"text","text":" button."}],"type":"paragraph"}],"name":"showConfirm"},{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"TextField","type":"codeVoice"},{"text":" placeholder.","type":"text"}]}],"name":"placeHolder"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Callback upon a click of the ","type":"text"},{"code":"Confirm","type":"codeVoice"},{"type":"text","text":" button.When text field was shown callback contain input text."}]}],"name":"confirmClosure"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager~1showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)\/title","value":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showAlertWithTitle:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager~1showAlert(title:content:showCancel:showConfirm:showTextFiled:placeHolder:confirmClosure:cancelClosure:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager\/title","op":"replace","value":"DialogManager"},{"op":"replace","value":[{"kind":"identifier","text":"DialogManager"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager\/navigatorTitle","value":[{"kind":"identifier","text":"DialogManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}