{"sections":[],"abstract":[{"type":"text","text":"Shows message operations."},{"type":"text","text":" "},{"text":"Generally, message operations are shown when you long-press a message.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showMessageActions","kind":"identifier"},{"kind":"text","text":"("},{"text":"actions","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"text":"], ","kind":"text"},{"text":"withHeader","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","isActive":true},{"type":"text","text":" array."}]}],"name":"actions"},{"name":"action","content":[{"inlineContent":[{"text":"Callback upon a click of a message operation.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/dialogmanager\/showmessageactions(actions:withheader:action:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/dialogmanager\/showmessageactions(actions:withheader:action:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","title":"showMessageActions(actions:withHeader:action:)","externalID":"c:@M@EaseChatUIKit@objc(cs)DialogManager(im)showMessageActionsWithActions:withHeader:action:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showMessageActions"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"], "},{"text":"withHeader","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?, ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showMessageActionsWithActions:withHeader:action:"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager\/showMessageActions(actions:withHeader:action:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogManager":{"navigatorTitle":[{"text":"DialogManager","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager","url":"\/documentation\/easechatuikit\/dialogmanager","kind":"symbol","role":"symbol","title":"DialogManager","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DialogManager"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ActionSheetItemProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/easechatuikit\/actionsheetitemprotocol","abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"role":"symbol","title":"ActionSheetItemProtocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DialogManager/showMessageActions(actions:withHeader:action:)":{"navigatorTitle":[{"text":"showMessageActionsWithActions:withHeader:action:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showMessageActions","kind":"identifier"},{"kind":"text","text":"("},{"text":"actions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"ActionSheetItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"], "},{"text":"withHeader","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","url":"\/documentation\/easechatuikit\/dialogmanager\/showmessageactions(actions:withheader:action:)","title":"showMessageActions(actions:withHeader:action:)","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Shows message operations."},{"type":"text","text":" "},{"type":"text","text":"Generally, message operations are shown when you long-press a message."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DialogManager\/showMessageActions(actions:withHeader:action:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"showMessageActionsWithActions:withHeader:action:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showMessageActionsWithActions:withHeader:action:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"showMessageActionsWithActions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<id<ActionSheetItemProtocol>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"actions","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withHeader:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"withHeader","kind":"internalParam"},{"kind":"text","text":" "},{"text":"action:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"id<ActionSheetItemProtocol>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"action","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"value":"DialogManager","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager\/fragments","value":[{"kind":"identifier","text":"DialogManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/title","value":"ActionSheetItemProtocol"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/fragments","op":"replace","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}]},{"value":"showMessageActionsWithActions:withHeader:action:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager~1showMessageActions(actions:withHeader:action:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"showMessageActionsWithActions:withHeader:action:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DialogManager~1showMessageActions(actions:withHeader:action:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}