{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightItems","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"rightItems","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent@EaseChatNavigationBarClickEventRightItems","title":"EaseChatNavigationBarClickEvent.rightItems","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightItems"}],"navigatorTitle":[{"text":"EaseChatNavigationBarClickEventRightItems","kind":"identifier"}],"symbolKind":"case","roleHeading":"Case"},"variants":[{"paths":["\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/rightitems"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/rightitems"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent":{"abstract":[],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent","navigatorTitle":[{"text":"EaseChatNavigationBarClickEvent","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}],"role":"symbol","title":"EaseChatNavigationBarClickEvent","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent/rightItems":{"role":"symbol","url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent\/rightitems","abstract":[],"navigatorTitle":[{"text":"EaseChatNavigationBarClickEventRightItems","kind":"identifier"}],"title":"EaseChatNavigationBarClickEvent.rightItems","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightItems","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent\/rightItems","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"EaseChatNavigationBarClickEventRightItems"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventRightItems"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventRightItems"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/title","value":"EaseChatNavigationBarClickEvent"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}],"op":"replace"},{"op":"replace","value":"EaseChatNavigationBarClickEventRightItems","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1rightItems\/title"},{"value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEventRightItems"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent~1rightItems\/fragments"}]}]}