{"variants":[{"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/agorachatcontactmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/agorachatcontactmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/AgoraChatContactManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidApprove(byUser:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidDecline(byUser:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidReceive(fromUser:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidAdd(byUser:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidRemove(byUser:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"AgoraChatContactManagerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/friendshipDidRemove(byUser:)":{"role":"symbol","title":"friendshipDidRemove(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidRemove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidRemove(byUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendshipDidRemoveByUser:"}],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/friendshipdidremove(byuser:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/friendRequestDidReceive(fromUser:message:)":{"role":"symbol","title":"friendRequestDidReceive(fromUser:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidReceive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidReceive(fromUser:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendRequestDidReceiveFromUser:message:"}],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/friendrequestdidreceive(fromuser:message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/friendRequestDidDecline(byUser:)":{"role":"symbol","title":"friendRequestDidDecline(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidDecline"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidDecline(byUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendRequestDidDeclineByUser:"}],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/friendrequestdiddecline(byuser:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/friendshipDidAdd(byUser:)":{"role":"symbol","title":"friendshipDidAdd(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendshipDidAdd"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidAdd(byUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendshipDidAddByUser:"}],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/friendshipdidadd(byuser:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement":{"role":"symbol","title":"ContactServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactServiceImplement"}],"url":"\/documentation\/easechatuikit\/contactserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/friendRequestDidApprove(byUser:)":{"role":"symbol","title":"friendRequestDidApprove(byUser:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"friendRequestDidApprove"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidApprove(byUser:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendRequestDidApproveByUser:"}],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/friendrequestdidapprove(byuser:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidApprove(byUser:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidDecline(byUser:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidReceive(fromUser:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidAdd(byUser:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidRemove(byUser:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendshipDidRemove(byUser:)\/title","value":"friendshipDidRemoveByUser:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendshipDidRemove(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidRemoveByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidReceive(fromUser:message:)\/title","value":"friendRequestDidReceiveFromUser:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidReceive(fromUser:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidReceiveFromUser:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidDecline(byUser:)\/title","value":"friendRequestDidDeclineByUser:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidDecline(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidDeclineByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendshipDidAdd(byUser:)\/title","value":"friendshipDidAddByUser:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendshipDidAdd(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendshipDidAddByUser:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/title","value":"ContactServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/fragments","value":[{"kind":"identifier","text":"ContactServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidApprove(byUser:)\/title","value":"friendRequestDidApproveByUser:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidApprove(byUser:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidApproveByUser:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}