{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidAdd(byUser:)"},"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactServiceImplement(im)friendshipDidAddByUser:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"friendshipDidAdd","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"byUser"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"title":"friendshipDidAdd(byUser:)","extendedModule":"EaseChatUIKit","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"friendshipDidAddByUser:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friendshipDidAdd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byUser","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aUsername"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/friendshipdidadd(byuser:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/friendshipdidadd(byuser:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/EMContactManagerDelegate-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"EMContactManagerDelegate.friendshipDidAdd(byUser:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/EMContactManagerDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/EMContactManagerDelegate-Implementations","kind":"article","title":"EMContactManagerDelegate Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/emcontactmanagerdelegate-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/friendshipDidAdd(byUser:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendshipDidAdd(byUser:)","kind":"symbol","title":"friendshipDidAdd(byUser:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friendshipDidAdd","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byUser","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/friendshipdidadd(byuser:)","navigatorTitle":[{"text":"friendshipDidAddByUser:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","abstract":[],"url":"\/documentation\/easechatuikit\/contactserviceimplement","navigatorTitle":[{"text":"ContactServiceImplement","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactServiceImplement"}],"kind":"symbol","type":"topic","title":"ContactServiceImplement"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"friendshipDidAddByUser:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"friendshipDidAddByUser:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"friendshipDidAddByUser:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"aUsername","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendshipDidAdd(byUser:)\/title","value":"friendshipDidAddByUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendshipDidAdd(byUser:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"friendshipDidAddByUser:","kind":"identifier"}]},{"value":"ContactServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/fragments","value":[{"text":"ContactServiceImplement","kind":"identifier"}],"op":"replace"}]}]}