{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/friendrequestdiddecline(byuser:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/friendrequestdiddecline(byuser:)"]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMContactManagerDelegate.friendRequestDidDecline(byUser:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendRequestDidDecline"},{"kind":"text","text":"("},{"text":"byUser","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aUsername"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidDecline(byUser:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendRequestDidDecline"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"byUser"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidDeclineByUser:"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactServiceImplement(im)friendRequestDidDeclineByUser:","roleHeading":"Instance Method","title":"friendRequestDidDecline(byUser:)"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/EMContactManagerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactServiceImplement"}],"abstract":[],"url":"\/documentation\/easechatuikit\/contactserviceimplement","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactServiceImplement"}],"title":"ContactServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/friendRequestDidDecline(byUser:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/friendrequestdiddecline(byuser:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"friendRequestDidDecline","kind":"identifier"},{"text":"(","kind":"text"},{"text":"byUser","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/friendRequestDidDecline(byUser:)","kind":"symbol","type":"topic","title":"friendRequestDidDecline(byUser:)","navigatorTitle":[{"text":"friendRequestDidDeclineByUser:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/EMContactManagerDelegate-Implementations":{"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/contactserviceimplement\/emcontactmanagerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/EMContactManagerDelegate-Implementations","kind":"article","role":"collectionGroup","title":"EMContactManagerDelegate Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"friendRequestDidDeclineByUser:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"friendRequestDidDeclineByUser:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"friendRequestDidDeclineByUser:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"aUsername","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/title","value":"ContactServiceImplement"},{"value":[{"kind":"identifier","text":"ContactServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidDecline(byUser:)\/title","value":"friendRequestDidDeclineByUser:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"friendRequestDidDeclineByUser:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1friendRequestDidDecline(byUser:)\/fragments"}]}]}