{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerEmergencyListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","text":"ContactEmergencyListener"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener"}]}],"name":"listener"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/registeremergencylistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactserviceimplement\/registeremergencylistener(listener:)"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/registerEmergencyListener(listener:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactServiceImplement(im)registerEmergencyListenerWithListener:","title":"registerEmergencyListener(listener:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"registerEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","text":"ContactEmergencyListener"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit","roleHeading":"Instance Method","role":"symbol","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"Register emergency listener"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/ContactServiceProtocol-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/ContactServiceProtocol-Implementations":{"title":"ContactServiceProtocol Implementations","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/ContactServiceProtocol-Implementations","role":"collectionGroup","url":"\/documentation\/easechatuikit\/contactserviceimplement\/contactserviceprotocol-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement":{"title":"ContactServiceImplement","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactServiceImplement"}],"url":"\/documentation\/easechatuikit\/contactserviceimplement","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement","navigatorTitle":[{"kind":"identifier","text":"ContactServiceImplement"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyListener":{"navigatorTitle":[{"kind":"identifier","text":"ContactEmergencyListener"}],"url":"\/documentation\/easechatuikit\/contactemergencylistener","title":"ContactEmergencyListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactEmergencyListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener","kind":"symbol","type":"topic","abstract":[],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactServiceImplement/registerEmergencyListener(listener:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactServiceImplement\/registerEmergencyListener(listener:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"registerEmergencyListenerWithListener:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerEmergencyListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","kind":"typeIdentifier","text":"ContactEmergencyListener"},{"text":")","kind":"text"}],"abstract":[{"text":"Register emergency listener","type":"text"}],"title":"registerEmergencyListener(listener:)","url":"\/documentation\/easechatuikit\/contactserviceimplement\/registeremergencylistener(listener:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"registerEmergencyListenerWithListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerEmergencyListenerWithListener:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"registerEmergencyListenerWithListener:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","kind":"typeIdentifier","text":"id<ContactEmergencyListener>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/title","value":"ContactServiceImplement","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/fragments","op":"replace","value":[{"text":"ContactServiceImplement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement\/navigatorTitle","value":[{"kind":"identifier","text":"ContactServiceImplement"}]},{"value":"ContactEmergencyListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/fragments","value":[{"text":"ContactEmergencyListener","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/navigatorTitle","op":"replace","value":[{"text":"ContactEmergencyListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1registerEmergencyListener(listener:)\/title","value":"registerEmergencyListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactServiceImplement~1registerEmergencyListener(listener:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}]}]}]}