{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"unbindNotificationDeviceToken","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","text":"ChatError"},{"text":"?) -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/logout(unbindNotificationDeviceToken:completion:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient"]]},"abstract":[{"text":"Logout user","type":"text"}],"metadata":{"title":"logout(unbindNotificationDeviceToken:completion:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"logoutWithUnbindNotificationDeviceToken:completion:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"logout","kind":"identifier"},{"kind":"text","text":"("},{"text":"unbindNotificationDeviceToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient(im)logoutWithUnbindNotificationDeviceToken:completion:","symbolKind":"method"},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/logout(unbindnotificationdevicetoken:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/logout(unbindnotificationdevicetoken:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient/logout(unbindNotificationDeviceToken:completion:)":{"kind":"symbol","abstract":[{"text":"Logout user","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logout","kind":"identifier"},{"text":"(","kind":"text"},{"text":"unbindNotificationDeviceToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"logout(unbindNotificationDeviceToken:completion:)","url":"\/documentation\/easechatuikit\/easechatuikitclient\/logout(unbindnotificationdevicetoken:completion:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"logoutWithUnbindNotificationDeviceToken:completion:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/logout(unbindNotificationDeviceToken:completion:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"title":"ChatError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chaterror","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatUIKitClient"}],"url":"\/documentation\/easechatuikit\/easechatuikitclient","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient","type":"topic","navigatorTitle":[{"text":"EaseChatUIKitClient","kind":"identifier"}],"title":"EaseChatUIKitClient"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"logoutWithUnbindNotificationDeviceToken:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"logoutWithUnbindNotificationDeviceToken:completion:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"logoutWithUnbindNotificationDeviceToken:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"unbindNotificationDeviceToken"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"EMError","preciseIdentifier":"c:objc(cs)EMError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"logoutWithUnbindNotificationDeviceToken:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1logout(unbindNotificationDeviceToken:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1logout(unbindNotificationDeviceToken:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"logoutWithUnbindNotificationDeviceToken:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/title","value":"EaseChatUIKitClient","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/fragments","value":[{"text":"EaseChatUIKitClient","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}