{"variants":[{"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/registeruserstatelistener(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/registeruserstatelistener(_:)"]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/registerUserStateListener(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerUserStateListener","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient(im)registerUserStateListener:","title":"registerUserStateListener(_:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"registerUserStateListener:"}]},"abstract":[{"text":"Register a user to listen for callbacks that monitor user status changes.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerUserStateListener"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"listener","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","text":"UserStateChangedListener"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","isActive":true}]}],"name":"listener"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient":{"abstract":[],"url":"\/documentation\/easechatuikit\/easechatuikitclient","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient","navigatorTitle":[{"text":"EaseChatUIKitClient","kind":"identifier"}],"role":"symbol","title":"EaseChatUIKitClient","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EaseChatUIKitClient","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener":{"kind":"symbol","navigatorTitle":[{"text":"UserStateChangedListener","kind":"identifier"}],"title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"}],"url":"\/documentation\/easechatuikit\/userstatechangedlistener","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient/registerUserStateListener(_:)":{"title":"registerUserStateListener(_:)","kind":"symbol","url":"\/documentation\/easechatuikit\/easechatuikitclient\/registeruserstatelistener(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/registerUserStateListener(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerUserStateListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"registerUserStateListener:"}],"role":"symbol","abstract":[{"type":"text","text":"Register a user to listen for callbacks that monitor user status changes."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"registerUserStateListener:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"registerUserStateListener:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"registerUserStateListener:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<UserStateChangedListener>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":") "},{"text":"listener","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/title","value":"EaseChatUIKitClient","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/fragments","op":"replace","value":[{"text":"EaseChatUIKitClient","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/title","value":"UserStateChangedListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/fragments","value":[{"kind":"identifier","text":"UserStateChangedListener"}],"op":"replace"},{"value":"registerUserStateListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1registerUserStateListener(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1registerUserStateListener(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerUserStateListener:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}