{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient"]]},"metadata":{"symbolKind":"property","title":"shared","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"text":"EaseChatUIKitClient","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient"}],"navigatorTitle":[{"text":"shared","kind":"identifier"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Type Property","externalID":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient(cpy)shared"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/shared"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient","kind":"typeIdentifier","text":"EaseChatUIKitClient","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/shared","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient/shared":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient","text":"EaseChatUIKitClient"}],"title":"shared","url":"\/documentation\/easechatuikit\/easechatuikitclient\/shared","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/shared","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatUIKitClient"}],"url":"\/documentation\/easechatuikit\/easechatuikitclient","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient","type":"topic","navigatorTitle":[{"text":"EaseChatUIKitClient","kind":"identifier"}],"title":"EaseChatUIKitClient"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"shared","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient","kind":"typeIdentifier","text":"EaseChatUIKitClient","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient"},{"text":" * ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1shared\/title","value":"shared"},{"value":[{"text":"shared","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1shared\/fragments","op":"replace"},{"value":"EaseChatUIKitClient","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/fragments","op":"replace","value":[{"text":"EaseChatUIKitClient","kind":"identifier"}]}]}]}