{"metadata":{"role":"symbol","title":"unregisterUserStateListener(_:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"unregisterUserStateListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"unregisterUserStateListener:","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitClient(im)unregisterUserStateListener:"},"abstract":[{"text":"Remove monitoring of user status changes.","type":"text"}],"variants":[{"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/unregisteruserstatelistener(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/easechatuikitclient\/unregisteruserstatelistener(_:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/unregisterUserStateListener(_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unregisterUserStateListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"listener","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener","kind":"typeIdentifier","text":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener"}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient":{"abstract":[],"url":"\/documentation\/easechatuikit\/easechatuikitclient","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient","navigatorTitle":[{"text":"EaseChatUIKitClient","kind":"identifier"}],"role":"symbol","title":"EaseChatUIKitClient","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EaseChatUIKitClient","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UserStateChangedListener":{"kind":"symbol","navigatorTitle":[{"text":"UserStateChangedListener","kind":"identifier"}],"title":"UserStateChangedListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UserStateChangedListener","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UserStateChangedListener"}],"url":"\/documentation\/easechatuikit\/userstatechangedlistener","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitClient/unregisterUserStateListener(_:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitClient\/unregisterUserStateListener(_:)","title":"unregisterUserStateListener(_:)","type":"topic","url":"\/documentation\/easechatuikit\/easechatuikitclient\/unregisteruserstatelistener(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterUserStateListener"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UserStateChangedListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)UserStateChangedListener"},{"text":")","kind":"text"}],"abstract":[{"text":"Remove monitoring of user status changes.","type":"text"}],"navigatorTitle":[{"text":"unregisterUserStateListener:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"unregisterUserStateListener:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterUserStateListener:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"unregisterUserStateListener:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)UserStateChangedListener","text":"id<UserStateChangedListener>"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/title","op":"replace","value":"EaseChatUIKitClient"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitClient"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/title","op":"replace","value":"UserStateChangedListener"},{"op":"replace","value":[{"text":"UserStateChangedListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UserStateChangedListener\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1unregisterUserStateListener(_:)\/title","value":"unregisterUserStateListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitClient~1unregisterUserStateListener(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"unregisterUserStateListener:"}],"op":"replace"}]}]}