{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell"]]},"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageCell(im)createBubbleMultiCorners","role":"symbol","title":"createBubbleMultiCorners()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createBubbleMultiCorners","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageBubbleMultiCorner","kind":"typeIdentifier","text":"MessageBubbleMultiCorner"}],"navigatorTitle":[{"kind":"identifier","text":"createBubbleMultiCorners"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createBubbleMultiCorners","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"MessageBubbleMultiCorner","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleMultiCorner","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageBubbleMultiCorner","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell\/createBubbleMultiCorners()"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecell\/createbubblemulticorners()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagecell\/createbubblemulticorners()"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagecell","role":"symbol","title":"MessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleMultiCorner":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/messagebubblemulticorner","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleMultiCorner","navigatorTitle":[{"kind":"identifier","text":"MessageBubbleMultiCorner"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageBubbleMultiCorner","kind":"identifier"}],"title":"MessageBubbleMultiCorner","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell/createBubbleMultiCorners()":{"role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/messagecell\/createbubblemulticorners()","abstract":[],"type":"topic","title":"createBubbleMultiCorners()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell\/createBubbleMultiCorners()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createBubbleMultiCorners","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageBubbleMultiCorner","text":"MessageBubbleMultiCorner","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createBubbleMultiCorners","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"createBubbleMultiCorners","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"createBubbleMultiCorners","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"MessageBubbleMultiCorner","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageBubbleMultiCorner","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleMultiCorner"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBubbleMultiCorners"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","op":"replace","value":"MessageCell"},{"value":[{"kind":"identifier","text":"MessageCell"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments"},{"op":"replace","value":[{"text":"MessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/navigatorTitle"},{"value":"MessageBubbleMultiCorner","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleMultiCorner\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleMultiCorner\/fragments","value":[{"kind":"identifier","text":"MessageBubbleMultiCorner"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleMultiCorner\/navigatorTitle","op":"replace","value":[{"text":"MessageBubbleMultiCorner","kind":"identifier"}]},{"value":"createBubbleMultiCorners","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell~1createBubbleMultiCorners()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell~1createBubbleMultiCorners()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createBubbleMultiCorners"}]}]}]}