{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecell\/refresh(entity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagecell\/refresh(entity:)"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Refresh cell with "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","type":"reference","isActive":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell"]]},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageCell(im)refreshWithEntity:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"refreshWithEntity:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"title":"refresh(entity:)"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell\/refresh(entity:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(refreshWithEntity:) "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"typeIdentifier","text":"MessageEntity"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"entity","content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messageentity","title":"MessageEntity","navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell/refresh(entity:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refresh","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"role":"symbol","url":"\/documentation\/easechatuikit\/messagecell\/refresh(entity:)","abstract":[{"type":"text","text":"Refresh cell with "},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity"}],"navigatorTitle":[{"kind":"identifier","text":"refreshWithEntity:"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell\/refresh(entity:)","kind":"symbol","title":"refresh(entity:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageCell","kind":"identifier"}],"kind":"symbol","title":"MessageCell","url":"\/documentation\/easechatuikit\/messagecell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshWithEntity:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshWithEntity:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"refreshWithEntity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity"},{"kind":"text","text":" *) "},{"text":"entity","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"value":"MessageEntity","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments","value":[{"text":"MessageEntity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell~1refresh(entity:)\/title","op":"replace","value":"refreshWithEntity:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell~1refresh(entity:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"refreshWithEntity:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","value":"MessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","value":[{"kind":"identifier","text":"MessageCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}