{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(initWithConversationId:chatType:) "},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"chatType"},{"kind":"text","text":": "},{"text":"ChatType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType","kind":"typeIdentifier"},{"text":" = .chat)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"conversationId: The ID of the conversation."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"chatType: The type of chat. Default value is "},{"type":"codeVoice","code":".chat"},{"text":".","type":"text"}]}]}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"This initializer sets the "},{"type":"codeVoice","code":"profile"},{"type":"text","text":" property based on the conversation ID. If the conversation ID is found in the conversations cache, the profile is set to the corresponding information. Otherwise, the profile ID is set to the conversation ID."}]},{"type":"paragraph","inlineContent":[{"text":"The ","type":"text"},{"code":"chatType","type":"codeVoice"},{"type":"text","text":" parameter determines the type of chat, which can be "},{"type":"codeVoice","code":".group"},{"text":" or ","type":"text"},{"type":"codeVoice","code":".chat"},{"text":". If the chat type is not one of these options, it defaults to ","type":"text"},{"type":"codeVoice","code":".chatroom"},{"type":"text","text":"."}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/searchresultmessagescontroller\/init(conversationid:chattype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchresultmessagescontroller\/init(conversationid:chattype:)"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","title":"init(conversationId:chatType:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"chatType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType","text":"ChatType"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)SearchResultMessagesController(im)initWithConversationId:chatType:","navigatorTitle":[{"text":"initWithConversationId:chatType:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController"]]},"abstract":[{"type":"text","text":"Initializes a new instance of the "},{"code":"MessageListController","type":"codeVoice"},{"text":" class with the specified conversation ID and chat type.","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatType":{"title":"ChatType","type":"topic","abstract":[{"text":"An enumeration representing different types of chats.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ChatType","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chattype","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatType","navigatorTitle":[{"text":"ChatType","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/init(conversationId:chatType:)":{"navigatorTitle":[{"text":"initWithConversationId:chatType:","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/init(conversationid:chattype:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"chatType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType","text":"ChatType","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(conversationId:chatType:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/init(conversationId:chatType:)","abstract":[{"type":"text","text":"Initializes a new instance of the "},{"type":"codeVoice","code":"MessageListController"},{"type":"text","text":" class with the specified conversation ID and chat type."}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController":{"title":"SearchResultMessagesController","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchResultMessagesController"}],"navigatorTitle":[{"kind":"identifier","text":"SearchResultMessagesController"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConversationId:chatType:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConversationId:chatType:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithConversationId:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatType:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"chatType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"ChatType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatType\/title"},{"value":[{"kind":"identifier","text":"ChatType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(conversationId:chatType:)\/title","op":"replace","value":"initWithConversationId:chatType:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1init(conversationId:chatType:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConversationId:chatType:","kind":"identifier"}],"op":"replace"},{"value":"SearchResultMessagesController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/title"},{"value":[{"text":"SearchResultMessagesController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/fragments"}]}]}