{"variants":[{"paths":["\/documentation\/easechatuikit\/searchresultmessagescontroller\/viewdetail()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/searchresultmessagescontroller\/viewdetail()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDetail()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController"]]},"metadata":{"role":"symbol","title":"viewDetail()","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)SearchResultMessagesController(im)viewDetail","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDetail","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDetail"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"This method is called to view the detail of a chat message."},{"type":"text","text":" "},{"type":"text","text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly."},{"text":" ","type":"text"},{"text":"If the previous view controller in the navigation stack is either ","type":"text"},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"text":", it pops the current view controller.","type":"text"},{"type":"text","text":" "},{"text":"If the chat type is individual, it presents the ","type":"text"},{"type":"codeVoice","code":"ContactInfoController"},{"text":" with the given profile.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is group, it presents the ","type":"text"},{"code":"GroupInfoController","type":"codeVoice"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"},{"text":" ","type":"text"},{"text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either ","type":"text"},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"code":"ContactInfoViewController","type":"codeVoice"},{"text":" and dismisses it.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is individual, it presents the "},{"code":"ContactInfoController","type":"codeVoice"},{"text":" with the given profile.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"code":"GroupInfoController","type":"codeVoice"},{"type":"text","text":" with the given group ID and updates the navigation title with the group name."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDetail","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchResultMessagesController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController","abstract":[],"title":"SearchResultMessagesController","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller","navigatorTitle":[{"text":"SearchResultMessagesController","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchResultMessagesController/viewDetail()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDetail","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"viewDetail","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchResultMessagesController\/viewDetail()","url":"\/documentation\/easechatuikit\/searchresultmessagescontroller\/viewdetail()","abstract":[{"type":"text","text":"This method is called to view the detail of a chat message."},{"type":"text","text":" "},{"type":"text","text":"It determines the type of chat (individual or group) and presents the appropriate view controller accordingly."},{"type":"text","text":" "},{"text":"If the previous view controller in the navigation stack is either ","type":"text"},{"code":"GroupInfoViewController","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"text":", it pops the current view controller.","type":"text"},{"text":" ","type":"text"},{"text":"If the chat type is individual, it presents the ","type":"text"},{"type":"codeVoice","code":"ContactInfoController"},{"type":"text","text":" with the given profile."},{"type":"text","text":" "},{"type":"text","text":"If the chat type is group, it presents the "},{"code":"GroupInfoController","type":"codeVoice"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"},{"type":"text","text":" "},{"text":"If there is no previous view controller in the navigation stack, it checks if the presenting view controller is either ","type":"text"},{"type":"codeVoice","code":"GroupInfoViewController"},{"type":"text","text":" or "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" and dismisses it."},{"text":" ","type":"text"},{"type":"text","text":"If the chat type is individual, it presents the "},{"type":"codeVoice","code":"ContactInfoController"},{"text":" with the given profile.","type":"text"},{"type":"text","text":" "},{"text":"If the chat type is group, it presents the ","type":"text"},{"code":"GroupInfoController","type":"codeVoice"},{"text":" with the given group ID and updates the navigation title with the group name.","type":"text"}],"title":"viewDetail()","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"viewDetail","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDetail","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"viewDetail","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/title","value":"SearchResultMessagesController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/fragments","op":"replace","value":[{"text":"SearchResultMessagesController","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SearchResultMessagesController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewDetail()\/title","value":"viewDetail"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDetail","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchResultMessagesController~1viewDetail()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}