{"abstract":[{"type":"text","text":"When the cell clicked,callback."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem"]]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactlistheaderitem\/actionclosure"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactlistheaderitem\/actionclosure"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactListItemActionClosure","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListItemActionClosure","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"actionClosure"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"actionClosure","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContactListItemActionClosure","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactListHeaderItem(py)actionClosure","title":"actionClosure","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem\/actionClosure","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItem":{"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem","navigatorTitle":[{"text":"ContactListHeaderItem","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactlistheaderitem","title":"ContactListHeaderItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContactListHeaderItem","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListItemActionClosure":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListItemActionClosure","url":"\/documentation\/easechatuikit\/contactlistitemactionclosure","title":"ContactListItemActionClosure","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ContactListItemActionClosure","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ContactListItemActionClosure","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItem/actionClosure":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"actionClosure","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea","text":"ContactListItemActionClosure"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"When the cell clicked,callback."}],"title":"actionClosure","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"actionClosure"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactlistheaderitem\/actionclosure","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem\/actionClosure"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"actionClosure","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"actionClosure"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"kind":"text","text":")("},{"kind":"typeIdentifier","text":"id<ContactListHeaderItemProtocol>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem\/title","value":"ContactListHeaderItem"},{"value":[{"text":"ContactListHeaderItem","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem\/navigatorTitle","value":[{"kind":"identifier","text":"ContactListHeaderItem"}]},{"value":"actionClosure","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem~1actionClosure\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem~1actionClosure\/fragments","value":[{"text":"actionClosure","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}