{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"featureIdentify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListItemActionClosure","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea","text":"ContactListItemActionClosure"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"featureName","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The feature name of the contact header item"}]}]},{"name":"featureIcon","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The icon of the contact header item"}]}]},{"name":"action","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The callback on item clicked."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactlistheaderitem\/init(featureidentify:featurename:featureicon:action:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactlistheaderitem\/init(featureidentify:featurename:featureicon:action:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem\/init(featureIdentify:featureName:featureIcon:action:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"type":"codeVoice","code":"ContactListItem"},{"type":"text","text":" object ."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"featureIdentify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListItemActionClosure","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea"},{"kind":"text","text":")"}],"title":"init(featureIdentify:featureName:featureIcon:action:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactListHeaderItem(im)initWithFeatureIdentify:featureName:featureIcon:action:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFeatureIdentify:featureName:featureIcon:action:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItem/init(featureIdentify:featureName:featureIcon:action:)":{"role":"symbol","title":"init(featureIdentify:featureName:featureIcon:action:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"featureIdentify"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"featureIcon"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListItemActionClosure","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"A convenience initializer for creating an "},{"type":"codeVoice","code":"ContactListItem"},{"type":"text","text":" object ."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem\/init(featureIdentify:featureName:featureIcon:action:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFeatureIdentify:featureName:featureIcon:action:"}],"url":"\/documentation\/easechatuikit\/contactlistheaderitem\/init(featureidentify:featurename:featureicon:action:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListItemActionClosure":{"role":"symbol","title":"ContactListItemActionClosure","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListItemActionClosure"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListItemActionClosure","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactListItemActionClosure"}],"url":"\/documentation\/easechatuikit\/contactlistitemactionclosure"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItem":{"role":"symbol","title":"ContactListHeaderItem","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListHeaderItem"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItem","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderItem"}],"url":"\/documentation\/easechatuikit\/contactlistheaderitem"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFeatureIdentify:featureName:featureIcon:action:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFeatureIdentify:featureName:featureIcon:action:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithFeatureIdentify:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"featureIdentify"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"featureName"},{"kind":"text","text":" "},{"kind":"identifier","text":"featureIcon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"featureIcon"},{"kind":"text","text":" "},{"kind":"identifier","text":"action:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(id<ContactListHeaderItemProtocol>)","preciseIdentifier":"c:BFv(#*Qo@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"action"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem~1init(featureIdentify:featureName:featureIcon:action:)\/title","value":"initWithFeatureIdentify:featureName:featureIcon:action:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem~1init(featureIdentify:featureName:featureIcon:action:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFeatureIdentify:featureName:featureIcon:action:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem\/title","value":"ContactListHeaderItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItem\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderItem"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}