{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageMultiSelectedBottomBar(im)initWithFrame:","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"roleHeading":"Initializer","title":"init(frame:)"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar\/init(frame:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/messagemultiselectedbottombar\/init(frame:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagemultiselectedbottombar\/init(frame:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBar/init(frame:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombar\/init(frame:)","type":"topic","kind":"symbol","role":"symbol","title":"init(frame:)","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar\/init(frame:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBar":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageMultiSelectedBottomBar","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MessageMultiSelectedBottomBar","role":"symbol","url":"\/documentation\/easechatuikit\/messagemultiselectedbottombar","navigatorTitle":[{"kind":"identifier","text":"MessageMultiSelectedBottomBar"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithFrame:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar~1init(frame:)\/title","value":"initWithFrame:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar~1init(frame:)\/fragments","op":"replace"},{"value":"MessageMultiSelectedBottomBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar\/title"},{"value":[{"text":"MessageMultiSelectedBottomBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar\/navigatorTitle","value":[{"kind":"identifier","text":"MessageMultiSelectedBottomBar"}]}]}]}