{"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operationClosure"},{"text":": ((","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageMultiSelectedBottomBar(py)operationClosure","navigatorTitle":[{"kind":"identifier","text":"operationClosure"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"operationClosure","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","title":"operationClosure"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagemultiselectedbottombar\/operationclosure"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagemultiselectedbottombar\/operationclosure"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar"]]},"abstract":[{"type":"text","text":"Action button click callback"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar\/operationClosure","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBar":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageMultiSelectedBottomBar"}],"kind":"symbol","title":"MessageMultiSelectedBottomBar","role":"symbol","type":"topic","navigatorTitle":[{"text":"MessageMultiSelectedBottomBar","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar","url":"\/documentation\/easechatuikit\/messagemultiselectedbottombar","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBarOperation":{"abstract":[],"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombaroperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"navigatorTitle":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"MessageMultiSelectedBottomBarOperation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBar/operationClosure":{"navigatorTitle":[{"text":"operationClosure","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operationClosure"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombar\/operationclosure","type":"topic","title":"operationClosure","abstract":[{"type":"text","text":"Action button click callback"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBar\/operationClosure","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"operationClosure"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"operationClosure"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"operationClosure"},{"kind":"text","text":")("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":");","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar\/title","value":"MessageMultiSelectedBottomBar"},{"value":[{"text":"MessageMultiSelectedBottomBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/title","op":"replace","value":"MessageMultiSelectedBottomBarOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/fragments","value":[{"kind":"identifier","text":"MessageMultiSelectedBottomBarOperation"}]},{"op":"replace","value":"operationClosure","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar~1operationClosure\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBar~1operationClosure\/fragments","value":[{"kind":"identifier","text":"operationClosure"}]}]}]}