{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantCell"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantCell\/init(displayStyle:identifier:)"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithDisplayStyle:identifier:"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"displayStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactDisplayStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactDisplayStyle"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"title":"init(displayStyle:identifier:)","roleHeading":"Initializer","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantCell(im)initWithDisplayStyle:identifier:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"displayStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactDisplayStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactDisplayStyle"},{"text":", ","kind":"text"},{"text":"identifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupparticipantcell\/init(displaystyle:identifier:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupparticipantcell\/init(displaystyle:identifier:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantCell":{"type":"topic","navigatorTitle":[{"text":"GroupParticipantCell","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantCell"}],"title":"GroupParticipantCell","kind":"symbol","url":"\/documentation\/easechatuikit\/groupparticipantcell","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactDisplayStyle":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactDisplayStyle"}],"url":"\/documentation\/easechatuikit\/contactdisplaystyle","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyle"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle","abstract":[],"title":"ContactDisplayStyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantCell/init(displayStyle:identifier:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDisplayStyle:identifier:"}],"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"displayStyle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ContactDisplayStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactDisplayStyle","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(displayStyle:identifier:)","kind":"symbol","url":"\/documentation\/easechatuikit\/groupparticipantcell\/init(displaystyle:identifier:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantCell\/init(displayStyle:identifier:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithDisplayStyle:identifier:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDisplayStyle:identifier:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDisplayStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ContactDisplayStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactDisplayStyle"},{"kind":"text","text":") "},{"text":"displayStyle","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"identifier","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantCell\/title","value":"GroupParticipantCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantCell\/fragments","value":[{"kind":"identifier","text":"GroupParticipantCell"}],"op":"replace"},{"value":"ContactDisplayStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/title"},{"value":[{"text":"ContactDisplayStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/fragments","op":"replace"},{"value":"initWithDisplayStyle:identifier:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantCell~1init(displayStyle:identifier:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantCell~1init(displayStyle:identifier:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDisplayStyle:identifier:"}],"op":"replace"}]}]}