{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageTitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"childControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"constraintsSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" = .zero)"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"pageTitles","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of strings representing the titles of each page."}]}]},{"name":"childControllers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of UIViewControllers representing the child view controllers for each page."}]}]},{"name":"constraintsSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An optional CGSize representing the size of the constraints for the presented view component."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A PageContainersDialogController instance."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/pagecontainersdialogcontroller\/init(pagetitles:childcontrollers:constraintssize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/pagecontainersdialogcontroller\/init(pagetitles:childcontrollers:constraintssize:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController\/init(pageTitles:childControllers:constraintsSize:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Initializes a PageContainersDialogController with the given page titles, child view controllers, and optional constraints size."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageTitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"childControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"constraintsSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"title":"init(pageTitles:childControllers:constraintsSize:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@EaseChatUIKit@objc(cs)PageContainersDialogController(im)initWithPageTitles:childControllers:constraintsSize:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPageTitles:childControllers:constraintsSize:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainersDialogController/init(pageTitles:childControllers:constraintsSize:)":{"role":"symbol","title":"init(pageTitles:childControllers:constraintsSize:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pageTitles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"childControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"constraintsSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a PageContainersDialogController with the given page titles, child view controllers, and optional constraints size."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController\/init(pageTitles:childControllers:constraintsSize:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPageTitles:childControllers:constraintsSize:"}],"url":"\/documentation\/easechatuikit\/pagecontainersdialogcontroller\/init(pagetitles:childcontrollers:constraintssize:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainersDialogController":{"role":"symbol","title":"PageContainersDialogController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainersDialogController"}],"abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainersDialogController"}],"url":"\/documentation\/easechatuikit\/pagecontainersdialogcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithPageTitles:childControllers:constraintsSize:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageTitles:childControllers:constraintsSize:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPageTitles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageTitles"},{"kind":"text","text":" "},{"kind":"identifier","text":"childControllers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<UIViewController *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"childControllers"},{"kind":"text","text":" "},{"kind":"identifier","text":"constraintsSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"constraintsSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController~1init(pageTitles:childControllers:constraintsSize:)\/title","value":"initWithPageTitles:childControllers:constraintsSize:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController~1init(pageTitles:childControllers:constraintsSize:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPageTitles:childControllers:constraintsSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/title","value":"PageContainersDialogController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/fragments","value":[{"kind":"identifier","text":"PageContainersDialogController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}