{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pagecontainersdialogcontroller\/willremoveclosure"]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willRemoveClosure"},{"text":": (() -> ())?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController\/willRemoveClosure"},"metadata":{"title":"willRemoveClosure","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willRemoveClosure"},{"text":": (() -> ())?","kind":"text"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit30PageContainersDialogControllerC17willRemoveClosureyycSgvp"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainersDialogController/willRemoveClosure":{"role":"symbol","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController\/willRemoveClosure","title":"willRemoveClosure","url":"\/documentation\/easechatuikit\/pagecontainersdialogcontroller\/willremoveclosure","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"willRemoveClosure","kind":"identifier"},{"kind":"text","text":": (() -> ())?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainersDialogController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainersDialogController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainersDialogController"}],"url":"\/documentation\/easechatuikit\/pagecontainersdialogcontroller","title":"PageContainersDialogController","type":"topic","abstract":[{"type":"text","text":"A controller that manages a page container which displays a collection of child view controllers in a paged interface."}],"role":"symbol","navigatorTitle":[{"text":"PageContainersDialogController","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/title","op":"replace","value":"PageContainersDialogController"},{"value":[{"text":"PageContainersDialogController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainersDialogController\/navigatorTitle","value":[{"kind":"identifier","text":"PageContainersDialogController"}]}]}]}