{"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/agorachatmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/agorachatmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/AgoraChatManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/conversationListDidUpdate(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesDidReceive(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesInfoDidRecall(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/onConversationRead(_:to:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"AgoraChatManagerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/onConversationRead(_:to:)":{"role":"symbol","title":"onConversationRead(_:to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationRead"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/onConversationRead(_:to:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onConversationRead:to:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/onconversationread(_:to:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/messagesDidReceive(_:)":{"role":"symbol","title":"messagesDidReceive(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesDidReceive"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesDidReceive(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesDidReceive:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/messagesdidreceive(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"role":"symbol","title":"ConversationServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/conversationListDidUpdate(_:)":{"role":"symbol","title":"conversationListDidUpdate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationListDidUpdate"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"ChatConversation","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/conversationListDidUpdate(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"conversationListDidUpdate:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationlistdidupdate(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/messagesInfoDidRecall(_:)":{"role":"symbol","title":"messagesInfoDidRecall(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesInfoDidRecall"},{"kind":"text","text":"(["},{"kind":"typeIdentifier","text":"RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"kind":"text","text":"])"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesInfoDidRecall(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"messagesInfoDidRecall:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/messagesinfodidrecall(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/conversationListDidUpdate(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesDidReceive(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesInfoDidRecall(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/onConversationRead(_:to:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1onConversationRead(_:to:)\/title","value":"onConversationRead:to:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1onConversationRead(_:to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationRead:to:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1messagesDidReceive(_:)\/title","value":"messagesDidReceive:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1messagesDidReceive(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesDidReceive:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"kind":"identifier","text":"ConversationServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1conversationListDidUpdate(_:)\/title","value":"conversationListDidUpdate:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1conversationListDidUpdate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"conversationListDidUpdate:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1messagesInfoDidRecall(_:)\/title","value":"messagesInfoDidRecall:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1messagesInfoDidRecall(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesInfoDidRecall:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}