{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"code":"ChannelServiceListener","type":"codeVoice"}]}],"name":"listener"}],"kind":"parameters"}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationServiceImplement(im)bindConversationEventsListenerWithListener:","title":"bindConversationEventsListener(listener:)","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener","text":"ConversationServiceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Bind channel changed listener"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener":{"role":"symbol","navigatorTitle":[{"text":"ConversationServiceListener","kind":"identifier"}],"type":"topic","abstract":[],"title":"ConversationServiceListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","url":"\/documentation\/easechatuikit\/conversationservicelistener","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","title":"ConversationServiceImplement","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationServiceImplement"}],"navigatorTitle":[{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/bindConversationEventsListener(listener:)":{"role":"symbol","navigatorTitle":[{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"type":"topic","title":"bindConversationEventsListener(listener:)","abstract":[{"text":"Bind channel changed listener","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"bindConversationEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"text":"ConversationServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"kind":"article","type":"topic","title":"ConversationService Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"bindConversationEventsListenerWithListener:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<ConversationServiceListener>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"ConversationServiceListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/title"},{"value":[{"kind":"identifier","text":"ConversationServiceListener"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/fragments","op":"replace"},{"value":"ConversationServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"text":"ConversationServiceImplement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/title","value":"bindConversationEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}