{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearSilentMode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SilentModeResult","text":"SilentModeResult"},{"kind":"text","text":"?, "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"conversationId","content":[{"inlineContent":[{"text":"The id of the conversation.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback. If successful, the silent state corresponding to the session ID will be returned. If failed, the failure reason will be returned."}]}],"name":"completion"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearSilentMode","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"text":"SilentModeResult","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"clearSilentModeWithConversationId:completion:","kind":"identifier"}],"extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationServiceImplement(im)clearSilentModeWithConversationId:completion:","symbolKind":"method","roleHeading":"Instance Method","title":"clearSilentMode(conversationId:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/clearsilentmode(conversationid:completion:)"]},{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/clearsilentmode(conversationid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Clear the quiesce status of a session","type":"text"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SilentModeResult":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SilentModeResult","navigatorTitle":[{"kind":"identifier","text":"SilentModeResult"}],"type":"topic","url":"\/documentation\/easechatuikit\/silentmoderesult","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SilentModeResult"}],"title":"SilentModeResult","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/clearSilentMode(conversationId:completion:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)","role":"symbol","title":"clearSilentMode(conversationId:completion:)","navigatorTitle":[{"text":"clearSilentModeWithConversationId:completion:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/clearsilentmode(conversationid:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearSilentMode"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":")","kind":"text"}],"abstract":[{"text":"Clear the quiesce status of a session","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","title":"ConversationServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","title":"ConversationService Implementations","kind":"article","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"title":"ChatError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chaterror","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"clearSilentModeWithConversationId:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearSilentModeWithConversationId:completion:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"clearSilentModeWithConversationId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"text":")(","kind":"text"},{"text":"EMSilentModeResult","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMSilentModeResult"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMError","text":"EMError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1clearSilentMode(conversationId:completion:)\/title","value":"clearSilentModeWithConversationId:completion:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearSilentModeWithConversationId:completion:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1clearSilentMode(conversationId:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"op":"replace"}]}]}