{"metadata":{"title":"conversationListDidUpdate(_:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"conversationListDidUpdate:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"conversationListDidUpdate","kind":"identifier"},{"kind":"text","text":"(["},{"text":"ChatConversation","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"text":"])","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationServiceImplement(im)conversationListDidUpdate:","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationListDidUpdate"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"aConversationList"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","text":"ChatConversation"},{"kind":"text","text":"])"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/conversationlistdidupdate(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/conversationlistdidupdate(_:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/conversationListDidUpdate(_:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/EMChatManagerDelegate-Implementations"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"EMChatManagerDelegate.conversationListDidUpdate(_:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatConversation":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"ChatConversation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","role":"symbol","title":"ChatConversation","url":"\/documentation\/easechatuikit\/chatconversation","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ChatConversation"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/conversationListDidUpdate(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"conversationListDidUpdate","kind":"identifier"},{"text":"([","kind":"text"},{"text":"ChatConversation","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"kind":"text","text":"])"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/conversationListDidUpdate(_:)","type":"topic","navigatorTitle":[{"text":"conversationListDidUpdate:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationlistdidupdate(_:)","title":"conversationListDidUpdate(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/EMChatManagerDelegate-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/EMChatManagerDelegate-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/emchatmanagerdelegate-implementations","title":"EMChatManagerDelegate Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","title":"ConversationServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"conversationListDidUpdate:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"conversationListDidUpdate:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"conversationListDidUpdate:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<EMConversation *>"},{"kind":"text","text":" *) "},{"text":"aConversationList","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1conversationListDidUpdate(_:)\/title","value":"conversationListDidUpdate:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1conversationListDidUpdate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"conversationListDidUpdate:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement","op":"replace"},{"value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}