{"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/deleteConversation(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchAllConversations(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchPinnedConversations(cursor:pageSize:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchSilentMode(conversationIds:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadExistConversations(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/markAllMessagesAsRead(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/pin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unpin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unregisterEmergencyListener(listener:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"ConversationService Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/fetchSilentMode(conversationIds:completion:)":{"role":"symbol","title":"fetchSilentMode(conversationIds:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationIds"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get the session where the server is set to silent state"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchSilentMode(conversationIds:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchSilentModeWithConversationIds:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/fetchsilentmode(conversationids:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/unpin(conversationId:completion:)":{"role":"symbol","title":"unpin(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unpin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unpin a conversation."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unpin(conversationId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unpinWithConversationId:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/unpin(conversationid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/deleteConversation(conversationId:completion:)":{"role":"symbol","title":"deleteConversation(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deleteConversation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Delete a conversation exist in db&server."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/deleteConversation(conversationId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deleteConversationWithConversationId:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/deleteconversation(conversationid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/setSilentMode(conversationId:completion:)":{"role":"symbol","title":"setSilentMode(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set a session to silent state"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSilentModeWithConversationId:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/setsilentmode(conversationid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/fetchAllConversations(completion:)":{"role":"symbol","title":"fetchAllConversations(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchAllConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (("},{"kind":"typeIdentifier","text":"CursorResult","preciseIdentifier":"s:13EaseChatUIKit12CursorResulta"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?)"}],"abstract":[{"type":"text","text":"Fetch conversations from server."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchAllConversations(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchAllConversationsWithCompletion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/fetchallconversations(completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/loadExistConversations(completion:)":{"role":"symbol","title":"loadExistConversations(completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadExistConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": (["},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"], "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Get all conversations from database."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadExistConversations(completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadExistConversationsWithCompletion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/loadexistconversations(completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/unbindConversationEventsListener(listener:)":{"role":"symbol","title":"unbindConversationEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindConversationEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unbind channel changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unbindConversationEventsListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/unbindconversationeventslistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/fetchPinnedConversations(cursor:pageSize:completion:)":{"role":"symbol","title":"fetchPinnedConversations(cursor:pageSize:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPinnedConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cursor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"CursorResult","preciseIdentifier":"s:13EaseChatUIKit12CursorResulta"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Fetch pinned conversations from server."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchPinnedConversations(cursor:pageSize:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchPinnedConversationsWithCursor:pageSize:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/fetchpinnedconversations(cursor:pagesize:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"role":"symbol","title":"ConversationServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/clearSilentMode(conversationId:completion:)":{"role":"symbol","title":"clearSilentMode(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Clear the quiesce status of a session"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearSilentModeWithConversationId:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/clearsilentmode(conversationid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/registerEmergencyListener(listener:)":{"role":"symbol","title":"registerEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"registerEmergencyListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Register emergency listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/registerEmergencyListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"registerEmergencyListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/registeremergencylistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/bindConversationEventsListener(listener:)":{"role":"symbol","title":"bindConversationEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Bind channel changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/bindconversationeventslistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/markAllMessagesAsRead(conversationId:)":{"role":"symbol","title":"markAllMessagesAsRead(conversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"markAllMessagesAsRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Mark all of the history messages as already read."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/markAllMessagesAsRead(conversationId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"markAllMessagesAsReadWithConversationId:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/markallmessagesasread(conversationid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/unregisterEmergencyListener(listener:)":{"role":"symbol","title":"unregisterEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unregisterEmergencyListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unregister emergency listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unregisterEmergencyListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/unregisteremergencylistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/pin(conversationId:completion:)":{"role":"symbol","title":"pin(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pin"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Pin a conversation to the top"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/pin(conversationId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"pinWithConversationId:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/pin(conversationid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/loadIfNotExistCreate(conversationId:)":{"role":"symbol","title":"loadIfNotExistCreate(conversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadIfNotExistCreate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"ChatConversation","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Load a session and create one if it does not exist"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/bindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/clearSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/deleteConversation(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchAllConversations(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchPinnedConversations(cursor:pageSize:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/fetchSilentMode(conversationIds:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadExistConversations(completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/markAllMessagesAsRead(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/pin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/registerEmergencyListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unpin(conversationId:completion:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unregisterEmergencyListener(listener:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1fetchSilentMode(conversationIds:completion:)\/title","value":"fetchSilentModeWithConversationIds:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1fetchSilentMode(conversationIds:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchSilentModeWithConversationIds:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unpin(conversationId:completion:)\/title","value":"unpinWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unpin(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unpinWithConversationId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1deleteConversation(conversationId:completion:)\/title","value":"deleteConversationWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1deleteConversation(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deleteConversationWithConversationId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1setSilentMode(conversationId:completion:)\/title","value":"setSilentModeWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1setSilentMode(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSilentModeWithConversationId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1fetchAllConversations(completion:)\/title","value":"fetchAllConversationsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1fetchAllConversations(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchAllConversationsWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1loadExistConversations(completion:)\/title","value":"loadExistConversationsWithCompletion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1loadExistConversations(completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadExistConversationsWithCompletion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unbindConversationEventsListener(listener:)\/title","value":"unbindConversationEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unbindConversationEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindConversationEventsListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1fetchPinnedConversations(cursor:pageSize:completion:)\/title","value":"fetchPinnedConversationsWithCursor:pageSize:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1fetchPinnedConversations(cursor:pageSize:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fetchPinnedConversationsWithCursor:pageSize:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"kind":"identifier","text":"ConversationServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1clearSilentMode(conversationId:completion:)\/title","value":"clearSilentModeWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1clearSilentMode(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearSilentModeWithConversationId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1registerEmergencyListener(listener:)\/title","value":"registerEmergencyListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1registerEmergencyListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"registerEmergencyListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/title","value":"bindConversationEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1bindConversationEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1markAllMessagesAsRead(conversationId:)\/title","value":"markAllMessagesAsReadWithConversationId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1markAllMessagesAsRead(conversationId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markAllMessagesAsReadWithConversationId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unregisterEmergencyListener(listener:)\/title","value":"unregisterEmergencyListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unregisterEmergencyListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unregisterEmergencyListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1pin(conversationId:completion:)\/title","value":"pinWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1pin(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pinWithConversationId:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:)\/title","value":"loadIfNotExistCreateWithConversationId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}