{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"eventsNotifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSHashTable","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSHashTable"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"ConversationEmergencyListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"kind":"text","text":"> { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/eventsNotifiers"},"metadata":{"roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit28ConversationServiceImplementC15eventsNotifiersSo11NSHashTableCyAA0D17EmergencyListener_pGvp","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventsNotifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable"},{"kind":"text","text":"<"},{"text":"ConversationEmergencyListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"kind":"text","text":">"}],"modules":[{"name":"EaseChatUIKit"}],"title":"eventsNotifiers"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/eventsnotifiers"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","title":"ConversationServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","title":"ConversationEmergencyListener","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencylistener","abstract":[],"navigatorTitle":[{"text":"ConversationEmergencyListener","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationEmergencyListener","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/eventsNotifiers":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/eventsNotifiers","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"eventsNotifiers"},{"kind":"text","text":": "},{"text":"NSHashTable","preciseIdentifier":"c:objc(cs)NSHashTable","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener","text":"ConversationEmergencyListener","kind":"typeIdentifier"},{"kind":"text","text":">"}],"kind":"symbol","title":"eventsNotifiers","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/eventsnotifiers"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"kind":"identifier","text":"ConversationServiceImplement"}]},{"op":"replace","value":"ConversationEmergencyListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/fragments","value":[{"text":"ConversationEmergencyListener","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}