{"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","title":"loadIfNotExistCreate(conversationId:type:)","navigatorTitle":[{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:type:"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationServiceImplement(im)loadIfNotExistCreateWithConversationId:type:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadIfNotExistCreate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatConversationType","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","text":"ChatConversation","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadIfNotExistCreate"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","kind":"typeIdentifier","text":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType"},{"text":") -> ","kind":"text"},{"text":"ChatConversation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"conversationId","content":[{"inlineContent":[{"text":"The ID of the conversation.","type":"text"}],"type":"paragraph"}]},{"name":"type","content":[{"inlineContent":[{"text":"The ","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType","type":"reference"},{"type":"text","text":" of the conversation."}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:type:)"},"abstract":[{"type":"text","text":"Load a session and create one if it does not exist"}],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatConversation":{"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatConversation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatConversation"}],"title":"ChatConversation","type":"topic","url":"\/documentation\/easechatuikit\/chatconversation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","title":"ConversationServiceImplement","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationServiceImplement"}],"navigatorTitle":[{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"kind":"article","type":"topic","title":"ConversationService Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/loadIfNotExistCreate(conversationId:type:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/loadIfNotExistCreate(conversationId:type:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadIfNotExistCreate","kind":"identifier"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"ChatConversationType","preciseIdentifier":"s:13EaseChatUIKit0B16ConversationTypea","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"ChatConversation","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:type:"}],"title":"loadIfNotExistCreate(conversationId:type:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Load a session and create one if it does not exist"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/loadifnotexistcreate(conversationid:type:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatConversationType":{"type":"topic","url":"\/documentation\/easechatuikit\/chatconversationtype","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatConversationType"}],"navigatorTitle":[{"text":"ChatConversationType","kind":"identifier"}],"role":"symbol","abstract":[],"title":"ChatConversationType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversationType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"loadIfNotExistCreateWithConversationId:type:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:type:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"EMConversation","preciseIdentifier":"c:objc(cs)EMConversation","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"loadIfNotExistCreateWithConversationId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"type:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EMConversationType","preciseIdentifier":"c:@E@EMConversationType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:type:)\/title","value":"loadIfNotExistCreateWithConversationId:type:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1loadIfNotExistCreate(conversationId:type:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadIfNotExistCreateWithConversationId:type:"}],"op":"replace"}]}]}