{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/mapper(objects:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mapper","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"objects"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ChatConversation","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"text":"]) -> [","kind":"text"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"]"}],"externalID":"s:13EaseChatUIKit28ConversationServiceImplementC6mapper7objectsSayAA0D4InfoCGSaySo14EMConversationCG_tF","extendedModule":"EaseChatUIKit","title":"mapper(objects:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/mapper(objects:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mapper"},{"kind":"text","text":"("},{"kind":"externalParam","text":"objects"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","text":"ChatConversation","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa","kind":"typeIdentifier"},{"kind":"text","text":"]) -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"]"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatConversation":{"url":"\/documentation\/easechatuikit\/chatconversation","title":"ChatConversation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatConversation","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatConversation","kind":"identifier"}],"navigatorTitle":[{"text":"ChatConversation","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"type":"topic","title":"ConversationInfo","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationinfo","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationInfo"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/mapper(objects:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mapper","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"objects"},{"kind":"text","text":": ["},{"text":"ChatConversation","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B12Conversationa"},{"text":"]) -> [","kind":"text"},{"kind":"typeIdentifier","text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"kind":"text","text":"]"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/mapper(objects:)","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/mapper(objects:)","title":"mapper(objects:)","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceImplement"}],"title":"ConversationServiceImplement","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement"}},"variantOverrides":[{"patch":[{"value":"ConversationInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title"},{"value":[{"kind":"identifier","text":"ConversationInfo"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"kind":"identifier","text":"ConversationServiceImplement"}]},{"op":"replace","value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}