{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messagesInfoDidRecall","kind":"identifier"},{"text":"([","kind":"text"},{"text":"RecallInfo","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"kind":"text","text":"])"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messagesInfoDidRecall:"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationServiceImplement(im)messagesInfoDidRecall:","title":"messagesInfoDidRecall(_:)","modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","symbolKind":"method"},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"EMChatManagerDelegate.messagesInfoDidRecall(_:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messagesInfoDidRecall"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"aRecallMessagesInfo","kind":"internalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo","text":"RecallInfo","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"text":"])","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/EMChatManagerDelegate-Implementations"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/messagesinfodidrecall(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/messagesinfodidrecall(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesInfoDidRecall(_:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/RecallInfo":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RecallInfo"}],"title":"RecallInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"RecallInfo"}],"url":"\/documentation\/easechatuikit\/recallinfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceImplement"}],"title":"ConversationServiceImplement","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/messagesInfoDidRecall(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messagesInfoDidRecall","kind":"identifier"},{"text":"([","kind":"text"},{"text":"RecallInfo","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"messagesInfoDidRecall:","kind":"identifier"}],"title":"messagesInfoDidRecall(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/messagesInfoDidRecall(_:)","kind":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/messagesinfodidrecall(_:)","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/EMChatManagerDelegate-Implementations":{"type":"topic","abstract":[],"title":"EMChatManagerDelegate Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/emchatmanagerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/EMChatManagerDelegate-Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"messagesInfoDidRecall:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messagesInfoDidRecall:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messagesInfoDidRecall:"},{"kind":"text","text":"("},{"text":"NSArray<EMRecallMessageInfo *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aRecallMessagesInfo"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","op":"replace","value":"ConversationServiceImplement"},{"value":[{"text":"ConversationServiceImplement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments"},{"value":[{"kind":"identifier","text":"ConversationServiceImplement"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1messagesInfoDidRecall(_:)\/title","value":"messagesInfoDidRecall:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"messagesInfoDidRecall:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1messagesInfoDidRecall(_:)\/fragments"}]}]}