{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta","text":"SilentModeResult"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"conversationId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of the conversation."}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback. If successful, the silent state corresponding to the session ID will be returned. If failed, the failure reason will be returned."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/setsilentmode(conversationid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/setsilentmode(conversationid:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set a session to silent state"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"title":"setSilentMode(conversationId:completion:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationServiceImplement(im)setSilentModeWithConversationId:completion:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"setSilentModeWithConversationId:completion:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"role":"symbol","title":"ChatError","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatError"}],"url":"\/documentation\/easechatuikit\/chaterror"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"role":"symbol","title":"ConversationServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SilentModeResult":{"role":"symbol","title":"SilentModeResult","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SilentModeResult"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SilentModeResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SilentModeResult"}],"url":"\/documentation\/easechatuikit\/silentmoderesult"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/setSilentMode(conversationId:completion:)":{"role":"symbol","title":"setSilentMode(conversationId:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setSilentMode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","text":"SilentModeResult","preciseIdentifier":"s:13EaseChatUIKit16SilentModeResulta"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Set a session to silent state"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/setSilentMode(conversationId:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setSilentModeWithConversationId:completion:"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/setsilentmode(conversationid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"role":"collectionGroup","title":"ConversationService Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setSilentModeWithConversationId:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSilentModeWithConversationId:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setSilentModeWithConversationId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"conversationId"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(AgoraChatSilentModeResult *, AgoraChatError *)","preciseIdentifier":"c:BFv(#*$objc(cs)AgoraChatSilentModeResult#*$objc(cs)AgoraChatError)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"kind":"identifier","text":"ConversationServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1setSilentMode(conversationId:completion:)\/title","value":"setSilentModeWithConversationId:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1setSilentMode(conversationId:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setSilentModeWithConversationId:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}