{"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindConversationEventsListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationServiceImplement(im)unbindConversationEventsListenerWithListener:","role":"symbol","extendedModule":"EaseChatUIKit","title":"unbindConversationEventsListener(listener:)","navigatorTitle":[{"kind":"identifier","text":"unbindConversationEventsListenerWithListener:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"unbindConversationEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier","text":"ConversationServiceListener"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"ChannelServiceListener","type":"codeVoice"}]}]}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/unbindconversationeventslistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationserviceimplement\/unbindconversationeventslistener(listener:)"]}],"abstract":[{"text":"Unbind channel changed listener","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/ConversationService-Implementations":{"kind":"article","type":"topic","title":"ConversationService Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/conversationservice-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/ConversationService-Implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener":{"role":"symbol","navigatorTitle":[{"text":"ConversationServiceListener","kind":"identifier"}],"type":"topic","abstract":[],"title":"ConversationServiceListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ConversationServiceListener","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","url":"\/documentation\/easechatuikit\/conversationservicelistener","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","title":"ConversationServiceImplement","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationServiceImplement"}],"navigatorTitle":[{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement/unbindConversationEventsListener(listener:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement\/unbindConversationEventsListener(listener:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindConversationEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"unbindConversationEventsListenerWithListener:","kind":"identifier"}],"title":"unbindConversationEventsListener(listener:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Unbind channel changed listener"}],"url":"\/documentation\/easechatuikit\/conversationserviceimplement\/unbindconversationeventslistener(listener:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"unbindConversationEventsListenerWithListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"unbindConversationEventsListenerWithListener:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"unbindConversationEventsListenerWithListener:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<ConversationServiceListener>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ConversationServiceListener","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/title","value":"ConversationServiceListener"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationServiceListener"}]},{"value":"ConversationServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"text":"ConversationServiceImplement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unbindConversationEventsListener(listener:)\/title","op":"replace","value":"unbindConversationEventsListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement~1unbindConversationEventsListener(listener:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unbindConversationEventsListenerWithListener:","kind":"identifier"}]}]}]}