{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@SearchHeaderBarDisplayStyle@SearchHeaderBarDisplayStyleOther","roleHeading":"Case","title":"SearchHeaderBarDisplayStyle.other","role":"symbol","navigatorTitle":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"other","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/other"]},{"paths":["\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/other"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/other","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle/other":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"other"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/other","role":"symbol","navigatorTitle":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/other","title":"SearchHeaderBarDisplayStyle.other","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}],"abstract":[],"title":"SearchHeaderBarDisplayStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"SearchHeaderBarDisplayStyleOther","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyleOther"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SearchHeaderBarDisplayStyleOther","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1other\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1other\/fragments","value":[{"text":"SearchHeaderBarDisplayStyleOther","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/title","op":"replace","value":"SearchHeaderBarDisplayStyle"},{"value":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/navigatorTitle","op":"replace","value":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}]}]}]}