{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/withback"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/withback"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/withBack"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withBack"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"withBack","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case","title":"SearchHeaderBarDisplayStyle.withBack","role":"symbol","externalID":"c:@M@EaseChatUIKit@E@SearchHeaderBarDisplayStyle@SearchHeaderBarDisplayStyleWithBack","navigatorTitle":[{"kind":"identifier","text":"SearchHeaderBarDisplayStyleWithBack"}],"modules":[{"name":"EaseChatUIKit"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle/withBack":{"navigatorTitle":[{"text":"SearchHeaderBarDisplayStyleWithBack","kind":"identifier"}],"kind":"symbol","title":"SearchHeaderBarDisplayStyle.withBack","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle\/withBack","abstract":[],"url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle\/withback","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"withBack","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHeaderBarDisplayStyle":{"title":"SearchHeaderBarDisplayStyle","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHeaderBarDisplayStyle"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHeaderBarDisplayStyle","url":"\/documentation\/easechatuikit\/searchheaderbardisplaystyle","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SearchHeaderBarDisplayStyleWithBack"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SearchHeaderBarDisplayStyleWithBack","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SearchHeaderBarDisplayStyleWithBack","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1withBack\/title","op":"replace","value":"SearchHeaderBarDisplayStyleWithBack"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle~1withBack\/fragments","value":[{"text":"SearchHeaderBarDisplayStyleWithBack","kind":"identifier"}],"op":"replace"},{"value":"SearchHeaderBarDisplayStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHeaderBarDisplayStyle\/fragments","op":"replace","value":[{"text":"SearchHeaderBarDisplayStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}