{"variants":[{"paths":["\/documentation\/easechatuikit\/actionsheetitemprotocol\/action"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/actionsheetitemprotocol\/action"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The closure to be executed when the action sheet item is selected."}],"metadata":{"role":"symbol","required":true,"title":"action","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol(py)action","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea","kind":"typeIdentifier","text":"ActionClosure"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"action","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol\/action","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionClosure","kind":"typeIdentifier","text":"ActionClosure"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol/action":{"abstract":[{"text":"The closure to be executed when the action sheet item is selected.","type":"text"}],"title":"action","type":"topic","url":"\/documentation\/easechatuikit\/actionsheetitemprotocol\/action","required":true,"role":"symbol","navigatorTitle":[{"text":"action","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol\/action","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"action","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ActionClosure","preciseIdentifier":"s:13EaseChatUIKit13ActionClosurea","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionClosure":{"role":"symbol","url":"\/documentation\/easechatuikit\/actionclosure","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionClosure","type":"topic","title":"ActionClosure","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionClosure"}],"navigatorTitle":[{"text":"ActionClosure","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol":{"abstract":[{"text":"A protocol that defines properties and methods for an action sheet item.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/actionsheetitemprotocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","title":"ActionSheetItemProtocol","navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"action","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"action"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":" (^","kind":"text"},{"text":"action","kind":"identifier"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"id<ActionSheetItemProtocol>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"text":", ","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"","kind":"internalParam"},{"kind":"text","text":");"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol~1action\/title","value":"action"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol~1action\/fragments","value":[{"text":"action","kind":"identifier"}]},{"op":"replace","value":"ActionSheetItemProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/title"},{"op":"replace","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/navigatorTitle","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}