{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"text":"ActionSheetItemType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol(py)type","symbolKind":"property","required":true,"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"kind":"text","text":": "},{"text":"ActionSheetItemType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","kind":"typeIdentifier"}],"title":"type","navigatorTitle":[{"kind":"identifier","text":"type"}]},"abstract":[{"text":"The type of the action sheet item.","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","isActive":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/actionsheetitemprotocol\/type"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/actionsheetitemprotocol\/type"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol\/type","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemType":{"title":"ActionSheetItemType","navigatorTitle":[{"text":"ActionSheetItemType","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ActionSheetItemType","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/actionsheetitemtype","kind":"symbol","abstract":[{"type":"text","text":"An enumeration representing the type of an action sheet item."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol":{"abstract":[{"text":"A protocol that defines properties and methods for an action sheet item.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/actionsheetitemprotocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","title":"ActionSheetItemProtocol","navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol/type":{"title":"type","role":"symbol","url":"\/documentation\/easechatuikit\/actionsheetitemprotocol\/type","abstract":[{"type":"text","text":"The type of the action sheet item."},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType","isActive":true}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ActionSheetItemType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType"}],"kind":"symbol","required":true,"navigatorTitle":[{"text":"type","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol\/type","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"type"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"type","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ActionSheetItemType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ActionSheetItemType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ActionSheetItemType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/fragments","op":"replace","value":[{"kind":"identifier","text":"ActionSheetItemType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemType\/navigatorTitle","value":[{"text":"ActionSheetItemType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/title","op":"replace","value":"ActionSheetItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/fragments","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol~1type\/title","value":"type","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol~1type\/fragments","value":[{"kind":"identifier","text":"type"}],"op":"replace"}]}]}