{"variants":[{"paths":["\/documentation\/easechatuikit\/alertmessagecell\/clickaction(gesture:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/alertmessagecell\/clickaction(gesture:)"]}],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)AlertMessageCell(im)clickActionWithGesture:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"clickActionWithGesture:","kind":"identifier"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickAction"},{"kind":"text","text":"("},{"text":"gesture","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","kind":"typeIdentifier","text":"UITapGestureRecognizer"},{"text":")","kind":"text"}],"role":"symbol","title":"clickAction(gesture:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/clickAction(gesture:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clickAction"},{"kind":"text","text":"("},{"text":"gesture","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITapGestureRecognizer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell/clickAction(gesture:)":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell\/clickAction(gesture:)","type":"topic","navigatorTitle":[{"text":"clickActionWithGesture:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/alertmessagecell\/clickaction(gesture:)","role":"symbol","title":"clickAction(gesture:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clickAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"gesture","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITapGestureRecognizer","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertMessageCell":{"navigatorTitle":[{"text":"AlertMessageCell","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AlertMessageCell"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertMessageCell","kind":"symbol","title":"AlertMessageCell","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/alertmessagecell","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clickActionWithGesture:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"clickActionWithGesture:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"clickActionWithGesture:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITapGestureRecognizer","text":"UITapGestureRecognizer"},{"text":" *) ","kind":"text"},{"text":"gesture","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"clickActionWithGesture:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1clickAction(gesture:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell~1clickAction(gesture:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clickActionWithGesture:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell\/title","value":"AlertMessageCell","op":"replace"},{"value":[{"kind":"identifier","text":"AlertMessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"AlertMessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertMessageCell\/navigatorTitle"}]}]}