{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"itemIndexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/choiceitemlayout\/initiallayoutattributesforappearingitem(at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/choiceitemlayout\/initiallayoutattributesforappearingitem(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout\/initialLayoutAttributesForAppearingItem(at:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"title":"initialLayoutAttributesForAppearingItem(at:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ChoiceItemLayout(im)initialLayoutAttributesForAppearingItemAtIndexPath:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChoiceItemLayout/initialLayoutAttributesForAppearingItem(at:)":{"role":"symbol","title":"initialLayoutAttributesForAppearingItem(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItem"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout\/initialLayoutAttributesForAppearingItem(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"}],"url":"\/documentation\/easechatuikit\/choiceitemlayout\/initiallayoutattributesforappearingitem(at:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChoiceItemLayout":{"role":"symbol","title":"ChoiceItemLayout","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"abstract":[{"type":"text","text":"Choice layout"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"url":"\/documentation\/easechatuikit\/choiceitemlayout"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initialLayoutAttributesForAppearingItemAtIndexPath:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UICollectionViewLayoutAttributes","preciseIdentifier":"c:objc(cs)UICollectionViewLayoutAttributes"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"itemIndexPath"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout~1initialLayoutAttributesForAppearingItem(at:)\/title","value":"initialLayoutAttributesForAppearingItemAtIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout~1initialLayoutAttributesForAppearingItem(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initialLayoutAttributesForAppearingItemAtIndexPath:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout\/title","value":"ChoiceItemLayout"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout\/fragments","value":[{"kind":"identifier","text":"ChoiceItemLayout"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}