{"sections":[],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forCollectionViewUpdates"},{"text":": [","kind":"text"},{"text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"roleHeading":"Instance Method","title":"prepare(forCollectionViewUpdates:)","symbolKind":"method","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ChoiceItemLayout(im)prepareForCollectionViewUpdates:","navigatorTitle":[{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}],"modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prepare","kind":"identifier"},{"kind":"text","text":"("},{"text":"forCollectionViewUpdates","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"updateItems","kind":"internalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout\/prepare(forCollectionViewUpdates:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChoiceItemLayout/prepare(forCollectionViewUpdates:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepare"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forCollectionViewUpdates"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionViewUpdateItem","preciseIdentifier":"c:objc(cs)UICollectionViewUpdateItem"},{"kind":"text","text":"])"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout\/prepare(forCollectionViewUpdates:)","title":"prepare(forCollectionViewUpdates:)","url":"\/documentation\/easechatuikit\/choiceitemlayout\/prepare(forcollectionviewupdates:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"prepareForCollectionViewUpdates:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChoiceItemLayout":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChoiceItemLayout"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChoiceItemLayout"}],"url":"\/documentation\/easechatuikit\/choiceitemlayout","kind":"symbol","title":"ChoiceItemLayout","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChoiceItemLayout","abstract":[{"type":"text","text":"Choice layout"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"prepareForCollectionViewUpdates:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"prepareForCollectionViewUpdates:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"prepareForCollectionViewUpdates:"},{"kind":"text","text":"("},{"text":"NSArray<UICollectionViewUpdateItem *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"updateItems"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"prepareForCollectionViewUpdates:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout~1prepare(forCollectionViewUpdates:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"prepareForCollectionViewUpdates:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout~1prepare(forCollectionViewUpdates:)\/fragments"},{"value":"ChoiceItemLayout","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout\/title","op":"replace"},{"value":[{"text":"ChoiceItemLayout","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChoiceItemLayout\/fragments","op":"replace"}]}]}