{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAllBlockUsers","kind":"identifier"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchblockcontactcontroller\/loadallblockusers()"]},{"paths":["\/documentation\/easechatuikit\/searchblockcontactcontroller\/loadallblockusers()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"loadAllBlockUsers","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)SearchBlockContactController(im)loadAllBlockUsers","title":"loadAllBlockUsers()","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadAllBlockUsers","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/loadAllBlockUsers()"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchBlockContactController":{"title":"SearchBlockContactController","navigatorTitle":[{"kind":"identifier","text":"SearchBlockContactController"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBlockContactController"}],"url":"\/documentation\/easechatuikit\/searchblockcontactcontroller","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchBlockContactController/loadAllBlockUsers()":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/loadAllBlockUsers()","role":"symbol","title":"loadAllBlockUsers()","url":"\/documentation\/easechatuikit\/searchblockcontactcontroller\/loadallblockusers()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadAllBlockUsers","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"loadAllBlockUsers"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"loadAllBlockUsers","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"loadAllBlockUsers","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"loadAllBlockUsers","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SearchBlockContactController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/fragments","value":[{"kind":"identifier","text":"SearchBlockContactController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/navigatorTitle","value":[{"kind":"identifier","text":"SearchBlockContactController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController~1loadAllBlockUsers()\/title","op":"replace","value":"loadAllBlockUsers"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadAllBlockUsers"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController~1loadAllBlockUsers()\/fragments"}]}]}