{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"presentSearchController:"}],"role":"symbol","title":"presentSearchController(_:)","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)SearchBlockContactController(im)presentSearchController:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentSearchController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"symbolKind":"method"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/searchblockcontactcontroller\/presentsearchcontroller(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/searchblockcontactcontroller\/presentsearchcontroller(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/UISearchControllerDelegate-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/presentSearchController(_:)"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISearchControllerDelegate.presentSearchController(_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentSearchController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"searchController"},{"text":": ","kind":"text"},{"text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchBlockContactController":{"title":"SearchBlockContactController","navigatorTitle":[{"kind":"identifier","text":"SearchBlockContactController"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBlockContactController"}],"url":"\/documentation\/easechatuikit\/searchblockcontactcontroller","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchBlockContactController/presentSearchController(_:)":{"navigatorTitle":[{"text":"presentSearchController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/presentSearchController(_:)","title":"presentSearchController(_:)","abstract":[],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentSearchController"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"url":"\/documentation\/easechatuikit\/searchblockcontactcontroller\/presentsearchcontroller(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchBlockContactController/UISearchControllerDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/UISearchControllerDelegate-Implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/easechatuikit\/searchblockcontactcontroller\/uisearchcontrollerdelegate-implementations","title":"UISearchControllerDelegate Implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"presentSearchController:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"presentSearchController:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"presentSearchController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController"},{"kind":"text","text":" *) "},{"text":"searchController","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/title","op":"replace","value":"SearchBlockContactController"},{"value":[{"text":"SearchBlockContactController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/navigatorTitle","value":[{"kind":"identifier","text":"SearchBlockContactController"}],"op":"replace"},{"value":"presentSearchController:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController~1presentSearchController(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"presentSearchController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController~1presentSearchController(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}