{"topicSections":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/updateSearchResults(for:)"],"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"UISearchResultsUpdating Implementations","roleHeading":"API Collection"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchblockcontactcontroller\/uisearchresultsupdating-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchblockcontactcontroller\/uisearchresultsupdating-implementations"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/UISearchResultsUpdating-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchBlockContactController/updateSearchResults(for:)":{"navigatorTitle":[{"kind":"identifier","text":"updateSearchResultsForSearchController:"}],"url":"\/documentation\/easechatuikit\/searchblockcontactcontroller\/updatesearchresults(for:)","abstract":[],"role":"symbol","title":"updateSearchResults(for:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/updateSearchResults(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateSearchResults","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchBlockContactController":{"title":"SearchBlockContactController","navigatorTitle":[{"kind":"identifier","text":"SearchBlockContactController"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SearchBlockContactController"}],"url":"\/documentation\/easechatuikit\/searchblockcontactcontroller","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchBlockContactController\/updateSearchResults(for:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":"updateSearchResultsForSearchController:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController~1updateSearchResults(for:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"updateSearchResultsForSearchController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController~1updateSearchResults(for:)\/fragments"},{"value":"SearchBlockContactController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/fragments","value":[{"kind":"identifier","text":"SearchBlockContactController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchBlockContactController\/navigatorTitle","value":[{"text":"SearchBlockContactController","kind":"identifier"}],"op":"replace"}]}]}