{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"began"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchFieldState"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchfieldstate\/began"]},{"paths":["\/documentation\/easechatuikit\/searchfieldstate\/began"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@E@SearchFieldState@SearchFieldStateBegan","role":"symbol","title":"SearchFieldState.began","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"began"}],"navigatorTitle":[{"text":"SearchFieldStateBegan","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchFieldState\/began"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchFieldState":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchFieldState","url":"\/documentation\/easechatuikit\/searchfieldstate","navigatorTitle":[{"text":"SearchFieldState","kind":"identifier"}],"kind":"symbol","title":"SearchFieldState","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchFieldState"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchFieldState/began":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchFieldStateBegan"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"began"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchFieldState\/began","role":"symbol","title":"SearchFieldState.began","url":"\/documentation\/easechatuikit\/searchfieldstate\/began","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SearchFieldStateBegan","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SearchFieldStateBegan","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SearchFieldStateBegan"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"SearchFieldState","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchFieldState\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchFieldState\/fragments","op":"replace","value":[{"kind":"identifier","text":"SearchFieldState"}]},{"op":"replace","value":"SearchFieldStateBegan","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchFieldState~1began\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchFieldState~1began\/fragments","op":"replace","value":[{"kind":"identifier","text":"SearchFieldStateBegan"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}