{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@IBInspectable","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"The color of the disk in the view center, the default value is ripplePink color"}],"variants":[{"paths":["\/documentation\/easechatuikit\/rippleanimationview\/diskcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/rippleanimationview\/diskcolor"]}],"metadata":{"title":"diskColor","externalID":"c:@M@EaseChatUIKit@objc(cs)RippleAnimationView(py)diskColor","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"diskColor"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"diskColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RippleAnimationView\/diskColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RippleAnimationView"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/RippleAnimationView":{"url":"\/documentation\/easechatuikit\/rippleanimationview","role":"symbol","abstract":[{"type":"text","text":"A view with ripple animation"}],"navigatorTitle":[{"text":"RippleAnimationView","kind":"identifier"}],"type":"topic","title":"RippleAnimationView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RippleAnimationView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RippleAnimationView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/RippleAnimationView/diskColor":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RippleAnimationView\/diskColor","abstract":[{"type":"text","text":"The color of the disk in the view center, the default value is ripplePink color"}],"url":"\/documentation\/easechatuikit\/rippleanimationview\/diskcolor","navigatorTitle":[{"text":"diskColor","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"diskColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","title":"diskColor"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"diskColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"diskColor","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"diskColor"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"RippleAnimationView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1RippleAnimationView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"RippleAnimationView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1RippleAnimationView\/fragments","op":"replace"},{"op":"replace","value":"diskColor","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1RippleAnimationView~1diskColor\/title"},{"value":[{"kind":"identifier","text":"diskColor"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1RippleAnimationView~1diskColor\/fragments"}]}]}