{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/didSelect(entity:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate\/didselect(entity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate\/didselect(entity:)"]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"didSelectWithEntity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didSelect","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"text":"PinnedMessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity"},{"kind":"text","text":")"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate(im)didSelectWithEntity:","role":"symbol","roleHeading":"Instance Method","title":"didSelect(entity:)","required":true,"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didSelect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity","kind":"typeIdentifier","text":"PinnedMessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity"},{"text":")","kind":"text"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate/didSelect(entity:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"didSelect","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity","text":"PinnedMessageEntity"},{"text":")","kind":"text"}],"abstract":[],"title":"didSelect(entity:)","role":"symbol","navigatorTitle":[{"text":"didSelectWithEntity:","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate\/didSelect(entity:)","url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate\/didselect(entity:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate":{"navigatorTitle":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","kind":"symbol","title":"PinnedMessagesContainerDelegate","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessageEntity":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessageentity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity","navigatorTitle":[{"kind":"identifier","text":"PinnedMessageEntity"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PinnedMessageEntity","kind":"identifier"}],"title":"PinnedMessageEntity","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"didSelectWithEntity:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"didSelectWithEntity:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"didSelectWithEntity:"},{"text":"(","kind":"text"},{"text":"PinnedMessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"entity"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"didSelectWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate~1didSelect(entity:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didSelectWithEntity:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate~1didSelect(entity:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/title","value":"PinnedMessagesContainerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/fragments","value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"op":"replace"},{"value":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/title","value":"PinnedMessageEntity","op":"replace"},{"value":[{"text":"PinnedMessageEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/fragments"},{"value":[{"text":"PinnedMessageEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}