{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/addEventsListener(_:)"},"sections":[],"abstract":[{"text":"Add events listener of the message list.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addEventsListener"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"listener"},{"kind":"text","text":": "},{"text":"MessageListDriverEventsListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","isActive":true,"type":"reference"}]}],"name":"listener"}],"kind":"parameters"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MessageListDriverEventsListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"addEventsListener:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageListViewModel(im)addEventsListener:","symbolKind":"method","roleHeading":"Instance Method","title":"addEventsListener(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/addeventslistener(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/addeventslistener(_:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListViewModel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","navigatorTitle":[{"text":"MessageListViewModel","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel","role":"symbol","title":"MessageListViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/addEventsListener(_:)":{"title":"addEventsListener(_:)","abstract":[{"type":"text","text":"Add events listener of the message list."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MessageListDriverEventsListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/addeventslistener(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/addEventsListener(_:)","navigatorTitle":[{"text":"addEventsListener:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener":{"title":"MessageListDriverEventsListener","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListDriverEventsListener","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","navigatorTitle":[{"text":"MessageListDriverEventsListener","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"addEventsListener:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addEventsListener:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"addEventsListener:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<MessageListDriverEventsListener>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments"},{"value":"addEventsListener:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1addEventsListener(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1addEventsListener(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addEventsListener:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/title","op":"replace","value":"MessageListDriverEventsListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/fragments","value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}]}]}]}