{"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/bindpincontainerdriver(driver:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/bindpincontainerdriver(driver:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","title":"bindPinContainerDriver(driver:)","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"bindPinContainerDriverWithDriver:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindPinContainerDriver"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"driver"},{"text":": ","kind":"text"},{"text":"IPinnedMessagesContainerDriver","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IPinnedMessagesContainerDriver"},{"kind":"text","text":")"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageListViewModel(im)bindPinContainerDriverWithDriver:"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/bindPinContainerDriver(driver:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindPinContainerDriver"},{"text":"(","kind":"text"},{"text":"driver","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IPinnedMessagesContainerDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IPinnedMessagesContainerDriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/bindPinContainerDriver(driver:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/bindPinContainerDriver(driver:)","type":"topic","navigatorTitle":[{"text":"bindPinContainerDriverWithDriver:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindPinContainerDriver","kind":"identifier"},{"kind":"text","text":"("},{"text":"driver","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IPinnedMessagesContainerDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IPinnedMessagesContainerDriver"},{"text":")","kind":"text"}],"title":"bindPinContainerDriver(driver:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/bindpincontainerdriver(driver:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver":{"url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"IPinnedMessagesContainerDriver","navigatorTitle":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"bindPinContainerDriverWithDriver:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"bindPinContainerDriverWithDriver:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"bindPinContainerDriverWithDriver:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)IPinnedMessagesContainerDriver","kind":"typeIdentifier","text":"id<IPinnedMessagesContainerDriver>"},{"text":") ","kind":"text"},{"text":"driver","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","op":"replace","value":"MessageListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"MessageListViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1bindPinContainerDriver(driver:)\/title","value":"bindPinContainerDriverWithDriver:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1bindPinContainerDriver(driver:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"bindPinContainerDriverWithDriver:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/title","op":"replace","value":"IPinnedMessagesContainerDriver"},{"value":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/navigatorTitle","op":"replace","value":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}