{"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onCurrentUserLeft(groupId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupOwnerUpdated(groupId:ownerId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onUserJoinedGroup(groupId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onUserLeaveGroup(groupId:userId:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"kind":"article","variants":[{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/groupservicelistener-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/groupservicelistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"GroupServiceListener Implementations","roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupServiceListener-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onGroupOwnerUpdated(groupId:ownerId:userId:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupOwnerUpdated"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ownerId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"abstract":[{"text":"The group owner of the current group has changed.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupownerupdated(groupid:ownerid:userid:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupOwnerUpdated(groupId:ownerId:userId:)","title":"onGroupOwnerUpdated(groupId:ownerId:userId:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onUserLeaveGroup(groupId:userId:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onUserLeaveGroup"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"onUserLeaveGroupWithGroupId:userId:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onUserLeaveGroup(groupId:userId:)","type":"topic","abstract":[{"type":"text","text":"When some user left group."}],"title":"onUserLeaveGroup(groupId:userId:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onuserleavegroup(groupid:userid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onAttributesChangedOfGroupMember"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"operatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">)"}],"abstract":[{"text":"When attributes changed of some group member.","type":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onattributeschangedofgroupmember(groupid:userid:operatorid:attributes:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","title":"onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"kind":"symbol","title":"MessageListViewModel","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","url":"\/documentation\/easechatuikit\/messagelistviewmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"text":"MessageListViewModel","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onUserJoinedGroup(groupId:userId:)":{"role":"symbol","abstract":[{"type":"text","text":"When some user joined group."}],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onuserjoinedgroup(groupid:userid:)","navigatorTitle":[{"text":"onUserJoinedGroupWithGroupId:userId:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onUserJoinedGroup(groupId:userId:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onUserJoinedGroup","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"onUserJoinedGroup(groupId:userId:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onCurrentUserLeft(groupId:reason:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onCurrentUserLeft","kind":"identifier"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GroupLeaveReason","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16GroupLeaveReasona"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Current user is removed."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/oncurrentuserleft(groupid:reason:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onCurrentUserLeft(groupId:reason:)","title":"onCurrentUserLeft(groupId:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onCurrentUserLeft(groupId:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupOwnerUpdated(groupId:ownerId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onUserJoinedGroup(groupId:userId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onUserLeaveGroup(groupId:userId:)"],"generated":true}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupOwnerUpdated(groupId:ownerId:userId:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onGroupOwnerUpdatedWithGroupId:ownerId:userId:"}]},{"value":"onUserLeaveGroupWithGroupId:userId:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onUserLeaveGroup(groupId:userId:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onUserLeaveGroup(groupId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onUserLeaveGroupWithGroupId:userId:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/title","value":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onAttributesChangedOfGroupMember(groupId:userId:operatorId:attributes:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAttributesChangedOfGroupMemberWithGroupId:userId:operatorId:attributes:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onUserJoinedGroup(groupId:userId:)\/title","value":"onUserJoinedGroupWithGroupId:userId:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onUserJoinedGroup(groupId:userId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserJoinedGroupWithGroupId:userId:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onCurrentUserLeft(groupId:reason:)\/title","value":"onCurrentUserLeftWithGroupId:reason:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onCurrentUserLeft(groupId:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onCurrentUserLeftWithGroupId:reason:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}