{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupChatThreadEventListener-Implementations","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","roleHeading":"API Collection","title":"GroupChatThreadEventListener Implementations"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/groupchatthreadeventlistener-implementations"]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/groupchatthreadeventlistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupChatThreadEventOccur(type:event:)"]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onGroupChatThreadEventOccur(type:event:)":{"navigatorTitle":[{"text":"onGroupChatThreadEventOccurWithType:event:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupChatThreadEventOccur(type:event:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupchatthreadeventoccur(type:event:)","role":"symbol","abstract":[{"type":"text","text":"Some event occur on group chat thread."}],"title":"onGroupChatThreadEventOccur(type:event:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupChatThreadEventOccur","kind":"identifier"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","text":"GroupChatThreadEventType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"kind":"symbol","title":"MessageListViewModel","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","url":"\/documentation\/easechatuikit\/messagelistviewmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"text":"MessageListViewModel","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupChatThreadEventOccur(type:event:)"],"generated":true}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":"onGroupChatThreadEventOccurWithType:event:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupChatThreadEventOccur(type:event:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupChatThreadEventOccur(type:event:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}]},{"op":"replace","value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"kind":"identifier","text":"MessageListViewModel"}]}]}]}