{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageTopicClicked"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/messagetopicclicked(entity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/messagetopicclicked(entity:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageTopicClicked"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"messageTopicClickedWithEntity:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","title":"messageTopicClicked(entity:)","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)messageTopicClickedWithEntity:","symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageTopicClicked(entity:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageTopicClicked(entity:)":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagetopicclicked(entity:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageTopicClicked(entity:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageTopicClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"title":"messageTopicClicked(entity:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"messageTopicClickedWithEntity:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"title":"MessageEntity","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageEntity"}],"url":"\/documentation\/easechatuikit\/messageentity","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"messageTopicClickedWithEntity:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"messageTopicClickedWithEntity:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messageTopicClickedWithEntity:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"entity"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageTopicClicked(entity:)\/title","op":"replace","value":"messageTopicClickedWithEntity:"},{"value":[{"kind":"text","text":"- "},{"text":"messageTopicClickedWithEntity:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageTopicClicked(entity:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title","value":"MessageEntity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments","value":[{"kind":"identifier","text":"MessageEntity"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/navigatorTitle","value":[{"kind":"identifier","text":"MessageEntity"}],"op":"replace"},{"op":"replace","value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"MessageListViewModel"}]}]}]}