{"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidRecalled(recallInfo:)"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDidRecalled"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","kind":"typeIdentifier","text":"RecallInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"title":"messageDidRecalled(recallInfo:)","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)messageDidRecalledWithRecallInfo:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/messagedidrecalled(recallinfo:)"]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/messagedidrecalled(recallinfo:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Handles the event when a message is recalled."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recallInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","kind":"typeIdentifier","text":"RecallInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"recallInfo","content":[{"inlineContent":[{"type":"text","text":"The recall information containing the recalled message."}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageDidRecalled(recallInfo:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","kind":"typeIdentifier","text":"RecallInfo"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageDidRecalled(recallInfo:)","abstract":[{"text":"Handles the event when a message is recalled.","type":"text"}],"title":"messageDidRecalled(recallInfo:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagedidrecalled(recallinfo:)","navigatorTitle":[{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/RecallInfo":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RecallInfo"}],"title":"RecallInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"RecallInfo"}],"url":"\/documentation\/easechatuikit\/recallinfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"messageDidRecalledWithRecallInfo:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messageDidRecalledWithRecallInfo:"},{"text":"(","kind":"text"},{"text":"EMRecallMessageInfo","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMRecallMessageInfo"},{"kind":"text","text":" *) "},{"text":"recallInfo","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The recall information containing the recalled message.","type":"text"}]}],"name":"recallInfo"}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidRecalled(recallInfo:)\/title","value":"messageDidRecalledWithRecallInfo:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"messageDidRecalledWithRecallInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageDidRecalled(recallInfo:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"value":[{"text":"MessageListViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}]}]}]}