{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageReactionChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"changes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MessageReactionChange","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)messageReactionChangedWithChanges:","symbolKind":"method","extendedModule":"EaseChatUIKit","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"messageReactionChangedWithChanges:"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageReactionChanged","kind":"identifier"},{"text":"(","kind":"text"},{"text":"changes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MessageReactionChange","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"kind":"text","text":"])"}],"title":"messageReactionChanged(changes:)"},"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/messagereactionchanged(changes:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/messagereactionchanged(changes:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionChanged(changes:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionChange":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionchange","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReactionChange"}],"title":"MessageReactionChange","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageReactionChange"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/messageReactionChanged(changes:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/messageReactionChanged(changes:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageReactionChangedWithChanges:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageReactionChanged"},{"text":"(","kind":"text"},{"text":"changes","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MessageReactionChange","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"kind":"text","text":"])"}],"abstract":[],"kind":"symbol","title":"messageReactionChanged(changes:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagereactionchanged(changes:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"messageReactionChangedWithChanges:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"messageReactionChangedWithChanges:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messageReactionChangedWithChanges:"},{"kind":"text","text":"("},{"text":"NSArray<EMMessageReactionChange *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"changes"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","op":"replace","value":[{"text":"MessageListViewModel","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageReactionChanged(changes:)\/title","value":"messageReactionChangedWithChanges:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1messageReactionChanged(changes:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageReactionChangedWithChanges:"}]}]}]}