{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupchatthreadeventoccur(type:event:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupchatthreadeventoccur(type:event:)"]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupChatThreadEventOccur(type:event:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupChatThreadEventListener-Implementations"]]},"metadata":{"title":"onGroupChatThreadEventOccur(type:event:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)onGroupChatThreadEventOccurWithType:event:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onGroupChatThreadEventOccur"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupChatThreadEventType","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"event"},{"kind":"text","text":": "},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Some event occur on group chat thread.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupChatThreadEventOccur","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","text":"GroupChatThreadEventType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupChatThreadEvent","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"type"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","isActive":true,"type":"reference"}]}],"name":"event"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType":{"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/groupchatthreadeventtype","title":"GroupChatThreadEventType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupChatThreadEventType"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onGroupChatThreadEventOccur(type:event:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onGroupChatThreadEventOccur"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"GroupChatThreadEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"event"},{"text":": ","kind":"text"},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"abstract":[{"text":"Some event occur on group chat thread.","type":"text"}],"title":"onGroupChatThreadEventOccur(type:event:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupchatthreadeventoccur(type:event:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupChatThreadEventOccur(type:event:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/GroupChatThreadEventListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/GroupChatThreadEventListener-Implementations","kind":"article","title":"GroupChatThreadEventListener Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/groupchatthreadeventlistener-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEvent":{"url":"\/documentation\/easechatuikit\/groupchatthreadevent","title":"GroupChatThreadEvent","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupChatThreadEvent"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEvent"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onGroupChatThreadEventOccurWithType:event:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"onGroupChatThreadEventOccurWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GroupChatThreadEventType","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"kind":"identifier","text":"event:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMChatThreadEvent","text":"EMChatThreadEvent","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"event"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"GroupChatThreadEventType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/navigatorTitle","value":[{"text":"GroupChatThreadEventType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupChatThreadEventOccur(type:event:)\/title","op":"replace","value":"onGroupChatThreadEventOccurWithType:event:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupChatThreadEventOccur(type:event:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onGroupChatThreadEventOccurWithType:event:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"},{"value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}