{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onGroupEventDidChanged"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"users","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"event","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent","type":"reference","isActive":true}]}]},{"name":"groupId","content":[{"inlineContent":[{"type":"text","text":"The id of the group."}],"type":"paragraph"}]},{"name":"users","content":[{"type":"paragraph","inlineContent":[{"text":"[UserId].","type":"text"}]}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupEventDidChanged(event:groupId:users:)"},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onGroupEventDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"users","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"title":"onGroupEventDidChanged(event:groupId:users:)","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)onGroupEventDidChangedWithEvent:groupId:users:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"onGroupEventDidChangedWithEvent:groupId:users:","kind":"identifier"}],"extendedModule":"EaseChatUIKit"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"When a event of group changes on other devices","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupeventdidchanged(event:groupid:users:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupeventdidchanged(event:groupid:users:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MultiDeviceListener-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onGroupEventDidChanged(event:groupId:users:)":{"role":"symbol","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/ongroupeventdidchanged(event:groupid:users:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onGroupEventDidChanged(event:groupId:users:)","type":"topic","title":"onGroupEventDidChanged(event:groupId:users:)","abstract":[{"type":"text","text":"When a event of group changes on other devices"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onGroupEventDidChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"users","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"onGroupEventDidChangedWithEvent:groupId:users:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceEvent":{"title":"MultiDeviceEvent","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceEvent","kind":"identifier"}],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/MultiDeviceListener-Implementations":{"title":"MultiDeviceListener Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MultiDeviceListener-Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/multidevicelistener-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"onGroupEventDidChangedWithEvent:groupId:users:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onGroupEventDidChangedWithEvent:groupId:users:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onGroupEventDidChangedWithEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EMMultiDevicesEvent","preciseIdentifier":"c:@E@EMMultiDevicesEvent","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"groupId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"users:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"users"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onGroupEventDidChangedWithEvent:groupId:users:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupEventDidChanged(event:groupId:users:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"onGroupEventDidChangedWithEvent:groupId:users:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onGroupEventDidChanged(event:groupId:users:)\/fragments"},{"value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"kind":"identifier","text":"MessageListViewModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"}]}]}