{"metadata":{"title":"onInputBoxEventsOccur(action:attributeText:)","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageInputBarActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"attributeText","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?)","kind":"text"}],"roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)onInputBoxEventsOccurWithAction:attributeText:"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onInputBoxEventsOccur(action:attributeText:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"kind":"text","text":" "},{"text":"type","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType"},{"kind":"text","text":", "},{"text":"attributeText","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType"}],"type":"paragraph"}],"name":"type"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"NSAttributedString of textfield."}]}],"name":"type"}],"kind":"parameters"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/oninputboxeventsoccur(action:attributetext:)"]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/oninputboxeventsoccur(action:attributetext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"The method will call on input box event occur."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBarActionType":{"role":"symbol","abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"title":"MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageInputBarActionType","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/messageinputbaractiontype","navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onInputBoxEventsOccur(action:attributeText:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":", "},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?)"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/oninputboxeventsoccur(action:attributetext:)","kind":"symbol","title":"onInputBoxEventsOccur(action:attributeText:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"abstract":[{"text":"The method will call on input box event occur.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onInputBoxEventsOccur(action:attributeText:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/MessageListViewActionEventsDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","title":"MessageListViewActionEventsDelegate Implementations","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributeText:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"text":" *) ","kind":"text"},{"text":"attributeText","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"MessageInputBarActionType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/fragments","value":[{"text":"MessageInputBarActionType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/navigatorTitle","value":[{"kind":"identifier","text":"MessageInputBarActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onInputBoxEventsOccur(action:attributeText:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","op":"replace","value":"MessageListViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}