{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageListLoadMore","kind":"identifier"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageListLoadMore()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"MessageListViewActionEventsDelegate.onMessageListLoadMore()"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagelistloadmore()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagelistloadmore()"]}],"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","navigatorTitle":[{"kind":"identifier","text":"onMessageListLoadMore"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)onMessageListLoadMore","role":"symbol","title":"onMessageListLoadMore()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageListLoadMore"},{"text":"()","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/MessageListViewActionEventsDelegate-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","kind":"article","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations","role":"collectionGroup","title":"MessageListViewActionEventsDelegate Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListViewModel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","navigatorTitle":[{"text":"MessageListViewModel","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel","role":"symbol","title":"MessageListViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onMessageListLoadMore()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageListLoadMore","kind":"identifier"},{"kind":"text","text":"()"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagelistloadmore()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageListLoadMore()","title":"onMessageListLoadMore()","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"onMessageListLoadMore","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"onMessageListLoadMore","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageListLoadMore","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onMessageListLoadMore","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"op":"replace","value":[{"kind":"identifier","text":"MessageListViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageListLoadMore()\/title","value":"onMessageListLoadMore","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageListLoadMore","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageListLoadMore()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}