{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageReactionChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"changes"},{"kind":"text","text":": ["},{"text":"MessageReactionChange","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","type":"reference","isActive":true}]}],"name":"changes"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReactionChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changes"},{"text":": [","kind":"text"},{"text":"MessageReactionChange","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"text":"])","kind":"text"}],"symbolKind":"method","role":"symbol","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)onMessageReactionChangedWithChanges:","title":"onMessageReactionChanged(changes:)","roleHeading":"Instance Method","navigatorTitle":[{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"abstract":[{"type":"text","text":"When reaction of message changed."}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageReactionChanged(changes:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagereactionchanged(changes:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagereactionchanged(changes:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/ChatResponseListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations","kind":"article","title":"ChatResponseListener Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/chatresponselistener-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionChange":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionChange","type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageReactionChange","kind":"identifier"}],"kind":"symbol","abstract":[],"title":"MessageReactionChange","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReactionChange","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagereactionchange"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onMessageReactionChanged(changes:)":{"abstract":[{"text":"When reaction of message changed.","type":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagereactionchanged(changes:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageReactionChanged(changes:)","title":"onMessageReactionChanged(changes:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageReactionChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"changes"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MessageReactionChange","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"kind":"symbol","title":"MessageListViewModel","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","url":"\/documentation\/easechatuikit\/messagelistviewmodel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"text":"MessageListViewModel","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"onMessageReactionChangedWithChanges:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<EMMessageReactionChange *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"changes","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageReactionChanged(changes:)\/title","value":"onMessageReactionChangedWithChanges:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageReactionChanged(changes:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","op":"replace","value":"MessageListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"kind":"identifier","text":"MessageListViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}