{"metadata":{"symbolKind":"method","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)onMessageStickiedTopWithConversationId:messageId:operation:info:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageStickiedTop","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa","text":"MessagePinOperation"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa","kind":"typeIdentifier","text":"MessagePinInfo"},{"text":")","kind":"text"}],"title":"onMessageStickiedTop(conversationId:messageId:operation:info:)","navigatorTitle":[{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:messageId:operation:info:"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageStickiedTop(conversationId:messageId:operation:info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When message stickied top the method called."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageStickiedTop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagePinOperation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinOperation","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa"},{"text":", ","kind":"text"},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa","text":"MessagePinInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinInfo","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"conversationId","content":[{"inlineContent":[{"type":"text","text":"ID of the conversation"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"ID of the message.","type":"text"}]}],"name":"messageId"},{"name":"operation","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinOperation"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinInfo"}]}],"name":"info"}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagestickiedtop(conversationid:messageid:operation:info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagestickiedtop(conversationid:messageid:operation:info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessagePinInfo":{"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePinInfo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagePinInfo"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinInfo","url":"\/documentation\/easechatuikit\/messagepininfo","title":"MessagePinInfo","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onMessageStickiedTop(conversationId:messageId:operation:info:)":{"abstract":[{"text":"When message stickied top the method called.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageStickiedTop(conversationId:messageId:operation:info:)","role":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageStickiedTop"},{"kind":"text","text":"("},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa","kind":"typeIdentifier","text":"MessagePinOperation"},{"kind":"text","text":", "},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessagePinInfo","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onMessageStickiedTopWithConversationId:messageId:operation:info:","kind":"identifier"}],"title":"onMessageStickiedTop(conversationId:messageId:operation:info:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagestickiedtop(conversationid:messageid:operation:info:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/ChatResponseListener-Implementations":{"type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/ChatResponseListener-Implementations","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/chatresponselistener-implementations","title":"ChatResponseListener Implementations","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessagePinOperation":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinOperation","role":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePinOperation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessagePinOperation"}],"title":"MessagePinOperation","url":"\/documentation\/easechatuikit\/messagepinoperation","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"onMessageStickiedTopWithConversationId:messageId:operation:info:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageStickiedTopWithConversationId:messageId:operation:info:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onMessageStickiedTopWithConversationId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"conversationId","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageId:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"messageId"},{"text":" ","kind":"text"},{"text":"operation:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@EMMessagePinOperation","text":"EMMessagePinOperation"},{"kind":"text","text":") "},{"text":"operation","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)EMMessagePinInfo","kind":"typeIdentifier","text":"EMMessagePinInfo"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"onMessageStickiedTopWithConversationId:messageId:operation:info:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onMessageStickiedTopWithConversationId:messageId:operation:info:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageStickiedTop(conversationId:messageId:operation:info:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}