{"kind":"symbol","metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"onMessageReactionClicked(reaction:entity:)","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageReactionClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageReaction","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":")"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)onMessageReactionClickedWithReaction:entity:","symbolKind":"method"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageReactionClicked(reaction:entity:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageReactionClicked"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageReaction","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona"},{"kind":"text","text":"?, "},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","text":"MessageEntity"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","type":"reference"},{"type":"text","text":" object,if nil is "},{"type":"codeVoice","code":"..."},{"type":"text","text":" clicked."}]}],"name":"reaction"},{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","type":"reference","isActive":true}],"type":"paragraph"}],"name":"entity"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagereactionclicked(reaction:entity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagereactionclicked(reaction:entity:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Message reaction&"},{"type":"codeVoice","code":"..."},{"text":" clicked.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/MessageListViewActionEventsDelegate-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/MessageListViewActionEventsDelegate-Implementations","kind":"article","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/messagelistviewactioneventsdelegate-implementations","role":"collectionGroup","title":"MessageListViewActionEventsDelegate Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageListViewModel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","navigatorTitle":[{"text":"MessageListViewModel","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/messagelistviewmodel","role":"symbol","title":"MessageListViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/onMessageReactionClicked(reaction:entity:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageReactionClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageReaction","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"entity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/onmessagereactionclicked(reaction:entity:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/onMessageReactionClicked(reaction:entity:)","kind":"symbol","title":"onMessageReactionClicked(reaction:entity:)","type":"topic","role":"symbol","navigatorTitle":[{"text":"onMessageReactionClickedWithReaction:entity:","kind":"identifier"}],"abstract":[{"type":"text","text":"Message reaction&"},{"type":"codeVoice","code":"..."},{"text":" clicked.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReaction":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReaction"}],"kind":"symbol","abstract":[],"title":"MessageReaction","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","navigatorTitle":[{"kind":"identifier","text":"MessageReaction"}],"url":"\/documentation\/easechatuikit\/messagereaction","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","title":"MessageEntity","url":"\/documentation\/easechatuikit\/messageentity","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageEntity"}],"kind":"symbol","navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onMessageReactionClickedWithReaction:entity:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onMessageReactionClickedWithReaction:entity:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onMessageReactionClickedWithReaction:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMMessageReaction","text":"EMMessageReaction","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reaction"},{"kind":"text","text":" "},{"text":"entity:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","text":"MessageEntity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"entity"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"MessageListViewModel","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title"},{"value":[{"kind":"identifier","text":"MessageListViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageReactionClicked(reaction:entity:)\/title","value":"onMessageReactionClickedWithReaction:entity:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1onMessageReactionClicked(reaction:entity:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageReactionClickedWithReaction:entity:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title","op":"replace","value":"MessageEntity"},{"value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments"}]}]}