{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageListViewModel(im)pinAlertWithInfo:operation:","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","title":"pinAlert(info:operation:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinAlert"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePinInfo","preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa","text":"MessagePinOperation","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"pinAlertWithInfo:operation:","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/pinAlert(info:operation:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/pinalert(info:operation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/pinalert(info:operation:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pinAlert"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinInfo","text":"MessagePinInfo","preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinOperation","text":"MessagePinOperation","preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessagePinOperation":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinOperation","role":"symbol","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePinOperation","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MessagePinOperation"}],"title":"MessagePinOperation","url":"\/documentation\/easechatuikit\/messagepinoperation","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/pinAlert(info:operation:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinAlert","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"text":"MessagePinInfo","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit14MessagePinInfoa"},{"kind":"text","text":", "},{"text":"operation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessagePinOperation","preciseIdentifier":"s:13EaseChatUIKit19MessagePinOperationa"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/pinAlert(info:operation:)","abstract":[],"title":"pinAlert(info:operation:)","url":"\/documentation\/easechatuikit\/messagelistviewmodel\/pinalert(info:operation:)","navigatorTitle":[{"kind":"identifier","text":"pinAlertWithInfo:operation:"}],"kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessagePinInfo":{"type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessagePinInfo","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessagePinInfo"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessagePinInfo","url":"\/documentation\/easechatuikit\/messagepininfo","title":"MessagePinInfo","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"url":"\/documentation\/easechatuikit\/messagelistviewmodel","title":"MessageListViewModel","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewModel"}],"navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"pinAlertWithInfo:operation:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"pinAlertWithInfo:operation:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"pinAlertWithInfo:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMMessagePinInfo","text":"EMMessagePinInfo","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"operation:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@EMMessagePinOperation","kind":"typeIdentifier","text":"EMMessagePinOperation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"operation"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1pinAlert(info:operation:)\/title","value":"pinAlertWithInfo:operation:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1pinAlert(info:operation:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"pinAlertWithInfo:operation:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/navigatorTitle","value":[{"text":"MessageListViewModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}