{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willSendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/willsendmessage(attributetext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagelistviewmodel\/willsendmessage(attributetext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/willSendMessage(attributeText:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"willSendMessageWithAttributeText:"}],"role":"symbol","title":"willSendMessage(attributeText:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willSendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageListViewModel(im)willSendMessageWithAttributeText:","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel/willSendMessage(attributeText:)":{"role":"symbol","title":"willSendMessage(attributeText:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willSendMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel\/willSendMessage(attributeText:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willSendMessageWithAttributeText:"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel\/willsendmessage(attributetext:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewModel":{"role":"symbol","title":"MessageListViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageListViewModel"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListViewModel"}],"url":"\/documentation\/easechatuikit\/messagelistviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"willSendMessageWithAttributeText:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willSendMessageWithAttributeText:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"willSendMessageWithAttributeText:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"attributeText"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1willSendMessage(attributeText:)\/title","value":"willSendMessageWithAttributeText:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel~1willSendMessage(attributeText:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willSendMessageWithAttributeText:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/title","value":"MessageListViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewModel\/fragments","value":[{"kind":"identifier","text":"MessageListViewModel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}