{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"collectionView(_:layout:sizeForItemAt:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageReactionView(im)collectionView:layout:sizeForItemAtIndexPath:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/UICollectionViewDelegateFlowLayout-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"collectionViewLayout"},{"kind":"text","text":": "},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":" "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}]}]}],"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UICollectionViewDelegateFlowLayout.collectionView(_:layout:sizeForItemAt:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)"]},{"paths":["\/documentation\/easechatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionView/UICollectionViewDelegateFlowLayout-Implementations":{"abstract":[],"role":"collectionGroup","title":"UICollectionViewDelegateFlowLayout Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/UICollectionViewDelegateFlowLayout-Implementations","type":"topic","url":"\/documentation\/easechatuikit\/messagereactionview\/uicollectionviewdelegateflowlayout-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionView":{"type":"topic","url":"\/documentation\/easechatuikit\/messagereactionview","kind":"symbol","title":"MessageReactionView","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MessageReactionView","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"MessageReactionView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionView/collectionView(_:layout:sizeForItemAt:)":{"url":"\/documentation\/easechatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)","title":"collectionView(_:layout:sizeForItemAt:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"layout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayout","text":"UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sizeForItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"collectionView:layout:sizeForItemAtIndexPath:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"collectionView"},{"text":" ","kind":"text"},{"text":"layout:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionViewLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"text":" *) ","kind":"text"},{"text":"collectionViewLayout","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeForItemAtIndexPath:"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"MessageReactionView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView\/fragments","value":[{"text":"MessageReactionView","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/title","value":"collectionView:layout:sizeForItemAtIndexPath:"},{"value":[{"kind":"text","text":"- "},{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}