{"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"UICollectionViewDelegateFlowLayout Implementations","role":"collectionGroup","roleHeading":"API Collection"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/UICollectionViewDelegateFlowLayout-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagereactionview\/uicollectionviewdelegateflowlayout-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagereactionview\/uicollectionviewdelegateflowlayout-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView"]]},"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionView":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView","abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionview","navigatorTitle":[{"kind":"identifier","text":"MessageReactionView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageReactionView"}],"kind":"symbol","type":"topic","title":"MessageReactionView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionView/collectionView(_:layout:minimumLineSpacingForSectionAt:)":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":": "},{"text":"UICollectionViewLayout","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minimumLineSpacingForSectionAt"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","role":"symbol","title":"collectionView(_:layout:minimumLineSpacingForSectionAt:)","url":"\/documentation\/easechatuikit\/messagereactionview\/collectionview(_:layout:minimumlinespacingforsectionat:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionView/collectionView(_:layout:sizeForItemAt:)":{"title":"collectionView(_:layout:sizeForItemAt:)","type":"topic","navigatorTitle":[{"text":"collectionView:layout:sizeForItemAtIndexPath:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","text":"UICollectionViewLayout"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sizeForItemAt"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionview\/collectionview(_:layout:sizeforitemat:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionView/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)":{"abstract":[],"type":"topic","navigatorTitle":[{"text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"text":": ","kind":"text"},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minimumInteritemSpacingForSectionAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","role":"symbol","title":"collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","url":"\/documentation\/easechatuikit\/messagereactionview\/collectionview(_:layout:minimuminteritemspacingforsectionat:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumInteritemSpacingForSectionAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:minimumLineSpacingForSectionAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionView\/collectionView(_:layout:sizeForItemAt:)"],"generated":true,"title":"Instance Methods"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView\/title","op":"replace","value":"MessageReactionView"},{"op":"replace","value":[{"text":"MessageReactionView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumLineSpacingForSectionAt:)\/title","value":"collectionView:layout:minimumLineSpacingForSectionAtIndex:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumLineSpacingForSectionAt:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:minimumLineSpacingForSectionAtIndex:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/title","value":"collectionView:layout:sizeForItemAtIndexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:sizeForItemAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:layout:sizeForItemAtIndexPath:"}]},{"value":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:minimumInteritemSpacingForSectionAtIndex:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionView~1collectionView(_:layout:minimumInteritemSpacingForSectionAt:)\/fragments"}]}]}