{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationservice\/bindconversationeventslistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationservice\/bindconversationeventslistener(listener:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bindConversationEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationServiceListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"code":"ChannelServiceListener","type":"codeVoice"}]}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"bindConversationEventsListener","kind":"identifier"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener","text":"ConversationServiceListener"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationService(im)bindConversationEventsListenerWithListener:","symbolKind":"method","roleHeading":"Instance Method","title":"bindConversationEventsListener(listener:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService"]]},"abstract":[{"type":"text","text":"Bind channel changed listener"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/bindConversationEventsListener(listener:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/bindConversationEventsListener(listener:)":{"url":"\/documentation\/easechatuikit\/conversationservice\/bindconversationeventslistener(listener:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/bindConversationEventsListener(listener:)","title":"bindConversationEventsListener(listener:)","abstract":[{"type":"text","text":"Bind channel changed listener"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bindConversationEventsListener"},{"kind":"text","text":"("},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ConversationServiceListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationServiceListener"},{"text":")","kind":"text"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceListener":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationServiceListener"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceListener","url":"\/documentation\/easechatuikit\/conversationservicelistener","navigatorTitle":[{"text":"ConversationServiceListener","kind":"identifier"}],"abstract":[],"type":"topic","title":"ConversationServiceListener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationService"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","url":"\/documentation\/easechatuikit\/conversationservice","navigatorTitle":[{"text":"ConversationService","kind":"identifier"}],"abstract":[],"type":"topic","title":"ConversationService"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"bindConversationEventsListenerWithListener:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"bindConversationEventsListenerWithListener:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ConversationServiceListener","text":"id<ConversationServiceListener>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1bindConversationEventsListener(listener:)\/title","value":"bindConversationEventsListenerWithListener:"},{"value":[{"text":"- ","kind":"text"},{"text":"bindConversationEventsListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1bindConversationEventsListener(listener:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/title","value":"ConversationServiceListener","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceListener\/fragments","value":[{"text":"ConversationServiceListener","kind":"identifier"}]},{"op":"replace","value":"ConversationService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/title"},{"value":[{"text":"ConversationService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}