{"sections":[],"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationService(im)fetchPinnedConversationsWithCursor:pageSize:completion:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchPinnedConversations"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cursor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit12CursorResulta","text":"CursorResult","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"ConversationInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","kind":"typeIdentifier"},{"text":">?, ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"navigatorTitle":[{"text":"fetchPinnedConversationsWithCursor:pageSize:completion:","kind":"identifier"}],"role":"symbol","title":"fetchPinnedConversations(cursor:pageSize:completion:)","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationservice\/fetchpinnedconversations(cursor:pagesize:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationservice\/fetchpinnedconversations(cursor:pagesize:completion:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fetchPinnedConversations","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cursor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CursorResult","preciseIdentifier":"s:13EaseChatUIKit12CursorResulta","kind":"typeIdentifier","text":"CursorResult"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","text":"ConversationInfo"},{"kind":"text","text":">?, "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"cursor","content":[{"type":"paragraph","inlineContent":[{"text":"Paging cursor.","type":"text"}]}]},{"name":"pageSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size number of current page."}]}]},{"content":[{"inlineContent":[{"text":"Callback, including session list results and error information. If successful, the session list will be returned. If failed, error information will be returned.","type":"text"}],"type":"paragraph"}],"name":"completion"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchPinnedConversations(cursor:pageSize:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Fetch pinned conversations from server.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CursorResult":{"navigatorTitle":[{"kind":"identifier","text":"CursorResult"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CursorResult"}],"abstract":[],"url":"\/documentation\/easechatuikit\/cursorresult","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CursorResult","kind":"symbol","type":"topic","title":"CursorResult","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/fetchPinnedConversations(cursor:pageSize:completion:)":{"navigatorTitle":[{"text":"fetchPinnedConversationsWithCursor:pageSize:completion:","kind":"identifier"}],"required":true,"abstract":[{"text":"Fetch pinned conversations from server.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/fetchPinnedConversations(cursor:pageSize:completion:)","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/fetchpinnedconversations(cursor:pagesize:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"fetchPinnedConversations","kind":"identifier"},{"kind":"text","text":"("},{"text":"cursor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"pageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:13EaseChatUIKit12CursorResulta","text":"CursorResult","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"ConversationInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo"},{"text":">?, ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","title":"fetchPinnedConversations(cursor:pageSize:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService":{"type":"topic","title":"ConversationService","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationService"}],"navigatorTitle":[{"text":"ConversationService","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/conversationservice"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"navigatorTitle":[{"kind":"identifier","text":"ConversationInfo"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/conversationinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","kind":"symbol","type":"topic","title":"ConversationInfo","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"url":"\/documentation\/easechatuikit\/chaterror","role":"symbol","abstract":[],"title":"ChatError","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"}],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"fetchPinnedConversationsWithCursor:pageSize:completion:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fetchPinnedConversationsWithCursor:pageSize:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"fetchPinnedConversationsWithCursor:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cursor"},{"kind":"text","text":" "},{"text":"pageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"uint8_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t"},{"text":") ","kind":"text"},{"text":"pageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)EMCursorResult","text":"EMCursorResult<ConversationInfo *>"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"EMError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"fetchPinnedConversationsWithCursor:pageSize:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchPinnedConversations(cursor:pageSize:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1fetchPinnedConversations(cursor:pageSize:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"fetchPinnedConversationsWithCursor:pageSize:completion:","kind":"identifier"}]},{"value":"ConversationService","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/title"},{"value":[{"text":"ConversationService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/fragments"},{"value":"ConversationInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","value":[{"kind":"identifier","text":"ConversationInfo"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}