{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"markAllMessagesAsRead"},{"kind":"text","text":"("},{"kind":"externalParam","text":"conversationId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/markAllMessagesAsRead(conversationId:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService"]]},"sections":[],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationService(im)markAllMessagesAsReadWithConversationId:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"markAllMessagesAsRead","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"title":"markAllMessagesAsRead(conversationId:)","navigatorTitle":[{"text":"markAllMessagesAsReadWithConversationId:","kind":"identifier"}],"role":"symbol","symbolKind":"method","required":true},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Mark all of the history messages as already read."}],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationservice\/markallmessagesasread(conversationid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationservice\/markallmessagesasread(conversationid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationService"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/conversationservice","role":"symbol","title":"ConversationService","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","navigatorTitle":[{"kind":"identifier","text":"ConversationService"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/markAllMessagesAsRead(conversationId:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/markAllMessagesAsRead(conversationId:)","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/markallmessagesasread(conversationid:)","navigatorTitle":[{"text":"markAllMessagesAsReadWithConversationId:","kind":"identifier"}],"required":true,"abstract":[{"type":"text","text":"Mark all of the history messages as already read."}],"title":"markAllMessagesAsRead(conversationId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"markAllMessagesAsRead","kind":"identifier"},{"text":"(","kind":"text"},{"text":"conversationId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"markAllMessagesAsReadWithConversationId:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"markAllMessagesAsReadWithConversationId:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"markAllMessagesAsReadWithConversationId:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"conversationId","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"ConversationService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/fragments","value":[{"text":"ConversationService","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ConversationService","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1markAllMessagesAsRead(conversationId:)\/title","op":"replace","value":"markAllMessagesAsReadWithConversationId:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"markAllMessagesAsReadWithConversationId:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1markAllMessagesAsRead(conversationId:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}