{"variants":[{"paths":["\/documentation\/easechatuikit\/conversationservice\/registeremergencylistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationservice\/registeremergencylistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ConversationEmergencyListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"kind":"text","text":")"}],"title":"registerEmergencyListener(listener:)","navigatorTitle":[{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"required":true,"externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationService(im)registerEmergencyListenerWithListener:","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/registerEmergencyListener(listener:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Register emergency listener"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerEmergencyListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener","text":"ConversationEmergencyListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","isActive":true}]}],"name":"listener"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationService"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/conversationservice","role":"symbol","title":"ConversationService","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService","navigatorTitle":[{"kind":"identifier","text":"ConversationService"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"url":"\/documentation\/easechatuikit\/conversationemergencylistener","kind":"symbol","role":"symbol","title":"ConversationEmergencyListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationEmergencyListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationService/registerEmergencyListener(listener:)":{"role":"symbol","abstract":[{"type":"text","text":"Register emergency listener"}],"navigatorTitle":[{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"title":"registerEmergencyListener(listener:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationService\/registerEmergencyListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"registerEmergencyListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/conversationservice\/registeremergencylistener(listener:)","required":true,"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"registerEmergencyListenerWithListener:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<ConversationEmergencyListener>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","type":"reference"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","value":"ConversationService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/fragments","value":[{"text":"ConversationService","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"ConversationService"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/title","value":"ConversationEmergencyListener"},{"value":[{"text":"ConversationEmergencyListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/navigatorTitle","value":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"op":"replace"},{"value":"registerEmergencyListenerWithListener:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1registerEmergencyListener(listener:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"registerEmergencyListenerWithListener:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationService~1registerEmergencyListener(listener:)\/fragments"}]}]}