{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListItemActionClosure","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea","kind":"typeIdentifier","text":"ContactListItemActionClosure"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","externalID":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol(py)actionClosure","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"actionClosure"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea","text":"ContactListItemActionClosure"},{"text":"?","kind":"text"}],"title":"actionClosure","navigatorTitle":[{"kind":"identifier","text":"actionClosure"}],"role":"symbol","symbolKind":"property","required":true},"abstract":[{"type":"text","text":"When the cell clicked,callback."}],"variants":[{"paths":["\/documentation\/easechatuikit\/contactlistheaderitemprotocol\/actionclosure"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactlistheaderitemprotocol\/actionclosure"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol\/actionClosure","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItemProtocol/actionClosure":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"actionClosure","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit28ContactListItemActionClosurea","kind":"typeIdentifier","text":"ContactListItemActionClosure"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol\/actionClosure","navigatorTitle":[{"kind":"identifier","text":"actionClosure"}],"title":"actionClosure","url":"\/documentation\/easechatuikit\/contactlistheaderitemprotocol\/actionclosure","role":"symbol","kind":"symbol","required":true,"abstract":[{"text":"When the cell clicked,callback.","type":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItemProtocol":{"navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol","abstract":[{"text":"A protocol of the contact list item.","type":"text"}],"title":"ContactListHeaderItemProtocol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"role":"symbol","url":"\/documentation\/easechatuikit\/contactlistheaderitemprotocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListItemActionClosure":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListItemActionClosure","url":"\/documentation\/easechatuikit\/contactlistitemactionclosure","title":"ContactListItemActionClosure","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ContactListItemActionClosure","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ContactListItemActionClosure","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"actionClosure","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"actionClosure","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"actionClosure"},{"text":")(","kind":"text"},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol","kind":"typeIdentifier","text":"id<ContactListHeaderItemProtocol>"},{"text":" ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":");"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol~1actionClosure\/title","op":"replace","value":"actionClosure"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol~1actionClosure\/fragments","value":[{"text":"actionClosure","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol\/title","value":"ContactListHeaderItemProtocol","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol\/navigatorTitle","value":[{"text":"ContactListHeaderItemProtocol","kind":"identifier"}]}]}]}