{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ChatFileMessageCell","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FileMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)FileMessageCell","kind":"typeIdentifier","text":"FileMessageCell"},{"kind":"text","text":".Type"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/chatfilemessagecell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/chatfilemessagecell"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatFileMessageCell","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)ChatFileMessageCell","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatFileMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FileMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)FileMessageCell","kind":"typeIdentifier"},{"kind":"text","text":".Type"}],"title":"ChatFileMessageCell","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"ChatFileMessageCell"}],"modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"type":"topic","role":"symbol","title":"ComponentsRegister","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"url":"\/documentation\/easechatuikit\/componentsregister","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/FileMessageCell":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FileMessageCell"}],"navigatorTitle":[{"text":"FileMessageCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FileMessageCell","title":"FileMessageCell","url":"\/documentation\/easechatuikit\/filemessagecell","kind":"symbol","type":"topic","role":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatFileMessageCell":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatFileMessageCell","kind":"symbol","title":"ChatFileMessageCell","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatFileMessageCell"},{"text":": ","kind":"text"},{"text":"FileMessageCell","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)FileMessageCell"},{"text":".Type","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/componentsregister\/chatfilemessagecell","navigatorTitle":[{"text":"ChatFileMessageCell","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"ChatFileMessageCell","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ChatFileMessageCell","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:*QO","text":"Class"},{"text":" ","kind":"text"},{"text":"ChatFileMessageCell","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","op":"replace","value":[{"text":"ComponentsRegister","kind":"identifier"}]},{"op":"replace","value":"FileMessageCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FileMessageCell\/title"},{"value":[{"text":"FileMessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FileMessageCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatFileMessageCell\/title","value":"ChatFileMessageCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatFileMessageCell\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatFileMessageCell"}]}]}]}