{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/chatcustommessagecell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/chatcustommessagecell"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)ChatCustomMessageCell","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"ChatCustomMessageCell","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ChatCustomMessageCell","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CustomMessageCell","text":"CustomMessageCell","kind":"typeIdentifier"},{"kind":"text","text":".Type"}],"title":"ChatCustomMessageCell","role":"symbol","modules":[{"name":"EaseChatUIKit"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatCustomMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomMessageCell","text":"CustomMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CustomMessageCell"},{"text":".Type","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"url":"\/documentation\/easechatuikit\/componentsregister","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"title":"ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CustomMessageCell":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CustomMessageCell","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CustomMessageCell","navigatorTitle":[{"kind":"identifier","text":"CustomMessageCell"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/custommessagecell","role":"symbol","title":"CustomMessageCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatCustomMessageCell":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ChatCustomMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CustomMessageCell","text":"CustomMessageCell"},{"kind":"text","text":".Type"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatCustomMessageCell","type":"topic","navigatorTitle":[{"text":"ChatCustomMessageCell","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/componentsregister\/chatcustommessagecell","title":"ChatCustomMessageCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"ChatCustomMessageCell","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ChatCustomMessageCell","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"text":"Class","preciseIdentifier":"c:*QO","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"ChatCustomMessageCell","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","value":[{"text":"ComponentsRegister","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"CustomMessageCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomMessageCell\/title"},{"value":[{"kind":"identifier","text":"CustomMessageCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CustomMessageCell\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatCustomMessageCell\/title","value":"ChatCustomMessageCell","op":"replace"},{"value":[{"text":"ChatCustomMessageCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatCustomMessageCell\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}