{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAudioMessageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AudioMessageCell","text":"AudioMessageCell"},{"kind":"text","text":".Type"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/componentsregister\/chataudiomessagecell"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/componentsregister\/chataudiomessagecell"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAudioMessageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AudioMessageCell"},{"kind":"text","text":".Type"}],"title":"ChatAudioMessageCell","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)ChatAudioMessageCell","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ChatAudioMessageCell"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"role":"symbol","title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/easechatuikit\/componentsregister"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatAudioMessageCell":{"role":"symbol","title":"ChatAudioMessageCell","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAudioMessageCell"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AudioMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AudioMessageCell"},{"kind":"text","text":".Type"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatAudioMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatAudioMessageCell"}],"url":"\/documentation\/easechatuikit\/componentsregister\/chataudiomessagecell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioMessageCell":{"role":"symbol","title":"AudioMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AudioMessageCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageCell","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AudioMessageCell"}],"url":"\/documentation\/easechatuikit\/audiomessagecell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ChatAudioMessageCell"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatAudioMessageCell"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatAudioMessageCell"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/title","value":"ChatAudioMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatAudioMessageCell\/fragments","value":[{"kind":"identifier","text":"ChatAudioMessageCell"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageCell\/title","value":"AudioMessageCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageCell\/fragments","value":[{"kind":"identifier","text":"AudioMessageCell"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}