{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)ChatTextMessageCell","role":"symbol","title":"ChatTextMessageCell","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatTextMessageCell","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TextMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)TextMessageCell"},{"text":".Type","kind":"text"}],"navigatorTitle":[{"text":"ChatTextMessageCell","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatTextMessageCell"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"ChatTextMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)TextMessageCell","kind":"typeIdentifier","text":"TextMessageCell"},{"kind":"text","text":".Type"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/chattextmessagecell"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/chattextmessagecell"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TextMessageCell":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TextMessageCell","kind":"symbol","title":"TextMessageCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TextMessageCell"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/textmessagecell","navigatorTitle":[{"text":"TextMessageCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"type":"topic","role":"symbol","title":"ComponentsRegister","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"url":"\/documentation\/easechatuikit\/componentsregister","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ChatTextMessageCell":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ChatTextMessageCell","kind":"symbol","title":"ChatTextMessageCell","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatTextMessageCell","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TextMessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)TextMessageCell"},{"text":".Type","kind":"text"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/componentsregister\/chattextmessagecell","navigatorTitle":[{"text":"ChatTextMessageCell","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"ChatTextMessageCell","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ChatTextMessageCell"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatTextMessageCell"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"TextMessageCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextMessageCell\/title"},{"value":[{"text":"TextMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TextMessageCell\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister","op":"replace"},{"value":[{"kind":"identifier","text":"ComponentsRegister"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/title","value":"ChatTextMessageCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ChatTextMessageCell\/fragments","op":"replace","value":[{"text":"ChatTextMessageCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}