{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactInfoController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController","text":"ContactInfoViewController"},{"kind":"text","text":".Type"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/componentsregister\/contactinfocontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/componentsregister\/contactinfocontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactInfoController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Contact detail info of the group."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactInfoController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactInfoViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController"},{"kind":"text","text":".Type"}],"title":"ContactInfoController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)ContactInfoController","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ContactInfoController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ContactInfoController":{"role":"symbol","title":"ContactInfoController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactInfoController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactInfoViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController"},{"kind":"text","text":".Type"}],"abstract":[{"type":"text","text":"Contact detail info of the group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ContactInfoController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactInfoController"}],"url":"\/documentation\/easechatuikit\/componentsregister\/contactinfocontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"role":"symbol","title":"ContactInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactInfoViewController"}],"abstract":[{"type":"text","text":"This is the documentation comment for the "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" class."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"role":"symbol","title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/easechatuikit\/componentsregister"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ContactInfoController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ContactInfoController"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactInfoController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactInfoController\/title","value":"ContactInfoController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ContactInfoController\/fragments","value":[{"kind":"identifier","text":"ContactInfoController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","value":[{"kind":"identifier","text":"ContactInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}