{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationListController","text":"ConversationListController"},{"kind":"text","text":".Type"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/componentsregister\/conversationscontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/componentsregister\/conversationscontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationsController","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Conversation list page controller"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationListController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationListController"},{"kind":"text","text":".Type"}],"title":"ConversationsController","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)ConversationsController","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationsController"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"role":"symbol","title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/easechatuikit\/componentsregister"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/ConversationsController":{"role":"symbol","title":"ConversationsController","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationListController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationListController"},{"kind":"text","text":".Type"}],"abstract":[{"type":"text","text":"Conversation list page controller"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/ConversationsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationsController"}],"url":"\/documentation\/easechatuikit\/componentsregister\/conversationscontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationListController":{"role":"symbol","title":"ConversationListController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationListController"}],"abstract":[{"type":"text","text":"When you"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationListController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationListController"}],"url":"\/documentation\/easechatuikit\/conversationlistcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"ConversationsController"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationsController"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationsController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationsController\/title","value":"ConversationsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1ConversationsController\/fragments","value":[{"kind":"identifier","text":"ConversationsController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/title","value":"ConversationListController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationListController\/fragments","value":[{"kind":"identifier","text":"ConversationListController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}