{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Group detail info view controller."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/groupinfocontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/groupinfocontroller"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupInfoController"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupInfoController"},{"text":": ","kind":"text"},{"text":"GroupInfoViewController","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController"},{"text":".Type","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","title":"GroupInfoController","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"GroupInfoController","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)GroupInfoController","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupInfoController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupInfoViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController"},{"text":".Type","kind":"text"}]},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"type":"topic","role":"symbol","title":"ComponentsRegister","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"url":"\/documentation\/easechatuikit\/componentsregister","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/GroupInfoController":{"abstract":[{"text":"Group detail info view controller.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupInfoController","title":"GroupInfoController","type":"topic","navigatorTitle":[{"text":"GroupInfoController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/componentsregister\/groupinfocontroller","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"GroupInfoController","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupInfoViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController"},{"text":".Type","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoViewController"}],"title":"GroupInfoViewController","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"GroupInfoController"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"GroupInfoController","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":") "},{"text":"Class","kind":"typeIdentifier","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"text":"GroupInfoController","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","value":[{"text":"ComponentsRegister","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupInfoController\/title","value":"GroupInfoController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupInfoController\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupInfoController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","op":"replace","value":"GroupInfoViewController"},{"value":[{"kind":"identifier","text":"GroupInfoViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","op":"replace"}]}]}