{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"abstract":[{"type":"text","text":"Participants controller of the group."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/groupparticipantcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/groupparticipantcontroller"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupParticipantsController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsController"},{"kind":"text","text":".Type"}],"roleHeading":"Instance Property","title":"GroupParticipantController","symbolKind":"property","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)GroupParticipantController","navigatorTitle":[{"text":"GroupParticipantController","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupParticipantController","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantController"},{"kind":"text","text":": "},{"text":"GroupParticipantsController","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController"},{"text":".Type","kind":"text"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"url":"\/documentation\/easechatuikit\/componentsregister","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"title":"ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/GroupParticipantController":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantController"},{"text":": ","kind":"text"},{"text":"GroupParticipantsController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsController","kind":"typeIdentifier"},{"text":".Type","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/GroupParticipantController","title":"GroupParticipantController","url":"\/documentation\/easechatuikit\/componentsregister\/groupparticipantcontroller","role":"symbol","abstract":[{"text":"Participants controller of the group.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"GroupParticipantController"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController":{"abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController","title":"GroupParticipantsController","role":"symbol","url":"\/documentation\/easechatuikit\/groupparticipantscontroller","navigatorTitle":[{"text":"GroupParticipantsController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantsController"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"GroupParticipantController","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"GroupParticipantController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:*QO","text":"Class","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantController"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"value":"ComponentsRegister","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","op":"replace"},{"op":"replace","value":[{"text":"ComponentsRegister","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupParticipantController\/title","op":"replace","value":"GroupParticipantController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1GroupParticipantController\/fragments","value":[{"text":"GroupParticipantController","kind":"identifier"}]},{"value":"GroupParticipantsController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupParticipantsController"}]}]}]}