{"variants":[{"paths":["\/documentation\/easechatuikit\/componentsregister\/joinedgroupscontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/componentsregister\/joinedgroupscontroller"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinedGroupsController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)JoinedGroupsViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController","kind":"typeIdentifier","text":"JoinedGroupsViewController"},{"kind":"text","text":".Type"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)JoinedGroupsController","symbolKind":"property","role":"symbol","title":"JoinedGroupsController","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"JoinedGroupsController"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"JoinedGroupsController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)JoinedGroupsViewController","kind":"typeIdentifier","text":"JoinedGroupsViewController"},{"text":".Type","kind":"text"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/JoinedGroupsController","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"url":"\/documentation\/easechatuikit\/componentsregister","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"title":"ComponentsRegister","abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ComponentsRegister"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/JoinedGroupsController":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/JoinedGroupsController","role":"symbol","title":"JoinedGroupsController","navigatorTitle":[{"kind":"identifier","text":"JoinedGroupsController"}],"url":"\/documentation\/easechatuikit\/componentsregister\/joinedgroupscontroller","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoinedGroupsController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"JoinedGroupsViewController","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)JoinedGroupsViewController"},{"kind":"text","text":".Type"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/JoinedGroupsViewController":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/JoinedGroupsViewController","url":"\/documentation\/easechatuikit\/joinedgroupsviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"JoinedGroupsViewController"}],"navigatorTitle":[{"text":"JoinedGroupsViewController","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","title":"JoinedGroupsViewController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"JoinedGroupsController"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"JoinedGroupsController"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"text":"JoinedGroupsController","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ComponentsRegister","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title"},{"value":[{"kind":"identifier","text":"ComponentsRegister"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","op":"replace"},{"op":"replace","value":"JoinedGroupsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1JoinedGroupsController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1JoinedGroupsController\/fragments","value":[{"text":"JoinedGroupsController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/title","value":"JoinedGroupsViewController"},{"value":[{"kind":"identifier","text":"JoinedGroupsViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1JoinedGroupsViewController\/fragments"}]}]}