{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRenderEntity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":".Type"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/componentsregister\/messagerenderentity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/componentsregister\/messagerenderentity"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageRenderEntity","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message cell render entity."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRenderEntity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":".Type"}],"title":"MessageRenderEntity","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ComponentsRegister(py)MessageRenderEntity","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"MessageRenderEntity"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister":{"role":"symbol","title":"ComponentsRegister","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ComponentsRegister"}],"abstract":[{"type":"text","text":"An object containing UI components that are used through the EaseChatUIKit SDK."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ComponentsRegister"}],"url":"\/documentation\/easechatuikit\/componentsregister"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"role":"symbol","title":"MessageEntity","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageEntity"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageEntity"}],"url":"\/documentation\/easechatuikit\/messageentity"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ComponentsRegister/MessageRenderEntity":{"role":"symbol","title":"MessageRenderEntity","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRenderEntity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":".Type"}],"abstract":[{"type":"text","text":"Message cell render entity."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ComponentsRegister\/MessageRenderEntity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageRenderEntity"}],"url":"\/documentation\/easechatuikit\/componentsregister\/messagerenderentity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"MessageRenderEntity"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"MessageRenderEntity"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"Class","preciseIdentifier":"c:*QO"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageRenderEntity"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/title","value":"ComponentsRegister"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister\/fragments","value":[{"kind":"identifier","text":"ComponentsRegister"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title","value":"MessageEntity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments","value":[{"kind":"identifier","text":"MessageEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessageRenderEntity\/title","value":"MessageRenderEntity"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ComponentsRegister~1MessageRenderEntity\/fragments","value":[{"kind":"identifier","text":"MessageRenderEntity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}