{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"kind":"text","text":" "},{"text":"collectionViewLayout","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UICollectionViewLayout","preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"referenceSizeForFooterInSection"},{"kind":"text","text":" "},{"text":"section","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegateFlowLayout-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UICollectionViewDelegateFlowLayout.collectionView(_:layout:referenceSizeForFooterInSection:)","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"title":"collectionView(_:layout:referenceSizeForFooterInSection:)","role":"symbol","roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"kind":"text","text":", "},{"text":"layout","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayout","kind":"typeIdentifier","text":"UICollectionViewLayout"},{"kind":"text","text":", "},{"text":"referenceSizeForFooterInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageReactionsDetailController(im)collectionView:layout:referenceSizeForFooterInSection:","navigatorTitle":[{"text":"collectionView:layout:referenceSizeForFooterInSection:","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/collectionView(_:layout:referenceSizeForFooterInSection:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/collectionview(_:layout:referencesizeforfooterinsection:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/collectionview(_:layout:referencesizeforfooterinsection:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/collectionView(_:layout:referenceSizeForFooterInSection:)":{"abstract":[],"title":"collectionView(_:layout:referenceSizeForFooterInSection:)","url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/collectionview(_:layout:referencesizeforfooterinsection:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/collectionView(_:layout:referenceSizeForFooterInSection:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"layout"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayout","text":"UICollectionViewLayout","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"referenceSizeForFooterInSection"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionsDetailController"}],"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller","title":"MessageReactionsDetailController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController","abstract":[],"type":"topic","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/UICollectionViewDelegateFlowLayout-Implementations":{"type":"topic","title":"UICollectionViewDelegateFlowLayout Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/uicollectionviewdelegateflowlayout-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UICollectionViewDelegateFlowLayout-Implementations"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"collectionView:layout:referenceSizeForFooterInSection:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"collectionView:layout:referenceSizeForFooterInSection:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"layout:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionViewLayout","text":"UICollectionViewLayout","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"collectionViewLayout"},{"text":" ","kind":"text"},{"kind":"identifier","text":"referenceSizeForFooterInSection:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"section"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"collectionView:layout:referenceSizeForFooterInSection:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1collectionView(_:layout:referenceSizeForFooterInSection:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1collectionView(_:layout:referenceSizeForFooterInSection:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:layout:referenceSizeForFooterInSection:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/title","op":"replace","value":"MessageReactionsDetailController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/fragments","value":[{"text":"MessageReactionsDetailController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}