{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionUsers"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/messageReactionUsers()","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/messagereactionusers()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/messagereactionusers()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"messageReactionUsers","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageReactionUsers","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageReactionsDetailController(im)messageReactionUsers","role":"symbol","symbolKind":"method","title":"messageReactionUsers()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"kind":"symbol","type":"topic","title":"MessageReactionsDetailController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionsDetailController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/messageReactionUsers()":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/messagereactionusers()","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/messageReactionUsers()","role":"symbol","navigatorTitle":[{"text":"messageReactionUsers","kind":"identifier"}],"title":"messageReactionUsers()","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionUsers"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"messageReactionUsers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageReactionUsers"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"messageReactionUsers","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":"MessageReactionsDetailController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/title","op":"replace"},{"op":"replace","value":[{"text":"MessageReactionsDetailController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/fragments"},{"value":"messageReactionUsers","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1messageReactionUsers()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageReactionUsers"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1messageReactionUsers()\/fragments"}]}]}