{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"tableView"},{"text":": ","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"text":"cellForRowAt","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/tableview(_:cellforrowat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/tableview(_:cellforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageReactionsDetailController(im)tableView:cellForRowAtIndexPath:","roleHeading":"Instance Method","title":"tableView(_:cellForRowAt:)","role":"symbol","navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cellForRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/tableView(_:cellForRowAt:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UITableViewDataSource.tableView(_:cellForRowAt:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDataSource-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/tableView(_:cellForRowAt:)":{"navigatorTitle":[{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"title":"tableView(_:cellForRowAt:)","url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/tableview(_:cellforrowat:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/tableView(_:cellForRowAt:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController/UITableViewDataSource-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController\/UITableViewDataSource-Implementations","kind":"article","title":"UITableViewDataSource Implementations","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller\/uitableviewdatasource-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsDetailController":{"url":"\/documentation\/easechatuikit\/messagereactionsdetailcontroller","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsDetailController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsDetailController"}],"kind":"symbol","type":"topic","title":"MessageReactionsDetailController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageReactionsDetailController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"tableView:cellForRowAtIndexPath:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"tableView:"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":" *) "},{"text":"tableView","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cellForRowAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1tableView(_:cellForRowAt:)\/title","value":"tableView:cellForRowAtIndexPath:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController~1tableView(_:cellForRowAt:)\/fragments"},{"op":"replace","value":"MessageReactionsDetailController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsDetailController\/fragments","value":[{"kind":"identifier","text":"MessageReactionsDetailController"}]}]}]}