{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView\/icon","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"icon","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"icon","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImageView","preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit19PinnedIndicatorViewC4iconSo07UIImageF0Cvp"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pinnedindicatorview\/icon"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"icon","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImageView","text":"UIImageView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedIndicatorView":{"title":"PinnedIndicatorView","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PinnedIndicatorView","kind":"identifier"}],"navigatorTitle":[{"text":"PinnedIndicatorView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pinnedindicatorview","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedIndicatorView/icon":{"abstract":[],"title":"icon","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView\/icon","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"icon","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIImageView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImageView"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/pinnedindicatorview\/icon","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"PinnedIndicatorView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView\/title"},{"value":[{"text":"PinnedIndicatorView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PinnedIndicatorView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}