{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView\/refresh(entity:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"refreshWithEntity:","kind":"identifier"}],"title":"refresh(entity:)","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)PinnedIndicatorView(im)refreshWithEntity:","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pinnedindicatorview\/refresh(entity:)"]},{"paths":["\/documentation\/easechatuikit\/pinnedindicatorview\/refresh(entity:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedIndicatorView/refresh(entity:)":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView\/refresh(entity:)","url":"\/documentation\/easechatuikit\/pinnedindicatorview\/refresh(entity:)","navigatorTitle":[{"text":"refreshWithEntity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"refresh(entity:)","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"title":"MessageEntity","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageEntity"}],"url":"\/documentation\/easechatuikit\/messageentity","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedIndicatorView":{"title":"PinnedIndicatorView","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PinnedIndicatorView","kind":"identifier"}],"navigatorTitle":[{"text":"PinnedIndicatorView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pinnedindicatorview","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedIndicatorView"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"refreshWithEntity:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithEntity:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"refreshWithEntity:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"entity"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"refreshWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView~1refresh(entity:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView~1refresh(entity:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"refreshWithEntity:","kind":"identifier"}]},{"value":"MessageEntity","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments","value":[{"text":"MessageEntity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"MessageEntity"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView\/title","op":"replace","value":"PinnedIndicatorView"},{"value":[{"text":"PinnedIndicatorView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedIndicatorView\/navigatorTitle","op":"replace","value":[{"text":"PinnedIndicatorView","kind":"identifier"}]}]}]}