{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitContext(py)chatCache","navigatorTitle":[{"kind":"identifier","text":"chatCache"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatCache"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":">?","kind":"text"}],"title":"chatCache","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/chatCache","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"The cache of user information on the side of the message in the chat page. The key is the user ID and the value is an object that complies with the "},{"type":"codeVoice","code":"EaseProfileProtocol"},{"text":" protocol.Display the info on chat page.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatuikitcontext\/chatcache"]},{"paths":["\/documentation\/easechatuikit\/chatuikitcontext\/chatcache"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":">?","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/chatCache":{"navigatorTitle":[{"kind":"identifier","text":"chatCache"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatCache"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":">?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/chatCache","kind":"symbol","title":"chatCache","abstract":[{"text":"The cache of user information on the side of the message in the chat page. The key is the user ID and the value is an object that complies with the ","type":"text"},{"type":"codeVoice","code":"EaseProfileProtocol"},{"text":" protocol.Display the info on chat page.","type":"text"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatuikitcontext\/chatcache","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext":{"kind":"symbol","title":"ChatUIKitContext","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitContext"}],"navigatorTitle":[{"kind":"identifier","text":"ChatUIKitContext"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProtocol":{"abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatuserprofileprotocol","role":"symbol","title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"chatCache","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"chatCache","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id<ChatUserProfileProtocol>>"},{"kind":"text","text":" * "},{"text":"chatCache","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1chatCache\/title","value":"chatCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1chatCache\/fragments","value":[{"kind":"identifier","text":"chatCache"}]},{"value":"ChatUIKitContext","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/title"},{"value":[{"text":"ChatUIKitContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/fragments"},{"value":[{"kind":"identifier","text":"ChatUIKitContext"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/title","value":"ChatUserProfileProtocol"},{"op":"replace","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}]}]}]}