{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProviderOC","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupProfileProviderOC"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatGroupProfileProviderOC","text":"ChatGroupProfileProviderOC","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProviderOC"},{"kind":"text","text":"?"}]}]}],"metadata":{"navigatorTitle":[{"text":"groupProfileProviderOC","kind":"identifier"}],"role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupProfileProviderOC"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatGroupProfileProviderOC","text":"ChatGroupProfileProviderOC"},{"kind":"text","text":"?"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitContext(py)groupProfileProviderOC","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","title":"groupProfileProviderOC"},"variants":[{"paths":["\/documentation\/easechatuikit\/chatuikitcontext\/groupprofileprovideroc"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatuikitcontext\/groupprofileprovideroc"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroupProfileProviderOC":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProviderOC","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"navigatorTitle":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/chatgroupprofileprovideroc","type":"topic","title":"ChatGroupProfileProviderOC"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext":{"kind":"symbol","title":"ChatUIKitContext","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitContext"}],"navigatorTitle":[{"kind":"identifier","text":"ChatUIKitContext"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/groupProfileProviderOC":{"type":"topic","title":"groupProfileProviderOC","navigatorTitle":[{"text":"groupProfileProviderOC","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupProfileProviderOC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatGroupProfileProviderOC","kind":"typeIdentifier","text":"ChatGroupProfileProviderOC"},{"text":"?","kind":"text"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext\/groupprofileprovideroc","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProviderOC"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"groupProfileProviderOC"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"groupProfileProviderOC","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<ChatGroupProfileProviderOC>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ChatGroupProfileProviderOC"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupProfileProviderOC"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ChatGroupProfileProviderOC","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC\/fragments","op":"replace","value":[{"text":"ChatGroupProfileProviderOC","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ChatGroupProfileProviderOC"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatGroupProfileProviderOC\/navigatorTitle"},{"value":"ChatUIKitContext","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/fragments","value":[{"kind":"identifier","text":"ChatUIKitContext"}]},{"value":[{"kind":"identifier","text":"ChatUIKitContext"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/navigatorTitle"},{"value":"groupProfileProviderOC","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1groupProfileProviderOC\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext~1groupProfileProviderOC\/fragments","value":[{"kind":"identifier","text":"groupProfileProviderOC"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}