{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProvider"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatuikitcontext\/groupprofileprovider"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"groupProfileProvider","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ChatGroupProfileProvider","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B20GroupProfileProviderP"},{"kind":"text","text":"?"}],"externalID":"s:13EaseChatUIKit0bC7ContextC20groupProfileProviderAA0b5GroupfG0_pSgvp","role":"symbol","title":"groupProfileProvider","roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"groupProfileProvider","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProvider","preciseIdentifier":"s:13EaseChatUIKit0B20GroupProfileProviderP","kind":"typeIdentifier","text":"ChatGroupProfileProvider"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext/groupProfileProvider":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupProfileProvider"},{"kind":"text","text":": "},{"text":"ChatGroupProfileProvider","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B20GroupProfileProviderP"},{"text":"?","kind":"text"}],"abstract":[],"title":"groupProfileProvider","role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/chatuikitcontext\/groupprofileprovider","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext\/groupProfileProvider"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroupProfileProvider":{"kind":"symbol","url":"\/documentation\/easechatuikit\/chatgroupprofileprovider","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroupProfileProvider","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatGroupProfileProvider"}],"type":"topic","title":"ChatGroupProfileProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatGroupProfileProvider"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitContext":{"kind":"symbol","title":"ChatUIKitContext","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitContext"}],"navigatorTitle":[{"kind":"identifier","text":"ChatUIKitContext"}],"url":"\/documentation\/easechatuikit\/chatuikitcontext","abstract":[],"role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/title","value":"ChatUIKitContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/fragments","value":[{"kind":"identifier","text":"ChatUIKitContext"}]},{"value":[{"text":"ChatUIKitContext","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitContext\/navigatorTitle"}]}]}