{"abstract":[{"type":"text","text":"Cache a group member attribute for key."}],"metadata":{"title":"cache(groupId:userId:key:value:)","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache(im)cacheWithGroupId:userId:key:value:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"cacheWithGroupId:userId:key:value:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/cache(groupid:userid:key:value:)"]},{"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/cache(groupid:userid:key:value:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/cache(groupId:userId:key:value:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(cacheWithGroupId:userId:key:value:) "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"text":"ID of the group.","type":"text"}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Attribute key"}],"type":"paragraph"}],"name":"key"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Attribute value","type":"text"}]}],"name":"value"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache":{"kind":"symbol","url":"\/documentation\/easechatuikit\/groupmemberattributescache","title":"GroupMemberAttributesCache","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupMemberAttributesCache","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupMemberAttributesCache"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache/cache(groupId:userId:key:value:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/groupmemberattributescache\/cache(groupid:userid:key:value:)","title":"cache(groupId:userId:key:value:)","type":"topic","abstract":[{"text":"Cache a group member attribute for key.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/cache(groupId:userId:key:value:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cache"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"key","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"cacheWithGroupId:userId:key:value:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"cacheWithGroupId:userId:key:value:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheWithGroupId:userId:key:value:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"cacheWithGroupId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"userId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"text":" ","kind":"text"},{"text":"key:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"text":"value:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/title","value":"GroupMemberAttributesCache","op":"replace"},{"value":[{"text":"GroupMemberAttributesCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1cache(groupId:userId:key:value:)\/title","value":"cacheWithGroupId:userId:key:value:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cacheWithGroupId:userId:key:value:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1cache(groupId:userId:key:value:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}