{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerOC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseGroupMemberProfileProviderOC","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseGroupMemberProfileProviderOC","text":"EaseGroupMemberProfileProviderOC"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/provideroc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/provideroc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/providerOC","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerOC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseGroupMemberProfileProviderOC","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseGroupMemberProfileProviderOC"},{"kind":"text","text":"?"}],"title":"providerOC","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache(py)providerOC","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"providerOC"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache":{"role":"symbol","title":"GroupMemberAttributesCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupMemberAttributesCache"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupMemberAttributesCache"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseGroupMemberProfileProviderOC":{"role":"symbol","title":"EaseGroupMemberProfileProviderOC","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseGroupMemberProfileProviderOC"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseGroupMemberProfileProviderOC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseGroupMemberProfileProviderOC"}],"url":"\/documentation\/easechatuikit\/easegroupmemberprofileprovideroc"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache/providerOC":{"role":"symbol","title":"providerOC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"providerOC"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseGroupMemberProfileProviderOC","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseGroupMemberProfileProviderOC"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/providerOC","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"providerOC"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache\/provideroc"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"providerOC"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"providerOC"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<EaseGroupMemberProfileProviderOC>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)EaseGroupMemberProfileProviderOC"},{"kind":"text","text":" * "},{"kind":"identifier","text":"providerOC"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/title","value":"GroupMemberAttributesCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/fragments","value":[{"kind":"identifier","text":"GroupMemberAttributesCache"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseGroupMemberProfileProviderOC\/title","value":"EaseGroupMemberProfileProviderOC"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseGroupMemberProfileProviderOC\/fragments","value":[{"kind":"identifier","text":"EaseGroupMemberProfileProviderOC"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1providerOC\/title","value":"providerOC"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1providerOC\/fragments","value":[{"kind":"identifier","text":"providerOC"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}