{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/removeCacheProfile(groupId:profile:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache"]]},"metadata":{"title":"removeCacheProfile(groupId:profile:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"removeProfileCacheWithGroupId:profile:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeCacheProfile","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache(im)removeProfileCacheWithGroupId:profile:","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Remove  a conform ","type":"text"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol"},{"type":"text","text":" cache object.."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(removeProfileCacheWithGroupId:profile:) ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeCacheProfile"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","kind":"typeIdentifier","text":"EaseProfileProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group."}]}],"name":"groupId"},{"name":"profile","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol"}]}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/removecacheprofile(groupid:profile:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/removecacheprofile(groupid:profile:)"]}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache":{"kind":"symbol","url":"\/documentation\/easechatuikit\/groupmemberattributescache","title":"GroupMemberAttributesCache","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupMemberAttributesCache","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupMemberAttributesCache"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"title":"EaseProfileProtocol","abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"EaseProfileProtocol","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/easeprofileprotocol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","navigatorTitle":[{"kind":"identifier","text":"EaseProfileProtocol"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache/removeCacheProfile(groupId:profile:)":{"navigatorTitle":[{"text":"removeProfileCacheWithGroupId:profile:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache\/removecacheprofile(groupid:profile:)","title":"removeCacheProfile(groupId:profile:)","abstract":[{"text":"Remove  a conform ","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","isActive":true},{"text":" cache object..","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/removeCacheProfile(groupId:profile:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeCacheProfile","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol"},{"text":")","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"removeProfileCacheWithGroupId:profile:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeProfileCacheWithGroupId:profile:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeProfileCacheWithGroupId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"profile:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<EaseProfileProtocol>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"profile"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/title","value":"GroupMemberAttributesCache"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/fragments","value":[{"text":"GroupMemberAttributesCache","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"EaseProfileProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title"},{"value":[{"text":"EaseProfileProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1removeCacheProfile(groupId:profile:)\/title","value":"removeProfileCacheWithGroupId:profile:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1removeCacheProfile(groupId:profile:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeProfileCacheWithGroupId:profile:","kind":"identifier"}]}]}]}