{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCacheProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profiles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group"}]}]},{"name":"profiles","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Array that you want to update of the conform "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol"},{"type":"text","text":" object."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/updatecacheprofile(groupid:profiles:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/updatecacheprofile(groupid:profiles:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/updateCacheProfile(groupId:profiles:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Update cache profiles"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCacheProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profiles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":"])"}],"title":"updateCacheProfile(groupId:profiles:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache(im)updateCacheProfileWithGroupId:profiles:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateCacheProfileWithGroupId:profiles:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache/updateCacheProfile(groupId:profiles:)":{"role":"symbol","title":"updateCacheProfile(groupId:profiles:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCacheProfile"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"profiles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Update cache profiles"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/updateCacheProfile(groupId:profiles:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateCacheProfileWithGroupId:profiles:"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache\/updatecacheprofile(groupid:profiles:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"role":"symbol","title":"EaseProfileProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseProfileProtocol"}],"abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseProfileProtocol"}],"url":"\/documentation\/easechatuikit\/easeprofileprotocol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache":{"role":"symbol","title":"GroupMemberAttributesCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupMemberAttributesCache"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupMemberAttributesCache"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateCacheProfileWithGroupId:profiles:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCacheProfileWithGroupId:profiles:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateCacheProfileWithGroupId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"groupId"},{"kind":"text","text":" "},{"kind":"identifier","text":"profiles:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<EaseProfileProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"profiles"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1updateCacheProfile(groupId:profiles:)\/title","value":"updateCacheProfileWithGroupId:profiles:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1updateCacheProfile(groupId:profiles:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCacheProfileWithGroupId:profiles:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title","value":"EaseProfileProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments","value":[{"kind":"identifier","text":"EaseProfileProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/title","value":"GroupMemberAttributesCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/fragments","value":[{"kind":"identifier","text":"GroupMemberAttributesCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}