{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(updateCacheWithGroupId:userId:key:value:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"groupId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the group"}]}]},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user."}]}]},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Attribute key."}]}]},{"name":"value","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Attribute value"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/updatecache(groupid:userid:key:value:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupmemberattributescache\/updatecache(groupid:userid:key:value:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/updateCache(groupId:userId:key:value:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Update a group member cache attribute value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"updateCache(groupId:userId:key:value:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache(im)updateCacheWithGroupId:userId:key:value:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateCacheWithGroupId:userId:key:value:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache":{"role":"symbol","title":"GroupMemberAttributesCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupMemberAttributesCache"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupMemberAttributesCache"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache/updateCache(groupId:userId:key:value:)":{"role":"symbol","title":"updateCache(groupId:userId:key:value:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateCache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update a group member cache attribute value."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache\/updateCache(groupId:userId:key:value:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"updateCacheWithGroupId:userId:key:value:"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache\/updatecache(groupid:userid:key:value:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateCacheWithGroupId:userId:key:value:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCacheWithGroupId:userId:key:value:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateCacheWithGroupId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"groupId"},{"kind":"text","text":" "},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"kind":"identifier","text":"key:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"value:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/title","value":"GroupMemberAttributesCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/fragments","value":[{"kind":"identifier","text":"GroupMemberAttributesCache"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1updateCache(groupId:userId:key:value:)\/title","value":"updateCacheWithGroupId:userId:key:value:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache~1updateCache(groupId:userId:key:value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateCacheWithGroupId:userId:key:value:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}