{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeRightActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType","text":"UIContextualActionType"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/appearance\/conversation-swift.class\/swiperightactions"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Conversation-swift.class\/swipeRightActions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Menu items that appear after swiping right in a conversation.You can choose to have just some of the features or all of them."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeRightActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":"]"}],"title":"swipeRightActions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13EaseChatUIKit10AppearanceC12ConversationC17swipeRightActionsSayAA22UIContextualActionTypeOGvp","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Conversation-swift.class"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIContextualActionType":{"role":"symbol","title":"UIContextualActionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIContextualActionType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"UIContextualActionType"}],"url":"\/documentation\/easechatuikit\/uicontextualactiontype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Conversation-swift.class":{"role":"symbol","title":"Appearance.Conversation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Conversation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Conversation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Conversation"}],"url":"\/documentation\/easechatuikit\/appearance\/conversation-swift.class"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance/Conversation-swift.class/swipeRightActions":{"role":"symbol","title":"swipeRightActions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"swipeRightActions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIContextualActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@UIContextualActionType"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Menu items that appear after swiping right in a conversation.You can choose to have just some of the features or all of them."},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIContextualActionType"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance\/Conversation-swift.class\/swipeRightActions","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/appearance\/conversation-swift.class\/swiperightactions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","title":"Appearance","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Appearance"}],"abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Appearance"}],"url":"\/documentation\/easechatuikit\/appearance"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/title","value":"UIContextualActionType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIContextualActionType\/fragments","value":[{"kind":"identifier","text":"UIContextualActionType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}