{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell\/display"},"sections":[],"metadata":{"role":"symbol","externalID":"s:13EaseChatUIKit11ContactCellC7displayAA0D12DisplayStyleOvp","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContactDisplayStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactDisplayStyle"}],"title":"display"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContactDisplayStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactDisplayStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle"},{"text":" { get }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactcell\/display"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCell/display":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell\/display","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"display","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ContactDisplayStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactDisplayStyle"}],"kind":"symbol","title":"display","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/contactcell\/display"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCell":{"navigatorTitle":[{"kind":"identifier","text":"ContactCell"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactcell","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactCell"}],"title":"ContactCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactDisplayStyle":{"url":"\/documentation\/easechatuikit\/contactdisplaystyle","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactDisplayStyle","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactDisplayStyle"}],"title":"ContactDisplayStyle","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"ContactCell","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCell\/fragments","value":[{"text":"ContactCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/title","op":"replace","value":"ContactDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactDisplayStyle\/fragments","value":[{"text":"ContactDisplayStyle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}