{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell\/layoutSubviews()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactcell\/layoutsubviews()"]},{"paths":["\/documentation\/easechatuikit\/contactcell\/layoutsubviews()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"symbolKind":"method","role":"symbol","title":"layoutSubviews()","navigatorTitle":[{"text":"layoutSubviews","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactCell(im)layoutSubviews","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCell/layoutSubviews()":{"navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell\/layoutSubviews()","kind":"symbol","role":"symbol","title":"layoutSubviews()","url":"\/documentation\/easechatuikit\/contactcell\/layoutsubviews()","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"layoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCell":{"navigatorTitle":[{"kind":"identifier","text":"ContactCell"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/contactcell","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCell","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactCell"}],"title":"ContactCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"layoutSubviews","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"layoutSubviews","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCell~1layoutSubviews()\/title","op":"replace","value":"layoutSubviews"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCell~1layoutSubviews()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"layoutSubviews","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCell\/title","value":"ContactCell"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCell\/fragments","value":[{"kind":"identifier","text":"ContactCell"}]}]}]}