{"sections":[],"metadata":{"title":"pullToRefresh(_:stateDidChange:)","required":true,"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pullToRefresh","kind":"identifier"},{"text":"(","kind":"text"},{"text":"PullRefresher","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PullRefresher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"stateDidChange"},{"text":": ","kind":"text"},{"text":"PullRefresherState","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit18PullRefresherStateO"},{"text":")","kind":"text"}],"externalID":"s:13EaseChatUIKit21PullRefresherDelegateP13pullToRefresh_14stateDidChangeyAA0dE0C_AA0dE5StateOtF"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresherDelegate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pullToRefresh","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"view"},{"text":": ","kind":"text"},{"text":"PullRefresher","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresher","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PullRefresher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stateDidChange"},{"kind":"text","text":" "},{"kind":"internalParam","text":"state"},{"kind":"text","text":": "},{"text":"PullRefresherState","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit18PullRefresherStateO","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresherState"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresherDelegate\/pullToRefresh(_:stateDidChange:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pullrefresherdelegate\/pulltorefresh(_:statedidchange:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PullRefresherDelegate":{"abstract":[],"kind":"symbol","title":"PullRefresherDelegate","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PullRefresherDelegate"}],"url":"\/documentation\/easechatuikit\/pullrefresherdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PullRefresherDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresherDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PullRefresher":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PullRefresher"}],"abstract":[],"title":"PullRefresher","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PullRefresher"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/pullrefresher","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresher"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PullRefresherDelegate/pullToRefresh(_:stateDidChange:)":{"abstract":[],"kind":"symbol","title":"pullToRefresh(_:stateDidChange:)","type":"topic","required":true,"role":"symbol","url":"\/documentation\/easechatuikit\/pullrefresherdelegate\/pulltorefresh(_:statedidchange:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pullToRefresh","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PullRefresher","text":"PullRefresher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"stateDidChange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit18PullRefresherStateO","text":"PullRefresherState"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresherDelegate\/pullToRefresh(_:stateDidChange:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PullRefresherState":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PullRefresherState"}],"abstract":[],"title":"PullRefresherState","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PullRefresherState"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/pullrefresherstate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PullRefresherState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PullRefresher\/title","value":"PullRefresher"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PullRefresher\/fragments","op":"replace","value":[{"kind":"identifier","text":"PullRefresher"}]},{"value":[{"text":"PullRefresher","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PullRefresher\/navigatorTitle","op":"replace"}]}]}