{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/reportoptioncell\/refresh(select:title:)"]},{"paths":["\/documentation\/easechatuikit\/reportoptioncell\/refresh(select:title:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionCell\/refresh(select:title:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionCell"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)ReportOptionCell(im)refreshWithSelect:title:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"select"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"text":"title","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"refresh(select:title:)","navigatorTitle":[{"kind":"identifier","text":"refreshWithSelect:title:"}],"symbolKind":"method","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Refresh report option select state.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refresh","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"select"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"title"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Whether select or not.","type":"text"}]}],"name":"select"},{"name":"title","content":[{"inlineContent":[{"text":"Title","type":"text"}],"type":"paragraph"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReportOptionCell/refresh(select:title:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"text":"select","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"title"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionCell\/refresh(select:title:)","navigatorTitle":[{"text":"refreshWithSelect:title:","kind":"identifier"}],"title":"refresh(select:title:)","url":"\/documentation\/easechatuikit\/reportoptioncell\/refresh(select:title:)","role":"symbol","kind":"symbol","abstract":[{"text":"Refresh report option select state.","type":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ReportOptionCell":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ReportOptionCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ReportOptionCell","url":"\/documentation\/easechatuikit\/reportoptioncell","title":"ReportOptionCell","abstract":[],"navigatorTitle":[{"text":"ReportOptionCell","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"refreshWithSelect:title:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"refreshWithSelect:title:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshWithSelect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"select","kind":"internalParam"},{"kind":"text","text":" "},{"text":"title:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"title"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"select","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether select or not."}]}]},{"name":"title","content":[{"inlineContent":[{"text":"Title","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionCell~1refresh(select:title:)\/title","op":"replace","value":"refreshWithSelect:title:"},{"value":[{"kind":"text","text":"- "},{"text":"refreshWithSelect:title:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionCell~1refresh(select:title:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionCell\/title","value":"ReportOptionCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionCell\/fragments","op":"replace","value":[{"text":"ReportOptionCell","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ReportOptionCell\/navigatorTitle","value":[{"text":"ReportOptionCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}