{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderCell"]]},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactListHeaderCell(im)createSeparatorLine","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createSeparatorLine"},{"kind":"text","text":"() -> "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"title":"createSeparatorLine()","navigatorTitle":[{"text":"createSeparatorLine","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createSeparatorLine","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier","text":"UIView"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactlistheadercell\/createseparatorline()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactlistheadercell\/createseparatorline()"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderCell\/createSeparatorLine()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderCell/createSeparatorLine()":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createSeparatorLine","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createSeparatorLine"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderCell\/createSeparatorLine()","url":"\/documentation\/easechatuikit\/contactlistheadercell\/createseparatorline()","title":"createSeparatorLine()","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderCell":{"url":"\/documentation\/easechatuikit\/contactlistheadercell","kind":"symbol","title":"ContactListHeaderCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ContactListHeaderCell"}],"navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderCell"}],"role":"symbol","abstract":[{"type":"text","text":"The header list cell of the contact list."}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderCell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"createSeparatorLine","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createSeparatorLine"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" *) "},{"text":"createSeparatorLine","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderCell~1createSeparatorLine()\/title","op":"replace","value":"createSeparatorLine"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderCell~1createSeparatorLine()\/fragments","value":[{"kind":"text","text":"- "},{"text":"createSeparatorLine","kind":"identifier"}],"op":"replace"},{"value":"ContactListHeaderCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderCell\/title"},{"value":[{"text":"ContactListHeaderCell","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderCell\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderCell\/navigatorTitle","value":[{"text":"ContactListHeaderCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}