{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/emptystateview\/init(frame:emptyimage:onretry:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/emptystateview\/init(frame:emptyimage:onretry:)"]}],"abstract":[{"text":"Init a empty state view.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyStateView"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyStateView\/init(frame:emptyImage:onRetry:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"emptyImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"onRetry","kind":"externalParam"},{"text":": () -> ())","kind":"text"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithFrame:emptyImage:onRetry:","kind":"identifier"}],"title":"init(frame:emptyImage:onRetry:)","externalID":"c:@M@EaseChatUIKit@objc(cs)EmptyStateView(im)initWithFrame:emptyImage:onRetry:","symbolKind":"init","modules":[{"name":"EaseChatUIKit"}],"role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"emptyImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"onRetry"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"text":" () -> ())","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"inlineContent":[{"type":"text","text":"CGRect"}],"type":"paragraph"}]},{"name":"emptyImage","content":[{"type":"paragraph","inlineContent":[{"text":"UIImage?","type":"text"}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyStateView/init(frame:emptyImage:onRetry:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"emptyImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"onRetry","kind":"externalParam"},{"kind":"text","text":": () -> ())"}],"url":"\/documentation\/easechatuikit\/emptystateview\/init(frame:emptyimage:onretry:)","abstract":[{"text":"Init a empty state view.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyStateView\/init(frame:emptyImage:onRetry:)","role":"symbol","kind":"symbol","title":"init(frame:emptyImage:onRetry:)","type":"topic","navigatorTitle":[{"text":"initWithFrame:emptyImage:onRetry:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EmptyStateView":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EmptyStateView","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/emptystateview","title":"EmptyStateView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EmptyStateView","navigatorTitle":[{"text":"EmptyStateView","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithFrame:emptyImage:onRetry:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithFrame:emptyImage:onRetry:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"kind":"text","text":" "},{"text":"emptyImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"emptyImage"},{"kind":"text","text":" "},{"text":"onRetry:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"text":")()) ","kind":"text"},{"kind":"internalParam","text":"onRetry"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyStateView~1init(frame:emptyImage:onRetry:)\/title","value":"initWithFrame:emptyImage:onRetry:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyStateView~1init(frame:emptyImage:onRetry:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:emptyImage:onRetry:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyStateView\/title","op":"replace","value":"EmptyStateView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EmptyStateView\/fragments","value":[{"text":"EmptyStateView","kind":"identifier"}]}]}]}