{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/easechatuikit\/pinnedmessagesindicator\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/pinnedmessagesindicator\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"title":"switchTheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier","text":"ThemeStyle"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)PinnedMessagesIndicator(im)switchThemeWithStyle:","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle"}],"type":"paragraph"}],"name":"style"}],"kind":"parameters"}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/switchTheme(style:)","interfaceLanguage":"swift"},"abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/ThemeSwitchProtocol-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesIndicator/switchTheme(style:)":{"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"text":" to switch theme.","type":"text"}],"title":"switchTheme(style:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/switchTheme(style:)","kind":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagesindicator\/switchtheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"type":"topic","abstract":[{"text":"An object containing visual configurations for the whole application.","type":"text"}],"title":"Appearance","kind":"symbol","navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesIndicator":{"type":"topic","kind":"symbol","title":"PinnedMessagesIndicator","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesIndicator","kind":"identifier"}],"navigatorTitle":[{"text":"PinnedMessagesIndicator","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pinnedmessagesindicator","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesIndicator/ThemeSwitchProtocol-Implementations":{"url":"\/documentation\/easechatuikit\/pinnedmessagesindicator\/themeswitchprotocol-implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","abstract":[],"kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle":{"type":"topic","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","type":"reference","isActive":true},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"text":" method","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","title":"ThemeStyle","kind":"symbol","url":"\/documentation\/easechatuikit\/themestyle","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"switchThemeWithStyle:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchThemeWithStyle:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"switchThemeWithStyle:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","text":"ThemeStyle"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator~1switchTheme(style:)\/title","op":"replace","value":"switchThemeWithStyle:"},{"value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator~1switchTheme(style:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance","op":"replace"},{"op":"replace","value":[{"text":"Appearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments"},{"value":[{"text":"Appearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator\/title","value":"PinnedMessagesIndicator"},{"value":[{"text":"PinnedMessagesIndicator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"PinnedMessagesIndicator"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/title","value":"ThemeStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"ThemeStyle"}]},{"value":[{"kind":"identifier","text":"ThemeStyle"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/navigatorTitle"}]}]}