{"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/switchTheme(style:)"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","roleHeading":"API Collection"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pinnedmessagesindicator\/themeswitchprotocol-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pinnedmessagesindicator\/themeswitchprotocol-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/ThemeSwitchProtocol-Implementations"},"sections":[],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesIndicator/switchTheme(style:)":{"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"text":" to switch theme.","type":"text"}],"title":"switchTheme(style:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/switchTheme(style:)","kind":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagesindicator\/switchtheme(style:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesIndicator":{"type":"topic","kind":"symbol","title":"PinnedMessagesIndicator","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesIndicator","kind":"identifier"}],"navigatorTitle":[{"text":"PinnedMessagesIndicator","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pinnedmessagesindicator","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesIndicator\/switchTheme(style:)"],"title":"Instance Methods","generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator~1switchTheme(style:)\/title","value":"switchThemeWithStyle:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator~1switchTheme(style:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator\/title","value":"PinnedMessagesIndicator"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator\/fragments","op":"replace","value":[{"kind":"identifier","text":"PinnedMessagesIndicator"}]},{"value":[{"kind":"identifier","text":"PinnedMessagesIndicator"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesIndicator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}