{"abstract":[{"text":"Converts the specified ranges of the input attributed string to emoji images using the provided symbol and returns the resulting attributed string.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"convertEmoji","kind":"identifier"},{"text":"(","kind":"text"},{"text":"input","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableAttributedString","text":"NSMutableAttributedString","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ranges"},{"text":": [","kind":"text"},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"symbol"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageBounds"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableAttributedString","kind":"typeIdentifier","text":"NSMutableAttributedString"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"input","content":[{"type":"paragraph","inlineContent":[{"text":"The input attributed string to convert.","type":"text"}]}]},{"name":"ranges","content":[{"type":"paragraph","inlineContent":[{"text":"The ranges of the input attributed string to convert to emoji images.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The symbol to use for the emoji images."}],"type":"paragraph"}],"name":"symbol"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"A new attributed string with the specified ranges replaced with emoji images."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor\/convertEmoji(input:ranges:symbol:imageBounds:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"convertEmoji"},{"kind":"text","text":"("},{"text":"input","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableAttributedString","text":"NSMutableAttributedString","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ranges","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"symbol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"imageBounds","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)NSMutableAttributedString","text":"NSMutableAttributedString","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"convertEmojiWithInput:ranges:symbol:imageBounds:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"title":"convertEmoji(input:ranges:symbol:imageBounds:)","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatEmojiConvertor(im)convertEmojiWithInput:ranges:symbol:imageBounds:"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:imagebounds:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:imagebounds:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatEmojiConvertor":{"abstract":[{"type":"text","text":"A class that converts emojis in a given NSMutableAttributedString to their corresponding UIImage."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor","url":"\/documentation\/easechatuikit\/chatemojiconvertor","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatEmojiConvertor"}],"navigatorTitle":[{"text":"ChatEmojiConvertor","kind":"identifier"}],"title":"ChatEmojiConvertor","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatEmojiConvertor/convertEmoji(input:ranges:symbol:imageBounds:)":{"abstract":[{"type":"text","text":"Converts the specified ranges of the input attributed string to emoji images using the provided symbol and returns the resulting attributed string."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor\/convertEmoji(input:ranges:symbol:imageBounds:)","url":"\/documentation\/easechatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:imagebounds:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"convertEmoji","kind":"identifier"},{"kind":"text","text":"("},{"text":"input","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ranges"},{"kind":"text","text":": ["},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange"},{"text":"], ","kind":"text"},{"text":"symbol","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"imageBounds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSMutableAttributedString","text":"NSMutableAttributedString","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"convertEmojiWithInput:ranges:symbol:imageBounds:"}],"title":"convertEmoji(input:ranges:symbol:imageBounds:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"convertEmojiWithInput:ranges:symbol:imageBounds:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"convertEmojiWithInput:ranges:symbol:imageBounds:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSMutableAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"text":" *) ","kind":"text"},{"text":"convertEmojiWithInput:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSMutableAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"text":" *) ","kind":"text"},{"text":"input","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ranges:"},{"kind":"text","text":"("},{"text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ranges","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"symbol:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"symbol"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageBounds:"},{"text":"(","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"imageBounds"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor\/title","op":"replace","value":"ChatEmojiConvertor"},{"value":[{"kind":"identifier","text":"ChatEmojiConvertor"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor~1convertEmoji(input:ranges:symbol:imageBounds:)\/title","value":"convertEmojiWithInput:ranges:symbol:imageBounds:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor~1convertEmoji(input:ranges:symbol:imageBounds:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"convertEmojiWithInput:ranges:symbol:imageBounds:","kind":"identifier"}]}]}]}