{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertEmoji"},{"kind":"text","text":"("},{"kind":"externalParam","text":"input"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ranges"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"symbol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"input","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The input attributed string to convert."}]}]},{"name":"ranges","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The ranges of the input attributed string to convert to emoji images."}]}]},{"name":"symbol","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The symbol to use for the emoji images."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new attributed string with the specified ranges replaced with emoji images."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor\/convertEmoji(input:ranges:symbol:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Converts the specified ranges of the input attributed string to emoji images using the provided symbol and returns the resulting attributed string."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertEmoji"},{"kind":"text","text":"("},{"kind":"externalParam","text":"input"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ranges"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"symbol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"}],"title":"convertEmoji(input:ranges:symbol:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatEmojiConvertor(im)convertEmojiWithInput:ranges:symbol:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"convertEmojiWithInput:ranges:symbol:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatEmojiConvertor":{"role":"symbol","title":"ChatEmojiConvertor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatEmojiConvertor"}],"abstract":[{"type":"text","text":"A class that converts emojis in a given NSMutableAttributedString to their corresponding UIImage."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatEmojiConvertor"}],"url":"\/documentation\/easechatuikit\/chatemojiconvertor"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatEmojiConvertor/convertEmoji(input:ranges:symbol:)":{"role":"symbol","title":"convertEmoji(input:ranges:symbol:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"convertEmoji"},{"kind":"text","text":"("},{"kind":"externalParam","text":"input"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ranges"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"NSRange","preciseIdentifier":"c:@T@NSRange"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"symbol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"}],"abstract":[{"type":"text","text":"Converts the specified ranges of the input attributed string to emoji images using the provided symbol and returns the resulting attributed string."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatEmojiConvertor\/convertEmoji(input:ranges:symbol:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"convertEmojiWithInput:ranges:symbol:"}],"url":"\/documentation\/easechatuikit\/chatemojiconvertor\/convertemoji(input:ranges:symbol:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"convertEmojiWithInput:ranges:symbol:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertEmojiWithInput:ranges:symbol:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"convertEmojiWithInput:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSMutableAttributedString","preciseIdentifier":"c:objc(cs)NSMutableAttributedString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"input"},{"kind":"text","text":" "},{"kind":"identifier","text":"ranges:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSValue *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ranges"},{"kind":"text","text":" "},{"kind":"identifier","text":"symbol:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"symbol"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor\/title","value":"ChatEmojiConvertor"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor\/fragments","value":[{"kind":"identifier","text":"ChatEmojiConvertor"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor~1convertEmoji(input:ranges:symbol:)\/title","value":"convertEmojiWithInput:ranges:symbol:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatEmojiConvertor~1convertEmoji(input:ranges:symbol:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"convertEmojiWithInput:ranges:symbol:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}