{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","text":"ContactListHeaderStyle"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactview\/headerstyle"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/headerStyle","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle"}],"title":"headerStyle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:13EaseChatUIKit11ContactViewC11headerStyleAA0d10ListHeaderG0Ovp","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/headerStyle":{"role":"symbol","title":"headerStyle","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerStyle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/headerStyle","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/headerstyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView":{"role":"symbol","title":"ContactView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactView"}],"url":"\/documentation\/easechatuikit\/contactview"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle":{"role":"symbol","title":"ContactListHeaderStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListHeaderStyle"}],"abstract":[{"type":"text","text":"The header display style of the "},{"type":"codeVoice","code":"ContactList"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyle"}],"url":"\/documentation\/easechatuikit\/contactlistheaderstyle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/title","value":"ContactView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/fragments","value":[{"kind":"identifier","text":"ContactView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/title","value":"ContactListHeaderStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}