{"metadata":{"title":"IContactListDriver Implementations","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactview\/icontactlistdriver-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactview\/icontactlistdriver-implementations"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/IContactListDriver-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/appendThenRefresh(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/occurError()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshHeader(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshList(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/remove(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/removeActionHandler(actionHandler:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/addActionHandler(actionHandler:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListActionEventsDelegate"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"kind":"symbol","abstract":[{"type":"text","text":"Add UI actions handler."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/addActionHandler(actionHandler:)","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/addactionhandler(actionhandler:)","title":"addActionHandler(actionHandler:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView":{"title":"ContactView","url":"\/documentation\/easechatuikit\/contactview","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/remove(info:)":{"url":"\/documentation\/easechatuikit\/contactview\/remove(info:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/remove(info:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The method can be used when you want to remove a contact."}],"title":"remove(info:)","navigatorTitle":[{"text":"removeWithInfo:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"remove"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"info"},{"text":": ","kind":"text"},{"text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/appendThenRefresh(info:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"appendThenRefresh"},{"text":"(","kind":"text"},{"text":"info","kind":"externalParam"},{"kind":"text","text":": "},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"appendThenRefreshWithInfo:"}],"kind":"symbol","abstract":[{"type":"text","text":"The method can be user when you want to add someone to contact list."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/appendThenRefresh(info:)","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/appendthenrefresh(info:)","title":"appendThenRefresh(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/refreshList(infos:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"refreshList","kind":"identifier"},{"kind":"text","text":"("},{"text":"infos","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"refreshListWithInfos:"}],"kind":"symbol","abstract":[{"type":"text","text":"This method can be used when pulling down to refresh."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshList(infos:)","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/refreshlist(infos:)","title":"refreshList(infos:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/occurError()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"occurError"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"occurError","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"When fetch list occur error."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/occurError()","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/occurerror()","title":"occurError()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/refreshProfiles(infos:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshProfiles"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"infos"},{"kind":"text","text":": ["},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":"])","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"refreshProfilesWithInfos:"}],"kind":"symbol","abstract":[{"type":"text","text":"This method can be used when you want refresh some  display info  of datas."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshProfiles(infos:)","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/refreshprofiles(infos:)","title":"refreshProfiles(infos:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/refreshHeader(info:)":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"refreshHeader","kind":"identifier"},{"kind":"text","text":"("},{"text":"info","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol","text":"ContactListHeaderItemProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method can be used when you want to refresh header of the contact list."}],"url":"\/documentation\/easechatuikit\/contactview\/refreshheader(info:)","title":"refreshHeader(info:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshHeader(info:)","navigatorTitle":[{"text":"refreshHeaderWithInfo:","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/removeActionHandler(actionHandler:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeActionHandler","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactListActionEventsDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListActionEventsDelegate"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"removeActionHandlerWithActionHandler:","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Remove UI action handler."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/removeActionHandler(actionHandler:)","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/removeactionhandler(actionhandler:)","title":"removeActionHandler(actionHandler:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/addActionHandler(actionHandler:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/appendThenRefresh(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/occurError()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshHeader(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshList(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshProfiles(infos:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/remove(info:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/removeActionHandler(actionHandler:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1addActionHandler(actionHandler:)\/title","op":"replace","value":"addActionHandlerWithActionHandler:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1addActionHandler(actionHandler:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/title","value":"ContactView"},{"value":[{"text":"ContactView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1remove(info:)\/title","value":"removeWithInfo:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1remove(info:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeWithInfo:"}]},{"op":"replace","value":"appendThenRefreshWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1appendThenRefresh(info:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1appendThenRefresh(info:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"appendThenRefreshWithInfo:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshList(infos:)\/title","value":"refreshListWithInfos:"},{"value":[{"text":"- ","kind":"text"},{"text":"refreshListWithInfos:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshList(infos:)\/fragments"},{"op":"replace","value":"occurError","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1occurError()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"occurError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1occurError()\/fragments"},{"op":"replace","value":"refreshProfilesWithInfos:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshProfiles(infos:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshProfiles(infos:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"refreshProfilesWithInfos:","kind":"identifier"}]},{"value":"refreshHeaderWithInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshHeader(info:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"refreshHeaderWithInfo:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshHeader(info:)\/fragments"},{"value":"removeActionHandlerWithActionHandler:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1removeActionHandler(actionHandler:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1removeActionHandler(actionHandler:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeActionHandlerWithActionHandler:","kind":"identifier"}],"op":"replace"}]}]}