{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshHeader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol","text":"ContactListHeaderItemProtocol"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"info","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactview\/refreshheader(info:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactview\/refreshheader(info:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshHeader(info:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method can be used when you want to refresh header of the contact list."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"refreshHeaderWithInfo:"}],"role":"symbol","title":"refreshHeader(info:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshHeader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListHeaderItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactView(im)refreshHeaderWithInfo:","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/IContactListDriver-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/IContactListDriver-Implementations":{"role":"collectionGroup","title":"IContactListDriver Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/IContactListDriver-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/contactview\/icontactlistdriver-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView":{"role":"symbol","title":"ContactView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactView"}],"url":"\/documentation\/easechatuikit\/contactview"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactView/refreshHeader(info:)":{"role":"symbol","title":"refreshHeader(info:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshHeader"},{"kind":"text","text":"("},{"kind":"externalParam","text":"info"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ContactListHeaderItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"The method can be used when you want to refresh header of the contact list."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactView\/refreshHeader(info:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"refreshHeaderWithInfo:"}],"url":"\/documentation\/easechatuikit\/contactview\/refreshheader(info:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderItemProtocol":{"role":"symbol","title":"ContactListHeaderItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"abstract":[{"type":"text","text":"A protocol of the contact list item."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderItemProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}],"url":"\/documentation\/easechatuikit\/contactlistheaderitemprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshHeaderWithInfo:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshHeaderWithInfo:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshHeaderWithInfo:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<ContactListHeaderItemProtocol>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ContactListHeaderItemProtocol"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"info"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/title","value":"ContactView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView\/fragments","value":[{"kind":"identifier","text":"ContactView"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshHeader(info:)\/title","value":"refreshHeaderWithInfo:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactView~1refreshHeader(info:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshHeaderWithInfo:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol\/title","value":"ContactListHeaderItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderItemProtocol\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderItemProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}