{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","text":"MessageReaction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/refresh(reaction:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"text":"reaction","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","kind":"typeIdentifier","text":"MessageReaction"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageReactionCell(im)refreshWithReaction:","title":"refresh(reaction:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"refreshWithReaction:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagereactioncell\/refresh(reaction:)"]},{"paths":["\/documentation\/easechatuikit\/messagereactioncell\/refresh(reaction:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell/refresh(reaction:)":{"navigatorTitle":[{"text":"refreshWithReaction:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"reaction"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","text":"MessageReaction","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"refresh(reaction:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell\/refresh(reaction:)","abstract":[],"url":"\/documentation\/easechatuikit\/messagereactioncell\/refresh(reaction:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionCell":{"url":"\/documentation\/easechatuikit\/messagereactioncell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionCell","abstract":[],"title":"MessageReactionCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReactionCell"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageReactionCell"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReaction":{"url":"\/documentation\/easechatuikit\/messagereaction","title":"MessageReaction","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReaction"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReaction"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"refreshWithReaction:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"refreshWithReaction:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshWithReaction:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMMessageReaction","text":"EMMessageReaction","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reaction"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"refreshWithReaction:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1refresh(reaction:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithReaction:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell~1refresh(reaction:)\/fragments"},{"value":"MessageReactionCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionCell\/fragments","value":[{"text":"MessageReactionCell","kind":"identifier"}]}]}]}