{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver"]]},"abstract":[{"type":"text","text":"Add mention user to textfield on needed."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addMentionUserToField","kind":"identifier"},{"kind":"text","text":"("},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EaseProfileProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"user","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"NSAttributedString","type":"codeVoice"}],"type":"paragraph"}]}]}],"metadata":{"role":"symbol","required":true,"navigatorTitle":[{"text":"addMentionUserToFieldWithUser:","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver(im)addMentionUserToFieldWithUser:","title":"addMentionUserToField(user:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addMentionUserToField"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"user"},{"text":": ","kind":"text"},{"text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/addMentionUserToField(user:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/addmentionusertofield(user:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/addmentionusertofield(user:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver":{"title":"IMessageListViewDriver","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IMessageListViewDriver"}],"url":"\/documentation\/easechatuikit\/imessagelistviewdriver","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"title":"EaseProfileProtocol","abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"EaseProfileProtocol","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/easeprofileprotocol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","navigatorTitle":[{"kind":"identifier","text":"EaseProfileProtocol"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver/addMentionUserToField(user:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/imessagelistviewdriver\/addmentionusertofield(user:)","required":true,"navigatorTitle":[{"text":"addMentionUserToFieldWithUser:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/addMentionUserToField(user:)","title":"addMentionUserToField(user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addMentionUserToField","kind":"identifier"},{"kind":"text","text":"("},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Add mention user to textfield on needed."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"addMentionUserToFieldWithUser:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addMentionUserToFieldWithUser:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addMentionUserToFieldWithUser:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<EaseProfileProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"user"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"IMessageListViewDriver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/title"},{"value":[{"text":"IMessageListViewDriver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title","value":"EaseProfileProtocol"},{"op":"replace","value":[{"kind":"identifier","text":"EaseProfileProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1addMentionUserToField(user:)\/title","value":"addMentionUserToFieldWithUser:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1addMentionUserToField(user:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"addMentionUserToFieldWithUser:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}