{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"messages","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"[ChatMessage]"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/refreshmessages(messages:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/refreshmessages(messages:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/refreshMessages(messages:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message list on first load show db messages ."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"refreshMessagesWithMessages:"}],"role":"symbol","title":"refreshMessages(messages:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver(im)refreshMessagesWithMessages:","required":true,"modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatMessage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"url":"\/documentation\/easechatuikit\/chatmessage"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver/refreshMessages(messages:)":{"navigatorTitle":[{"kind":"identifier","text":"refreshMessagesWithMessages:"}],"role":"symbol","title":"refreshMessages(messages:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshMessages"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messages"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"Message list on first load show db messages ."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/refreshMessages(messages:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/easechatuikit\/imessagelistviewdriver\/refreshmessages(messages:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver":{"role":"symbol","title":"IMessageListViewDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IMessageListViewDriver"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IMessageListViewDriver"}],"url":"\/documentation\/easechatuikit\/imessagelistviewdriver"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"refreshMessagesWithMessages:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshMessagesWithMessages:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"refreshMessagesWithMessages:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<AgoraChatMessage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"messages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1refreshMessages(messages:)\/title","value":"refreshMessagesWithMessages:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1refreshMessages(messages:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"refreshMessagesWithMessages:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/title","value":"IMessageListViewDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/fragments","value":[{"kind":"identifier","text":"IMessageListViewDriver"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}