{"variants":[{"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/showmessage(message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/showmessage(message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showMessage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"showMessageWithMessage:"}],"modules":[{"name":"EaseChatUIKit"}],"required":true,"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver(im)showMessageWithMessage:","symbolKind":"method","roleHeading":"Instance Method","title":"showMessage(message:)"},"sections":[],"abstract":[{"text":"Display new message.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/showMessage(message:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showMessage"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","isActive":true}]}],"name":"message"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","title":"ChatMessage","abstract":[],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver/showMessage(message:)":{"title":"showMessage(message:)","abstract":[{"type":"text","text":"Display new message."}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/showMessage(message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showMessage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/imessagelistviewdriver\/showmessage(message:)","role":"symbol","navigatorTitle":[{"text":"showMessageWithMessage:","kind":"identifier"}],"type":"topic","required":true},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver":{"title":"IMessageListViewDriver","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IMessageListViewDriver"}],"url":"\/documentation\/easechatuikit\/imessagelistviewdriver","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"showMessageWithMessage:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showMessageWithMessage:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"showMessageWithMessage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)EMChatMessage","text":"EMChatMessage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1showMessage(message:)\/title","value":"showMessageWithMessage:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1showMessage(message:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showMessageWithMessage:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/title","value":"IMessageListViewDriver"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/fragments","value":[{"text":"IMessageListViewDriver","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}