{"abstract":[{"type":"text","text":"Update state on chat thread load messages finished."}],"variants":[{"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/updatethreadloadmessagesfinished(finished:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/imessagelistviewdriver\/updatethreadloadmessagesfinished(finished:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/updateThreadLoadMessagesFinished(finished:)"},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"updateThreadLoadMessagesFinished","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"finished"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(pl)IMessageListViewDriver(im)updateThreadLoadMessagesFinishedWithFinished:","required":true,"title":"updateThreadLoadMessagesFinished(finished:)","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"updateThreadLoadMessagesFinishedWithFinished:"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateThreadLoadMessagesFinished","kind":"identifier"},{"kind":"text","text":"("},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Bool","type":"text"}],"type":"paragraph"}],"name":"finished"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/imessagelistviewdriver","abstract":[],"role":"symbol","title":"IMessageListViewDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"IMessageListViewDriver","kind":"identifier"}],"navigatorTitle":[{"text":"IMessageListViewDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IMessageListViewDriver/updateThreadLoadMessagesFinished(finished:)":{"abstract":[{"type":"text","text":"Update state on chat thread load messages finished."}],"url":"\/documentation\/easechatuikit\/imessagelistviewdriver\/updatethreadloadmessagesfinished(finished:)","title":"updateThreadLoadMessagesFinished(finished:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IMessageListViewDriver\/updateThreadLoadMessagesFinished(finished:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateThreadLoadMessagesFinished"},{"kind":"text","text":"("},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}],"kind":"symbol","required":true,"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"updateThreadLoadMessagesFinishedWithFinished:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"updateThreadLoadMessagesFinishedWithFinished:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"finished","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"finished","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Bool"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/title","value":"IMessageListViewDriver"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/fragments","value":[{"kind":"identifier","text":"IMessageListViewDriver"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver\/navigatorTitle","value":[{"text":"IMessageListViewDriver","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1updateThreadLoadMessagesFinished(finished:)\/title","value":"updateThreadLoadMessagesFinishedWithFinished:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"updateThreadLoadMessagesFinishedWithFinished:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IMessageListViewDriver~1updateThreadLoadMessagesFinished(finished:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}