{"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}]},"variants":[{"paths":["\/documentation\/easechatuikit\/messagecellstyle\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/!=(_:_:)"],"generated":true,"anchor":"Operators","title":"Operators"}],"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle","type":"topic","role":"symbol","abstract":[{"text":"Enum representing the style of a message cell.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageCellStyle"}],"navigatorTitle":[{"kind":"identifier","text":"MessageCellStyle"}],"title":"MessageCellStyle","kind":"symbol","url":"\/documentation\/easechatuikit\/messagecellstyle"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCellStyle/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCellStyle\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","role":"symbol","url":"\/documentation\/easechatuikit\/messagecellstyle\/!=(_:_:)","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle\/title","op":"replace","value":"MessageCellStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle\/fragments","value":[{"text":"MessageCellStyle","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"MessageCellStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCellStyle\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}