{"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"title":"shared","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PopMenuKeyboardManager","text":"PopMenuKeyboardManager","kind":"typeIdentifier"}],"role":"symbol","externalID":"s:13EaseChatUIKit22PopMenuKeyboardManagerC6sharedACvpZ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuKeyboardManager","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PopMenuKeyboardManager","kind":"typeIdentifier","text":"PopMenuKeyboardManager"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/popmenukeyboardmanager\/shared"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuKeyboardManager"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuKeyboardManager\/shared","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PopMenuKeyboardManager":{"url":"\/documentation\/easechatuikit\/popmenukeyboardmanager","type":"topic","kind":"symbol","title":"PopMenuKeyboardManager","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PopMenuKeyboardManager","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuKeyboardManager","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PopMenuKeyboardManager"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PopMenuKeyboardManager/shared":{"kind":"symbol","url":"\/documentation\/easechatuikit\/popmenukeyboardmanager\/shared","title":"shared","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuKeyboardManager\/shared","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PopMenuKeyboardManager","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PopMenuKeyboardManager"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"PopMenuKeyboardManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuKeyboardManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuKeyboardManager\/fragments","value":[{"text":"PopMenuKeyboardManager","kind":"identifier"}]},{"op":"replace","value":[{"text":"PopMenuKeyboardManager","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuKeyboardManager\/navigatorTitle"}]}]}