{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LoadingView\/switchTheme(style:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" to switch theme.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","type":"reference"}],"type":"paragraph"}],"name":"style"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LoadingView","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LoadingView\/ThemeSwitchProtocol-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/loadingview\/switchtheme(style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/loadingview\/switchtheme(style:)"]}],"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)LoadingView(im)switchThemeWithStyle:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"title":"switchTheme(style:)","modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LoadingView":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"LoadingView"}],"title":"LoadingView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LoadingView","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoadingView","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/loadingview","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LoadingView/switchTheme(style:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LoadingView\/switchTheme(style:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"title":"switchTheme(style:)","type":"topic","url":"\/documentation\/easechatuikit\/loadingview\/switchtheme(style:)","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"type":"topic","abstract":[{"text":"An object containing visual configurations for the whole application.","type":"text"}],"title":"Appearance","kind":"symbol","navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","url":"\/documentation\/easechatuikit\/appearance"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle":{"type":"topic","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","type":"reference","isActive":true},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"text":" method","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","title":"ThemeStyle","kind":"symbol","url":"\/documentation\/easechatuikit\/themestyle","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/LoadingView/ThemeSwitchProtocol-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/LoadingView\/ThemeSwitchProtocol-Implementations","role":"collectionGroup","abstract":[],"title":"ThemeSwitchProtocol Implementations","kind":"article","url":"\/documentation\/easechatuikit\/loadingview\/themeswitchprotocol-implementations","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"switchThemeWithStyle:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LoadingView\/title","value":"LoadingView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LoadingView\/fragments","value":[{"text":"LoadingView","kind":"identifier"}],"op":"replace"},{"value":[{"text":"LoadingView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LoadingView\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LoadingView~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1LoadingView~1switchTheme(style:)\/fragments"},{"value":"Appearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/navigatorTitle","value":[{"text":"Appearance","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/title","op":"replace","value":"ThemeStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/fragments","op":"replace","value":[{"kind":"identifier","text":"ThemeStyle"}]},{"op":"replace","value":[{"kind":"identifier","text":"ThemeStyle"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/navigatorTitle"}]}]}