{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"s:13EaseChatUIKit17URLPreviewManagerC11HTMLContentC8imageURLSSSgvp","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol","title":"imageURL","symbolKind":"property"},"variants":[{"paths":["\/documentation\/easechatuikit\/urlpreviewmanager\/htmlcontent\/imageurl"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent\/imageURL"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager/HTMLContent/imageURL":{"role":"symbol","type":"topic","title":"imageURL","kind":"symbol","url":"\/documentation\/easechatuikit\/urlpreviewmanager\/htmlcontent\/imageurl","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent\/imageURL"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager/HTMLContent":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTMLContent","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/urlpreviewmanager\/htmlcontent","role":"symbol","title":"URLPreviewManager.HTMLContent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent","navigatorTitle":[{"kind":"identifier","text":"HTMLContent"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager":{"role":"symbol","type":"topic","title":"URLPreviewManager","kind":"symbol","url":"\/documentation\/easechatuikit\/urlpreviewmanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewManager","kind":"identifier"}],"navigatorTitle":[{"text":"URLPreviewManager","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/title","value":"URLPreviewManager"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/fragments","value":[{"text":"URLPreviewManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/navigatorTitle","value":[{"text":"URLPreviewManager","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}