{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent\/towards","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/urlpreviewmanager\/htmlcontent\/towards"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"towards","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","text":"BubbleTowards"}]}],"kind":"declarations"}],"metadata":{"externalID":"s:13EaseChatUIKit17URLPreviewManagerC11HTMLContentC7towardsAA13BubbleTowardsOvp","title":"towards","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"towards"},{"kind":"text","text":": "},{"text":"BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","kind":"typeIdentifier"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property","roleHeading":"Instance Property"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager/HTMLContent":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HTMLContent","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/urlpreviewmanager\/htmlcontent","role":"symbol","title":"URLPreviewManager.HTMLContent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent","navigatorTitle":[{"kind":"identifier","text":"HTMLContent"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager/HTMLContent/towards":{"url":"\/documentation\/easechatuikit\/urlpreviewmanager\/htmlcontent\/towards","title":"towards","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"towards","kind":"identifier"},{"kind":"text","text":": "},{"text":"BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","kind":"typeIdentifier"}],"type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/HTMLContent\/towards"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/BubbleTowards":{"role":"symbol","type":"topic","title":"BubbleTowards","kind":"symbol","url":"\/documentation\/easechatuikit\/bubbletowards","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}],"navigatorTitle":[{"text":"BubbleTowards","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager":{"role":"symbol","type":"topic","title":"URLPreviewManager","kind":"symbol","url":"\/documentation\/easechatuikit\/urlpreviewmanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewManager","kind":"identifier"}],"navigatorTitle":[{"text":"URLPreviewManager","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/title","value":"BubbleTowards"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/fragments","value":[{"text":"BubbleTowards","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/navigatorTitle","value":[{"kind":"identifier","text":"BubbleTowards"}]},{"value":"URLPreviewManager","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/title"},{"value":[{"text":"URLPreviewManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/navigatorTitle","value":[{"kind":"identifier","text":"URLPreviewManager"}]}]}]}