{"sections":[],"metadata":{"externalID":"s:13EaseChatUIKit15ContactCardViewC6avatarAA05ImageF0Cvp","symbolKind":"property","role":"symbol","title":"avatar","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","text":"ImageView","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView\/avatar"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/contactcardview\/avatar"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"avatar","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView","kind":"typeIdentifier","text":"ImageView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCardView/avatar":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView\/avatar","title":"avatar","url":"\/documentation\/easechatuikit\/contactcardview\/avatar","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avatar","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ImageView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ImageView":{"abstract":[{"text":"A subclass of ","type":"text"},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":" that provides a method for loading an image from a URL."}],"url":"\/documentation\/easechatuikit\/imageview","navigatorTitle":[{"kind":"identifier","text":"ImageView"}],"title":"ImageView","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ImageView","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCardView":{"role":"symbol","type":"topic","title":"ContactCardView","kind":"symbol","url":"\/documentation\/easechatuikit\/contactcardview","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactCardView"}],"navigatorTitle":[{"kind":"identifier","text":"ContactCardView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/title","value":"ImageView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/fragments","value":[{"text":"ImageView","kind":"identifier"}]},{"value":[{"text":"ImageView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ImageView\/navigatorTitle"},{"value":"ContactCardView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCardView\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ContactCardView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCardView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCardView\/navigatorTitle","op":"replace","value":[{"text":"ContactCardView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}