{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactcardview\/init(coder:)"]},{"paths":["\/documentation\/easechatuikit\/contactcardview\/init(coder:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView\/init(coder:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","text":"NSCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"init","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Initializer","title":"init(coder:)","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactCardView(im)initWithCoder:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCardView/init(coder:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView\/init(coder:)","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/contactcardview\/init(coder:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactCardView":{"role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactCardView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/contactcardview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactCardView"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactCardView","title":"ContactCardView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithCoder:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coder"},{"text":";","kind":"text"}]}]}},{"value":"initWithCoder:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCardView~1init(coder:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCardView~1init(coder:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCardView\/title","op":"replace","value":"ContactCardView"},{"value":[{"kind":"identifier","text":"ContactCardView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactCardView\/fragments","op":"replace"}]}]}