{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FileMessageCell\/init(towards:reuseIdentifier:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/filemessagecell\/init(towards:reuseidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/filemessagecell\/init(towards:reuseidentifier:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FileMessageCell"]]},"abstract":[{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","isActive":true},{"type":"text","text":" required init method."}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)FileMessageCell(im)initWithTowards:reuseIdentifier:","symbolKind":"init","role":"symbol","title":"init(towards:reuseIdentifier:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"towards","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards"},{"kind":"text","text":", "},{"text":"reuseIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"required","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"towards"},{"kind":"text","text":": "},{"text":"BubbleTowards","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards"},{"kind":"text","text":", "},{"text":"reuseIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"towards","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","isActive":true},{"type":"text","text":" is towards of the bubble."}]}]},{"name":"reuseIdentifier","content":[{"inlineContent":[{"type":"text","text":"Cell reuse identifier."}],"type":"paragraph"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/FileMessageCell":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FileMessageCell","navigatorTitle":[{"text":"FileMessageCell","kind":"identifier"}],"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FileMessageCell","kind":"identifier"}],"title":"FileMessageCell","role":"symbol","url":"\/documentation\/easechatuikit\/filemessagecell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/FileMessageCell/init(towards:reuseIdentifier:)":{"abstract":[{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","isActive":true,"type":"reference"},{"type":"text","text":" required init method."}],"kind":"symbol","url":"\/documentation\/easechatuikit\/filemessagecell\/init(towards:reuseidentifier:)","type":"topic","title":"init(towards:reuseIdentifier:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/FileMessageCell\/init(towards:reuseIdentifier:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"towards"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","text":"BubbleTowards","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reuseIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/BubbleTowards":{"title":"BubbleTowards","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BubbleTowards","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/bubbletowards","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","navigatorTitle":[{"text":"BubbleTowards","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"url":"\/documentation\/easechatuikit\/messagecell","role":"symbol","abstract":[],"type":"topic","kind":"symbol","title":"MessageCell","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageCell"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithTowards:reuseIdentifier:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTowards:reuseIdentifier:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithTowards:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"BubbleTowards","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards"},{"kind":"text","text":") "},{"text":"towards","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"reuseIdentifier:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"reuseIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"FileMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FileMessageCell\/title"},{"op":"replace","value":[{"text":"FileMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FileMessageCell\/fragments"},{"value":"initWithTowards:reuseIdentifier:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FileMessageCell~1init(towards:reuseIdentifier:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTowards:reuseIdentifier:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1FileMessageCell~1init(towards:reuseIdentifier:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/title","value":"BubbleTowards","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/fragments","op":"replace","value":[{"text":"BubbleTowards","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","value":"MessageCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","op":"replace","value":[{"text":"MessageCell","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}