{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Case","externalID":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType@GroupChatThreadEventTypeCreated","role":"symbol","title":"GroupChatThreadEventType.created","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventTypeCreated"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType\/created"},"variants":[{"paths":["\/documentation\/easechatuikit\/groupchatthreadeventtype\/created"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupchatthreadeventtype\/created"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"created"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType":{"navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","url":"\/documentation\/easechatuikit\/groupchatthreadeventtype","role":"symbol","abstract":[],"title":"GroupChatThreadEventType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GroupChatThreadEventType","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType/created":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType\/created","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventTypeCreated"}],"title":"GroupChatThreadEventType.created","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"created","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupchatthreadeventtype\/created"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"GroupChatThreadEventTypeCreated","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"GroupChatThreadEventTypeCreated","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"GroupChatThreadEventTypeCreated","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"GroupChatThreadEventType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType~1created\/title","value":"GroupChatThreadEventTypeCreated"},{"op":"replace","value":[{"text":"GroupChatThreadEventTypeCreated","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType~1created\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}