{"metadata":{"navigatorTitle":[{"text":"GroupChatThreadEventTypeUpdated","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"title":"GroupChatThreadEventType.updated","role":"symbol","externalID":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType@GroupChatThreadEventTypeUpdated","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updated"}],"symbolKind":"case","roleHeading":"Case"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType\/updated"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"updated","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupchatthreadeventtype\/updated"]},{"paths":["\/documentation\/easechatuikit\/groupchatthreadeventtype\/updated"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType/updated":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"updated","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType\/updated","title":"GroupChatThreadEventType.updated","url":"\/documentation\/easechatuikit\/groupchatthreadeventtype\/updated","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventTypeUpdated"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType":{"navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/groupchatthreadeventtype","title":"GroupChatThreadEventType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupChatThreadEventType"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"GroupChatThreadEventTypeUpdated"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"GroupChatThreadEventTypeUpdated","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"GroupChatThreadEventTypeUpdated","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"GroupChatThreadEventTypeUpdated","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType~1updated\/title"},{"value":[{"text":"GroupChatThreadEventTypeUpdated","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType~1updated\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/title","value":"GroupChatThreadEventType"},{"value":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}