{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType\/userKicked","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/groupchatthreadeventtype\/userkicked"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupchatthreadeventtype\/userkicked"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userKicked"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"userKicked"}],"roleHeading":"Case","symbolKind":"case","navigatorTitle":[{"text":"GroupChatThreadEventTypeUserKicked","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType@GroupChatThreadEventTypeUserKicked","title":"GroupChatThreadEventType.userKicked","modules":[{"name":"EaseChatUIKit"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType/userKicked":{"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"userKicked"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventTypeUserKicked"}],"url":"\/documentation\/easechatuikit\/groupchatthreadeventtype\/userkicked","role":"symbol","type":"topic","title":"GroupChatThreadEventType.userKicked","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType\/userKicked"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType":{"navigatorTitle":[{"text":"GroupChatThreadEventType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","url":"\/documentation\/easechatuikit\/groupchatthreadeventtype","role":"symbol","abstract":[],"title":"GroupChatThreadEventType","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"GroupChatThreadEventType","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"GroupChatThreadEventTypeUserKicked","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"GroupChatThreadEventTypeUserKicked","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"GroupChatThreadEventTypeUserKicked"}]}]}},{"value":"GroupChatThreadEventTypeUserKicked","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType~1userKicked\/title"},{"op":"replace","value":[{"text":"GroupChatThreadEventTypeUserKicked","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType~1userKicked\/fragments"},{"value":"GroupChatThreadEventType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/title","op":"replace"},{"value":[{"text":"GroupChatThreadEventType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}