{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/init","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)URLPreviewManager(im)init","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/urlpreviewmanager\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager/init":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager\/init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/urlpreviewmanager\/init","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/URLPreviewManager":{"role":"symbol","type":"topic","title":"URLPreviewManager","kind":"symbol","url":"\/documentation\/easechatuikit\/urlpreviewmanager","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"URLPreviewManager","kind":"identifier"}],"navigatorTitle":[{"text":"URLPreviewManager","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/URLPreviewManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"URLPreviewManager","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/fragments","op":"replace","value":[{"kind":"identifier","text":"URLPreviewManager"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1URLPreviewManager\/navigatorTitle","value":[{"kind":"identifier","text":"URLPreviewManager"}]}]}]}