{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatmessagestatus\/read"]},{"paths":["\/documentation\/easechatuikit\/chatmessagestatus\/read"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"EaseChatUIKit"}],"title":"ChatMessageStatus.read","externalID":"c:@M@EaseChatUIKit@E@ChatMessageStatus@ChatMessageStatusRead","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"ChatMessageStatusRead","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus\/read"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","abstract":[],"title":"ChatMessage","url":"\/documentation\/easechatuikit\/chatmessage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessage","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessageStatus":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus","role":"symbol","navigatorTitle":[{"text":"ChatMessageStatus","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatmessagestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMessageStatus","kind":"identifier"}],"abstract":[{"text":"The status of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},{"type":"text","text":"."}],"title":"ChatMessageStatus"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessageStatus/read":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatmessagestatus\/read","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus\/read","navigatorTitle":[{"text":"ChatMessageStatusRead","kind":"identifier"}],"abstract":[],"title":"ChatMessageStatus.read"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"ChatMessageStatusRead","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"ChatMessageStatusRead"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"ChatMessageStatusRead","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ChatMessageStatus","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus\/fragments","value":[{"kind":"identifier","text":"ChatMessageStatus"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus~1read\/title","value":"ChatMessageStatusRead"},{"value":[{"text":"ChatMessageStatusRead","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus~1read\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}