{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"sending","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatmessagestatus\/sending"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatmessagestatus\/sending"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus\/sending"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"ChatMessageStatus.sending","role":"symbol","roleHeading":"Case","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sending"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@E@ChatMessageStatus@ChatMessageStatusSending","navigatorTitle":[{"kind":"identifier","text":"ChatMessageStatusSending"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessageStatus/sending":{"abstract":[],"title":"ChatMessageStatus.sending","url":"\/documentation\/easechatuikit\/chatmessagestatus\/sending","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus\/sending","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"sending","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ChatMessageStatusSending","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","abstract":[],"title":"ChatMessage","url":"\/documentation\/easechatuikit\/chatmessage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessage","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessageStatus":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus","role":"symbol","navigatorTitle":[{"text":"ChatMessageStatus","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatmessagestatus","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatMessageStatus","kind":"identifier"}],"abstract":[{"text":"The status of ","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},{"type":"text","text":"."}],"title":"ChatMessageStatus"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ChatMessageStatusSending","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatMessageStatusSending"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"ChatMessageStatusSending","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus~1sending\/title","value":"ChatMessageStatusSending"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus~1sending\/fragments","value":[{"text":"ChatMessageStatusSending","kind":"identifier"}]},{"op":"replace","value":"ChatMessageStatus","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus\/fragments","value":[{"text":"ChatMessageStatus","kind":"identifier"}]}]}]}