{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(cleanCacheWithType:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanCache"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","text":"EaseChatUIKitCacheType"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"type","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","type":"reference","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext\/cleanCache(type:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Clean the cache of "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","isActive":true,"type":"reference"},{"type":"text","text":" type"}],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/easechatuikitcontext\/cleancache(type:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/easechatuikitcontext\/cleancache(type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"cleanCache(type:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"cleanCacheWithType:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanCache"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"EaseChatUIKitCacheType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType"},{"text":")","kind":"text"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitContext(im)cleanCacheWithType:","symbolKind":"method"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitCacheType":{"url":"\/documentation\/easechatuikit\/easechatuikitcachetype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"type":"topic","title":"EaseChatUIKitCacheType","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitContext":{"title":"EaseChatUIKitContext","url":"\/documentation\/easechatuikit\/easechatuikitcontext","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EaseChatUIKitContext","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"EaseChatUIKitContext","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitContext/cleanCache(type:)":{"url":"\/documentation\/easechatuikit\/easechatuikitcontext\/cleancache(type:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cleanCache"},{"text":"(","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType","text":"EaseChatUIKitCacheType"},{"text":")","kind":"text"}],"type":"topic","title":"cleanCache(type:)","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext\/cleanCache(type:)","abstract":[{"type":"text","text":"Clean the cache of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","isActive":true},{"text":" type","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cleanCacheWithType:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"cleanCacheWithType:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cleanCacheWithType:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"cleanCacheWithType:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","text":"EaseChatUIKitCacheType"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/title","value":"EaseChatUIKitCacheType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/fragments","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext\/title","value":"EaseChatUIKitContext"},{"op":"replace","value":[{"kind":"identifier","text":"EaseChatUIKitContext"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext\/fragments"},{"value":"cleanCacheWithType:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext~1cleanCache(type:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"cleanCacheWithType:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext~1cleanCache(type:)\/fragments","op":"replace"}]}]}