{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMemberAttributeCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache","text":"GroupMemberAttributesCache"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/easechatuikitcontext\/groupmemberattributecache"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/easechatuikitcontext\/groupmemberattributecache"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext\/groupMemberAttributeCache","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cache object of group member’s display properties"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMemberAttributeCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupMemberAttributesCache","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache"},{"kind":"text","text":"?"}],"title":"groupMemberAttributeCache","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitContext(py)groupMemberAttributeCache","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"groupMemberAttributeCache"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitContext":{"role":"symbol","title":"EaseChatUIKitContext","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatUIKitContext"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitContext"}],"url":"\/documentation\/easechatuikit\/easechatuikitcontext"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupMemberAttributesCache":{"role":"symbol","title":"GroupMemberAttributesCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupMemberAttributesCache"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupMemberAttributesCache"}],"url":"\/documentation\/easechatuikit\/groupmemberattributescache"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitContext/groupMemberAttributeCache":{"role":"symbol","title":"groupMemberAttributeCache","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMemberAttributeCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupMemberAttributesCache","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Cache object of group member’s display properties"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitContext\/groupMemberAttributeCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupMemberAttributeCache"}],"url":"\/documentation\/easechatuikit\/easechatuikitcontext\/groupmemberattributecache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"groupMemberAttributeCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"groupMemberAttributeCache"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupMemberAttributesCache","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)GroupMemberAttributesCache","text":"GroupMemberAttributesCache"},{"kind":"text","text":" * "},{"kind":"identifier","text":"groupMemberAttributeCache"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext\/title","value":"EaseChatUIKitContext"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitContext"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/title","value":"GroupMemberAttributesCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupMemberAttributesCache\/fragments","value":[{"kind":"identifier","text":"GroupMemberAttributesCache"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext~1groupMemberAttributeCache\/title","value":"groupMemberAttributeCache"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitContext~1groupMemberAttributeCache\/fragments","value":[{"kind":"identifier","text":"groupMemberAttributeCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}