{"sections":[],"abstract":[{"type":"text","text":"Creates a navigation bar for the MessageListController."}],"metadata":{"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatThreadViewController(im)createNavigation","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"createNavigation"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createNavigation"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","text":"EaseChatNavigationBar"}],"title":"createNavigation()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createNavigation","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","text":"EaseChatNavigationBar"}]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"An instance of EaseChatNavigationBar.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/createnavigation()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/createnavigation()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/createNavigation()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EaseChatNavigationBar","kind":"identifier"}],"navigatorTitle":[{"text":"EaseChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the EaseChatUIKit."}],"kind":"symbol","title":"EaseChatNavigationBar","url":"\/documentation\/easechatuikit\/easechatnavigationbar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/createNavigation()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/createNavigation()","abstract":[{"type":"text","text":"Creates a navigation bar for the MessageListController."}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/createnavigation()","navigatorTitle":[{"text":"createNavigation","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createNavigation","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"EaseChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"}],"kind":"symbol","type":"topic","title":"createNavigation()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"type":"topic","title":"ChatThreadViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createNavigation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"createNavigation","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"EaseChatNavigationBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createNavigation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/title","value":"EaseChatNavigationBar","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/fragments","op":"replace","value":[{"text":"EaseChatNavigationBar","kind":"identifier"}]},{"value":"createNavigation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1createNavigation()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"createNavigation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1createNavigation()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}]}]}]}