{"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewController(im)documentPicker:didPickDocumentsAtURLs:","symbolKind":"method","role":"symbol","title":"documentPicker(_:didPickDocumentsAt:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"documentPicker:didPickDocumentsAtURLs:"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"documentPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIDocumentPickerViewController","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"didPickDocumentsAt","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"])","kind":"text"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/documentPicker(_:didPickDocumentsAt:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIDocumentPickerDelegate.documentPicker(_:didPickDocumentsAt:)"},{"type":"text","text":"."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"documentPicker","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"controller"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPickDocumentsAt"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"urls"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"])","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/UIDocumentPickerDelegate-Implementations"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/documentpicker(_:didpickdocumentsat:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/documentpicker(_:didpickdocumentsat:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/UIDocumentPickerDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/uidocumentpickerdelegate-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/UIDocumentPickerDelegate-Implementations","role":"collectionGroup","title":"UIDocumentPickerDelegate Implementations","kind":"article","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/documentPicker(_:didPickDocumentsAt:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/documentPicker(_:didPickDocumentsAt:)","role":"symbol","title":"documentPicker(_:didPickDocumentsAt:)","navigatorTitle":[{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/documentpicker(_:didpickdocumentsat:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentPicker"},{"text":"(","kind":"text"},{"text":"UIDocumentPickerViewController","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didPickDocumentsAt"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"])"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"title":"ChatThreadViewController","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"documentPicker:didPickDocumentsAtURLs:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"documentPicker:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPickDocumentsAtURLs:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSURL *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"urls"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1documentPicker(_:didPickDocumentsAt:)\/title","value":"documentPicker:didPickDocumentsAtURLs:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1documentPicker(_:didPickDocumentsAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentPicker:didPickDocumentsAtURLs:","kind":"identifier"}],"op":"replace"},{"value":"ChatThreadViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title"},{"value":[{"kind":"identifier","text":"ChatThreadViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments"}]}]}