{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentPickerWasCancelled"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/documentPickerWasCancelled(_:)"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/documentpickerwascancelled(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/documentpickerwascancelled(_:)"]}],"kind":"symbol","metadata":{"extendedModule":"EaseChatUIKit","title":"documentPickerWasCancelled(_:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"documentPickerWasCancelled:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPickerWasCancelled","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewController(im)documentPickerWasCancelled:","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/UIDocumentPickerDelegate-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIDocumentPickerDelegate.documentPickerWasCancelled(_:)"},{"text":".","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"title":"ChatThreadViewController","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/UIDocumentPickerDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/uidocumentpickerdelegate-implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/UIDocumentPickerDelegate-Implementations","role":"collectionGroup","title":"UIDocumentPickerDelegate Implementations","kind":"article","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/documentPickerWasCancelled(_:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/documentPickerWasCancelled(_:)","role":"symbol","title":"documentPickerWasCancelled(_:)","navigatorTitle":[{"kind":"identifier","text":"documentPickerWasCancelled:"}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/documentpickerwascancelled(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentPickerWasCancelled","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController"},{"kind":"text","text":")"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"documentPickerWasCancelled:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentPickerWasCancelled:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"documentPickerWasCancelled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIDocumentPickerViewController","text":"UIDocumentPickerViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace"},{"value":"documentPickerWasCancelled:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1documentPickerWasCancelled(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1documentPickerWasCancelled(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"documentPickerWasCancelled:","kind":"identifier"}]}]}]}