{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imagePickerController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"picker"},{"text":": ","kind":"text"},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishPickingMediaWithInfo","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"info"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","text":"InfoKey","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)"]}],"metadata":{"symbolKind":"method","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewController(im)imagePickerController:didFinishPickingMediaWithInfo:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imagePickerController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"InfoKey","preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"])","kind":"text"}],"modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/UIImagePickerControllerDelegate-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIImagePickerControllerDelegate.imagePickerController(_:didFinishPickingMediaWithInfo:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","title":"ChatThreadViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatThreadViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/UIImagePickerControllerDelegate-Implementations":{"kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/UIImagePickerControllerDelegate-Implementations","title":"UIImagePickerControllerDelegate Implementations","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/uiimagepickercontrollerdelegate-implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imagePickerController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","kind":"typeIdentifier","text":"InfoKey"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"])"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"imagePickerController:didFinishPickingMediaWithInfo:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"imagePickerController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController"},{"kind":"text","text":" *) "},{"text":"picker","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"didFinishPickingMediaWithInfo:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,id>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController","op":"replace"},{"value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/navigatorTitle","value":[{"kind":"identifier","text":"ChatThreadViewController"}],"op":"replace"},{"op":"replace","value":"imagePickerController:didFinishPickingMediaWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"op":"replace"}]}]}