{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/onInputBoxEventsOccur(action:attributeText:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/oninputboxeventsoccur(action:attributetext:)"]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/oninputboxeventsoccur(action:attributetext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"text":"MessageInputBarActionType","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"attributeText","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"text":"?)","kind":"text"}],"title":"onInputBoxEventsOccur(action:attributeText:)","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewController(im)onInputBoxEventsOccurWithAction:attributeText:","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/MessageListDriverEventsListener-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onInputBoxEventsOccur","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":" "},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]}]},{"parameters":[{"name":"type","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","isActive":true}]}]},{"name":"attributeText","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Text view’s attributeText"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/onInputBoxEventsOccur(action:attributeText:)":{"role":"symbol","navigatorTitle":[{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccur"},{"text":"(","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/oninputboxeventsoccur(action:attributetext:)","title":"onInputBoxEventsOccur(action:attributeText:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/onInputBoxEventsOccur(action:attributeText:)","abstract":[{"type":"text","text":"The method will call on input menu bar actioned."}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/MessageListDriverEventsListener-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/messagelistdrivereventslistener-implementations","title":"MessageListDriverEventsListener Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/MessageListDriverEventsListener-Implementations","type":"topic","abstract":[],"kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"type":"topic","title":"ChatThreadViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBarActionType":{"role":"symbol","navigatorTitle":[{"text":"MessageInputBarActionType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageInputBarActionType","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messageinputbaractiontype","title":"MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onInputBoxEventsOccurWithAction:attributeText:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onInputBoxEventsOccurWithAction:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"type","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"attributeText:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"attributeText"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1onInputBoxEventsOccur(action:attributeText:)\/title","value":"onInputBoxEventsOccurWithAction:attributeText:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"onInputBoxEventsOccurWithAction:attributeText:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1onInputBoxEventsOccur(action:attributeText:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","op":"replace","value":"ChatThreadViewController"},{"op":"replace","value":[{"text":"ChatThreadViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/title","op":"replace","value":"MessageInputBarActionType"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/fragments","value":[{"kind":"identifier","text":"MessageInputBarActionType"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}