{"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewController(im)previewController:previewItemAtIndex:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"previewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController","text":"QLPreviewController"},{"text":", ","kind":"text"},{"text":"previewItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> "},{"text":"QLPreviewItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"title":"previewController(_:previewItemAt:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"QLPreviewControllerDataSource.previewController(_:previewItemAt:)"},{"text":".","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/previewcontroller(_:previewitemat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/previewcontroller(_:previewitemat:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"previewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"previewItemAt","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"QLPreviewItem","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/QLPreviewControllerDataSource-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/QLPreviewControllerDataSource-Implementations":{"role":"collectionGroup","title":"QLPreviewControllerDataSource Implementations","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/qlpreviewcontrollerdatasource-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/QLPreviewControllerDataSource-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/previewController(_:previewItemAt:)":{"title":"previewController(_:previewItemAt:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/previewcontroller(_:previewitemat:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"previewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"QLPreviewController","preciseIdentifier":"c:objc(cs)QLPreviewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewItemAt","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") -> ","kind":"text"},{"text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"previewController:previewItemAtIndex:"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"type":"topic","title":"ChatThreadViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"previewController:previewItemAtIndex:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"previewController:previewItemAtIndex:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Qoobjc(pl)QLPreviewItem","kind":"typeIdentifier","text":"id<QLPreviewItem>"},{"kind":"text","text":") "},{"kind":"identifier","text":"previewController:"},{"kind":"text","text":"("},{"text":"QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":" "},{"text":"previewItemAtIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"previewController:previewItemAtIndex:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1previewController(_:previewItemAt:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1previewController(_:previewItemAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"previewController:previewItemAtIndex:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments","op":"replace","value":[{"text":"ChatThreadViewController","kind":"identifier"}]}]}]}