{"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/numberOfPreviewItems(in:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)"],"title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/qlpreviewcontrollerdatasource-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/qlpreviewcontrollerdatasource-implementations"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/QLPreviewControllerDataSource-Implementations"},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"QLPreviewControllerDataSource Implementations","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController"]]},"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"title":"ChatThreadViewController","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/previewController(_:previewItemAt:)":{"navigatorTitle":[{"text":"previewController:previewItemAtIndex:","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/previewcontroller(_:previewitemat:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previewController"},{"text":"(","kind":"text"},{"text":"QLPreviewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController"},{"kind":"text","text":", "},{"text":"previewItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"QLPreviewItem","preciseIdentifier":"c:objc(pl)QLPreviewItem"}],"title":"previewController(_:previewItemAt:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)","abstract":[],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/numberOfPreviewItems(in:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"numberOfPreviewItems","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)QLPreviewController","text":"QLPreviewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/numberOfPreviewItems(in:)","title":"numberOfPreviewItems(in:)","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/numberofpreviewitems(in:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"numberOfPreviewItemsInPreviewController:"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/numberOfPreviewItems(in:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/previewController(_:previewItemAt:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"value":"previewController:previewItemAtIndex:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1previewController(_:previewItemAt:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1previewController(_:previewItemAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"previewController:previewItemAtIndex:","kind":"identifier"}]},{"value":"numberOfPreviewItemsInPreviewController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1numberOfPreviewItems(in:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"numberOfPreviewItemsInPreviewController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1numberOfPreviewItems(in:)\/fragments"}]}]}