{"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/showmessagelongpressedmenuwitharrow(cell:items:header:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/showmessagelongpressedmenuwitharrow(cell:items:header:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showMessageLongPressedMenuWithArrow","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cell"},{"text":": ","kind":"text"},{"text":"MessageCell","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":", "},{"text":"items","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","kind":"typeIdentifier","text":"ActionSheetItemProtocol"},{"kind":"text","text":"], "},{"text":"header","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/showMessageLongPressedMenuWithArrow(cell:items:header:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewController(im)showMessageLongPressedMenuWithArrowWithCell:items:header:","navigatorTitle":[{"text":"showMessageLongPressedMenuWithArrowWithCell:items:header:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showMessageLongPressedMenuWithArrow","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cell"},{"kind":"text","text":": "},{"text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"items","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"ActionSheetItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"header"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"text":"?)","kind":"text"}],"extendedModule":"EaseChatUIKit","role":"symbol","title":"showMessageLongPressedMenuWithArrow(cell:items:header:)"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","title":"ChatThreadViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatThreadViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/showMessageLongPressedMenuWithArrow(cell:items:header:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/showmessagelongpressedmenuwitharrow(cell:items:header:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"showMessageLongPressedMenuWithArrowWithCell:items:header:"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"showMessageLongPressedMenuWithArrow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cell","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":", "},{"kind":"externalParam","text":"items"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":"], "},{"text":"header","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIView","preciseIdentifier":"c:objc(cs)UIView","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"showMessageLongPressedMenuWithArrow(cell:items:header:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/showMessageLongPressedMenuWithArrow(cell:items:header:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol":{"abstract":[{"text":"A protocol that defines properties and methods for an action sheet item.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/actionsheetitemprotocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","title":"ActionSheetItemProtocol","navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagecell","role":"symbol","title":"MessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"showMessageLongPressedMenuWithArrowWithCell:items:header:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showMessageLongPressedMenuWithArrowWithCell:items:header:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"showMessageLongPressedMenuWithArrowWithCell:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell"},{"kind":"text","text":" *) "},{"text":"cell","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"items:"},{"kind":"text","text":"("},{"text":"NSArray<id<ActionSheetItemProtocol>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"items","kind":"internalParam"},{"kind":"text","text":" "},{"text":"header:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView","text":"UIView"},{"kind":"text","text":" *) "},{"text":"header","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"ChatThreadViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/navigatorTitle"},{"value":"showMessageLongPressedMenuWithArrowWithCell:items:header:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1showMessageLongPressedMenuWithArrow(cell:items:header:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showMessageLongPressedMenuWithArrowWithCell:items:header:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1showMessageLongPressedMenuWithArrow(cell:items:header:)\/fragments","op":"replace"},{"value":"ActionSheetItemProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/fragments","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","value":"MessageCell"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","op":"replace","value":[{"text":"MessageCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/navigatorTitle","value":[{"text":"MessageCell","kind":"identifier"}],"op":"replace"}]}]}