{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/showMoreActions()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showMoreActions","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewController(im)showMoreActions","title":"showMoreActions()","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"showMoreActions","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/showmoreactions()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/showmoreactions()"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"showMoreActions","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"title":"ChatThreadViewController","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/showMoreActions()":{"url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/showmoreactions()","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/showMoreActions()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"showMoreActions"},{"text":"()","kind":"text"}],"title":"showMoreActions()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"showMoreActions","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"showMoreActions"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"showMoreActions"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"showMoreActions","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ChatThreadViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments","value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"showMoreActions","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1showMoreActions()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"showMoreActions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1showMoreActions()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}