{"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/switchTheme(style:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/ThemeSwitchProtocol-Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"ThemeSwitchProtocol Implementations","modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","roleHeading":"API Collection"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/switchTheme(style:)":{"title":"switchTheme(style:)","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/switchtheme(style:)","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/switchTheme(style:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"title":"ChatThreadViewController","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/switchTheme(style:)"],"generated":true}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":"switchThemeWithStyle:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1switchTheme(style:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1switchTheme(style:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title","value":"ChatThreadViewController","op":"replace"},{"value":[{"text":"ChatThreadViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments"}]}]}