{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/UIImagePickerControllerDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController"]]},"metadata":{"role":"collectionGroup","title":"UIImagePickerControllerDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}]},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/uiimagepickercontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewcontroller\/uiimagepickercontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerControllerDidCancel(_:)"],"generated":true,"title":"Instance Methods"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/imagePickerControllerDidCancel(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imagePickerControllerDidCancel","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerControllerDidCancel(_:)","type":"topic","navigatorTitle":[{"text":"imagePickerControllerDidCancel:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/imagepickercontrollerdidcancel(_:)","title":"imagePickerControllerDidCancel(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController/imagePickerController(_:didFinishPickingMediaWithInfo:)":{"role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller\/imagepickercontroller(_:didfinishpickingmediawithinfo:)","title":"imagePickerController(_:didFinishPickingMediaWithInfo:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePickerController"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImagePickerController","text":"UIImagePickerController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishPickingMediaWithInfo"},{"text":": [","kind":"text"},{"text":"UIImagePickerController","preciseIdentifier":"c:objc(cs)UIImagePickerController","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@T@UIImagePickerControllerInfoKey","kind":"typeIdentifier","text":"InfoKey"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"imagePickerController:didFinishPickingMediaWithInfo:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewController":{"title":"ChatThreadViewController","url":"\/documentation\/easechatuikit\/chatthreadviewcontroller","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewController"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerController(_:didFinishPickingMediaWithInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewController\/imagePickerControllerDidCancel(_:)"],"generated":true,"title":"Instance Methods"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1imagePickerControllerDidCancel(_:)\/title","op":"replace","value":"imagePickerControllerDidCancel:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1imagePickerControllerDidCancel(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imagePickerControllerDidCancel:","kind":"identifier"}]},{"value":"imagePickerController:didFinishPickingMediaWithInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePickerController:didFinishPickingMediaWithInfo:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController~1imagePickerController(_:didFinishPickingMediaWithInfo:)\/fragments"},{"value":"ChatThreadViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}