{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/contentAttributes(content:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAttributes","kind":"identifier"},{"kind":"text","text":"("},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"AlertView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView"}],"languages":["swift"]}]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"contentAttributes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)AlertView(im)contentAttributesWithContent:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"contentAttributesWithContent:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","title":"contentAttributes(content:)"},"variants":[{"paths":["\/documentation\/easechatuikit\/alertview\/contentattributes(content:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/alertview\/contentattributes(content:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"]]},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView/contentAttributes(content:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contentAttributes","kind":"identifier"},{"text":"(","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSAttributedString","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","text":"AlertView"}],"url":"\/documentation\/easechatuikit\/alertview\/contentattributes(content:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"contentAttributesWithContent:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/contentAttributes(content:)","abstract":[],"title":"contentAttributes(content:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","abstract":[],"role":"symbol","title":"AlertView","url":"\/documentation\/easechatuikit\/alertview"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"contentAttributesWithContent:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"contentAttributesWithContent:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","text":"AlertView"},{"kind":"text","text":" *) "},{"text":"contentAttributesWithContent:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"content"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1contentAttributes(content:)\/title","value":"contentAttributesWithContent:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1contentAttributes(content:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"contentAttributesWithContent:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title","value":"AlertView"},{"value":[{"text":"AlertView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}