{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"rightButtonWithColor:"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)AlertView(im)rightButtonWithColor:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rightButton","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?) -> ","kind":"text"},{"text":"AlertView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"rightButton(color:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/rightButton(color:)"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/alertview\/rightbutton(color:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/alertview\/rightbutton(color:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rightButton","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"color"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?) -> ","kind":"text"},{"text":"AlertView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","kind":"typeIdentifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView/rightButton(color:)":{"title":"rightButton(color:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightButton"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"AlertView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView"}],"url":"\/documentation\/easechatuikit\/alertview\/rightbutton(color:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"rightButtonWithColor:"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/rightButton(color:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"title":"AlertView","abstract":[],"url":"\/documentation\/easechatuikit\/alertview","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"rightButtonWithColor:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"rightButtonWithColor:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"AlertView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rightButtonWithColor:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"color","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"rightButtonWithColor:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1rightButton(color:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1rightButton(color:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightButtonWithColor:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title","value":"AlertView"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}]}]}]}