{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/rightButtonRadius(cornerRadius:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rightButtonRadius","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CornerRadius","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CornerRadius","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit12CornerRadiusO"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/alertview\/rightbuttonradius(cornerradius:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"]]},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightButtonRadius","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit12CornerRadiusO","text":"CornerRadius","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView","kind":"typeIdentifier"}],"role":"symbol","title":"rightButtonRadius(cornerRadius:)","symbolKind":"method","externalID":"s:13EaseChatUIKit9AlertViewC17rightButtonRadius06cornerH0AcA06CornerH0O_tF","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView/rightButtonRadius(cornerRadius:)":{"title":"rightButtonRadius(cornerRadius:)","kind":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/alertview\/rightbuttonradius(cornerradius:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/rightButtonRadius(cornerRadius:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightButtonRadius","kind":"identifier"},{"kind":"text","text":"("},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit12CornerRadiusO","kind":"typeIdentifier","text":"CornerRadius"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","title":"AlertView","kind":"symbol","url":"\/documentation\/easechatuikit\/alertview","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CornerRadius":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CornerRadius","title":"CornerRadius","abstract":[{"type":"text","text":"A set of convenience methods for configuring UIView properties, such as corner radius, background color, gradient, content mode, layer properties, user interaction, tag, center, and transform."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CornerRadius"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/cornerradius","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CornerRadius"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title","value":"AlertView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/navigatorTitle","value":[{"kind":"identifier","text":"AlertView"}],"op":"replace"}]}]}