{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/rightButton(cornerRadius:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/alertview\/rightbutton(cornerradius:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/alertview\/rightbutton(cornerradius:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@discardableResult"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightButton"},{"text":"(","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","text":"AlertView"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"metadata":{"roleHeading":"Instance Method","title":"rightButton(cornerRadius:)","navigatorTitle":[{"kind":"identifier","text":"rightButtonWithCornerRadius:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rightButton","kind":"identifier"},{"kind":"text","text":"("},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"AlertView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)AlertView(im)rightButtonWithCornerRadius:","symbolKind":"method","role":"symbol"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView/rightButton(cornerRadius:)":{"title":"rightButton(cornerRadius:)","kind":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/alertview\/rightbutton(cornerradius:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/rightButton(cornerRadius:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightButton"},{"kind":"text","text":"("},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"rightButtonWithCornerRadius:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","title":"AlertView","kind":"symbol","url":"\/documentation\/easechatuikit\/alertview","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"rightButtonWithCornerRadius:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"rightButtonWithCornerRadius:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","text":"AlertView"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"rightButtonWithCornerRadius:"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cornerRadius"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1rightButton(cornerRadius:)\/title","value":"rightButtonWithCornerRadius:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1rightButton(cornerRadius:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rightButtonWithCornerRadius:"}]},{"op":"replace","value":"AlertView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title"},{"value":[{"kind":"identifier","text":"AlertView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments","op":"replace"},{"value":[{"text":"AlertView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}