{"variants":[{"paths":["\/documentation\/easechatuikit\/alertview\/textfielddelegate(delegate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/alertview\/textfielddelegate(delegate:)"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/textFieldDelegate(delegate:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)AlertView(im)textFieldDelegateWithDelegate:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textFieldDelegate"},{"kind":"text","text":"("},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UITextFieldDelegate","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextFieldDelegate"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView","kind":"typeIdentifier"}],"title":"textFieldDelegate(delegate:)","navigatorTitle":[{"text":"textFieldDelegateWithDelegate:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"textFieldDelegate","kind":"identifier"},{"kind":"text","text":"("},{"text":"delegate","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UITextFieldDelegate","preciseIdentifier":"c:objc(pl)UITextFieldDelegate"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","title":"AlertView","kind":"symbol","url":"\/documentation\/easechatuikit\/alertview","navigatorTitle":[{"kind":"identifier","text":"AlertView"}],"role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView/textFieldDelegate(delegate:)":{"title":"textFieldDelegate(delegate:)","kind":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/alertview\/textfielddelegate(delegate:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/textFieldDelegate(delegate:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"textFieldDelegate"},{"text":"(","kind":"text"},{"text":"delegate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UITextFieldDelegate","text":"UITextFieldDelegate"},{"kind":"text","text":") -> "},{"text":"AlertView","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"textFieldDelegateWithDelegate:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"textFieldDelegateWithDelegate:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textFieldDelegateWithDelegate:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"AlertView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"textFieldDelegateWithDelegate:"},{"text":"(","kind":"text"},{"text":"id<UITextFieldDelegate>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UITextFieldDelegate"},{"kind":"text","text":") "},{"text":"delegate","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title","value":"AlertView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments","op":"replace","value":[{"kind":"identifier","text":"AlertView"}]},{"value":[{"text":"AlertView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/navigatorTitle"},{"value":"textFieldDelegateWithDelegate:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1textFieldDelegate(delegate:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1textFieldDelegate(delegate:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textFieldDelegateWithDelegate:","kind":"identifier"}]}]}]}