{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textField","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","kind":"typeIdentifier","text":"AlertView"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","title":"textField(font:)","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"text":"textFieldWithFont:","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)AlertView(im)textFieldWithFont:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"textField","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"font"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","text":"AlertView","kind":"typeIdentifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/alertview\/textfield(font:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/alertview\/textfield(font:)"]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/textField(font:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView/textField(font:)":{"abstract":[],"title":"textField(font:)","kind":"symbol","url":"\/documentation\/easechatuikit\/alertview\/textfield(font:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView\/textField(font:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"textField","kind":"identifier"},{"kind":"text","text":"("},{"text":"font","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","text":"AlertView"}],"navigatorTitle":[{"text":"textFieldWithFont:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AlertView":{"title":"AlertView","abstract":[],"url":"\/documentation\/easechatuikit\/alertview","type":"topic","role":"symbol","navigatorTitle":[{"text":"AlertView","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"AlertView","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"textFieldWithFont:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"textFieldWithFont:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)AlertView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AlertView","text":"AlertView"},{"kind":"text","text":" *) "},{"text":"textFieldWithFont:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"},{"kind":"text","text":" *) "},{"text":"font","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"textFieldWithFont:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1textField(font:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView~1textField(font:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"textFieldWithFont:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/title","value":"AlertView"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AlertView\/fragments","value":[{"text":"AlertView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}