{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"withDateAndTime","kind":"identifier"}]}]}],"metadata":{"externalID":"c:@M@EaseChatUIKit@E@MessageContentDisplayStyle@MessageContentDisplayStyleWithDateAndTime","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withDateAndTime"}],"title":"MessageContentDisplayStyle.withDateAndTime","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyleWithDateAndTime"}],"modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withDateAndTime"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withdateandtime"]},{"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withdateandtime"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","kind":"symbol","title":"MessageContentDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageContentDisplayStyle","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle","navigatorTitle":[{"text":"MessageContentDisplayStyle","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle/withDateAndTime":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withDateAndTime","title":"MessageContentDisplayStyle.withDateAndTime","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withDateAndTime"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withdateandtime","navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyleWithDateAndTime"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"MessageContentDisplayStyleWithDateAndTime","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"MessageContentDisplayStyleWithDateAndTime","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"MessageContentDisplayStyleWithDateAndTime"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/title","op":"replace","value":"MessageContentDisplayStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/fragments","op":"replace","value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withDateAndTime\/title","value":"MessageContentDisplayStyleWithDateAndTime"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withDateAndTime\/fragments","value":[{"text":"MessageContentDisplayStyleWithDateAndTime","kind":"identifier"}]}]}]}