{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withMessageThread","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withMessageThread"}],"title":"MessageContentDisplayStyle.withMessageThread","navigatorTitle":[{"text":"MessageContentDisplayStyleWithMessageThread","kind":"identifier"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@E@MessageContentDisplayStyle@MessageContentDisplayStyleWithMessageThread","roleHeading":"Case","symbolKind":"case","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withMessageThread"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withmessagethread"]},{"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withmessagethread"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle/withMessageThread":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withMessageThread","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withMessageThread"}],"kind":"symbol","title":"MessageContentDisplayStyle.withMessageThread","url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withmessagethread","navigatorTitle":[{"text":"MessageContentDisplayStyleWithMessageThread","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle":{"title":"MessageContentDisplayStyle","navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyle"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageContentDisplayStyle","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"MessageContentDisplayStyleWithMessageThread","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"MessageContentDisplayStyleWithMessageThread","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"MessageContentDisplayStyleWithMessageThread","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withMessageThread\/title","op":"replace","value":"MessageContentDisplayStyleWithMessageThread"},{"op":"replace","value":[{"text":"MessageContentDisplayStyleWithMessageThread","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withMessageThread\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/title","op":"replace","value":"MessageContentDisplayStyle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/fragments","value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/navigatorTitle","value":[{"text":"MessageContentDisplayStyle","kind":"identifier"}],"op":"replace"}]}]}