{"kind":"symbol","sections":[],"metadata":{"symbolKind":"case","roleHeading":"Case","title":"MessageContentDisplayStyle.withReply","externalID":"c:@M@EaseChatUIKit@E@MessageContentDisplayStyle@MessageContentDisplayStyleWithReply","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withReply"}],"navigatorTitle":[{"text":"MessageContentDisplayStyleWithReply","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withreply"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withreply"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"withReply","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withReply","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle/withReply":{"title":"MessageContentDisplayStyle.withReply","navigatorTitle":[{"text":"MessageContentDisplayStyleWithReply","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withReply","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"withReply","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withreply","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MessageContentDisplayStyle","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle","navigatorTitle":[{"kind":"identifier","text":"MessageContentDisplayStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","abstract":[],"title":"MessageContentDisplayStyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MessageContentDisplayStyleWithReply","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"MessageContentDisplayStyleWithReply"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MessageContentDisplayStyleWithReply"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withReply\/title","op":"replace","value":"MessageContentDisplayStyleWithReply"},{"value":[{"text":"MessageContentDisplayStyleWithReply","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withReply\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/title","value":"MessageContentDisplayStyle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/fragments","value":[{"kind":"identifier","text":"MessageContentDisplayStyle"}]}]}]}