{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withavatar"]},{"paths":["\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withavatar"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"withAvatar","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAvatar"}],"symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@MessageContentDisplayStyle@MessageContentDisplayStyleWithAvatar","roleHeading":"Case","title":"MessageContentDisplayStyle.withAvatar","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"MessageContentDisplayStyleWithAvatar","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withAvatar","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle/withAvatar":{"abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle\/withavatar","title":"MessageContentDisplayStyle.withAvatar","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"withAvatar"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle\/withAvatar","navigatorTitle":[{"text":"MessageContentDisplayStyleWithAvatar","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageContentDisplayStyle":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageContentDisplayStyle","kind":"symbol","title":"MessageContentDisplayStyle","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageContentDisplayStyle","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagecontentdisplaystyle","navigatorTitle":[{"text":"MessageContentDisplayStyle","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"MessageContentDisplayStyleWithAvatar"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"MessageContentDisplayStyleWithAvatar","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"MessageContentDisplayStyleWithAvatar","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withAvatar\/title","value":"MessageContentDisplayStyleWithAvatar"},{"value":[{"kind":"identifier","text":"MessageContentDisplayStyleWithAvatar"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle~1withAvatar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/title","value":"MessageContentDisplayStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageContentDisplayStyle\/fragments","value":[{"kind":"identifier","text":"MessageContentDisplayStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}