{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType\/addFriend"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"addFriend","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactemergencytype\/addfriend"]},{"paths":["\/documentation\/easechatuikit\/contactemergencytype\/addfriend"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"addFriend","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"ContactEmergencyType.addFriend","navigatorTitle":[{"kind":"identifier","text":"ContactEmergencyTypeAddFriend"}],"externalID":"c:@M@EaseChatUIKit@E@ContactEmergencyType@ContactEmergencyTypeAddFriend","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Case"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyType":{"role":"symbol","navigatorTitle":[{"text":"ContactEmergencyType","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/contactemergencytype","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ContactEmergencyType","kind":"identifier"}],"title":"ContactEmergencyType"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyType/addFriend":{"navigatorTitle":[{"text":"ContactEmergencyTypeAddFriend","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType\/addFriend","kind":"symbol","role":"symbol","title":"ContactEmergencyType.addFriend","url":"\/documentation\/easechatuikit\/contactemergencytype\/addfriend","type":"topic","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"addFriend","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"ContactEmergencyTypeAddFriend","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"ContactEmergencyTypeAddFriend"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ContactEmergencyTypeAddFriend"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyType\/title","value":"ContactEmergencyType","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyType\/fragments","value":[{"kind":"identifier","text":"ContactEmergencyType"}],"op":"replace"},{"op":"replace","value":"ContactEmergencyTypeAddFriend","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyType~1addFriend\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyType~1addFriend\/fragments","value":[{"kind":"identifier","text":"ContactEmergencyTypeAddFriend"}]}]}]}