{"variants":[{"paths":["\/documentation\/easechatuikit\/messagereactionscontroller\/reactionslist"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagereactionscontroller\/reactionslist"]}],"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController\/reactionsList"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController"]]},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageReactionsController(py)reactionsList","navigatorTitle":[{"text":"reactionsList","kind":"identifier"}],"symbolKind":"property","role":"symbol","title":"reactionsList","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"reactionsList","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"reactionsList","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsController":{"abstract":[],"kind":"symbol","title":"MessageReactionsController","type":"topic","role":"symbol","navigatorTitle":[{"text":"MessageReactionsController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagereactionscontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageReactionsController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsController/reactionsList":{"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"reactionsList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController\/reactionsList","url":"\/documentation\/easechatuikit\/messagereactionscontroller\/reactionslist","title":"reactionsList","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"reactionsList"},{"text":": ","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"reactionsList","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"reactionsList","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"reactionsList"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController\/title","value":"MessageReactionsController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController\/fragments","op":"replace","value":[{"text":"MessageReactionsController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController\/navigatorTitle","value":[{"text":"MessageReactionsController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController~1reactionsList\/title","value":"reactionsList"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController~1reactionsList\/fragments","value":[{"text":"reactionsList","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}