{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"UICollectionViewDelegate Implementations","modules":[{"name":"EaseChatUIKit"}]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController\/collectionView(_:didSelectItemAt:)"],"generated":true}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController\/UICollectionViewDelegate-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagereactionscontroller\/uicollectionviewdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagereactionscontroller\/uicollectionviewdelegate-implementations"]}],"sections":[],"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController","type":"topic","abstract":[],"title":"MessageReactionsController","url":"\/documentation\/easechatuikit\/messagereactionscontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReactionsController"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageReactionsController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReactionsController/collectionView(_:didSelectItemAt:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/messagereactionscontroller\/collectionview(_:didselectitemat:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectItemAt"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController\/collectionView(_:didSelectItemAt:)","title":"collectionView(_:didSelectItemAt:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReactionsController\/collectionView(_:didSelectItemAt:)"]}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController\/title","op":"replace","value":"MessageReactionsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController\/fragments","value":[{"kind":"identifier","text":"MessageReactionsController"}]},{"op":"replace","value":"collectionView:didSelectItemAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController~1collectionView(_:didSelectItemAt:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageReactionsController~1collectionView(_:didSelectItemAt:)\/fragments"}]}]}