{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupPlaceHolder"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/conversationappearance\/groupplaceholder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationappearance\/groupplaceholder"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Group chat default place holder of avatar.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/groupPlaceHolder"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupPlaceHolder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"groupPlaceHolder","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationAppearance(py)groupPlaceHolder","roleHeading":"Instance Property","title":"groupPlaceHolder"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/groupPlaceHolder":{"url":"\/documentation\/easechatuikit\/conversationappearance\/groupplaceholder","kind":"symbol","title":"groupPlaceHolder","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupPlaceHolder"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/groupPlaceHolder","role":"symbol","abstract":[{"text":"Group chat default place holder of avatar.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"groupPlaceHolder"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance":{"title":"ConversationAppearance","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationAppearance","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationappearance","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance","navigatorTitle":[{"kind":"identifier","text":"ConversationAppearance"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"groupPlaceHolder","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"groupPlaceHolder"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"groupPlaceHolder"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1groupPlaceHolder\/title","op":"replace","value":"groupPlaceHolder"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1groupPlaceHolder\/fragments","op":"replace","value":[{"text":"groupPlaceHolder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance\/title","value":"ConversationAppearance","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance\/fragments","value":[{"text":"ConversationAppearance","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}