{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"moreActions","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"moreActions"}],"role":"symbol","title":"moreActions","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationAppearance(py)moreActions"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/moreActions"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationappearance\/moreactions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationappearance\/moreactions"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moreActions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","kind":"typeIdentifier","text":"ActionSheetItemProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"ActionSheet menu configuration items after clicking more buttons in a single session side sliding menu."},{"type":"text","text":" "},{"text":"How to use?","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"let translate = ActionSheetItem(title: \"translate\", type: .normal,tag: \"Translate\")"},{"text":" ","type":"text"},{"type":"codeVoice","code":"translate.action = { }"},{"type":"text","text":" "},{"code":"Appearance.conversation.moreActions.append(translate)","type":"codeVoice"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance":{"title":"ConversationAppearance","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ConversationAppearance","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationappearance","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance","navigatorTitle":[{"kind":"identifier","text":"ConversationAppearance"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationAppearance/moreActions":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"moreActions","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"text":"]","kind":"text"}],"url":"\/documentation\/easechatuikit\/conversationappearance\/moreactions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationAppearance\/moreActions","kind":"symbol","title":"moreActions","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"moreActions"}],"abstract":[{"text":"ActionSheet menu configuration items after clicking more buttons in a single session side sliding menu.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"How to use?"},{"text":" ","type":"text"},{"type":"codeVoice","code":"let translate = ActionSheetItem(title: \"translate\", type: .normal,tag: \"Translate\")"},{"type":"text","text":" "},{"code":"translate.action = { }","type":"codeVoice"},{"type":"text","text":" "},{"type":"codeVoice","code":"Appearance.conversation.moreActions.append(translate)"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ActionSheetItemProtocol","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ActionSheetItemProtocol"}],"url":"\/documentation\/easechatuikit\/actionsheetitemprotocol","abstract":[{"type":"text","text":"A protocol that defines properties and methods for an action sheet item."}],"role":"symbol","title":"ActionSheetItemProtocol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"moreActions","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"moreActions","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<id<ActionSheetItemProtocol>>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"moreActions"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ConversationAppearance","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance\/title","op":"replace"},{"value":[{"text":"ConversationAppearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance\/fragments","op":"replace"},{"value":"moreActions","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1moreActions\/title"},{"value":[{"text":"moreActions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationAppearance~1moreActions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/title","value":"ActionSheetItemProtocol"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/fragments","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}