{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headerStyle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","kind":"typeIdentifier","text":"ContactListHeaderStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle"},{"text":" { get }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headerStyle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactSearchResultController(py)headerStyle","navigatorTitle":[{"text":"headerStyle","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"title":"headerStyle","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/headerStyle","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/headerstyle"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/headerstyle"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactSearchResultController","kind":"identifier"}],"title":"ContactSearchResultController","type":"topic","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/headerStyle":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/headerStyle","role":"symbol","title":"headerStyle","navigatorTitle":[{"text":"headerStyle","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/headerstyle","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"headerStyle","kind":"identifier"},{"kind":"text","text":": "},{"text":"ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","kind":"typeIdentifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle":{"url":"\/documentation\/easechatuikit\/contactlistheaderstyle","abstract":[{"text":"The header display style of the ","type":"text"},{"code":"ContactList","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactListHeaderStyle"}],"title":"ContactListHeaderStyle","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ContactListHeaderStyle","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"headerStyle","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"headerStyle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","kind":"typeIdentifier","text":"ContactListHeaderStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headerStyle"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"ContactSearchResultController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/fragments","value":[{"kind":"identifier","text":"ContactSearchResultController"}]},{"value":"headerStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1headerStyle\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1headerStyle\/fragments","op":"replace","value":[{"text":"headerStyle","kind":"identifier"}]},{"value":"ContactListHeaderStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/fragments","value":[{"kind":"identifier","text":"ContactListHeaderStyle"}],"op":"replace"}]}]}