{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/init(headerStyle:selectProfiles:ignoreIds:action:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactSearchResultController(im)initWithHeaderStyle:selectProfiles:ignoreIds:action:","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"title":"init(headerStyle:selectProfiles:ignoreIds:action:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"headerStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContactListHeaderStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"selectProfiles"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"ignoreIds"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"action","kind":"externalParam"},{"text":": (","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithHeaderStyle:selectProfiles:ignoreIds:action:","kind":"identifier"}],"symbolKind":"init","roleHeading":"Initializer"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/init(headerstyle:selectprofiles:ignoreids:action:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/init(headerstyle:selectprofiles:ignoreids:action:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController"]]},"abstract":[{"type":"codeVoice","code":"ContactListController"},{"type":"text","text":" init method.Only available in Objective-C language."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"headerStyle","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","text":"ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","kind":"typeIdentifier"},{"kind":"text","text":" = .contact, "},{"text":"selectProfiles","kind":"externalParam"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":"] = [], "},{"kind":"externalParam","text":"ignoreIds"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"] = [], ","kind":"text"},{"kind":"externalParam","text":"action"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"headerStyle","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","isActive":true}],"type":"paragraph"}]},{"name":"action","content":[{"inlineContent":[{"type":"text","text":"Select row callback."}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactListHeaderStyle":{"navigatorTitle":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"title":"ContactListHeaderStyle","url":"\/documentation\/easechatuikit\/contactlistheaderstyle","abstract":[{"type":"text","text":"The header display style of the "},{"type":"codeVoice","code":"ContactList"},{"type":"text","text":"."}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactListHeaderStyle"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/init(headerStyle:selectProfiles:ignoreIds:action:)":{"title":"init(headerStyle:selectProfiles:ignoreIds:action:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/init(headerStyle:selectProfiles:ignoreIds:action:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"headerStyle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","text":"ContactListHeaderStyle"},{"kind":"text","text":", "},{"kind":"externalParam","text":"selectProfiles"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"ChatUserProfileProtocol"},{"text":"], ","kind":"text"},{"text":"ignoreIds","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"], ","kind":"text"},{"text":"action","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatUserProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"code":"ContactListController","type":"codeVoice"},{"text":" init method.Only available in Objective-C language.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/init(headerstyle:selectprofiles:ignoreids:action:)","navigatorTitle":[{"kind":"identifier","text":"initWithHeaderStyle:selectProfiles:ignoreIds:action:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller","navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"role":"symbol","abstract":[],"title":"ContactSearchResultController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContactSearchResultController","kind":"identifier"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProtocol":{"abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatuserprofileprotocol","role":"symbol","title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithHeaderStyle:selectProfiles:ignoreIds:action:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithHeaderStyle:selectProfiles:ignoreIds:action:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"initWithHeaderStyle:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","text":"ContactListHeaderStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactListHeaderStyle","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"headerStyle","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"selectProfiles:"},{"kind":"text","text":"("},{"text":"NSArray<id<ChatUserProfileProtocol>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"selectProfiles"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreIds:"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"ignoreIds","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"action:"},{"text":"(","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","text":"id<ChatUserProfileProtocol>"},{"kind":"text","text":" "},{"kind":"internalParam","text":""},{"kind":"text","text":")) "},{"text":"action","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactListHeaderStyle","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"headerStyle"},{"name":"action","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Select row callback."}]}]}],"kind":"parameters"}},{"value":"ContactListHeaderStyle","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/title"},{"value":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/fragments"},{"op":"replace","value":[{"text":"ContactListHeaderStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactListHeaderStyle\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1init(headerStyle:selectProfiles:ignoreIds:action:)\/title","value":"initWithHeaderStyle:selectProfiles:ignoreIds:action:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1init(headerStyle:selectProfiles:ignoreIds:action:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithHeaderStyle:selectProfiles:ignoreIds:action:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/title","value":"ContactSearchResultController","op":"replace"},{"value":[{"text":"ContactSearchResultController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ContactSearchResultController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/navigatorTitle"},{"op":"replace","value":"ChatUserProfileProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/title"},{"value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/navigatorTitle","value":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"op":"replace"}]}]}