{"variants":[{"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/uisearchcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/uisearchcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/UISearchControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/presentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willPresentSearchController(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"UISearchControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/didDismissSearchController(_:)":{"role":"symbol","title":"didDismissSearchController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didDismissSearchController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/didDismissSearchController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didDismissSearchController:"}],"url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/diddismisssearchcontroller(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/willDismissSearchController(_:)":{"role":"symbol","title":"willDismissSearchController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissSearchController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willDismissSearchController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willDismissSearchController:"}],"url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/willdismisssearchcontroller(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/willPresentSearchController(_:)":{"role":"symbol","title":"willPresentSearchController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresentSearchController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willPresentSearchController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"willPresentSearchController:"}],"url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/willpresentsearchcontroller(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/presentSearchController(_:)":{"role":"symbol","title":"presentSearchController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentSearchController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/presentSearchController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"presentSearchController:"}],"url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/presentsearchcontroller(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController":{"role":"symbol","title":"ContactSearchResultController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactSearchResultController"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"url":"\/documentation\/easechatuikit\/contactsearchresultcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/didPresentSearchController(_:)":{"role":"symbol","title":"didPresentSearchController(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didPresentSearchController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/didPresentSearchController(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didPresentSearchController:"}],"url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/didpresentsearchcontroller(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/presentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willPresentSearchController(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1didDismissSearchController(_:)\/title","value":"didDismissSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1didDismissSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didDismissSearchController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1willDismissSearchController(_:)\/title","value":"willDismissSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1willDismissSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willDismissSearchController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1willPresentSearchController(_:)\/title","value":"willPresentSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1willPresentSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willPresentSearchController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1presentSearchController(_:)\/title","value":"presentSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1presentSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"presentSearchController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/title","value":"ContactSearchResultController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/fragments","value":[{"kind":"identifier","text":"ContactSearchResultController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1didPresentSearchController(_:)\/title","value":"didPresentSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1didPresentSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didPresentSearchController:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}