{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactSearchResultController(im)viewDidLoad","role":"symbol","title":"viewDidLoad()","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/viewdidload()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/viewDidLoad()"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/viewDidLoad()":{"title":"viewDidLoad()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/viewDidLoad()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/viewdidload()","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller","navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"role":"symbol","abstract":[],"title":"ContactSearchResultController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ContactSearchResultController","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLoad"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidLoad"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1viewDidLoad()\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"}]},{"value":"ContactSearchResultController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/fragments","value":[{"text":"ContactSearchResultController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/navigatorTitle","value":[{"text":"ContactSearchResultController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}