{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"searchController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"text":")","kind":"text"}]}]}],"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"willPresentSearchController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"text":")","kind":"text"}],"title":"willPresentSearchController(_:)","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"willPresentSearchController:"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactSearchResultController(im)willPresentSearchController:"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willPresentSearchController(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/UISearchControllerDelegate-Implementations"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISearchControllerDelegate.willPresentSearchController(_:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/willpresentsearchcontroller(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactsearchresultcontroller\/willpresentsearchcontroller(_:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/willPresentSearchController(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willPresentSearchController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/willPresentSearchController(_:)","title":"willPresentSearchController(_:)","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/willpresentsearchcontroller(_:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"willPresentSearchController:"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactSearchResultController","kind":"identifier"}],"title":"ContactSearchResultController","type":"topic","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ContactSearchResultController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactSearchResultController/UISearchControllerDelegate-Implementations":{"kind":"article","title":"UISearchControllerDelegate Implementations","url":"\/documentation\/easechatuikit\/contactsearchresultcontroller\/uisearchcontrollerdelegate-implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactSearchResultController\/UISearchControllerDelegate-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"willPresentSearchController:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willPresentSearchController:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"willPresentSearchController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchController","kind":"typeIdentifier","text":"UISearchController"},{"kind":"text","text":" *) "},{"text":"searchController","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1willPresentSearchController(_:)\/title","value":"willPresentSearchController:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"willPresentSearchController:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController~1willPresentSearchController(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/title","value":"ContactSearchResultController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactSearchResultController\/fragments","value":[{"text":"ContactSearchResultController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}