{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageCell\/removeActionHandler","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"removeActionHandler","kind":"identifier"},{"text":": ((","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity","text":"PinnedMessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageCell"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/pinnedmessagecell\/removeactionhandler"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"removeActionHandler","externalID":"s:13EaseChatUIKit17PinnedMessageCellC19removeActionHandleryAA0dE6EntityCcSgvp","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeActionHandler","kind":"identifier"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity","kind":"typeIdentifier","text":"PinnedMessageEntity"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":")?"}],"roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"property"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessageCell/removeActionHandler":{"url":"\/documentation\/easechatuikit\/pinnedmessagecell\/removeactionhandler","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageCell\/removeActionHandler","title":"removeActionHandler","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeActionHandler","kind":"identifier"},{"text":": ((","kind":"text"},{"text":"PinnedMessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)PinnedMessageEntity"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessageEntity":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessageentity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageEntity","navigatorTitle":[{"kind":"identifier","text":"PinnedMessageEntity"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PinnedMessageEntity","kind":"identifier"}],"title":"PinnedMessageEntity","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessageCell":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/pinnedmessagecell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessageCell","navigatorTitle":[{"kind":"identifier","text":"PinnedMessageCell"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PinnedMessageCell","kind":"identifier"}],"title":"PinnedMessageCell"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/title","value":"PinnedMessageEntity"},{"value":[{"text":"PinnedMessageEntity","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"PinnedMessageEntity"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageEntity\/navigatorTitle"},{"value":"PinnedMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageCell\/title"},{"value":[{"text":"PinnedMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageCell\/fragments","op":"replace"},{"value":[{"text":"PinnedMessageCell","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessageCell\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}