{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarClicked(profile:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageAvatarClicked","kind":"identifier"},{"text":"(","kind":"text"},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"profile","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","isActive":true}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate\/onmessageavatarclicked(profile:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate\/onmessageavatarclicked(profile:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate"]]},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageAvatarClicked","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol","title":"onMessageAvatarClicked(profile:)","navigatorTitle":[{"kind":"identifier","text":"onMessageAvatarClickedWithProfile:"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate(im)onMessageAvatarClickedWithProfile:","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"The method will call on message avatar clicked"}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewActionEventsDelegate/onMessageAvatarClicked(profile:)":{"navigatorTitle":[{"text":"onMessageAvatarClickedWithProfile:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate\/onMessageAvatarClicked(profile:)","kind":"symbol","role":"symbol","title":"onMessageAvatarClicked(profile:)","url":"\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate\/onmessageavatarclicked(profile:)","required":true,"type":"topic","abstract":[{"text":"The method will call on message avatar clicked","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageAvatarClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewActionEventsDelegate":{"role":"symbol","abstract":[],"url":"\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate","title":"MessageListViewActionEventsDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EaseProfileProtocol"}],"role":"symbol","abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"type":"topic","title":"EaseProfileProtocol","url":"\/documentation\/easechatuikit\/easeprofileprotocol","navigatorTitle":[{"text":"EaseProfileProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"onMessageAvatarClickedWithProfile:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarClickedWithProfile:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarClickedWithProfile:"},{"text":"(","kind":"text"},{"text":"id<EaseProfileProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":") "},{"text":"profile","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate~1onMessageAvatarClicked(profile:)\/title","value":"onMessageAvatarClickedWithProfile:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarClickedWithProfile:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate~1onMessageAvatarClicked(profile:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/fragments","value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title","value":"EaseProfileProtocol","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments","op":"replace","value":[{"text":"EaseProfileProtocol","kind":"identifier"}]}]}]}