{"metadata":{"title":"onMessageVisible(entity:)","role":"symbol","roleHeading":"Instance Method","required":true,"navigatorTitle":[{"kind":"identifier","text":"onMessageVisibleWithEntity:"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)MessageListViewActionEventsDelegate(im)onMessageVisibleWithEntity:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageVisible"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate\/onmessagevisible(entity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate\/onmessagevisible(entity:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate\/onMessageVisible(entity:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Message visible on scroll in screen"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageVisible"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"entity","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","isActive":true}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewActionEventsDelegate/onMessageVisible(entity:)":{"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageVisible","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"title":"onMessageVisible(entity:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate\/onMessageVisible(entity:)","abstract":[{"text":"Message visible on scroll in screen","type":"text"}],"required":true,"url":"\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate\/onmessagevisible(entity:)","navigatorTitle":[{"text":"onMessageVisibleWithEntity:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListViewActionEventsDelegate":{"type":"topic","title":"MessageListViewActionEventsDelegate","navigatorTitle":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"url":"\/documentation\/easechatuikit\/messagelistviewactioneventsdelegate","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListViewActionEventsDelegate"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"title":"MessageEntity","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageEntity"}],"url":"\/documentation\/easechatuikit\/messageentity","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onMessageVisibleWithEntity:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageVisibleWithEntity:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageVisibleWithEntity:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"entity","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","type":"reference"}]}],"name":"entity"}]},"op":"replace"},{"value":"onMessageVisibleWithEntity:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate~1onMessageVisible(entity:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageVisibleWithEntity:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate~1onMessageVisible(entity:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/title","value":"MessageListViewActionEventsDelegate"},{"value":[{"kind":"identifier","text":"MessageListViewActionEventsDelegate"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListViewActionEventsDelegate\/navigatorTitle","value":[{"text":"MessageListViewActionEventsDelegate","kind":"identifier"}]},{"value":"MessageEntity","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments","value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/navigatorTitle","value":[{"text":"MessageEntity","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}