{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/left"},"metadata":{"externalID":"c:@M@EaseChatUIKit@E@TriangleDirection@TriangleDirectionLeft","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"}],"navigatorTitle":[{"text":"TriangleDirectionLeft","kind":"identifier"}],"title":"TriangleDirection.left","symbolKind":"case","roleHeading":"Case","role":"symbol","modules":[{"name":"EaseChatUIKit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/triangledirection\/left"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/triangledirection\/left"]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection/left":{"url":"\/documentation\/easechatuikit\/triangledirection\/left","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection\/left","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"left","kind":"identifier"}],"type":"topic","abstract":[],"title":"TriangleDirection.left","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TriangleDirectionLeft"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TriangleDirection":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TriangleDirection","kind":"identifier"}],"title":"TriangleDirection","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TriangleDirection","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"TriangleDirection","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/triangledirection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"TriangleDirectionLeft"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"kind":"identifier","text":"TriangleDirectionLeft"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"TriangleDirectionLeft"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection~1left\/title","value":"TriangleDirectionLeft","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection~1left\/fragments","value":[{"text":"TriangleDirectionLeft","kind":"identifier"}]},{"op":"replace","value":"TriangleDirection","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/fragments","value":[{"kind":"identifier","text":"TriangleDirection"}]},{"op":"replace","value":[{"kind":"identifier","text":"TriangleDirection"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TriangleDirection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}