{"sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar\/collectionView(_:numberOfItemsInSection:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pagecontainertitlebar\/uicollectionviewdatasource-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pagecontainertitlebar\/uicollectionviewdatasource-implementations"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"UICollectionViewDataSource Implementations"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar\/UICollectionViewDataSource-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainerTitleBar/collectionView(_:numberOfItemsInSection:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/easechatuikit\/pagecontainertitlebar\/collectionview(_:numberofitemsinsection:)","type":"topic","title":"collectionView(_:numberOfItemsInSection:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar\/collectionView(_:numberOfItemsInSection:)","navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainerTitleBar/collectionView(_:cellForItemAt:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar\/collectionView(_:cellForItemAt:)","kind":"symbol","navigatorTitle":[{"text":"collectionView:cellForItemAtIndexPath:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForItemAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":") -> ","kind":"text"},{"text":"UICollectionViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionViewCell"}],"url":"\/documentation\/easechatuikit\/pagecontainertitlebar\/collectionview(_:cellforitemat:)","type":"topic","title":"collectionView(_:cellForItemAt:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainerTitleBar":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PageContainerTitleBar"}],"type":"topic","title":"PageContainerTitleBar","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar","abstract":[],"navigatorTitle":[{"text":"PageContainerTitleBar","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pagecontainertitlebar"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar\/collectionView(_:cellForItemAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainerTitleBar\/collectionView(_:numberOfItemsInSection:)"],"generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"collectionView:numberOfItemsInSection:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar~1collectionView(_:numberOfItemsInSection:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar~1collectionView(_:numberOfItemsInSection:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar~1collectionView(_:cellForItemAt:)\/title","op":"replace","value":"collectionView:cellForItemAtIndexPath:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar~1collectionView(_:cellForItemAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:cellForItemAtIndexPath:"}]},{"value":"PageContainerTitleBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainerTitleBar\/fragments","value":[{"text":"PageContainerTitleBar","kind":"identifier"}]}]}]}