{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addActionHandler"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PinnedMessagesContainerDelegate","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The object of conform ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","isActive":true,"type":"reference"},{"type":"text","text":"."}]}],"name":"actionHandler"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/addactionhandler(actionhandler:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/addactionhandler(actionhandler:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/addActionHandler(actionHandler:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"addActionHandler(actionHandler:)","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addActionHandler"},{"text":"(","kind":"text"},{"text":"actionHandler","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate","text":"PinnedMessagesContainerDelegate","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"method","navigatorTitle":[{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)IPinnedMessagesContainerDriver(im)addActionHandlerWithActionHandler:","required":true},"abstract":[{"type":"text","text":"Add action events listener of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","isActive":true},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver":{"url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"IPinnedMessagesContainerDriver","navigatorTitle":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainerDelegate":{"navigatorTitle":[{"text":"PinnedMessagesContainerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","kind":"symbol","title":"PinnedMessagesContainerDelegate","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainerdelegate","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PinnedMessagesContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PinnedMessagesContainer","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/pinnedmessagescontainer","type":"topic","title":"PinnedMessagesContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","navigatorTitle":[{"kind":"identifier","text":"PinnedMessagesContainer"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver/addActionHandler(actionHandler:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addActionHandler","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"actionHandler"},{"text":": ","kind":"text"},{"text":"PinnedMessagesContainerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/addActionHandler(actionHandler:)","title":"addActionHandler(actionHandler:)","navigatorTitle":[{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}],"abstract":[{"type":"text","text":"Add action events listener of "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainer","isActive":true},{"type":"text","text":"."}],"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/addactionhandler(actionhandler:)","kind":"symbol","required":true}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"addActionHandlerWithActionHandler:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"addActionHandlerWithActionHandler:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<PinnedMessagesContainerDelegate>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)PinnedMessagesContainerDelegate"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"actionHandler"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"actionHandler","content":[{"inlineContent":[{"type":"text","text":"The object of conform "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PinnedMessagesContainerDelegate","isActive":true},{"text":".","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/title","value":"IPinnedMessagesContainerDriver"},{"value":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/fragments","op":"replace"},{"value":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/navigatorTitle"},{"op":"replace","value":"PinnedMessagesContainerDelegate","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/title"},{"value":[{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"PinnedMessagesContainerDelegate"}],"op":"replace"},{"op":"replace","value":"PinnedMessagesContainer","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/fragments","value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"op":"replace"},{"value":[{"text":"PinnedMessagesContainer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PinnedMessagesContainer\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1addActionHandler(actionHandler:)\/title","value":"addActionHandlerWithActionHandler:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1addActionHandler(actionHandler:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addActionHandlerWithActionHandler:"}]}]}]}