{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/remove(messageId:)"},"metadata":{"navigatorTitle":[{"text":"removeWithMessageId:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"title":"remove(messageId:)","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)IPinnedMessagesContainerDriver(im)removeWithMessageId:","required":true,"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/remove(messageid:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/remove(messageid:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver/remove(messageId:)":{"navigatorTitle":[{"kind":"identifier","text":"removeWithMessageId:"}],"role":"symbol","type":"topic","abstract":[],"required":true,"kind":"symbol","url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver\/remove(messageid:)","title":"remove(messageId:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver\/remove(messageId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"remove","kind":"identifier"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IPinnedMessagesContainerDriver":{"url":"\/documentation\/easechatuikit\/ipinnedmessagescontainerdriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IPinnedMessagesContainerDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[],"title":"IPinnedMessagesContainerDriver","navigatorTitle":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"removeWithMessageId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeWithMessageId:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"removeWithMessageId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"messageId","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1remove(messageId:)\/title","value":"removeWithMessageId:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeWithMessageId:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver~1remove(messageId:)\/fragments","op":"replace"},{"value":"IPinnedMessagesContainerDriver","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/fragments","value":[{"text":"IPinnedMessagesContainerDriver","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IPinnedMessagesContainerDriver\/navigatorTitle","value":[{"kind":"identifier","text":"IPinnedMessagesContainerDriver"}],"op":"replace"}]}]}