{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions\/init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatuikitoptions\/init"]}],"metadata":{"role":"symbol","title":"init","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitOptions(im)init","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitOptions":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions","role":"symbol","navigatorTitle":[{"text":"ChatUIKitOptions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/chatuikitoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitOptions"}],"title":"ChatUIKitOptions","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitOptions/init":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions\/init","title":"init","kind":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/chatuikitoptions\/init","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/title","value":"ChatUIKitOptions","op":"replace"},{"value":[{"text":"ChatUIKitOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/navigatorTitle","value":[{"kind":"identifier","text":"ChatUIKitOptions"}]}]}]}