{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions\/option_chat","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The option of chat sdk function."}],"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/chatuikitoptions\/option_chat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatuikitoptions\/option_chat"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"text":"option_chat","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"option_chat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatOptions","text":"ChatOptions","kind":"typeIdentifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitOptions(py)option_chat","title":"option_chat","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"option_chat"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatOptions","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatOptions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatOptions"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatOptions":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChatOptions","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatOptions"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatOptions","url":"\/documentation\/easechatuikit\/chatoptions","title":"ChatOptions","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitOptions/option_chat":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"option_chat","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatOptions","text":"ChatOptions","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The option of chat sdk function."}],"type":"topic","title":"option_chat","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions\/option_chat","url":"\/documentation\/easechatuikit\/chatuikitoptions\/option_chat","navigatorTitle":[{"kind":"identifier","text":"option_chat"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitOptions":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions","role":"symbol","navigatorTitle":[{"text":"ChatUIKitOptions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/chatuikitoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitOptions"}],"title":"ChatUIKitOptions","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"option_chat","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"option_chat"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatOptions","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatOptions","text":"ChatOptions"},{"text":" * ","kind":"text"},{"text":"option_chat","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatOptions\/title","value":"ChatOptions","op":"replace"},{"value":[{"kind":"identifier","text":"ChatOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatOptions\/fragments","op":"replace"},{"op":"replace","value":[{"text":"ChatOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatOptions\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions~1option_chat\/title","value":"option_chat","op":"replace"},{"value":[{"kind":"identifier","text":"option_chat"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions~1option_chat\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/title","op":"replace","value":"ChatUIKitOptions"},{"op":"replace","value":[{"text":"ChatUIKitOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/navigatorTitle","op":"replace","value":[{"text":"ChatUIKitOptions","kind":"identifier"}]}]}]}