{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"option_UI","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions","text":"UIOptions","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions\/option_UI","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/chatuikitoptions\/option_ui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatuikitoptions\/option_ui"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"option_UI","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatUIKitOptions(py)option_UI","roleHeading":"Instance Property","role":"symbol","title":"option_UI","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"option_UI","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions"}],"symbolKind":"property"},"kind":"symbol","abstract":[{"text":"The option of UI components.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions":{"title":"UIOptions","navigatorTitle":[{"text":"UIOptions","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/uioptions","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIOptions"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitOptions":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions","role":"symbol","navigatorTitle":[{"text":"ChatUIKitOptions","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/chatuikitoptions","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatUIKitOptions"}],"title":"ChatUIKitOptions","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUIKitOptions/option_UI":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"option_UI"},{"text":": ","kind":"text"},{"text":"UIOptions","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions"}],"title":"option_UI","abstract":[{"type":"text","text":"The option of UI components."}],"navigatorTitle":[{"text":"option_UI","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/chatuikitoptions\/option_ui","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUIKitOptions\/option_UI"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"option_UI","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"option_UI"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions","text":"UIOptions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions"},{"text":" * ","kind":"text"},{"text":"option_UI","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions\/title","op":"replace","value":"UIOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions\/fragments","value":[{"text":"UIOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions\/navigatorTitle","value":[{"kind":"identifier","text":"UIOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/title","value":"ChatUIKitOptions"},{"value":[{"kind":"identifier","text":"ChatUIKitOptions"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/fragments","op":"replace"},{"value":[{"text":"ChatUIKitOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions\/navigatorTitle"},{"value":"option_UI","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions~1option_UI\/title"},{"value":[{"kind":"identifier","text":"option_UI"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUIKitOptions~1option_UI\/fragments","op":"replace"}]}]}