{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagemultiselectbarclicked(operation:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagemultiselectbarclicked(operation:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"operation","content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","isActive":true}],"type":"paragraph"}]}],"kind":"parameters"}],"abstract":[{"type":"text","text":"When you click a message list multi select bar item,the method will call."}],"sections":[],"metadata":{"title":"onMessageMultiSelectBarClicked(operation:)","required":true,"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener(im)onMessageMultiSelectBarClickedWithOperation:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageMultiSelectBarClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"operation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation","text":"MessageMultiSelectedBottomBarOperation"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMultiSelectBarClicked(operation:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener":{"url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","abstract":[],"type":"topic","kind":"symbol","title":"MessageListDriverEventsListener","navigatorTitle":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MessageListDriverEventsListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onMessageMultiSelectBarClicked(operation:)":{"abstract":[{"type":"text","text":"When you click a message list multi select bar item,the method will call."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onMessageMultiSelectBarClicked(operation:)","type":"topic","navigatorTitle":[{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onmessagemultiselectbarclicked(operation:)","kind":"symbol","required":true,"title":"onMessageMultiSelectBarClicked(operation:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageMultiSelectBarClicked"},{"text":"(","kind":"text"},{"text":"operation","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageMultiSelectedBottomBarOperation":{"navigatorTitle":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagemultiselectedbottombaroperation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageMultiSelectedBottomBarOperation"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","abstract":[],"title":"MessageMultiSelectedBottomBarOperation","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"onMessageMultiSelectBarClickedWithOperation:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageMultiSelectBarClickedWithOperation:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","kind":"typeIdentifier","text":"MessageMultiSelectedBottomBarOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageMultiSelectedBottomBarOperation"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"operation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageMultiSelectedBottomBarOperation","isActive":true}]}],"name":"operation"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/title","value":"MessageListDriverEventsListener","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/fragments","value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/navigatorTitle","op":"replace","value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageMultiSelectBarClicked(operation:)\/title","value":"onMessageMultiSelectBarClickedWithOperation:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageMultiSelectBarClickedWithOperation:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onMessageMultiSelectBarClicked(operation:)\/fragments"},{"value":"MessageMultiSelectedBottomBarOperation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/title"},{"value":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/fragments"},{"value":[{"text":"MessageMultiSelectedBottomBarOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageMultiSelectedBottomBarOperation\/navigatorTitle"}]}]}