{"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onOtherPartyTypingText()","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"onOtherPartyTypingText"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)MessageListDriverEventsListener(im)onOtherPartyTypingText","symbolKind":"method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onOtherPartyTypingText"},{"text":"()","kind":"text"}],"roleHeading":"Instance Method","title":"onOtherPartyTypingText()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onOtherPartyTypingText"},{"text":"()","kind":"text"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onotherpartytypingtext()"]},{"paths":["\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onotherpartytypingtext()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"When other party begin typing text.The method will called."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener/onOtherPartyTypingText()":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"When other party begin typing text.The method will called."}],"navigatorTitle":[{"text":"onOtherPartyTypingText","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener\/onOtherPartyTypingText()","title":"onOtherPartyTypingText()","url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener\/onotherpartytypingtext()","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onOtherPartyTypingText"},{"text":"()","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListDriverEventsListener":{"url":"\/documentation\/easechatuikit\/messagelistdrivereventslistener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListDriverEventsListener","abstract":[],"type":"topic","kind":"symbol","title":"MessageListDriverEventsListener","navigatorTitle":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"MessageListDriverEventsListener","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"onOtherPartyTypingText","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onOtherPartyTypingText"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"onOtherPartyTypingText","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"onOtherPartyTypingText","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onOtherPartyTypingText()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener~1onOtherPartyTypingText()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onOtherPartyTypingText"}]},{"op":"replace","value":"MessageListDriverEventsListener","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/title"},{"value":[{"kind":"identifier","text":"MessageListDriverEventsListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/fragments"},{"value":[{"text":"MessageListDriverEventsListener","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListDriverEventsListener\/navigatorTitle"}]}]}