{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"roleHeading":"Initializer","symbolKind":"init","title":"init()","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ConversationInfo(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"required","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationinfo\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationinfo\/init()"]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo\/init()","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationInfo","kind":"identifier"}],"abstract":[],"type":"topic","title":"ConversationInfo","navigatorTitle":[{"text":"ConversationInfo","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/conversationinfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationInfo/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationInfo\/init()","title":"init()","url":"\/documentation\/easechatuikit\/conversationinfo\/init()","role":"symbol","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/title","value":"ConversationInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo\/fragments","value":[{"text":"ConversationInfo","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationInfo~1init()\/fragments"}]}]}