{"metadata":{"title":"filterResultsWithSearchString(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"filterResultsWithSearchString"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"filterResultsWithSearchString:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)SearchHistoryMessagesViewController(im)filterResultsWithSearchString:"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/filterresultswithsearchstring(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/filterresultswithsearchstring(_:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/filterResultsWithSearchString(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"filterResultsWithSearchString","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"searchText"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/filterResultsWithSearchString(_:)":{"title":"filterResultsWithSearchString(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"filterResultsWithSearchString","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"filterResultsWithSearchString:"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/filterresultswithsearchstring(_:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/filterResultsWithSearchString(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController":{"url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller","type":"topic","title":"SearchHistoryMessagesViewController","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"filterResultsWithSearchString:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"filterResultsWithSearchString:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"filterResultsWithSearchString:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"searchText","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"filterResultsWithSearchString:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1filterResultsWithSearchString(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"filterResultsWithSearchString:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1filterResultsWithSearchString(_:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/title","value":"SearchHistoryMessagesViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/fragments","value":[{"text":"SearchHistoryMessagesViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}