{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UISearchBarDelegate.searchBarCancelButtonClicked(_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/UISearchBarDelegate-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/searchBarCancelButtonClicked(_:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"searchBar"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar","text":"UISearchBar"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"extendedModule":"EaseChatUIKit","title":"searchBarCancelButtonClicked(_:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"searchBarCancelButtonClicked:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"UISearchBar","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchBar"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)SearchHistoryMessagesViewController(im)searchBarCancelButtonClicked:","symbolKind":"method"},"variants":[{"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/searchbarcancelbuttonclicked(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/searchbarcancelbuttonclicked(_:)"]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController":{"url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller","type":"topic","title":"SearchHistoryMessagesViewController","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/UISearchBarDelegate-Implementations":{"title":"UISearchBarDelegate Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/UISearchBarDelegate-Implementations","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/uisearchbardelegate-implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/searchBarCancelButtonClicked(_:)":{"title":"searchBarCancelButtonClicked(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"searchBarCancelButtonClicked:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/searchBarCancelButtonClicked(_:)","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/searchbarcancelbuttonclicked(_:)","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"searchBarCancelButtonClicked:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"searchBarCancelButtonClicked:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"searchBarCancelButtonClicked:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier","text":"UISearchBar"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"searchBar"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SearchHistoryMessagesViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/fragments","value":[{"text":"SearchHistoryMessagesViewController","kind":"identifier"}],"op":"replace"},{"value":"searchBarCancelButtonClicked:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1searchBarCancelButtonClicked(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"searchBarCancelButtonClicked:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1searchBarCancelButtonClicked(_:)\/fragments"}]}]}