{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"UISearchControllerDelegate Implementations"},"kind":"article","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/uisearchcontrollerdelegate-implementations"]},{"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/uisearchcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/presentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willPresentSearchController(_:)"],"generated":true,"title":"Instance Methods"}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/UISearchControllerDelegate-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/didDismissSearchController(_:)":{"abstract":[],"title":"didDismissSearchController(_:)","type":"topic","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/diddismisssearchcontroller(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didDismissSearchController"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"didDismissSearchController:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/didDismissSearchController(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/willPresentSearchController(_:)":{"abstract":[],"title":"willPresentSearchController(_:)","type":"topic","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/willpresentsearchcontroller(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willPresentSearchController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"willPresentSearchController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willPresentSearchController(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController":{"title":"SearchHistoryMessagesViewController","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchHistoryMessagesViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/presentSearchController(_:)":{"abstract":[],"title":"presentSearchController(_:)","type":"topic","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/presentsearchcontroller(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"presentSearchController"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"presentSearchController:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/presentSearchController(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/didPresentSearchController(_:)":{"abstract":[],"title":"didPresentSearchController(_:)","type":"topic","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/didpresentsearchcontroller(_:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didPresentSearchController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"didPresentSearchController:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/didPresentSearchController(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/willDismissSearchController(_:)":{"abstract":[],"title":"willDismissSearchController(_:)","type":"topic","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/willdismisssearchcontroller(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDismissSearchController"},{"text":"(","kind":"text"},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"willDismissSearchController:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willDismissSearchController(_:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/didDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/didPresentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/presentSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willDismissSearchController(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willPresentSearchController(_:)"],"title":"Instance Methods","generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1didDismissSearchController(_:)\/title","op":"replace","value":"didDismissSearchController:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1didDismissSearchController(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didDismissSearchController:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1willPresentSearchController(_:)\/title","op":"replace","value":"willPresentSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1willPresentSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willPresentSearchController:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/title","value":"SearchHistoryMessagesViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/fragments","op":"replace","value":[{"text":"SearchHistoryMessagesViewController","kind":"identifier"}]},{"value":"presentSearchController:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1presentSearchController(_:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1presentSearchController(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentSearchController:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1didPresentSearchController(_:)\/title","value":"didPresentSearchController:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1didPresentSearchController(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didPresentSearchController:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1willDismissSearchController(_:)\/title","value":"willDismissSearchController:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1willDismissSearchController(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"willDismissSearchController:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}