{"variants":[{"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/uisearchbardelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/uisearchbardelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/UISearchBarDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"UISearchBarDelegate Implementations"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/searchBarCancelButtonClicked(_:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController":{"url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller","type":"topic","title":"SearchHistoryMessagesViewController","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/searchBarCancelButtonClicked(_:)":{"title":"searchBarCancelButtonClicked(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"searchBarCancelButtonClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"UISearchBar","preciseIdentifier":"c:objc(cs)UISearchBar","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"searchBarCancelButtonClicked:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/searchBarCancelButtonClicked(_:)","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/searchbarcancelbuttonclicked(_:)","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/searchBarCancelButtonClicked(_:)"],"generated":true,"title":"Instance Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/title","op":"replace","value":"SearchHistoryMessagesViewController"},{"value":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1searchBarCancelButtonClicked(_:)\/title","value":"searchBarCancelButtonClicked:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1searchBarCancelButtonClicked(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"searchBarCancelButtonClicked:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}