{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"viewWillAppear(_:)","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)SearchHistoryMessagesViewController(im)viewWillAppear:","navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"roleHeading":"Instance Method","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/viewWillAppear(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/viewwillappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/viewwillappear(_:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController":{"url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller","type":"topic","title":"SearchHistoryMessagesViewController","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/viewWillAppear(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/viewWillAppear(_:)","title":"viewWillAppear(_:)","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/viewwillappear(_:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewWillAppear:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewWillAppear:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"SearchHistoryMessagesViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/title"},{"op":"replace","value":[{"text":"SearchHistoryMessagesViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1viewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}