{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"willDismissSearchController:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"willDismissSearchController","kind":"identifier"},{"kind":"text","text":"("},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"text":")","kind":"text"}],"title":"willDismissSearchController(_:)","role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)SearchHistoryMessagesViewController(im)willDismissSearchController:","symbolKind":"method"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UISearchControllerDelegate.willDismissSearchController(_:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willDismissSearchController(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"willDismissSearchController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"searchController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController","text":"UISearchController"},{"kind":"text","text":")"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/willdismisssearchcontroller(_:)"]},{"paths":["\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/willdismisssearchcontroller(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/UISearchControllerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/UISearchControllerDelegate-Implementations":{"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/UISearchControllerDelegate-Implementations","kind":"article","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/uisearchcontrollerdelegate-implementations","role":"collectionGroup","title":"UISearchControllerDelegate Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController":{"url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller","type":"topic","title":"SearchHistoryMessagesViewController","abstract":[],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController","navigatorTitle":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchHistoryMessagesViewController/willDismissSearchController(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"willDismissSearchController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UISearchController","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":")"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchHistoryMessagesViewController\/willDismissSearchController(_:)","kind":"symbol","url":"\/documentation\/easechatuikit\/searchhistorymessagesviewcontroller\/willdismisssearchcontroller(_:)","role":"symbol","navigatorTitle":[{"text":"willDismissSearchController:","kind":"identifier"}],"title":"willDismissSearchController(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"willDismissSearchController:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"willDismissSearchController:"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"willDismissSearchController:"},{"kind":"text","text":"("},{"text":"UISearchController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISearchController"},{"kind":"text","text":" *) "},{"text":"searchController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SearchHistoryMessagesViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SearchHistoryMessagesViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1willDismissSearchController(_:)\/title","value":"willDismissSearchController:"},{"value":[{"text":"- ","kind":"text"},{"text":"willDismissSearchController:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchHistoryMessagesViewController~1willDismissSearchController(_:)\/fragments","op":"replace"}]}]}