{"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/agorachatgroupmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/agorachatgroupmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/AgoraChatGroupManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"AgoraChatGroupManagerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupOwnerDidUpdate(_:newOwner:oldOwner:)":{"role":"symbol","title":"groupOwnerDidUpdate(_:newOwner:oldOwner:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupOwnerDidUpdate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"newOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"oldOwner"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupOwnerDidUpdate:newOwner:oldOwner:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupownerdidupdate(_:newowner:oldowner:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/userDidJoin(_:user:)":{"role":"symbol","title":"userDidJoin(_:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidJoin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidJoinGroup:user:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/userdidjoin(_:user:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)":{"role":"symbol","title":"onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAttributesChangedOfGroupMember"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributes"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"operatorId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/onattributeschangedofgroupmember(_:userid:attributes:operatorid:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupInvitationDidAccept(_:invitee:)":{"role":"symbol","title":"groupInvitationDidAccept(_:invitee:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidAccept"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidAccept:invitee:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdidaccept(_:invitee:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/didJoin(_:inviter:message:)":{"role":"symbol","title":"didJoin(_:inviter:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didJoin"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didJoinGroup:inviter:message:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/didjoin(_:inviter:message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/didLeave(_:reason:)":{"role":"symbol","title":"didLeave(_:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"didLeave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupLeaveReason","preciseIdentifier":"s:13EaseChatUIKit16GroupLeaveReasona"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didLeaveGroup:reason:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/didleave(_:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupInvitationDidReceive(_:groupName:inviter:message:)":{"role":"symbol","title":"groupInvitationDidReceive(_:groupName:inviter:message:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"inviter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdidreceive(_:groupname:inviter:message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"role":"symbol","title":"GroupServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupServiceImplement"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/userDidLeave(_:user:)":{"role":"symbol","title":"userDidLeave(_:user:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"userDidLeave"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"userDidLeaveGroup:user:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/userdidleave(_:user:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupInvitationDidDecline(_:invitee:reason:)":{"role":"symbol","title":"groupInvitationDidDecline(_:invitee:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidDecline"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidDecline:invitee:reason:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdiddecline(_:invitee:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/joinGroupRequestDidReceive(_:user:reason:)":{"role":"symbol","title":"joinGroupRequestDidReceive(_:user:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinGroupRequestDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidReceive:user:reason:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/joingrouprequestdidreceive(_:user:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/joinGroupRequestDidDecline(_:reason:)":{"role":"symbol","title":"joinGroupRequestDidDecline(_:reason:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinGroupRequestDidDecline"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidDecline:reason:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/joingrouprequestdiddecline(_:reason:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/joinGroupRequestDidApprove(_:)":{"role":"symbol","title":"joinGroupRequestDidApprove(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"joinGroupRequestDidApprove"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidApprove:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/joingrouprequestdidapprove(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/title","value":"groupOwnerDidUpdate:newOwner:oldOwner:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupOwnerDidUpdate:newOwner:oldOwner:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidJoin(_:user:)\/title","value":"userDidJoinGroup:user:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidJoin(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidJoinGroup:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)\/title","value":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidAccept(_:invitee:)\/title","value":"groupInvitationDidAccept:invitee:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidAccept(_:invitee:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidAccept:invitee:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didJoin(_:inviter:message:)\/title","value":"didJoinGroup:inviter:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didJoin(_:inviter:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didJoinGroup:inviter:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didLeave(_:reason:)\/title","value":"didLeaveGroup:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didLeave(_:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didLeaveGroup:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/title","value":"groupInvitationDidReceive:groupName:inviter:message:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title","value":"GroupServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments","value":[{"kind":"identifier","text":"GroupServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidLeave(_:user:)\/title","value":"userDidLeaveGroup:user:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidLeave(_:user:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"userDidLeaveGroup:user:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/title","value":"groupInvitationDidDecline:invitee:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"groupInvitationDidDecline:invitee:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidReceive(_:user:reason:)\/title","value":"joinGroupRequestDidReceive:user:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidReceive(_:user:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinGroupRequestDidReceive:user:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidDecline(_:reason:)\/title","value":"joinGroupRequestDidDecline:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidDecline(_:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinGroupRequestDidDecline:reason:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidApprove(_:)\/title","value":"joinGroupRequestDidApprove:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidApprove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"joinGroupRequestDidApprove:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}