{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/declineJoinApplication(groupId:userId:reason:completion:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/declinejoinapplication(groupid:userid:reason:completion:)"]},{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/declinejoinapplication(groupid:userid:reason:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"declineJoinApplication","kind":"identifier"},{"text":"(","kind":"text"},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"extendedModule":"EaseChatUIKit","title":"declineJoinApplication(groupId:userId:reason:completion:)","navigatorTitle":[{"kind":"identifier","text":"declineJoinApplicationWithGroupId:userId:reason:completion:"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupServiceImplement(im)declineJoinApplicationWithGroupId:userId:reason:completion:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"declineJoinApplication"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"reason","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"attribute"},{"kind":"text","text":" ("},{"kind":"typeIdentifier","text":"ChatGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"ID of the group."}],"type":"paragraph"}],"name":"groupId"},{"content":[{"inlineContent":[{"text":"ID of the user.","type":"text"}],"type":"paragraph"}],"name":"userId"},{"content":[{"inlineContent":[{"text":"Reason for rejection.","type":"text"}],"type":"paragraph"}],"name":"reason"},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a non-empty group object will be returned. If failed, a non-empty group object will be returned."}]}]}],"kind":"parameters"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations"]]},"abstract":[{"type":"text","text":"Decline the application of the user."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"title":"ChatError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chaterror","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/GroupService-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupservice-implementations","role":"collectionGroup","title":"GroupService Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","navigatorTitle":[{"kind":"identifier","text":"GroupServiceImplement"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement","role":"symbol","title":"GroupServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroup":{"title":"ChatGroup","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/declineJoinApplication(groupId:userId:reason:completion:)":{"url":"\/documentation\/easechatuikit\/groupserviceimplement\/declinejoinapplication(groupid:userid:reason:completion:)","abstract":[{"type":"text","text":"Decline the application of the user."}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"declineJoinApplication"},{"kind":"text","text":"("},{"text":"groupId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":"?, "},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","title":"declineJoinApplication(groupId:userId:reason:completion:)","navigatorTitle":[{"kind":"identifier","text":"declineJoinApplicationWithGroupId:userId:reason:completion:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/declineJoinApplication(groupId:userId:reason:completion:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"declineJoinApplicationWithGroupId:userId:reason:completion:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"declineJoinApplicationWithGroupId:userId:reason:completion:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"declineJoinApplicationWithGroupId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"groupId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"userId:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"text":"reason:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"reason","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" (^","kind":"text"},{"kind":"text","text":")("},{"preciseIdentifier":"c:objc(cs)EMGroup","kind":"typeIdentifier","text":"EMGroup"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":""},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)EMError","kind":"typeIdentifier","text":"EMError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"GroupServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments","value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1declineJoinApplication(groupId:userId:reason:completion:)\/title","op":"replace","value":"declineJoinApplicationWithGroupId:userId:reason:completion:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1declineJoinApplication(groupId:userId:reason:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"declineJoinApplicationWithGroupId:userId:reason:completion:"}]}]}]}