{"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/emgroupmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/emgroupmanagerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","metadata":{"roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}],"title":"EMGroupManagerDelegate Implementations","role":"collectionGroup"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)"],"generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMGroupManagerDelegate-Implementations","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/userDidLeave(_:user:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)","url":"\/documentation\/easechatuikit\/groupserviceimplement\/userdidleave(_:user:)","abstract":[],"navigatorTitle":[{"text":"userDidLeaveGroup:user:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"userDidLeave","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":", "},{"text":"user","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"userDidLeave(_:user:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupInvitationDidAccept(_:invitee:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupInvitationDidAccept"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":", "},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"groupInvitationDidAccept(_:invitee:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"groupInvitationDidAccept:invitee:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdidaccept(_:invitee:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupInvitationDidReceive(_:groupName:inviter:message:)":{"url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdidreceive(_:groupname:inviter:message:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupInvitationDidReceive"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}],"title":"groupInvitationDidReceive(_:groupName:inviter:message:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement","kind":"symbol","abstract":[],"title":"GroupServiceImplement","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/userDidJoin(_:user:)":{"title":"userDidJoin(_:user:)","navigatorTitle":[{"text":"userDidJoinGroup:user:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"userDidJoin","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"text":", ","kind":"text"},{"text":"user","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/userdidjoin(_:user:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","abstract":[],"type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupOwnerDidUpdate(_:newOwner:oldOwner:)":{"navigatorTitle":[{"text":"groupOwnerDidUpdate:newOwner:oldOwner:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","kind":"symbol","role":"symbol","title":"groupOwnerDidUpdate(_:newOwner:oldOwner:)","url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupownerdidupdate(_:newowner:oldowner:)","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"groupOwnerDidUpdate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier","text":"ChatGroup"},{"kind":"text","text":", "},{"text":"newOwner","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"oldOwner","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/joinGroupRequestDidApprove(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"joinGroupRequestDidApprove","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"joinGroupRequestDidApprove(_:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidApprove:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/joingrouprequestdidapprove(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onAttributesChangedOfGroupMember"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"attributes","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?, ","kind":"text"},{"text":"operatorId","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"abstract":[],"type":"topic","title":"onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/onattributeschangedofgroupmember(_:userid:attributes:operatorid:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/joinGroupRequestDidDecline(_:reason:)":{"type":"topic","abstract":[],"title":"joinGroupRequestDidDecline(_:reason:)","role":"symbol","url":"\/documentation\/easechatuikit\/groupserviceimplement\/joingrouprequestdiddecline(_:reason:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"joinGroupRequestDidDecline","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidDecline:reason:"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/joinGroupRequestDidReceive(_:user:reason:)":{"abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"joinGroupRequestDidReceive"},{"text":"(","kind":"text"},{"text":"ChatGroup","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"user"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"joinGroupRequestDidReceive(_:user:reason:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","url":"\/documentation\/easechatuikit\/groupserviceimplement\/joingrouprequestdidreceive(_:user:reason:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"joinGroupRequestDidReceive:user:reason:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/didJoin(_:inviter:message:)":{"abstract":[],"kind":"symbol","type":"topic","title":"didJoin(_:inviter:message:)","navigatorTitle":[{"kind":"identifier","text":"didJoinGroup:inviter:message:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"didJoin","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","role":"symbol","url":"\/documentation\/easechatuikit\/groupserviceimplement\/didjoin(_:inviter:message:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/didLeave(_:reason:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didLeave"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"reason"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupLeaveReason","preciseIdentifier":"s:13EaseChatUIKit16GroupLeaveReasona"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"didLeaveGroup:reason:"}],"title":"didLeave(_:reason:)","url":"\/documentation\/easechatuikit\/groupserviceimplement\/didleave(_:reason:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupInvitationDidDecline(_:invitee:reason:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","kind":"symbol","url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdiddecline(_:invitee:reason:)","title":"groupInvitationDidDecline(_:invitee:reason:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupInvitationDidDecline","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"invitee"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"reason","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"navigatorTitle":[{"text":"groupInvitationDidDecline:invitee:reason:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didJoin(_:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/didLeave(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidAccept(_:invitee:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidDecline(_:invitee:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupOwnerDidUpdate(_:newOwner:oldOwner:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidApprove(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidDecline(_:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/joinGroupRequestDidReceive(_:user:reason:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidJoin(_:user:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/userDidLeave(_:user:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidLeave(_:user:)\/title","value":"userDidLeaveGroup:user:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidLeave(_:user:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userDidLeaveGroup:user:"}],"op":"replace"},{"op":"replace","value":"groupInvitationDidAccept:invitee:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidAccept(_:invitee:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidAccept(_:invitee:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"groupInvitationDidAccept:invitee:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/title","value":"groupInvitationDidReceive:groupName:inviter:message:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}]},{"value":"GroupServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title"},{"value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments"},{"value":"userDidJoinGroup:user:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidJoin(_:user:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1userDidJoin(_:user:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"userDidJoinGroup:user:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/title","op":"replace","value":"groupOwnerDidUpdate:newOwner:oldOwner:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"groupOwnerDidUpdate:newOwner:oldOwner:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupOwnerDidUpdate(_:newOwner:oldOwner:)\/fragments"},{"value":"joinGroupRequestDidApprove:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidApprove(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidApprove(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"joinGroupRequestDidApprove:","kind":"identifier"}]},{"value":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onAttributesChangedOfGroupMember:userId:attributes:operatorId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onAttributesChangedOfGroupMember(_:userId:attributes:operatorId:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidDecline(_:reason:)\/title","value":"joinGroupRequestDidDecline:reason:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidDecline(_:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"joinGroupRequestDidDecline:reason:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidReceive(_:user:reason:)\/title","op":"replace","value":"joinGroupRequestDidReceive:user:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1joinGroupRequestDidReceive(_:user:reason:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"joinGroupRequestDidReceive:user:reason:","kind":"identifier"}]},{"value":"didJoinGroup:inviter:message:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didJoin(_:inviter:message:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didJoin(_:inviter:message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"didJoinGroup:inviter:message:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didLeave(_:reason:)\/title","op":"replace","value":"didLeaveGroup:reason:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1didLeave(_:reason:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didLeaveGroup:reason:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/title","value":"groupInvitationDidDecline:invitee:reason:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"groupInvitationDidDecline:invitee:reason:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidDecline(_:invitee:reason:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}