{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"EMThreadManagerDelegate Implementations","role":"collectionGroup","roleHeading":"API Collection"},"kind":"article","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMThreadManagerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadCreate(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadDestroy(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/emthreadmanagerdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/emthreadmanagerdelegate-implementations"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","kind":"symbol","navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement","title":"GroupServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/onChatThreadCreate(_:)":{"url":"\/documentation\/easechatuikit\/groupserviceimplement\/onchatthreadcreate(_:)","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadCreate(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onChatThreadCreate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"GroupChatThreadEvent","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"title":"onChatThreadCreate(_:)","abstract":[],"navigatorTitle":[{"text":"onChatThreadCreate:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/onChatThreadDestroy(_:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadDestroy(_:)","type":"topic","navigatorTitle":[{"text":"onChatThreadDestroy:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onChatThreadDestroy","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/onchatthreaddestroy(_:)","title":"onChatThreadDestroy(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/onUserKickOutOfChatThread(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onUserKickOutOfChatThread","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"onUserKickOutOfChatThread(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"onUserKickOutOfChatThread:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/onuserkickoutofchatthread(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/onChatThreadUpdate(_:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/onchatthreadupdate(_:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onChatThreadUpdate","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","kind":"typeIdentifier","text":"GroupChatThreadEvent"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onChatThreadUpdate:"}],"title":"onChatThreadUpdate(_:)","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadCreate(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadDestroy(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onUserKickOutOfChatThread(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title","op":"replace","value":"GroupServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments","op":"replace","value":[{"text":"GroupServiceImplement","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadCreate(_:)\/title","value":"onChatThreadCreate:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadCreate(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadCreate:"}],"op":"replace"},{"value":"onChatThreadDestroy:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadDestroy(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadDestroy(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onChatThreadDestroy:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onUserKickOutOfChatThread(_:)\/title","value":"onUserKickOutOfChatThread:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onUserKickOutOfChatThread:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onUserKickOutOfChatThread(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadUpdate(_:)\/title","value":"onChatThreadUpdate:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onChatThreadUpdate:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadUpdate(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}