{"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/fetchmemberattribute(groupid:userid:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/fetchmemberattribute(groupid:userid:completion:)"]}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupServiceImplement(im)fetchMemberAttributeWithGroupId:userId:completion:","role":"symbol","extendedModule":"EaseChatUIKit","title":"fetchMemberAttribute(groupId:userId:completion:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchMemberAttribute"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": ("},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fetchMemberAttributeWithGroupId:userId:completion:"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/fetchMemberAttribute(groupId:userId:completion:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Get individual group member attributes.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fetchMemberAttribute"},{"kind":"text","text":"("},{"kind":"externalParam","text":"groupId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"text":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:SD","text":"Dictionary","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"ID of the group.","type":"text"}],"type":"paragraph"}],"name":"groupId"},{"name":"userId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the user."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The request callback contains the group object and error information. If successful, a empty error object will be returned. If failed, a non-empty group object will be returned."}]}],"name":"completion"}],"kind":"parameters"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement","kind":"symbol","abstract":[],"title":"GroupServiceImplement","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/fetchMemberAttribute(groupId:userId:completion:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/fetchMemberAttribute(groupId:userId:completion:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fetchMemberAttribute","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"groupId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fetchMemberAttributeWithGroupId:userId:completion:"}],"kind":"symbol","title":"fetchMemberAttribute(groupId:userId:completion:)","role":"symbol","abstract":[{"type":"text","text":"Get individual group member attributes."}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/fetchmemberattribute(groupid:userid:completion:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/GroupService-Implementations":{"url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupservice-implementations","kind":"article","abstract":[],"title":"GroupService Implementations","role":"collectionGroup","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"url":"\/documentation\/easechatuikit\/chaterror","role":"symbol","abstract":[],"title":"ChatError","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"}],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"fetchMemberAttributeWithGroupId:userId:completion:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"fetchMemberAttributeWithGroupId:userId:completion:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"fetchMemberAttributeWithGroupId:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"groupId"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":" (^"},{"kind":"text","text":")("},{"text":"EMError","preciseIdentifier":"c:objc(cs)EMError","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"text":")) ","kind":"text"},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title","value":"GroupServiceImplement","op":"replace"},{"value":[{"text":"GroupServiceImplement","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1fetchMemberAttribute(groupId:userId:completion:)\/title","value":"fetchMemberAttributeWithGroupId:userId:completion:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1fetchMemberAttribute(groupId:userId:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fetchMemberAttributeWithGroupId:userId:completion:","kind":"identifier"}],"op":"replace"}]}]}