{"metadata":{"title":"groupInvitationDidReceive(_:groupName:inviter:message:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupServiceImplement(im)groupInvitationDidReceive:groupName:inviter:message:","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"groupInvitationDidReceive"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"groupName"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"modules":[{"name":"EaseChatUIKit"}]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"EMGroupManagerDelegate.groupInvitationDidReceive(_:groupName:inviter:message:)"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdidreceive(_:groupname:inviter:message:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdidreceive(_:groupname:inviter:message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMGroupManagerDelegate-Implementations"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"groupInvitationDidReceive","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"aGroupId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"groupName","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aGroupName","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"inviter","kind":"externalParam"},{"kind":"text","text":" "},{"text":"aInviter","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"message","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"aMessage","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","navigatorTitle":[{"kind":"identifier","text":"GroupServiceImplement"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement","role":"symbol","title":"GroupServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/EMGroupManagerDelegate-Implementations":{"kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement\/emgroupmanagerdelegate-implementations","abstract":[],"title":"EMGroupManagerDelegate Implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMGroupManagerDelegate-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/groupInvitationDidReceive(_:groupName:inviter:message:)":{"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupInvitationDidReceive"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"groupName","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"inviter","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/groupInvitationDidReceive(_:groupName:inviter:message:)","role":"symbol","title":"groupInvitationDidReceive(_:groupName:inviter:message:)","kind":"symbol","url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupinvitationdidreceive(_:groupname:inviter:message:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"groupInvitationDidReceive:groupName:inviter:message:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"groupInvitationDidReceive:groupName:inviter:message:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"groupInvitationDidReceive:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"aGroupId","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupName:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"aGroupName","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"inviter:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"aInviter"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"aMessage","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"GroupServiceImplement","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GroupServiceImplement"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/title","value":"groupInvitationDidReceive:groupName:inviter:message:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1groupInvitationDidReceive(_:groupName:inviter:message:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"groupInvitationDidReceive:groupName:inviter:message:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}