{"metadata":{"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupServiceImplement(im)onChatThreadUpdate:","symbolKind":"method","title":"onChatThreadUpdate(_:)","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"onChatThreadUpdate:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onChatThreadUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}],"extendedModule":"EaseChatUIKit"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onChatThreadUpdate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"event","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/onchatthreadupdate(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/onchatthreadupdate(_:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"EMThreadManagerDelegate.onChatThreadUpdate(_:)"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMThreadManagerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"navigatorTitle":[{"text":"GroupServiceImplement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement","kind":"symbol","abstract":[],"title":"GroupServiceImplement","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEvent":{"navigatorTitle":[{"text":"GroupChatThreadEvent","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","url":"\/documentation\/easechatuikit\/groupchatthreadevent","role":"symbol","abstract":[],"title":"GroupChatThreadEvent","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupChatThreadEvent"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/EMThreadManagerDelegate-Implementations":{"type":"topic","title":"EMThreadManagerDelegate Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/easechatuikit\/groupserviceimplement\/emthreadmanagerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/EMThreadManagerDelegate-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/onChatThreadUpdate(_:)":{"navigatorTitle":[{"text":"onChatThreadUpdate:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/onChatThreadUpdate(_:)","kind":"symbol","role":"symbol","title":"onChatThreadUpdate(_:)","url":"\/documentation\/easechatuikit\/groupserviceimplement\/onchatthreadupdate(_:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onChatThreadUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"GroupChatThreadEvent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onChatThreadUpdate:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onChatThreadUpdate:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onChatThreadUpdate:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)EMChatThreadEvent","kind":"typeIdentifier","text":"EMChatThreadEvent"},{"kind":"text","text":" *) "},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"GroupServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments","value":[{"text":"GroupServiceImplement","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadUpdate(_:)\/title","value":"onChatThreadUpdate:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1onChatThreadUpdate(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onChatThreadUpdate:","kind":"identifier"}],"op":"replace"}]}]}