{"kind":"symbol","sections":[],"metadata":{"title":"unbindGroupChatThreadEventListener(listener:)","roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupServiceImplement(im)unbindGroupChatThreadEventListenerWithListener:","symbolKind":"method","navigatorTitle":[{"text":"unbindGroupChatThreadEventListenerWithListener:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindGroupChatThreadEventListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener","text":"GroupChatThreadEventListener"},{"kind":"text","text":")"}],"modules":[{"name":"EaseChatUIKit"}]},"abstract":[{"text":"Unbind group chat thread event listener","type":"text"}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/unbindgroupchatthreadeventlistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/unbindgroupchatthreadeventlistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/unbindGroupChatThreadEventListener(listener:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindGroupChatThreadEventListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"text":"GroupChatThreadEventListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","isActive":true}],"type":"paragraph"}],"name":"listener"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventListener":{"title":"GroupChatThreadEventListener","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupChatThreadEventListener","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupchatthreadeventlistener","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventListener","navigatorTitle":[{"text":"GroupChatThreadEventListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/unbindGroupChatThreadEventListener(listener:)":{"url":"\/documentation\/easechatuikit\/groupserviceimplement\/unbindgroupchatthreadeventlistener(listener:)","abstract":[{"type":"text","text":"Unbind group chat thread event listener"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unbindGroupChatThreadEventListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupChatThreadEventListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener"},{"kind":"text","text":")"}],"title":"unbindGroupChatThreadEventListener(listener:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/unbindGroupChatThreadEventListener(listener:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"unbindGroupChatThreadEventListenerWithListener:"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/GroupService-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupservice-implementations","role":"collectionGroup","title":"GroupService Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GroupServiceImplement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","navigatorTitle":[{"kind":"identifier","text":"GroupServiceImplement"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement","role":"symbol","title":"GroupServiceImplement"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unbindGroupChatThreadEventListenerWithListener:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"unbindGroupChatThreadEventListenerWithListener:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unbindGroupChatThreadEventListenerWithListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GroupChatThreadEventListener>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)GroupChatThreadEventListener"},{"kind":"text","text":") "},{"text":"listener","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/title","value":"GroupChatThreadEventListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventListener\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventListener"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1unbindGroupChatThreadEventListener(listener:)\/title","value":"unbindGroupChatThreadEventListenerWithListener:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1unbindGroupChatThreadEventListener(listener:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"unbindGroupChatThreadEventListenerWithListener:","kind":"identifier"}]},{"value":"GroupServiceImplement","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments","value":[{"text":"GroupServiceImplement","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}