{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindGroupEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener","text":"GroupServiceListener"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/unbindgroupeventslistener(listener:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupserviceimplement\/unbindgroupeventslistener(listener:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/unbindGroupEventsListener(listener:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Unbind group event changed listener"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"unbindGroupEventsListenerWithListener:"}],"role":"symbol","title":"unbindGroupEventsListener(listener:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindGroupEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupServiceImplement(im)unbindGroupEventsListenerWithListener:","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement":{"role":"symbol","title":"GroupServiceImplement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceImplement"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupServiceImplement"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/GroupService-Implementations":{"role":"collectionGroup","title":"GroupService Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/GroupService-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/groupserviceimplement\/groupservice-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceImplement/unbindGroupEventsListener(listener:)":{"role":"symbol","title":"unbindGroupEventsListener(listener:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unbindGroupEventsListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupServiceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)GroupServiceListener"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Unbind group event changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceImplement\/unbindGroupEventsListener(listener:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unbindGroupEventsListenerWithListener:"}],"url":"\/documentation\/easechatuikit\/groupserviceimplement\/unbindgroupeventslistener(listener:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupServiceListener":{"role":"symbol","title":"GroupServiceListener","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupServiceListener"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupServiceListener","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupServiceListener"}],"url":"\/documentation\/easechatuikit\/groupservicelistener"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"unbindGroupEventsListenerWithListener:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindGroupEventsListenerWithListener:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"unbindGroupEventsListenerWithListener:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<GroupServiceListener>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)GroupServiceListener"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"listener"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/title","value":"GroupServiceImplement"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement\/fragments","value":[{"kind":"identifier","text":"GroupServiceImplement"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1unbindGroupEventsListener(listener:)\/title","value":"unbindGroupEventsListenerWithListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceImplement~1unbindGroupEventsListener(listener:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindGroupEventsListenerWithListener:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/title","value":"GroupServiceListener"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupServiceListener\/fragments","value":[{"kind":"identifier","text":"GroupServiceListener"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}