{"kind":"symbol","abstract":[{"type":"text","text":"The option of UI components."}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)EaseChatUIKitOptions(py)option_UI","title":"option_UI","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"option_UI","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions","kind":"typeIdentifier","text":"UIOptions"}],"navigatorTitle":[{"kind":"identifier","text":"option_UI"}],"symbolKind":"property","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitOptions\/option_UI"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/easechatuikitoptions\/option_ui"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/easechatuikitoptions\/option_ui"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitOptions"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"option_UI"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions","text":"UIOptions","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitOptions/option_UI":{"abstract":[{"type":"text","text":"The option of UI components."}],"role":"symbol","title":"option_UI","url":"\/documentation\/easechatuikit\/easechatuikitoptions\/option_ui","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"option_UI"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions","text":"UIOptions"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitOptions\/option_UI","type":"topic","navigatorTitle":[{"text":"option_UI","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/UIOptions":{"navigatorTitle":[{"kind":"identifier","text":"UIOptions"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"UIOptions"}],"url":"\/documentation\/easechatuikit\/uioptions","kind":"symbol","abstract":[],"title":"UIOptions","role":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitOptions":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EaseChatUIKitOptions","kind":"identifier"}],"role":"symbol","title":"EaseChatUIKitOptions","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/easechatuikitoptions","navigatorTitle":[{"text":"EaseChatUIKitOptions","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitOptions"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"option_UI","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"option_UI"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"text":"UIOptions","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)UIOptions","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/UIOptions"},{"kind":"text","text":" * "},{"text":"option_UI","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitOptions~1option_UI\/title","value":"option_UI","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitOptions~1option_UI\/fragments","op":"replace","value":[{"text":"option_UI","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions\/title","value":"UIOptions"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1UIOptions\/fragments","value":[{"text":"UIOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitOptions\/title","value":"EaseChatUIKitOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitOptions\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}