{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"metadata":{"title":"EaseChatUIKitCacheType.all","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType@EaseChatUIKitCacheTypeAll","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeAll"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"all","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/easechatuikitcachetype\/all"]},{"paths":["\/documentation\/easechatuikit\/easechatuikitcachetype\/all"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType\/all","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitCacheType":{"url":"\/documentation\/easechatuikit\/easechatuikitcachetype","title":"EaseChatUIKitCacheType","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"navigatorTitle":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitCacheType/all":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType\/all","title":"EaseChatUIKitCacheType.all","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"all"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/easechatuikitcachetype\/all","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeAll"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"EaseChatUIKitCacheTypeAll","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"EaseChatUIKitCacheTypeAll","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"EaseChatUIKitCacheTypeAll","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/title","value":"EaseChatUIKitCacheType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/fragments","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/navigatorTitle","value":[{"text":"EaseChatUIKitCacheType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType~1all\/title","op":"replace","value":"EaseChatUIKitCacheTypeAll"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType~1all\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeAll"}],"op":"replace"}]}]}