{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMemberAttribute"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/easechatuikitcachetype\/groupmemberattribute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/easechatuikitcachetype\/groupmemberattribute"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType\/groupMemberAttribute","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMemberAttribute"}],"title":"EaseChatUIKitCacheType.groupMemberAttribute","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@EaseChatUIKitCacheType@EaseChatUIKitCacheTypeGroupMemberAttribute","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeGroupMemberAttribute"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitCacheType":{"role":"symbol","title":"EaseChatUIKitCacheType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}],"url":"\/documentation\/easechatuikit\/easechatuikitcachetype"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatUIKitCacheType/groupMemberAttribute":{"role":"symbol","title":"EaseChatUIKitCacheType.groupMemberAttribute","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"groupMemberAttribute"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatUIKitCacheType\/groupMemberAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeGroupMemberAttribute"}],"url":"\/documentation\/easechatuikit\/easechatuikitcachetype\/groupmemberattribute"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"EaseChatUIKitCacheTypeGroupMemberAttribute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeGroupMemberAttribute"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeGroupMemberAttribute"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/title","value":"EaseChatUIKitCacheType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType~1groupMemberAttribute\/title","value":"EaseChatUIKitCacheTypeGroupMemberAttribute"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatUIKitCacheType~1groupMemberAttribute\/fragments","value":[{"kind":"identifier","text":"EaseChatUIKitCacheTypeGroupMemberAttribute"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}