{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/audiomessageview\/themeswitchprotocol-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/audiomessageview\/themeswitchprotocol-implementations"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView"]]},"sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView\/switchTheme(style:)"],"title":"Instance Methods","generated":true}],"kind":"article","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"ThemeSwitchProtocol Implementations","modules":[{"name":"EaseChatUIKit"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioMessageView":{"role":"symbol","navigatorTitle":[{"text":"AudioMessageView","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/audiomessageview","title":"AudioMessageView","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AudioMessageView","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioMessageView/switchTheme(style:)":{"role":"symbol","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/audiomessageview\/switchtheme(style:)","title":"switchTheme(style:)","kind":"symbol","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView\/switchTheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView\/switchTheme(style:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":"AudioMessageView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageView\/fragments","op":"replace","value":[{"kind":"identifier","text":"AudioMessageView"}]},{"value":"switchThemeWithStyle:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageView~1switchTheme(style:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchThemeWithStyle:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageView~1switchTheme(style:)\/fragments"}]}]}