{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView\/towards","interfaceLanguage":"swift"},"metadata":{"title":"towards","symbolKind":"property","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"towards"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","text":"BubbleTowards"}],"externalID":"s:13EaseChatUIKit16AudioMessageViewC7towardsAA13BubbleTowardsOvp"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"towards","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BubbleTowards","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards"},{"text":" { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/audiomessageview\/towards"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioMessageView":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AudioMessageView"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AudioMessageView"}],"title":"AudioMessageView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView","abstract":[],"url":"\/documentation\/easechatuikit\/audiomessageview","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioMessageView/towards":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"towards","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","text":"BubbleTowards","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioMessageView\/towards","kind":"symbol","title":"towards","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/audiomessageview\/towards","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/BubbleTowards":{"role":"symbol","type":"topic","title":"BubbleTowards","kind":"symbol","url":"\/documentation\/easechatuikit\/bubbletowards","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BubbleTowards"}],"navigatorTitle":[{"text":"BubbleTowards","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards"}},"variantOverrides":[{"patch":[{"value":"AudioMessageView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageView\/fragments","value":[{"text":"AudioMessageView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"AudioMessageView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioMessageView\/navigatorTitle"},{"op":"replace","value":"BubbleTowards","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/title"},{"value":[{"kind":"identifier","text":"BubbleTowards"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/navigatorTitle","value":[{"kind":"identifier","text":"BubbleTowards"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}