{"abstract":[{"text":"Opens the chat conversation for the current group.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/alreadychat()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/alreadychat()"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"alreadyChat","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method is called when the user wants to open the chat conversation for the current group. It performs the following steps:"}]},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Acknowledges the conversation read by calling "},{"type":"codeVoice","code":"ackConversationRead"},{"type":"text","text":" method of the shared "},{"type":"codeVoice","code":"ChatClient"},{"type":"text","text":" instance."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Checks if the previous view controller in the navigation stack is "},{"code":"MessageListController","type":"codeVoice"},{"type":"text","text":"."}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If it is, pops to the view controller before that and then pushes a new instance of ","type":"text"},{"code":"ComponentsRegister.shared.MessageViewController","type":"codeVoice"},{"text":" with the conversation ID and chat type set to ","type":"text"},{"type":"codeVoice","code":".group"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If it is not, directly pushes a new instance of ","type":"text"},{"code":"ComponentsRegister.shared.MessageViewController","type":"codeVoice"},{"type":"text","text":" with the conversation ID and chat type set to "},{"type":"codeVoice","code":".group"},{"type":"text","text":"."}]}]}]}]},{"content":[{"inlineContent":[{"text":"If the navigation stack is empty, checks if the presenting view controller is ","type":"text"},{"code":"MessageListController","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"text":"If it is, dismisses the presenting view controller and then presents a new instance of ","type":"text"},{"type":"codeVoice","code":"ComponentsRegister.shared.MessageViewController"},{"text":" with the conversation ID and chat type set to ","type":"text"},{"code":".group","type":"codeVoice"},{"text":".","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If it is not, presents a new instance of ","type":"text"},{"code":"ComponentsRegister.shared.MessageViewController","type":"codeVoice"},{"type":"text","text":" with the conversation ID and chat type set to "},{"type":"codeVoice","code":".group"},{"type":"text","text":" using the full screen modal presentation style."}]}]}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"If there is no presenting view controller, creates a new instance of ","type":"text"},{"type":"codeVoice","code":"ComponentsRegister.shared.MessageViewController"},{"type":"text","text":" with the conversation ID and chat type set to "},{"type":"codeVoice","code":".group"},{"text":" and navigates to it using ","type":"text"},{"code":"ControllerStack.toDestination","type":"codeVoice"},{"text":" method.","type":"text"}]}]}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/alreadyChat()","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"alreadyChat","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","title":"alreadyChat()","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController(im)alreadyChat","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"alreadyChat"},{"kind":"text","text":"()"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupInfoViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupInfoViewController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","type":"topic","title":"GroupInfoViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/alreadyChat()":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/alreadyChat()","navigatorTitle":[{"text":"alreadyChat","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/alreadychat()","title":"alreadyChat()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"alreadyChat","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","abstract":[{"text":"Opens the chat conversation for the current group.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"alreadyChat","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"alreadyChat","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"text":"alreadyChat","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"GroupInfoViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","value":[{"kind":"identifier","text":"GroupInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1alreadyChat()\/title","value":"alreadyChat"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"alreadyChat"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1alreadyChat()\/fragments"}]}]}