{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createNavigation","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"EaseChatNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"An instance of EaseChatNavigationBar."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/createnavigation()"]},{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/createnavigation()"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/createNavigation()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"abstract":[{"text":"Creates and returns a navigation bar for the GroupInfoViewController.","type":"text"}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController(im)createNavigation","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createNavigation","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","text":"EaseChatNavigationBar","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"createNavigation","kind":"identifier"}],"symbolKind":"method","title":"createNavigation()","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar":{"kind":"symbol","type":"topic","title":"EaseChatNavigationBar","abstract":[{"text":"Navigation  bar of the EaseChatUIKit.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","url":"\/documentation\/easechatuikit\/easechatnavigationbar","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatNavigationBar","kind":"identifier"}],"navigatorTitle":[{"text":"EaseChatNavigationBar","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupInfoViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupInfoViewController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","type":"topic","title":"GroupInfoViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/createNavigation()":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/createNavigation()","navigatorTitle":[{"text":"createNavigation","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates and returns a navigation bar for the GroupInfoViewController."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createNavigation"},{"text":"() -> ","kind":"text"},{"text":"EaseChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"}],"title":"createNavigation()","role":"symbol","url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/createnavigation()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createNavigation"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"createNavigation","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","text":"EaseChatNavigationBar"},{"text":" *) ","kind":"text"},{"text":"createNavigation","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"EaseChatNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/title"},{"value":[{"text":"EaseChatNavigationBar","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","value":"GroupInfoViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"GroupInfoViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1createNavigation()\/title","value":"createNavigation"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"createNavigation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1createNavigation()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}