{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"disband"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Disbands the group."},{"type":"text","text":" "},{"type":"text","text":"This method shows an alert to confirm the disbanding of the group. If the user confirms, it calls the "},{"type":"codeVoice","code":"disband"},{"text":" method of the ","type":"text"},{"code":"service","type":"codeVoice"},{"type":"text","text":" object to disband the group. After successful disbanding, it posts a notification with the group ID and pops the current view controller from the navigation stack. If there is an error during the disbanding process, it logs the error message."}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/disband()","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController(im)disband","title":"disband()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"disband"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"disband"}],"symbolKind":"method","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/disband()"]},{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/disband()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/disband()":{"abstract":[{"type":"text","text":"Disbands the group."},{"type":"text","text":" "},{"type":"text","text":"This method shows an alert to confirm the disbanding of the group. If the user confirms, it calls the "},{"code":"disband","type":"codeVoice"},{"type":"text","text":" method of the "},{"code":"service","type":"codeVoice"},{"text":" object to disband the group. After successful disbanding, it posts a notification with the group ID and pops the current view controller from the navigation stack. If there is an error during the disbanding process, it logs the error message.","type":"text"}],"role":"symbol","title":"disband()","url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/disband()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"disband","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/disband()","navigatorTitle":[{"kind":"identifier","text":"disband"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoViewController"}],"title":"GroupInfoViewController","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"disband","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"disband","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"disband"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1disband()\/title","value":"disband","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1disband()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"disband","kind":"identifier"}]},{"value":"GroupInfoViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title"},{"value":[{"text":"GroupInfoViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments"}]}]}