{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/fillDatas()","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Fills the data for the GroupInfoViewController.","type":"text"}],"metadata":{"title":"fillDatas()","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillDatas"},{"text":"() -> [[","kind":"text"},{"text":"DetailInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfo","kind":"typeIdentifier"},{"text":"]]","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"fillDatas","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController(im)fillDatas"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/filldatas()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/filldatas()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fillDatas"},{"text":"() -> [[","kind":"text"},{"text":"DetailInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfo","kind":"typeIdentifier"},{"kind":"text","text":"]]"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"An array of arrays of DetailInfo objects representing the filled data."}],"type":"paragraph"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"abstract":[],"navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"title":"GroupInfoViewController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"GroupInfoViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo":{"type":"topic","title":"DetailInfo","navigatorTitle":[{"text":"DetailInfo","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetailInfo","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/detailinfo","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/fillDatas()":{"navigatorTitle":[{"kind":"identifier","text":"fillDatas"}],"title":"fillDatas()","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Fills the data for the GroupInfoViewController."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/fillDatas()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"fillDatas","kind":"identifier"},{"text":"() -> [[","kind":"text"},{"text":"DetailInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfo","kind":"typeIdentifier"},{"kind":"text","text":"]]"}],"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/filldatas()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"fillDatas","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"fillDatas","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"NSArray<NSArray<DetailInfo *> *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fillDatas"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"An array of arrays of DetailInfo objects representing the filled data.","type":"text"}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","op":"replace","value":"GroupInfoViewController"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","value":[{"text":"GroupInfoViewController","kind":"identifier"}],"op":"replace"},{"value":[{"text":"GroupInfoViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo\/title","op":"replace","value":"DetailInfo"},{"value":[{"text":"DetailInfo","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo\/navigatorTitle","op":"replace","value":[{"text":"DetailInfo","kind":"identifier"}]},{"value":"fillDatas","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1fillDatas()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"fillDatas","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1fillDatas()\/fragments"}]}]}