{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"handleEditCallback","kind":"identifier"},{"kind":"text","text":"("},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupInfoEditType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditType","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupInfoEditType"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"text","content":[{"inlineContent":[{"text":"The edited text.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The type of information being edited."}],"type":"paragraph"}],"name":"type"}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleEditCallback"},{"text":"(","kind":"text"},{"text":"text","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"GroupInfoEditType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupInfoEditType"},{"text":")","kind":"text"}],"title":"handleEditCallback(text:type:)","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupInfoViewController(im)handleEditCallbackWithText:type:","navigatorTitle":[{"kind":"identifier","text":"handleEditCallbackWithText:type:"}],"extendedModule":"EaseChatUIKit"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/handleEditCallback(text:type:)"},"sections":[],"abstract":[{"type":"text","text":"Handles the callback for editing group information."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/handleeditcallback(text:type:)"]},{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/handleeditcallback(text:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/handleEditCallback(text:type:)":{"abstract":[{"type":"text","text":"Handles the callback for editing group information."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/handleEditCallback(text:type:)","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/handleeditcallback(text:type:)","title":"handleEditCallback(text:type:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleEditCallback","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"GroupInfoEditType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupInfoEditType"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"handleEditCallbackWithText:type:"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoEditType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupInfoEditType"}],"type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditType","kind":"symbol","url":"\/documentation\/easechatuikit\/groupinfoedittype","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupInfoEditType"}],"title":"GroupInfoEditType"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupInfoViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupInfoViewController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","type":"topic","title":"GroupInfoViewController"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"handleEditCallbackWithText:type:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleEditCallbackWithText:type:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"handleEditCallbackWithText:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"text"},{"text":" ","kind":"text"},{"text":"type:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoEditType","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupInfoEditType","kind":"typeIdentifier","text":"GroupInfoEditType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"handleEditCallbackWithText:type:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1handleEditCallback(text:type:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"handleEditCallbackWithText:type:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1handleEditCallback(text:type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditType\/title","value":"GroupInfoEditType"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoEditType\/fragments","value":[{"kind":"identifier","text":"GroupInfoEditType"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","value":"GroupInfoViewController"},{"value":[{"text":"GroupInfoViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}