{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/memberoptions"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"memberOptions","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"memberOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"ActionSheetItem","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem"},{"text":"]","kind":"text"}],"externalID":"s:13EaseChatUIKit23GroupInfoViewControllerC13memberOptionsSayAA15ActionSheetItemCGvp","symbolKind":"property"},"abstract":[{"type":"text","text":"A private array that stores the member options for the group."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/memberOptions","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"memberOptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ActionSheetItem","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Each member option is represented by an ","type":"text"},{"type":"codeVoice","code":"ActionSheetItem"},{"text":" object, which contains the title, type, and tag of the option.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"Example usage:","type":"text"}]},{"type":"codeListing","syntax":null,"code":["private var memberOptions = [ActionSheetItem(title: \"group_details_extend_button_leave\".chat.localize, type: .destructive, tag: \"quit_group\")]"]}],"kind":"content"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/memberOptions":{"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/memberoptions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/memberOptions","title":"memberOptions","abstract":[{"type":"text","text":"A private array that stores the member options for the group."}],"role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"memberOptions","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem","kind":"typeIdentifier","text":"ActionSheetItem"},{"kind":"text","text":"]"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GroupInfoViewController","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupInfoViewController"}],"abstract":[],"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","type":"topic","title":"GroupInfoViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem":{"url":"\/documentation\/easechatuikit\/actionsheetitem","title":"ActionSheetItem","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem","navigatorTitle":[{"kind":"identifier","text":"ActionSheetItem"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActionSheetItem"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","value":"GroupInfoViewController"},{"op":"replace","value":[{"text":"GroupInfoViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/title","value":"ActionSheetItem"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/fragments","value":[{"text":"ActionSheetItem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}