{"abstract":[{"text":"Handles the navigation click events in the GroupInfoViewController.","type":"text"}],"metadata":{"title":"navigationClick(type:indexPath:)","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"EaseChatNavigationBarClickEvent","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":"?)","kind":"text"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)GroupInfoViewController(im)navigationClickWithType:indexPath:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","text":"EaseChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The type of navigation click event."}]}],"name":"type"},{"name":"indexPath","content":[{"type":"paragraph","inlineContent":[{"text":"The optional index path associated with the event.","type":"text"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/navigationclick(type:indexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/navigationClick(type:indexPath:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/navigationClick(type:indexPath:)":{"type":"topic","title":"navigationClick(type:indexPath:)","navigatorTitle":[{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/navigationclick(type:indexpath:)","abstract":[{"type":"text","text":"Handles the navigation click events in the GroupInfoViewController."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/navigationClick(type:indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"navigationClick","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EaseChatNavigationBarClickEvent","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoViewController"}],"title":"GroupInfoViewController","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent":{"abstract":[],"url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent","navigatorTitle":[{"text":"EaseChatNavigationBarClickEvent","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}],"role":"symbol","title":"EaseChatNavigationBarClickEvent","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"navigationClickWithType:indexPath:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent","text":"EaseChatNavigationBarClickEvent","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"indexPath:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"navigationClickWithType:indexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1navigationClick(type:indexPath:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController~1navigationClick(type:indexPath:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","value":"GroupInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","value":[{"text":"GroupInfoViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/title","value":"EaseChatNavigationBarClickEvent"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}]}]}]}