{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/navigation"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"lazy","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","text":"EaseChatNavigationBar","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/navigation"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EaseChatNavigationBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar"}],"symbolKind":"property","role":"symbol","title":"navigation","externalID":"s:13EaseChatUIKit23GroupInfoViewControllerC10navigationAA0aB13NavigationBarCvp","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EaseChatNavigationBar","kind":"identifier"}],"navigatorTitle":[{"text":"EaseChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the EaseChatUIKit."}],"kind":"symbol","title":"EaseChatNavigationBar","url":"\/documentation\/easechatuikit\/easechatnavigationbar","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoViewController"}],"title":"GroupInfoViewController","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/navigation":{"title":"navigation","kind":"symbol","url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/navigation","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/navigation","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigation"},{"text":": ","kind":"text"},{"text":"EaseChatNavigationBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)EaseChatNavigationBar","kind":"typeIdentifier"}],"role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"EaseChatNavigationBar","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBar"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","value":"GroupInfoViewController"},{"value":[{"kind":"identifier","text":"GroupInfoViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","op":"replace"}]}]}