{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ownerOptions"},{"text":": [","kind":"text"},{"text":"ActionSheetItem","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Example usage:"}]},{"syntax":null,"type":"codeListing","code":["private var ownerOptions = [","    ActionSheetItem(title: \"group_details_extend_button_disband\".chat.localize, type: .destructive, tag: \"disband_group\"),","    ActionSheetItem(title: \"group_details_extend_button_transfer\".chat.localize, type: .destructive, tag: \"transfer_owner\")","]"]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/easechatuikit\/groupinfoviewcontroller\/owneroptions"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"s:13EaseChatUIKit23GroupInfoViewControllerC12ownerOptionsSayAA15ActionSheetItemCGvp","roleHeading":"Instance Property","title":"ownerOptions","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ownerOptions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"ActionSheetItem","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/ownerOptions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController"]]},"abstract":[{"text":"A private array of ","type":"text"},{"type":"codeVoice","code":"ActionSheetItem"},{"type":"text","text":" objects representing the owner options in the group info view controller."},{"type":"text","text":" "},{"type":"text","text":"Each "},{"code":"ActionSheetItem","type":"codeVoice"},{"text":" contains a title, type, and tag.","type":"text"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItem":{"role":"symbol","navigatorTitle":[{"text":"ActionSheetItem","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ActionSheetItem","kind":"identifier"}],"type":"topic","title":"ActionSheetItem","url":"\/documentation\/easechatuikit\/actionsheetitem","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItem","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController/ownerOptions":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ownerOptions"},{"text":": [","kind":"text"},{"text":"ActionSheetItem","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ActionSheetItem","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"ownerOptions","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/groupinfoviewcontroller\/owneroptions","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController\/ownerOptions","abstract":[{"type":"text","text":"A private array of "},{"code":"ActionSheetItem","type":"codeVoice"},{"type":"text","text":" objects representing the owner options in the group info view controller."},{"type":"text","text":" "},{"text":"Each ","type":"text"},{"type":"codeVoice","code":"ActionSheetItem"},{"type":"text","text":" contains a title, type, and tag."}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupInfoViewController":{"url":"\/documentation\/easechatuikit\/groupinfoviewcontroller","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"GroupInfoViewController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupInfoViewController"}],"title":"GroupInfoViewController","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"ActionSheetItem","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItem\/fragments","value":[{"kind":"identifier","text":"ActionSheetItem"}],"op":"replace"},{"value":"GroupInfoViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupInfoViewController\/fragments","value":[{"text":"GroupInfoViewController","kind":"identifier"}]}]}]}