{"kind":"symbol","metadata":{"symbolKind":"case","externalID":"c:@M@EaseChatUIKit@E@ConversationEmergencyType@ConversationEmergencyTypeDelete","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeDelete"}],"role":"symbol","title":"ConversationEmergencyType.delete","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"delete","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delete"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationemergencytype\/delete"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationemergencytype\/delete"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/delete","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/delete":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ConversationEmergencyTypeDelete","kind":"identifier"}],"type":"topic","abstract":[],"title":"ConversationEmergencyType.delete","url":"\/documentation\/easechatuikit\/conversationemergencytype\/delete","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/delete","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delete","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"ConversationEmergencyType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType","abstract":[],"url":"\/documentation\/easechatuikit\/conversationemergencytype","title":"ConversationEmergencyType","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ConversationEmergencyTypeDelete"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyTypeDelete"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"ConversationEmergencyTypeDelete"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1delete\/title","value":"ConversationEmergencyTypeDelete"},{"op":"replace","value":[{"text":"ConversationEmergencyTypeDelete","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1delete\/fragments"},{"value":"ConversationEmergencyType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/title"},{"value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/fragments","op":"replace"}]}]}