{"variants":[{"paths":["\/documentation\/easechatuikit\/conversationemergencytype\/loadallconversationfirstloaduikit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/conversationemergencytype\/loadallconversationfirstloaduikit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAllConversationFirstLoadUIKit"}],"title":"ConversationEmergencyType.loadAllConversationFirstLoadUIKit","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@E@ConversationEmergencyType@ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit","roleHeading":"Case","symbolKind":"case","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/loadAllConversationFirstLoadUIKit"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"loadAllConversationFirstLoadUIKit","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/loadAllConversationFirstLoadUIKit":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAllConversationFirstLoadUIKit","kind":"identifier"}],"title":"ConversationEmergencyType.loadAllConversationFirstLoadUIKit","navigatorTitle":[{"text":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/loadAllConversationFirstLoadUIKit","type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencytype\/loadallconversationfirstloaduikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationemergencytype","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType","navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyType"}],"abstract":[],"title":"ConversationEmergencyType"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1loadAllConversationFirstLoadUIKit\/title","value":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1loadAllConversationFirstLoadUIKit\/fragments","value":[{"text":"ConversationEmergencyTypeLoadAllConversationFirstLoadUIKit","kind":"identifier"}]},{"value":"ConversationEmergencyType","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyType"}]},{"op":"replace","value":[{"text":"ConversationEmergencyType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}