{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationemergencytype\/loadallmessagefirstloaduikit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationemergencytype\/loadallmessagefirstloaduikit"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@EaseChatUIKit@E@ConversationEmergencyType@ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit","symbolKind":"case","roleHeading":"Case","title":"ConversationEmergencyType.loadAllMessageFirstLoadUIKit","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAllMessageFirstLoadUIKit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/loadAllMessageFirstLoadUIKit"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadAllMessageFirstLoadUIKit"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType/loadAllMessageFirstLoadUIKit":{"title":"ConversationEmergencyType.loadAllMessageFirstLoadUIKit","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType\/loadAllMessageFirstLoadUIKit","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"loadAllMessageFirstLoadUIKit","kind":"identifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/conversationemergencytype\/loadallmessagefirstloaduikit","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType","abstract":[],"type":"topic","title":"ConversationEmergencyType","role":"symbol","url":"\/documentation\/easechatuikit\/conversationemergencytype","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ConversationEmergencyType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1loadAllMessageFirstLoadUIKit\/title"},{"value":[{"text":"ConversationEmergencyTypeLoadAllMessageFirstLoadUIKit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType~1loadAllMessageFirstLoadUIKit\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/title","op":"replace","value":"ConversationEmergencyType"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/fragments","op":"replace","value":[{"text":"ConversationEmergencyType","kind":"identifier"}]}]}]}