{"variants":[{"paths":["\/documentation\/easechatuikit\/translatetextview\/initwithframe:textcontainer:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"introducedAt":"7.0","beta":false},{"introducedAt":"7.0","beta":false,"deprecated":false,"name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"7.0","deprecated":false,"unavailable":false}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:textContainer:"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)TranslateTextView(im)initWithFrame:textContainer:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithFrame:textContainer:","kind":"identifier"}],"title":"initWithFrame:textContainer:","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TranslateTextView\/initWithFrame:textContainer:"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TranslateTextView"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithFrame:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"textContainer:"},{"kind":"text","text":"("},{"text":"NSTextContainer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSTextContainer"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"textContainer"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TranslateTextView/initWithFrame:textContainer:":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TranslateTextView\/initWithFrame:textContainer:","type":"topic","navigatorTitle":[{"text":"initWithFrame:textContainer:","kind":"identifier"}],"kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithFrame:textContainer:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/translatetextview\/initwithframe:textcontainer:","title":"initWithFrame:textContainer:"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/TranslateTextView":{"url":"\/documentation\/easechatuikit\/translatetextview","title":"TranslateTextView","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/TranslateTextView","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TranslateTextView","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TranslateTextView"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TranslateTextView\/title","op":"replace","value":"TranslateTextView"},{"op":"replace","value":[{"text":"TranslateTextView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TranslateTextView\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1TranslateTextView\/navigatorTitle","value":[{"kind":"identifier","text":"TranslateTextView"}],"op":"replace"}]}]}