{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITableViewDataSource.tableView(_:numberOfRowsInSection:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDataSource-Implementations"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"text":", ","kind":"text"},{"text":"numberOfRowsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","role":"symbol","title":"tableView(_:numberOfRowsInSection:)","externalID":"c:@CM@EaseChatUIKit@objc(cs)SearchConversationsController(im)tableView:numberOfRowsInSection:","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/tableView(_:numberOfRowsInSection:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/searchconversationscontroller\/tableview(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/searchconversationscontroller\/tableview(_:numberofrowsinsection:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier","text":"UITableView"},{"kind":"text","text":", "},{"text":"numberOfRowsInSection","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"section"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SearchConversationsController","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"SearchConversationsController","url":"\/documentation\/easechatuikit\/searchconversationscontroller","abstract":[],"navigatorTitle":[{"text":"SearchConversationsController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/UITableViewDataSource-Implementations":{"abstract":[],"title":"UITableViewDataSource Implementations","type":"topic","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDataSource-Implementations","role":"collectionGroup","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/uitableviewdatasource-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/tableView(_:numberOfRowsInSection:)":{"abstract":[],"title":"tableView(_:numberOfRowsInSection:)","type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/tableView(_:numberOfRowsInSection:)","role":"symbol","url":"\/documentation\/easechatuikit\/searchconversationscontroller\/tableview(_:numberofrowsinsection:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"tableView:numberOfRowsInSection:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"tableView:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":" "},{"text":"numberOfRowsInSection:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"section"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController\/title","value":"SearchConversationsController"},{"value":[{"text":"SearchConversationsController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1tableView(_:numberOfRowsInSection:)\/fragments"}]}]}