{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/UITableViewDelegate-Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController"]]},"metadata":{"role":"collectionGroup","title":"UITableViewDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/searchconversationscontroller\/uitableviewdelegate-implementations"]},{"paths":["\/documentation\/easechatuikit\/searchconversationscontroller\/uitableviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/tableView(_:didSelectRowAt:)"],"title":"Instance Methods","generated":true}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SearchConversationsController","kind":"identifier"}],"title":"SearchConversationsController","navigatorTitle":[{"text":"SearchConversationsController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/searchconversationscontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController","role":"symbol","abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/SearchConversationsController/tableView(_:didSelectRowAt:)":{"url":"\/documentation\/easechatuikit\/searchconversationscontroller\/tableview(_:didselectrowat:)","navigatorTitle":[{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/tableView(_:didSelectRowAt:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView"},{"kind":"text","text":", "},{"text":"didSelectRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":")","kind":"text"}],"title":"tableView(_:didSelectRowAt:)","type":"topic","kind":"symbol","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/SearchConversationsController\/tableView(_:didSelectRowAt:)"],"generated":true}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"SearchConversationsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController\/fragments","value":[{"text":"SearchConversationsController","kind":"identifier"}]},{"op":"replace","value":"tableView:didSelectRowAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1tableView(_:didSelectRowAt:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"tableView:didSelectRowAtIndexPath:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1SearchConversationsController~1tableView(_:didSelectRowAt:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}