{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle\/Equatable-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle\/!=(_:_:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"lhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/themestyle\/!=(_:_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"extendedModule":"Swift","title":"!=(_:_:)","modules":[{"name":"EaseChatUIKit","relatedModules":["Swift"]}],"role":"symbol","roleHeading":"Operator","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@EaseChatUIKit@E@ThemeStyle","symbolKind":"op"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle/Equatable-Implementations":{"title":"Equatable Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/themestyle\/equatable-implementations","role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle\/Equatable-Implementations","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"url":"\/documentation\/easechatuikit\/themestyle","title":"ThemeStyle","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","abstract":[{"type":"text","text":"Contain light and dark themes of the chat room UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","type":"reference","isActive":true},{"text":".Then call ","type":"text"},{"code":"Theme.switchTheme(style: .custom)","type":"codeVoice"},{"type":"text","text":" method"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThemeStyle","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle/!=(_:_:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/easechatuikit\/themestyle\/!=(_:_:)","role":"symbol","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/appearance","title":"Appearance","kind":"symbol","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/title","value":"ThemeStyle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/fragments","value":[{"kind":"identifier","text":"ThemeStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments","value":[{"kind":"identifier","text":"Appearance"}]}]}]}