{"variants":[{"paths":["\/documentation\/easechatuikit\/conversationemergencylistener\/onconversationsunreadcountupdate(unreadcount:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationemergencylistener\/onconversationsunreadcountupdate(unreadcount:)"]}],"sections":[],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onConversationsUnreadCountUpdate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"unreadCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener(im)onConversationsUnreadCountUpdateWithUnreadCount:","required":true,"navigatorTitle":[{"kind":"identifier","text":"onConversationsUnreadCountUpdateWithUnreadCount:"}],"title":"onConversationsUnreadCountUpdate(unreadCount:)","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener"]]},"abstract":[{"type":"text","text":"You’ll receive the result on some conversation last message update."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationsUnreadCountUpdate(unreadCount:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationsUnreadCountUpdate","kind":"identifier"},{"kind":"text","text":"("},{"text":"unreadCount","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Total unread count."}],"type":"paragraph"}],"name":"unreadCount"}],"kind":"parameters"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"url":"\/documentation\/easechatuikit\/conversationemergencylistener","kind":"symbol","role":"symbol","title":"ConversationEmergencyListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationEmergencyListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener/onConversationsUnreadCountUpdate(unreadCount:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onConversationsUnreadCountUpdate(unreadCount:)","kind":"symbol","title":"onConversationsUnreadCountUpdate(unreadCount:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onConversationsUnreadCountUpdate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"unreadCount"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"onConversationsUnreadCountUpdateWithUnreadCount:"}],"required":true,"role":"symbol","abstract":[{"type":"text","text":"You’ll receive the result on some conversation last message update."}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencylistener\/onconversationsunreadcountupdate(unreadcount:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"onConversationsUnreadCountUpdateWithUnreadCount:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onConversationsUnreadCountUpdateWithUnreadCount:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onConversationsUnreadCountUpdateWithUnreadCount:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":") "},{"text":"unreadCount","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"unreadCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Total unread count."}]}]}],"kind":"parameters"}},{"value":"ConversationEmergencyListener","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/title"},{"op":"replace","value":[{"text":"ConversationEmergencyListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/navigatorTitle","value":[{"text":"ConversationEmergencyListener","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onConversationsUnreadCountUpdate(unreadCount:)\/title","value":"onConversationsUnreadCountUpdateWithUnreadCount:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onConversationsUnreadCountUpdate(unreadCount:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"onConversationsUnreadCountUpdateWithUnreadCount:","kind":"identifier"}],"op":"replace"}]}]}