{"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationemergencylistener\/onresult(error:type:)"]},{"paths":["\/documentation\/easechatuikit\/conversationemergencylistener\/onresult(error:type:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"You’ll receive the result on conversation service request successful or failure.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(pl)ConversationEmergencyListener(im)onResultWithError:type:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"onResultWithError:type:"}],"symbolKind":"method","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onResult","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ConversationEmergencyType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ConversationEmergencyType"},{"text":")","kind":"text"}],"role":"symbol","title":"onResult(error:type:)"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onResult(error:type:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onResult"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ConversationEmergencyType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ConversationEmergencyType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":".Success "},{"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","isActive":true},{"type":"text","text":" is nil."}]}]},{"name":"type","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"}]}]}],"kind":"parameters"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener/onResult(error:type:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener\/onResult(error:type:)","kind":"symbol","title":"onResult(error:type:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onResult","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ConversationEmergencyType","text":"ConversationEmergencyType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"onResultWithError:type:","kind":"identifier"}],"required":true,"role":"symbol","abstract":[{"type":"text","text":"You’ll receive the result on conversation service request successful or failure."}],"type":"topic","url":"\/documentation\/easechatuikit\/conversationemergencylistener\/onresult(error:type:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"title":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chaterror"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyListener","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"url":"\/documentation\/easechatuikit\/conversationemergencylistener","kind":"symbol","role":"symbol","title":"ConversationEmergencyListener","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationEmergencyListener"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationEmergencyType":{"role":"symbol","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/conversationemergencytype","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType","navigatorTitle":[{"text":"ConversationEmergencyType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ConversationEmergencyType"}],"abstract":[],"title":"ConversationEmergencyType"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onResultWithError:type:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onResultWithError:type:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onResultWithError:"},{"kind":"text","text":"("},{"text":"EMError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"type:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationEmergencyType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ConversationEmergencyType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":".Success "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError"},{"type":"text","text":" is nil."}]}]},{"name":"type","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationEmergencyType"}],"type":"paragraph"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onResult(error:type:)\/title","value":"onResultWithError:type:"},{"value":[{"kind":"text","text":"- "},{"text":"onResultWithError:type:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener~1onResult(error:type:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/title","value":"ConversationEmergencyListener"},{"value":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"ConversationEmergencyListener"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyListener\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/title","value":"ConversationEmergencyType","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/fragments","value":[{"kind":"identifier","text":"ConversationEmergencyType"}]},{"value":[{"kind":"identifier","text":"ConversationEmergencyType"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationEmergencyType\/navigatorTitle","op":"replace"}]}]}