{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView\/initWithImage:","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","title":"initWithImage:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithImage:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)GradientEmojiView(im)initWithImage:"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithImage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/gradientemojiview\/initwithimage:"]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientEmojiView":{"role":"symbol","type":"topic","title":"GradientEmojiView","kind":"symbol","url":"\/documentation\/easechatuikit\/gradientemojiview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GradientEmojiView","kind":"identifier"}],"navigatorTitle":[{"text":"GradientEmojiView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientEmojiView/initWithImage:":{"role":"symbol","kind":"symbol","url":"\/documentation\/easechatuikit\/gradientemojiview\/initwithimage:","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView\/initWithImage:","abstract":[],"title":"initWithImage:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"GradientEmojiView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientEmojiView\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientEmojiView\/fragments","value":[{"text":"GradientEmojiView","kind":"identifier"}]},{"op":"replace","value":[{"text":"GradientEmojiView","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientEmojiView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}