{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView\/initWithImage:highlightedImage:"},"metadata":{"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)GradientEmojiView(im)initWithImage:highlightedImage:","platforms":[{"introducedAt":"3.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"unavailable":false,"introducedAt":"3.0","name":"iPadOS","beta":false,"deprecated":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"3.0"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:highlightedImage:"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","title":"initWithImage:highlightedImage:","fragments":[{"kind":"text","text":"- "},{"text":"initWithImage:highlightedImage:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/gradientemojiview\/initwithimage:highlightedimage:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithImage:"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"highlightedImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"highlightedImage","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientEmojiView":{"role":"symbol","type":"topic","title":"GradientEmojiView","kind":"symbol","url":"\/documentation\/easechatuikit\/gradientemojiview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"GradientEmojiView","kind":"identifier"}],"navigatorTitle":[{"text":"GradientEmojiView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GradientEmojiView/initWithImage:highlightedImage:":{"url":"\/documentation\/easechatuikit\/gradientemojiview\/initwithimage:highlightedimage:","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithImage:highlightedImage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GradientEmojiView\/initWithImage:highlightedImage:","title":"initWithImage:highlightedImage:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"text":"initWithImage:highlightedImage:","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"GradientEmojiView","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientEmojiView\/title","op":"replace"},{"value":[{"kind":"identifier","text":"GradientEmojiView"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientEmojiView\/fragments","op":"replace"},{"value":[{"text":"GradientEmojiView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GradientEmojiView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}