{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow\/draw(_:)"},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"draw","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"drawRect:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)MessageBubbleWithArrow(im)drawRect:","roleHeading":"Instance Method","title":"draw(_:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagebubblewitharrow\/draw(_:)"]},{"paths":["\/documentation\/easechatuikit\/messagebubblewitharrow\/draw(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleWithArrow/draw(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"draw"},{"text":"(","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow\/draw(_:)","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"role":"symbol","url":"\/documentation\/easechatuikit\/messagebubblewitharrow\/draw(_:)","title":"draw(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleWithArrow":{"title":"MessageBubbleWithArrow","abstract":[],"url":"\/documentation\/easechatuikit\/messagebubblewitharrow","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageBubbleWithArrow","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"MessageBubbleWithArrow","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"drawRect:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"drawRect:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"drawRect:"},{"kind":"text","text":"("},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"rect"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow~1draw(_:)\/title","value":"drawRect:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow~1draw(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"drawRect:"}]},{"op":"replace","value":"MessageBubbleWithArrow","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow\/fragments","value":[{"text":"MessageBubbleWithArrow","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}