{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow\/init(frame:forward:)"},"sections":[],"metadata":{"title":"init(frame:forward:)","role":"symbol","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"text":"forward","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)MessageBubbleWithArrow(im)initWithFrame:forward:","navigatorTitle":[{"text":"initWithFrame:forward:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forward"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","kind":"typeIdentifier","text":"BubbleTowards"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagebubblewitharrow\/init(frame:forward:)"]},{"paths":["\/documentation\/easechatuikit\/messagebubblewitharrow\/init(frame:forward:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/BubbleTowards":{"url":"\/documentation\/easechatuikit\/bubbletowards","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BubbleTowards"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"BubbleTowards","kind":"identifier"}],"title":"BubbleTowards","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleWithArrow":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow","url":"\/documentation\/easechatuikit\/messagebubblewitharrow","type":"topic","title":"MessageBubbleWithArrow","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageBubbleWithArrow"}],"navigatorTitle":[{"text":"MessageBubbleWithArrow","kind":"identifier"}],"role":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageBubbleWithArrow/init(frame:forward:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"forward","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BubbleTowards","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","title":"init(frame:forward:)","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithFrame:forward:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/messagebubblewitharrow\/init(frame:forward:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageBubbleWithArrow\/init(frame:forward:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithFrame:forward:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:forward:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"frame"},{"kind":"text","text":" "},{"kind":"identifier","text":"forward:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/BubbleTowards","preciseIdentifier":"c:@M@EaseChatUIKit@E@BubbleTowards","kind":"typeIdentifier","text":"BubbleTowards"},{"kind":"text","text":") "},{"kind":"internalParam","text":"forward"},{"text":";","kind":"text"}]}]},"op":"replace"},{"value":"BubbleTowards","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1BubbleTowards\/fragments","value":[{"text":"BubbleTowards","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow\/title","value":"MessageBubbleWithArrow"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow\/fragments","value":[{"text":"MessageBubbleWithArrow","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow~1init(frame:forward:)\/title","value":"initWithFrame:forward:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:forward:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageBubbleWithArrow~1init(frame:forward:)\/fragments"}]}]}