{"sections":[],"metadata":{"role":"symbol","title":"cellForRowAt(indexPath:)","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)GroupParticipantsController(im)cellForRowAtIndexPath:","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cellForRowAt","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"}],"extendedModule":"EaseChatUIKit","navigatorTitle":[{"text":"cellForRowAtIndexPath:","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cellForRowAt","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/cellForRowAt(indexPath:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/cellforrowat(indexpath:)"]},{"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/cellforrowat(indexpath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController/cellForRowAt(indexPath:)":{"url":"\/documentation\/easechatuikit\/groupparticipantscontroller\/cellforrowat(indexpath:)","title":"cellForRowAt(indexPath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cellForRowAt"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"UITableViewCell","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/cellForRowAt(indexPath:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"cellForRowAtIndexPath:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController":{"role":"symbol","title":"GroupParticipantsController","url":"\/documentation\/easechatuikit\/groupparticipantscontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController","navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsController"}],"abstract":[{"text":"A view controller that displays the participants of a group.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantsController"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"cellForRowAtIndexPath:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"cellForRowAtIndexPath:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"cellForRowAtIndexPath:"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"cellForRowAtIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1cellForRowAt(indexPath:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1cellForRowAt(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cellForRowAtIndexPath:"}]},{"value":"GroupParticipantsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/fragments","value":[{"kind":"identifier","text":"GroupParticipantsController"}]},{"value":[{"text":"GroupParticipantsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}