{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/chatgroup"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/chatgroup"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatGroup","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","kind":"typeIdentifier","text":"ChatGroup"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsController(py)chatGroup","navigatorTitle":[{"text":"chatGroup","kind":"identifier"}],"title":"chatGroup","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"chatGroup"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","text":"ChatGroup","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa"},{"kind":"text","text":" { get }"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/chatGroup"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatGroup":{"title":"ChatGroup","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatGroup","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/chatgroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatGroup","navigatorTitle":[{"text":"ChatGroup","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController":{"abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController","title":"GroupParticipantsController","role":"symbol","url":"\/documentation\/easechatuikit\/groupparticipantscontroller","navigatorTitle":[{"text":"GroupParticipantsController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantsController"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController/chatGroup":{"url":"\/documentation\/easechatuikit\/groupparticipantscontroller\/chatgroup","role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/chatGroup","navigatorTitle":[{"kind":"identifier","text":"chatGroup"}],"type":"topic","title":"chatGroup","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"chatGroup","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Groupa","text":"ChatGroup"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"chatGroup"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"chatGroup"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"EMGroup","preciseIdentifier":"c:objc(cs)EMGroup"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"chatGroup"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/title","value":"GroupParticipantsController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/fragments","value":[{"kind":"identifier","text":"GroupParticipantsController"}]},{"value":"chatGroup","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1chatGroup\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1chatGroup\/fragments","value":[{"text":"chatGroup","kind":"identifier"}],"op":"replace"}]}]}