{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/ignoreContacts()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreContacts"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"ignoreContacts","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ignoreContacts","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"title":"ignoreContacts()","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsController(im)ignoreContacts"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/ignorecontacts()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/ignorecontacts()"]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController/ignoreContacts()":{"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/ignoreContacts()","navigatorTitle":[{"text":"ignoreContacts","kind":"identifier"}],"abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"ignoreContacts","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"title":"ignoreContacts()","role":"symbol","url":"\/documentation\/easechatuikit\/groupparticipantscontroller\/ignorecontacts()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController":{"abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController","title":"GroupParticipantsController","role":"symbol","url":"\/documentation\/easechatuikit\/groupparticipantscontroller","navigatorTitle":[{"text":"GroupParticipantsController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantsController"}],"kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"ignoreContacts"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"ignoreContacts","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ignoreContacts","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"ignoreContacts","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1ignoreContacts()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1ignoreContacts()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"ignoreContacts","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/title","op":"replace","value":"GroupParticipantsController"},{"value":[{"text":"GroupParticipantsController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/fragments"}]}]}