{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupParticipantsOperation","text":"GroupParticipantsOperation"},{"kind":"text","text":" { get }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/operation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/operation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/operation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupParticipantsOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupParticipantsOperation"}],"title":"operation","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@EaseChatUIKit@objc(cs)GroupParticipantsController(py)operation","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"operation"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController/operation":{"role":"symbol","title":"operation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupParticipantsOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupParticipantsOperation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/operation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operation"}],"url":"\/documentation\/easechatuikit\/groupparticipantscontroller\/operation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsOperation":{"role":"symbol","title":"GroupParticipantsOperation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantsOperation"}],"abstract":[{"type":"text","text":"An enumeration representing the possible operations for group participants."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsOperation"}],"url":"\/documentation\/easechatuikit\/groupparticipantsoperation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController":{"role":"symbol","title":"GroupParticipantsController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"GroupParticipantsController"}],"abstract":[{"type":"text","text":"A view controller that displays the participants of a group."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsController"}],"url":"\/documentation\/easechatuikit\/groupparticipantscontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"operation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"operation"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsOperation","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupParticipantsOperation","text":"GroupParticipantsOperation"},{"kind":"text","text":" "},{"kind":"identifier","text":"operation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1operation\/title","value":"operation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1operation\/fragments","value":[{"kind":"identifier","text":"operation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsOperation\/title","value":"GroupParticipantsOperation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsOperation\/fragments","value":[{"kind":"identifier","text":"GroupParticipantsOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/title","value":"GroupParticipantsController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/fragments","value":[{"kind":"identifier","text":"GroupParticipantsController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}