{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"metadata":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/uiscrollviewdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/groupparticipantscontroller\/uiscrollviewdelegate-implementations"]}],"sections":[],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/scrollViewDidEndDragging(_:willDecelerate:)"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController":{"role":"symbol","title":"GroupParticipantsController","url":"\/documentation\/easechatuikit\/groupparticipantscontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController","navigatorTitle":[{"kind":"identifier","text":"GroupParticipantsController"}],"abstract":[{"text":"A view controller that displays the participants of a group.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupParticipantsController"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController/scrollViewDidEndDragging(_:willDecelerate:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDragging","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willDecelerate"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"scrollViewDidEndDragging(_:willDecelerate:)","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/scrollViewDidEndDragging(_:willDecelerate:)","type":"topic","url":"\/documentation\/easechatuikit\/groupparticipantscontroller\/scrollviewdidenddragging(_:willdecelerate:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupParticipantsController/scrollViewDidEndDecelerating(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"title":"scrollViewDidEndDecelerating(_:)","navigatorTitle":[{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/scrollViewDidEndDecelerating(_:)","type":"topic","url":"\/documentation\/easechatuikit\/groupparticipantscontroller\/scrollviewdidenddecelerating(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupParticipantsController\/scrollViewDidEndDragging(_:willDecelerate:)"],"generated":true,"title":"Instance Methods"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/title","value":"GroupParticipantsController"},{"value":[{"kind":"identifier","text":"GroupParticipantsController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/fragments"},{"value":[{"text":"GroupParticipantsController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1scrollViewDidEndDragging(_:willDecelerate:)\/title","value":"scrollViewDidEndDragging:willDecelerate:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDragging:willDecelerate:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments"},{"value":"scrollViewDidEndDecelerating:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1scrollViewDidEndDecelerating(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupParticipantsController~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}]}]}]}