{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/init(frame:viewControllers:indicators:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"frame"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewControllers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"], ","kind":"text"},{"text":"indicators","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"title":"init(frame:viewControllers:indicators:)","roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@EaseChatUIKit@objc(cs)PageContainer(im)initWithFrame:viewControllers:indicators:","navigatorTitle":[{"text":"initWithFrame:viewControllers:indicators:","kind":"identifier"}],"role":"symbol"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewControllers"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"indicators"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"frame","content":[{"inlineContent":[{"type":"text","text":"The frame for the "},{"type":"codeVoice","code":"PageContainer"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"viewControllers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of "},{"code":"UIViewController","type":"codeVoice"},{"type":"text","text":"s to be displayed in the "},{"type":"codeVoice","code":"PageContainer"},{"type":"text","text":"."}]}]},{"content":[{"inlineContent":[{"text":"An array of strings representing the indicators for the ","type":"text"},{"code":"PageContainer","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}],"name":"indicators"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer"]]},"abstract":[{"type":"text","text":"A convenience initializer for creating a "},{"type":"codeVoice","code":"PageContainer"},{"text":" with a given frame, view controllers, and indicators.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/init(frame:viewcontrollers:indicators:)"]},{"paths":["\/documentation\/easechatuikit\/pagecontainer\/init(frame:viewcontrollers:indicators:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer":{"abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"url":"\/documentation\/easechatuikit\/pagecontainer","title":"PageContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PageContainer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/init(frame:viewControllers:indicators:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"frame","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":"], ","kind":"text"},{"text":"indicators","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"A convenience initializer for creating a "},{"type":"codeVoice","code":"PageContainer"},{"text":" with a given frame, view controllers, and indicators.","type":"text"}],"url":"\/documentation\/easechatuikit\/pagecontainer\/init(frame:viewcontrollers:indicators:)","role":"symbol","title":"init(frame:viewControllers:indicators:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/init(frame:viewControllers:indicators:)","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:viewControllers:indicators:"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithFrame:viewControllers:indicators:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFrame:viewControllers:indicators:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithFrame:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"text":") ","kind":"text"},{"text":"frame","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewControllers:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIViewController *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewControllers"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicators:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indicators"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"frame","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The frame for the "},{"type":"codeVoice","code":"PageContainer"},{"text":".","type":"text"}]}]},{"name":"viewControllers","content":[{"inlineContent":[{"type":"text","text":"An array of "},{"type":"codeVoice","code":"UIViewController"},{"text":"s to be displayed in the ","type":"text"},{"type":"codeVoice","code":"PageContainer"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"indicators","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An array of strings representing the indicators for the "},{"code":"PageContainer","type":"codeVoice"},{"text":".","type":"text"}]}]}]}},{"op":"add","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"A new "},{"type":"codeVoice","code":"PageContainer"},{"text":" instance.","type":"text"}]}],"kind":"content"}},{"value":"PageContainer","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/navigatorTitle","value":[{"kind":"identifier","text":"PageContainer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1init(frame:viewControllers:indicators:)\/title","value":"initWithFrame:viewControllers:indicators:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1init(frame:viewControllers:indicators:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithFrame:viewControllers:indicators:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}