{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations"]]},"kind":"symbol","metadata":{"title":"pageViewController(_:willTransitionTo:)","navigatorTitle":[{"text":"pageViewController:willTransitionToViewControllers:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)PageContainer(im)pageViewController:willTransitionToViewControllers:","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageViewController","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIPageViewController","kind":"typeIdentifier","text":"UIPageViewController"},{"kind":"text","text":", "},{"text":"willTransitionTo","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"])","kind":"text"}],"role":"symbol"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIPageViewControllerDelegate.pageViewController(_:willTransitionTo:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"pageViewController","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"kind":"text","text":", "},{"text":"willTransitionTo","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"pendingViewControllers"},{"kind":"text","text":": ["},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"])"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/pageViewController(_:willTransitionTo:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)","abstract":[],"role":"symbol","type":"topic","title":"pageViewController(_:willTransitionTo:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willTransitionTo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"pageViewController:willTransitionToViewControllers:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","role":"symbol","abstract":[{"text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"PageContainer","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pagecontainer","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"}],"title":"PageContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/UIPageViewControllerDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations","role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/easechatuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations","type":"topic","title":"UIPageViewControllerDelegate Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"pageViewController:willTransitionToViewControllers:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"pageViewController:willTransitionToViewControllers:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"pageViewController:"},{"kind":"text","text":"("},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":" *) ","kind":"text"},{"text":"pageViewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"willTransitionToViewControllers:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIViewController *>"},{"text":" *) ","kind":"text"},{"text":"pendingViewControllers","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/title","value":"pageViewController:willTransitionToViewControllers:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"pageViewController:willTransitionToViewControllers:","kind":"identifier"}]},{"value":"PageContainer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/fragments","op":"replace","value":[{"kind":"identifier","text":"PageContainer"}]}]}]}