{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UIPageViewControllerDataSource.pageViewController(_:viewControllerAfter:)"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageViewController"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"viewControllerAfter","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":") -> ","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"metadata":{"title":"pageViewController(_:viewControllerAfter:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"text":"viewControllerAfter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"?"}],"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","extendedModule":"EaseChatUIKit","roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)PageContainer(im)pageViewController:viewControllerAfterViewController:","role":"symbol","navigatorTitle":[{"text":"pageViewController:viewControllerAfterViewController:","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:viewControllerAfter:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerafter:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerafter:)"]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"type":"topic","abstract":[{"text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","kind":"symbol","url":"\/documentation\/easechatuikit\/pagecontainer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"title":"PageContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/UIPageViewControllerDataSource-Implementations":{"title":"UIPageViewControllerDataSource Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","url":"\/documentation\/easechatuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/pageViewController(_:viewControllerAfter:)":{"title":"pageViewController(_:viewControllerAfter:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"viewControllerAfter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"pageViewController:viewControllerAfterViewController:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:viewControllerAfter:)","url":"\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerafter:)","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"pageViewController:viewControllerAfterViewController:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:viewControllerAfterViewController:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pageViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"pageViewController"},{"text":" ","kind":"text"},{"text":"viewControllerAfterViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"PageContainer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/fragments","value":[{"text":"PageContainer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:viewControllerAfter:)\/title","op":"replace","value":"pageViewController:viewControllerAfterViewController:"},{"value":[{"text":"- ","kind":"text"},{"text":"pageViewController:viewControllerAfterViewController:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:viewControllerAfter:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}