{"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIPageViewControllerDataSource.pageViewController(_:viewControllerBefore:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)PageContainer(im)pageViewController:viewControllerBeforeViewController:","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"pageViewController:viewControllerBeforeViewController:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pageViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewControllerBefore"},{"text":": ","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"title":"pageViewController(_:viewControllerBefore:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations"]]},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"pageViewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIPageViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"text":"viewControllerBefore","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/pageViewController(_:viewControllerBefore:)":{"role":"symbol","navigatorTitle":[{"text":"pageViewController:viewControllerBeforeViewController:","kind":"identifier"}],"type":"topic","title":"pageViewController(_:viewControllerBefore:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:viewControllerBefore:)","url":"\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:viewcontrollerbefore:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"viewControllerBefore"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/UIPageViewControllerDataSource-Implementations":{"title":"UIPageViewControllerDataSource Implementations","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDataSource-Implementations","url":"\/documentation\/easechatuikit\/pagecontainer\/uipageviewcontrollerdatasource-implementations","kind":"article","abstract":[],"role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PageContainer","kind":"identifier"}],"type":"topic","abstract":[{"text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","kind":"symbol","url":"\/documentation\/easechatuikit\/pagecontainer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}],"title":"PageContainer"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"pageViewController:viewControllerBeforeViewController:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pageViewController:viewControllerBeforeViewController:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"},{"text":" *) ","kind":"text"},{"text":"pageViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pageViewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"viewControllerBeforeViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/title","value":"pageViewController:viewControllerBeforeViewController:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:viewControllerBefore:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pageViewController:viewControllerBeforeViewController:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/title","value":"PageContainer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/fragments","value":[{"text":"PageContainer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}