{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"pageViewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController"},{"text":", ","kind":"text"},{"text":"didFinishAnimating","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"finished","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"previousViewControllers"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"transitionCompleted"},{"kind":"text","text":" "},{"text":"completed","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)PageContainer(im)pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:","extendedModule":"EaseChatUIKit","title":"pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pageViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController"},{"text":", ","kind":"text"},{"text":"didFinishAnimating","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"previousViewControllers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"transitionCompleted"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"}],"modules":[{"name":"EaseChatUIKit"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIPageViewControllerDelegate.pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:didfinishanimating:previousviewcontrollers:transitioncompleted:)"]},{"paths":["\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:didfinishanimating:previousviewcontrollers:transitioncompleted:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/UIPageViewControllerDelegate-Implementations":{"abstract":[],"title":"UIPageViewControllerDelegate Implementations","kind":"article","url":"\/documentation\/easechatuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations","type":"topic","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer":{"abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"url":"\/documentation\/easechatuikit\/pagecontainer","title":"PageContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PageContainer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)":{"abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:didfinishanimating:previousviewcontrollers:transitioncompleted:)","navigatorTitle":[{"text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"kind":"text","text":"("},{"text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishAnimating"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"previousViewControllers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"kind":"text","text":"], "},{"text":"transitionCompleted","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","title":"pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","type":"topic","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"pageViewController:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"pageViewController"},{"text":" ","kind":"text"},{"text":"didFinishAnimating:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"finished","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"previousViewControllers:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<UIViewController *>"},{"text":" *) ","kind":"text"},{"text":"previousViewControllers","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transitionCompleted:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"completed","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","value":"PageContainer","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/title"},{"value":[{"kind":"identifier","text":"PageContainer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/navigatorTitle","value":[{"text":"PageContainer","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)\/title","value":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"},{"value":[{"kind":"text","text":"- "},{"text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}