{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/switchTheme(style:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/easechatuikit\/pagecontainer\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/pagecontainer\/themeswitchprotocol-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/ThemeSwitchProtocol-Implementations","interfaceLanguage":"swift"},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"ThemeSwitchProtocol Implementations"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer":{"abstract":[{"type":"text","text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar."}],"url":"\/documentation\/easechatuikit\/pagecontainer","title":"PageContainer","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PageContainer","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PageContainer"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/switchTheme(style:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/switchTheme(style:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"switchThemeWithStyle:"}],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"title":"switchTheme(style:)","type":"topic","url":"\/documentation\/easechatuikit\/pagecontainer\/switchtheme(style:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/switchTheme(style:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"PageContainer","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/fragments","value":[{"kind":"identifier","text":"PageContainer"}]},{"value":[{"kind":"identifier","text":"PageContainer"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1switchTheme(style:)\/title","value":"switchThemeWithStyle:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1switchTheme(style:)\/fragments"}]}]}