{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"UIPageViewControllerDelegate Implementations"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/UIPageViewControllerDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)"],"generated":true,"title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/pagecontainer\/uipageviewcontrollerdelegate-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer","role":"symbol","abstract":[{"text":"A container view controller that manages a UIPageViewController and a PageContainerTitleBar.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"PageContainer","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/pagecontainer","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PageContainer"}],"title":"PageContainer"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/pageViewController(_:willTransitionTo:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:willtransitionto:)","abstract":[],"role":"symbol","type":"topic","title":"pageViewController(_:willTransitionTo:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pageViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIPageViewController","text":"UIPageViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"willTransitionTo"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController"},{"kind":"text","text":"])"}],"navigatorTitle":[{"text":"pageViewController:willTransitionToViewControllers:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PageContainer/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"}],"url":"\/documentation\/easechatuikit\/pagecontainer\/pageviewcontroller(_:didfinishanimating:previousviewcontrollers:transitioncompleted:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"pageViewController"},{"text":"(","kind":"text"},{"text":"UIPageViewController","preciseIdentifier":"c:objc(cs)UIPageViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didFinishAnimating","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previousViewControllers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"transitionCompleted","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"title":"pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PageContainer\/pageViewController(_:willTransitionTo:)"],"generated":true,"title":"Instance Methods"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/title","value":"PageContainer","op":"replace"},{"op":"replace","value":[{"text":"PageContainer","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer\/fragments"},{"value":"pageViewController:willTransitionToViewControllers:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:willTransitionTo:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"pageViewController:willTransitionToViewControllers:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)\/title","op":"replace","value":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PageContainer~1pageViewController(_:didFinishAnimating:previousViewControllers:transitionCompleted:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"pageViewController:didFinishAnimating:previousViewControllers:transitionCompleted:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}