{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participants"},"metadata":{"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","title":"participants","navigatorTitle":[{"kind":"identifier","text":"participants"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatThreadParticipantsController(py)participants","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"participants"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol"},{"text":"]","kind":"text"}]},"abstract":[{"type":"text","text":"The array of participants in the group."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"participants"},{"text":": [","kind":"text"},{"text":"EaseProfileProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":"] { get }"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/participants"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/participants"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController":{"abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller","navigatorTitle":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"role":"symbol","title":"ChatThreadParticipantsController","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/participants":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/participants","abstract":[{"type":"text","text":"The array of participants in the group."}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"participants","kind":"identifier"},{"kind":"text","text":": ["},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":"]"}],"navigatorTitle":[{"text":"participants","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/participants","kind":"symbol","title":"participants","role":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EaseProfileProtocol"}],"role":"symbol","abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"type":"topic","title":"EaseProfileProtocol","url":"\/documentation\/easechatuikit\/easeprofileprotocol","navigatorTitle":[{"text":"EaseProfileProtocol","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"participants","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"participants"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<EaseProfileProtocol>>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"participants","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"value":"ChatThreadParticipantsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/fragments","value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"op":"replace"},{"value":"participants","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1participants\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1participants\/fragments","value":[{"text":"participants","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title","value":"EaseProfileProtocol"},{"op":"replace","value":[{"text":"EaseProfileProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}