{"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UIScrollViewDelegate-Implementations"},"metadata":{"role":"collectionGroup","roleHeading":"API Collection","title":"UIScrollViewDelegate Implementations","modules":[{"name":"EaseChatUIKit"}]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/scrollViewDidEndDecelerating(_:)"],"title":"Instance Methods","generated":true}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"article","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController","title":"ChatThreadParticipantsController","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/scrollViewDidEndDecelerating(_:)":{"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/scrollviewdidenddecelerating(_:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/scrollViewDidEndDecelerating(_:)","title":"scrollViewDidEndDecelerating(_:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/scrollViewDidEndDecelerating(_:)"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/title","value":"ChatThreadParticipantsController"},{"value":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1scrollViewDidEndDecelerating(_:)\/fragments","op":"replace"}]}]}