{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/uitableviewdatasource-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController"]]},"kind":"article","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"UITableViewDataSource Implementations","roleHeading":"API Collection"},"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/tableView(_:numberOfRowsInSection:)"]}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/tableView(_:numberOfRowsInSection:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"numberOfRowsInSection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/tableView(_:numberOfRowsInSection:)","title":"tableView(_:numberOfRowsInSection:)","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/tableview(_:numberofrowsinsection:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadParticipantsController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ChatThreadParticipantsController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController","title":"ChatThreadParticipantsController","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadParticipantsController/tableView(_:cellForRowAt:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/tableView(_:cellForRowAt:)","url":"\/documentation\/easechatuikit\/chatthreadparticipantscontroller\/tableview(_:cellforrowat:)","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"kind":"symbol","title":"tableView(_:cellForRowAt:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cellForRowAt"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadParticipantsController\/tableView(_:numberOfRowsInSection:)"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1tableView(_:numberOfRowsInSection:)\/title","value":"tableView:numberOfRowsInSection:"},{"value":[{"text":"- ","kind":"text"},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1tableView(_:numberOfRowsInSection:)\/fragments","op":"replace"},{"value":"ChatThreadParticipantsController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController\/fragments","value":[{"kind":"identifier","text":"ChatThreadParticipantsController"}],"op":"replace"},{"value":"tableView:cellForRowAtIndexPath:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1tableView(_:cellForRowAt:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadParticipantsController~1tableView(_:cellForRowAt:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}]}]}]}