{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(bindWithDriver:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver","text":"IContactListDriver"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"driver","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object of conform"},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/bind(driver:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/bind(driver:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/bind(driver:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Bind UI driver and service"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IContactListDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver"},{"kind":"text","text":")"}],"title":"bind(driver:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel(im)bindWithDriver:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"bindWithDriver:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"role":"symbol","title":"ContactViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactViewModel"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactViewModel"}],"url":"\/documentation\/easechatuikit\/contactviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver":{"role":"symbol","title":"IContactListDriver","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IContactListDriver"}],"abstract":[{"type":"text","text":"A driver protocol of "},{"type":"codeVoice","code":"ContactList"},{"type":"text","text":"."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IContactListDriver"}],"url":"\/documentation\/easechatuikit\/icontactlistdriver"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/bind(driver:)":{"role":"symbol","title":"bind(driver:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"bind"},{"kind":"text","text":"("},{"kind":"externalParam","text":"driver"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IContactListDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Bind UI driver and service"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/bind(driver:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bindWithDriver:"}],"url":"\/documentation\/easechatuikit\/contactviewmodel\/bind(driver:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"bindWithDriver:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindWithDriver:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"bindWithDriver:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<IContactListDriver>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)IContactListDriver"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"driver"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"kind":"identifier","text":"ContactViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/title","value":"IContactListDriver"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/fragments","value":[{"kind":"identifier","text":"IContactListDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1bind(driver:)\/title","value":"bindWithDriver:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1bind(driver:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"bindWithDriver:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}