{"metadata":{"roleHeading":"API Collection","title":"ContactListActionEventsDelegate Implementations","modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/ContactListActionEventsDelegate-Implementations","interfaceLanguage":"swift"},"kind":"article","sections":[],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/didSelected(indexPath:profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListScroll(indexPath:)"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/contactlistactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/contactlistactioneventsdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/onContactListOccurErrorWhenFetchServer()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListOccurErrorWhenFetchServer()","url":"\/documentation\/easechatuikit\/contactviewmodel\/oncontactlistoccurerrorwhenfetchserver()","abstract":[{"text":"When fetch conversations list occur error.Empty view retry button on clicked.The method will call.","type":"text"}],"navigatorTitle":[{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onContactListOccurErrorWhenFetchServer","kind":"identifier"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","title":"onContactListOccurErrorWhenFetchServer()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/didSelected(indexPath:profile:)":{"navigatorTitle":[{"text":"didSelectedWithIndexPath:profile:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/didSelected(indexPath:profile:)","kind":"symbol","role":"symbol","title":"didSelected(indexPath:profile:)","url":"\/documentation\/easechatuikit\/contactviewmodel\/didselected(indexpath:profile:)","type":"topic","abstract":[{"type":"text","text":"The method’ll called on contact list cell clicked."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didSelected","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"EaseProfileProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","url":"\/documentation\/easechatuikit\/contactviewmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewModel","kind":"identifier"}],"title":"ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/onContactListScroll(indexPath:)":{"navigatorTitle":[{"text":"onContactListScrollWithIndexPath:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListScroll(indexPath:)","kind":"symbol","role":"symbol","title":"onContactListScroll(indexPath:)","url":"\/documentation\/easechatuikit\/contactviewmodel\/oncontactlistscroll(indexpath:)","type":"topic","abstract":[{"type":"text","text":"When contact list scrolled."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactListScroll"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/onContactListEndScrollNeededDisplayInfos(ids:)":{"navigatorTitle":[{"text":"onContactListEndScrollNeededDisplayInfosWithIds:","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","kind":"symbol","role":"symbol","title":"onContactListEndScrollNeededDisplayInfos(ids:)","url":"\/documentation\/easechatuikit\/contactviewmodel\/oncontactlistendscrollneededdisplayinfos(ids:)","type":"topic","abstract":[{"type":"text","text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onContactListEndScrollNeededDisplayInfos","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ids"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/didSelected(indexPath:profile:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListOccurErrorWhenFetchServer()","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListScroll(indexPath:)"]}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListOccurErrorWhenFetchServer()\/title","value":"onContactListOccurErrorWhenFetchServer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListOccurErrorWhenFetchServer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListOccurErrorWhenFetchServer"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1didSelected(indexPath:profile:)\/title","value":"didSelectedWithIndexPath:profile:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1didSelected(indexPath:profile:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"didSelectedWithIndexPath:profile:"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel","op":"replace"},{"value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListScroll(indexPath:)\/title","value":"onContactListScrollWithIndexPath:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onContactListScrollWithIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListScroll(indexPath:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListEndScrollNeededDisplayInfos(ids:)\/title","value":"onContactListEndScrollNeededDisplayInfosWithIds:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListEndScrollNeededDisplayInfos(ids:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}