{"kind":"article","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/ContactEventsResponse-Implementations","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidAgree(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidDecline(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidReceive(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendshipDidAddSuccessful(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendshipDidRemove(by:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactviewmodel\/contacteventsresponse-implementations"]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/contacteventsresponse-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"EaseChatUIKit"}],"title":"ContactEventsResponse Implementations"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/friendRequestDidReceive(by:)":{"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidReceiveBy:"}],"title":"friendRequestDidReceive(by:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"friendRequestDidReceive","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[{"text":"Received friend request","type":"text"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidReceive(by:)","kind":"symbol","url":"\/documentation\/easechatuikit\/contactviewmodel\/friendrequestdidreceive(by:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/friendRequestDidAgree(by:)":{"abstract":[{"text":"The friend request was accepted by the other party","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidAgreeBy:"}],"url":"\/documentation\/easechatuikit\/contactviewmodel\/friendrequestdidagree(by:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidAgree(by:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"friendRequestDidAgree","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"title":"friendRequestDidAgree(by:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/friendRequestDidDecline(by:)":{"title":"friendRequestDidDecline(by:)","abstract":[{"type":"text","text":"Friend request was rejected by the other party"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidDecline(by:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"friendRequestDidDecline","kind":"identifier"},{"kind":"text","text":"("},{"text":"by","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"friendRequestDidDeclineBy:"}],"url":"\/documentation\/easechatuikit\/contactviewmodel\/friendrequestdiddecline(by:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"kind":"symbol","url":"\/documentation\/easechatuikit\/contactviewmodel","abstract":[{"type":"text","text":"Bind service and driver"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","title":"ContactViewModel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/friendshipDidRemove(by:)":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendshipDidRemove(by:)","role":"symbol","title":"friendshipDidRemove(by:)","navigatorTitle":[{"kind":"identifier","text":"friendshipDidRemoveBy:"}],"url":"\/documentation\/easechatuikit\/contactviewmodel\/friendshipdidremove(by:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"friendshipDidRemove","kind":"identifier"},{"kind":"text","text":"("},{"text":"by","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"abstract":[{"text":"The friend relationship was removed by the other party","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/friendshipDidAddSuccessful(by:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"friendshipDidAddSuccessful"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"by"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendshipDidAddSuccessful(by:)","kind":"symbol","abstract":[{"text":"Friend relationship added successfully","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"friendshipDidAddSuccessfulBy:"}],"role":"symbol","url":"\/documentation\/easechatuikit\/contactviewmodel\/friendshipdidaddsuccessful(by:)","title":"friendshipDidAddSuccessful(by:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidAgree(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidDecline(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendRequestDidReceive(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendshipDidAddSuccessful(by:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/friendshipDidRemove(by:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendRequestDidReceive(by:)\/title","op":"replace","value":"friendRequestDidReceiveBy:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidReceiveBy:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendRequestDidReceive(by:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendRequestDidAgree(by:)\/title","value":"friendRequestDidAgreeBy:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendRequestDidAgree(by:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"friendRequestDidAgreeBy:","kind":"identifier"}],"op":"replace"},{"value":"friendRequestDidDeclineBy:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendRequestDidDecline(by:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"friendRequestDidDeclineBy:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendRequestDidDecline(by:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendshipDidRemove(by:)\/title","value":"friendshipDidRemoveBy:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"friendshipDidRemoveBy:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendshipDidRemove(by:)\/fragments"},{"value":"friendshipDidAddSuccessfulBy:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendshipDidAddSuccessful(by:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"friendshipDidAddSuccessfulBy:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1friendshipDidAddSuccessful(by:)\/fragments"}]}]}