{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"driver","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver","text":"IContactListDriver"},{"kind":"text","text":"? { get }"}]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/driver"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/driver","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property","title":"driver","role":"symbol","roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit16ContactViewModelC6driverAA18IContactListDriver_pSgvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"driver","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IContactListDriver","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/IContactListDriver":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/IContactListDriver","abstract":[{"text":"A driver protocol of ","type":"text"},{"code":"ContactList","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","title":"IContactListDriver","role":"symbol","url":"\/documentation\/easechatuikit\/icontactlistdriver","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"IContactListDriver","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"IContactListDriver"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/driver":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/driver","abstract":[],"type":"topic","title":"driver","role":"symbol","url":"\/documentation\/easechatuikit\/contactviewmodel\/driver","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"driver","kind":"identifier"},{"kind":"text","text":": "},{"text":"IContactListDriver","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)IContactListDriver"},{"kind":"text","text":"?"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"kind":"symbol","url":"\/documentation\/easechatuikit\/contactviewmodel","abstract":[{"type":"text","text":"Bind service and driver"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactViewModel","kind":"identifier"}],"navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","title":"ContactViewModel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"IContactListDriver","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1IContactListDriver\/fragments","value":[{"kind":"identifier","text":"IContactListDriver"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace"}]}]}