{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"loadAllContacts","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel(im)loadAllContacts","roleHeading":"Instance Method","role":"symbol","title":"loadAllContacts()","symbolKind":"method","navigatorTitle":[{"text":"loadAllContacts","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/loadAllContacts()"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"loadAllContacts","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactviewmodel\/loadallcontacts()"]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/loadallcontacts()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","url":"\/documentation\/easechatuikit\/contactviewmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewModel","kind":"identifier"}],"title":"ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/loadAllContacts()":{"url":"\/documentation\/easechatuikit\/contactviewmodel\/loadallcontacts()","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/loadAllContacts()","title":"loadAllContacts()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadAllContacts","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"loadAllContacts","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"loadAllContacts"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"loadAllContacts"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"loadAllContacts","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","op":"replace","value":"ContactViewModel"},{"value":[{"text":"ContactViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1loadAllContacts()\/title","value":"loadAllContacts"},{"value":[{"kind":"text","text":"- "},{"text":"loadAllContacts","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1loadAllContacts()\/fragments"}]}]}