{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/MultiDeviceListener-Implementations","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactviewmodel\/multidevicelistener-implementations"]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/multidevicelistener-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"article","metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection","role":"collectionGroup","title":"MultiDeviceListener Implementations"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactsEventDidChanged(event:userId:extension:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/onContactsEventDidChanged(event:userId:extension:)":{"abstract":[{"type":"text","text":"When a event of contact changes on other devices"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactsEventDidChanged"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extension"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactsEventDidChanged(event:userId:extension:)","url":"\/documentation\/easechatuikit\/contactviewmodel\/oncontactseventdidchanged(event:userid:extension:)","navigatorTitle":[{"text":"onContactsEventDidChangedWithEvent:userId:extension:","kind":"identifier"}],"title":"onContactsEventDidChanged(event:userId:extension:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactViewModel"}],"type":"topic","abstract":[{"text":"Bind service and driver","type":"text"}],"url":"\/documentation\/easechatuikit\/contactviewmodel","role":"symbol","title":"ContactViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactsEventDidChanged(event:userId:extension:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactsEventDidChanged(event:userId:extension:)\/title","op":"replace","value":"onContactsEventDidChangedWithEvent:userId:extension:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactsEventDidChanged(event:userId:extension:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onContactsEventDidChangedWithEvent:userId:extension:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"value":[{"text":"ContactViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/navigatorTitle","value":[{"text":"ContactViewModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}