{"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/oncontactseventdidchanged(event:userid:extension:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/oncontactseventdidchanged(event:userid:extension:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"When a event of contact changes on other devices"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onContactsEventDidChanged"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa","text":"MultiDeviceEvent","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent"},{"text":", ","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"extension","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"info"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent"}],"type":"paragraph"}],"name":"event"},{"name":"userId","content":[{"inlineContent":[{"type":"text","text":"The id of the user."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"Extension info.","type":"text"}],"type":"paragraph"}],"name":"info"}],"kind":"parameters"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactsEventDidChanged(event:userId:extension:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactsEventDidChanged"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MultiDeviceEvent","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"extension"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactViewModel(im)onContactsEventDidChangedWithEvent:userId:extension:","navigatorTitle":[{"kind":"identifier","text":"onContactsEventDidChangedWithEvent:userId:extension:"}],"extendedModule":"EaseChatUIKit","title":"onContactsEventDidChanged(event:userId:extension:)","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/MultiDeviceListener-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactViewModel"}],"type":"topic","abstract":[{"text":"Bind service and driver","type":"text"}],"url":"\/documentation\/easechatuikit\/contactviewmodel","role":"symbol","title":"ContactViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/onContactsEventDidChanged(event:userId:extension:)":{"abstract":[{"type":"text","text":"When a event of contact changes on other devices"}],"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactsEventDidChanged"},{"text":"(","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MultiDeviceEvent","preciseIdentifier":"s:13EaseChatUIKit16MultiDeviceEventa"},{"kind":"text","text":", "},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"extension"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactsEventDidChanged(event:userId:extension:)","url":"\/documentation\/easechatuikit\/contactviewmodel\/oncontactseventdidchanged(event:userid:extension:)","navigatorTitle":[{"text":"onContactsEventDidChangedWithEvent:userId:extension:","kind":"identifier"}],"title":"onContactsEventDidChanged(event:userId:extension:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceEvent":{"title":"MultiDeviceEvent","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiDeviceEvent","kind":"identifier"}],"navigatorTitle":[{"text":"MultiDeviceEvent","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/multideviceevent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceEvent"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/MultiDeviceListener-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/MultiDeviceListener-Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/easechatuikit\/contactviewmodel\/multidevicelistener-implementations","kind":"article","abstract":[],"title":"MultiDeviceListener Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onContactsEventDidChangedWithEvent:userId:extension:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onContactsEventDidChangedWithEvent:userId:extension:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onContactsEventDidChangedWithEvent:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EMMultiDevicesEvent","preciseIdentifier":"c:@E@EMMultiDevicesEvent"},{"text":") ","kind":"text"},{"text":"event","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userId:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"userId"},{"kind":"text","text":" "},{"text":"extension:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"info","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel","op":"replace"},{"value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/navigatorTitle","value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace"},{"value":"onContactsEventDidChangedWithEvent:userId:extension:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactsEventDidChanged(event:userId:extension:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactsEventDidChanged(event:userId:extension:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onContactsEventDidChangedWithEvent:userId:extension:"}]}]}]}