{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"ids","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"[conversationId]"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/oncontactlistendscrollneededdisplayinfos(ids:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/oncontactlistendscrollneededdisplayinfos(ids:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}],"role":"symbol","title":"onContactListEndScrollNeededDisplayInfos(ids:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactViewModel(im)onContactListEndScrollNeededDisplayInfosWithIds:","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/ContactListActionEventsDelegate-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"role":"symbol","title":"ContactViewModel","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactViewModel"}],"abstract":[{"type":"text","text":"Bind service and driver"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactViewModel"}],"url":"\/documentation\/easechatuikit\/contactviewmodel"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/onContactListEndScrollNeededDisplayInfos(ids:)":{"role":"symbol","title":"onContactListEndScrollNeededDisplayInfos(ids:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfos"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ids"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"abstract":[{"type":"text","text":"The method will called on conversation list end scroll,then it will ask you for the session nickname and avatar data and then refresh it."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/onContactListEndScrollNeededDisplayInfos(ids:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}],"url":"\/documentation\/easechatuikit\/contactviewmodel\/oncontactlistendscrollneededdisplayinfos(ids:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/ContactListActionEventsDelegate-Implementations":{"role":"collectionGroup","title":"ContactListActionEventsDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/ContactListActionEventsDelegate-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/contactviewmodel\/contactlistactioneventsdelegate-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onContactListEndScrollNeededDisplayInfosWithIds:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ids"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"kind":"identifier","text":"ContactViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListEndScrollNeededDisplayInfos(ids:)\/title","value":"onContactListEndScrollNeededDisplayInfosWithIds:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1onContactListEndScrollNeededDisplayInfos(ids:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onContactListEndScrollNeededDisplayInfosWithIds:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}