{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"processFriendshipDidRemoveWithUserId:","kind":"identifier"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactViewModel(im)processFriendshipDidRemoveWithUserId:","extendedModule":"EaseChatUIKit","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"processFriendshipDidRemove(userId:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processFriendshipDidRemove","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"userId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}]},"variants":[{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/processfriendshipdidremove(userid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/processfriendshipdidremove(userid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/processFriendshipDidRemove(userId:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processFriendshipDidRemove"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/processFriendshipDidRemove(userId:)":{"navigatorTitle":[{"text":"processFriendshipDidRemoveWithUserId:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/contactviewmodel\/processfriendshipdidremove(userid:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/processFriendshipDidRemove(userId:)","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processFriendshipDidRemove"},{"text":"(","kind":"text"},{"text":"userId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"title":"processFriendshipDidRemove(userId:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","url":"\/documentation\/easechatuikit\/contactviewmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewModel","kind":"identifier"}],"title":"ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"processFriendshipDidRemoveWithUserId:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"processFriendshipDidRemoveWithUserId:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"processFriendshipDidRemoveWithUserId:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"userId","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1processFriendshipDidRemove(userId:)\/title","value":"processFriendshipDidRemoveWithUserId:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"processFriendshipDidRemoveWithUserId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1processFriendshipDidRemove(userId:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"text":"ContactViewModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}