{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/registerEventsListener(_:)"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"registerEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ContactEmergencyListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener"},{"text":")","kind":"text"}],"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"title":"registerEventsListener(_:)","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel(im)registerEventsListener:","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"registerEventsListener:","kind":"identifier"}]},"abstract":[{"text":"Register to monitor when certain emergencies occur","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactviewmodel\/registereventslistener(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactviewmodel\/registereventslistener(_:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"registerEventsListener"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"listener"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener","text":"ContactEmergencyListener","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener","type":"reference","isActive":true}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyListener":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/contactemergencylistener","role":"symbol","navigatorTitle":[{"text":"ContactEmergencyListener","kind":"identifier"}],"title":"ContactEmergencyListener","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactEmergencyListener","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"abstract":[{"text":"Bind service and driver","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","type":"topic","url":"\/documentation\/easechatuikit\/contactviewmodel","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ContactViewModel","kind":"identifier"}],"title":"ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/registerEventsListener(_:)":{"url":"\/documentation\/easechatuikit\/contactviewmodel\/registereventslistener(_:)","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Register to monitor when certain emergencies occur"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/registerEventsListener(_:)","title":"registerEventsListener(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"registerEventsListener","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ContactEmergencyListener","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"registerEventsListener:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"registerEventsListener:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"registerEventsListener:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"registerEventsListener:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id<ContactEmergencyListener>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ContactEmergencyListener"},{"kind":"text","text":") "},{"kind":"internalParam","text":"listener"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/title","value":"ContactEmergencyListener"},{"op":"replace","value":[{"text":"ContactEmergencyListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","value":"ContactViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments","value":[{"kind":"identifier","text":"ContactViewModel"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1registerEventsListener(_:)\/title","op":"replace","value":"registerEventsListener:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1registerEventsListener(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"registerEventsListener:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}