{"metadata":{"navigatorTitle":[{"text":"viewContact","kind":"identifier"}],"role":"symbol","title":"viewContact","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactViewModel(py)viewContact","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewContact"},{"kind":"text","text":": (("},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"ChatUserProfileProtocol"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")?"}],"symbolKind":"property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactviewmodel\/viewcontact"]},{"paths":["\/documentation\/easechatuikit\/contactviewmodel\/viewcontact"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/viewContact","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewContact"},{"text":": ((","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","preciseIdentifier":"s:s4Voida","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactViewModel"}],"type":"topic","abstract":[{"text":"Bind service and driver","type":"text"}],"url":"\/documentation\/easechatuikit\/contactviewmodel","role":"symbol","title":"ContactViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel","navigatorTitle":[{"text":"ContactViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatUserProfileProtocol":{"abstract":[{"text":"Profile of the ChatUIKit display needed.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatuserprofileprotocol","role":"symbol","title":"ChatUserProfileProtocol","type":"topic","kind":"symbol","navigatorTitle":[{"text":"ChatUserProfileProtocol","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatUserProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatUserProfileProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactViewModel/viewContact":{"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewContact"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactViewModel\/viewContact","title":"viewContact","url":"\/documentation\/easechatuikit\/contactviewmodel\/viewcontact","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"viewContact","kind":"identifier"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"ChatUserProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"viewContact","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"viewContact","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":" (^"},{"kind":"identifier","text":"viewContact"},{"kind":"text","text":")("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ChatUserProfileProtocol","kind":"typeIdentifier","text":"id<ChatUserProfileProtocol>"},{"text":" ","kind":"text"},{"kind":"internalParam","text":""},{"text":");","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/title","op":"replace","value":"ContactViewModel"},{"value":[{"kind":"identifier","text":"ContactViewModel"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/fragments"},{"op":"replace","value":[{"text":"ContactViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel\/navigatorTitle"},{"value":"ChatUserProfileProtocol","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/fragments"},{"value":[{"kind":"identifier","text":"ChatUserProfileProtocol"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatUserProfileProtocol\/navigatorTitle"},{"op":"replace","value":"viewContact","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1viewContact\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactViewModel~1viewContact\/fragments","op":"replace","value":[{"kind":"identifier","text":"viewContact"}]}]}]}