{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar\/switchTheme(style:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/easechatnavigationbar\/switchtheme(style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/easechatnavigationbar\/switchtheme(style:)"]}],"abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"metadata":{"extendedModule":"EaseChatUIKit","title":"switchTheme(style:)","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)EaseChatNavigationBar(im)switchThemeWithStyle:","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar\/ThemeSwitchProtocol-Implementations"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier","text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle"}]}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}],"url":"\/documentation\/easechatuikit\/themestyle","title":"ThemeStyle","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","abstract":[{"type":"text","text":"Contain light and dark themes of the chat room UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","type":"reference","isActive":true},{"text":".Then call ","type":"text"},{"code":"Theme.switchTheme(style: .custom)","type":"codeVoice"},{"type":"text","text":" method"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ThemeStyle","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"role":"symbol","navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/appearance","title":"Appearance","kind":"symbol","abstract":[{"type":"text","text":"An object containing visual configurations for the whole application."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar":{"kind":"symbol","type":"topic","title":"EaseChatNavigationBar","abstract":[{"text":"Navigation  bar of the EaseChatUIKit.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar","url":"\/documentation\/easechatuikit\/easechatnavigationbar","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatNavigationBar","kind":"identifier"}],"navigatorTitle":[{"text":"EaseChatNavigationBar","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar/switchTheme(style:)":{"title":"switchTheme(style:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar\/switchTheme(style:)","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/easechatnavigationbar\/switchtheme(style:)","abstract":[{"text":"When some view Implement the protocol method,you can use ","type":"text"},{"code":"Theme.switchTheme(style: .dark)","type":"codeVoice"},{"type":"text","text":" to switch theme."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBar/ThemeSwitchProtocol-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBar\/ThemeSwitchProtocol-Implementations","role":"collectionGroup","title":"ThemeSwitchProtocol Implementations","url":"\/documentation\/easechatuikit\/easechatnavigationbar\/themeswitchprotocol-implementations","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"switchThemeWithStyle:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"switchThemeWithStyle:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier","text":"ThemeStyle","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"ThemeStyle","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/fragments","value":[{"kind":"identifier","text":"ThemeStyle"}]},{"value":"Appearance","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title"},{"op":"replace","value":[{"text":"Appearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/title","value":"EaseChatNavigationBar"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar\/fragments","value":[{"text":"EaseChatNavigationBar","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar~1switchTheme(style:)\/title","value":"switchThemeWithStyle:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBar~1switchTheme(style:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"switchThemeWithStyle:"}]}]}]}