{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/requestMessages()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestMessages"},{"text":"()","kind":"text"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/requestmessages()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/requestmessages()"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatHistoryViewController(im)requestMessages","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"requestMessages","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestMessages","kind":"identifier"},{"text":"()","kind":"text"}],"title":"requestMessages()"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chathistoryviewcontroller","abstract":[],"title":"ChatHistoryViewController","navigatorTitle":[{"kind":"identifier","text":"ChatHistoryViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatHistoryViewController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController/requestMessages()":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/requestMessages()","abstract":[],"url":"\/documentation\/easechatuikit\/chathistoryviewcontroller\/requestmessages()","navigatorTitle":[{"text":"requestMessages","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestMessages"},{"kind":"text","text":"()"}],"kind":"symbol","type":"topic","title":"requestMessages()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"requestMessages","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestMessages"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"requestMessages"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ChatHistoryViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/fragments","value":[{"text":"ChatHistoryViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"requestMessages","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1requestMessages()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestMessages"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1requestMessages()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}