{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/rightItemsAction(indexPath:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightItemsAction","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"languages":["swift"]}]}],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"title":"rightItemsAction(indexPath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rightItemsAction","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier","text":"IndexPath"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"rightItemsActionWithIndexPath:"}],"role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(cs)ChatHistoryViewController(im)rightItemsActionWithIndexPath:","symbolKind":"method"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/rightitemsaction(indexpath:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/rightitemsaction(indexpath:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController":{"url":"\/documentation\/easechatuikit\/chathistoryviewcontroller","role":"symbol","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatHistoryViewController"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatHistoryViewController"}],"title":"ChatHistoryViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController/rightItemsAction(indexPath:)":{"navigatorTitle":[{"text":"rightItemsActionWithIndexPath:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/chathistoryviewcontroller\/rightitemsaction(indexpath:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/rightItemsAction(indexPath:)","type":"topic","role":"symbol","title":"rightItemsAction(indexPath:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rightItemsAction"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"text":"?)","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"rightItemsActionWithIndexPath:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightItemsActionWithIndexPath:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rightItemsActionWithIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/title","value":"ChatHistoryViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/fragments","value":[{"kind":"identifier","text":"ChatHistoryViewController"}]},{"value":[{"kind":"identifier","text":"ChatHistoryViewController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1rightItemsAction(indexPath:)\/title","op":"replace","value":"rightItemsActionWithIndexPath:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1rightItemsAction(indexPath:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rightItemsActionWithIndexPath:"}]}]}]}