{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/tableView(_:numberOfRowsInSection:)"],"generated":true}],"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/UITableViewDataSource-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/uitableviewdatasource-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/uitableviewdatasource-implementations"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController"]]},"metadata":{"title":"UITableViewDataSource Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}]},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController/tableView(_:cellForRowAt:)":{"abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"tableView:cellForRowAtIndexPath:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/tableView(_:cellForRowAt:)","title":"tableView(_:cellForRowAt:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"text":"cellForRowAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/easechatuikit\/chathistoryviewcontroller\/tableview(_:cellforrowat:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController/tableView(_:numberOfRowsInSection:)":{"navigatorTitle":[{"kind":"identifier","text":"tableView:numberOfRowsInSection:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/tableView(_:numberOfRowsInSection:)","kind":"symbol","role":"symbol","title":"tableView(_:numberOfRowsInSection:)","url":"\/documentation\/easechatuikit\/chathistoryviewcontroller\/tableview(_:numberofrowsinsection:)","type":"topic","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"numberOfRowsInSection","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chathistoryviewcontroller","abstract":[],"title":"ChatHistoryViewController","navigatorTitle":[{"kind":"identifier","text":"ChatHistoryViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatHistoryViewController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/tableView(_:cellForRowAt:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/tableView(_:numberOfRowsInSection:)"],"generated":true}],"path":"\/topicSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1tableView(_:cellForRowAt:)\/title","op":"replace","value":"tableView:cellForRowAtIndexPath:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"tableView:cellForRowAtIndexPath:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1tableView(_:cellForRowAt:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1tableView(_:numberOfRowsInSection:)\/title","op":"replace","value":"tableView:numberOfRowsInSection:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1tableView(_:numberOfRowsInSection:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"tableView:numberOfRowsInSection:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/title","value":"ChatHistoryViewController","op":"replace"},{"op":"replace","value":[{"text":"ChatHistoryViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/fragments"}]}]}