{"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatHistoryViewController(im)viewDidLoad","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","title":"viewDidLoad()","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"roleHeading":"Instance Method"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"},{"kind":"text","text":"()"}]}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/viewDidLoad()","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/viewdidload()"]},{"paths":["\/documentation\/easechatuikit\/chathistoryviewcontroller\/viewdidload()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chathistoryviewcontroller","abstract":[],"title":"ChatHistoryViewController","navigatorTitle":[{"kind":"identifier","text":"ChatHistoryViewController"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatHistoryViewController","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatHistoryViewController/viewDidLoad()":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/easechatuikit\/chathistoryviewcontroller\/viewdidload()","abstract":[],"title":"viewDidLoad()","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatHistoryViewController\/viewDidLoad()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewDidLoad","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/title","op":"replace","value":"ChatHistoryViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController\/fragments","value":[{"kind":"identifier","text":"ChatHistoryViewController"}]},{"value":"viewDidLoad","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1viewDidLoad()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatHistoryViewController~1viewDidLoad()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}