{"variants":[{"paths":["\/documentation\/easechatuikit\/popmenucollectionviewcell\/refresh(item:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/popmenucollectionviewcell\/refresh(item:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell\/refresh(item:)"},"metadata":{"title":"refresh(item:)","modules":[{"name":"EaseChatUIKit"}],"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)PopMenuCollectionViewCell(im)refreshWithItem:","navigatorTitle":[{"text":"refreshWithItem:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refresh"},{"kind":"text","text":"("},{"kind":"externalParam","text":"item"},{"text":": ","kind":"text"},{"text":"ActionSheetItemProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"refresh"},{"text":"(","kind":"text"},{"text":"item","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PopMenuCollectionViewCell":{"navigatorTitle":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PopMenuCollectionViewCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell","title":"PopMenuCollectionViewCell","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/popmenucollectionviewcell","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ActionSheetItemProtocol":{"abstract":[{"text":"A protocol that defines properties and methods for an action sheet item.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/easechatuikit\/actionsheetitemprotocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ActionSheetItemProtocol","title":"ActionSheetItemProtocol","navigatorTitle":[{"text":"ActionSheetItemProtocol","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ActionSheetItemProtocol"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PopMenuCollectionViewCell/refresh(item:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell\/refresh(item:)","kind":"symbol","title":"refresh(item:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"refresh","kind":"identifier"},{"text":"(","kind":"text"},{"text":"item","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol","text":"ActionSheetItemProtocol","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"refreshWithItem:","kind":"identifier"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/popmenucollectionviewcell\/refresh(item:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"refreshWithItem:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"refreshWithItem:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"refreshWithItem:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<ActionSheetItemProtocol>","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)ActionSheetItemProtocol"},{"kind":"text","text":") "},{"text":"item","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell\/title","value":"PopMenuCollectionViewCell","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell\/fragments","value":[{"text":"PopMenuCollectionViewCell","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell\/navigatorTitle"},{"value":"ActionSheetItemProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"ActionSheetItemProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ActionSheetItemProtocol\/navigatorTitle","value":[{"text":"ActionSheetItemProtocol","kind":"identifier"}]},{"value":"refreshWithItem:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell~1refresh(item:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell~1refresh(item:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"refreshWithItem:"}]}]}]}