{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/popmenucollectionviewcell\/switchtheme(style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/popmenucollectionviewcell\/switchtheme(style:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)PopMenuCollectionViewCell(im)switchThemeWithStyle:","roleHeading":"Instance Method","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"title":"switchTheme(style:)","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"switchTheme","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle"},{"kind":"text","text":")"}],"symbolKind":"method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"switchTheme"},{"text":"(","kind":"text"},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ThemeStyle","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","isActive":true,"type":"reference"}]}]}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell\/ThemeSwitchProtocol-Implementations"]]},"sections":[],"abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"text":" to switch theme.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell\/switchTheme(style:)","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PopMenuCollectionViewCell/switchTheme(style:)":{"kind":"symbol","type":"topic","title":"switchTheme(style:)","abstract":[{"type":"text","text":"When some view Implement the protocol method,you can use "},{"type":"codeVoice","code":"Theme.switchTheme(style: .dark)"},{"type":"text","text":" to switch theme."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell\/switchTheme(style:)","role":"symbol","navigatorTitle":[{"text":"switchThemeWithStyle:","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/popmenucollectionviewcell\/switchtheme(style:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"switchTheme","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"ThemeStyle","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ThemeStyle":{"type":"topic","abstract":[{"type":"text","text":"Contain light and dark themes of the ease chat UIKit.If you want to switch custom theme,you’ll modify primary&secondary&error&neutral&neutralSpecial hues properties in "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","type":"reference","isActive":true},{"type":"text","text":".Then call "},{"type":"codeVoice","code":"Theme.switchTheme(style: .custom)"},{"text":" method","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ThemeStyle"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","title":"ThemeStyle","kind":"symbol","url":"\/documentation\/easechatuikit\/themestyle","navigatorTitle":[{"kind":"identifier","text":"ThemeStyle"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PopMenuCollectionViewCell/ThemeSwitchProtocol-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell\/ThemeSwitchProtocol-Implementations","title":"ThemeSwitchProtocol Implementations","kind":"article","url":"\/documentation\/easechatuikit\/popmenucollectionviewcell\/themeswitchprotocol-implementations","type":"topic","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PopMenuCollectionViewCell":{"navigatorTitle":[{"kind":"identifier","text":"PopMenuCollectionViewCell"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PopMenuCollectionViewCell","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PopMenuCollectionViewCell","title":"PopMenuCollectionViewCell","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/popmenucollectionviewcell","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/Appearance":{"type":"topic","abstract":[{"text":"An object containing visual configurations for the whole application.","type":"text"}],"title":"Appearance","kind":"symbol","navigatorTitle":[{"text":"Appearance","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Appearance","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/Appearance","url":"\/documentation\/easechatuikit\/appearance"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"switchThemeWithStyle:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"switchThemeWithStyle:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"switchThemeWithStyle:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ThemeStyle","text":"ThemeStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ThemeStyle"},{"text":") ","kind":"text"},{"text":"style","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell~1switchTheme(style:)\/title","op":"replace","value":"switchThemeWithStyle:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"switchThemeWithStyle:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell~1switchTheme(style:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/title","value":"ThemeStyle"},{"op":"replace","value":[{"text":"ThemeStyle","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/fragments"},{"value":[{"text":"ThemeStyle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ThemeStyle\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell\/title","value":"PopMenuCollectionViewCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell\/fragments","value":[{"text":"PopMenuCollectionViewCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PopMenuCollectionViewCell\/navigatorTitle","op":"replace","value":[{"text":"PopMenuCollectionViewCell","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/title","value":"Appearance","op":"replace"},{"op":"replace","value":[{"text":"Appearance","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Appearance"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1Appearance\/navigatorTitle"}]}]}