{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/controllerstack\/init"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ControllerStack"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ControllerStack\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@EaseChatUIKit@objc(cs)ControllerStack(im)init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ControllerStack":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ControllerStack"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ControllerStack","title":"ControllerStack","type":"topic","navigatorTitle":[{"text":"ControllerStack","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/controllerstack","kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ControllerStack/init":{"abstract":[],"url":"\/documentation\/easechatuikit\/controllerstack\/init","title":"init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ControllerStack\/init"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ControllerStack\/title","value":"ControllerStack","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ControllerStack\/fragments","value":[{"text":"ControllerStack","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ControllerStack\/navigatorTitle","value":[{"text":"ControllerStack","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}