{"kind":"article","metadata":{"roleHeading":"API Collection","modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup","title":"ChatResponseListener Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations"},"topicSections":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messagesAlreadyRead(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageStatusDidChanged(message:status:error:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/chatresponselistener-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/chatresponselistener-implementations"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageDidRecalled(recallInfo:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidRecalled(recallInfo:)","title":"onMessageDidRecalled(recallInfo:)","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidrecalled(recallinfo:)","role":"symbol","abstract":[{"type":"text","text":"When message recalled."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recallInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","text":"RecallInfo"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageAttachmentStatusChanged(message:error:)":{"role":"symbol","title":"onMessageAttachmentStatusChanged(message:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageAttachmentStatusChanged"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"onMessageAttachmentStatusChangedWithMessage:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"When status of message attachment changed."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageAttachmentStatusChanged(message:error:)","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessageattachmentstatuschanged(message:error:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messagesAlreadyRead(conversationId:)":{"title":"messagesAlreadyRead(conversationId:)","role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagesalreadyread(conversationid:)","abstract":[{"type":"text","text":"Update messages read state on received channel ack."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messagesAlreadyRead"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"conversationId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"messagesAlreadyReadWithConversationId:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messagesAlreadyRead(conversationId:)","kind":"symbol","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageReactionChanged(changes:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageReactionChangedWithChanges:"}],"role":"symbol","type":"topic","title":"onMessageReactionChanged(changes:)","abstract":[{"text":"When reaction of message changed.","type":"text"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagereactionchanged(changes:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageReactionChanged"},{"text":"(","kind":"text"},{"text":"changes","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MessageReactionChange","preciseIdentifier":"s:13EaseChatUIKit21MessageReactionChangea"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageReactionChanged(changes:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageDidEdited(message:)":{"abstract":[{"type":"text","text":"When message edited."}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidedited(message:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidEdited"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidEdited(message:)","title":"onMessageDidEdited(message:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageDidEditedWithMessage:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageDidReceived(message:)":{"navigatorTitle":[{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidReceived(message:)","kind":"symbol","role":"symbol","title":"onMessageDidReceived(message:)","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidreceived(message:)","type":"topic","abstract":[{"text":"When message received.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageDidReceived"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"abstract":[],"title":"ChatThreadViewModel","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageStatusDidChanged(message:status:error:)":{"abstract":[{"text":"When status of message changed.","type":"text"}],"title":"onMessageStatusDidChanged(message:status:error:)","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagestatusdidchanged(message:status:error:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageStatusDidChanged(message:status:error:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageStatusDidChanged","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"text":"status","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ChatMessageStatus","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"onMessageStatusDidChangedWithMessage:status:error:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messagesAlreadyRead(conversationId:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageAttachmentStatusChanged(message:error:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidEdited(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidRecalled(recallInfo:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidReceived(message:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageReactionChanged(changes:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageStatusDidChanged(message:status:error:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":"onMessageDidRecalledWithRecallInfo:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidRecalled(recallInfo:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidRecalled(recallInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageDidRecalledWithRecallInfo:"}]},{"op":"replace","value":"onMessageAttachmentStatusChangedWithMessage:error:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageAttachmentStatusChanged(message:error:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageAttachmentStatusChangedWithMessage:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageAttachmentStatusChanged(message:error:)\/fragments"},{"value":"messagesAlreadyReadWithConversationId:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messagesAlreadyRead(conversationId:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messagesAlreadyReadWithConversationId:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messagesAlreadyRead(conversationId:)\/fragments"},{"op":"replace","value":"onMessageReactionChangedWithChanges:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageReactionChanged(changes:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onMessageReactionChangedWithChanges:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageReactionChanged(changes:)\/fragments"},{"value":"onMessageDidEditedWithMessage:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidEdited(message:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"onMessageDidEditedWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidEdited(message:)\/fragments"},{"value":"onMessageDidReceivedWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidReceived(message:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidReceived(message:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","op":"replace","value":"ChatThreadViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","op":"replace","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageStatusDidChanged(message:status:error:)\/title","op":"replace","value":"onMessageStatusDidChangedWithMessage:status:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"onMessageStatusDidChangedWithMessage:status:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageStatusDidChanged(message:status:error:)\/fragments"}]}]}