{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionClicked(reaction:entity:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)messageReactionClickedWithReaction:entity:","roleHeading":"Instance Method","title":"messageReactionClicked(reaction:entity:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"messageReactionClickedWithReaction:entity:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messageReactionClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","text":"MessageReaction"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageReactionClicked"},{"text":"(","kind":"text"},{"text":"reaction","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","text":"MessageReaction"},{"text":"?, ","kind":"text"},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messagereactionclicked(reaction:entity:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messagereactionclicked(reaction:entity:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageReactionClicked(reaction:entity:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagereactionclicked(reaction:entity:)","type":"topic","title":"messageReactionClicked(reaction:entity:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messageReactionClicked","kind":"identifier"},{"kind":"text","text":"("},{"text":"reaction","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit15MessageReactiona","text":"MessageReaction"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"entity"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","text":"MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageReactionClicked(reaction:entity:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"messageReactionClickedWithReaction:entity:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"abstract":[],"title":"ChatThreadViewModel","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageReaction":{"url":"\/documentation\/easechatuikit\/messagereaction","title":"MessageReaction","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageReaction","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageReaction"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageReaction"}],"abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/messageentity","title":"MessageEntity","navigatorTitle":[{"text":"MessageEntity","kind":"identifier"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"messageReactionClickedWithReaction:entity:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageReactionClickedWithReaction:entity:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageReactionClickedWithReaction:"},{"text":"(","kind":"text"},{"text":"EMMessageReaction","preciseIdentifier":"c:objc(cs)EMMessageReaction","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"reaction"},{"text":" ","kind":"text"},{"kind":"identifier","text":"entity:"},{"kind":"text","text":"("},{"text":"MessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"entity"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageReactionClicked(reaction:entity:)\/title","value":"messageReactionClickedWithReaction:entity:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageReactionClickedWithReaction:entity:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageReactionClicked(reaction:entity:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","op":"replace","value":"ChatThreadViewModel"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]},{"op":"replace","value":"MessageEntity","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title"},{"op":"replace","value":[{"kind":"identifier","text":"MessageEntity"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}