{"kind":"symbol","metadata":{"roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)messageAvatarLongPressedWithProfile:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"messageAvatarLongPressedWithProfile:"}],"role":"symbol","title":"messageAvatarLongPressed(profile:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageAvatarLongPressed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":")","kind":"text"}],"symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageAvatarLongPressed"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messageavatarlongpressed(profile:)"]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messageavatarlongpressed(profile:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAvatarLongPressed(profile:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"abstract":[],"title":"ChatThreadViewModel","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EaseProfileProtocol"}],"role":"symbol","abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"type":"topic","title":"EaseProfileProtocol","url":"\/documentation\/easechatuikit\/easeprofileprotocol","navigatorTitle":[{"text":"EaseProfileProtocol","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageAvatarLongPressed(profile:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messageavatarlongpressed(profile:)","type":"topic","title":"messageAvatarLongPressed(profile:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageAvatarLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageAvatarLongPressed(profile:)","role":"symbol","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"messageAvatarLongPressedWithProfile:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id<EaseProfileProtocol>","kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"profile"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title","value":"EaseProfileProtocol"},{"value":[{"text":"EaseProfileProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageAvatarLongPressed(profile:)\/title","value":"messageAvatarLongPressedWithProfile:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"messageAvatarLongPressedWithProfile:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageAvatarLongPressed(profile:)\/fragments"}]}]}