{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"messageStatusChanged"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus","text":"ChatMessageStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?)"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"message","content":[{"inlineContent":[{"type":"text","text":"The chat message whose status has changed."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The new status of the chat message."}],"type":"paragraph"}],"name":"status"},{"content":[{"inlineContent":[{"text":"An optional error associated with the status change.","type":"text"}],"type":"paragraph"}],"name":"error"}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messagestatuschanged(message:status:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messagestatuschanged(message:status:error:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"extendedModule":"EaseChatUIKit","navigatorTitle":[{"kind":"identifier","text":"messageStatusChangedWithMessage:status:error:"}],"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"messageStatusChanged","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"kind":"text","text":", "},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatMessageStatus","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?)"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)messageStatusChangedWithMessage:status:error:","roleHeading":"Instance Method","modules":[{"name":"EaseChatUIKit"}],"title":"messageStatusChanged(message:status:error:)"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageStatusChanged(message:status:error:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Notifies the message list view model when the status of a chat message has changed."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"title":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chaterror"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageStatusChanged(message:status:error:)":{"navigatorTitle":[{"text":"messageStatusChangedWithMessage:status:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"messageStatusChanged","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"status"},{"text":": ","kind":"text"},{"text":"ChatMessageStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageStatusChanged(message:status:error:)","kind":"symbol","title":"messageStatusChanged(message:status:error:)","abstract":[{"type":"text","text":"Notifies the message list view model when the status of a chat message has changed."}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagestatuschanged(message:status:error:)","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","abstract":[],"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessageStatus":{"abstract":[{"type":"text","text":"The status of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},{"text":".","type":"text"}],"url":"\/documentation\/easechatuikit\/chatmessagestatus","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessageStatus"}],"title":"ChatMessageStatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessageStatus","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"role":"symbol","abstract":[],"title":"ChatThreadViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"messageStatusChangedWithMessage:status:error:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"messageStatusChangedWithMessage:status:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"messageStatusChangedWithMessage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMChatMessage","kind":"typeIdentifier","text":"EMChatMessage"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessageStatus","preciseIdentifier":"c:@M@EaseChatUIKit@E@ChatMessageStatus","text":"ChatMessageStatus"},{"text":") ","kind":"text"},{"text":"status","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EMError","preciseIdentifier":"c:objc(cs)EMError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The chat message whose status has changed."}],"type":"paragraph"}],"name":"message"},{"name":"status","content":[{"inlineContent":[{"text":"The new status of the chat message.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"An optional error associated with the status change.","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"value":"messageStatusChangedWithMessage:status:error:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageStatusChanged(message:status:error:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageStatusChanged(message:status:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageStatusChangedWithMessage:status:error:"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus\/title","op":"replace","value":"ChatMessageStatus"},{"op":"replace","value":[{"text":"ChatMessageStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatMessageStatus\/navigatorTitle","value":[{"text":"ChatMessageStatus","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel","op":"replace"},{"value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/navigatorTitle","op":"replace","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]}]}]}