{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidReceived(message:)"},"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)messageDidReceivedWithMessage:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"messageDidReceived(message:)","navigatorTitle":[{"kind":"identifier","text":"messageDidReceivedWithMessage:"}],"extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"messageDidReceived"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}]},"kind":"symbol","sections":[],"abstract":[{"text":"Handles the received message and performs necessary actions based on the message type.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"messageDidReceived","kind":"identifier"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"message","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The received ChatMessage object."}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messagedidreceived(message:)"]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/messagedidreceived(message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/messageDidReceived(message:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"messageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/messageDidReceived(message:)","title":"messageDidReceived(message:)","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagedidreceived(message:)","role":"symbol","abstract":[{"text":"Handles the received message and performs necessary actions based on the message type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"messageDidReceivedWithMessage:"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","title":"ChatMessage","abstract":[],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewModel"}],"title":"ChatThreadViewModel","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","kind":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"messageDidReceivedWithMessage:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"messageDidReceivedWithMessage:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"messageDidReceivedWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMChatMessage","text":"EMChatMessage"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidReceived(message:)\/title","value":"messageDidReceivedWithMessage:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"messageDidReceivedWithMessage:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1messageDidReceived(message:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}