{"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"onGroupChatThreadEventOccurWithType:event:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupChatThreadEventOccur","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","text":"GroupChatThreadEventType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"GroupChatThreadEvent","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa"},{"kind":"text","text":")"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)onGroupChatThreadEventOccurWithType:event:","modules":[{"name":"EaseChatUIKit"}],"title":"onGroupChatThreadEventOccur(type:event:)","extendedModule":"EaseChatUIKit"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onGroupChatThreadEventOccur(type:event:)"},"kind":"symbol","abstract":[{"type":"text","text":"Some event occur on group chat thread."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/GroupChatThreadEventListener-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onGroupChatThreadEventOccur","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"GroupChatThreadEventType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","kind":"typeIdentifier","text":"GroupChatThreadEvent"},{"kind":"text","text":")"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","isActive":true,"type":"reference"}]}],"name":"type"},{"name":"event","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"type":"reference","isActive":true,"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent"}]}]}],"kind":"parameters"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/ongroupchatthreadeventoccur(type:event:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/ongroupchatthreadeventoccur(type:event:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onGroupChatThreadEventOccur(type:event:)":{"role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/ongroupchatthreadeventoccur(type:event:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onGroupChatThreadEventOccur(type:event:)","type":"topic","title":"onGroupChatThreadEventOccur(type:event:)","abstract":[{"text":"Some event occur on group chat thread.","type":"text"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onGroupChatThreadEventOccur","kind":"identifier"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"GroupChatThreadEventType","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType"},{"text":", ","kind":"text"},{"text":"event","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit05GroupB11ThreadEventa","text":"GroupChatThreadEvent"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onGroupChatThreadEventOccurWithType:event:"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEvent":{"url":"\/documentation\/easechatuikit\/groupchatthreadevent","title":"GroupChatThreadEvent","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEvent","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupChatThreadEvent"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEvent"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/GroupChatThreadEventType":{"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/groupchatthreadeventtype","title":"GroupChatThreadEventType","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"GroupChatThreadEventType"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"GroupChatThreadEventType"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"role":"symbol","abstract":[],"title":"ChatThreadViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/GroupChatThreadEventListener-Implementations":{"type":"topic","abstract":[],"title":"GroupChatThreadEventListener Implementations","role":"collectionGroup","kind":"article","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/groupchatthreadeventlistener-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/GroupChatThreadEventListener-Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onGroupChatThreadEventOccurWithType:event:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onGroupChatThreadEventOccurWithType:event:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"onGroupChatThreadEventOccurWithType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/GroupChatThreadEventType","preciseIdentifier":"c:@M@EaseChatUIKit@E@GroupChatThreadEventType","text":"GroupChatThreadEventType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"text":"event:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)EMChatThreadEvent","text":"EMChatThreadEvent","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"event","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"onGroupChatThreadEventOccurWithType:event:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onGroupChatThreadEventOccur(type:event:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"onGroupChatThreadEventOccurWithType:event:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onGroupChatThreadEventOccur(type:event:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/title","value":"GroupChatThreadEventType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/fragments","value":[{"kind":"identifier","text":"GroupChatThreadEventType"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1GroupChatThreadEventType\/navigatorTitle","value":[{"text":"GroupChatThreadEventType","kind":"identifier"}],"op":"replace"},{"value":"ChatThreadViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/navigatorTitle","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}