{"abstract":[{"type":"text","text":"When message recalled."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidRecalled(recallInfo:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RecallInfo","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"recallInfo","content":[{"inlineContent":[{"text":"","type":"text"},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidrecalled(recallinfo:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidrecalled(recallinfo:)"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations"]]},"kind":"symbol","metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)onMessageDidRecalledWithRecallInfo:","title":"onMessageDidRecalled(recallInfo:)","roleHeading":"Instance Method","symbolKind":"method","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageDidRecalled","kind":"identifier"},{"kind":"text","text":"("},{"text":"recallInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","text":"RecallInfo"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","abstract":[],"title":"ChatMessage","url":"\/documentation\/easechatuikit\/chatmessage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessage","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageDidRecalled(recallInfo:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidRecalled(recallInfo:)","title":"onMessageDidRecalled(recallInfo:)","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidrecalled(recallinfo:)","role":"symbol","abstract":[{"type":"text","text":"When message recalled."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageDidRecalled","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"recallInfo"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit10RecallInfoa","text":"RecallInfo"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"abstract":[],"title":"ChatThreadViewModel","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/ChatResponseListener-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/chatresponselistener-implementations","type":"topic","title":"ChatResponseListener Implementations","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/RecallInfo":{"role":"symbol","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/recallinfo","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RecallInfo","kind":"identifier"}],"navigatorTitle":[{"text":"RecallInfo","kind":"identifier"}],"title":"RecallInfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/RecallInfo"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"onMessageDidRecalledWithRecallInfo:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"EMRecallMessageInfo","preciseIdentifier":"c:objc(cs)EMRecallMessageInfo"},{"text":" *) ","kind":"text"},{"text":"recallInfo","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"onMessageDidRecalledWithRecallInfo:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidRecalled(recallInfo:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidRecalled(recallInfo:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"onMessageDidRecalledWithRecallInfo:","kind":"identifier"}]},{"value":"ChatThreadViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title"},{"value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments"}]}]}