{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageAvatarLongPressed(profile:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"onMessageAvatarLongPressed(profile:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageAvatarLongPressed"},{"text":"(","kind":"text"},{"text":"profile","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"EaseProfileProtocol","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)onMessageAvatarLongPressedWithProfile:","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageAvatarLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"profile"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","text":"EaseProfileProtocol"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","type":"reference","isActive":true}],"type":"paragraph"}],"name":"profile"}],"kind":"parameters"}],"abstract":[{"type":"text","text":"The method will call on message avatar long pressed."}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessageavatarlongpressed(profile:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessageavatarlongpressed(profile:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/MessageListViewActionEventsDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations","title":"MessageListViewActionEventsDelegate Implementations","abstract":[],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagelistviewactioneventsdelegate-implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageAvatarLongPressed(profile:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessageavatarlongpressed(profile:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageAvatarLongPressed(profile:)","title":"onMessageAvatarLongPressed(profile:)","abstract":[{"text":"The method will call on message avatar long pressed.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"onMessageAvatarLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"text":"profile","kind":"externalParam"},{"kind":"text","text":": "},{"text":"EaseProfileProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)EaseProfileProtocol"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewModel"}],"title":"ChatThreadViewModel","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseProfileProtocol":{"title":"EaseProfileProtocol","abstract":[{"type":"text","text":"Profile of the EaseChatUIKit display needed."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"EaseProfileProtocol","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/easeprofileprotocol","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseProfileProtocol","navigatorTitle":[{"kind":"identifier","text":"EaseProfileProtocol"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onMessageAvatarLongPressedWithProfile:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"onMessageAvatarLongPressedWithProfile:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)EaseProfileProtocol","text":"id<EaseProfileProtocol>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"profile"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"onMessageAvatarLongPressedWithProfile:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageAvatarLongPressed(profile:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageAvatarLongPressedWithProfile:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageAvatarLongPressed(profile:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]},{"value":"EaseProfileProtocol","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseProfileProtocol\/fragments","op":"replace","value":[{"text":"EaseProfileProtocol","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}