{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"onMessageVisible"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]},{"parameters":[{"name":"entity","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","isActive":true,"type":"reference"}]}]}],"kind":"parameters"}],"variants":[{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagevisible(entity:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagevisible(entity:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageVisible(entity:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Message visible on scroll in screen"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"onMessageVisible(entity:)","navigatorTitle":[{"text":"onMessageVisibleWithEntity:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageVisible","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier","text":"MessageEntity"},{"kind":"text","text":")"}],"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)onMessageVisibleWithEntity:","extendedModule":"EaseChatUIKit","symbolKind":"method","role":"symbol"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageVisible(entity:)":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagevisible(entity:)","role":"symbol","title":"onMessageVisible(entity:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageVisible(entity:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onMessageVisible","kind":"identifier"},{"kind":"text","text":"("},{"text":"entity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"onMessageVisibleWithEntity:"}],"abstract":[{"type":"text","text":"Message visible on scroll in screen"}],"kind":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/MessageListViewActionEventsDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagelistviewactioneventsdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations","type":"topic","abstract":[],"kind":"article","title":"MessageListViewActionEventsDelegate Implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageEntity":{"title":"MessageEntity","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageEntity"}],"url":"\/documentation\/easechatuikit\/messageentity","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MessageEntity","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"role":"symbol","abstract":[],"title":"ChatThreadViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"onMessageVisibleWithEntity:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageVisibleWithEntity:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageVisibleWithEntity:"},{"kind":"text","text":"("},{"text":"MessageEntity","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageEntity","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageEntity","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"entity"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageVisible(entity:)\/title","value":"onMessageVisibleWithEntity:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageVisible(entity:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageVisibleWithEntity:"}],"op":"replace"},{"value":"MessageEntity","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/fragments","value":[{"kind":"identifier","text":"MessageEntity"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageEntity\/navigatorTitle","value":[{"kind":"identifier","text":"MessageEntity"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewModel"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/navigatorTitle","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]}]}]}