{"abstract":[{"type":"text","text":"The method will call on message content long pressed."}],"metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)onMessageContentLongPressedWithCell:","symbolKind":"method","roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","role":"symbol","navigatorTitle":[{"text":"onMessageContentLongPressedWithCell:","kind":"identifier"}],"title":"onMessageContentLongPressed(cell:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageContentLongPressed","kind":"identifier"},{"kind":"text","text":"("},{"text":"cell","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagecontentlongpressed(cell:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagecontentlongpressed(cell:)"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageContentLongPressed(cell:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageContentLongPressed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cell"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","text":"MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","isActive":true,"type":"reference"}],"type":"paragraph"}],"name":"message"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/MessageListViewActionEventsDelegate-Implementations":{"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/messagelistviewactioneventsdelegate-implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/MessageListViewActionEventsDelegate-Implementations","type":"topic","abstract":[],"kind":"article","title":"MessageListViewActionEventsDelegate Implementations","role":"collectionGroup"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"role":"symbol","abstract":[],"title":"ChatThreadViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageCell":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MessageCell"}],"type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/messagecell","role":"symbol","title":"MessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","navigatorTitle":[{"text":"MessageCell","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageContentLongPressed(cell:)":{"abstract":[{"text":"The method will call on message content long pressed.","type":"text"}],"url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagecontentlongpressed(cell:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageContentLongPressed(cell:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"onMessageContentLongPressedWithCell:"}],"title":"onMessageContentLongPressed(cell:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"onMessageContentLongPressed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cell","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","text":"MessageCell","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"onMessageContentLongPressedWithCell:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageContentLongPressedWithCell:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageContentLongPressedWithCell:"},{"text":"(","kind":"text"},{"text":"MessageCell","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageCell","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)MessageCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cell","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"ChatThreadViewModel","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace"},{"value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/title","value":"MessageCell","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/fragments","value":[{"kind":"identifier","text":"MessageCell"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageCell\/navigatorTitle","value":[{"text":"MessageCell","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageContentLongPressed(cell:)\/title","op":"replace","value":"onMessageContentLongPressedWithCell:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"onMessageContentLongPressedWithCell:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageContentLongPressed(cell:)\/fragments"}]}]}