{"abstract":[{"text":"When message received.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidReceived(message:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageDidReceived"},{"kind":"text","text":"("},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"message","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"}],"type":"paragraph"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidreceived(message:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidreceived(message:)"]}],"metadata":{"navigatorTitle":[{"text":"onMessageDidReceivedWithMessage:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"title":"onMessageDidReceived(message:)","roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onMessageDidReceived","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":")","kind":"text"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)onMessageDidReceivedWithMessage:"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/ChatResponseListener-Implementations":{"kind":"article","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/chatresponselistener-implementations","title":"ChatResponseListener Implementations","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/ChatResponseListener-Implementations","abstract":[],"role":"collectionGroup","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatThreadViewModel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ChatThreadViewModel"}],"title":"ChatThreadViewModel","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/onMessageDidReceived(message:)":{"navigatorTitle":[{"text":"onMessageDidReceivedWithMessage:","kind":"identifier"}],"kind":"symbol","title":"onMessageDidReceived(message:)","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/onmessagedidreceived(message:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/onMessageDidReceived(message:)","abstract":[{"text":"When message received.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"onMessageDidReceived"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","title":"ChatMessage","abstract":[],"navigatorTitle":[{"text":"ChatMessage","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"onMessageDidReceivedWithMessage:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"onMessageDidReceivedWithMessage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)EMChatMessage","kind":"typeIdentifier","text":"EMChatMessage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","value":"ChatThreadViewModel","op":"replace"},{"op":"replace","value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidReceived(message:)\/title","value":"onMessageDidReceivedWithMessage:"},{"value":[{"text":"- ","kind":"text"},{"text":"onMessageDidReceivedWithMessage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1onMessageDidReceived(message:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}