{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"processInputEvents","kind":"identifier"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","text":"MessageInputBarActionType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/processinputevents(action:attributetext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/processinputevents(action:attributetext:)"]}],"metadata":{"symbolKind":"method","extendedModule":"EaseChatUIKit","modules":[{"name":"EaseChatUIKit"}],"title":"processInputEvents(action:attributeText:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"processInputEvents"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"action"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"kind":"text","text":": "},{"text":"NSAttributedString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"processInputEventsWithAction:attributeText:"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)processInputEventsWithAction:attributeText:","roleHeading":"Instance Method"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processInputEvents(action:attributeText:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageInputBarActionType":{"role":"symbol","abstract":[{"text":"The types of actions that can be triggered by the input bar.","type":"text"}],"title":"MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MessageInputBarActionType","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/messageinputbaractiontype","navigatorTitle":[{"kind":"identifier","text":"MessageInputBarActionType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"role":"symbol","abstract":[],"title":"ChatThreadViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/processInputEvents(action:attributeText:)":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/processInputEvents(action:attributeText:)","kind":"symbol","title":"processInputEvents(action:attributeText:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"processInputEvents"},{"kind":"text","text":"("},{"text":"action","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"attributeText"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSAttributedString","text":"NSAttributedString"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"processInputEventsWithAction:attributeText:"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/processinputevents(action:attributetext:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"processInputEventsWithAction:attributeText:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"processInputEventsWithAction:attributeText:"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"processInputEventsWithAction:"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@MessageInputBarActionType","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageInputBarActionType","kind":"typeIdentifier","text":"MessageInputBarActionType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"kind":"text","text":" "},{"kind":"identifier","text":"attributeText:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSAttributedString","kind":"typeIdentifier","text":"NSAttributedString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"attributeText"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/title","value":"MessageInputBarActionType"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/fragments","value":[{"text":"MessageInputBarActionType","kind":"identifier"}]},{"value":[{"text":"MessageInputBarActionType","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageInputBarActionType\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title","op":"replace","value":"ChatThreadViewModel"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","value":[{"text":"ChatThreadViewModel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1processInputEvents(action:attributeText:)\/title","value":"processInputEventsWithAction:attributeText:"},{"value":[{"kind":"text","text":"- "},{"text":"processInputEventsWithAction:attributeText:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1processInputEvents(action:attributeText:)\/fragments","op":"replace"}]}]}