{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"showOriginalText","kind":"identifier"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","kind":"typeIdentifier","text":"ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/showoriginaltext(message:)"]},{"paths":["\/documentation\/easechatuikit\/chatthreadviewmodel\/showoriginaltext(message:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)ChatThreadViewModel(im)showOriginalTextWithMessage:","roleHeading":"Instance Method","navigatorTitle":[{"text":"showOriginalTextWithMessage:","kind":"identifier"}],"title":"showOriginalText(message:)","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"showOriginalText"},{"text":"(","kind":"text"},{"text":"message","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/showOriginalText(message:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel/showOriginalText(message:)":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"showOriginalTextWithMessage:"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel\/showOriginalText(message:)","title":"showOriginalText(message:)","kind":"symbol","url":"\/documentation\/easechatuikit\/chatthreadviewmodel\/showoriginaltext(message:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"showOriginalText","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"message"},{"text":": ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"kind":"text","text":")"}],"type":"topic","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatThreadViewModel":{"role":"symbol","abstract":[],"title":"ChatThreadViewModel","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatThreadViewModel","url":"\/documentation\/easechatuikit\/chatthreadviewmodel","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatThreadViewModel"}],"kind":"symbol","navigatorTitle":[{"text":"ChatThreadViewModel","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","kind":"symbol","url":"\/documentation\/easechatuikit\/chatmessage","abstract":[],"role":"symbol","title":"ChatMessage","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatMessage"}],"navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"showOriginalTextWithMessage:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"showOriginalTextWithMessage:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"showOriginalTextWithMessage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMChatMessage","text":"EMChatMessage"},{"text":" *) ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"showOriginalTextWithMessage:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1showOriginalText(message:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel~1showOriginalText(message:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"showOriginalTextWithMessage:"}],"op":"replace"},{"op":"replace","value":"ChatThreadViewModel","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/fragments","op":"replace","value":[{"text":"ChatThreadViewModel","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"ChatThreadViewModel"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatThreadViewModel\/navigatorTitle"}]}]}