{"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onResult","kind":"identifier"},{"kind":"text","text":"("},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ContactEmergencyType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactEmergencyType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"operatorId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","title":"onResult(error:type:operatorId:)","symbolKind":"method","role":"symbol","externalID":"c:@M@EaseChatUIKit@objc(pl)ContactEmergencyListener(im)onResultWithError:type:operatorId:","navigatorTitle":[{"kind":"identifier","text":"onResultWithError:type:operatorId:"}],"modules":[{"name":"EaseChatUIKit"}],"required":true},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)"},"variants":[{"paths":["\/documentation\/easechatuikit\/contactemergencylistener\/onresult(error:type:operatorid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactemergencylistener\/onresult(error:type:operatorid:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"onResult","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"error"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"text":"ContactEmergencyType","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactEmergencyType"},{"kind":"text","text":", "},{"text":"operatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":".Success ","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","type":"reference","isActive":true},{"type":"text","text":" is nil."}]}],"name":"error"},{"name":"type","content":[{"inlineContent":[{"type":"text","text":""},{"isActive":true,"type":"reference","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType"}],"type":"paragraph"}]},{"name":"operatorId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The id of operator."}]}]}],"kind":"parameters"}],"kind":"symbol","abstract":[{"type":"text","text":"You’ll receive the result on conversation service request successful or failure."}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"title":"ChatError","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatError"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/chaterror","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyListener":{"title":"ContactEmergencyListener","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener","url":"\/documentation\/easechatuikit\/contactemergencylistener","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ContactEmergencyListener","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"ContactEmergencyListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyListener/onResult(error:type:operatorId:)":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyListener\/onResult(error:type:operatorId:)","url":"\/documentation\/easechatuikit\/contactemergencylistener\/onresult(error:type:operatorid:)","title":"onResult(error:type:operatorId:)","kind":"symbol","required":true,"role":"symbol","abstract":[{"text":"You’ll receive the result on conversation service request successful or failure.","type":"text"}],"navigatorTitle":[{"text":"onResultWithError:type:operatorId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"onResult","kind":"identifier"},{"text":"(","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"kind":"text","text":"?, "},{"text":"type","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ContactEmergencyType","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactEmergencyType"},{"kind":"text","text":", "},{"text":"operatorId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactEmergencyType":{"title":"ContactEmergencyType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactEmergencyType","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType","navigatorTitle":[{"text":"ContactEmergencyType","kind":"identifier"}],"abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/contactemergencytype","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"onResultWithError:type:operatorId:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"onResultWithError:type:operatorId:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"onResultWithError:"},{"kind":"text","text":"("},{"text":"EMError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"type:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactEmergencyType","text":"ContactEmergencyType","preciseIdentifier":"c:@M@EaseChatUIKit@E@ContactEmergencyType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"text":"operatorId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"operatorId"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/title","value":"ContactEmergencyListener"},{"value":[{"kind":"identifier","text":"ContactEmergencyListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener\/fragments"},{"value":"onResultWithError:type:operatorId:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener~1onResult(error:type:operatorId:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"onResultWithError:type:operatorId:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyListener~1onResult(error:type:operatorId:)\/fragments"},{"op":"replace","value":"ContactEmergencyType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyType\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactEmergencyType\/fragments","value":[{"text":"ContactEmergencyType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}