{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"MessageListType.history","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"MessageListTypeHistory","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"history","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@E@MessageListType@MessageListTypeHistory","symbolKind":"case"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/history"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelisttype\/history"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelisttype\/history"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"history"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType":{"title":"MessageListType","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MessageListType"}],"url":"\/documentation\/easechatuikit\/messagelisttype","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType","navigatorTitle":[{"kind":"identifier","text":"MessageListType"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageListType/history":{"url":"\/documentation\/easechatuikit\/messagelisttype\/history","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageListType\/history","title":"MessageListType.history","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageListTypeHistory"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"history"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"MessageListTypeHistory","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"MessageListTypeHistory"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MessageListTypeHistory"}]}]}},{"value":"MessageListType","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"MessageListType"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1history\/title","value":"MessageListTypeHistory","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageListType~1history\/fragments","value":[{"kind":"identifier","text":"MessageListTypeHistory"}],"op":"replace"}]}]}