{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cellForRowAtIndexPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"indexPath","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The index path of the cell."}]}],"name":"indexPath"}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A table view cell for the specified index path."}]}],"kind":"content"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/cellforrowatindexpath(indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/cellforrowatindexpath(indexpath:)"]}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactInfoViewController(im)cellForRowAtIndexPathWithIndexPath:","title":"cellForRowAtIndexPath(indexPath:)","extendedModule":"EaseChatUIKit","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cellForRowAtIndexPath","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"cellForRowAtIndexPathWithIndexPath:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/cellForRowAtIndexPath(indexPath:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a table view cell for the specified index path."}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/cellForRowAtIndexPath(indexPath:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/cellforrowatindexpath(indexpath:)","abstract":[{"text":"Returns a table view cell for the specified index path.","type":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/cellForRowAtIndexPath(indexPath:)","type":"topic","title":"cellForRowAtIndexPath(indexPath:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cellForRowAtIndexPath","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UITableViewCell","kind":"typeIdentifier","text":"UITableViewCell"}],"navigatorTitle":[{"kind":"identifier","text":"cellForRowAtIndexPathWithIndexPath:"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"title":"ContactInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactInfoViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","navigatorTitle":[{"text":"ContactInfoViewController","kind":"identifier"}],"abstract":[{"text":"This is the documentation comment for the ","type":"text"},{"code":"ContactInfoViewController","type":"codeVoice"},{"text":" class.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"cellForRowAtIndexPathWithIndexPath:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cellForRowAtIndexPathWithIndexPath:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableViewCell","text":"UITableViewCell","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cellForRowAtIndexPathWithIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSIndexPath","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1cellForRowAtIndexPath(indexPath:)\/title","value":"cellForRowAtIndexPathWithIndexPath:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1cellForRowAtIndexPath(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cellForRowAtIndexPathWithIndexPath:","kind":"identifier"}]},{"value":"ContactInfoViewController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","value":[{"kind":"identifier","text":"ContactInfoViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}