{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/conversationService","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"conversationService","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ConversationServiceImplement","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationServiceImplement"}]}],"kind":"declarations"}],"sections":[],"metadata":{"symbolKind":"property","externalID":"s:13EaseChatUIKit25ContactInfoViewControllerC19conversationServiceAA012ConversationI9ImplementCvp","role":"symbol","title":"conversationService","roleHeading":"Instance Property","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"conversationService"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ConversationServiceImplement","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationServiceImplement"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/conversationservice"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"title":"ContactInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactInfoViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","navigatorTitle":[{"text":"ContactInfoViewController","kind":"identifier"}],"abstract":[{"text":"This is the documentation comment for the ","type":"text"},{"code":"ContactInfoViewController","type":"codeVoice"},{"text":" class.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/conversationService":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/conversationService","role":"symbol","title":"conversationService","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/conversationservice","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"conversationService","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ConversationServiceImplement","text":"ConversationServiceImplement"}],"abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationServiceImplement":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationServiceImplement","title":"ConversationServiceImplement","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/conversationserviceimplement","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"ConversationServiceImplement"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ConversationServiceImplement","kind":"identifier"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController"},{"value":[{"text":"ContactInfoViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/title","value":"ConversationServiceImplement"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationServiceImplement\/fragments","value":[{"kind":"identifier","text":"ConversationServiceImplement"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}