{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createHeader"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfoHeader","text":"DetailInfoHeader"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"An instance of DetailInfoHeader."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/createheader()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/createheader()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/createHeader()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Creates a header view for the ContactInfoViewController."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createHeader"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DetailInfoHeader","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfoHeader"}],"title":"createHeader()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController(im)createHeader","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"createHeader"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfoHeader":{"role":"symbol","title":"DetailInfoHeader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetailInfoHeader"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetailInfoHeader"}],"url":"\/documentation\/easechatuikit\/detailinfoheader"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/createHeader()":{"role":"symbol","title":"createHeader()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createHeader"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DetailInfoHeader","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfoHeader"}],"abstract":[{"type":"text","text":"Creates a header view for the ContactInfoViewController."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/createHeader()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createHeader"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/createheader()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"role":"symbol","title":"ContactInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactInfoViewController"}],"abstract":[{"type":"text","text":"This is the documentation comment for the "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" class."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"createHeader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createHeader"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfoHeader","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfoHeader","text":"DetailInfoHeader"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createHeader"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/title","value":"DetailInfoHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfoHeader\/fragments","value":[{"kind":"identifier","text":"DetailInfoHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1createHeader()\/title","value":"createHeader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1createHeader()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"createHeader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","value":[{"kind":"identifier","text":"ContactInfoViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}