{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/dictionaryMapToInfo(json:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/dictionarymaptoinfo(json:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/dictionarymaptoinfo(json:)"]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"dictionaryMapToInfoWithJson:","kind":"identifier"}],"title":"dictionaryMapToInfo(json:)","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dictionaryMapToInfo"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":">) -> ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfo","kind":"typeIdentifier","text":"DetailInfo"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController(im)dictionaryMapToInfoWithJson:","roleHeading":"Instance Method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"dictionaryMapToInfo","kind":"identifier"},{"text":"(","kind":"text"},{"text":"json","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SD","text":"Dictionary"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"text":">) -> ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo","text":"DetailInfo","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfo"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"title":"ContactInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactInfoViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","navigatorTitle":[{"text":"ContactInfoViewController","kind":"identifier"}],"abstract":[{"text":"This is the documentation comment for the ","type":"text"},{"code":"ContactInfoViewController","type":"codeVoice"},{"text":" class.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/DetailInfo":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetailInfo"}],"kind":"symbol","navigatorTitle":[{"text":"DetailInfo","kind":"identifier"}],"abstract":[],"url":"\/documentation\/easechatuikit\/detailinfo","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo","type":"topic","title":"DetailInfo"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/dictionaryMapToInfo(json:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/dictionarymaptoinfo(json:)","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/dictionaryMapToInfo(json:)","title":"dictionaryMapToInfo(json:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"dictionaryMapToInfo","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"json"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Dictionary","preciseIdentifier":"s:SD"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"text":"Any","kind":"keyword"},{"kind":"text","text":">) -> "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfo","kind":"typeIdentifier","text":"DetailInfo"}],"navigatorTitle":[{"text":"dictionaryMapToInfoWithJson:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"dictionaryMapToInfoWithJson:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"dictionaryMapToInfoWithJson:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/DetailInfo","kind":"typeIdentifier","text":"DetailInfo","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)DetailInfo"},{"kind":"text","text":" *) "},{"text":"dictionaryMapToInfoWithJson:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"json"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","value":[{"kind":"identifier","text":"ContactInfoViewController"}],"op":"replace"},{"value":"DetailInfo","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo\/title"},{"value":[{"kind":"identifier","text":"DetailInfo"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1DetailInfo\/fragments"},{"value":"dictionaryMapToInfoWithJson:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1dictionaryMapToInfo(json:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"dictionaryMapToInfoWithJson:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1dictionaryMapToInfo(json:)\/fragments"}]}]}