{"variants":[{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/didselectrow(indexpath:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/didselectrow(indexpath:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didSelectRow","kind":"identifier"},{"text":"(","kind":"text"},{"text":"indexPath","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"indexPath","content":[{"inlineContent":[{"text":"The index path of the selected row.","type":"text"}],"type":"paragraph"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/didSelectRow(indexPath:)"},"abstract":[{"text":"Called when a row is selected in the table view.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"metadata":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"didSelectRow","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactInfoViewController(im)didSelectRowWithIndexPath:","navigatorTitle":[{"text":"didSelectRowWithIndexPath:","kind":"identifier"}],"extendedModule":"EaseChatUIKit","title":"didSelectRow(indexPath:)","symbolKind":"method","modules":[{"name":"EaseChatUIKit"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"type":"topic","title":"ContactInfoViewController","navigatorTitle":[{"text":"ContactInfoViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"This is the documentation comment for the "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" class."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactInfoViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/didSelectRow(indexPath:)":{"abstract":[{"text":"Called when a row is selected in the table view.","type":"text"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/didselectrow(indexpath:)","title":"didSelectRow(indexPath:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"didSelectRow","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"didSelectRowWithIndexPath:"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/didSelectRow(indexPath:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"didSelectRowWithIndexPath:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"didSelectRowWithIndexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"didSelectRowWithIndexPath:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The index path of the selected row.","type":"text"}]}],"name":"indexPath"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"ContactInfoViewController"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/navigatorTitle","value":[{"text":"ContactInfoViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"didSelectRowWithIndexPath:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1didSelectRow(indexPath:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1didSelectRow(indexPath:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"didSelectRowWithIndexPath:"}],"op":"replace"}]}]}