{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerActions"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/headeractions()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/headeractions()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/headerActions()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method is responsible for handling the header actions in the ContactInfoViewController."},{"type":"text","text":" "},{"type":"text","text":"It checks if there is a chat action item available in the contact’s detail extension action items."},{"type":"text","text":" "},{"type":"text","text":"If found, it sets the action closure to invoke the "},{"type":"codeVoice","code":"alreadyChat()"},{"type":"text","text":" method when the action is triggered."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerActions"},{"kind":"text","text":"()"}],"title":"headerActions()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController(im)headerActions","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"headerActions"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/headerActions()":{"role":"symbol","title":"headerActions()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"headerActions"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method is responsible for handling the header actions in the ContactInfoViewController."},{"type":"text","text":" "},{"type":"text","text":"It checks if there is a chat action item available in the contact’s detail extension action items."},{"type":"text","text":" "},{"type":"text","text":"If found, it sets the action closure to invoke the "},{"type":"codeVoice","code":"alreadyChat()"},{"type":"text","text":" method when the action is triggered."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/headerActions()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"headerActions"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/headeractions()"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"role":"symbol","title":"ContactInfoViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ContactInfoViewController"}],"abstract":[{"type":"text","text":"This is the documentation comment for the "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" class."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ContactInfoViewController"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"headerActions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"headerActions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"headerActions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1headerActions()\/title","value":"headerActions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1headerActions()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"headerActions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","value":[{"kind":"identifier","text":"ContactInfoViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}