{"metadata":{"symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController(im)navigationClickWithType:indexPath:","role":"symbol","title":"navigationClick(type:indexPath:)","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigationClick"},{"kind":"text","text":"("},{"text":"type","kind":"externalParam"},{"kind":"text","text":": "},{"text":"EaseChatNavigationBarClickEvent","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/navigationClick(type:indexPath:)"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","text":"EaseChatNavigationBarClickEvent","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"indexPath"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"type","content":[{"inlineContent":[{"text":"The type of navigation click event.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The optional index path associated with the event."}],"type":"paragraph"}],"name":"indexPath"}],"kind":"parameters"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Handles the navigation click events in the ContactInfoViewController."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/navigationclick(type:indexpath:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/navigationclick(type:indexpath:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"title":"ContactInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactInfoViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","navigatorTitle":[{"text":"ContactInfoViewController","kind":"identifier"}],"abstract":[{"text":"This is the documentation comment for the ","type":"text"},{"code":"ContactInfoViewController","type":"codeVoice"},{"text":" class.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/EaseChatNavigationBarClickEvent":{"kind":"symbol","type":"topic","title":"EaseChatNavigationBarClickEvent","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","url":"\/documentation\/easechatuikit\/easechatnavigationbarclickevent","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EaseChatNavigationBarClickEvent","kind":"identifier"}],"navigatorTitle":[{"text":"EaseChatNavigationBarClickEvent","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/navigationClick(type:indexPath:)":{"kind":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/navigationclick(type:indexpath:)","abstract":[{"type":"text","text":"Handles the navigation click events in the ContactInfoViewController."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/navigationClick(type:indexPath:)","title":"navigationClick(type:indexPath:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"navigationClick"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent","text":"EaseChatNavigationBarClickEvent","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"indexPath"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"navigationClickWithType:indexPath:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"navigationClickWithType:indexPath:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"navigationClickWithType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"EaseChatNavigationBarClickEvent","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/EaseChatNavigationBarClickEvent","preciseIdentifier":"c:@M@EaseChatUIKit@E@EaseChatNavigationBarClickEvent"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"type"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indexPath:"},{"kind":"text","text":"("},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"kind":"text","text":" *) "},{"text":"indexPath","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","value":[{"text":"ContactInfoViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/title","op":"replace","value":"EaseChatNavigationBarClickEvent"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1EaseChatNavigationBarClickEvent\/fragments","value":[{"kind":"identifier","text":"EaseChatNavigationBarClickEvent"}]},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1navigationClick(type:indexPath:)\/title","value":"navigationClickWithType:indexPath:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"navigationClickWithType:indexPath:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1navigationClick(type:indexPath:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}