{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/operateDisturb(isOn:name:)"},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/operatedisturb(ison:name:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/operatedisturb(ison:name:)"]}],"metadata":{"navigatorTitle":[{"text":"operateDisturbWithIsOn:name:","kind":"identifier"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)ContactInfoViewController(im)operateDisturbWithIsOn:name:","roleHeading":"Instance Method","extendedModule":"EaseChatUIKit","role":"symbol","title":"operateDisturb(isOn:name:)","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"operateDisturb"},{"kind":"text","text":"("},{"kind":"externalParam","text":"isOn"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"operateDisturb"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isOn"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"type":"topic","title":"ContactInfoViewController","navigatorTitle":[{"text":"ContactInfoViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"This is the documentation comment for the "},{"type":"codeVoice","code":"ContactInfoViewController"},{"type":"text","text":" class."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ContactInfoViewController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/operateDisturb(isOn:name:)":{"abstract":[],"url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/operatedisturb(ison:name:)","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/operateDisturb(isOn:name:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"operateDisturbWithIsOn:name:"}],"title":"operateDisturb(isOn:name:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"operateDisturb","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"isOn"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"operateDisturbWithIsOn:name:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"operateDisturbWithIsOn:name:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"operateDisturbWithIsOn:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isOn","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"ContactInfoViewController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments","value":[{"text":"ContactInfoViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/navigatorTitle","value":[{"text":"ContactInfoViewController","kind":"identifier"}]},{"value":"operateDisturbWithIsOn:name:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1operateDisturb(isOn:name:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1operateDisturb(isOn:name:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"operateDisturbWithIsOn:name:"}],"op":"replace"}]}]}