{"abstract":[{"text":"Sets up the view controller by adding subviews, setting avatar URL, nickname, user state, and detail text.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"showMenu"},{"text":" is false, it also configures the menu list and adds a footer view with an “Add Contact” button.","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/setup()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setup","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/setup()"]},{"paths":["\/documentation\/easechatuikit\/contactinfoviewcontroller\/setup()"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"setup","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"setup","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@EaseChatUIKit@objc(cs)ContactInfoViewController(im)setup","roleHeading":"Instance Method","title":"setup()"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController":{"title":"ContactInfoViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ContactInfoViewController","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController","navigatorTitle":[{"text":"ContactInfoViewController","kind":"identifier"}],"abstract":[{"text":"This is the documentation comment for the ","type":"text"},{"code":"ContactInfoViewController","type":"codeVoice"},{"text":" class.","type":"text"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ContactInfoViewController/setup()":{"kind":"symbol","url":"\/documentation\/easechatuikit\/contactinfoviewcontroller\/setup()","abstract":[{"type":"text","text":"Sets up the view controller by adding subviews, setting avatar URL, nickname, user state, and detail text."},{"type":"text","text":" "},{"type":"text","text":"If "},{"type":"codeVoice","code":"showMenu"},{"type":"text","text":" is false, it also configures the menu list and adds a footer view with an “Add Contact” button."}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ContactInfoViewController\/setup()","title":"setup()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"setup","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setup","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"setup","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"setup"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/title","value":"ContactInfoViewController"},{"value":[{"kind":"identifier","text":"ContactInfoViewController"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController\/fragments"},{"value":"setup","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1setup()\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ContactInfoViewController~1setup()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"setup","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}