{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/edit(messageId:text:completion:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"edit"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"kind":"text","text":" ("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError"},{"text":"?, ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","kind":"typeIdentifier","text":"ChatMessage"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"messageId","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the message."}]}]},{"name":"text","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Replacement king of "},{"type":"codeVoice","code":"String"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Callback, returns message if successful, returns error if failed"}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatservice\/edit(messageid:text:completion:)"]},{"paths":["\/documentation\/easechatuikit\/chatservice\/edit(messageid:text:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"edit"},{"kind":"text","text":"("},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"text"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier","text":"ChatError"},{"kind":"text","text":"?, "},{"preciseIdentifier":"s:13EaseChatUIKit0B7Messagea","text":"ChatMessage","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","title":"edit(messageId:text:completion:)","navigatorTitle":[{"kind":"identifier","text":"editWithMessageId:text:completion:"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)ChatService(im)editWithMessageId:text:completion:","modules":[{"name":"EaseChatUIKit"}],"required":true},"abstract":[{"text":"Edit text message content.","type":"text"}],"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService","type":"topic","abstract":[],"url":"\/documentation\/easechatuikit\/chatservice","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ChatService","kind":"identifier"}],"title":"ChatService","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatService","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/edit(messageId:text:completion:)":{"title":"edit(messageId:text:completion:)","kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/edit(messageId:text:completion:)","url":"\/documentation\/easechatuikit\/chatservice\/edit(messageid:text:completion:)","required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"edit"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":", ","kind":"text"},{"text":"text","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ChatMessage","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B7Messagea"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"editWithMessageId:text:completion:"}],"role":"symbol","abstract":[{"type":"text","text":"Edit text message content."}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"url":"\/documentation\/easechatuikit\/chaterror","role":"symbol","abstract":[],"title":"ChatError","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"ChatError","kind":"identifier"}],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatMessage":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatMessage","type":"topic","abstract":[],"title":"ChatMessage","url":"\/documentation\/easechatuikit\/chatmessage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ChatMessage"}],"kind":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChatMessage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"editWithMessageId:text:completion:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"editWithMessageId:text:completion:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"editWithMessageId:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"messageId"},{"kind":"text","text":" "},{"kind":"identifier","text":"text:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"text","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"EMError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMError"},{"text":" * ","kind":"text"},{"text":"","kind":"internalParam"},{"kind":"text","text":", "},{"text":"EMChatMessage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)EMChatMessage"},{"kind":"text","text":" * "},{"text":"","kind":"internalParam"},{"kind":"text","text":")) "},{"kind":"internalParam","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/title","value":"ChatService","op":"replace"},{"value":[{"text":"ChatService","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/fragments"},{"value":"editWithMessageId:text:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1edit(messageId:text:completion:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1edit(messageId:text:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"editWithMessageId:text:completion:"}],"op":"replace"}]}]}