{"kind":"symbol","identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinMessage(messageId:completion:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/chatservice\/pinmessage(messageid:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/chatservice\/pinmessage(messageid:completion:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pinMessage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"text":"@escaping","kind":"attribute"},{"text":" (","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","text":"ChatError","preciseIdentifier":"s:13EaseChatUIKit0B5Errora","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"messageId","content":[{"type":"paragraph","inlineContent":[{"text":"ID of the message.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Callback, returns error whether successful error is ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":", or error occur."}],"type":"paragraph"}],"name":"completion"}],"kind":"parameters"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pinMessage","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"messageId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"ChatError","kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit0B5Errora"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)ChatService(im)pinMessageWithMessageId:completion:","symbolKind":"method","navigatorTitle":[{"text":"pinMessageWithMessageId:completion:","kind":"identifier"}],"required":true,"roleHeading":"Instance Method","title":"pinMessage(messageId:completion:)"},"abstract":[{"text":"Stickied a message on top.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatError":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChatError"}],"title":"ChatError","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatError","kind":"symbol","type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"ChatError","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/chaterror"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService/pinMessage(messageId:completion:)":{"kind":"symbol","abstract":[{"type":"text","text":"Stickied a message on top."}],"role":"symbol","url":"\/documentation\/easechatuikit\/chatservice\/pinmessage(messageid:completion:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService\/pinMessage(messageId:completion:)","required":true,"title":"pinMessage(messageId:completion:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pinMessage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"messageId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": (","kind":"text"},{"preciseIdentifier":"s:13EaseChatUIKit0B5Errora","text":"ChatError","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"pinMessageWithMessageId:completion:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatService":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatService","url":"\/documentation\/easechatuikit\/chatservice","title":"ChatService","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ChatService","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChatService"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"pinMessageWithMessageId:completion:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pinMessageWithMessageId:completion:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pinMessageWithMessageId:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"messageId","kind":"internalParam"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"text":")(","kind":"text"},{"text":"EMError","preciseIdentifier":"c:objc(cs)EMError","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"internalParam","text":""},{"text":")) ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"ID of the message."}]}],"name":"messageId"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Callback, returns error whether successful error is "},{"code":"nil","type":"codeVoice"},{"text":", or error occur.","type":"text"}]}],"name":"completion"}]},"path":"\/primaryContentSections\/1"},{"value":"pinMessageWithMessageId:completion:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1pinMessage(messageId:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"pinMessageWithMessageId:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService~1pinMessage(messageId:completion:)\/fragments"},{"value":"ChatService","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"ChatService"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/fragments"},{"value":[{"kind":"identifier","text":"ChatService"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatService\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}