{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/UITableViewDelegate-Implementations"]]},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"leadingSwipeActionsConfigurationForRowAt"},{"kind":"text","text":": "},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UISwipeActionsConfiguration","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","kind":"identifier"}],"title":"tableView(_:leadingSwipeActionsConfigurationForRowAt:)","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)ConversationList(im)tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/tableView(_:leadingSwipeActionsConfigurationForRowAt:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITableViewDelegate.tableView(_:leadingSwipeActionsConfigurationForRowAt:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"tableView"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"tableView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UITableView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITableView"},{"kind":"text","text":", "},{"kind":"externalParam","text":"leadingSwipeActionsConfigurationForRowAt"},{"kind":"text","text":" "},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":": "},{"text":"IndexPath","preciseIdentifier":"s:10Foundation9IndexPathV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UISwipeActionsConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/conversationlist\/tableview(_:leadingswipeactionsconfigurationforrowat:)"]},{"paths":["\/documentation\/easechatuikit\/conversationlist\/tableview(_:leadingswipeactionsconfigurationforrowat:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationList":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ConversationList","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/conversationlist","title":"ConversationList","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList","kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ConversationList"}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationList/tableView(_:leadingSwipeActionsConfigurationForRowAt:)":{"role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/tableView(_:leadingSwipeActionsConfigurationForRowAt:)","abstract":[],"url":"\/documentation\/easechatuikit\/conversationlist\/tableview(_:leadingswipeactionsconfigurationforrowat:)","navigatorTitle":[{"kind":"identifier","text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tableView","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"leadingSwipeActionsConfigurationForRowAt","kind":"externalParam"},{"kind":"text","text":": "},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"kind":"text","text":") -> "},{"text":"UISwipeActionsConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","title":"tableView(_:leadingSwipeActionsConfigurationForRowAt:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationList/UITableViewDelegate-Implementations":{"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/UITableViewDelegate-Implementations","kind":"article","role":"collectionGroup","abstract":[],"title":"UITableViewDelegate Implementations","url":"\/documentation\/easechatuikit\/conversationlist\/uitableviewdelegate-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UISwipeActionsConfiguration","text":"UISwipeActionsConfiguration"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"tableView:"},{"text":"(","kind":"text"},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"tableView"},{"kind":"text","text":" "},{"kind":"identifier","text":"leadingSwipeActionsConfigurationForRowAtIndexPath:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexPath","kind":"typeIdentifier","text":"NSIndexPath"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"indexPath"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"ConversationList","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList\/title","op":"replace"},{"value":[{"text":"ConversationList","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList~1tableView(_:leadingSwipeActionsConfigurationForRowAt:)\/title","value":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList~1tableView(_:leadingSwipeActionsConfigurationForRowAt:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"tableView:leadingSwipeActionsConfigurationForRowAtIndexPath:","kind":"identifier"}]}]}]}