{"variants":[{"paths":["\/documentation\/easechatuikit\/conversationlist\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/conversationlist\/uiscrollviewdelegate-implementations"]}],"kind":"article","sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/UIScrollViewDelegate-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList"]]},"metadata":{"role":"collectionGroup","title":"UIScrollViewDelegate Implementations","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"API Collection"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/scrollViewDidEndDragging(_:willDecelerate:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationList/scrollViewDidEndDragging(_:willDecelerate:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDragging","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"willDecelerate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/conversationlist\/scrollviewdidenddragging(_:willdecelerate:)","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDragging:willDecelerate:"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/scrollViewDidEndDragging(_:willDecelerate:)","title":"scrollViewDidEndDragging(_:willDecelerate:)","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationList/scrollViewDidEndDecelerating(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIScrollView","preciseIdentifier":"c:objc(cs)UIScrollView"},{"kind":"text","text":")"}],"title":"scrollViewDidEndDecelerating(_:)","navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/scrollViewDidEndDecelerating(_:)","type":"topic","url":"\/documentation\/easechatuikit\/conversationlist\/scrollviewdidenddecelerating(_:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ConversationList":{"type":"topic","navigatorTitle":[{"text":"ConversationList","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList","url":"\/documentation\/easechatuikit\/conversationlist","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ConversationList"}],"role":"symbol","kind":"symbol","abstract":[],"title":"ConversationList"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/scrollViewDidEndDecelerating(_:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ConversationList\/scrollViewDidEndDragging(_:willDecelerate:)"],"title":"Instance Methods"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList~1scrollViewDidEndDragging(_:willDecelerate:)\/title","op":"replace","value":"scrollViewDidEndDragging:willDecelerate:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList~1scrollViewDidEndDragging(_:willDecelerate:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndDragging:willDecelerate:","kind":"identifier"}]},{"value":"scrollViewDidEndDecelerating:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList~1scrollViewDidEndDecelerating(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList\/title","value":"ConversationList"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList\/fragments","value":[{"text":"ConversationList","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ConversationList\/navigatorTitle","value":[{"text":"ConversationList","kind":"identifier"}]}]}]}