{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":" "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/easechatuikit\/presentationanimation\/animatetransition(using:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/presentationanimation\/animatetransition(using:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/animateTransition(using:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"UIViewControllerAnimatedTransitioning.animateTransition(using:)"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"title":"animateTransition(using:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@CM@EaseChatUIKit@objc(cs)PresentationAnimation(im)animateTransition:","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation":{"role":"symbol","title":"PresentationAnimation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PresentationAnimation"}],"url":"\/documentation\/easechatuikit\/presentationanimation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/animateTransition(using:)":{"role":"symbol","title":"animateTransition(using:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animateTransition"},{"kind":"text","text":"("},{"kind":"externalParam","text":"using"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/animateTransition(using:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}],"url":"\/documentation\/easechatuikit\/presentationanimation\/animatetransition(using:)"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"role":"collection","title":"EaseChatUIKit","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/UIViewControllerAnimatedTransitioning-Implementations":{"role":"collectionGroup","title":"UIViewControllerAnimatedTransitioning Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations","kind":"article","type":"topic","url":"\/documentation\/easechatuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"animateTransition:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animateTransition:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"animateTransition:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<UIViewControllerContextTransitioning>","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerContextTransitioning"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"transitionContext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/title","value":"PresentationAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/fragments","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation~1animateTransition(using:)\/title","value":"animateTransition:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation~1animateTransition(using:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animateTransition:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}