{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"performAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AnimationContext","kind":"typeIdentifier","text":"AnimationContext"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/presentationanimation\/performanimation(animationcontext:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/performAnimation(animationContext:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"performAnimation(animationContext:)","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"performAnimation"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","text":"AnimationContext"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"s:13EaseChatUIKit21PresentationAnimationC07performE016animationContextyAA0eH0V_tF"},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AnimationContext":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimationContext","kind":"identifier"}],"abstract":[],"title":"AnimationContext","role":"symbol","navigatorTitle":[{"text":"AnimationContext","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/animationcontext","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AnimationContext"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation":{"title":"PresentationAnimation","navigatorTitle":[{"text":"PresentationAnimation","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PresentationAnimation","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/presentationanimation","kind":"symbol","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/performAnimation(animationContext:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"performAnimation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"animationContext","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:13EaseChatUIKit16AnimationContextV","text":"AnimationContext"},{"text":")","kind":"text"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/performAnimation(animationContext:)","title":"performAnimation(animationContext:)","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/presentationanimation\/performanimation(animationcontext:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/title","value":"PresentationAnimation"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/fragments","value":[{"kind":"identifier","text":"PresentationAnimation"}]},{"op":"replace","value":[{"text":"PresentationAnimation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/navigatorTitle"}]}]}