{"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations"]},{"paths":["\/documentation\/easechatuikit\/presentationanimation\/uiviewcontrolleranimatedtransitioning-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/UIViewControllerAnimatedTransitioning-Implementations"},"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/animateTransition(using:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/transitionDuration(using:)"],"generated":true,"title":"Instance Methods"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation"]]},"metadata":{"roleHeading":"API Collection","title":"UIViewControllerAnimatedTransitioning Implementations","modules":[{"name":"EaseChatUIKit"}],"role":"collectionGroup"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/transitionDuration(using:)":{"navigatorTitle":[{"text":"transitionDuration:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/presentationanimation\/transitionduration(using:)","title":"transitionDuration(using:)","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/transitionDuration(using:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionDuration"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIViewControllerContextTransitioning","preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation/animateTransition(using:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"animateTransition","kind":"identifier"},{"kind":"text","text":"("},{"text":"using","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(pl)UIViewControllerContextTransitioning","text":"UIViewControllerContextTransitioning","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/animateTransition(using:)","title":"animateTransition(using:)","url":"\/documentation\/easechatuikit\/presentationanimation\/animatetransition(using:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"animateTransition:"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationAnimation":{"kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationAnimation"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation","title":"PresentationAnimation","navigatorTitle":[{"kind":"identifier","text":"PresentationAnimation"}],"url":"\/documentation\/easechatuikit\/presentationanimation","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/animateTransition(using:)","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationAnimation\/transitionDuration(using:)"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation~1transitionDuration(using:)\/title","value":"transitionDuration:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation~1transitionDuration(using:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"transitionDuration:","kind":"identifier"}]},{"value":"animateTransition:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation~1animateTransition(using:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation~1animateTransition(using:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"animateTransition:","kind":"identifier"}]},{"value":"PresentationAnimation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationAnimation\/fragments","value":[{"text":"PresentationAnimation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}