{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"forward","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"MessageOperation.forward","roleHeading":"Case","externalID":"c:@M@EaseChatUIKit@E@MessageOperation@MessageOperationForward","navigatorTitle":[{"text":"MessageOperationForward","kind":"identifier"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"forward"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/messageoperation\/forward"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messageoperation\/forward"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/forward","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/forward":{"navigatorTitle":[{"kind":"identifier","text":"MessageOperationForward"}],"abstract":[],"type":"topic","url":"\/documentation\/easechatuikit\/messageoperation\/forward","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"forward","kind":"identifier"}],"title":"MessageOperation.forward","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/forward","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation":{"type":"topic","title":"MessageOperation","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageOperation"}],"url":"\/documentation\/easechatuikit\/messageoperation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageOperation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"MessageOperationForward","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MessageOperationForward","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"MessageOperationForward"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"MessageOperationForward","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1forward\/title","op":"replace"},{"value":[{"text":"MessageOperationForward","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1forward\/fragments"},{"value":"MessageOperation","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/title"},{"op":"replace","value":[{"text":"MessageOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/fragments"},{"value":[{"kind":"identifier","text":"MessageOperation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}