{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"translate"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"translate","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@E@MessageOperation@MessageOperationTranslate","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"MessageOperationTranslate"}],"title":"MessageOperation.translate","symbolKind":"case","modules":[{"name":"EaseChatUIKit"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messageoperation\/translate"]},{"paths":["\/documentation\/easechatuikit\/messageoperation\/translate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/translate","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation/translate":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"translate"}],"kind":"symbol","navigatorTitle":[{"text":"MessageOperationTranslate","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation\/translate","url":"\/documentation\/easechatuikit\/messageoperation\/translate","title":"MessageOperation.translate","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageOperation":{"type":"topic","title":"MessageOperation","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MessageOperation"}],"url":"\/documentation\/easechatuikit\/messageoperation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"MessageOperation","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageOperation"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"MessageOperationTranslate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"MessageOperationTranslate","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"MessageOperationTranslate"}]}],"kind":"declarations"}},{"value":"MessageOperationTranslate","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1translate\/title"},{"op":"replace","value":[{"text":"MessageOperationTranslate","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation~1translate\/fragments"},{"op":"replace","value":"MessageOperation","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/fragments","value":[{"kind":"identifier","text":"MessageOperation"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MessageOperation"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageOperation\/navigatorTitle"}]}]}