{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/UICollectionViewDataSource-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelongpressmenu\/collectionview(_:numberofitemsinsection:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelongpressmenu\/collectionview(_:numberofitemsinsection:)"]}],"metadata":{"symbolKind":"method","extendedModule":"EaseChatUIKit","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageLongPressMenu(im)collectionView:numberOfItemsInSection:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"modules":[{"name":"EaseChatUIKit"}],"title":"collectionView(_:numberOfItemsInSection:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"numberOfItemsInSection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/collectionView(_:numberOfItemsInSection:)"},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UICollectionViewDataSource.collectionView(_:numberOfItemsInSection:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"text":"numberOfItemsInSection","kind":"externalParam"},{"kind":"text","text":" "},{"text":"section","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu/UICollectionViewDataSource-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/UICollectionViewDataSource-Implementations","title":"UICollectionViewDataSource Implementations","url":"\/documentation\/easechatuikit\/messagelongpressmenu\/uicollectionviewdatasource-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu":{"navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenu"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageLongPressMenu","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu","kind":"symbol","title":"MessageLongPressMenu","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelongpressmenu","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu/collectionView(_:numberOfItemsInSection:)":{"navigatorTitle":[{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelongpressmenu\/collectionview(_:numberofitemsinsection:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"collectionView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier","text":"UICollectionView"},{"text":", ","kind":"text"},{"text":"numberOfItemsInSection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"collectionView(_:numberOfItemsInSection:)","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/collectionView(_:numberOfItemsInSection:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"collectionView:numberOfItemsInSection:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"collectionView:numberOfItemsInSection:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"identifier","text":"collectionView:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView"},{"kind":"text","text":" *) "},{"text":"collectionView","kind":"internalParam"},{"kind":"text","text":" "},{"text":"numberOfItemsInSection:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"section","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/title","value":"MessageLongPressMenu"},{"value":[{"kind":"identifier","text":"MessageLongPressMenu"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/fragments"},{"value":[{"text":"MessageLongPressMenu","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/navigatorTitle"},{"value":"collectionView:numberOfItemsInSection:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu~1collectionView(_:numberOfItemsInSection:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"collectionView:numberOfItemsInSection:"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu~1collectionView(_:numberOfItemsInSection:)\/fragments"}]}]}