{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/UICollectionViewDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/messagelongpressmenu\/collectionview(_:didselectitemat:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/messagelongpressmenu\/collectionview(_:didselectitemat:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"internalParam"},{"kind":"text","text":": "},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectItemAt"},{"text":" ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UICollectionViewDelegate.collectionView(_:didSelectItemAt:)"},{"text":".","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/collectionView(_:didSelectItemAt:)"},"metadata":{"title":"collectionView(_:didSelectItemAt:)","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","externalID":"c:@CM@EaseChatUIKit@objc(cs)MessageLongPressMenu(im)collectionView:didSelectItemAtIndexPath:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"collectionView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UICollectionView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didSelectItemAt"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation9IndexPathV","text":"IndexPath","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","extendedModule":"EaseChatUIKit","navigatorTitle":[{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu":{"navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenu"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageLongPressMenu","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu","kind":"symbol","title":"MessageLongPressMenu","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelongpressmenu","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu/UICollectionViewDelegate-Implementations":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/UICollectionViewDelegate-Implementations","title":"UICollectionViewDelegate Implementations","abstract":[],"kind":"article","role":"collectionGroup","url":"\/documentation\/easechatuikit\/messagelongpressmenu\/uicollectionviewdelegate-implementations","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu/collectionView(_:didSelectItemAt:)":{"role":"symbol","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/collectionView(_:didSelectItemAt:)","title":"collectionView(_:didSelectItemAt:)","url":"\/documentation\/easechatuikit\/messagelongpressmenu\/collectionview(_:didselectitemat:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"collectionView"},{"text":"(","kind":"text"},{"text":"UICollectionView","preciseIdentifier":"c:objc(cs)UICollectionView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"didSelectItemAt","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IndexPath","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation9IndexPathV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"collectionView:didSelectItemAtIndexPath:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"collectionView:didSelectItemAtIndexPath:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"collectionView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UICollectionView","text":"UICollectionView"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"collectionView"},{"text":" ","kind":"text"},{"text":"didSelectItemAtIndexPath:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSIndexPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSIndexPath"},{"text":" *) ","kind":"text"},{"text":"indexPath","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"MessageLongPressMenu","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/fragments","value":[{"text":"MessageLongPressMenu","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/navigatorTitle","op":"replace","value":[{"text":"MessageLongPressMenu","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu~1collectionView(_:didSelectItemAt:)\/title","value":"collectionView:didSelectItemAtIndexPath:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"collectionView:didSelectItemAtIndexPath:"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu~1collectionView(_:didSelectItemAt:)\/fragments"}]}]}