{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"targetViewFrame","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":" { get }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/easechatuikit\/messagelongpressmenu\/targetviewframe"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/targetViewFrame"},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"externalID":"s:13EaseChatUIKit20MessageLongPressMenuC15targetViewFrameSo6CGRectVvp","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"targetViewFrame","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"targetViewFrame","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu":{"navigatorTitle":[{"kind":"identifier","text":"MessageLongPressMenu"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MessageLongPressMenu","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu","kind":"symbol","title":"MessageLongPressMenu","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelongpressmenu","type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MessageLongPressMenu/targetViewFrame":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetViewFrame"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MessageLongPressMenu\/targetViewFrame","title":"targetViewFrame","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/messagelongpressmenu\/targetviewframe","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/title","op":"replace","value":"MessageLongPressMenu"},{"op":"replace","value":[{"kind":"identifier","text":"MessageLongPressMenu"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MessageLongPressMenu\/navigatorTitle","value":[{"kind":"identifier","text":"MessageLongPressMenu"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}