{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","symbolKind":"method","title":"audioRecorderDidFinishRecording(_:successfully:)","navigatorTitle":[{"kind":"identifier","text":"audioRecorderDidFinishRecording:successfully:"}],"externalID":"c:@CM@EaseChatUIKit@objc(cs)AudioTools(im)audioRecorderDidFinishRecording:successfully:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecorderDidFinishRecording"},{"text":"(","kind":"text"},{"text":"AVAudioRecorder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":", ","kind":"text"},{"text":"successfully","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/AVAudioRecorderDelegate-Implementations"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"audioRecorderDidFinishRecording"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"recorder","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"AVAudioRecorder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"kind":"text","text":", "},{"text":"successfully","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"flag","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVAudioRecorderDelegate.audioRecorderDidFinishRecording(_:successfully:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools/audioRecorderDidFinishRecording(_:successfully:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecorderDidFinishRecording"},{"kind":"text","text":"("},{"text":"AVAudioRecorder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":", ","kind":"text"},{"text":"successfully","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)","title":"audioRecorderDidFinishRecording(_:successfully:)","url":"\/documentation\/easechatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"audioRecorderDidFinishRecording:successfully:"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools":{"navigatorTitle":[{"kind":"identifier","text":"AudioTools"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/audiotools","title":"AudioTools","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AudioTools","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools/AVAudioRecorderDelegate-Implementations":{"kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/AVAudioRecorderDelegate-Implementations","title":"AVAudioRecorderDelegate Implementations","url":"\/documentation\/easechatuikit\/audiotools\/avaudiorecorderdelegate-implementations","role":"collectionGroup","abstract":[],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"audioRecorderDidFinishRecording:successfully:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioRecorderDidFinishRecording:successfully:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"audioRecorderDidFinishRecording:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"AVAudioRecorder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"recorder"},{"text":" ","kind":"text"},{"kind":"identifier","text":"successfully:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"flag","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"audioRecorderDidFinishRecording:successfully:","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"audioRecorderDidFinishRecording:successfully:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/title","value":"AudioTools"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/fragments","value":[{"text":"AudioTools","kind":"identifier"}]}]}]}