{"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/AVAudioPlayerDelegate-Implementations"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/audiotools\/audioplayerdidfinishplaying(_:successfully:)"]},{"paths":["\/documentation\/easechatuikit\/audiotools\/audioplayerdidfinishplaying(_:successfully:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"audioPlayerDidFinishPlaying","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"player"},{"text":": ","kind":"text"},{"text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"successfully"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"flag"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:@CM@EaseChatUIKit@objc(cs)AudioTools(im)audioPlayerDidFinishPlaying:successfully:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"AVAudioPlayer","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"text":", ","kind":"text"},{"text":"successfully","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}],"role":"symbol","modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","title":"audioPlayerDidFinishPlaying(_:successfully:)","symbolKind":"method"},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"AVAudioPlayerDelegate.audioPlayerDidFinishPlaying(_:successfully:)"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/audioPlayerDidFinishPlaying(_:successfully:)"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools":{"navigatorTitle":[{"kind":"identifier","text":"AudioTools"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/audiotools","title":"AudioTools","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AudioTools","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools/AVAudioPlayerDelegate-Implementations":{"role":"collectionGroup","url":"\/documentation\/easechatuikit\/audiotools\/avaudioplayerdelegate-implementations","kind":"article","type":"topic","title":"AVAudioPlayerDelegate Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/AVAudioPlayerDelegate-Implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools/audioPlayerDidFinishPlaying(_:successfully:)":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/audiotools\/audioplayerdidfinishplaying(_:successfully:)","title":"audioPlayerDidFinishPlaying(_:successfully:)","navigatorTitle":[{"kind":"identifier","text":"audioPlayerDidFinishPlaying:successfully:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"audioPlayerDidFinishPlaying","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)AVAudioPlayer","kind":"typeIdentifier","text":"AVAudioPlayer"},{"kind":"text","text":", "},{"kind":"externalParam","text":"successfully"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/audioPlayerDidFinishPlaying(_:successfully:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"audioPlayerDidFinishPlaying:successfully:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"audioPlayerDidFinishPlaying:successfully:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"audioPlayerDidFinishPlaying:"},{"text":"(","kind":"text"},{"text":"AVAudioPlayer","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioPlayer"},{"kind":"text","text":" *) "},{"text":"player","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"successfully:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"flag","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"AudioTools","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/fragments","value":[{"text":"AudioTools","kind":"identifier"}],"op":"replace"},{"value":"audioPlayerDidFinishPlaying:successfully:","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1audioPlayerDidFinishPlaying(_:successfully:)\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1audioPlayerDidFinishPlaying(_:successfully:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"audioPlayerDidFinishPlaying:successfully:","kind":"identifier"}]}]}]}