{"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"AVAudioRecorderDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/AVAudioRecorderDelegate-Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/audiotools\/avaudiorecorderdelegate-implementations"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/audiotools\/avaudiorecorderdelegate-implementations"]}],"topicSections":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)"],"generated":true,"title":"Instance Methods"}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools":{"navigatorTitle":[{"kind":"identifier","text":"AudioTools"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/audiotools","title":"AudioTools","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AudioTools","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools/audioRecorderDidFinishRecording(_:successfully:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"audioRecorderDidFinishRecording"},{"kind":"text","text":"("},{"text":"AVAudioRecorder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVAudioRecorder"},{"text":", ","kind":"text"},{"text":"successfully","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)","title":"audioRecorderDidFinishRecording(_:successfully:)","url":"\/documentation\/easechatuikit\/audiotools\/audiorecorderdidfinishrecording(_:successfully:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"audioRecorderDidFinishRecording:successfully:"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/audioRecorderDidFinishRecording(_:successfully:)"],"title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":"AudioTools","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/title","op":"replace"},{"value":[{"kind":"identifier","text":"AudioTools"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/title","op":"replace","value":"audioRecorderDidFinishRecording:successfully:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1audioRecorderDidFinishRecording(_:successfully:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"audioRecorderDidFinishRecording:successfully:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}