{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopPlaying","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/easechatuikit\/audiotools\/stopplaying()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/audiotools\/stopplaying()"]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools"]]},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/stopPlaying()","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@EaseChatUIKit@objc(cs)AudioTools(im)stopPlaying","symbolKind":"method","roleHeading":"Instance Method","role":"symbol","title":"stopPlaying()","navigatorTitle":[{"text":"stopPlaying","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopPlaying"},{"kind":"text","text":"()"}]},"sections":[],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools":{"navigatorTitle":[{"kind":"identifier","text":"AudioTools"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools","abstract":[],"role":"symbol","url":"\/documentation\/easechatuikit\/audiotools","title":"AudioTools","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"AudioTools","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/AudioTools/stopPlaying()":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/AudioTools\/stopPlaying()","role":"symbol","title":"stopPlaying()","navigatorTitle":[{"text":"stopPlaying","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/audiotools\/stopplaying()","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopPlaying","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"stopPlaying"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"stopPlaying","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopPlaying"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/title","value":"AudioTools","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools\/fragments","value":[{"text":"AudioTools","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"stopPlaying","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1stopPlaying()\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1AudioTools~1stopPlaying()\/fragments","value":[{"kind":"text","text":"- "},{"text":"stopPlaying","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}