{"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CombineMessageCell\/content","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"kind":"text","text":": "},{"text":"CombineMessageView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CombineMessageView","kind":"typeIdentifier"}],"role":"symbol","title":"content","externalID":"c:@M@EaseChatUIKit@objc(cs)CombineMessageCell(py)content","navigatorTitle":[{"text":"content","kind":"identifier"}],"roleHeading":"Instance Property"},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/combinemessagecell\/content"]},{"paths":["\/documentation\/easechatuikit\/combinemessagecell\/content"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CombineMessageView","kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CombineMessageView","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CombineMessageView"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CombineMessageCell"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CombineMessageView":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/combinemessageview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CombineMessageView"}],"title":"CombineMessageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CombineMessageView","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CombineMessageView"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CombineMessageCell/content":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/combinemessagecell\/content","role":"symbol","navigatorTitle":[{"text":"content","kind":"identifier"}],"title":"content","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CombineMessageView","text":"CombineMessageView"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CombineMessageCell\/content"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/CombineMessageCell":{"kind":"symbol","type":"topic","url":"\/documentation\/easechatuikit\/combinemessagecell","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CombineMessageCell"}],"title":"CombineMessageCell","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CombineMessageCell"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CombineMessageCell"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","title":"EaseChatUIKit","type":"topic","abstract":[],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"content"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"content","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)CombineMessageView","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/CombineMessageView","text":"CombineMessageView","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"content"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"CombineMessageView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CombineMessageView\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CombineMessageView\/fragments","value":[{"text":"CombineMessageView","kind":"identifier"}],"op":"replace"},{"value":"content","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CombineMessageCell~1content\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CombineMessageCell~1content\/fragments","value":[{"text":"content","kind":"identifier"}]},{"value":"CombineMessageCell","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CombineMessageCell\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1CombineMessageCell\/fragments","value":[{"kind":"identifier","text":"CombineMessageCell"}]}]}]}