{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController"]]},"variants":[{"paths":["\/documentation\/easechatuikit\/presentationcontroller\/frameofpresentedviewincontainerview"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/easechatuikit\/presentationcontroller\/frameofpresentedviewincontainerview"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"frameOfPresentedViewInContainerView","modules":[{"name":"EaseChatUIKit"}],"navigatorTitle":[{"text":"frameOfPresentedViewInContainerView","kind":"identifier"}],"externalID":"c:@M@EaseChatUIKit@objc(cs)PresentationController(py)frameOfPresentedViewInContainerView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}]},"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController":{"abstract":[{"text":"A custom presentation controller that manages the transition animations and layout of the presented view controller’s view.","type":"text"}],"title":"PresentationController","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController","kind":"symbol","url":"\/documentation\/easechatuikit\/presentationcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PresentationController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PresentationController"}],"type":"topic"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/PresentationController/frameOfPresentedViewInContainerView":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"frameOfPresentedViewInContainerView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"frameOfPresentedViewInContainerView"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/PresentationController\/frameOfPresentedViewInContainerView","url":"\/documentation\/easechatuikit\/presentationcontroller\/frameofpresentedviewincontainerview","title":"frameOfPresentedViewInContainerView","abstract":[],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"frameOfPresentedViewInContainerView"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"frameOfPresentedViewInContainerView","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"frameOfPresentedViewInContainerView","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"PresentationController","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController\/title","op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController\/fragments","op":"replace","value":[{"kind":"identifier","text":"PresentationController"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController\/navigatorTitle","value":[{"kind":"identifier","text":"PresentationController"}]},{"value":"frameOfPresentedViewInContainerView","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/title"},{"value":[{"kind":"identifier","text":"frameOfPresentedViewInContainerView"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1PresentationController~1frameOfPresentedViewInContainerView\/fragments"}]}]}