{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/multideviceservice\/unbindmultidevicelistener(listener:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/multideviceservice\/unbindmultidevicelistener(listener:)"]}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceService\/unbindMultiDeviceListener(listener:)","interfaceLanguage":"swift"},"metadata":{"title":"unbindMultiDeviceListener(listener:)","modules":[{"name":"EaseChatUIKit"}],"externalID":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceService(im)unbindMultiDeviceListenerWithListener:","required":true,"symbolKind":"method","navigatorTitle":[{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"unbindMultiDeviceListener","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"text":"MultiDeviceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceService"]]},"abstract":[{"type":"text","text":"Unbind multi device changed listener"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindMultiDeviceListener"},{"kind":"text","text":"("},{"kind":"externalParam","text":"listener"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","text":"MultiDeviceListener"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"name":"listener","content":[{"inlineContent":[{"text":"","type":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","isActive":true,"type":"reference"}],"type":"paragraph"}]}]}],"sections":[],"kind":"symbol","references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceService/unbindMultiDeviceListener(listener:)":{"abstract":[{"type":"text","text":"Unbind multi device changed listener"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceService\/unbindMultiDeviceListener(listener:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"}],"kind":"symbol","url":"\/documentation\/easechatuikit\/multideviceservice\/unbindmultidevicelistener(listener:)","required":true,"title":"unbindMultiDeviceListener(listener:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unbindMultiDeviceListener"},{"text":"(","kind":"text"},{"text":"listener","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(pl)MultiDeviceListener","text":"MultiDeviceListener","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceListener":{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","type":"topic","role":"symbol","url":"\/documentation\/easechatuikit\/multidevicelistener","kind":"symbol","navigatorTitle":[{"text":"MultiDeviceListener","kind":"identifier"}],"abstract":[],"title":"MultiDeviceListener","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiDeviceListener","kind":"identifier"}]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/MultiDeviceService":{"url":"\/documentation\/easechatuikit\/multideviceservice","title":"MultiDeviceService","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiDeviceService"}],"navigatorTitle":[{"text":"MultiDeviceService","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceService","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"unbindMultiDeviceListenerWithListener:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"unbindMultiDeviceListenerWithListener:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qo@M@EaseChatUIKit@objc(pl)MultiDeviceListener","text":"id<MultiDeviceListener>","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"listener","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"listener","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":""},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/MultiDeviceListener","isActive":true,"type":"reference"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceService~1unbindMultiDeviceListener(listener:)\/title","value":"unbindMultiDeviceListenerWithListener:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"unbindMultiDeviceListenerWithListener:","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceService~1unbindMultiDeviceListener(listener:)\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/title","value":"MultiDeviceListener","op":"replace"},{"op":"replace","value":[{"text":"MultiDeviceListener","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/fragments"},{"value":[{"kind":"identifier","text":"MultiDeviceListener"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceListener\/navigatorTitle"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceService\/title","op":"replace","value":"MultiDeviceService"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceService\/fragments","value":[{"text":"MultiDeviceService","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"MultiDeviceService"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1MultiDeviceService\/navigatorTitle"}]}]}