{"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"datas"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)NewContactRequest","text":"NewContactRequest","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"datas","externalID":"s:13EaseChatUIKit27NewContactRequestControllerC5datasSayAA0deF0CGvp"},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/datas","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/easechatuikit\/newcontactrequestcontroller\/datas"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"datas","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequest","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)NewContactRequest","text":"NewContactRequest"},{"text":"] { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController"]]},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequest":{"abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequest","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NewContactRequest"}],"navigatorTitle":[{"text":"NewContactRequest","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/newcontactrequest","title":"NewContactRequest"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController":{"navigatorTitle":[{"kind":"identifier","text":"NewContactRequestController"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller","title":"NewContactRequestController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NewContactRequestController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController","kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController/datas":{"role":"symbol","title":"datas","kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/datas","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"datas","kind":"identifier"},{"text":": [","kind":"text"},{"text":"NewContactRequest","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)NewContactRequest","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller\/datas","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"NewContactRequest","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequest\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequest\/fragments","value":[{"text":"NewContactRequest","kind":"identifier"}],"op":"replace"},{"value":[{"text":"NewContactRequest","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequest\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/title","value":"NewContactRequestController"},{"value":[{"text":"NewContactRequestController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/navigatorTitle","value":[{"text":"NewContactRequestController","kind":"identifier"}],"op":"replace"}]}]}