{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/newcontactrequestcontroller\/navigation"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"navigation","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar","kind":"typeIdentifier","text":"ChatNavigationBar","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatNavigationBar"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/navigation","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit27NewContactRequestControllerC10navigationAA0B13NavigationBarCvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"navigation"},{"text":": ","kind":"text"},{"text":"ChatNavigationBar","kind":"typeIdentifier","preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatNavigationBar"}],"title":"navigation","role":"symbol","symbolKind":"property"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController":{"navigatorTitle":[{"kind":"identifier","text":"NewContactRequestController"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller","title":"NewContactRequestController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NewContactRequestController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController","kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController/navigation":{"type":"topic","title":"navigation","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"navigation","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@EaseChatUIKit@objc(cs)ChatNavigationBar","kind":"typeIdentifier","text":"ChatNavigationBar"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller\/navigation","role":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/navigation"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/ChatNavigationBar":{"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/ChatNavigationBar","navigatorTitle":[{"text":"ChatNavigationBar","kind":"identifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/chatnavigationbar","title":"ChatNavigationBar","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChatNavigationBar","kind":"identifier"}],"abstract":[{"type":"text","text":"Navigation  bar of the ChatUIKit."}],"role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/title","value":"NewContactRequestController"},{"op":"replace","value":[{"kind":"identifier","text":"NewContactRequestController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/fragments"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/navigatorTitle","value":[{"text":"NewContactRequestController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"ChatNavigationBar","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/fragments","op":"replace","value":[{"kind":"identifier","text":"ChatNavigationBar"}]},{"value":[{"text":"ChatNavigationBar","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1ChatNavigationBar\/navigatorTitle","op":"replace"}]}]}