{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/requestList","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"requestList","modules":[{"name":"EaseChatUIKit"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestList","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"s:13EaseChatUIKit27NewContactRequestControllerC11requestListSo11UITableViewCvp"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/newcontactrequestcontroller\/requestlist"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"requestList","kind":"identifier"},{"kind":"text","text":": "},{"text":"UITableView","preciseIdentifier":"c:objc(cs)UITableView","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController/requestList":{"role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestList","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UITableView","text":"UITableView","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/easechatuikit\/newcontactrequestcontroller\/requestlist","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/requestList","title":"requestList"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController":{"navigatorTitle":[{"kind":"identifier","text":"NewContactRequestController"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller","title":"NewContactRequestController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NewContactRequestController","kind":"identifier"}],"identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController","kind":"symbol","abstract":[],"type":"topic","role":"symbol"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"url":"\/documentation\/easechatuikit","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","type":"topic","title":"EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/title","op":"replace","value":"NewContactRequestController"},{"value":[{"kind":"identifier","text":"NewContactRequestController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"NewContactRequestController"}],"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}