{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/UIScrollViewDelegate-Implementations"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/easechatuikit\/newcontactrequestcontroller\/scrollviewdidenddecelerating(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/newcontactrequestcontroller\/scrollviewdidenddecelerating(_:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIScrollViewDelegate.scrollViewDidEndDecelerating(_:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/scrollViewDidEndDecelerating(_:)"},"metadata":{"symbolKind":"method","title":"scrollViewDidEndDecelerating(_:)","navigatorTitle":[{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"modules":[{"name":"EaseChatUIKit"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scrollViewDidEndDecelerating"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIScrollView","kind":"typeIdentifier","text":"UIScrollView"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:@CM@EaseChatUIKit@objc(cs)NewContactRequestController(im)scrollViewDidEndDecelerating:","extendedModule":"EaseChatUIKit"},"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController/scrollViewDidEndDecelerating(_:)":{"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/scrollViewDidEndDecelerating(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller\/scrollviewdidenddecelerating(_:)","title":"scrollViewDidEndDecelerating(_:)","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController/UIScrollViewDelegate-Implementations":{"type":"topic","kind":"article","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/UIScrollViewDelegate-Implementations","abstract":[],"title":"UIScrollViewDelegate Implementations","role":"collectionGroup","url":"\/documentation\/easechatuikit\/newcontactrequestcontroller\/uiscrollviewdelegate-implementations"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController":{"navigatorTitle":[{"kind":"identifier","text":"NewContactRequestController"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NewContactRequestController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller","title":"NewContactRequestController","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"scrollViewDidEndDecelerating:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"scrollViewDidEndDecelerating:"},{"text":"(","kind":"text"},{"text":"UIScrollView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"scrollView"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"op":"replace"},{"value":"NewContactRequestController","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/title"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/fragments","value":[{"kind":"identifier","text":"NewContactRequestController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}