{"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController"]]},"metadata":{"modules":[{"name":"EaseChatUIKit"}],"title":"UIScrollViewDelegate Implementations","roleHeading":"API Collection","role":"collectionGroup"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/UIScrollViewDelegate-Implementations"},"sections":[],"topicSections":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/scrollViewDidEndDecelerating(_:)"]}],"variants":[{"paths":["\/documentation\/easechatuikit\/newcontactrequestcontroller\/uiscrollviewdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/easechatuikit\/newcontactrequestcontroller\/uiscrollviewdelegate-implementations"]}],"references":{"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController":{"navigatorTitle":[{"kind":"identifier","text":"NewContactRequestController"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NewContactRequestController","kind":"identifier"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller","title":"NewContactRequestController","abstract":[]},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit":{"title":"EaseChatUIKit","url":"\/documentation\/easechatuikit","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit","role":"collection"},"doc://org.cocoapods.EaseChatUIKit/documentation/EaseChatUIKit/NewContactRequestController/scrollViewDidEndDecelerating(_:)":{"navigatorTitle":[{"kind":"identifier","text":"scrollViewDidEndDecelerating:"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/scrollViewDidEndDecelerating(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"scrollViewDidEndDecelerating","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIScrollView","text":"UIScrollView"},{"text":")","kind":"text"}],"url":"\/documentation\/easechatuikit\/newcontactrequestcontroller\/scrollviewdidenddecelerating(_:)","title":"scrollViewDidEndDecelerating(_:)","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.EaseChatUIKit\/documentation\/EaseChatUIKit\/NewContactRequestController\/scrollViewDidEndDecelerating(_:)"],"generated":true,"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/title","value":"NewContactRequestController"},{"value":[{"text":"NewContactRequestController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController~1scrollViewDidEndDecelerating(_:)\/title","value":"scrollViewDidEndDecelerating:"},{"path":"\/references\/doc:~1~1org.cocoapods.EaseChatUIKit~1documentation~1EaseChatUIKit~1NewContactRequestController~1scrollViewDidEndDecelerating(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"scrollViewDidEndDecelerating:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}